/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import Mathlib.Algebra.Algebra.Subalgebra.Centralizer
public import Mathlib.Algebra.Algebra.Subalgebra.Lattice
public import Mathlib.Algebra.MvPolynomial.Supported
public import Mathlib.Algebra.Ring.GeomSum
public import Mathlib.Data.Finsupp.Interval
public import Mathlib.LinearAlgebra.FiniteDimensional.Basic
public import Mathlib.RingTheory.Finiteness.Basic
public import Mathlib.RingTheory.MvPolynomial.Basic
public import Mathlib.RingTheory.MvPolynomial.WeightedHomogeneous
public import Mathlib.Tactic.LinearCombination
public import HJO.Symmetric.UkRegular
public import HJO.Symmetric.AxisSub
public meta import HJO.Attr

/-! # The axis generators freely generate the ring of symmetric functions

The graded pieces `Lambda_d` of the ring of symmetric functions, and the proof that the axis
substitution `Υ : p_k ↦ U_k` is bijective -- that is, that the axis generators are a free system
of generators of `Lambda L`. The consequence drawn here is the one needed later: as soon as the
collinear slope operators `Q_{ka, kb}`, `k ≥ 1`, pairwise commute, a slope homomorphism at `(a, b)`
exists. That splits the existence of a slope homomorphism into a genuine commutation statement about
the collinear operators and a formal consequence of it.

The grading is the weighted one on `Lambda L = MvPolynomial ℕ L` in which the generator `i`,
standing for `p_{i+1}`, has weight `i + 1`, so `Lambda_d` is
`MvPolynomial.weightedHomogeneousSubmodule` at that weight; `lambdaComp_eq_span` identifies it
with the span of the products of power sums of total degree `d`.
Mathlib supplies the direct-sum decomposition, and the finite dimensionality of each piece is
obtained from Mathlib's basis of a weight fibre once that fibre is seen to be finite: Mathlib's own
finiteness lemma for weight fibres assumes finitely many variables, which fails here, and it is the
unboundedness of the weight `i + 1` that replaces that hypothesis.

Two hypotheses on the parameter `v` (to be read as `q * u`) run through the second half: `v ≠ 0` and
`v ^ k ≠ 1` for every `k ≥ 1`. They are exactly what makes the coefficient of `p_k` in `U_k` nonzero
(`HJO.UkRegular.coeff_single_axisGen_ne_zero`), hence the triangular change of generators
invertible. Over the field `ℚ(q, u)` of coefficients used in §4.1 (Symmetric functions and the slope
homomorphism) of *Rogers-Ramanujan identities from the geometry of `X^a = Y^b`* both hold for
`v = q u`; `v ≠ 0, 1` alone does not suffice, since at `v = -1` the coefficient of `p_2` in `U_2`
vanishes.

The target `Module.End L (Lambda L)` of a slope homomorphism is not commutative, so the free
prescription `p_k ↦ Q_{ka, kb}` is taken into the subalgebra generated by those operators,
which is commutative because a pairwise commuting set adjoins to a subalgebra of its double
centraliser; that is `exists_algHom_of_commute`.
-/

@[expose] public section

open Finset MvPolynomial

namespace HJO.Sym

/-! ### The graded pieces of the ring of symmetric functions -/

section CommRing

variable {K : Type*} [CommRing K]

/-- The graded piece `Lambda_d` of the ring of symmetric functions: the `K`-span of the products
of power sums of total degree `d`. It is the weighted homogeneous submodule of degree `d` for the
weight giving the generator `i`, which stands for `p_{i+1}`, the weight `i + 1`;
`lambdaComp_eq_span` identifies it with the span of products just described. -/
@[hjo "def_lambda_component"]
def LambdaComp (K : Type*) [CommRing K] (d : ℕ) : Submodule K (Lambda K) :=
  weightedHomogeneousSubmodule K (fun i => i + 1) d

/-- Membership in a graded piece is weighted homogeneity: every monomial occurring in `f` has
parts summing to `d`. -/
theorem mem_lambdaComp {d : ℕ} {f : Lambda K} :
    f ∈ LambdaComp K d ↔ IsWeightedHomogeneous (fun i => i + 1) f d := Iff.rfl

/-- **The graded pieces multiply.** For `f ∈ Λ_a` and `g ∈ Λ_b` the product `f * g` lies in
`Λ_{a+b}`: a product of power sums of total degree `a` times one of total degree `b` is a product
of power sums of total degree `a + b`, and the pieces are `K`-subspaces, so the statement passes
to the linear combinations spanning them. -/
@[hjo "lem_ght_component_product"]
theorem mul_mem_lambdaComp {a b : ℕ} {f g : Lambda K} (hf : f ∈ LambdaComp K a)
    (hg : g ∈ LambdaComp K b) : f * g ∈ LambdaComp K (a + b) :=
  mem_lambdaComp.2 ((mem_lambdaComp.1 hf).mul (mem_lambdaComp.1 hg))

/-- **The unit is homogeneous of degree zero.** In the span reading of `lambdaComp_eq_span` it is
the empty product of power sums, whose parts sum to `0`. This is the degree-zero companion of
`mul_mem_lambdaComp`: together they say the grading is multiplicative. -/
theorem one_mem_lambdaComp (K : Type*) [CommRing K] : (1 : Lambda K) ∈ LambdaComp K 0 :=
  mem_lambdaComp.2 (isWeightedHomogeneous_one K _)

/-- A product of power sums, read off an exponent vector: the generator `p_{i+1}` occurs with
exponent `e i`. This is the monomial of `Lambda K` with exponent vector `e`. -/
theorem prod_powerSum_eq_monomial (e : ℕ →₀ ℕ) :
    ∏ i ∈ e.support, powerSum K (i + 1) ^ e i = monomial e (1 : K) := by
  rw [monomial_eq, C_1, one_mul, Finsupp.prod]
  exact Finset.prod_congr rfl fun i _ => by rw [powerSum, Nat.add_sub_cancel]

/-- **The graded piece is the span of the products of power sums of total degree `d`.** This is
the usual description of `Lambda_d`: a product `p_{λ₁} ⋯ p_{λ_ℓ}` with every `λ_i ≥ 1`
and `λ₁ + ⋯ + λ_ℓ = d` is the product below at the exponent vector recording the multiplicities
of the parts, and the total degree of the product is the weighted degree of that vector. -/
@[hjo "def_lambda_component"]
theorem lambdaComp_eq_span (d : ℕ) :
    LambdaComp K d = Submodule.span K {f : Lambda K | ∃ e : ℕ →₀ ℕ,
      Finsupp.weight (fun i => i + 1) e = d ∧
        f = ∏ i ∈ e.support, powerSum K (i + 1) ^ e i} := by
  classical
  refine le_antisymm (fun f hf => ?_) (Submodule.span_le.2 ?_)
  · rw [f.as_sum]
    refine Submodule.sum_mem _ fun e he => ?_
    have hspan : (∏ i ∈ e.support, powerSum K (i + 1) ^ e i) ∈
        Submodule.span K {f : Lambda K | ∃ e : ℕ →₀ ℕ,
          Finsupp.weight (fun i => i + 1) e = d ∧
            f = ∏ i ∈ e.support, powerSum K (i + 1) ^ e i} :=
      Submodule.subset_span ⟨e, mem_lambdaComp.1 hf (mem_support_iff.1 he), rfl⟩
    have hsmul := Submodule.smul_mem _ (coeff e f) hspan
    rwa [prod_powerSum_eq_monomial, smul_eq_C_mul, C_mul_monomial, mul_one] at hsmul
  · rintro f ⟨e, he, rfl⟩
    rw [SetLike.mem_coe, mem_lambdaComp, prod_powerSum_eq_monomial]
    exact isWeightedHomogeneous_monomial _ e 1 he

/-- **The grading.** The ring of symmetric functions is the internal direct sum of its graded
pieces. -/
@[hjo "lem_lambda_component_direct_sum"]
theorem lambdaComp_isInternal : DirectSum.IsInternal (LambdaComp K) := by
  classical
  have : DirectSum.Decomposition (fun d : ℕ => LambdaComp K d) :=
    weightedDecomposition K fun i : ℕ => i + 1
  exact DirectSum.Decomposition.isInternal _

/-! ### Finite dimensionality of the graded pieces -/

/-- The exponent vector dominating every exponent vector of weighted degree `d`: it is `d` at each
of the generators `p_1, …, p_d`, the only ones that can occur, and `0` beyond them. -/
noncomputable def weightBound (d : ℕ) : ℕ →₀ ℕ :=
  Finsupp.onFinset (Finset.range d) (fun i => if i < d then d else 0) fun i hi => by
    simp only [Finset.mem_range]
    by_contra h
    simp [h] at hi

/-- **Finitely many monomials of a given degree.** Only the generators `p_1, …, p_d` can occur
in a monomial of total degree `d`, and each with exponent at most `d`, so the exponent vectors of
weighted degree `d` are dominated by `weightBound d` and hence finite in number. Mathlib's
`Finsupp.finite_of_nat_weight_eq` assumes finitely many variables; here it is the unboundedness of
the weight `i + 1` that bounds the variables instead. -/
theorem finite_weight_eq (d : ℕ) :
    {e : ℕ →₀ ℕ | Finsupp.weight (fun i => i + 1) e = d}.Finite := by
  classical
  refine Set.Finite.subset (Finset.Iic (weightBound d)).finite_toSet fun e he => ?_
  have he' : Finsupp.weight (fun i => i + 1) e = d := he
  refine Finset.mem_coe.2 (Finset.mem_Iic.2 ((Finsupp.le_iff e _).2 fun i hi => ?_))
  have h1 := Finsupp.le_weight_of_ne_zero' (w := fun j : ℕ => j + 1)
    (Finsupp.mem_support_iff.1 hi)
  have h2 := Finsupp.le_weight (fun j : ℕ => j + 1) (s := i) (Nat.succ_ne_zero i) e
  rw [he'] at h1 h2
  rw [weightBound, Finsupp.onFinset_apply]
  split_ifs with h
  · exact h2
  · omega

/-- Each graded piece is finitely generated: it has a basis indexed by the exponent vectors of
weighted degree `d`, and there are finitely many of those. -/
theorem lambdaComp_fg (K : Type*) [CommRing K] (d : ℕ) : (LambdaComp K d).FG := by
  classical
  rw [LambdaComp, weightedHomogeneousSubmodule_eq_finsupp_supported, ← Module.Finite.iff_fg]
  have := (finite_weight_eq d).to_subtype
  exact Module.Finite.of_basis
    (basisRestrictSupport K {e : ℕ →₀ ℕ | Finsupp.weight (fun i => i + 1) e = d})

/-- A symmetric function is the sum of its graded components, over the finite range cut off by its
weighted total degree. -/
theorem sum_weightedHomogeneousComponent_range (f : Lambda K) :
    ∑ N ∈ Finset.range (weightedTotalDegree (fun i => i + 1) f + 1),
      weightedHomogeneousComponent (fun i => i + 1) N f = f := by
  classical
  ext e
  rw [coeff_sum]
  by_cases he : coeff e f = 0
  · rw [he, Finset.sum_eq_zero]
    intro N _
    rw [coeff_weightedHomogeneousComponent]
    split_ifs <;> simp [he]
  · have hmem : Finsupp.weight (fun i => i + 1) e ∈
        Finset.range (weightedTotalDegree (fun i => i + 1) f + 1) := by
      rw [Finset.mem_range, Nat.lt_succ_iff]
      exact le_weightedTotalDegree _ (mem_support_iff.2 he)
    rw [Finset.sum_eq_single_of_mem _ hmem]
    · rw [coeff_weightedHomogeneousComponent]
      split_ifs with h
      · rfl
      · exact absurd rfl h
    · intro N _ hN
      rw [coeff_weightedHomogeneousComponent]
      split_ifs with h
      · exact absurd h.symm hN
      · rfl

/-- **A degree-shifting linear endomorphism commutes with taking a graded component**, up to the
shift. A symmetric function is the sum of its components, and the image of the component of degree
`N` is homogeneous of degree `N + c`, so only the summand `N = d` survives the projection to degree
`d + c`.

The shift is a free parameter of the argument, and both readings of it are used: the
grade-preserving case `c = 0` is `weightedHomogeneousComponent_of_mem_lambdaComp` below, and for an
operator raising degree by `c` the hypothesis is what `HJO.Sym.ShiftsDegree.apply_mem_lambdaComp`
delivers. -/
theorem weightedHomogeneousComponent_of_mem_lambdaComp_add (Φ : Lambda K →ₗ[K] Lambda K) {c : ℕ}
    (hgr : ∀ (d : ℕ) (f : Lambda K), f ∈ LambdaComp K d → Φ f ∈ LambdaComp K (d + c)) (d : ℕ)
    (f : Lambda K) :
    weightedHomogeneousComponent (fun i => i + 1) (d + c) (Φ f)
      = Φ (weightedHomogeneousComponent (fun i => i + 1) d f) := by
  classical
  have hmem : ∀ N : ℕ, IsWeightedHomogeneous (fun i => i + 1)
      (Φ (weightedHomogeneousComponent (fun i => i + 1) N f)) (N + c) := fun N =>
    mem_lambdaComp.1 (hgr N _ (weightedHomogeneousComponent_mem _ f N))
  conv_lhs => rw [← sum_weightedHomogeneousComponent_range f]
  rw [map_sum, map_sum]
  by_cases hd : d ∈ Finset.range (weightedTotalDegree (fun i => i + 1) f + 1)
  · rw [Finset.sum_eq_single_of_mem d hd]
    · exact (hmem d).weightedHomogeneousComponent_same
    · intro N _ hN
      exact (hmem N).weightedHomogeneousComponent_ne (d + c) (by omega)
  · rw [Finset.mem_range, Nat.lt_succ_iff, Nat.not_le] at hd
    rw [weightedHomogeneousComponent_eq_zero _ f hd, map_zero, Finset.sum_eq_zero]
    intro N hN
    rw [Finset.mem_range, Nat.lt_succ_iff] at hN
    exact (hmem N).weightedHomogeneousComponent_ne (d + c) (by omega)

/-- **A grade-preserving linear endomorphism commutes with taking a graded component**, the shift
zero case of `weightedHomogeneousComponent_of_mem_lambdaComp_add`. -/
theorem weightedHomogeneousComponent_of_mem_lambdaComp (Φ : Lambda K →ₗ[K] Lambda K)
    (hgr : ∀ (d : ℕ) (f : Lambda K), f ∈ LambdaComp K d → Φ f ∈ LambdaComp K d) (d : ℕ)
    (f : Lambda K) :
    weightedHomogeneousComponent (fun i => i + 1) d (Φ f)
      = Φ (weightedHomogeneousComponent (fun i => i + 1) d f) := by
  simpa using weightedHomogeneousComponent_of_mem_lambdaComp_add Φ (c := 0)
    (by simpa using hgr) d f

end CommRing

/-- **The graded pieces are finite dimensional.** -/
@[hjo "lem_lambda_component_findim"]
theorem lambdaComp_finiteDimensional (L : Type*) [Field L] (d : ℕ) :
    FiniteDimensional L (LambdaComp L d) :=
  Module.Finite.iff_fg.2 (lambdaComp_fg L d)

/-! ### The complete homogeneous functions and the axis generators are homogeneous -/

section CommRing

variable {K : Type*} [CommRing K]

/-- **The complete homogeneous function `h_n` is homogeneous of degree `n`.** Newton's identity
writes `h_n` as a combination of the products `p_k h_{n-k}`, whose parts sum to `n`. -/
@[hjo "lem_hsymm_component"]
theorem completeHomog_mem_lambdaComp (K : Type*) [CommRing K] [Algebra ℚ K] (n : ℕ) :
    completeHomog K n ∈ LambdaComp K n := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    match n with
    | 0 => rw [UkRegular.completeHomog_zero]; exact one_mem_lambdaComp K
    | m + 1 =>
      rw [UkRegular.completeHomog_succ, mem_lambdaComp]
      refine IsWeightedHomogeneous.C_mul (IsWeightedHomogeneous.sum _ _ _ fun k hk => ?_) _
      rw [Finset.mem_range, Nat.lt_succ_iff] at hk
      have h1 : IsWeightedHomogeneous (fun i => i + 1) (powerSum K (k + 1)) (k + 1) := by
        rw [powerSum, Nat.add_sub_cancel]
        exact isWeightedHomogeneous_X K _ k
      have h2 : IsWeightedHomogeneous (fun i => i + 1) (completeHomog K (m - k)) (m - k) :=
        mem_lambdaComp.1 (ih (m - k) (by omega))
      have h3 : k + 1 + (m - k) = m + 1 := by omega
      exact h3 ▸ h1.mul h2

/-- A diagonal substitution preserves each graded piece: it multiplies each monomial by a scalar
and creates no new monomial. -/
theorem diagScale_mem_lambdaComp (c : ℕ → K) {d : ℕ} {f : Lambda K}
    (hf : f ∈ LambdaComp K d) : diagScale c f ∈ LambdaComp K d := by
  rw [mem_lambdaComp] at hf ⊢
  intro e he
  rw [UkRegular.coeff_diagScale] at he
  exact hf (right_ne_zero_of_mul he)

/-- An exponent vector of weighted degree `k` in which a generator of weight at least `k` occurs is
the exponent vector of `p_k` itself: that generator's weight already exhausts the degree, so it
occurs exactly once and nothing else occurs. -/
theorem eq_single_of_weight_eq {e : ℕ →₀ ℕ} {k i : ℕ}
    (he : Finsupp.weight (fun i => i + 1) e = k) (hi : e i ≠ 0) (hik : k ≤ i + 1) :
    e = Finsupp.single (k - 1) 1 := by
  classical
  have hmem : i ∈ e.support := Finsupp.mem_support_iff.2 hi
  have hik' := Finsupp.le_weight_of_ne_zero' (w := fun j : ℕ => j + 1) hi
  rw [he] at hik'
  have hik2 : i + 1 = k := by omega
  have hsum : ∑ j ∈ e.support, e j * (j + 1) = k := by
    rw [← he, Finsupp.weight_apply, Finsupp.sum]
    exact Finset.sum_congr rfl fun j _ => by rw [smul_eq_mul]
  have hle : e i * (i + 1) ≤ k := by
    rw [← hsum]
    exact Finset.single_le_sum (f := fun j => e j * (j + 1)) (fun j _ => Nat.zero_le _) hmem
  have hei : e i = 1 := by
    rcases Nat.lt_or_ge (e i) 2 with h | h
    · omega
    · exfalso
      have h2 : 2 * k ≤ e i * (i + 1) := by
        rw [hik2]
        exact Nat.mul_le_mul_right k h
      omega
  have herase : ∑ j ∈ e.support.erase i, e j * (j + 1) = 0 := by
    have h := Finset.add_sum_erase e.support (fun j => e j * (j + 1)) hmem
    rw [hsum, hei, one_mul, hik2] at h
    omega
  have hsupp : e.support ⊆ {i} := by
    intro j hj
    rw [Finset.mem_singleton]
    by_contra hji
    have hjm : j ∈ e.support.erase i := Finset.mem_erase.2 ⟨hji, hj⟩
    have hzero := Finset.sum_eq_zero_iff.1 herase j hjm
    rcases Nat.mul_eq_zero.1 hzero with h0 | h0
    · exact Finsupp.mem_support_iff.1 hj h0
    · omega
  rw [Finsupp.support_subset_singleton.1 hsupp, hei, ← hik2, Nat.add_sub_cancel]

/-- **The subalgebra generated by `p_1, …, p_{k-1}`** is the subalgebra of symmetric functions
involving only those generators: `p_j` is the variable `j - 1`, so the parts `< k` are exactly the
variables `i` with `i + 1 < k`. -/
theorem adjoin_powerSum_eq_supported (K : Type*) [CommRing K] (k : ℕ) :
    Algebra.adjoin K (powerSum K '' Set.Ico 1 k) = supported K {i : ℕ | i + 1 < k} := by
  rw [supported_eq_adjoin_X]
  congr 1
  ext f
  constructor
  · rintro ⟨j, ⟨hj1, hjk⟩, rfl⟩
    exact ⟨j - 1, show j - 1 + 1 < k by omega, by rw [powerSum]⟩
  · rintro ⟨i, hi, rfl⟩
    have hi' : i + 1 < k := hi
    exact ⟨i + 1, ⟨by omega, by omega⟩, by rw [powerSum, Nat.add_sub_cancel]⟩

end CommRing

section Field

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- **The axis generator `U_k` is homogeneous of degree `k`.** The axis alphabet is a diagonal
substitution, so it does not move a monomial off its degree, and `h_k` is homogeneous of degree
`k`. No hypothesis on `k` is needed: at `k = 0` the generator is the constant
`v / (v - 1)`, homogeneous of degree `0`. -/
@[hjo "lem_axis_component"]
theorem axisGen_mem_lambdaComp (v : L) (k : ℕ) : axisGen v k ∈ LambdaComp L k := by
  rw [axisGen, plethAxis_eq_diagScale, mem_lambdaComp]
  exact IsWeightedHomogeneous.C_mul
    (mem_lambdaComp.1 (diagScale_mem_lambdaComp _ (completeHomog_mem_lambdaComp L k))) _

/-- **The coefficient of `p_k` in `U_k`, in closed form.** For `k ≥ 1` and `v ≠ 0, 1` it is
`-(1 + v + ⋯ + v ^ (k - 1)) / (k v ^ (k - 1))`. Only the linear term `p_k / k` of `h_k`
contributes, the axis alphabet multiplies `p_k` by `v ^ (-k) - 1`, and the prefactor is
`v / (v - 1)`; the geometric-sum form is that product rewritten by
`v ^ k - 1 = (v - 1)(1 + v + ⋯ + v ^ (k - 1))`. At the totalized points `v = 0, 1` the generator
`U_k` vanishes and the displayed fraction does not describe it. -/
@[hjo "lem_axis_lead_formula"]
theorem coeff_single_axisGen_eq_geom [CharZero L] {v : L} (hv0 : v ≠ 0) (hv1 : v ≠ 1) {k : ℕ}
    (hk : 1 ≤ k) :
    coeff (Finsupp.single (k - 1) 1) (axisGen v k) =
      -((∑ i ∈ Finset.range k, v ^ i) / ((k : L) * v ^ (k - 1))) := by
  obtain ⟨m, rfl⟩ : ∃ m, k = m + 1 := ⟨k - 1, by omega⟩
  have hsub : v - 1 ≠ 0 := sub_ne_zero_of_ne hv1
  have hpow : v ^ m ≠ 0 := pow_ne_zero m hv0
  have hcast : ((m : L) + 1) ≠ 0 := by
    have : ((m + 1 : ℕ) : L) ≠ 0 := Nat.cast_ne_zero.2 (Nat.succ_ne_zero m)
    push_cast at this
    exact this
  have hgeom : (∑ i ∈ Finset.range (m + 1), v ^ i) * (v - 1) = v ^ (m + 1) - 1 :=
    geom_sum_mul v (m + 1)
  have hpow' : v ^ (m + 1) ≠ 0 := pow_ne_zero _ hv0
  have hkey : (v ^ (m + 1))⁻¹ - 1 =
      -((v - 1) * ∑ i ∈ Finset.range (m + 1), v ^ i) / v ^ (m + 1) := by
    field_simp
    linear_combination hgeom
  rw [Nat.add_sub_cancel, UkRegular.coeff_single_axisGen, hkey, pow_succ]
  push_cast
  field_simp

/-- **The coefficient of `p_k` in `U_k` is nonzero** at a parameter that is nonzero and not a root
of unity: the geometric sum `1 + v + ⋯ + v ^ (k - 1)` is `(v ^ k - 1) / (v - 1)`, and
`v ^ k ≠ 1`. -/
@[hjo "lem_axis_lead_ne_zero"]
theorem coeff_single_axisGen_ne_zero [CharZero L] {v : L} (hv0 : v ≠ 0)
    (hv1 : ∀ j : ℕ, v ^ (j + 1) ≠ 1) {k : ℕ} (hk : 1 ≤ k) :
    coeff (Finsupp.single (k - 1) 1) (axisGen v k) ≠ 0 :=
  (UkRegular.coeff_single_axisGen_ne_zero hv0 hv1 hk).2

/-- **The axis generator is triangular.** Removing from `U_k` its `p_k` term leaves an element of
the subalgebra generated by `p_1, …, p_{k-1}`: `U_k` is homogeneous of degree `k`, and the only
monomial of degree `k` with a part equal to `k` is `p_k` itself. No hypothesis on `k` is needed:
at `k = 0` both terms are scalars and the statement is trivially true. -/
@[hjo "lem_axis_sub_linear"]
theorem axisGen_sub_mem_adjoin (v : L) (k : ℕ) :
    axisGen v k - C (coeff (Finsupp.single (k - 1) 1) (axisGen v k)) * powerSum L k ∈
      Algebra.adjoin L (powerSum L '' Set.Ico 1 k) := by
  classical
  rw [adjoin_powerSum_eq_supported, mem_supported]
  intro i hi
  obtain ⟨e, he, hie⟩ := (mem_vars_iff_mem_support i).1 (Finset.mem_coe.1 hi)
  change i + 1 < k
  by_contra hik
  rw [Nat.not_lt] at hik
  rw [mem_support_iff, coeff_sub, powerSum, C_mul_X_eq_monomial, coeff_monomial] at he
  split_ifs at he with hee
  · rw [← hee, sub_self] at he
    exact he rfl
  · rw [sub_zero] at he
    exact hee (eq_single_of_weight_eq (mem_lambdaComp.1 (axisGen_mem_lambdaComp v k) he)
      (Finsupp.mem_support_iff.1 hie) hik).symm

/-! ### The axis substitution is bijective -/

omit [Algebra ℚ L] in
/-- **A triangular family generates.** If a subalgebra `A` contains, for every `k ≥ 1`, an element
whose `p_k` term has nonzero coefficient and whose remaining terms involve only `p_1, …, p_{k-1}`,
then `A` is everything: strong induction on `k` puts `p_k` in `A`, and the `p_k` generate. -/
@[hjo "lem_triangular_generates"]
theorem eq_top_of_triangular {A : Subalgebra L (Lambda L)}
    (h : ∀ k : ℕ, 1 ≤ k → ∃ g ∈ A, ∃ c : L, c ≠ 0 ∧
      g - C c * powerSum L k ∈ Algebra.adjoin L (powerSum L '' Set.Ico 1 k)) :
    A = ⊤ := by
  have hp : ∀ k : ℕ, 1 ≤ k → powerSum L k ∈ A := by
    intro k
    induction k using Nat.strong_induction_on with
    | _ k ih =>
      intro hk
      obtain ⟨g, hgA, c, hc, hmem⟩ := h k hk
      have hle : Algebra.adjoin L (powerSum L '' Set.Ico 1 k) ≤ A := by
        rw [Algebra.adjoin_le_iff]
        rintro f ⟨j, ⟨hj1, hjk⟩, rfl⟩
        exact ih j hjk hj1
      have hcp : C c * powerSum L k ∈ A := by
        have hd := sub_mem hgA (hle hmem)
        rwa [sub_sub_cancel] at hd
      have hCinv : C c⁻¹ ∈ A := by
        rw [← algebraMap_eq]
        exact A.algebraMap_mem c⁻¹
      have hsplit : powerSum L k = C c⁻¹ * (C c * powerSum L k) := by
        rw [← mul_assoc, ← C_mul, inv_mul_cancel₀ hc, C_1, one_mul]
      rw [hsplit]
      exact mul_mem hCinv hcp
  rw [eq_top_iff, ← adjoin_range_X, Algebra.adjoin_le_iff]
  rintro f ⟨i, rfl⟩
  have hX : (X i : Lambda L) = powerSum L (i + 1) := by rw [powerSum, Nat.add_sub_cancel]
  rw [hX]
  exact hp (i + 1) (by omega)

/-- **The axis generators generate.** At a parameter that is nonzero and not a root of unity the
axis generators form a triangular family, so they generate the whole ring of symmetric
functions. -/
@[hjo "lem_axis_generates"]
theorem adjoin_axisGen_eq_top [CharZero L] {v : L} (hv0 : v ≠ 0)
    (hv1 : ∀ j : ℕ, v ^ (j + 1) ≠ 1) :
    Algebra.adjoin L (axisGen v '' Set.Ici 1) = ⊤ :=
  eq_top_of_triangular fun k hk => ⟨axisGen v k, Algebra.subset_adjoin ⟨k, hk, rfl⟩,
    coeff (Finsupp.single (k - 1) 1) (axisGen v k),
    coeff_single_axisGen_ne_zero hv0 hv1 hk, axisGen_sub_mem_adjoin v k⟩

/-- **The axis substitution is surjective.** Its image is a subalgebra containing every axis
generator, and those generate. -/
@[hjo "lem_axis_sub_surj"]
theorem axisSub_surjective [CharZero L] {v : L} (hv0 : v ≠ 0)
    (hv1 : ∀ j : ℕ, v ^ (j + 1) ≠ 1) : Function.Surjective (axisSub v) := by
  have hrange : (axisSub v).range = ⊤ := by
    rw [eq_top_iff, ← adjoin_axisGen_eq_top hv0 hv1, Algebra.adjoin_le_iff]
    rintro f ⟨k, hk, rfl⟩
    exact ⟨powerSum L k, axisSub_powerSum v hk⟩
  intro f
  have hf : f ∈ (axisSub v).range := by rw [hrange]; exact Algebra.mem_top
  exact hf

/-- **The axis substitution is graded.** It sends a monomial of degree `d` to the product of the
matching axis generators, whose degrees add up to `d` again. -/
@[hjo "lem_axis_sub_graded"]
theorem axisSub_mem_lambdaComp (v : L) {d : ℕ} {f : Lambda L} (hf : f ∈ LambdaComp L d) :
    axisSub v f ∈ LambdaComp L d := by
  classical
  refine IsWeightedHomogeneous.induction_on
    (motive := fun p _ => axisSub v p ∈ LambdaComp L d) ?_ ?_ ?_ (mem_lambdaComp.1 hf)
  · rw [map_zero]
    exact zero_mem _
  · intro p q _ _ hp hq
    rw [map_add]
    exact add_mem hp hq
  · intro e r hr
    rw [mem_lambdaComp, monomial_eq, map_mul, algHom_C, algebraMap_eq]
    refine IsWeightedHomogeneous.C_mul ?_ r
    rw [Finsupp.prod, map_prod, ← hr, Finsupp.weight_apply, Finsupp.sum]
    refine IsWeightedHomogeneous.prod _ _ _ fun i _ => ?_
    rw [map_pow, axisSub_X]
    exact (mem_lambdaComp.1 (axisGen_mem_lambdaComp v (i + 1))).pow (e i)

/-- The axis substitution commutes with taking a graded component: it preserves each graded piece,
so `weightedHomogeneousComponent_of_mem_lambdaComp` applies to it. -/
theorem weightedHomogeneousComponent_axisSub (v : L) (d : ℕ) (f : Lambda L) :
    weightedHomogeneousComponent (fun i => i + 1) d (axisSub v f) =
      axisSub v (weightedHomogeneousComponent (fun i => i + 1) d f) :=
  weightedHomogeneousComponent_of_mem_lambdaComp (axisSub v).toLinearMap
    (fun _ _ hf => axisSub_mem_lambdaComp v hf) d f

/-- The axis substitution restricted to a graded piece, a linear endomorphism of that piece. -/
noncomputable def axisSubComp (v : L) (d : ℕ) : LambdaComp L d →ₗ[L] LambdaComp L d :=
  (axisSub v).toLinearMap.restrict fun _ hf => axisSub_mem_lambdaComp v hf

/-- The restriction of the axis substitution to a graded piece, on elements. -/
theorem axisSubComp_coe (v : L) (d : ℕ) (f : LambdaComp L d) :
    (axisSubComp v d f : Lambda L) = axisSub v f := rfl

/-- **Degreewise surjectivity.** A homogeneous symmetric function of degree `d` is the image of a
homogeneous one of the same degree: take the degree `d` component of any preimage. -/
@[hjo "lem_axis_sub_surj_component"]
theorem exists_mem_lambdaComp_axisSub_eq [CharZero L] {v : L} (hv0 : v ≠ 0)
    (hv1 : ∀ j : ℕ, v ^ (j + 1) ≠ 1) (d : ℕ) {f : Lambda L} (hf : f ∈ LambdaComp L d) :
    ∃ g ∈ LambdaComp L d, axisSub v g = f := by
  obtain ⟨h, hh⟩ := axisSub_surjective hv0 hv1 f
  refine ⟨weightedHomogeneousComponent (fun i => i + 1) d h,
    weightedHomogeneousComponent_mem _ h d, ?_⟩
  rw [← weightedHomogeneousComponent_axisSub, hh]
  exact (mem_lambdaComp.1 hf).weightedHomogeneousComponent_same

/-- The restriction of the axis substitution to a graded piece is surjective. -/
theorem axisSubComp_surjective [CharZero L] {v : L} (hv0 : v ≠ 0)
    (hv1 : ∀ j : ℕ, v ^ (j + 1) ≠ 1) (d : ℕ) : Function.Surjective (axisSubComp v d) := by
  rintro ⟨f, hf⟩
  obtain ⟨g, hg, hgf⟩ := exists_mem_lambdaComp_axisSub_eq hv0 hv1 d hf
  exact ⟨⟨g, hg⟩, Subtype.ext hgf⟩

/-- **Degreewise injectivity.** On a graded piece the axis substitution is a surjective linear
endomorphism of a finite-dimensional space, hence injective. -/
@[hjo "lem_axis_sub_inj_component"]
theorem eq_zero_of_mem_lambdaComp_of_axisSub_eq_zero [CharZero L] {v : L} (hv0 : v ≠ 0)
    (hv1 : ∀ j : ℕ, v ^ (j + 1) ≠ 1) (d : ℕ) {g : Lambda L} (hg : g ∈ LambdaComp L d)
    (h0 : axisSub v g = 0) : g = 0 := by
  have := lambdaComp_finiteDimensional L d
  have hinj : Function.Injective (axisSubComp v d) :=
    LinearMap.injective_iff_surjective.2 (axisSubComp_surjective hv0 hv1 d)
  have hval : axisSubComp v d ⟨g, hg⟩ = axisSubComp v d 0 := by
    rw [map_zero]
    exact Subtype.ext h0
  simpa using Subtype.ext_iff.1 (hinj hval)

/-- **The axis substitution is injective.** Each graded component of an element of its kernel is
again in the kernel, and there it vanishes by degreewise injectivity. -/
@[hjo "lem_axis_sub_inj"]
theorem axisSub_injective [CharZero L] {v : L} (hv0 : v ≠ 0)
    (hv1 : ∀ j : ℕ, v ^ (j + 1) ≠ 1) : Function.Injective (axisSub v) := by
  refine (injective_iff_map_eq_zero (axisSub v)).2 fun h hh => ?_
  have hcomp : ∀ N : ℕ, weightedHomogeneousComponent (fun i => i + 1) N h = 0 := by
    intro N
    refine eq_zero_of_mem_lambdaComp_of_axisSub_eq_zero hv0 hv1 N
      (weightedHomogeneousComponent_mem _ h N) ?_
    rw [← weightedHomogeneousComponent_axisSub, hh, map_zero]
  rw [← sum_weightedHomogeneousComponent_range h, Finset.sum_eq_zero fun N _ => hcomp N]

/-- **The axis generators freely generate.** At a parameter that is nonzero and not a root of
unity the axis substitution is bijective, so the axis generators are a free system of generators
of the ring of symmetric functions. -/
@[hjo "lem_axis_free"]
theorem axisSub_bijective [CharZero L] {v : L} (hv0 : v ≠ 0)
    (hv1 : ∀ j : ℕ, v ^ (j + 1) ≠ 1) : Function.Bijective (axisSub v) :=
  ⟨axisSub_injective hv0 hv1, axisSub_surjective hv0 hv1⟩

/-! ### A slope homomorphism exists once the collinear operators commute -/

omit [Algebra ℚ L] in
/-- A pairwise commuting family in a possibly noncommutative algebra prescribes an algebra
homomorphism out of the ring of symmetric functions: the subalgebra it generates lies in the double
centraliser of the family, hence is commutative, and the polynomial algebra maps freely into
that. -/
theorem exists_algHom_of_commute {E : Type*} [Ring E] [Algebra L E] (T : ℕ → E)
    (h : ∀ i j : ℕ, Commute (T i) (T j)) :
    ∃ Ψ : Lambda L →ₐ[L] E, ∀ i : ℕ, Ψ (X i) = T i := by
  classical
  have h1 : Algebra.adjoin L (Set.range T) ≤ Subalgebra.centralizer L (Set.range T) := by
    rw [Algebra.adjoin_le_iff]
    rintro z ⟨i, rfl⟩
    refine (Subalgebra.mem_centralizer_iff L).2 ?_
    rintro w ⟨j, rfl⟩
    exact h j i
  have h2 : Algebra.adjoin L (Set.range T) ≤
      Subalgebra.centralizer L (Subalgebra.centralizer L (Set.range T) : Set E) :=
    Algebra.adjoin_le_centralizer_centralizer L (Set.range T)
  have hcomm : ∀ x ∈ Algebra.adjoin L (Set.range T), ∀ y ∈ Algebra.adjoin L (Set.range T),
      Commute x y := fun x hx y hy =>
    ((Subalgebra.mem_centralizer_iff L).1 (h2 hx) y (h1 hy)).symm
  let _inst : CommRing (Algebra.adjoin L (Set.range T)) :=
    { (inferInstance : Ring (Algebra.adjoin L (Set.range T))) with
      mul_comm := fun x y => Subtype.ext (hcomm x x.2 y y.2) }
  refine ⟨(Subalgebra.val (Algebra.adjoin L (Set.range T))).comp
    (MvPolynomial.aeval fun i => (⟨T i, Algebra.subset_adjoin ⟨i, rfl⟩⟩ :
      Algebra.adjoin L (Set.range T))), fun i => ?_⟩
  simp

/-- **A slope homomorphism exists once the collinear operators commute.** The commuting operators
`Q_{ka, kb}`, `k ≥ 1`, prescribe an algebra homomorphism `Ψ : p_k ↦ Q_{ka, kb}`, and composing
it with the inverse of the axis substitution gives an algebra homomorphism sending `U_k` to
`Q_{ka, kb}`, that is, a slope homomorphism at `(a, b)`.

The paper states this (§4.1) at its fixed coprime pair `(a, b)`; neither coprimality nor positivity
enters the argument, so neither is assumed. What is assumed, and is implicit in the paper's base
field `ℚ(q, u)`, is that `v = q u` is nonzero and not a root of unity: that is what makes the axis
substitution invertible. -/
@[hjo "prop_slope_hom_exists"]
theorem exists_isSlopeHom [CharZero L] {a b : ℕ} {q u : L} (hv0 : q * u ≠ 0)
    (hv1 : ∀ j : ℕ, (q * u) ^ (j + 1) ≠ 1)
    (hcomm : ∀ k l : ℕ, 0 < k → 0 < l →
      Commute (Qop q u (a * k) (b * k)) (Qop q u (a * l) (b * l))) :
    ∃ Θ : Lambda L →ₐ[L] Module.End L (Lambda L), IsSlopeHom a b q u Θ := by
  obtain ⟨Ψ, hΨ⟩ := exists_algHom_of_commute (L := L)
    (fun i : ℕ => Qop q u (a * (i + 1)) (b * (i + 1)))
    fun i j => hcomm (i + 1) (j + 1) (Nat.succ_pos i) (Nat.succ_pos j)
  refine ⟨Ψ.comp (AlgEquiv.ofBijective (axisSub (q * u))
    (axisSub_bijective hv0 hv1)).symm.toAlgHom, ?_⟩
  intro k hk
  obtain ⟨m, rfl⟩ : ∃ m, k = m + 1 := ⟨k - 1, by omega⟩
  have hsymm : (AlgEquiv.ofBijective (axisSub (q * u)) (axisSub_bijective hv0 hv1)).symm
      (axisGen (q * u) (m + 1)) = X m := by
    rw [AlgEquiv.symm_apply_eq]
    exact (axisSub_X (q * u) m).symm
  change Ψ ((AlgEquiv.ofBijective (axisSub (q * u)) (axisSub_bijective hv0 hv1)).symm
    (axisGen (q * u) (m + 1))) = _
  rw [hsymm, hΨ]

end Field

end HJO.Sym
