/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.CarlssonMellit.DPATilde
public meta import HJO.Attr

/-! # The two ideals of `Ã`, and the arrow degree

The structure theorem for `Ã` names two submodules and one grading: the left ideal `I` generated by
`d₊^*d₊^m - d₊^{m+1}`, the left submodule `𝓘` of `Ã𝟏_0` that the structure theorem identifies with
the kernel of `Ã𝟏_0 → V_*`, and the arrow degree, which counts arrows and ignores loops. This file
defines all three.

## Main definitions

* `HJO.Dyck.Tilde.Atilde.dPlusPow`, `HJO.Dyck.Tilde.Atilde.dPlusStarPow`: the words `d₊^m` and
  `d₊^{*m}` of raising arrows out of a vertex.
* `HJO.Dyck.Tilde.Atilde.kernelIdeal`: the left ideal `I`.
* `HJO.Dyck.Tilde.Atilde.mellitKernel`: the left submodule `𝓘` of `Ã𝟏_0`.
* `HJO.Dyck.Tilde.arrowDeg`, `HJO.Dyck.Tilde.arrowDegWord`: the arrow degree of a generator and of
  a word.

## Main results

* `HJO.Dyck.Tilde.Atilde.dPlusStarPow_sub_dPlusPow_mem_kernelIdeal`:
  `HJO.Dyck.Tilde.Atilde.dPlusStarPow_sub_dPlusPow_mem_kernelIdeal`, that `d₊^{*m} - d₊^{m}` lies in
  `I`.

## Implementation notes

`Ideal R` is `Submodule R R`, the *left* ideal notion, which is what both `I` and `𝓘` are. `𝓘` is
described in the paper as a submodule of `Ã𝟏_0` rather than of `Ã`; every one of its generators
ends in `𝟏_0` — `dPlusStarPow 0 k` has the idempotent `e_0` as its empty product — so the span
taken in `Ã` already lies in `Ã𝟏_0`, and taking it there costs nothing and avoids carrying a
module structure over a subobject.

The paper writes `d₊^*d₊^m - d₊^{m+1}` with no vertex, and here every such element is read at
the vertex where its paths begin, so `I` is generated over *all* starting vertices `v`.
That is not a choice between two different ideals as far as the consumers are concerned: a
generator starting at `v ≠ 0` is killed by `e_0` on the right, so `I𝟏_0` — the only thing the
structure theorem reads — is the same whichever way the family is indexed.

The empty word of raising arrows is the idempotent at the vertex, not `1`, as throughout: the unit
of `Ã` is not in the span of the idempotents. So `dPlusStarPow 0 0` is `e_0` and the `k = 0`
generators of `𝓘` are `d₋d₊^* - 𝟏_0` and `d₊ + y_1d₊^*` with their trailing idempotent already in
place.

## References

Definitions `HJO.Dyck.Tilde.Atilde.kernelIdeal`, `HJO.Dyck.Tilde.Atilde.mellitKernel` and
`HJO.Dyck.Tilde.arrowDeg`; E. Carlsson and A. Mellit, *A proof of
the shuffle conjecture*, J. Amer. Math. Soc. **31** (2018) 661--697, Section 3.
-/

@[expose] public section

namespace HJO.Dyck.Tilde

/-! ### The arrow degree -/

/-- **The arrow degree of a generator**: `1` on each of the three arrows `d₊`, `d₊^*` and `d₋`,
and `0` on each loop `T_i` and each idempotent. -/
@[hjo "def_cm_arrow_degree"]
def arrowDeg : Gen → ℕ
  | .vertex _ => 0
  | .up _ => 1
  | .upStar _ => 1
  | .down _ => 1
  | .braid _ _ => 0

/-- **The arrow degree of a word**: the number of arrow letters in it, the loops and idempotents
contributing nothing. -/
@[hjo "def_cm_arrow_degree"]
def arrowDegWord (w : List Gen) : ℕ := (w.map arrowDeg).sum

@[simp] theorem arrowDegWord_nil : arrowDegWord [] = 0 := rfl

@[simp] theorem arrowDegWord_cons (g : Gen) (w : List Gen) :
    arrowDegWord (g :: w) = arrowDeg g + arrowDegWord w := rfl

@[simp] theorem arrowDegWord_append (v w : List Gen) :
    arrowDegWord (v ++ w) = arrowDegWord v + arrowDegWord w := by
  simp [arrowDegWord, List.sum_append]

namespace Atilde

variable {K : Type*} [CommRing K] {q u : K} [Invertible q] [Invertible (q - 1)]

/-! ### The incidence of the two raising arrows -/

@[simp]
theorem e_mul_dPlus (k : ℕ) : e K q u (k + 1) * dPlus K q u k = dPlus K q u k :=
  eq_of_sourceRel (SourceRel.vertex_mul_up k)

@[simp]
theorem dPlus_mul_e (k : ℕ) : dPlus K q u k * e K q u k = dPlus K q u k :=
  eq_of_sourceRel (SourceRel.up_mul_vertex k)

@[simp]
theorem e_mul_dPlusStar (k : ℕ) : e K q u (k + 1) * dPlusStar K q u k = dPlusStar K q u k :=
  eq_of_sourceRelStar (SourceRel.vertex_mul_up k)

@[simp]
theorem dPlusStar_mul_e (k : ℕ) : dPlusStar K q u k * e K q u k = dPlusStar K q u k :=
  eq_of_sourceRelStar (SourceRel.up_mul_vertex k)

/-! ### The words of raising arrows -/

/-- The word `d₊^m` of raising arrows from the vertex `v` to the vertex `v + m`, the empty word
being the idempotent `e_v`. -/
noncomputable def dPlusPow (K : Type*) [CommRing K] (q u : K) [Invertible q] [Invertible (q - 1)]
    (v : ℕ) : ℕ → Atilde K q u
  | 0 => e K q u v
  | m + 1 => dPlus K q u (v + m) * dPlusPow K q u v m

/-- The word `d₊^{*m}` of starred raising arrows from the vertex `v` to the vertex `v + m`, the
empty word being the idempotent `e_v`. -/
noncomputable def dPlusStarPow (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] (v : ℕ) : ℕ → Atilde K q u
  | 0 => e K q u v
  | m + 1 => dPlusStar K q u (v + m) * dPlusStarPow K q u v m

theorem dPlusPow_succ (v m : ℕ) :
    dPlusPow K q u v (m + 1) = dPlus K q u (v + m) * dPlusPow K q u v m := rfl

theorem dPlusStarPow_succ (v m : ℕ) :
    dPlusStarPow K q u v (m + 1) = dPlusStar K q u (v + m) * dPlusStarPow K q u v m := rfl

/-- The word of raising arrows starts at its vertex. -/
@[simp]
theorem dPlusPow_mul_e (v m : ℕ) : dPlusPow K q u v m * e K q u v = dPlusPow K q u v m := by
  induction m with
  | zero => exact e_mul_self v
  | succ m ih => rw [dPlusPow_succ, mul_assoc, ih]

/-- The starred word of raising arrows starts at its vertex. -/
@[simp]
theorem dPlusStarPow_mul_e (v m : ℕ) :
    dPlusStarPow K q u v m * e K q u v = dPlusStarPow K q u v m := by
  induction m with
  | zero => exact e_mul_self v
  | succ m ih => rw [dPlusStarPow_succ, mul_assoc, ih]

/-! ### The two ideals -/

/-- **The left ideal `I`** of `Ã` generated by the elements `d₊^*d₊^m - d₊^{m+1}` for `m ≥ 0`, each
read at the vertex `v` at which its paths begin. -/
@[hjo "def_cm_kernel_ideal"]
noncomputable def kernelIdeal (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : Ideal (Atilde K q u) :=
  Ideal.span {x | ∃ v m : ℕ,
    x = dPlusStar K q u (v + m) * dPlusPow K q u v m - dPlusPow K q u v (m + 1)}

/-- **The starred and unstarred powers agree modulo `I`.** For
every `m ≥ 0` the element `d₊^{*m} - d₊^{m}` of `Ã` lies in `I`.

Induction on `m`. At `m = 0` both words are the idempotent at the vertex, so the difference is `0`.
At `m + 1`, write

    `d₊^{*(m+1)} - d₊^{m+1} = d₊^*(d₊^{*m} - d₊^{m}) + (d₊^*d₊^{m} - d₊^{m+1})`,

whose first summand is in `I` because `I` is a *left* ideal and the second is a generator of `I` by
`HJO.Dyck.Tilde.Atilde.kernelIdeal`.

The paper writes the element with no vertex; here it is read at the vertex `v` at which its paths
begin, as the generators of `I` are, and the statement holds at every `v`. -/
@[hjo "lem_cm_kernel_ideal_dplus_power"]
theorem dPlusStarPow_sub_dPlusPow_mem_kernelIdeal (v m : ℕ) :
    dPlusStarPow K q u v m - dPlusPow K q u v m ∈ kernelIdeal K q u := by
  induction m with
  | zero =>
    have h0 : dPlusStarPow K q u v 0 - dPlusPow K q u v 0 = 0 := by
      rw [show dPlusStarPow K q u v 0 = e K q u v from rfl,
        show dPlusPow K q u v 0 = e K q u v from rfl, sub_self]
    rw [h0]
    exact Submodule.zero_mem _
  | succ m ih =>
    have hgen : dPlusStar K q u (v + m) * dPlusPow K q u v m - dPlusPow K q u v (m + 1)
        ∈ kernelIdeal K q u :=
      Ideal.subset_span ⟨v, m, rfl⟩
    have hrw : dPlusStarPow K q u v (m + 1) - dPlusPow K q u v (m + 1)
        = dPlusStar K q u (v + m) * (dPlusStarPow K q u v m - dPlusPow K q u v m)
          + (dPlusStar K q u (v + m) * dPlusPow K q u v m - dPlusPow K q u v (m + 1)) := by
      rw [dPlusStarPow_succ, mul_sub]
      abel
    rw [hrw]
    exact Submodule.add_mem _ (Ideal.mul_mem_left _ _ ih) hgen

/-- A generator of `I` starting above the vertex `0` is killed by `𝟏_0`, so `I𝟏_0` does not depend
on whether the family is indexed by the starting vertex or read at `0` alone. -/
theorem kernelIdeal_gen_mul_e_zero {v m : ℕ} (hv : v ≠ 0) :
    (dPlusStar K q u (v + m) * dPlusPow K q u v m - dPlusPow K q u v (m + 1)) * e K q u 0 = 0 := by
  have h : ∀ x : Atilde K q u, x * e K q u v = x → x * e K q u 0 = 0 := by
    intro x hx
    rw [← hx, mul_assoc, e_mul_e_of_ne hv, mul_zero]
  rw [sub_mul, h _ (by rw [mul_assoc, dPlusPow_mul_e]), h _ (dPlusPow_mul_e v (m + 1)), sub_zero]

/-- **The left submodule `𝓘` of `Ã𝟏_0`** generated by the elements `(d₋d₊^* - 𝟏_k)d₊^{*k}𝟏_0` and
`(d₊ + q^ky_1d₊^*)d₊^{*k}𝟏_0` for `k ≥ 0`: the submodule the structure theorem identifies with the
kernel of `Ã𝟏_0 → V_*`. -/
@[hjo "def_dpa_kernel_mellit"]
noncomputable def mellitKernel (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : Ideal (Atilde K q u) :=
  Ideal.span
    (Set.range (fun k : ℕ =>
        (dMinus K q u k * dPlusStar K q u k - e K q u k) * dPlusStarPow K q u 0 k) ∪
      Set.range (fun k : ℕ =>
        (dPlus K q u k + (q ^ k) • (yElt K q u (k + 1) 1 * dPlusStar K q u k)) *
          dPlusStarPow K q u 0 k))

end Atilde

end HJO.Dyck.Tilde
