/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.CarlssonMellit.BraidInverse
public import HJO.CarlssonMellit.DPATilde
public meta import HJO.Attr

/-! # The two-sided Dyck path algebra `𝔹`

`HJO.Dyck.TwoSided.Bq`: `𝔹` is the quotient of the path algebra of the quiver of `HJO.Dyck.Aq`
enlarged by one further arrow `d₊^*` from `k` to `k+1` for each `k ≥ 0`, by the two-sided ideal
generated by the relations of `HJO.Dyck.Aq` together with the elements obtained from those relations
by applying the bar automorphism `c ↦ c̄` of `𝕜` to the coefficients, replacing `d₊` by `d₊^*`, and
replacing each `T_i` by `T̂_i` of `HJO.Dyck.braidInvGen`.

## `𝔹` is `Ã` without the three mixed relations, and is built from the same data

The enlarged quiver, its free algebra, and the two groups of relations are already in
`HJO.CarlssonMellit.DPATilde`: `HJO.Dyck.Tilde.Gen` is the quiver, and `HJO.Dyck.SourceRel` is
the paper's own relation list written in an *arbitrary* family of generators, so the starred group
is that same inductive read at the substituted family — which is what makes "the elements obtained
from those relations by the substitution" a statement rather than a second transcription. `𝔹` is
the quotient by those two groups alone; `Ã` of `HJO.Dyck.Tilde.Atilde` is the further quotient by
the three relations mixing `y_i`, `z_i` and the two raising arrows.

That is exactly the stage at which the exchange of the starred and unstarred halves is visible, and
why it is a separate definition: the three further relations of `HJO.Dyck.Tilde.Atilde` are written
with `y_i` and `z_i`, which do not exist until the unstarred group has been imposed, so
`HJO.Dyck.TwoSided.Bq` is the largest quotient at which the two groups are present and symmetric.

**The bar on the coefficients is `q ↦ q⁻¹`.** `HJO.Dyck.SourceRel` reads only the scalar `q` — `u`
enters the construction through the third mixed relation of `HJO.Dyck.Tilde.Atilde` and nowhere else
— so applying `HJO.Sym.paramInvLambda` to the coefficients of the relations of `HJO.Dyck.Aq` is
replacing `q` by `q⁻¹`, and that is the substitution the starred group below is read at. The
substitution of `T_i` by `T̂_i` is `HJO.Dyck.Tilde.freeTinv`, the polynomial inverse of
`HJO.Dyck.braidInvGen` written in the free algebra, and `HJO.Dyck.Tilde.tinvOf_tinvOf` is the check
that the substitution is an involution on the loops — the starred copy of `T̂_i` is `T_i` again, so
the starred group really is the paper's own list.

## Main definitions

* `HJO.Dyck.TwoSided.Rel`: the relations, the quiver's own structure together with the unstarred and
  the starred group.
* `HJO.Dyck.TwoSided.Bq`: the algebra `𝔹`.
* `HJO.Dyck.TwoSided.e`, `dPlus`, `dPlusStar`, `dMinus`, `Tg`, `Tinv`: the generators in `𝔹`.

## Main results

* `HJO.Dyck.TwoSided.eq_of_sourceRel`, `HJO.Dyck.TwoSided.eq_of_sourceRelStar`: the two groups of
  relations hold in `𝔹`.
* `HJO.Dyck.TwoSided.Tg_mul_Tinv`, `HJO.Dyck.TwoSided.Tinv_mul_Tg`: `T̂_i` is the inverse of `T_i`
  in `𝔹`, which is the `σ(T_i) = T̂_i = T_i⁻¹`. It is `HJO.Dyck.mul_braidInvGen`
  applied to `𝔹`, with no computation repeated.

## References

E. Carlsson and A. Mellit, *A proof of the shuffle conjecture*, J. Amer. Math. Soc.
**31** (2018) 661--697, Section 3. -/

@[expose] public section

namespace HJO.Dyck.TwoSided

/-! ### The relations -/

section Free

variable (K : Type*) [CommRing K] (q : K) [Invertible q]

/-- **The relations of `𝔹`.** The enlarged quiver's own structure, then the paper's relations in
the unstarred generators, then the same inductive read in the starred ones.

The quiver relations are imposed once and are *not* substituted, for the reason recorded on
`HJO.Dyck.Tilde.Rel`: `braid_eq_zero` substituted into the starred group would read
`q⁻¹(0 + (q-1)e_k) = 0`, which kills every idempotent. The one incidence that must be substituted,
`e_{k+1}d₊ = d₊ = d₊e_k`, is carried inside `HJO.Dyck.SourceRel` precisely so that its starred copy
places `d₊^*` between the same two vertices. -/
inductive Rel : FreeAlgebra K Tilde.Gen → FreeAlgebra K Tilde.Gen → Prop where
  /-- The vertex elements are idempotent. -/
  | vertex_mul_self (k : ℕ) : Rel (Tilde.freeE K k * Tilde.freeE K k) (Tilde.freeE K k)
  /-- Distinct vertices are orthogonal. -/
  | vertex_mul_vertex {k l : ℕ} (h : k ≠ l) : Rel (Tilde.freeE K k * Tilde.freeE K l) 0
  /-- `d₋` lands at the vertex `k`. -/
  | vertex_mul_down (k : ℕ) : Rel (Tilde.freeE K k * Tilde.freeDown K k) (Tilde.freeDown K k)
  /-- `d₋` starts at the vertex `k + 1`. -/
  | down_mul_vertex (k : ℕ) : Rel (Tilde.freeDown K k * Tilde.freeE K (k + 1)) (Tilde.freeDown K k)
  /-- A loop at the vertex `k` lands there. -/
  | vertex_mul_braid (k i : ℕ) : Rel (Tilde.freeE K k * Tilde.freeT K k i) (Tilde.freeT K k i)
  /-- A loop at the vertex `k` starts there. -/
  | braid_mul_vertex (k i : ℕ) : Rel (Tilde.freeT K k i * Tilde.freeE K k) (Tilde.freeT K k i)
  /-- The quiver has the loops `T₁, …, T_{k-1}` at the vertex `k` and no others. -/
  | braid_eq_zero {k i : ℕ} (h : k ≤ i + 1) : Rel (Tilde.freeT K k i) 0
  /-- **The unstarred group**: the relations of `HJO.Dyck.Aq` in `d₊` and the loops. -/
  | source {x y : FreeAlgebra K Tilde.Gen}
      (h : SourceRel q (Tilde.freeE K) (Tilde.freeUp K) (Tilde.freeDown K) (Tilde.freeT K) x y) :
      Rel x y
  /-- **The starred group**: the very same relations after applying the bar to the coefficients,
  `d₊ ↦ d₊^*` and `T_i ↦ T̂_i`. -/
  | sourceStar {x y : FreeAlgebra K Tilde.Gen}
      (h : SourceRel (⅟q) (Tilde.freeE K) (Tilde.freeUpStar K) (Tilde.freeDown K)
        (Tilde.freeTinv K q) x y) :
      Rel x y

end Free

/-- **The two-sided Dyck path algebra `𝔹`**: the path algebra over `K` of the quiver of
`HJO.Dyck.Aq` enlarged by one further arrow `d₊^*` at each vertex, modulo the two-sided ideal
generated by the relations of `HJO.Dyck.Aq` together with their images under the bar on the
coefficients, `d₊ ↦ d₊^*` and `T_i ↦ T̂_i`. -/
@[hjo "def_cm_dpa_two_sided"]
abbrev Bq (K : Type*) [CommRing K] (q : K) [Invertible q] : Type _ := RingQuot (Rel K q)

namespace Bq

variable {K : Type*} [CommRing K] {q : K} [Invertible q]

/-- The quotient map from the free algebra on the enlarged quiver onto `𝔹`. -/
noncomputable def mk (K : Type*) [CommRing K] (q : K) [Invertible q] :
    FreeAlgebra K Tilde.Gen →ₐ[K] Bq K q :=
  RingQuot.mkAlgHom K (Rel K q)

/-- **The idempotent at the vertex `k`** in `𝔹`. -/
@[hjo "def_cm_dpa_two_sided"]
noncomputable def e (K : Type*) [CommRing K] (q : K) [Invertible q] (k : ℕ) : Bq K q :=
  mk K q (Tilde.freeE K k)

/-- **The raising arrow `d₊`** in `𝔹`. -/
@[hjo "def_cm_dpa_two_sided"]
noncomputable def dPlus (K : Type*) [CommRing K] (q : K) [Invertible q] (k : ℕ) : Bq K q :=
  mk K q (Tilde.freeUp K k)

/-- **The further raising arrow `d₊^*`** in `𝔹`, the arrow by which the quiver of `HJO.Dyck.Aq` is
enlarged. -/
@[hjo "def_cm_dpa_two_sided"]
noncomputable def dPlusStar (K : Type*) [CommRing K] (q : K) [Invertible q] (k : ℕ) : Bq K q :=
  mk K q (Tilde.freeUpStar K k)

/-- **The lowering arrow `d₋`** in `𝔹`. -/
@[hjo "def_cm_dpa_two_sided"]
noncomputable def dMinus (K : Type*) [CommRing K] (q : K) [Invertible q] (k : ℕ) : Bq K q :=
  mk K q (Tilde.freeDown K k)

/-- **The loop `T_{i+1}` at the vertex `k`** in `𝔹`, the paper's `T_i` being `Tg K q k (i - 1)`. -/
@[hjo "def_cm_dpa_two_sided"]
noncomputable def Tg (K : Type*) [CommRing K] (q : K) [Invertible q] (k i : ℕ) : Bq K q :=
  mk K q (Tilde.freeT K k i)

/-- The polynomial inverse `T̂_{i+1}` of the loop at the vertex `k`, inside `𝔹`: the element the
starred group is written with. -/
@[hjo "def_cm_dpa_two_sided"]
noncomputable def Tinv (K : Type*) [CommRing K] (q : K) [Invertible q] (k i : ℕ) : Bq K q :=
  tinvOf q ⅟q (Tg K q k i) (e K q k)

@[simp] theorem mk_freeE (k : ℕ) : mk K q (Tilde.freeE K k) = e K q k := rfl
@[simp] theorem mk_freeUp (k : ℕ) : mk K q (Tilde.freeUp K k) = dPlus K q k := rfl
@[simp] theorem mk_freeUpStar (k : ℕ) : mk K q (Tilde.freeUpStar K k) = dPlusStar K q k := rfl
@[simp] theorem mk_freeDown (k : ℕ) : mk K q (Tilde.freeDown K k) = dMinus K q k := rfl
@[simp] theorem mk_freeT (k i : ℕ) : mk K q (Tilde.freeT K k i) = Tg K q k i := rfl

@[simp] theorem mk_freeTinv (k i : ℕ) : mk K q (Tilde.freeTinv K q k i) = Tinv K q k i :=
  map_tinvOf _ q ⅟q (mk_freeT k i) (mk_freeE k)

/-- The polynomial inverse of `HJO.Dyck.braidInvGen`, read inside `𝔹`: `T̂_i = q⁻¹(T_i + (q-1)e_k)`,
which is `HJO.Dyck.braidInvGen` at the loop and the idempotent. -/
theorem Tinv_eq_braidInvGen (k i : ℕ) :
    Tinv K q k i = braidInvGen K q (Tg K q k i) (e K q k) := rfl

/-- Any relation of `Rel` holds in `𝔹`. -/
theorem mk_rel {x y : FreeAlgebra K Tilde.Gen} (h : Rel K q x y) : mk K q x = mk K q y :=
  RingQuot.mkAlgHom_rel K h

/-! ### The path-algebra structure -/

@[simp]
theorem e_mul_self (k : ℕ) : e K q k * e K q k = e K q k := by
  simpa using mk_rel (Rel.vertex_mul_self (K := K) (q := q) k)

@[simp]
theorem e_mul_e_of_ne {k l : ℕ} (h : k ≠ l) : e K q k * e K q l = 0 := by
  simpa using mk_rel (Rel.vertex_mul_vertex (K := K) (q := q) h)

@[simp]
theorem e_mul_dMinus (k : ℕ) : e K q k * dMinus K q k = dMinus K q k := by
  simpa using mk_rel (Rel.vertex_mul_down (K := K) (q := q) k)

@[simp]
theorem dMinus_mul_e (k : ℕ) : dMinus K q k * e K q (k + 1) = dMinus K q k := by
  simpa using mk_rel (Rel.down_mul_vertex (K := K) (q := q) k)

@[simp]
theorem e_mul_Tg (k i : ℕ) : e K q k * Tg K q k i = Tg K q k i := by
  simpa using mk_rel (Rel.vertex_mul_braid (K := K) (q := q) k i)

@[simp]
theorem Tg_mul_e (k i : ℕ) : Tg K q k i * e K q k = Tg K q k i := by
  simpa using mk_rel (Rel.braid_mul_vertex (K := K) (q := q) k i)

/-- The quiver has exactly `k - 1` loops at the vertex `k`. -/
@[hjo "def_cm_dpa_two_sided"]
theorem Tg_eq_zero {k i : ℕ} (h : k ≤ i + 1) : Tg K q k i = 0 := by
  simpa using mk_rel (Rel.braid_eq_zero (K := K) (q := q) h)

/-! ### The unstarred and the starred groups of relations -/

/-- **The unstarred group of relations holds in `𝔹`**: every instance of `HJO.Dyck.SourceRel`, read
at the scalar `q` and the generators `e`, `d₊`, `d₋`, `T`, is an identity of `𝔹`. -/
@[hjo "def_cm_dpa_two_sided"]
theorem eq_of_sourceRel {x y : Bq K q}
    (h : SourceRel q (e K q) (dPlus K q) (dMinus K q) (Tg K q) x y) : x = y := by
  induction h with
  | vertex_mul_up k => simpa using mk_rel (Rel.source (SourceRel.vertex_mul_up k))
  | up_mul_vertex k => simpa using mk_rel (Rel.source (SourceRel.up_mul_vertex k))
  | quadratic h => simpa using mk_rel (Rel.source (SourceRel.quadratic h))
  | braid_braid h => simpa using mk_rel (Rel.source (SourceRel.braid_braid h))
  | braid_comm hi hj hij => simpa using mk_rel (Rel.source (SourceRel.braid_comm hi hj hij))
  | braid_down h => simpa using mk_rel (Rel.source (SourceRel.braid_down h))
  | up_braid h => simpa using mk_rel (Rel.source (SourceRel.up_braid h))
  | braid_up_up k => simpa using mk_rel (Rel.source (SourceRel.braid_up_up k))
  | down_down_braid m => simpa using mk_rel (Rel.source (SourceRel.down_down_braid m))
  | down_delta j =>
    simpa [commOf] using mk_rel (Rel.source (SourceRel.down_delta (E := Tilde.freeE K) j))
  | braid_delta m =>
    simpa [commOf] using mk_rel (Rel.source (SourceRel.braid_delta (E := Tilde.freeE K) m))

/-- **The starred group of relations holds in `𝔹`**: every instance of `HJO.Dyck.SourceRel`, read at
the barred scalar `q⁻¹` and the substituted generators `e`, `d₊^*`, `d₋`, `T̂`, is an identity of
`𝔹`. This is the second group of generators of the ideal. -/
@[hjo "def_cm_dpa_two_sided"]
theorem eq_of_sourceRelStar {x y : Bq K q}
    (h : SourceRel (⅟q) (e K q) (dPlusStar K q) (dMinus K q) (Tinv K q) x y) : x = y := by
  induction h with
  | vertex_mul_up k => simpa using mk_rel (Rel.sourceStar (SourceRel.vertex_mul_up k))
  | up_mul_vertex k => simpa using mk_rel (Rel.sourceStar (SourceRel.up_mul_vertex k))
  | quadratic h => simpa using mk_rel (Rel.sourceStar (SourceRel.quadratic h))
  | braid_braid h => simpa using mk_rel (Rel.sourceStar (SourceRel.braid_braid h))
  | braid_comm hi hj hij => simpa using mk_rel (Rel.sourceStar (SourceRel.braid_comm hi hj hij))
  | braid_down h => simpa using mk_rel (Rel.sourceStar (SourceRel.braid_down h))
  | up_braid h => simpa using mk_rel (Rel.sourceStar (SourceRel.up_braid h))
  | braid_up_up k => simpa using mk_rel (Rel.sourceStar (SourceRel.braid_up_up k))
  | down_down_braid m => simpa using mk_rel (Rel.sourceStar (SourceRel.down_down_braid m))
  | down_delta j =>
    simpa [commOf] using mk_rel (Rel.sourceStar (SourceRel.down_delta (E := Tilde.freeE K) j))
  | braid_delta m =>
    simpa [commOf] using mk_rel (Rel.sourceStar (SourceRel.braid_delta (E := Tilde.freeE K) m))

/-! ### The polynomial inverse is an inverse in `𝔹` -/

/-- The quadratic relation of `HJO.Dyck.Aq` inside `𝔹`. -/
theorem quadratic {k i : ℕ} (h : i + 2 ≤ k) :
    (Tg K q k i - e K q k) * (Tg K q k i + q • e K q k) = 0 :=
  eq_of_sourceRel (SourceRel.quadratic h)

/-- **`T̂_i` is a two-sided inverse of `T_i` in `𝔹`**, the half `T_iT̂_i = e_k`: the instance of
`HJO.Dyck.mul_braidInvGen` at `𝔹`, the four relations it reads being the idempotence of `e_k`, the
two absorptions and the quadratic relation. This is what the `σ(T_i) = T̂_i = T_i⁻¹`
means at this stage, and no computation is repeated to get it. -/
theorem Tg_mul_Tinv {k i : ℕ} (h : i + 2 ≤ k) : Tg K q k i * Tinv K q k i = e K q k :=
  mul_braidInvGen (e_mul_self k) (e_mul_Tg k i) (Tg_mul_e k i) (quadratic h)

/-- **`T̂_i` is a two-sided inverse of `T_i` in `𝔹`**, the half `T̂_iT_i = e_k`. -/
theorem Tinv_mul_Tg {k i : ℕ} (h : i + 2 ≤ k) : Tinv K q k i * Tg K q k i = e K q k :=
  braidInvGen_mul (e_mul_self k) (e_mul_Tg k i) (Tg_mul_e k i) (quadratic h)

end Bq

end HJO.Dyck.TwoSided
