/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.CarlssonMellit.AqToAtilde
public import HJO.CarlssonMellit.KernelDplusStarStep
public meta import HJO.Attr

/-! # Every unstarred word has its raising arrows at the end

`HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0` needs the image of `𝔸_q𝟏_0` in
`Ã𝟏_0` written so that every `d₊` sits in one block applied to `𝟏_0`: the generators of `I` retire
`d₊^*` only against such a block, `I` being a *left* ideal. The natural source for that normal form
is the four-move reduction inside the proof of `HJO.Sweep.exists_linearEquiv_e0Ideal`, whose
termination measure the second move raises, by `HJO.Dyck.straightenMeasure_lt_moveTwo`.

This file proves the weaker statement that suffices, and proves it by structural induction with no
measure at all:

    `𝔸_q𝟏_0 = span_K { v₁ ⋯ v_r · d₊^n𝟏_0 }`,  each `vᵢ ∈ {e, T, y, d₋}`.

No `T` is eliminated and nothing is straightened — the `vᵢ` are an arbitrary word — so no
termination argument is needed and none is offered. The only content is that the span is closed
under multiplication by `d₊` on the *left*, and that is three relations of `Ã`:
`d₊T_i = T_{i+1}d₊`, the transport `d₊y_i = W_iy_iW_i^{-1}d₊` of
`HJO.Dyck.Tilde.Atilde.dPlus_mul_yElt`, and the commutator
`d₊d₋ = d₋d₊ + (q-1)T_1 ⋯ T_{k-1}y_k` of
`HJO.Dyck.Tilde.Atilde.commOf_eq_smul_segUpOf_mul_yElt`. The third is the one that does the work:
it turns a leading `d₊` into leading-`y` and leading-`d₋` terms, and its `y`-term has no trailing
`d₊` at all, which is why `y` has to be a letter.

## Main definitions

* `HJO.Dyck.Tilde.Atilde.levelSet`: the letters `e`, `T`, `y`, `d₋`.
* `HJO.Dyck.Tilde.Atilde.levelAlg`: the subalgebra they generate.
* `HJO.Dyck.Tilde.Atilde.levelPlus`: the span of `levelAlg` and `levelAlg · d₊`, the module the
  left-multiplication step lands in.
* `HJO.Dyck.Tilde.Atilde.raisingSpan`: the span `P` itself.
* `HJO.Dyck.Tilde.Atilde.aqE0`: the image of `𝔸_q𝟏_0` in `Ã`, along `HJO.Dyck.toTilde`.

## Main results

* `HJO.Dyck.Tilde.Atilde.dPlus_mul_mem_levelPlus`: `d₊a ∈ levelAlg + levelAlg·d₊` for
  `a ∈ levelAlg`. The structural induction, and the whole of the argument.
* `HJO.Dyck.Tilde.Atilde.dPlus_mul_mem_raisingSpan`: `P` is closed under `d₊` on the left.
* `HJO.Dyck.Tilde.Atilde.aqE0_eq_raisingSpan`: `𝔸_q𝟏_0 = P`.

## References

E. Carlsson and A. Mellit, *A proof of the shuffle conjecture*, J. Amer. Math. Soc. **31** (2018)
661--697, Section 7, the kernel of the extended action: Lemma
`HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0` and `HJO.Dyck.Tilde.Atilde`.
-/

@[expose] public section

namespace HJO.Dyck.Tilde.Atilde

variable {K : Type*} [CommRing K] {q u : K} [Invertible q] [Invertible (q - 1)]

/-! ### Two absorptions the raising block needs -/

/-- The raising arrow shifts a loop's index up by one, inside `Ã`: `d₊T_i = T_{i+1}d₊`. -/
theorem dPlus_mul_Tg {k i : ℕ} (h : i + 2 ≤ k) :
    dPlus K q u k * Tg K q u k i = Tg K q u (k + 1) (i + 1) * dPlus K q u k :=
  eq_of_sourceRel (SourceRel.up_braid (q := q) (E := e K q u) (U := dPlus K q u)
    (D := dMinus K q u) (T := Tg K q u) h)

/-- A block of raising arrows out of the vertex `v` lands at the vertex `v + m`. -/
@[simp]
theorem e_mul_dPlusPow (v m : ℕ) :
    e K q u (v + m) * dPlusPow K q u v m = dPlusPow K q u v m := by
  induction m with
  | zero => rw [Nat.add_zero, dPlusPow, e_mul_self]
  | succ m _ => rw [dPlusPow_succ, ← mul_assoc, show v + (m + 1) = v + m + 1 from by omega,
      e_mul_dPlus]

/-! ### The letters and the subalgebra they generate -/

/-- **The letters** allowed to the left of the terminal raising block: an idempotent, a loop, a
corner element `y_i` with `1 ≤ i ≤ k`, or a lowering arrow. The corner elements are letters because
the commutator `d₊d₋ - d₋d₊` is one of them and carries no trailing `d₊`; the index range is the
one on which `HJO.Dyck.Tilde.Atilde.yElt` is the paper's element rather than a totalization. -/
def levelSet (K : Type*) [CommRing K] (q u : K) [Invertible q] [Invertible (q - 1)] :
    Set (Atilde K q u) :=
  {x | (∃ k, x = e K q u k) ∨ (∃ k i, x = Tg K q u k i) ∨
    (∃ k i, 1 ≤ i ∧ i ≤ k ∧ x = yElt K q u k i) ∨ (∃ k, x = dMinus K q u k)}

/-- The subalgebra of `Ã` generated by the letters. -/
noncomputable def levelAlg (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : Subalgebra K (Atilde K q u) := Algebra.adjoin K (levelSet K q u)

theorem e_mem_levelAlg (k : ℕ) : e K q u k ∈ levelAlg K q u :=
  Algebra.subset_adjoin (Or.inl ⟨k, rfl⟩)

theorem Tg_mem_levelAlg (k i : ℕ) : Tg K q u k i ∈ levelAlg K q u :=
  Algebra.subset_adjoin (Or.inr (Or.inl ⟨k, i, rfl⟩))

theorem yElt_mem_levelAlg {k i : ℕ} (h1 : 1 ≤ i) (h2 : i ≤ k) :
    yElt K q u k i ∈ levelAlg K q u :=
  Algebra.subset_adjoin (Or.inr (Or.inr (Or.inl ⟨k, i, h1, h2, rfl⟩)))

theorem dMinus_mem_levelAlg (k : ℕ) : dMinus K q u k ∈ levelAlg K q u :=
  Algebra.subset_adjoin (Or.inr (Or.inr (Or.inr ⟨k, rfl⟩)))

theorem Tinv_mem_levelAlg (k i : ℕ) : Tinv K q u k i ∈ levelAlg K q u := by
  rw [Tinv, tinvOf]
  exact Subalgebra.smul_mem _ (add_mem (Tg_mem_levelAlg k i)
    (Subalgebra.smul_mem _ (e_mem_levelAlg k) _)) _

theorem segUpOf_mem_levelAlg (k a n : ℕ) :
    segUpOf (e K q u) (Tg K q u) k a n ∈ levelAlg K q u := by
  induction n with
  | zero => exact e_mem_levelAlg k
  | succ n ih => exact mul_mem ih (Tg_mem_levelAlg k (a + n))

theorem tinvWordOf_mem_levelAlg (k n : ℕ) :
    tinvWordOf q ⅟q (e K q u) (Tg K q u) k n ∈ levelAlg K q u := by
  induction n with
  | zero => exact e_mem_levelAlg k
  | succ n ih => exact mul_mem (Tinv_mem_levelAlg k n) ih

/-- **The commutator is a letter word**: `d₊d₋ - d₋d₊ = (q-1)T_1 ⋯ T_{k-1}y_k` lies in the
subalgebra generated by the letters, carrying no raising arrow at all. -/
theorem commOf_mem_levelAlg (k : ℕ) :
    commOf (dPlus K q u) (dMinus K q u) k ∈ levelAlg K q u := by
  have h := commOf_eq_smul_segUpOf_mul_yElt (K := K) (q := q) (u := u) (k := k + 1) (by omega)
  rw [Nat.add_sub_cancel] at h
  rw [h]
  exact Subalgebra.smul_mem _
    (mul_mem (segUpOf_mem_levelAlg (k + 1) 0 k) (yElt_mem_levelAlg (by omega) le_rfl)) _

/-! ### One step of the raising arrow -/

/-- The module the left multiplication `a ↦ d₊a` carries `levelAlg` into: the span of `levelAlg`
and of `levelAlg·d₊`. -/
noncomputable def levelPlus (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : Submodule K (Atilde K q u) :=
  Submodule.span K {x | x ∈ levelAlg K q u ∨ ∃ a ∈ levelAlg K q u, ∃ k, x = a * dPlus K q u k}

theorem mem_levelPlus_of_mem_levelAlg {a : Atilde K q u} (ha : a ∈ levelAlg K q u) :
    a ∈ levelPlus K q u := Submodule.subset_span (Or.inl ha)

theorem mul_dPlus_mem_levelPlus {a : Atilde K q u} (ha : a ∈ levelAlg K q u) (k : ℕ) :
    a * dPlus K q u k ∈ levelPlus K q u := Submodule.subset_span (Or.inr ⟨a, ha, k, rfl⟩)

theorem dPlus_mem_levelPlus (k : ℕ) : dPlus K q u k ∈ levelPlus K q u := by
  simpa using mul_dPlus_mem_levelPlus (one_mem (levelAlg K q u)) k

/-- `levelPlus` is a `levelAlg`-module. -/
theorem levelAlg_mul_mem_levelPlus {a x : Atilde K q u} (ha : a ∈ levelAlg K q u)
    (hx : x ∈ levelPlus K q u) : a * x ∈ levelPlus K q u := by
  refine Submodule.span_induction (p := fun z _ => a * z ∈ levelPlus K q u) ?_ ?_ ?_ ?_ hx
  · rintro z (hz | ⟨b, hb, k, rfl⟩)
    · exact mem_levelPlus_of_mem_levelAlg (mul_mem ha hz)
    · rw [← mul_assoc]
      exact mul_dPlus_mem_levelPlus (mul_mem ha hb) k
  · rw [mul_zero]; exact zero_mem _
  · intro y z _ _ hy hz; rw [mul_add]; exact add_mem hy hz
  · intro c y _ hy; rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

/-- Right multiplication by an element of `levelAlg` that the raising arrow can be moved past keeps
one inside `levelPlus`. This is the multiplicative step of the structural induction. -/
theorem levelPlus_mul_mem_levelPlus {x y : Atilde K q u} (hx : x ∈ levelPlus K q u)
    (hyA : y ∈ levelAlg K q u) (hy : ∀ k, dPlus K q u k * y ∈ levelPlus K q u) :
    x * y ∈ levelPlus K q u := by
  refine Submodule.span_induction (p := fun z _ => z * y ∈ levelPlus K q u) ?_ ?_ ?_ ?_ hx
  · rintro z (hz | ⟨b, hb, k, rfl⟩)
    · exact mem_levelPlus_of_mem_levelAlg (mul_mem hz hyA)
    · rw [mul_assoc]
      exact levelAlg_mul_mem_levelPlus hb (hy k)
  · rw [zero_mul]; exact zero_mem _
  · intro z w _ _ hz hw; rw [add_mul]; exact add_mem hz hw
  · intro c z _ hz; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hz

/-! #### The raising arrow past a single letter -/

/-- The raising arrow out of the vertex `k` annihilates every idempotent but `𝟏_k`. -/
theorem dPlus_mul_e_of_ne {k l : ℕ} (h : l ≠ k) : dPlus K q u k * e K q u l = 0 := by
  rw [← dPlus_mul_e (K := K) (q := q) (u := u) k, mul_assoc, e_mul_e_of_ne h.symm, mul_zero]

theorem dPlus_mul_e_mem_levelPlus (k l : ℕ) :
    dPlus K q u k * e K q u l ∈ levelPlus K q u := by
  rcases eq_or_ne l k with rfl | hl
  · rw [dPlus_mul_e]; exact dPlus_mem_levelPlus l
  · rw [dPlus_mul_e_of_ne hl]; exact zero_mem _

theorem dPlus_mul_Tg_mem_levelPlus (k l i : ℕ) :
    dPlus K q u k * Tg K q u l i ∈ levelPlus K q u := by
  rcases eq_or_ne l k with rfl | hl
  · rcases le_or_gt (i + 2) l with hi | hi
    · rw [dPlus_mul_Tg hi]
      exact mul_dPlus_mem_levelPlus (Tg_mem_levelAlg (l + 1) (i + 1)) l
    · rw [Tg_eq_zero (by omega), mul_zero]; exact zero_mem _
  · rw [← e_mul_Tg (K := K) (q := q) (u := u) l i, ← mul_assoc, dPlus_mul_e_of_ne hl, zero_mul]
    exact zero_mem _

theorem dPlus_mul_yElt_mem_levelPlus {k l i : ℕ} (h1 : 1 ≤ i) (h2 : i ≤ l) :
    dPlus K q u k * yElt K q u l i ∈ levelPlus K q u := by
  rcases eq_or_ne l k with rfl | hl
  · rw [dPlus_mul_yElt h1 h2]
    exact mul_dPlus_mem_levelPlus (mul_mem (mul_mem (segUpOf_mem_levelAlg (l + 1) 0 i)
      (yElt_mem_levelAlg h1 (by omega))) (tinvWordOf_mem_levelAlg (l + 1) i)) l
  · rw [← e_mul_yElt (K := K) (q := q) (u := u) l i, ← mul_assoc, dPlus_mul_e_of_ne hl, zero_mul]
    exact zero_mem _

/-- **The commutator step.** `d₊d₋ = d₋d₊ + (q-1)T_1 ⋯ T_{k-1}y_k`: the leading raising arrow is
traded for a leading lowering arrow and a leading corner element. -/
theorem dPlus_mul_dMinus_mem_levelPlus (k l : ℕ) :
    dPlus K q u k * dMinus K q u l ∈ levelPlus K q u := by
  rcases eq_or_ne l k with rfl | hl
  · have hsplit : dPlus K q u l * dMinus K q u l
        = commOf (dPlus K q u) (dMinus K q u) l + dMinus K q u (l + 1) * dPlus K q u (l + 1) := by
      rw [commOf]; abel
    rw [hsplit]
    exact add_mem (mem_levelPlus_of_mem_levelAlg (commOf_mem_levelAlg l))
      (mul_dPlus_mem_levelPlus (dMinus_mem_levelAlg (l + 1)) (l + 1))
  · rw [← e_mul_dMinus (K := K) (q := q) (u := u) l, ← mul_assoc, dPlus_mul_e_of_ne hl, zero_mul]
    exact zero_mem _

/-- **The structural induction**, and the whole of Part 1: the raising arrow multiplied on the left
into the subalgebra generated by the letters lands in the span of that subalgebra and of that
subalgebra times one raising arrow. There is no measure and no termination argument: the induction
is on the *formation* of the element of `levelAlg`, and the multiplicative step is
`HJO.Dyck.Tilde.Atilde.levelPlus_mul_mem_levelPlus`. -/
theorem dPlus_mul_mem_levelPlus {a : Atilde K q u} (ha : a ∈ levelAlg K q u) (k : ℕ) :
    dPlus K q u k * a ∈ levelPlus K q u := by
  induction ha using Algebra.adjoin_induction generalizing k with
  | mem z hz =>
    obtain ⟨l, rfl⟩ | ⟨l, i, rfl⟩ | ⟨l, i, h1, h2, rfl⟩ | ⟨l, rfl⟩ := hz
    · exact dPlus_mul_e_mem_levelPlus k l
    · exact dPlus_mul_Tg_mem_levelPlus k l i
    · exact dPlus_mul_yElt_mem_levelPlus h1 h2
    · exact dPlus_mul_dMinus_mem_levelPlus k l
  | algebraMap r =>
    rw [Algebra.algebraMap_eq_smul_one, mul_smul_comm, mul_one]
    exact Submodule.smul_mem _ r (dPlus_mem_levelPlus k)
  | add x y _ _ hx hy => rw [mul_add]; exact add_mem (hx k) (hy k)
  | mul x y _ hy hx hy' => rw [← mul_assoc]; exact levelPlus_mul_mem_levelPlus (hx k) hy hy'

/-! ### The span, and that it is the image of `𝔸_q𝟏_0` -/

/-- **`P`**: the span of `v₁ ⋯ v_r·d₊^n𝟏_0` with each `vᵢ` a letter. -/
noncomputable def raisingSpan (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : Submodule K (Atilde K q u) :=
  Submodule.span K {x | ∃ a ∈ levelAlg K q u, ∃ n, x = a * dPlusPow K q u 0 n}

theorem dPlusPow_mem_raisingSpan (n : ℕ) :
    dPlusPow K q u 0 n ∈ raisingSpan K q u :=
  Submodule.subset_span ⟨1, one_mem _, n, (one_mul _).symm⟩

theorem e0_mem_raisingSpan : e K q u 0 ∈ raisingSpan K q u := dPlusPow_mem_raisingSpan 0

theorem levelAlg_mul_mem_raisingSpan {a x : Atilde K q u} (ha : a ∈ levelAlg K q u)
    (hx : x ∈ raisingSpan K q u) : a * x ∈ raisingSpan K q u := by
  refine Submodule.span_induction (p := fun z _ => a * z ∈ raisingSpan K q u) ?_ ?_ ?_ ?_ hx
  · rintro z ⟨b, hb, n, rfl⟩
    rw [← mul_assoc]
    exact Submodule.subset_span ⟨a * b, mul_mem ha hb, n, rfl⟩
  · rw [mul_zero]; exact zero_mem _
  · intro y z _ _ hy hz; rw [mul_add]; exact add_mem hy hz
  · intro c y _ hy; rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

/-- One raising arrow extends a terminal raising block. -/
theorem dPlus_mul_dPlusPow_self (n : ℕ) :
    dPlus K q u n * dPlusPow K q u 0 n = dPlusPow K q u 0 (n + 1) := by
  rw [dPlusPow_succ, Nat.zero_add]

/-- A raising arrow out of the wrong vertex annihilates a terminal raising block. -/
theorem dPlus_mul_dPlusPow_of_ne {k n : ℕ} (hk : k ≠ n) :
    dPlus K q u k * dPlusPow K q u 0 n = 0 := by
  rw [← e_mul_dPlusPow (K := K) (q := q) (u := u) 0 n, Nat.zero_add, ← mul_assoc,
    dPlus_mul_e_of_ne hk.symm, zero_mul]

theorem levelPlus_mul_dPlusPow_mem_raisingSpan {x : Atilde K q u} (hx : x ∈ levelPlus K q u)
    (n : ℕ) : x * dPlusPow K q u 0 n ∈ raisingSpan K q u := by
  refine Submodule.span_induction (p := fun z _ => z * dPlusPow K q u 0 n ∈ raisingSpan K q u)
    ?_ ?_ ?_ ?_ hx
  · rintro z (hz | ⟨b, hb, k, rfl⟩)
    · exact Submodule.subset_span ⟨z, hz, n, rfl⟩
    · rw [mul_assoc]
      rcases eq_or_ne k n with rfl | hk
      · rw [dPlus_mul_dPlusPow_self]
        exact Submodule.subset_span ⟨b, hb, k + 1, rfl⟩
      · rw [dPlus_mul_dPlusPow_of_ne hk, mul_zero]; exact zero_mem _
  · rw [zero_mul]; exact zero_mem _
  · intro y z _ _ hy hz; rw [add_mul]; exact add_mem hy hz
  · intro c y _ hy; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hy

/-- **`P` is closed under the raising arrow on the left.** With
`HJO.Dyck.Tilde.Atilde.levelAlg_mul_mem_raisingSpan` this is the whole of the closure. -/
theorem dPlus_mul_mem_raisingSpan (k : ℕ) {x : Atilde K q u} (hx : x ∈ raisingSpan K q u) :
    dPlus K q u k * x ∈ raisingSpan K q u := by
  refine Submodule.span_induction (p := fun z _ => dPlus K q u k * z ∈ raisingSpan K q u)
    ?_ ?_ ?_ ?_ hx
  · rintro z ⟨a, ha, n, rfl⟩
    rw [← mul_assoc]
    exact levelPlus_mul_dPlusPow_mem_raisingSpan (dPlus_mul_mem_levelPlus ha k) n
  · rw [mul_zero]; exact zero_mem _
  · intro y z _ _ hy hz; rw [mul_add]; exact add_mem hy hz
  · intro c y _ hy; rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

/-- Every word in the unstarred generators carries `P` into itself. -/
theorem freeToTilde_mul_mem_raisingSpan (y : FreeAlgebra K HJO.Dyck.Gen) {x : Atilde K q u}
    (hx : x ∈ raisingSpan K q u) :
    HJO.Dyck.freeToTilde K q u y * x ∈ raisingSpan K q u := by
  induction y using FreeAlgebra.induction generalizing x with
  | grade0 r =>
    rw [AlgHom.commutes, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
    exact Submodule.smul_mem _ r hx
  | grade1 g =>
    rw [show HJO.Dyck.freeToTilde K q u (FreeAlgebra.ι K g) = HJO.Dyck.genToTilde K q u g from
      FreeAlgebra.lift_ι_apply _ _]
    cases g with
    | vertex l => exact levelAlg_mul_mem_raisingSpan (e_mem_levelAlg l) hx
    | up l => exact dPlus_mul_mem_raisingSpan l hx
    | down l => exact levelAlg_mul_mem_raisingSpan (dMinus_mem_levelAlg l) hx
    | braid l i => exact levelAlg_mul_mem_raisingSpan (Tg_mem_levelAlg l i) hx
  | mul a b ha hb => rw [map_mul, mul_assoc]; exact ha (hb hx)
  | add a b ha hb => rw [map_add, add_mul]; exact add_mem (ha hx) (hb hx)

/-- **The image of `𝔸_q𝟏_0` in `Ã`**, along the algebra map `HJO.Dyck.toTilde`. -/
noncomputable def aqE0 (K : Type*) [CommRing K] (q u : K) [Invertible q] [Invertible (q - 1)] :
    Submodule K (Atilde K q u) :=
  (Subalgebra.toSubmodule (HJO.Dyck.toTilde K q u).range).map (rightE0 K q u)

/-- **Part 1, one half**: every element of `𝔸_q𝟏_0` is a combination of words `v₁ ⋯ v_r·d₊^n𝟏_0`
with each `vᵢ ∈ {e, T, y, d₋}`. -/
theorem aqE0_le_raisingSpan : aqE0 K q u ≤ raisingSpan K q u := by
  rintro _ ⟨z, ⟨x, rfl⟩, rfl⟩
  obtain ⟨y, rfl⟩ := RingQuot.mkAlgHom_surjective K (HJO.Dyck.Rel K q) x
  have hmk : HJO.Dyck.toTilde K q u (Aq.mk K q y) = HJO.Dyck.freeToTilde K q u y :=
    HJO.Dyck.toTilde_mk y
  change HJO.Dyck.toTilde K q u (Aq.mk K q y) * e K q u 0 ∈ raisingSpan K q u
  rw [hmk]
  exact freeToTilde_mul_mem_raisingSpan y e0_mem_raisingSpan

/-! #### The converse, so that `P` is exactly the image -/

theorem levelAlg_le_toTilde_range :
    levelAlg K q u ≤ (HJO.Dyck.toTilde K q u).range := by
  rw [levelAlg]
  refine Algebra.adjoin_le ?_
  rintro z (⟨l, rfl⟩ | ⟨l, i, rfl⟩ | ⟨l, i, -, -, rfl⟩ | ⟨l, rfl⟩)
  · exact ⟨Aq.e K q l, HJO.Dyck.toTilde_e l⟩
  · exact ⟨Aq.Tg K q l i, HJO.Dyck.toTilde_Tg l i⟩
  · exact ⟨Aq.yElt K q l i, HJO.Dyck.toTilde_yElt l i⟩
  · exact ⟨Aq.dMinus K q l, HJO.Dyck.toTilde_dMinus l⟩

theorem dPlusPow_mem_toTilde_range (v n : ℕ) :
    dPlusPow K q u v n ∈ (HJO.Dyck.toTilde K q u).range := by
  induction n with
  | zero => exact ⟨Aq.e K q v, HJO.Dyck.toTilde_e v⟩
  | succ n ih =>
    rw [dPlusPow_succ]
    exact mul_mem ⟨Aq.dPlus K q (v + n), HJO.Dyck.toTilde_dPlus (v + n)⟩ ih

theorem raisingSpan_le_aqE0 : raisingSpan K q u ≤ aqE0 K q u := by
  refine Submodule.span_le.2 ?_
  rintro z ⟨a, ha, n, rfl⟩
  refine ⟨a * dPlusPow K q u 0 n, ?_, ?_⟩
  · exact (Subalgebra.mem_toSubmodule _).2
      (mul_mem (levelAlg_le_toTilde_range ha) (dPlusPow_mem_toTilde_range 0 n))
  · rw [rightE0_apply, mul_assoc, dPlusPow_mul_e]

/-- **Part 1.** The image of `𝔸_q𝟏_0` in `Ã` is *exactly* the span of the words
`v₁ ⋯ v_r·d₊^n𝟏_0` with each `vᵢ ∈ {e, T, y, d₋}`: every raising arrow can be pushed into one
terminal block, by structural induction on the word and with no termination measure.

This is strictly weaker than the normal form of `HJO.Sweep.exists_linearEquiv_e0Ideal` — no loop is
eliminated and no corner element is straightened — and that is the point: the measure of
`HJO.Dyck.straightenMeasure_lt_of_step`, which the second move raises by
`HJO.Dyck.straightenMeasure_lt_moveTwo`, is not consulted. -/
theorem aqE0_eq_raisingSpan : aqE0 K q u = raisingSpan K q u :=
  le_antisymm aqE0_le_raisingSpan raisingSpan_le_aqE0

end HJO.Dyck.Tilde.Atilde
