/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.CarlssonMellit.StarCornerMoves
public meta import HJO.Attr

/-! # `z` past a corner element, and the starred arrow on the unstarred image

The span route of `HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0` pushes `d₊^*`
rightwards through a word in the letters `{e, T, y, d₋}` until it meets the terminal raising block,
where the generators of `I` retire it. Pushing it past `d₋` produces a `z_k`, which must then be
pushed rightwards too. `z` past a
loop and `z` past a lowering arrow are `HJO.Dyck.Tilde.Atilde.zElt_mul_Tg_mem_span` and
`HJO.Dyck.Tilde.Atilde.zElt_mul_dMinus`. This file supplies the remaining one, `z` past a corner
element, and assembles the lemma.

## `z` past a corner element is not free, and is not a commutation

The remark under `HJO.Standing.exists_action_atilde_ker_eq_param` records that the double-affine
relation for `z_1y_1`
*fails* in `Ã`, by a correction term `qu\,y_1d_-d_+^*T_{k-1} ⋯ T_1` — so no relation of `Ã`
commutes `z` past `y`. What is true, and what the span route needs, is a *span modulo nothing*:

    `z_i^{(k)}y_j^{(k)} ∈ span_K { b·d₊^*, b·z_{i'} : b ∈ 𝔸_q }`

and the correction term is exactly why the `b·d₊^*` summand has to be there. The route is the
commutator: `y_j` is built from `d₊d₋ - d₋d₊` and loops, and `z` moves past `d₊` by the *first*
mixed relation (`z_{i+1}d₊ = d₊z_i`, index dropping) or, at `i = 1`, by the *third*
(`z_1d₊ = -uq^{k+1}y_1d₊^*`) — and that third relation is where a `d₊^*` is created, with no `z`
left in it. So the correction term is visible here as `mixed_top`, and it is
harmless: its `d₊^*` sits at the right end of the word, which is precisely the shape the terminal
raising block retires.

## What the assembled lemma says, and what it does not need

`HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0` carries no induction hypothesis:
no induction on arrow degree is used, and no assumption that the image already contains
everything of lower degree. The span route is unconditional.

## Main definitions

* `HJO.Dyck.Tilde.Atilde.unstarredAlg`: the image of `𝔸_q` in `Ã`.
* `HJO.Dyck.Tilde.Atilde.starMod`: the span of `𝔸_q·d₊^*` and `𝔸_q·z`, where the starred arrow
  pushed rightwards through a letter word lands.

## Main results

* `HJO.Dyck.Tilde.Atilde.zElt_mul_yElt_mem_starMod`: `z` past a corner element.
* `HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_starMod`, `zElt_mul_mem_starMod`: the simultaneous
  structural induction over the letters.
* `HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0`: the image of `𝔸_q𝟏_0` in
  `Ã𝟏_0/I𝟏_0` is carried into itself by `d₊^*`.

## References

E. Carlsson and A. Mellit, *A proof
of the shuffle conjecture*, J. Amer. Math. Soc. **31** (2018) 661--697, Section 7.
-/

@[expose] public section

namespace HJO.Dyck.Tilde.Atilde

variable {K : Type*} [CommRing K] {q u : K} [Invertible q] [Invertible (q - 1)]

/-! ### The unstarred subalgebra -/

/-- **The image of `𝔸_q` in `Ã`**, along `HJO.Dyck.toTilde`: the subalgebra generated by the
unstarred generators. -/
noncomputable def unstarredAlg (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : Subalgebra K (Atilde K q u) := (HJO.Dyck.toTilde K q u).range

theorem e_mem_unstarredAlg (k : ℕ) : e K q u k ∈ unstarredAlg K q u :=
  ⟨Aq.e K q k, HJO.Dyck.toTilde_e k⟩

theorem dPlus_mem_unstarredAlg (k : ℕ) : dPlus K q u k ∈ unstarredAlg K q u :=
  ⟨Aq.dPlus K q k, HJO.Dyck.toTilde_dPlus k⟩

theorem dMinus_mem_unstarredAlg (k : ℕ) : dMinus K q u k ∈ unstarredAlg K q u :=
  ⟨Aq.dMinus K q k, HJO.Dyck.toTilde_dMinus k⟩

theorem Tg_mem_unstarredAlg (k i : ℕ) : Tg K q u k i ∈ unstarredAlg K q u :=
  ⟨Aq.Tg K q k i, HJO.Dyck.toTilde_Tg k i⟩

theorem Tinv_mem_unstarredAlg (k i : ℕ) : Tinv K q u k i ∈ unstarredAlg K q u :=
  ⟨Aq.Tinv K q k i, HJO.Dyck.toTilde_Tinv k i⟩

theorem yElt_mem_unstarredAlg (k i : ℕ) : yElt K q u k i ∈ unstarredAlg K q u :=
  ⟨Aq.yElt K q k i, HJO.Dyck.toTilde_yElt k i⟩

theorem dPlusPow_mem_unstarredAlg (v n : ℕ) : dPlusPow K q u v n ∈ unstarredAlg K q u :=
  dPlusPow_mem_toTilde_range v n

theorem levelAlg_le_unstarredAlg : levelAlg K q u ≤ unstarredAlg K q u :=
  levelAlg_le_toTilde_range

theorem segUpOf_Tg_mem_unstarredAlg (k a n : ℕ) :
    segUpOf (e K q u) (Tg K q u) k a n ∈ unstarredAlg K q u := by
  induction n with
  | zero => exact e_mem_unstarredAlg k
  | succ n ih => exact mul_mem ih (Tg_mem_unstarredAlg k (a + n))

theorem segUpOf_Tinv_mem_unstarredAlg (k a n : ℕ) :
    segUpOf (e K q u) (Tinv K q u) k a n ∈ unstarredAlg K q u := by
  induction n with
  | zero => exact e_mem_unstarredAlg k
  | succ n ih => exact mul_mem ih (Tinv_mem_unstarredAlg k (a + n))

/-! ### The subalgebra of idempotents and loops -/

/-- The subalgebra of `Ã` generated by the idempotents and the loops: the words the starred arrow
and the starred corner element can be pushed past without leaving their own vertex. -/
noncomputable def loopAlg (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : Subalgebra K (Atilde K q u) :=
  Algebra.adjoin K {x | (∃ k, x = e K q u k) ∨ ∃ k s, x = Tg K q u k s}

theorem e_mem_loopAlg (k : ℕ) : e K q u k ∈ loopAlg K q u :=
  Algebra.subset_adjoin (Or.inl ⟨k, rfl⟩)

theorem Tg_mem_loopAlg (k s : ℕ) : Tg K q u k s ∈ loopAlg K q u :=
  Algebra.subset_adjoin (Or.inr ⟨k, s, rfl⟩)

theorem Tinv_mem_loopAlg (k s : ℕ) : Tinv K q u k s ∈ loopAlg K q u := by
  rw [Tinv, tinvOf]
  exact Subalgebra.smul_mem _ (add_mem (Tg_mem_loopAlg k s)
    (Subalgebra.smul_mem _ (e_mem_loopAlg k) _)) _

theorem segUpOf_Tg_mem_loopAlg (k a n : ℕ) :
    segUpOf (e K q u) (Tg K q u) k a n ∈ loopAlg K q u := by
  induction n with
  | zero => exact e_mem_loopAlg k
  | succ n ih => exact mul_mem ih (Tg_mem_loopAlg k (a + n))

theorem tinvWordOf_mem_loopAlg (k n : ℕ) :
    tinvWordOf q ⅟q (e K q u) (Tg K q u) k n ∈ loopAlg K q u := by
  induction n with
  | zero => exact e_mem_loopAlg k
  | succ n ih => exact mul_mem (Tinv_mem_loopAlg k n) ih

/-! ### Where the starred arrow and the starred corner element land -/

/-- **`starMod`**: the span of `𝔸_q·d₊^*` and `𝔸_q·z`. Pushing `d₊^*` rightwards through a word in
the letters `{e, T, y, d₋}` lands here, and every element of it, applied to a terminal raising
block, lands in `𝔸_q𝟏_0 + I𝟏_0`. -/
noncomputable def starMod (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : Submodule K (Atilde K q u) :=
  Submodule.span K {x | (∃ b ∈ unstarredAlg K q u, ∃ k, x = b * dPlusStar K q u k) ∨
    ∃ b ∈ unstarredAlg K q u, ∃ k i, 1 ≤ i ∧ i ≤ k ∧ x = b * zElt K q u k i}

/-- The span of `𝔸_q·z` at one vertex: where `z` pushed past idempotents and loops lands, the vertex
being unchanged because `z` is a loop at it. -/
noncomputable def zMod (K : Type*) [CommRing K] (q u : K) [Invertible q] [Invertible (q - 1)]
    (k : ℕ) : Submodule K (Atilde K q u) :=
  Submodule.span K {x | ∃ b ∈ unstarredAlg K q u, ∃ i, 1 ≤ i ∧ i ≤ k ∧ x = b * zElt K q u k i}

/-- The span of `𝔸_q·d₊^*` at one vertex. -/
noncomputable def dStarMod (K : Type*) [CommRing K] (q u : K) [Invertible q] [Invertible (q - 1)]
    (k : ℕ) : Submodule K (Atilde K q u) :=
  Submodule.span K {x | ∃ b ∈ unstarredAlg K q u, x = b * dPlusStar K q u k}

/-! #### Basic memberships -/

theorem mul_dPlusStar_mem_starMod {b : Atilde K q u} (hb : b ∈ unstarredAlg K q u) (k : ℕ) :
    b * dPlusStar K q u k ∈ starMod K q u := Submodule.subset_span (Or.inl ⟨b, hb, k, rfl⟩)

theorem mul_zElt_mem_starMod {b : Atilde K q u} (hb : b ∈ unstarredAlg K q u) {k i : ℕ}
    (h1 : 1 ≤ i) (hik : i ≤ k) : b * zElt K q u k i ∈ starMod K q u :=
  Submodule.subset_span (Or.inr ⟨b, hb, k, i, h1, hik, rfl⟩)

theorem dPlusStar_mem_starMod (k : ℕ) : dPlusStar K q u k ∈ starMod K q u := by
  simpa using mul_dPlusStar_mem_starMod (one_mem (unstarredAlg K q u)) k

theorem zElt_mem_starMod {k i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) :
    zElt K q u k i ∈ starMod K q u := by
  simpa using mul_zElt_mem_starMod (one_mem (unstarredAlg K q u)) h1 hik

theorem mul_zElt_mem_zMod {b : Atilde K q u} (hb : b ∈ unstarredAlg K q u) {k i : ℕ}
    (h1 : 1 ≤ i) (hik : i ≤ k) : b * zElt K q u k i ∈ zMod K q u k :=
  Submodule.subset_span ⟨b, hb, i, h1, hik, rfl⟩

theorem zElt_mem_zMod {k i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) :
    zElt K q u k i ∈ zMod K q u k := by
  simpa using mul_zElt_mem_zMod (one_mem (unstarredAlg K q u)) h1 hik

theorem mul_dPlusStar_mem_dStarMod {b : Atilde K q u} (hb : b ∈ unstarredAlg K q u) (k : ℕ) :
    b * dPlusStar K q u k ∈ dStarMod K q u k := Submodule.subset_span ⟨b, hb, rfl⟩

theorem dPlusStar_mem_dStarMod (k : ℕ) : dPlusStar K q u k ∈ dStarMod K q u k := by
  simpa using mul_dPlusStar_mem_dStarMod (one_mem (unstarredAlg K q u)) k

theorem zMod_le_starMod (k : ℕ) : zMod K q u k ≤ starMod K q u := by
  refine Submodule.span_le.2 ?_
  rintro z ⟨b, hb, i, h1, hik, rfl⟩
  exact mul_zElt_mem_starMod hb h1 hik

theorem dStarMod_le_starMod (k : ℕ) : dStarMod K q u k ≤ starMod K q u := by
  refine Submodule.span_le.2 ?_
  rintro z ⟨b, hb, rfl⟩
  exact mul_dPlusStar_mem_starMod hb k

/-! #### Left multiplication by the unstarred subalgebra -/

theorem unstarredAlg_mul_mem_starMod {a x : Atilde K q u} (ha : a ∈ unstarredAlg K q u)
    (hx : x ∈ starMod K q u) : a * x ∈ starMod K q u := by
  refine Submodule.span_induction (p := fun z _ => a * z ∈ starMod K q u) ?_ ?_ ?_ ?_ hx
  · rintro z (⟨b, hb, k, rfl⟩ | ⟨b, hb, k, i, h1, hik, rfl⟩)
    · rw [← mul_assoc]; exact mul_dPlusStar_mem_starMod (mul_mem ha hb) k
    · rw [← mul_assoc]; exact mul_zElt_mem_starMod (mul_mem ha hb) h1 hik
  · rw [mul_zero]; exact zero_mem _
  · intro y z _ _ hy hz; rw [mul_add]; exact add_mem hy hz
  · intro c y _ hy; rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

theorem unstarredAlg_mul_mem_zMod {a x : Atilde K q u} (ha : a ∈ unstarredAlg K q u) {k : ℕ}
    (hx : x ∈ zMod K q u k) : a * x ∈ zMod K q u k := by
  refine Submodule.span_induction (p := fun z _ => a * z ∈ zMod K q u k) ?_ ?_ ?_ ?_ hx
  · rintro z ⟨b, hb, i, h1, hik, rfl⟩
    rw [← mul_assoc]; exact mul_zElt_mem_zMod (mul_mem ha hb) h1 hik
  · rw [mul_zero]; exact zero_mem _
  · intro y z _ _ hy hz; rw [mul_add]; exact add_mem hy hz
  · intro c y _ hy; rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

theorem unstarredAlg_mul_mem_dStarMod {a x : Atilde K q u} (ha : a ∈ unstarredAlg K q u) {k : ℕ}
    (hx : x ∈ dStarMod K q u k) : a * x ∈ dStarMod K q u k := by
  refine Submodule.span_induction (p := fun z _ => a * z ∈ dStarMod K q u k) ?_ ?_ ?_ ?_ hx
  · rintro z ⟨b, hb, rfl⟩
    rw [← mul_assoc]; exact mul_dPlusStar_mem_dStarMod (mul_mem ha hb) k
  · rw [mul_zero]; exact zero_mem _
  · intro y z _ _ hy hz; rw [mul_add]; exact add_mem hy hz
  · intro c y _ hy; rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

/-! #### The two transfer lemmas: right multiplication -/

/-- Right multiplication carries `starMod` into itself as soon as it does so on the two generating
shapes. -/
theorem starMod_mul_mem_starMod {x y : Atilde K q u} (hx : x ∈ starMod K q u)
    (hstar : ∀ k, dPlusStar K q u k * y ∈ starMod K q u)
    (hz : ∀ k i, 1 ≤ i → i ≤ k → zElt K q u k i * y ∈ starMod K q u) :
    x * y ∈ starMod K q u := by
  refine Submodule.span_induction (p := fun z _ => z * y ∈ starMod K q u) ?_ ?_ ?_ ?_ hx
  · rintro z (⟨b, hb, k, rfl⟩ | ⟨b, hb, k, i, h1, hik, rfl⟩)
    · rw [mul_assoc]; exact unstarredAlg_mul_mem_starMod hb (hstar k)
    · rw [mul_assoc]; exact unstarredAlg_mul_mem_starMod hb (hz k i h1 hik)
  · rw [zero_mul]; exact zero_mem _
  · intro z w _ _ hzz hw; rw [add_mul]; exact add_mem hzz hw
  · intro c z _ hzz; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hzz

/-- The same for `zMod`, which needs only the `z` shape. -/
theorem zMod_mul_mem_starMod {k : ℕ} {x y : Atilde K q u} (hx : x ∈ zMod K q u k)
    (hz : ∀ i, 1 ≤ i → i ≤ k → zElt K q u k i * y ∈ starMod K q u) :
    x * y ∈ starMod K q u := by
  refine Submodule.span_induction (p := fun z _ => z * y ∈ starMod K q u) ?_ ?_ ?_ ?_ hx
  · rintro z ⟨b, hb, i, h1, hik, rfl⟩
    rw [mul_assoc]; exact unstarredAlg_mul_mem_starMod hb (hz i h1 hik)
  · rw [zero_mul]; exact zero_mem _
  · intro z w _ _ hzz hw; rw [add_mul]; exact add_mem hzz hw
  · intro c z _ hzz; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hzz

theorem zMod_mul_mem_zMod {k : ℕ} {x y : Atilde K q u} (hx : x ∈ zMod K q u k)
    (hz : ∀ i, 1 ≤ i → i ≤ k → zElt K q u k i * y ∈ zMod K q u k) :
    x * y ∈ zMod K q u k := by
  refine Submodule.span_induction (p := fun z _ => z * y ∈ zMod K q u k) ?_ ?_ ?_ ?_ hx
  · rintro z ⟨b, hb, i, h1, hik, rfl⟩
    rw [mul_assoc]; exact unstarredAlg_mul_mem_zMod hb (hz i h1 hik)
  · rw [zero_mul]; exact zero_mem _
  · intro z w _ _ hzz hw; rw [add_mul]; exact add_mem hzz hw
  · intro c z _ hzz; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hzz

theorem dStarMod_mul_mem_dStarMod {k : ℕ} {x y : Atilde K q u} (hx : x ∈ dStarMod K q u k)
    (hs : dPlusStar K q u k * y ∈ dStarMod K q u k) : x * y ∈ dStarMod K q u k := by
  refine Submodule.span_induction (p := fun z _ => z * y ∈ dStarMod K q u k) ?_ ?_ ?_ ?_ hx
  · rintro z ⟨b, hb, rfl⟩
    rw [mul_assoc]; exact unstarredAlg_mul_mem_dStarMod hb hs
  · rw [zero_mul]; exact zero_mem _
  · intro z w _ _ hzz hw; rw [add_mul]; exact add_mem hzz hw
  · intro c z _ hzz; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hzz

/-! ### The vertex, and the two rearranged mixed relations -/

/-- The starred raising arrow out of the vertex `k` annihilates every other idempotent. -/
theorem dPlusStar_mul_e_of_ne {k l : ℕ} (h : l ≠ k) : dPlusStar K q u k * e K q u l = 0 := by
  rw [← dPlusStar_mul_e (K := K) (q := q) (u := u) k, mul_assoc, e_mul_e_of_ne h.symm, mul_zero]

/-- A starred corner element at the vertex `k` annihilates every other idempotent. -/
theorem zElt_mul_e_of_ne {k i l : ℕ} (h : l ≠ k) : zElt K q u k i * e K q u l = 0 := by
  rw [← zElt_mul_e (K := K) (q := q) (u := u) k i, mul_assoc, e_mul_e_of_ne h.symm, mul_zero]

/-- The third mixed relation, solved for `z_1d₊`: the step that creates a `d₊^*` out of nothing but
unstarred letters, and the algebra-level source of the correction term in
`HJO.Standing.exists_action_atilde_ker_eq_param`. -/
theorem zElt_one_mul_dPlus (k : ℕ) :
    zElt K q u (k + 1) 1 * dPlus K q u k
      = -((u * q ^ (k + 1)) • (yElt K q u (k + 1) 1 * dPlusStar K q u k)) :=
  eq_neg_of_add_eq_zero_left (mixed_top k)

/-- The starred commutator split off a product `d₊^*d₋`. -/
theorem dPlusStar_mul_dMinus_eq (k : ℕ) :
    dPlusStar K q u k * dMinus K q u k
      = commOf (dPlusStar K q u) (dMinus K q u) k
        + dMinus K q u (k + 1) * dPlusStar K q u (k + 1) := by
  rw [commOf]; abel

/-- The starred commutator at the vertex `k+1`, as an unstarred word times `z_{k+1}`. -/
theorem commOf_star_mem_zMod (k : ℕ) :
    commOf (dPlusStar K q u) (dMinus K q u) k ∈ zMod K q u (k + 1) := by
  have h := commOf_star_eq_smul_segUpOf_mul_zElt (K := K) (q := q) (u := u) (k := k + 1) (by omega)
  rw [Nat.add_sub_cancel] at h
  rw [h]
  exact Submodule.smul_mem _ _
    (mul_zElt_mem_zMod (segUpOf_Tinv_mem_unstarredAlg (k + 1) 0 k) (by omega) le_rfl)

/-! ### The starred arrow past idempotents and loops -/

theorem dPlusStar_mul_Tg_mem_dStarMod (k l s : ℕ) :
    dPlusStar K q u k * Tg K q u l s ∈ dStarMod K q u k := by
  rcases eq_or_ne l k with rfl | hl
  · rcases le_or_gt (s + 2) l with hs | hs
    · rw [Tg_eq_tinvOf_Tinv, mul_smul_comm, mul_add, mul_smul_comm, dPlusStar_mul_e,
        dPlusStar_mul_Tinv hs]
      exact Submodule.smul_mem _ _ (add_mem
        (mul_dPlusStar_mem_dStarMod (Tinv_mem_unstarredAlg (l + 1) (s + 1)) l)
        (Submodule.smul_mem _ _ (dPlusStar_mem_dStarMod l)))
    · rw [Tg_eq_zero (by omega), mul_zero]; exact zero_mem _
  · rw [← e_mul_Tg (K := K) (q := q) (u := u) l s, ← mul_assoc, dPlusStar_mul_e_of_ne hl, zero_mul]
    exact zero_mem _

/-- The starred raising arrow passes rightwards through any word of idempotents and loops, staying
at its own vertex. -/
theorem dPlusStar_mul_mem_dStarMod (k : ℕ) {a : Atilde K q u} (ha : a ∈ loopAlg K q u) :
    dPlusStar K q u k * a ∈ dStarMod K q u k := by
  induction ha using Algebra.adjoin_induction with
  | mem z hz =>
    obtain ⟨l, rfl⟩ | ⟨l, s, rfl⟩ := hz
    · rcases eq_or_ne l k with rfl | hl
      · rw [dPlusStar_mul_e]; exact dPlusStar_mem_dStarMod l
      · rw [dPlusStar_mul_e_of_ne hl]; exact zero_mem _
    · exact dPlusStar_mul_Tg_mem_dStarMod k l s
  | algebraMap r =>
    rw [Algebra.algebraMap_eq_smul_one, mul_smul_comm, mul_one]
    exact Submodule.smul_mem _ r (dPlusStar_mem_dStarMod k)
  | add x y _ _ hx hy => rw [mul_add]; exact add_mem hx hy
  | mul x y _ _ hx hy => rw [← mul_assoc]; exact dStarMod_mul_mem_dStarMod hx hy

/-- The starred raising arrow past a corner element is the second mixed relation: the subscript goes
up by one and the arrow comes out on the right. -/
theorem dStarMod_mul_yElt_mem_starMod {k : ℕ} {x : Atilde K q u} (hx : x ∈ dStarMod K q u k)
    {j : ℕ} (h1 : 1 ≤ j) (hjk : j ≤ k) : x * yElt K q u k j ∈ starMod K q u := by
  refine Submodule.span_induction (p := fun z _ => z * yElt K q u k j ∈ starMod K q u)
    ?_ ?_ ?_ ?_ hx
  · rintro z ⟨b, hb, rfl⟩
    rw [mul_assoc, ← mixed_y h1 hjk, ← mul_assoc]
    exact mul_dPlusStar_mem_starMod (mul_mem hb (yElt_mem_unstarredAlg (k + 1) (j + 1))) k
  · rw [zero_mul]; exact zero_mem _
  · intro y z _ _ hy hz; rw [add_mul]; exact add_mem hy hz
  · intro c y _ hy; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hy

/-- The starred raising arrow past the unstarred commutator: the commutator is a loop word times the
top corner element, so the arrow travels through the loops and then the second mixed relation
applies. The raw expansion `d₊d₋ - d₋d₊` would not do — it puts `d₊^*` immediately left of a `d₊`,
which no relation of `Ã` moves. -/
theorem dPlusStar_mul_commOf_mem_starMod {k : ℕ} (hk : 1 ≤ k) :
    dPlusStar K q u k * commOf (dPlus K q u) (dMinus K q u) (k - 1) ∈ starMod K q u := by
  rw [commOf_eq_smul_segUpOf_mul_yElt hk, mul_smul_comm]
  refine Submodule.smul_mem _ _ ?_
  rw [← mul_assoc]
  exact dStarMod_mul_yElt_mem_starMod
    (dPlusStar_mul_mem_dStarMod k (segUpOf_Tg_mem_loopAlg k 0 (k - 1))) hk le_rfl

/-! ### The starred arrow past the letters -/

theorem dPlusStar_mul_e_mem_starMod (k l : ℕ) :
    dPlusStar K q u k * e K q u l ∈ starMod K q u := by
  rcases eq_or_ne l k with rfl | hl
  · rw [dPlusStar_mul_e]; exact dPlusStar_mem_starMod l
  · rw [dPlusStar_mul_e_of_ne hl]; exact zero_mem _

theorem dPlusStar_mul_Tg_mem_starMod (k l s : ℕ) :
    dPlusStar K q u k * Tg K q u l s ∈ starMod K q u :=
  dStarMod_le_starMod k (dPlusStar_mul_Tg_mem_dStarMod k l s)

theorem dPlusStar_mul_dMinus_mem_starMod (k l : ℕ) :
    dPlusStar K q u k * dMinus K q u l ∈ starMod K q u := by
  rcases eq_or_ne l k with rfl | hl
  · rw [dPlusStar_mul_dMinus_eq]
    exact add_mem (zMod_le_starMod (l + 1) (commOf_star_mem_zMod l))
      (mul_dPlusStar_mem_starMod (dMinus_mem_unstarredAlg (l + 1)) (l + 1))
  · rw [← e_mul_dMinus (K := K) (q := q) (u := u) l, ← mul_assoc, dPlusStar_mul_e_of_ne hl,
      zero_mul]
    exact zero_mem _

theorem dPlusStar_mul_yElt_mem_starMod (k : ℕ) {l j : ℕ} (h1 : 1 ≤ j) (hjl : j ≤ l) :
    dPlusStar K q u k * yElt K q u l j ∈ starMod K q u := by
  rcases eq_or_ne l k with rfl | hl
  · rw [← mixed_y h1 hjl]
    exact mul_dPlusStar_mem_starMod (yElt_mem_unstarredAlg (l + 1) (j + 1)) l
  · rw [← e_mul_yElt (K := K) (q := q) (u := u) l j, ← mul_assoc, dPlusStar_mul_e_of_ne hl,
      zero_mul]
    exact zero_mem _

/-! ### The starred corner element past the letters -/

section StarSwap

variable {bar : K ≃+* K} {σ : Atilde K q u →+ Atilde K q u}
  (h : IsStarSwap q bar (e K q u) (dPlus K q u) (dPlusStar K q u) (dMinus K q u) (Tg K q u) σ)
  (hbar : bar q = ⅟q)

include h hbar

theorem zElt_mul_Tg_mem_zMod {k i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) (l s : ℕ) :
    zElt K q u k i * Tg K q u l s ∈ zMod K q u k := by
  rcases eq_or_ne l k with rfl | hl
  · refine Submodule.span_le.2 ?_ (zElt_mul_Tg_mem_span h hbar h1 hik)
    rintro x ⟨i', h1', hik', rfl | rfl⟩
    · exact zElt_mem_zMod h1' hik'
    · exact mul_zElt_mem_zMod (Tg_mem_unstarredAlg l s) h1' hik'
  · rw [← e_mul_Tg (K := K) (q := q) (u := u) l s, ← mul_assoc, zElt_mul_e_of_ne hl, zero_mul]
    exact zero_mem _

theorem zElt_mul_Tg_mem_starMod {k i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) (l s : ℕ) :
    zElt K q u k i * Tg K q u l s ∈ starMod K q u :=
  zMod_le_starMod k (zElt_mul_Tg_mem_zMod h hbar h1 hik l s)

omit h hbar in
theorem zElt_mul_e_mem_starMod {k i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) (l : ℕ) :
    zElt K q u k i * e K q u l ∈ starMod K q u := by
  rcases eq_or_ne l k with rfl | hl
  · rw [zElt_mul_e]; exact zElt_mem_starMod h1 hik
  · rw [zElt_mul_e_of_ne hl]; exact zero_mem _

theorem zElt_mul_dMinus_mem_starMod {k i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) (l : ℕ) :
    zElt K q u k i * dMinus K q u l ∈ starMod K q u := by
  rcases eq_or_ne l k with rfl | hl
  · rw [zElt_mul_dMinus h hbar h1 hik]
    exact mul_zElt_mem_starMod (dMinus_mem_unstarredAlg l) h1 (by omega)
  · rw [← e_mul_dMinus (K := K) (q := q) (u := u) l, ← mul_assoc, zElt_mul_e_of_ne hl, zero_mul]
    exact zero_mem _

/-- The starred corner element passes rightwards through any word of idempotents and loops, staying
at its own vertex; the passage is `HJO.Dyck.Tilde.Atilde.zElt_mul_Tg_mem_span`, so the index changes
and scalars appear, but no `d₊^*` is created. -/
theorem zElt_mul_mem_zMod (k : ℕ) {a : Atilde K q u} (ha : a ∈ loopAlg K q u) :
    ∀ i, 1 ≤ i → i ≤ k → zElt K q u k i * a ∈ zMod K q u k := by
  induction ha using Algebra.adjoin_induction with
  | mem z hz =>
    intro i h1 hik
    obtain ⟨l, rfl⟩ | ⟨l, s, rfl⟩ := hz
    · rcases eq_or_ne l k with rfl | hl
      · rw [zElt_mul_e]; exact zElt_mem_zMod h1 hik
      · rw [zElt_mul_e_of_ne hl]; exact zero_mem _
    · exact zElt_mul_Tg_mem_zMod h hbar h1 hik l s
  | algebraMap r =>
    intro i h1 hik
    rw [Algebra.algebraMap_eq_smul_one, mul_smul_comm, mul_one]
    exact Submodule.smul_mem _ r (zElt_mem_zMod h1 hik)
  | add x y _ _ hx hy =>
    intro i h1 hik
    rw [mul_add]
    exact add_mem (hx i h1 hik) (hy i h1 hik)
  | mul x y _ _ hx hy =>
    intro i h1 hik
    rw [← mul_assoc]
    exact zMod_mul_mem_zMod (hx i h1 hik) hy

/-! ### `z` past the unstarred commutator -/

/-- **The starred corner element past the commutator** `d₊d₋ - d₋d₊`. The four cases are the two
terms of the commutator against `i = 1` and `i ≥ 2`: for `i ≥ 2` the first mixed relation drops the
index and only unstarred letters are produced; for `i = 1` the *third* mixed relation fires and
creates a `d₊^*`, which is why `starMod` has to carry a `𝔸_q·d₊^*` summand at all. -/
theorem zElt_mul_commOf_mem_starMod (m : ℕ) {i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ m + 1) :
    zElt K q u (m + 1) i * commOf (dPlus K q u) (dMinus K q u) m ∈ starMod K q u := by
  rw [commOf, mul_sub]
  refine sub_mem ?_ ?_
  · -- `z·d₊d₋`
    rcases Nat.lt_or_ge i 2 with hi | hi
    · obtain rfl : i = 1 := by omega
      rw [← mul_assoc, zElt_one_mul_dPlus,
        neg_mul ((u * q ^ (m + 1)) • (yElt K q u (m + 1) 1 * dPlusStar K q u m))
          (dMinus K q u m)]
      refine neg_mem ?_
      rw [smul_mul_assoc, mul_assoc, dPlusStar_mul_dMinus_eq, mul_add]
      refine Submodule.smul_mem _ _ (add_mem ?_ ?_)
      · exact zMod_le_starMod (m + 1)
          (unstarredAlg_mul_mem_zMod (yElt_mem_unstarredAlg (m + 1) 1) (commOf_star_mem_zMod m))
      · rw [← mul_assoc]
        exact mul_dPlusStar_mem_starMod
          (mul_mem (yElt_mem_unstarredAlg (m + 1) 1) (dMinus_mem_unstarredAlg (m + 1))) (m + 1)
    · obtain ⟨j, rfl⟩ : ∃ j, i = j + 1 := ⟨i - 1, by omega⟩
      rw [← mul_assoc, mixed_z (show 1 ≤ j by omega) (show j ≤ m by omega), mul_assoc,
        zElt_mul_dMinus h hbar (show 1 ≤ j by omega) (show j ≤ m by omega), ← mul_assoc]
      exact mul_zElt_mem_starMod
        (mul_mem (dPlus_mem_unstarredAlg m) (dMinus_mem_unstarredAlg m)) (by omega) (by omega)
  · -- `z·d₋d₊`
    rw [← mul_assoc, zElt_mul_dMinus h hbar h1 hik, mul_assoc]
    rcases Nat.lt_or_ge i 2 with hi | hi
    · obtain rfl : i = 1 := by omega
      rw [zElt_one_mul_dPlus, mul_neg]
      refine neg_mem ?_
      rw [mul_smul_comm, ← mul_assoc]
      refine Submodule.smul_mem _ _ ?_
      exact mul_dPlusStar_mem_starMod
        (mul_mem (dMinus_mem_unstarredAlg (m + 1)) (yElt_mem_unstarredAlg (m + 1 + 1) 1)) (m + 1)
    · obtain ⟨j, rfl⟩ : ∃ j, i = j + 1 := ⟨i - 1, by omega⟩
      rw [mixed_z (show 1 ≤ j by omega) (show j ≤ m + 1 by omega), ← mul_assoc]
      exact mul_zElt_mem_starMod
        (mul_mem (dMinus_mem_unstarredAlg (m + 1)) (dPlus_mem_unstarredAlg (m + 1)))
        (by omega) (by omega)

/-! ### `starMod` is stable under the letters it has moves for -/

omit h hbar in
theorem starMod_mul_e_mem_starMod {x : Atilde K q u} (hx : x ∈ starMod K q u) (l : ℕ) :
    x * e K q u l ∈ starMod K q u :=
  starMod_mul_mem_starMod hx (fun k => dPlusStar_mul_e_mem_starMod k l)
    (fun _ _ h1 hik => zElt_mul_e_mem_starMod h1 hik l)

theorem starMod_mul_Tg_mem_starMod {x : Atilde K q u} (hx : x ∈ starMod K q u) (l s : ℕ) :
    x * Tg K q u l s ∈ starMod K q u :=
  starMod_mul_mem_starMod hx (fun k => dPlusStar_mul_Tg_mem_starMod k l s)
    (fun _ _ h1 hik => zElt_mul_Tg_mem_starMod h hbar h1 hik l s)

theorem starMod_mul_dMinus_mem_starMod {x : Atilde K q u} (hx : x ∈ starMod K q u) (l : ℕ) :
    x * dMinus K q u l ∈ starMod K q u :=
  starMod_mul_mem_starMod hx (fun k => dPlusStar_mul_dMinus_mem_starMod k l)
    (fun _ _ h1 hik => zElt_mul_dMinus_mem_starMod h hbar h1 hik l)

/-! ### `z` past a corner element -/

/-- `z` past the *top* corner element `y_k`, which is the commutator conjugated by a word of inverse
loops. -/
theorem zElt_mul_yElt_top_mem_starMod {k i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) (hk : 1 ≤ k) :
    zElt K q u k i * yElt K q u k k ∈ starMod K q u := by
  obtain ⟨m, rfl⟩ : ∃ m, k = m + 1 := ⟨k - 1, by omega⟩
  have h0 : HJO.Dyck.cornerOf q ⅟q ⅟(q - 1) (e K q u) (dPlus K q u) (dMinus K q u) (Tg K q u)
        (m + 1) (m + 1)
      = ⅟(q - 1) • (tinvWordOf q ⅟q (e K q u) (Tg K q u) (m + 1) m *
          commOf (dPlus K q u) (dMinus K q u) m * e K q u (m + 1)) := by
    simpa only [Nat.add_sub_cancel] using HJO.Dyck.cornerOf_self_eq q ⅟q ⅟(q - 1) (e K q u)
      (dPlus K q u) (dMinus K q u) (Tg K q u) (m + 1)
  have htop : yElt K q u (m + 1) (m + 1)
      = ⅟(q - 1) • (tinvWordOf q ⅟q (e K q u) (Tg K q u) (m + 1) m *
          commOf (dPlus K q u) (dMinus K q u) m * e K q u (m + 1)) := h0
  rw [htop, mul_smul_comm]
  refine Submodule.smul_mem _ _ ?_
  rw [← mul_assoc, ← mul_assoc]
  refine starMod_mul_e_mem_starMod ?_ (m + 1)
  refine zMod_mul_mem_starMod
    (zElt_mul_mem_zMod h hbar (m + 1) (tinvWordOf_mem_loopAlg (m + 1) m) i h1 hik) ?_
  intro i' h1' hik'
  exact zElt_mul_commOf_mem_starMod h hbar m h1' hik'

/-- **`z` past a corner element.** For `1 ≤ i ≤ k` and `1 ≤ j ≤ k`,

    `z_i^{(k)}y_j^{(k)} ∈ span_K { b·d₊^*, b·z_{i'} : b ∈ 𝔸_q }`.

This is the weakest form the span route needs, and a commutation — which a direct proof of
`HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0` would need at its `y_iG` step — is
*false*: the double-affine relation for `z_1y_1` fails in `Ã` by a
correction term carrying `d_-d_+^*`. The `𝔸_q·d₊^*` summand is that correction term; it enters
through the third mixed relation, at `i = 1`, inside
`HJO.Dyck.Tilde.Atilde.zElt_mul_commOf_mem_starMod`.

The proof is a descending induction on `k - j` through the second defining formula of
`HJO.Dyck.Aq.yElt`, bottoming out at the top corner element, where the commutator appears and the
mixed relations fire. -/
theorem zElt_mul_yElt_mem_starMod_aux :
    ∀ d k i j : ℕ, 1 ≤ i → i ≤ k → 1 ≤ j → j ≤ k → k - j ≤ d →
      zElt K q u k i * yElt K q u k j ∈ starMod K q u := by
  intro d
  induction d with
  | zero =>
    intro k i j h1 hik hj1 hjk hd
    obtain rfl : j = k := by omega
    exact zElt_mul_yElt_top_mem_starMod h hbar h1 hik (by omega)
  | succ d ih =>
    intro k i j h1 hik hj1 hjk hd
    rcases eq_or_lt_of_le hjk with rfl | hjlt
    · exact zElt_mul_yElt_top_mem_starMod h hbar h1 hik (by omega)
    · have hrec : yElt K q u k j
          = ⅟q • (Tg K q u k (j - 1) * yElt K q u k (j + 1) * Tg K q u k (j - 1)) :=
        HJO.Dyck.cornerOf_recursion hj1 hjlt
      rw [hrec, mul_smul_comm]
      refine Submodule.smul_mem _ _ ?_
      rw [← mul_assoc, ← mul_assoc]
      refine starMod_mul_Tg_mem_starMod h hbar ?_ k (j - 1)
      refine zMod_mul_mem_starMod (zElt_mul_Tg_mem_zMod h hbar h1 hik k (j - 1)) ?_
      intro i' h1' hik'
      exact ih k i' (j + 1) h1' hik' (by omega) (by omega) (by omega)

/-- **`z` past a corner element**, as used. -/
theorem zElt_mul_yElt_mem_starMod {k i j : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) (hj1 : 1 ≤ j)
    (hjk : j ≤ k) : zElt K q u k i * yElt K q u k j ∈ starMod K q u :=
  zElt_mul_yElt_mem_starMod_aux h hbar (k - j) k i j h1 hik hj1 hjk le_rfl

theorem zElt_mul_yElt_mem_starMod' {k i l j : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) (hj1 : 1 ≤ j)
    (hjl : j ≤ l) : zElt K q u k i * yElt K q u l j ∈ starMod K q u := by
  rcases eq_or_ne l k with rfl | hl
  · exact zElt_mul_yElt_mem_starMod h hbar h1 hik hj1 hjl
  · rw [← e_mul_yElt (K := K) (q := q) (u := u) l j, ← mul_assoc, zElt_mul_e_of_ne hl, zero_mul]
    exact zero_mem _

theorem starMod_mul_yElt_mem_starMod {x : Atilde K q u} (hx : x ∈ starMod K q u) {l j : ℕ}
    (hj1 : 1 ≤ j) (hjl : j ≤ l) : x * yElt K q u l j ∈ starMod K q u :=
  starMod_mul_mem_starMod hx (fun k => dPlusStar_mul_yElt_mem_starMod k hj1 hjl)
    (fun _ _ hi1 hik => zElt_mul_yElt_mem_starMod' h hbar hi1 hik hj1 hjl)

/-! ### The structural induction: `starMod` absorbs the whole letter algebra -/

/-- **`starMod` is a right `levelAlg`-module.** Every letter of
`HJO.Dyck.Tilde.Atilde.levelSet` has a move, so the whole subalgebra they generate does, by
induction on the formation of the element — no measure and no normal form. -/
theorem starMod_mul_mem_starMod_of_mem_levelAlg {x : Atilde K q u} (hx : x ∈ starMod K q u)
    {a : Atilde K q u} (ha : a ∈ levelAlg K q u) : x * a ∈ starMod K q u := by
  induction ha using Algebra.adjoin_induction generalizing x with
  | mem z hz =>
    obtain ⟨l, rfl⟩ | ⟨l, s, rfl⟩ | ⟨l, j, hj1, hjl, rfl⟩ | ⟨l, rfl⟩ := hz
    · exact starMod_mul_e_mem_starMod hx l
    · exact starMod_mul_Tg_mem_starMod h hbar hx l s
    · exact starMod_mul_yElt_mem_starMod h hbar hx hj1 hjl
    · exact starMod_mul_dMinus_mem_starMod h hbar hx l
  | algebraMap r =>
    rw [Algebra.algebraMap_eq_smul_one, mul_smul_comm, mul_one]
    exact Submodule.smul_mem _ r hx
  | add y z _ _ hy hz => rw [mul_add]; exact add_mem (hy hx) (hz hx)
  | mul y z _ _ hy hz => rw [← mul_assoc]; exact hz (hy hx)

/-- **The starred arrow pushed rightwards through a letter word.** -/
theorem dPlusStar_mul_mem_starMod (k : ℕ) {a : Atilde K q u} (ha : a ∈ levelAlg K q u) :
    dPlusStar K q u k * a ∈ starMod K q u :=
  starMod_mul_mem_starMod_of_mem_levelAlg h hbar (dPlusStar_mem_starMod k) ha

end StarSwap

/-! ### Applying the result to a terminal raising block -/

theorem unstarredAlg_mul_mem_raisingSpan {b : Atilde K q u} (hb : b ∈ unstarredAlg K q u)
    {x : Atilde K q u} (hx : x ∈ raisingSpan K q u) : b * x ∈ raisingSpan K q u := by
  obtain ⟨y, rfl⟩ := hb
  obtain ⟨w, rfl⟩ := RingQuot.mkAlgHom_surjective K (HJO.Dyck.Rel K q) y
  have hmk : HJO.Dyck.toTilde K q u (Aq.mk K q w) = HJO.Dyck.freeToTilde K q u w :=
    HJO.Dyck.toTilde_mk w
  change HJO.Dyck.toTilde K q u (Aq.mk K q w) * x ∈ raisingSpan K q u
  rw [hmk]
  exact freeToTilde_mul_mem_raisingSpan w hx

theorem unstarredAlg_mul_mem_sup {b x : Atilde K q u} (hb : b ∈ unstarredAlg K q u)
    (hx : x ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u) :
    b * x ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u := by
  obtain ⟨p, hp, r, hr, rfl⟩ := Submodule.mem_sup.1 hx
  rw [mul_add]
  exact add_mem (Submodule.mem_sup_left (unstarredAlg_mul_mem_raisingSpan hb hp))
    (Submodule.mem_sup_right (mul_mem_kernelIdealE0 b hr))

theorem dPlusStar_mul_dPlusPow_of_ne {k n : ℕ} (hk : k ≠ n) :
    dPlusStar K q u k * dPlusPow K q u 0 n = 0 := by
  rw [← e_mul_dPlusPow (K := K) (q := q) (u := u) 0 n, Nat.zero_add, ← mul_assoc,
    dPlusStar_mul_e_of_ne hk.symm, zero_mul]

theorem zElt_mul_dPlusPow_of_ne {k i n : ℕ} (hk : k ≠ n) :
    zElt K q u k i * dPlusPow K q u 0 n = 0 := by
  rw [← e_mul_dPlusPow (K := K) (q := q) (u := u) 0 n, Nat.zero_add, ← mul_assoc,
    zElt_mul_e_of_ne hk.symm, zero_mul]

/-- The starred arrow on a terminal raising block: the generators of `I` retire it. -/
theorem dPlusStar_mul_dPlusPow_mem_sup (k n : ℕ) :
    dPlusStar K q u k * dPlusPow K q u 0 n ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u := by
  rcases eq_or_ne k n with rfl | hk
  · rw [dPlusStar_mul_dPlusPow_eq]
    exact add_mem (Submodule.mem_sup_left (dPlusPow_mem_raisingSpan (k + 1)))
      (Submodule.mem_sup_right (dPlusStar_mul_dPlusPow_sub_mem_kernelIdealE0 k))
  · rw [dPlusStar_mul_dPlusPow_of_ne hk]; exact zero_mem _

/-- The starred corner element on a terminal raising block: it is unstarred modulo `I𝟏_0`, by
`HJO.Dyck.Tilde.Atilde.zElt_mul_dPlusPow_sub_mem_kernelIdealE0`, and what it becomes is an unstarred
word, so it lies in `𝔸_q𝟏_0` by `HJO.Dyck.Tilde.Atilde.aqE0_eq_raisingSpan`. -/
theorem zElt_mul_dPlusPow_mem_sup {k i : ℕ} (h1 : 1 ≤ i) (hik : i ≤ k) (n : ℕ) :
    zElt K q u k i * dPlusPow K q u 0 n ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u := by
  rcases eq_or_ne k n with rfl | hk
  · obtain ⟨m, hm⟩ : ∃ m, k = m + 1 + (i - 1) := ⟨k - i, by omega⟩
    obtain ⟨j, hj⟩ : ∃ j, i = j + 1 := ⟨i - 1, by omega⟩
    subst hj
    simp only [Nat.add_sub_cancel] at hm
    subst hm
    have hmem := zElt_mul_dPlusPow_sub_mem_kernelIdealE0 (K := K) (q := q) (u := u) m j
    have hy : dPlusPow K q u (m + 1) j * (yElt K q u (m + 1) 1 * dPlusPow K q u 0 (m + 1))
        ∈ raisingSpan K q u := by
      rw [← mul_assoc]
      exact unstarredAlg_mul_mem_raisingSpan
        (mul_mem (dPlusPow_mem_unstarredAlg (m + 1) j) (yElt_mem_unstarredAlg (m + 1) 1))
        (dPlusPow_mem_raisingSpan (m + 1))
    have hsplit : zElt K q u (m + 1 + j) (j + 1) * dPlusPow K q u 0 (m + 1 + j)
        = (zElt K q u (m + 1 + j) (j + 1) * dPlusPow K q u 0 (m + 1 + j)
            + (u * q ^ (m + 1)) • (dPlusPow K q u (m + 1) j *
              (yElt K q u (m + 1) 1 * dPlusPow K q u 0 (m + 1))))
          - (u * q ^ (m + 1)) • (dPlusPow K q u (m + 1) j *
              (yElt K q u (m + 1) 1 * dPlusPow K q u 0 (m + 1))) := by abel
    rw [hsplit]
    exact sub_mem (Submodule.mem_sup_right hmem)
      (Submodule.mem_sup_left (Submodule.smul_mem _ _ hy))
  · rw [zElt_mul_dPlusPow_of_ne hk]; exact zero_mem _

/-- **Everything in `starMod`, applied to a terminal raising block, lands in `𝔸_q𝟏_0 + I𝟏_0`.** -/
theorem starMod_mul_dPlusPow_mem_sup {x : Atilde K q u} (hx : x ∈ starMod K q u) (n : ℕ) :
    x * dPlusPow K q u 0 n ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u := by
  refine Submodule.span_induction
    (p := fun z _ => z * dPlusPow K q u 0 n ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u)
    ?_ ?_ ?_ ?_ hx
  · rintro z (⟨b, hb, k, rfl⟩ | ⟨b, hb, k, i, h1, hik, rfl⟩)
    · rw [mul_assoc]
      exact unstarredAlg_mul_mem_sup hb (dPlusStar_mul_dPlusPow_mem_sup k n)
    · rw [mul_assoc]
      exact unstarredAlg_mul_mem_sup hb (zElt_mul_dPlusPow_mem_sup h1 hik n)
  · rw [zero_mul]; exact zero_mem _
  · intro y z _ _ hy hz; rw [add_mul]; exact add_mem hy hz
  · intro c y _ hy; rw [smul_mul_assoc]; exact Submodule.smul_mem _ c hy

/-! ### The starred arrow on the unstarred image -/

section Node

variable {bar : K ≃+* K} {σ : Atilde K q u →+ Atilde K q u}
  (h : IsStarSwap q bar (e K q u) (dPlus K q u) (dPlusStar K q u) (dMinus K q u) (Tg K q u) σ)
  (hbar : bar q = ⅟q)

include h hbar

/-- The core of `HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0`, stated on the
span of `HJO.Dyck.Tilde.Atilde.raisingSpan`. -/
theorem dPlusStar_mul_raisingSpan_mem_sup (k : ℕ) {x : Atilde K q u}
    (hx : x ∈ raisingSpan K q u) :
    dPlusStar K q u k * x ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u := by
  refine Submodule.span_induction
    (p := fun z _ => dPlusStar K q u k * z ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u)
    ?_ ?_ ?_ ?_ hx
  · rintro z ⟨a, ha, n, rfl⟩
    rw [← mul_assoc]
    exact starMod_mul_dPlusPow_mem_sup (dPlusStar_mul_mem_starMod h hbar k ha) n
  · rw [mul_zero]; exact zero_mem _
  · intro y z _ _ hy hz; rw [mul_add]; exact add_mem hy hz
  · intro c y _ hy; rw [mul_smul_comm]; exact Submodule.smul_mem _ c hy

/-- **The starred arrow does not leave the unstarred image.**
The image of `𝔸_q𝟏_0` in `Ã𝟏_0/I𝟏_0` is carried into itself by `d₊^*`.

Three things about this proof are worth recording.

*There is no induction hypothesis.* An induction would suppose the image already contains everything
of arrow degree at most `m` and conclude about degree `m`. The span route needs no such supposition:
`HJO.Dyck.Tilde.Atilde.aqE0_eq_raisingSpan` puts every element of the image in the form
`v_1 ⋯ v_r d₊^n𝟏_0` with the letters `v_i` free of `d₊`, and `d₊^*` is pushed rightwards through the
letters — past `T` by the starred `up_braid`, past `y` by `mixed_y`, past `d₋` by the starred
commutator, which is where a `z` appears — until it meets the terminal block, which the generators
of `I` retire. Nothing is measured and nothing is straightened, so the measure
`HJO.Dyck.straightenMeasure`, which the second straightening move raises
(`HJO.Dyck.straightenMeasure_lt_moveTwo`), is never consulted.

*The `z` that the starred commutator creates is placed by three lemmas*:
`HJO.Dyck.Tilde.Atilde.zElt_mul_Tg_mem_span` (past a loop, a span and not a commutation),
`HJO.Dyck.Tilde.Atilde.zElt_mul_dMinus` (past a lowering arrow, a genuine commutation), and
`HJO.Dyck.Tilde.Atilde.zElt_mul_yElt_mem_starMod` (past a corner element, where the failure of the
double-affine relation recorded under `HJO.Standing.exists_action_atilde_ker_eq_param` shows up as a
`d₊^*` with no `z` in it).

*It carries the hypotheses of `HJO.Sym.paramInvLambda`.* The three `z` moves are starred images of
`𝔸_q` facts and are obtained with a star swap, so a ring involution of `K` inverting `q` is assumed;
`Ã` admits one by `HJO.Dyck.Tilde.Atilde.exists_isStarSwap` as soon as `HJO.Sym.paramInvLambda`
holds and `u` is invertible. The statement below carries these hypotheses explicitly.

The conclusion is in fact stronger than an induction on arrow degree would need: there is **no
arrow-degree induction hypothesis** at all, so the straightening measure of the proof of
`HJO.Sweep.exists_linearEquiv_e0Ideal` is never consulted. Removing the involution hypothesis too
means lifting `HJO.Dyck.Aq.yElt_mul_Tg_comm` and `HJO.Dyck.Aq.yElt_mul_dMinus` to
`HJO.Dyck.CornerFamily`, which needs new fields on that structure; the adjacent-index half is
already generic. -/
@[hjo "lem_cm_kernel_dplus_star_step"]
theorem dPlusStar_mul_mem_aqE0_sup_kernelIdealE0 (k : ℕ) {x : Atilde K q u}
    (hx : x ∈ aqE0 K q u) :
    dPlusStar K q u k * x ∈ aqE0 K q u ⊔ kernelIdealE0 K q u := by
  rw [aqE0_eq_raisingSpan] at hx ⊢
  exact dPlusStar_mul_raisingSpan_mem_sup h hbar k hx

/-! ### The image of `𝔸_q𝟏_0` exhausts `Ã𝟏_0` modulo `I𝟏_0` -/

theorem dPlusStar_mul_mem_sup (k : ℕ) {y : Atilde K q u}
    (hy : y ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u) :
    dPlusStar K q u k * y ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u := by
  obtain ⟨p, hp, r, hr, rfl⟩ := Submodule.mem_sup.1 hy
  rw [mul_add]
  exact add_mem (dPlusStar_mul_raisingSpan_mem_sup h hbar k hp)
    (Submodule.mem_sup_right (mul_mem_kernelIdealE0 _ hr))

/-- Every word in the generators of `Ã` carries `𝔸_q𝟏_0 + I𝟏_0` into itself: the unstarred letters
because it is the image of a subalgebra, and `d₊^*` by
`HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0`. -/
theorem mk_mul_mem_sup (w : FreeAlgebra K Tilde.Gen) {y : Atilde K q u}
    (hy : y ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u) :
    mk K q u w * y ∈ raisingSpan K q u ⊔ kernelIdealE0 K q u := by
  induction w using FreeAlgebra.induction generalizing y with
  | grade0 r =>
    rw [AlgHom.commutes, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
    exact Submodule.smul_mem _ r hy
  | grade1 g =>
    cases g with
    | vertex l =>
      change e K q u l * y ∈ _
      exact unstarredAlg_mul_mem_sup (e_mem_unstarredAlg l) hy
    | up l =>
      change dPlus K q u l * y ∈ _
      exact unstarredAlg_mul_mem_sup (dPlus_mem_unstarredAlg l) hy
    | upStar l =>
      change dPlusStar K q u l * y ∈ _
      exact dPlusStar_mul_mem_sup h hbar l hy
    | down l =>
      change dMinus K q u l * y ∈ _
      exact unstarredAlg_mul_mem_sup (dMinus_mem_unstarredAlg l) hy
    | braid l i =>
      change Tg K q u l i * y ∈ _
      exact unstarredAlg_mul_mem_sup (Tg_mem_unstarredAlg l i) hy
  | mul a b ha hb => rw [map_mul, mul_assoc]; exact ha (hb hy)
  | add a b ha hb => rw [map_add, add_mul]; exact add_mem (ha hy) (hb hy)

/-- **`Ã𝟏_0 = 𝔸_q𝟏_0 + I𝟏_0`**: the image of `𝔸_q𝟏_0` in `Ã𝟏_0/I𝟏_0` is *everything*.

This is the whole of `HJO.Standing.atildeE0_inf_ker_evalOne_eq_param`'s induction — the half of that
statement that lives in the algebra. It is usually run as an induction on the arrow degree; no
induction on degree is used here, because
`HJO.Dyck.Tilde.Atilde.dPlusStar_mul_mem_aqE0_sup_kernelIdealE0` needs none. What
`HJO.Standing.atildeE0_inf_ker_evalOne_eq_param` needs beyond this is the *injectivity* of the
induced map on the image of `𝔸_q𝟏_0`, which rests on `HJO.Sweep.exists_linearEquiv_e0Ideal` (proved
in `HJO/CMStructure/Thm52Injective.lean`). -/
theorem atildeE0_eq_aqE0_sup_kernelIdealE0 :
    atildeE0 K q u = aqE0 K q u ⊔ kernelIdealE0 K q u := by
  rw [aqE0_eq_raisingSpan]
  refine le_antisymm ?_ (sup_le ?_ ?_)
  · rintro _ ⟨x, rfl⟩
    obtain ⟨w, rfl⟩ := RingQuot.mkAlgHom_surjective K (Tilde.Rel K q u) x
    change mk K q u w * e K q u 0 ∈ _
    exact mk_mul_mem_sup h hbar w (Submodule.mem_sup_left e0_mem_raisingSpan)
  · refine Submodule.span_le.2 ?_
    rintro z ⟨a, ha, n, rfl⟩
    exact ⟨a * dPlusPow K q u 0 n, by rw [rightE0_apply, mul_assoc, dPlusPow_mul_e]⟩
  · rintro _ ⟨z, _, rfl⟩
    exact ⟨z, rfl⟩

end Node

end HJO.Dyck.Tilde.Atilde
