/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import Mathlib.RingTheory.TwoSidedIdeal.Operations
public import HJO.CarlssonMellit.StarSwap
public meta import HJO.Attr

/-! # The mixed ideal of `𝔹`, and its stability under a star swap

`HJO.Dyck.TwoSided.Bq.mixedIdeal`: `J` is the two-sided ideal of `𝔹` of `HJO.Dyck.TwoSided.Bq`
generated, for every `k ≥ 0` and every admissible index `i`, by the three elements

    `z_{i+1}d₊ - d₊z_i`,   `y_{i+1}d₊^* - d₊^*y_i`,   `z_1d₊ + uq^{k+1}y_1d₊^*`,

which are the three further relations of `HJO.Dyck.Tilde.Atilde` read in `𝔹`.

`HJO.Dyck.TwoSided.Bq.IsStarSwap.mem_mixedIdeal`: if `σ` is a star swap of `𝔹` then `σ(J) ⊆ J`.

## A two-sided ideal, and why `Ideal` will not do

`Ideal R` in Mathlib is `Submodule R R`, the *left* ideal notion, and `𝔹` is very far from
commutative: the first two generators are the relations `z_{i+1}d₊ = d₊z_i` and
`y_{i+1}d₊^* = d₊^*y_i`, whose whole content is that two orders of multiplication agree. So `J` is
`TwoSidedIdeal (Bq K q)`, and the kernel ideal `I` of `HJO.Dyck.Tilde.Atilde.kernelIdeal` stays an
`Ideal` (a left ideal), which is how it is defined.

## The index ranges, and the vertex each element is read at

The three generators are read at the vertex at which their paths begin, exactly as
`HJO.Dyck.Tilde.Rel` reads the three mixed relations: `d₊ : k → k+1` is `dPlus k`, so in
`z_{i+1}d₊ - d₊z_i` the left `z_{i+1}` is a corner element at the vertex `k+1` and the right `z_i`
one at the vertex `k`, and the "admissible index" is `1 ≤ i ≤ k`. In the third
generator both corner elements sit at the vertex `k+1` and the scalar is `uq^{k+1}`.

Those ranges are not decoration either: `HJO.Dyck.TwoSided.Bq.zElt` and `yElt` are the intended
elements only at `1 ≤ i ≤ k`, and `HJO.Dyck.IsStarSwap.map_cornerOf` — which is what carries `y_i`
to `z_i` — is stated exactly there.

## No surjectivity, and `q ≠ 0`, `q ≠ 1`, `u ≠ 0`

`HJO.Dyck.TwoSided.Bq.IsStarSwap.mem_mixedIdeal` needs `bar q = q⁻¹` and `bar u = u⁻¹`, so it
carries `[Invertible u]` alongside the `[Invertible q]` and `[Invertible (q-1)]` that `𝔹` and the
corner elements already carry. The third generator is where `u` enters: `σ` sends it to
`u^{-1}q^{-(k+1)}` times itself, so the inverse of `u` has to exist for the image to be a scalar
multiple of the generator rather than a new element. As in
`HJO.Dyck.Tilde.Atilde.IsStarSwap.mem_kernelIdeal`, the closing induction needs no surjectivity of
`σ`: `TwoSidedIdeal.span_induction` only ever asks for `σ(ax) = σ(a)σ(x)` and `σ(xb) = σ(x)σ(b)`,
and `J` absorbs on both sides.

## Main definitions

* `HJO.Dyck.TwoSided.Bq.mixedIdeal`.

## Main results

* `HJO.Dyck.TwoSided.Bq.IsStarSwap.mem_mixedIdeal`.

## References

Transcribing E. Carlsson and A. Mellit, *A proof of the shuffle conjecture*, J. Amer. Math.
Soc. **31** (2018) 661--697, Section 3.
-/

@[expose] public section

namespace HJO.Dyck.TwoSided.Bq

variable {K : Type*} [CommRing K] {q u : K} [Invertible q] [Invertible (q - 1)]

/-! ### The three families of generators -/

variable (K q) in
/-- The first family of generators of `J`: the relation `z_{i+1}d₊ = d₊z_i`, at the vertex `k` with
`1 ≤ i ≤ k`. -/
def mixedGenZ : Set (Bq K q) :=
  {x | ∃ k i : ℕ, 1 ≤ i ∧ i ≤ k ∧
    x = zElt K q (k + 1) (i + 1) * dPlus K q k - dPlus K q k * zElt K q k i}

variable (K q) in
/-- The second family of generators of `J`: the relation `y_{i+1}d₊^* = d₊^*y_i`, at the vertex `k`
with `1 ≤ i ≤ k`. -/
def mixedGenY : Set (Bq K q) :=
  {x | ∃ k i : ℕ, 1 ≤ i ∧ i ≤ k ∧
    x = yElt K q (k + 1) (i + 1) * dPlusStar K q k - dPlusStar K q k * yElt K q k i}

variable (K q u) in
/-- The third family of generators of `J`: the relation `z_1d₊ + uq^{k+1}y_1d₊^* = 0`, at the
vertex `k`. -/
def mixedGenTop : Set (Bq K q) :=
  {x | ∃ k : ℕ, x = zElt K q (k + 1) 1 * dPlus K q k
    + (u * q ^ (k + 1)) • (yElt K q (k + 1) 1 * dPlusStar K q k)}

/-- **The mixed ideal `J` of `𝔹`.** The two-sided ideal generated by the three
families above — the three further relations of `HJO.Dyck.Tilde.Atilde`, read in `𝔹`, where `y_i`
and `z_i` exist because the unstarred and the starred group have already been imposed. -/
@[hjo "def_cm_mixed_ideal"]
noncomputable def mixedIdeal (K : Type*) [CommRing K] (q u : K) [Invertible q]
    [Invertible (q - 1)] : TwoSidedIdeal (Bq K q) :=
  TwoSidedIdeal.span (mixedGenZ K q ∪ mixedGenY K q ∪ mixedGenTop K q u)

theorem mixedGenZ_subset_mixedIdeal : mixedGenZ K q ⊆ (mixedIdeal K q u : Set (Bq K q)) :=
  fun _ hx => TwoSidedIdeal.subset_span (Set.mem_union_left _ (Set.mem_union_left _ hx))

theorem mixedGenY_subset_mixedIdeal : mixedGenY K q ⊆ (mixedIdeal K q u : Set (Bq K q)) :=
  fun _ hx => TwoSidedIdeal.subset_span (Set.mem_union_left _ (Set.mem_union_right _ hx))

theorem mixedGenTop_subset_mixedIdeal : mixedGenTop K q u ⊆ (mixedIdeal K q u : Set (Bq K q)) :=
  fun _ hx => TwoSidedIdeal.subset_span (Set.mem_union_right _ hx)

/-- A scalar multiple of an element of `J` lies in `J`: `cx` is `(c·1)x` and `J` absorbs on the
left. -/
theorem smul_mem_mixedIdeal (c : K) {x : Bq K q} (hx : x ∈ mixedIdeal K q u) :
    c • x ∈ mixedIdeal K q u := by
  rw [Algebra.smul_def]
  exact TwoSidedIdeal.mul_mem_left _ _ _ hx

/-! ### A star swap preserves the mixed ideal -/

namespace IsStarSwap

variable [Invertible u] {bar : K ≃+* K} {σ : Bq K q →+ Bq K q}
variable (h : IsStarSwap q bar (e K q) (dPlus K q) (dPlusStar K q) (dMinus K q) (Tg K q) σ)
  (hbar : bar q = ⅟q)

include h hbar

/-- **A star swap preserves the mixed ideal.** The first generator goes to
the second and the second to the first, `σ` being multiplicative, exchanging the two raising arrows,
and carrying `y_i` to `z_i` and back by `HJO.Dyck.IsStarSwap.map_cornerOf` and
`HJO.Dyck.IsStarSwap.map_cornerOf_symm`. The third goes to `u^{-1}q^{-(k+1)}` times itself:
`σ(z_1d₊ + uq^{k+1}y_1d₊^*) = y_1d₊^* + u^{-1}q^{-(k+1)}z_1d₊`, and multiplying the generator by
that scalar gives the same element back, `u^{-1}q^{-(k+1)}·uq^{k+1}` being `1`. In each case the
value lies in `J`, and the span is closed by induction, `J` absorbing on both sides. -/
@[hjo "lem_cm_star_swap_mixed"]
theorem mem_mixedIdeal (hbaru : bar u = ⅟u) {x : Bq K q} (hx : x ∈ mixedIdeal K q u) :
    σ x ∈ mixedIdeal K q u := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem x hxs =>
    rcases hxs with (⟨k, i, hi, hik, rfl⟩ | ⟨k, i, hi, hik, rfl⟩) | ⟨k, rfl⟩
    · rw [map_sub, h.map_mul, h.map_mul, h.map_dPlus,
        IsStarSwap.map_zElt h hbar (by omega : 1 ≤ i + 1) (by omega : i + 1 ≤ k + 1),
        IsStarSwap.map_zElt h hbar hi hik]
      exact mixedGenY_subset_mixedIdeal ⟨k, i, hi, hik, rfl⟩
    · rw [map_sub, h.map_mul, h.map_mul, h.map_dPlusStar,
        IsStarSwap.map_yElt h hbar (by omega : 1 ≤ i + 1) (by omega : i + 1 ≤ k + 1),
        IsStarSwap.map_yElt h hbar hi hik]
      exact mixedGenZ_subset_mixedIdeal ⟨k, i, hi, hik, rfl⟩
    · have hscal : bar (u * q ^ (k + 1)) = ⅟u * ⅟q ^ (k + 1) := by
        rw [map_mul, map_pow, hbar, hbaru]
      have hone : ⅟u * ⅟q ^ (k + 1) * (u * q ^ (k + 1)) = 1 := by
        rw [show ⅟u * ⅟q ^ (k + 1) * (u * q ^ (k + 1))
          = ⅟u * u * (⅟q ^ (k + 1) * q ^ (k + 1)) from by ring, invOf_mul_self,
          ← mul_pow, invOf_mul_self, one_pow, mul_one]
      have himg : σ (zElt K q (k + 1) 1 * dPlus K q k
            + (u * q ^ (k + 1)) • (yElt K q (k + 1) 1 * dPlusStar K q k))
          = (⅟u * ⅟q ^ (k + 1)) • (zElt K q (k + 1) 1 * dPlus K q k
            + (u * q ^ (k + 1)) • (yElt K q (k + 1) 1 * dPlusStar K q k)) := by
        rw [map_add, h.map_smul, h.map_mul, h.map_mul, h.map_dPlus, h.map_dPlusStar,
          IsStarSwap.map_zElt h hbar le_rfl (by omega : 1 ≤ k + 1),
          IsStarSwap.map_yElt h hbar le_rfl (by omega : 1 ≤ k + 1), hscal, smul_add, smul_smul,
          hone, one_smul]
        abel
      rw [himg]
      exact smul_mem_mixedIdeal _ (mixedGenTop_subset_mixedIdeal ⟨k, rfl⟩)
  | zero => rw [map_zero]; exact TwoSidedIdeal.zero_mem _
  | add x y _ _ ihx ihy => rw [map_add]; exact TwoSidedIdeal.add_mem _ ihx ihy
  | neg x _ ih => rw [map_neg]; exact TwoSidedIdeal.neg_mem _ ih
  | left_absorb a x _ ih => rw [h.map_mul]; exact TwoSidedIdeal.mul_mem_left _ _ _ ih
  | right_absorb b x _ ih => rw [h.map_mul]; exact TwoSidedIdeal.mul_mem_right _ _ _ ih

end IsStarSwap

end HJO.Dyck.TwoSided.Bq
