/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.CarlssonMellit.DPATildeIdeals
public import HJO.CarlssonMellit.StarSwap
public meta import HJO.Attr

/-! # The kernel ideal is stable under a star swap

`HJO.Dyck.Tilde.Atilde.dPlus_mul_dPlusStarPow_sub_mem_kernelIdeal`: for every `m ≥ 0` the element
`d₊d₊^{*m} - d₊^{*(m+1)}` of `Ã` lies in the left ideal `I` of `HJO.Dyck.Tilde.Atilde.kernelIdeal`.

`HJO.Dyck.Tilde.Atilde.IsStarSwap.mem_kernelIdeal`: if `σ` is a star swap of `Ã` then `σ(I) ⊆ I`.

## The generators are read at a vertex, as everywhere in this library

`HJO.Dyck.Tilde.Atilde.kernelIdeal` writes its generators `d₊^*d₊^m - d₊^{m+1}` with no vertex, and
`HJO.Dyck.Tilde.Atilde.kernelIdeal` reads each at the vertex `v` at which its paths begin,
generating over all `v`. The two statements below are therefore stated at every `v` as well; the
note on `HJO.Dyck.Tilde.Atilde.kernelIdeal` records why `I𝟏_0` — the only thing the structure
theorem reads — does not depend on the indexing.

## No surjectivity is used

The closing step is "a left ideal generated by a set that an additive multiplicative map
carries into `I` is carried into `I`, since the map carries `Ãg_j` into `ÃI ⊆ I`" — which as written
would want `σ` surjective to recover all of `Ã`. It is not needed and is not used:
`Submodule.span_induction` on the span only ever needs `σ(ax) = σ(a)σ(x) ∈ I` from `x`'s membership,
`I` being a left ideal. A star swap *is* surjective, by `HJO.Dyck.IsStarSwap.surjective`, but that
is not what closes this.

## Main results

* `HJO.Dyck.Tilde.Atilde.dPlus_mul_dPlusStarPow_sub_mem_kernelIdeal`:
  `HJO.Dyck.Tilde.Atilde.dPlus_mul_dPlusStarPow_sub_mem_kernelIdeal`.
* `HJO.Dyck.Tilde.Atilde.IsStarSwap.mem_kernelIdeal`.

## References

Lemmas `HJO.Dyck.Tilde.Atilde.dPlus_mul_dPlusStarPow_sub_mem_kernelIdeal` and
`HJO.Dyck.Tilde.Atilde.IsStarSwap.mem_kernelIdeal`; and `HJO.Dyck.Tilde.Atilde.kernelIdeal`,
`HJO.Dyck.Tilde.Atilde`, `HJO.Dyck.IsStarSwap`, with
`HJO.Dyck.Tilde.Atilde.dPlusStarPow_sub_dPlusPow_mem_kernelIdeal`. Transcribing E. Carlsson and
A. Mellit, *A proof of the shuffle conjecture*, J. Amer. Math. Soc. **31** (2018) 661--697,
Section 3.
-/

@[expose] public section

namespace HJO.Dyck.Tilde.Atilde

variable {K : Type*} [CommRing K] {q u : K} [Invertible q] [Invertible (q - 1)]

/-! ### The swapped generators lie in the kernel ideal -/

/-- **The swapped kernel generators lie in the kernel ideal.** For every
`m ≥ 0` the element `d₊d₊^{*m} - d₊^{*(m+1)}` of `Ã` lies in `I`, at every vertex `v` at which its
paths begin.

The argument: `d₊^{*m} - d₊^{m}` and `d₊^{*(m+1)} - d₊^{m+1}` lie in `I` by
`HJO.Dyck.Tilde.Atilde.dPlusStarPow_sub_dPlusPow_mem_kernelIdeal`, so `I` being a left ideal so does

    `d₊(d₊^{*m} - d₊^{m}) + (d₊^{m+1} - d₊^{*(m+1)}) = d₊d₊^{*m} - d₊^{*(m+1)}`,

the middle term cancelling because `d₊d₊^{m}` *is* `d₊^{m+1}`. -/
@[hjo "lem_cm_kernel_ideal_swap"]
theorem dPlus_mul_dPlusStarPow_sub_mem_kernelIdeal (v m : ℕ) :
    dPlus K q u (v + m) * dPlusStarPow K q u v m - dPlusStarPow K q u v (m + 1)
      ∈ kernelIdeal K q u := by
  have h1 : dPlus K q u (v + m) * (dPlusStarPow K q u v m - dPlusPow K q u v m)
      ∈ kernelIdeal K q u :=
    Ideal.mul_mem_left _ _ (dPlusStarPow_sub_dPlusPow_mem_kernelIdeal v m)
  have h2 : dPlusPow K q u v (m + 1) - dPlusStarPow K q u v (m + 1) ∈ kernelIdeal K q u := by
    have := dPlusStarPow_sub_dPlusPow_mem_kernelIdeal (K := K) (q := q) (u := u) v (m + 1)
    simpa using neg_mem this
  have hrw : dPlus K q u (v + m) * dPlusStarPow K q u v m - dPlusStarPow K q u v (m + 1)
      = dPlus K q u (v + m) * (dPlusStarPow K q u v m - dPlusPow K q u v m)
        + (dPlusPow K q u v (m + 1) - dPlusStarPow K q u v (m + 1)) := by
    rw [mul_sub, dPlusPow_succ]
    abel
  rw [hrw]
  exact Submodule.add_mem _ h1 h2

/-! ### A star swap preserves the kernel ideal -/

namespace IsStarSwap

variable {bar : K ≃+* K} {σ : Atilde K q u →+ Atilde K q u}
variable (h : IsStarSwap q bar (e K q u) (dPlus K q u) (dPlusStar K q u) (dMinus K q u)
  (Tg K q u) σ)

include h

/-- A star swap carries the word of raising arrows to the starred word. -/
theorem map_dPlusPow (v m : ℕ) : σ (dPlusPow K q u v m) = dPlusStarPow K q u v m := by
  induction m with
  | zero => exact h.map_e v
  | succ m ih => rw [dPlusPow_succ, dPlusStarPow_succ, h.map_mul, h.map_dPlus, ih]

/-- A star swap carries the starred word of raising arrows back to the unstarred word. -/
theorem map_dPlusStarPow (v m : ℕ) : σ (dPlusStarPow K q u v m) = dPlusPow K q u v m := by
  induction m with
  | zero => exact h.map_e v
  | succ m ih => rw [dPlusPow_succ, dPlusStarPow_succ, h.map_mul, h.map_dPlusStar, ih]

/-- **A star swap preserves the kernel ideal.** `σ` is
multiplicative and exchanges the two raising arrows, so it carries the `m`-th generator
`d₊^*d₊^m - d₊^{m+1}` of `HJO.Dyck.Tilde.Atilde.kernelIdeal` to `d₊d₊^{*m} - d₊^{*(m+1)}`, which
lies in `I` by `HJO.Dyck.Tilde.Atilde.dPlus_mul_dPlusStarPow_sub_mem_kernelIdeal`. The span is then
closed by induction, `I` being a left ideal: the scalar case is `σ(ax) = σ(a)σ(x)`, which needs
nothing of `σ(a)`. -/
@[hjo "lem_cm_star_flip_kernel_ideal"]
theorem mem_kernelIdeal {x : Atilde K q u} (hx : x ∈ kernelIdeal K q u) :
    σ x ∈ kernelIdeal K q u := by
  induction hx using Submodule.span_induction with
  | mem x hxs =>
    obtain ⟨v, m, rfl⟩ := hxs
    rw [map_sub, h.map_mul, h.map_dPlusStar, map_dPlusPow h v m, map_dPlusPow h v (m + 1)]
    exact dPlus_mul_dPlusStarPow_sub_mem_kernelIdeal v m
  | zero => rw [map_zero]; exact Submodule.zero_mem _
  | add x y _ _ ihx ihy => rw [map_add]; exact Submodule.add_mem _ ihx ihy
  | smul a x _ ih =>
    rw [smul_eq_mul, h.map_mul]
    exact Ideal.mul_mem_left _ _ ih

end IsStarSwap

end HJO.Dyck.Tilde.Atilde
