/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import Mathlib.Algebra.BigOperators.Finprod
public import Mathlib.Algebra.Order.Group.Int
public import Mathlib.Algebra.Order.Ring.Int
public import Mathlib.Algebra.Ring.TransferInstance
public import Mathlib.Data.Finsupp.Order
public import Mathlib.Data.Finsupp.PWO
public import Mathlib.RingTheory.HahnSeries.Multiplication
public import Mathlib.Tactic.Ring
public meta import HJO.Attr

/-! # The BGLX ring of cone-supported formal sums in `k` variables

The identity BGLX prove as their Theorem 2.1 is an identity among formal sums in `z_1, …, z_k`
whose coefficients lie in `Λ` and whose supports are unbounded in *both* directions: the factor
`∑_{r ≥ 0} (-z_i)ʳ e_r` contributes arbitrarily high powers of `z_i`, and the expansion of the
kernel factor `Exp[-M z_i / z_j]` arbitrarily low powers of `z_j`. So the ambient object is
neither the Laurent polynomial ring nor `Λ[[z]][z⁻¹]`. It is the ring of those formal sums whose
support is bounded below in the cone generated by the `e_i`, by the `e_i - e_j` for `i` before `j`
in a chosen ordering of the variables, and by a bounded part of the `-e_i`; multiplication is
well posed there because each graded piece for a weighting of the variables that decreases
strictly along the ordering is finite.

This file builds that ring. The ordering is carried explicitly, as a permutation `τ`, because the
cone is *not* stable under permuting the variables, and the symmetrisation step of BGLX's proof has
to move between the orderings; `relabelAlgEquiv` is that move.

## Main definitions

* `HJO.Bglx.Family`: the `Λ`-module `M_k` of *all* families `(f_α)_{α ∈ ℤ^k}` of coefficients,
  with `HJO.Bglx.mono α` for `z ^ α`.
* `HJO.Bglx.psum`: the partial sums `P^τ_j(α) = α_{τ(1)} + ⋯ + α_{τ(j)}` of an exponent along the
  ordering, and `HJO.Bglx.psumEquiv`, the bijection `α ↦ (P^τ_j(α))_j` of `ℤ^k` onto itself.
* `HJO.Bglx.cone`: the exponent cone `C^τ_k = {α : P^τ_j(α) ≥ 0 for every j}`, an
  `AddSubmonoid` of the exponent lattice.
* `HJO.Bglx.ConeRing`: the cone-bounded formal sums `R^τ_k`, with `HJO.Bglx.coneSubmodule` for
  the same thing as a `Λ`-submodule of `M_k`, and `HJO.Bglx.ConeRing.coeff_mul` for the product.
* `HJO.Bglx.ct`: constant-term extraction `CT_k : M_k → Λ`.
* `HJO.Bglx.relabel`: the relabelling `τ_*` of the variables, on all of `M_k`;
  `HJO.Bglx.ConeRing.relabelAlgEquiv` is the `Λ`-algebra isomorphism `R^ρ_k ≃ R^{τρ}_k` it
  restricts to.

## Implementation notes

**The exponent lattice is `Fin k →₀ ℤ`**, not `Fin k → ℤ`. For a finite index type the two are
the same lattice, and the `Finsupp` spelling is the one `dopWordSymbol` already uses for the
symbols this ring is built to receive, so a Laurent polynomial
`AddMonoidAlgebra K (Fin k →₀ ℤ)` is read as a member of `M_k` by its coefficient function with
no reindexing; `isConeBounded_of_finite` is then exactly the statement that every such symbol
lies in `R^τ_k`. It also carries the pointwise order and `Finsupp.wellQuasiOrderedLE`
(Dickson's lemma) that the support condition needs.

**Mathlib's `AddMonoidAlgebra` is of no use here and `HahnSeries` carries the ring.** The support
condition is not a submonoid condition: `R^τ_k` consists of families supported in a *translate*
`β + C^τ_k` of the cone, with `β` depending on the family, so the supports are not contained in
any one submonoid of `ℤ^k` and the elements are not finitely supported — `AddMonoidAlgebra` is
the wrong object twice over. What does carry the structure is `HahnSeries`: reindexing an
exponent by the partial-sum bijection `psumEquiv τ` turns "support contained in some
`β + C^τ_k`" into "support bounded below coordinatewise", and for the pointwise order on
`Fin k →₀ ℤ` *that is the same condition as* `Set.IsPWO` — bounded below gives `IsPWO` by
Dickson's lemma (`isPWO_of_bddBelow`) and `IsPWO` gives bounded below because each coordinate
projection is monotone and a well-founded set of integers has a minimum
(`bddBelow_of_isPWO`). So `hahnEquiv` is a bijection of `R^τ_k` onto
`HahnSeries (Fin k →₀ ℤ) Λ`, and `instCommRing` transports Mathlib's commutative ring structure
back along it. The weighting argument is therefore *not* redone by hand: Mathlib's
`Finset.antidiagonal` of two `IsPWO` sets is where the finiteness lives, and
`Set.IsPWO.finite_addAntidiagonal` is the statement "each of the `k` integers `P^τ_j(α')` lies
in a fixed finite interval" in Mathlib's coordinates. The two basic statements about
the product are kept as theorems about this ring rather than left inside the transport:
`finite_convSupport` is its finiteness, and `coeff_mul` its convolution formula.

The weighting is recorded anyway, in `sum_psum_eq`: `∑_j P^τ_j(α) = ∑_i (k - τ⁻¹(i)) α_i`, so
that the graded functional in question is available and visibly positive on the cone's
generators (`mem_cone_of_nonneg` and `mem_cone_nsmul_sub_single` are those generators).

The partial sums are indexed by `j : ℕ` rather than `1 ≤ j ≤ k`, with the letters of `α` extended
by zero past `k`. Nothing is added: `P^τ_0 = 0` always, and `P^τ_j = P^τ_k` for `j ≥ k`
(`psum_eq_psum_of_le`), so `∀ j : ℕ, 0 ≤ P^τ_j(α)` is the `1 ≤ j ≤ k` condition and
no `Fin` arithmetic appears in the telescoping that proves `psumEquiv` bijective. Indices are
zero-based throughout, so `psum τ α j` is `P^τ_j` with its `τ(1), …, τ(j)` read
as `τ(0), …, τ(j-1)`.

Generic in the coefficient ring: `Family`, `ct` and `relabel` need only `Zero`/`Semiring`, and
the ring needs `CommRing`. The `Λ` over `𝕜 = ℚ(q, u)` is the instance `R = Lambda K`,
and `dopWordSymbol`'s `K` is another.

The two degenerate cases are proved, not assumed: at `k = 0` the cone is
everything (`cone_eq_top_of_zero`) and the ring is the coefficient ring
(`ConeRing.zeroVarsAlgEquiv`).

**How the definitions match BGLX's.** (1) `psum`/`cone`/`ConeRing`/`ct`/`relabel` are the `P^τ_j`,
`C^τ_k`, `R^τ_k`, `CT_k` and `τ_*` on the nose, with `ConeRing.coeff_mul` pinning the product to the
displayed convolution and `ConeRing.coeff_relabelAlgEquiv` pinning the algebra isomorphism to `τ_*`
rather than to some other map between the two rings. (2) Nothing is weakened to make a proof go
through: the cone really is closed under addition (`cone` is an `AddSubmonoid`), the cone-bounded
families really are a submodule (`coneSubmodule`), and the convolution really is a finite sum
(`finite_convSupport`), all three being the three things that make the product well posed. (3) The
product is not characterised up to something: `coeff_mul_of_subset` computes each coefficient as a
sum over *any* finset containing the contributing exponents, so a reader may take the finset the
situation hands them. (4) The instantiation is not degenerate: `mem_cone_of_nonneg` and
`mem_cone_nsmul_sub_single` exhibit the two families of generators the factors of BGLX's identity
live on, and `isConeBounded_of_finite` puts every Laurent polynomial in the ring, so `R^τ_k` is
neither empty of the intended members nor all of `M_k` (a family supported on the `-r e_1` for all
`r` is not cone-bounded, the partial sum `P^τ_1` being unbounded below on it).

## References

This file follows F. Bergeron, A. M. Garsia, E. Leven and G. Xin, *Some remarkable new plethystic
operators in the theory of Macdonald polynomials*, arXiv:1405.0316v1, J. Comb. **7** (2016)
671--714, whose Theorem 2.1 and its proof are the identity these formal sums are the vocabulary
for; the ambient ring is not named there, and the choice of the cone is made here.
-/

@[expose] public section

namespace HJO.Bglx

variable {k : ℕ} {R : Type*}

/-- The `m`-th coordinate of an exponent, extended by `0` for `m ≥ k`. -/
def coord (α : Fin k →₀ ℤ) (m : ℕ) : ℤ := if h : m < k then α ⟨m, h⟩ else 0

/-- The `m`-th letter of the exponent `α` read in the order `τ`, that is `α_{τ(m)}`, extended
by `0` for `m ≥ k`. -/
def letter (τ : Equiv.Perm (Fin k)) (α : Fin k →₀ ℤ) (m : ℕ) : ℤ :=
  if h : m < k then α (τ ⟨m, h⟩) else 0

/-- The partial sums of an exponent along an ordering: `P^τ_j(α) = α_{τ(0)} + ⋯ + α_{τ(j-1)}`,
with the empty sum `0` at `j = 0` and the constant value `P^τ_k(α)` for `j ≥ k`. -/
@[hjo "def_bglx_psum"]
def psum (τ : Equiv.Perm (Fin k)) (α : Fin k →₀ ℤ) (j : ℕ) : ℤ :=
  ∑ m ∈ Finset.range j, letter τ α m

variable {τ : Equiv.Perm (Fin k)} {α β : Fin k →₀ ℤ}

lemma coord_eq_of_lt {m : ℕ} (h : m < k) : coord α m = α ⟨m, h⟩ := dite_eq_left h
lemma coord_eq_zero_of_le {m : ℕ} (h : k ≤ m) : coord α m = 0 := dite_eq_right (Nat.not_lt.2 h)
lemma letter_eq_of_lt {m : ℕ} (h : m < k) : letter τ α m = α (τ ⟨m, h⟩) := dite_eq_left h
lemma letter_eq_zero_of_le {m : ℕ} (h : k ≤ m) : letter τ α m = 0 :=
  dite_eq_right (Nat.not_lt.2 h)

@[simp] lemma psum_zero : psum τ α 0 = 0 := by simp [psum]

lemma psum_succ (j : ℕ) : psum τ α (j + 1) = psum τ α j + letter τ α j :=
  Finset.sum_range_succ _ _

lemma psum_eq_psum_of_le {j : ℕ} (h : k ≤ j) : psum τ α j = psum τ α k := by
  induction j with
  | zero => simp_all
  | succ n ih =>
    rcases eq_or_lt_of_le h with h' | h'
    · exact congrArg (psum τ α) h'.symm
    · rw [psum_succ, letter_eq_zero_of_le (by omega), add_zero, ih (by omega)]

@[simp] lemma letter_add : letter τ (α + β) = letter τ α + letter τ β := by
  funext m; simp only [letter, Pi.add_apply]; split <;> simp

lemma psum_add (j : ℕ) : psum τ (α + β) j = psum τ α j + psum τ β j := by
  simp only [psum, letter_add, Pi.add_apply, Finset.sum_add_distrib]

@[simp] lemma letter_zero : letter τ (0 : Fin k →₀ ℤ) = 0 := by
  funext m; simp only [letter]; split <;> simp

@[simp] lemma psum_zero_fun (j : ℕ) : psum τ (0 : Fin k →₀ ℤ) j = 0 := by simp [psum]

@[simp] lemma letter_neg : letter τ (-α) = -letter τ α := by
  funext m; simp only [letter, Pi.neg_apply]; split <;> simp

lemma psum_neg (j : ℕ) : psum τ (-α) j = -psum τ α j := by
  simp only [psum, letter_neg, Pi.neg_apply, Finset.sum_neg_distrib]

lemma psum_sub (j : ℕ) : psum τ (α - β) j = psum τ α j - psum τ β j := by
  rw [sub_eq_add_neg, psum_add, psum_neg, sub_eq_add_neg]

/-- The coordinate sequence shifted by one, with value `0` at `0`. -/
def coordShift (b : Fin k →₀ ℤ) : ℕ → ℤ
  | 0 => 0
  | (m + 1) => coord b m

@[simp] lemma coordShift_zero (b : Fin k →₀ ℤ) : coordShift b 0 = 0 := rfl

@[simp] lemma coordShift_succ (b : Fin k →₀ ℤ) (m : ℕ) : coordShift b (m + 1) = coord b m := rfl

/-- The tuple of partial sums of `α` along `τ`. -/
noncomputable def psumFun (τ : Equiv.Perm (Fin k)) (α : Fin k →₀ ℤ) : Fin k →₀ ℤ :=
  Finsupp.equivFunOnFinite.symm fun j => psum τ α (j.val + 1)

/-- The exponent with prescribed partial sums along `τ`. -/
noncomputable def psumInvFun (τ : Equiv.Perm (Fin k)) (b : Fin k →₀ ℤ) : Fin k →₀ ℤ :=
  Finsupp.equivFunOnFinite.symm fun i => coord b (τ.symm i).val - coordShift b (τ.symm i).val

@[simp] lemma psumFun_apply (j : Fin k) : psumFun τ α j = psum τ α (j.val + 1) := by
  simp [psumFun]

@[simp] lemma psumInvFun_apply (b : Fin k →₀ ℤ) (i : Fin k) :
    psumInvFun τ b i = coord b (τ.symm i).val - coordShift b (τ.symm i).val := by
  simp [psumInvFun]

lemma coord_psumFun {m : ℕ} (h : m < k) : coord (psumFun τ α) m = psum τ α (m + 1) := by
  rw [coord_eq_of_lt h, psumFun_apply]

lemma letter_psumInvFun (b : Fin k →₀ ℤ) {m : ℕ} (h : m < k) :
    letter τ (psumInvFun τ b) m = coord b m - coordShift b m := by
  rw [letter_eq_of_lt h, psumInvFun_apply]
  simp

lemma psum_psumInvFun (b : Fin k →₀ ℤ) :
    ∀ j : ℕ, j < k → psum τ (psumInvFun τ b) (j + 1) = coord b j
  | 0, h => by rw [psum_succ, psum_zero, zero_add, letter_psumInvFun b h, coordShift_zero,
      sub_zero]
  | (j + 1), h => by
      rw [psum_succ, psum_psumInvFun b j (by omega), letter_psumInvFun b h, coordShift_succ]
      omega

lemma coordShift_psumFun {m : ℕ} (h : m ≤ k) : coordShift (psumFun τ α) m = psum τ α m := by
  cases m with
  | zero => simp
  | succ n => rw [coordShift_succ, coord_psumFun (by omega)]

lemma psumInvFun_psumFun : psumInvFun τ (psumFun τ α) = α := by
  refine Finsupp.ext fun i => ?_
  rw [psumInvFun_apply, coord_psumFun (τ.symm i).isLt,
    coordShift_psumFun (le_of_lt (τ.symm i).isLt), psum_succ,
    letter_eq_of_lt (τ.symm i).isLt]
  simp

lemma psumFun_psumInvFun (b : Fin k →₀ ℤ) : psumFun τ (psumInvFun τ b) = b := by
  refine Finsupp.ext fun j => ?_
  rw [psumFun_apply, psum_psumInvFun b j.val j.isLt, coord_eq_of_lt j.isLt]

lemma psumFun_add : psumFun τ (α + β) = psumFun τ α + psumFun τ β := by
  refine Finsupp.ext fun j => ?_
  simp [psum_add]

/-- The partial-sum bijection of the exponent lattice. -/
@[hjo "def_bglx_psum"]
noncomputable def psumEquiv (τ : Equiv.Perm (Fin k)) : (Fin k →₀ ℤ) ≃+ (Fin k →₀ ℤ) where
  toFun := psumFun τ
  invFun := psumInvFun τ
  left_inv _ := psumInvFun_psumFun
  right_inv := psumFun_psumInvFun
  map_add' _ _ := psumFun_add

@[simp] lemma psumEquiv_apply (j : Fin k) : psumEquiv τ α j = psum τ α (j.val + 1) :=
  psumFun_apply j

/-- `psum τ · j` as an additive homomorphism. -/
def psumHom (τ : Equiv.Perm (Fin k)) (j : ℕ) : (Fin k →₀ ℤ) →+ ℤ where
  toFun α := psum τ α j
  map_zero' := psum_zero_fun j
  map_add' _ _ := psum_add j

@[simp] lemma psumHom_apply (j : ℕ) : psumHom τ j α = psum τ α j := rfl

lemma psum_nsmul (r : ℕ) (j : ℕ) : psum τ (r • α) j = r * psum τ α j := by
  rw [← psumHom_apply (τ := τ) (α := r • α) j, map_nsmul, psumHom_apply, nsmul_eq_mul]

lemma letter_single (i : Fin k) (c : ℤ) (m : ℕ) :
    letter τ (Finsupp.single i c) m = if m = (τ.symm i).val then c else 0 := by
  by_cases h : m < k
  · rw [letter_eq_of_lt h]
    by_cases h2 : m = (τ.symm i).val
    · have : τ (⟨m, h⟩ : Fin k) = i := by
        rw [show (⟨m, h⟩ : Fin k) = τ.symm i from Fin.ext h2]
        exact τ.apply_symm_apply i
      rw [this, Finsupp.single_eq_same, ite_eq_left h2]
    · have : τ (⟨m, h⟩ : Fin k) ≠ i := by
        intro hc
        exact h2 (by rw [← hc, τ.symm_apply_apply])
      rw [Finsupp.single_eq_of_ne this, ite_eq_right h2]
  · rw [letter_eq_zero_of_le (Nat.not_lt.1 h), ite_eq_right]
    have := (τ.symm i).isLt
    omega

lemma psum_single (i : Fin k) (c : ℤ) (l : ℕ) :
    psum τ (Finsupp.single i c) l = if (τ.symm i).val < l then c else 0 := by
  simp only [psum, letter_single]
  rw [Finset.sum_ite_eq' (Finset.range l) ((τ.symm i).val) (fun _ => c)]
  simp

/-- The exponent cone of the ordering `τ`. -/
@[hjo "def_bglx_cone"]
def cone (τ : Equiv.Perm (Fin k)) : AddSubmonoid (Fin k →₀ ℤ) where
  carrier := {α | ∀ j : ℕ, 0 ≤ psum τ α j}
  add_mem' ha hb j := by rw [psum_add]; exact add_nonneg (ha j) (hb j)
  zero_mem' j := by simp

lemma mem_cone : α ∈ cone τ ↔ ∀ j : ℕ, 0 ≤ psum τ α j := Iff.rfl

lemma sub_mem_cone_iff : α - β ∈ cone τ ↔ ∀ j : ℕ, psum τ β j ≤ psum τ α j := by
  simp only [mem_cone, psum_sub, sub_nonneg]

lemma mem_cone_iff_le : α ∈ cone τ ↔ 0 ≤ psumEquiv τ α := by
  rw [mem_cone, Finsupp.le_def]
  refine ⟨fun h j => by simpa using h (j.val + 1), fun h => ?_⟩
  have key : ∀ j : ℕ, j ≤ k → 0 ≤ psum τ α j := by
    intro j _
    match j with
    | 0 => simp
    | (l + 1) => simpa using h ⟨l, by omega⟩
  intro j
  rcases Nat.lt_or_ge j k with hj | hj
  · exact key j hj.le
  · rw [psum_eq_psum_of_le hj]
    exact key k le_rfl

lemma mem_cone_of_nonneg (h : 0 ≤ α) : α ∈ cone τ := by
  intro j
  refine Finset.sum_nonneg fun m _ => ?_
  by_cases hm : m < k
  · rw [letter_eq_of_lt hm]
    simpa using Finsupp.le_def.1 h (τ ⟨m, hm⟩)
  · rw [letter_eq_zero_of_le (Nat.not_lt.1 hm)]

lemma cone_eq_top_of_zero (τ : Equiv.Perm (Fin 0)) : cone τ = ⊤ := by
  refine (AddSubmonoid.eq_top_iff' _).2 fun α j => ?_
  refine le_of_eq (Finset.sum_eq_zero fun m _ => ?_).symm
  exact letter_eq_zero_of_le (Nat.zero_le m)

lemma mem_cone_nsmul_sub_single {i j : Fin k} (h : (τ.symm i).val < (τ.symm j).val) (r : ℕ) :
    r • (Finsupp.single i (1 : ℤ) - Finsupp.single j (1 : ℤ)) ∈ cone τ := by
  intro l
  rw [psum_nsmul, psum_sub, psum_single, psum_single]
  refine mul_nonneg (Int.natCast_nonneg r) ?_
  split_ifs <;> omega

lemma sub_mem_cone_iff_le : α - β ∈ cone τ ↔ psumEquiv τ β ≤ psumEquiv τ α := by
  rw [mem_cone_iff_le, map_sub, sub_nonneg]

lemma mem_vadd_cone_iff :
    α ∈ (β + ·) '' (cone τ : Set (Fin k →₀ ℤ)) ↔ α - β ∈ cone τ := by
  refine ⟨?_, fun h => ⟨α - β, h, by simp⟩⟩
  rintro ⟨γ, hγ, rfl⟩
  simpa using hγ

/-- A set of exponents bounded below is partially well-ordered (Dickson's lemma). -/
lemma isPWO_of_bddBelow {S : Set (Fin k →₀ ℤ)} {b : Fin k →₀ ℤ} (h : ∀ x ∈ S, b ≤ x) :
    S.IsPWO := by
  have hmono : Monotone fun x : Fin k →₀ ℕ => x.mapRange (fun n : ℕ => (n : ℤ)) rfl + b := by
    intro x y hxy
    refine add_le_add ?_ le_rfl
    rw [Finsupp.le_def]
    intro i
    simpa using Finsupp.le_def.1 hxy i
  refine Set.IsPWO.mono
    ((Set.isPWO_of_wellQuasiOrderedLE Set.univ).image_of_monotone hmono) fun x hx => ?_
  refine ⟨(x - b).mapRange Int.toNat rfl, Set.mem_univ _, ?_⟩
  refine Finsupp.ext fun i => ?_
  have hbi : b i ≤ x i := Finsupp.le_def.1 (h x hx) i
  simp only [Finsupp.coe_add, Pi.add_apply, Finsupp.mapRange_apply, Finsupp.coe_sub,
    Pi.sub_apply]
  omega

/-- A partially well-ordered set of exponents is bounded below. -/
lemma bddBelow_of_isPWO {S : Set (Fin k →₀ ℤ)} (hS : S.IsPWO) :
    ∃ b : Fin k →₀ ℤ, ∀ x ∈ S, b ≤ x := by
  rcases S.eq_empty_or_nonempty with rfl | hne
  · exact ⟨0, by simp⟩
  have hmono : ∀ i : Fin k, Monotone fun x : Fin k →₀ ℤ => x i :=
    fun i _ _ hxy => Finsupp.le_def.1 hxy i
  have hwf : ∀ i : Fin k, ((fun x : Fin k →₀ ℤ => x i) '' S).IsWF :=
    fun i => Set.isPWO_iff_isWF.1 (hS.image_of_monotone (hmono i))
  have hnei : ∀ i : Fin k, ((fun x : Fin k →₀ ℤ => x i) '' S).Nonempty :=
    fun i => hne.image _
  refine ⟨Finsupp.equivFunOnFinite.symm fun i => (hwf i).min (hnei i), fun x hx => ?_⟩
  rw [Finsupp.le_def]
  intro i
  simpa using (hwf i).min_le (hnei i) ⟨x, hx, rfl⟩

/-- The `Λ`-module of all formal sums in `k` variables with coefficients in `R`. -/
@[hjo "def_bglx_family_module"]
abbrev Family (k : ℕ) (R : Type*) := (Fin k →₀ ℤ) → R

/-- `z ^ α`, the formal sum with coefficient `1` at `α` and `0` elsewhere. -/
@[hjo "def_bglx_family_module"]
noncomputable def mono [Zero R] [One R] (α : Fin k →₀ ℤ) : Family k R := Pi.single α 1

/-- Cone-boundedness: the support lies in `β + C ^ τ` for some `β`. -/
def IsConeBounded [Zero R] (τ : Equiv.Perm (Fin k)) (f : Family k R) : Prop :=
  ∃ β : Fin k →₀ ℤ, Function.support f ⊆ (β + ·) '' (cone τ : Set (Fin k →₀ ℤ))

private lemma sum_range_sum_range (g : ℕ → ℤ) (n : ℕ) :
    ∑ j ∈ Finset.range n, ∑ m ∈ Finset.range (j + 1), g m
      = ∑ m ∈ Finset.range n, ((n - m : ℕ) : ℤ) * g m := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [Finset.sum_range_succ, ih]
    have h1 : ∀ m ∈ Finset.range (n + 1),
        ((n + 1 - m : ℕ) : ℤ) * g m = ((n - m : ℕ) : ℤ) * g m + g m := by
      intro m hm
      rw [Finset.mem_range] at hm
      rw [show ((n + 1 - m : ℕ) : ℤ) = ((n - m : ℕ) : ℤ) + 1 by omega]
      ring
    rw [Finset.sum_congr rfl h1, Finset.sum_add_distrib,
      Finset.sum_range_succ (f := fun m => ((n - m : ℕ) : ℤ) * g m)]
    simp

/-- The weighting of the variables that the cone is graded by: the sum of the partial sums of
`α` is `∑ i (k - τ⁻¹ i) α i`, a weighting strictly decreasing along `τ` and positive on each
generator of the cone. -/
lemma sum_psum_eq (α : Fin k →₀ ℤ) :
    ∑ j ∈ Finset.range k, psum τ α (j + 1)
      = ∑ i : Fin k, ((k - (τ.symm i : ℕ) : ℕ) : ℤ) * α i := by
  rw [show (∑ j ∈ Finset.range k, psum τ α (j + 1))
      = ∑ j ∈ Finset.range k, ∑ m ∈ Finset.range (j + 1), letter τ α m from rfl,
    sum_range_sum_range, ← Fin.sum_univ_eq_sum_range]
  refine Fintype.sum_bijective τ τ.bijective
    (fun m : Fin k => ((k - (m : ℕ) : ℕ) : ℤ) * letter τ α (m : ℕ))
    (fun i : Fin k => ((k - (τ.symm i : ℕ) : ℕ) : ℤ) * α i) fun m => ?_
  rw [Equiv.symm_apply_apply, letter_eq_of_lt m.isLt]

/-- Relabelling the exponents by `τ`: `(τ • α) (τ i) = α i`. -/
def relabelExp (τ : Equiv.Perm (Fin k)) : (Fin k →₀ ℤ) ≃+ (Fin k →₀ ℤ) := Finsupp.domCongr τ

@[simp] lemma relabelExp_apply_perm (i : Fin k) : relabelExp τ α (τ i) = α i := by
  simp [relabelExp, Finsupp.domCongr, Finsupp.equivMapDomain_apply]

lemma relabelExp_trans (a b : Equiv.Perm (Fin k)) :
    relabelExp (a * b) = (relabelExp b).trans (relabelExp a) := by
  rw [relabelExp, relabelExp, relabelExp, Finsupp.domCongr_trans]
  rfl

@[simp] lemma relabelExp_one : relabelExp (1 : Equiv.Perm (Fin k)) = AddEquiv.refl _ :=
  Finsupp.domCongr_refl

lemma letter_relabelExp (σ ρ : Equiv.Perm (Fin k)) (m : ℕ) :
    letter (σ * ρ) (relabelExp σ α) m = letter ρ α m := by
  by_cases h : m < k
  · rw [letter_eq_of_lt h, letter_eq_of_lt h]
    exact relabelExp_apply_perm (ρ ⟨m, h⟩)
  · rw [letter_eq_zero_of_le (Nat.not_lt.1 h), letter_eq_zero_of_le (Nat.not_lt.1 h)]

lemma psum_relabelExp (σ ρ : Equiv.Perm (Fin k)) (j : ℕ) :
    psum (σ * ρ) (relabelExp σ α) j = psum ρ α j := by
  simp only [psum, letter_relabelExp]

lemma psumEquiv_relabelExp (σ ρ : Equiv.Perm (Fin k)) :
    psumEquiv (σ * ρ) (relabelExp σ α) = psumEquiv ρ α := by
  refine Finsupp.ext fun j => ?_
  rw [psumEquiv_apply, psumEquiv_apply, psum_relabelExp]

lemma psumEquiv_symm_relabelExp (σ ρ : Equiv.Perm (Fin k)) (γ : Fin k →₀ ℤ) :
    (psumEquiv ρ).symm γ = (relabelExp σ).symm ((psumEquiv (σ * ρ)).symm γ) := by
  apply (relabelExp σ).injective
  rw [AddEquiv.apply_symm_apply]
  refine (AddEquiv.eq_symm_apply _).2 ?_
  rw [psumEquiv_relabelExp, AddEquiv.apply_symm_apply]

lemma mem_cone_relabelExp (σ ρ : Equiv.Perm (Fin k)) :
    relabelExp σ α ∈ cone (σ * ρ) ↔ α ∈ cone ρ := by
  simp only [mem_cone, psum_relabelExp]

section ZeroCoeff

variable [Zero R]

lemma isConeBounded_iff {f : Family k R} :
    IsConeBounded τ f ↔ ∃ β : Fin k →₀ ℤ, ∀ α, f α ≠ 0 → ∀ j : ℕ, psum τ β j ≤ psum τ α j := by
  simp only [IsConeBounded, Set.subset_def, Function.mem_support, mem_vadd_cone_iff,
    sub_mem_cone_iff]

/-- The coefficient family of a formal sum, reindexed by the partial-sum bijection. -/
noncomputable def toHahnCoeff (τ : Equiv.Perm (Fin k)) (f : Family k R) : (Fin k →₀ ℤ) → R :=
  fun γ => f ((psumEquiv τ).symm γ)

lemma support_toHahnCoeff {f : Family k R} :
    Function.support (toHahnCoeff τ f) = psumEquiv τ '' Function.support f := by
  ext γ
  simp only [Function.mem_support, toHahnCoeff, Set.mem_image]
  refine ⟨fun h => ⟨(psumEquiv τ).symm γ, h, by simp⟩, ?_⟩
  rintro ⟨α, hα, rfl⟩
  simpa using hα

lemma isConeBounded_iff_isPWO {f : Family k R} :
    IsConeBounded τ f ↔ (Function.support (toHahnCoeff τ f)).IsPWO := by
  rw [support_toHahnCoeff]
  constructor
  · rintro ⟨β, hβ⟩
    refine isPWO_of_bddBelow (b := psumEquiv τ β) ?_
    rintro γ ⟨α, hα, rfl⟩
    exact (sub_mem_cone_iff_le).1 (mem_vadd_cone_iff.1 (hβ hα))
  · intro h
    obtain ⟨b, hb⟩ := bddBelow_of_isPWO h
    refine ⟨(psumEquiv τ).symm b, fun α hα => mem_vadd_cone_iff.2 (sub_mem_cone_iff_le.2 ?_)⟩
    simpa using hb _ ⟨α, hα, rfl⟩

/-- Finite support is cone-bounded. -/
@[hjo "lem_bglx_laurent_cone_bounded"]
theorem isConeBounded_of_finite {f : Family k R} (hf : (Function.support f).Finite) :
    IsConeBounded τ f := by
  refine isConeBounded_iff_isPWO.2 ?_
  rw [support_toHahnCoeff]
  exact (hf.image _).isPWO

/-- The ring of cone-bounded formal sums. -/
@[hjo "def_bglx_cone_ring"]
structure ConeRing (k : ℕ) (τ : Equiv.Perm (Fin k)) (R : Type*) [Zero R] where
  /-- the coefficient family -/
  coeff : Family k R
  /-- its support is cone-bounded -/
  isConeBounded : IsConeBounded τ coeff

namespace ConeRing

@[ext] lemma ext {x y : ConeRing k τ R} (h : x.coeff = y.coeff) : x = y := by
  cases x; cases y; simpa using h

/-- The reindexing isomorphism onto Hahn series over the exponent lattice. -/
noncomputable def hahnEquiv (k : ℕ) (τ : Equiv.Perm (Fin k)) (R : Type*) [Zero R] :
    ConeRing k τ R ≃ HahnSeries (Fin k →₀ ℤ) R where
  toFun x := ⟨toHahnCoeff τ x.coeff, isConeBounded_iff_isPWO.1 x.isConeBounded⟩
  invFun x := ⟨fun α => x.coeff (psumEquiv τ α), isConeBounded_iff_isPWO.2 (by
    have h : toHahnCoeff τ (fun α => x.coeff (psumEquiv τ α)) = x.coeff := by
      funext γ; simp [toHahnCoeff]
    rw [h]; exact x.isPWO_support)⟩
  left_inv x := by ext α; simp [toHahnCoeff]
  right_inv x := by ext γ; simp [toHahnCoeff]

lemma coeff_hahnEquiv (x : ConeRing k τ R) (γ : Fin k →₀ ℤ) :
    (hahnEquiv k τ R x).coeff γ = x.coeff ((psumEquiv τ).symm γ) := rfl

@[simp] lemma coeff_hahnEquiv_psumEquiv (x : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    (hahnEquiv k τ R x).coeff (psumEquiv τ α) = x.coeff α := by
  rw [coeff_hahnEquiv, AddEquiv.symm_apply_apply]

@[simp] lemma coeff_hahnEquiv_symm (x : HahnSeries (Fin k →₀ ℤ) R) (α : Fin k →₀ ℤ) :
    ((hahnEquiv k τ R).symm x).coeff α = x.coeff (psumEquiv τ α) := rfl

end ConeRing

end ZeroCoeff

section Mod

variable [Semiring R]

lemma toHahnCoeff_add (f g : Family k R) :
    toHahnCoeff τ (f + g) = toHahnCoeff τ f + toHahnCoeff τ g := rfl

lemma toHahnCoeff_smul (r : R) (f : Family k R) :
    toHahnCoeff τ (r • f) = r • toHahnCoeff τ f := rfl

lemma isConeBounded_add {f g : Family k R} (hf : IsConeBounded τ f) (hg : IsConeBounded τ g) :
    IsConeBounded τ (f + g) := by
  rw [isConeBounded_iff_isPWO] at hf hg ⊢
  rw [toHahnCoeff_add]
  exact (Set.isPWO_union.2 ⟨hf, hg⟩).mono (Function.support_add _ _)

lemma isConeBounded_smul (r : R) {f : Family k R} (hf : IsConeBounded τ f) :
    IsConeBounded τ (r • f) := by
  rw [isConeBounded_iff_isPWO] at hf ⊢
  rw [toHahnCoeff_smul]
  refine hf.mono fun γ hγ => ?_
  rw [Function.mem_support] at hγ ⊢
  exact fun h => hγ (by simp [Pi.smul_apply, h])

/-- The cone-bounded formal sums form a `Λ`-submodule of all formal sums. -/
@[hjo "def_bglx_cone_ring"]
def coneSubmodule (k : ℕ) (τ : Equiv.Perm (Fin k)) (R : Type*) [Semiring R] :
    Submodule R (Family k R) where
  carrier := {f | IsConeBounded τ f}
  add_mem' := isConeBounded_add
  zero_mem' := isConeBounded_of_finite (by simp)
  smul_mem' := isConeBounded_smul

@[simp] lemma mem_coneSubmodule {f : Family k R} :
    f ∈ coneSubmodule k τ R ↔ IsConeBounded τ f := Iff.rfl

/-- Constant-term extraction in `k` variables. -/
@[hjo "def_bglx_cone_ct"]
def ct (k : ℕ) (R : Type*) [Semiring R] : Family k R →ₗ[R] R where
  toFun f := f 0
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

@[simp] lemma ct_apply (f : Family k R) : ct k R f = f 0 := rfl

/-- **`CT_k` is dual to the monomials**: it takes `z ^ β` to `1` when `β = 0` and to `0` at every
other exponent. With `ct_apply` this pins `CT_k` down: a `Λ`-linear functional is determined on the
finitely supported families by its values on the monomials, so `CT_k` is extraction of the
coefficient of `z_1^0 z_2^0 ⋯ z_k^0` and nothing else. Not a `simp` lemma: `ct_apply` is more
general, matches everything this does and fires first, leaving `mono β 0`. -/
lemma ct_mono (β : Fin k →₀ ℤ) : ct k R (mono β) = if β = 0 then 1 else 0 := by
  rw [ct_apply, mono, Pi.single_apply]
  exact if_congr eq_comm rfl rfl

/-- Relabelling the variables: `τ_* (∑ f_α z ^ α) = ∑ f_α z ^ (τ α)`. -/
@[hjo "def_bglx_relabel"]
def relabel (τ : Equiv.Perm (Fin k)) : Family k R ≃ₗ[R] Family k R :=
  LinearEquiv.funCongrLeft R R (relabelExp τ).toEquiv.symm

@[simp] lemma relabel_apply (f : Family k R) (α : Fin k →₀ ℤ) :
    relabel τ f α = f ((relabelExp τ).symm α) := rfl

lemma relabel_apply_relabelExp (f : Family k R) (α : Fin k →₀ ℤ) :
    relabel τ f (relabelExp τ α) = f α := by
  rw [relabel_apply, AddEquiv.symm_apply_apply]

lemma relabel_relabel (a b : Equiv.Perm (Fin k)) (f : Family k R) :
    relabel a (relabel b f) = relabel (a * b) f := by
  funext α
  rw [relabel_apply, relabel_apply, relabel_apply, relabelExp_trans]
  rfl

@[simp] lemma relabel_one (f : Family k R) : relabel (1 : Equiv.Perm (Fin k)) f = f := by
  funext α
  rw [relabel_apply, relabelExp_one]
  rfl

lemma isConeBounded_relabel {σ ρ : Equiv.Perm (Fin k)} {f : Family k R}
    (hf : IsConeBounded ρ f) : IsConeBounded (σ * ρ) (relabel σ f) := by
  rw [isConeBounded_iff] at hf ⊢
  obtain ⟨β, hβ⟩ := hf
  refine ⟨relabelExp σ β, fun α hα j => ?_⟩
  rw [relabel_apply] at hα
  have h := hβ _ hα j
  rwa [← psum_relabelExp σ ρ (α := β) j,
    ← psum_relabelExp σ ρ (α := (relabelExp σ).symm α) j, AddEquiv.apply_symm_apply] at h

end Mod

namespace ConeRing

section Ring

variable [CommRing R]

/-- The commutative ring structure. -/
@[hjo "lem_bglx_cone_ring_algebra"]
noncomputable instance instCommRing : CommRing (ConeRing k τ R) := (hahnEquiv k τ R).commRing

lemma add_def (x y : ConeRing k τ R) :
    x + y = (hahnEquiv k τ R).symm (hahnEquiv k τ R x + hahnEquiv k τ R y) := rfl

lemma mul_def (x y : ConeRing k τ R) :
    x * y = (hahnEquiv k τ R).symm (hahnEquiv k τ R x * hahnEquiv k τ R y) := rfl

lemma one_def : (1 : ConeRing k τ R) = (hahnEquiv k τ R).symm 1 := rfl

lemma zero_def : (0 : ConeRing k τ R) = (hahnEquiv k τ R).symm 0 := rfl

lemma neg_def (x : ConeRing k τ R) :
    -x = (hahnEquiv k τ R).symm (-(hahnEquiv k τ R x)) := rfl

@[simp] lemma coeff_add (x y : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    (x + y).coeff α = x.coeff α + y.coeff α := by
  rw [add_def, coeff_hahnEquiv_symm, HahnSeries.coeff_add, coeff_hahnEquiv_psumEquiv,
    coeff_hahnEquiv_psumEquiv]

@[simp] lemma coeff_zero (α : Fin k →₀ ℤ) : (0 : ConeRing k τ R).coeff α = 0 := by
  rw [zero_def, coeff_hahnEquiv_symm, HahnSeries.coeff_zero]

@[simp] lemma coeff_neg (x : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    (-x).coeff α = -x.coeff α := by
  rw [neg_def, coeff_hahnEquiv_symm, HahnSeries.coeff_neg, coeff_hahnEquiv_psumEquiv]

@[simp] lemma coeff_one (α : Fin k →₀ ℤ) :
    (1 : ConeRing k τ R).coeff α = if α = 0 then 1 else 0 := by
  rw [one_def, coeff_hahnEquiv_symm, HahnSeries.coeff_one]
  congr 1
  simp [(psumEquiv τ).map_eq_zero_iff]

/-- The pairs contributing to the coefficient of `z ^ α` in a product. -/
def convSupport (x y : ConeRing k τ R) (α : Fin k →₀ ℤ) : Set (Fin k →₀ ℤ) :=
  {α' | x.coeff α' ≠ 0 ∧ y.coeff (α - α') ≠ 0}

open scoped Classical in
/-- The contributing exponents lie in the image of the Hahn antidiagonal. -/
lemma convSupport_subset (x y : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    convSupport x y α ⊆ ↑((Finset.antidiagonal (hahnEquiv k τ R x).isPWO_support
      (hahnEquiv k τ R y).isPWO_support (psumEquiv τ α)).image
        (fun p => (psumEquiv τ).symm p.1)) := by
  rintro α' ⟨h1, h2⟩
  rw [Finset.mem_coe, Finset.mem_image]
  refine ⟨(psumEquiv τ α', psumEquiv τ (α - α')), Finset.mem_antidiagonal.2 ⟨?_, ?_, ?_⟩, ?_⟩
  · rw [HahnSeries.mem_support, coeff_hahnEquiv_psumEquiv]
    exact h1
  · rw [HahnSeries.mem_support, coeff_hahnEquiv_psumEquiv]
    exact h2
  · rw [← map_add]
    congr 1
    abel
  · simp

/-- The finiteness: only finitely many pairs contribute to a coefficient. -/
theorem finite_convSupport (x y : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    (convSupport x y α).Finite := by
  classical
  exact Set.Finite.subset (Finset.finite_toSet _) (convSupport_subset x y α)

/-- The product is the convolution, computed over any finset containing the contributing
exponents. -/
theorem coeff_mul_of_subset (x y : ConeRing k τ R) (α : Fin k →₀ ℤ)
    (s : Finset (Fin k →₀ ℤ)) (hs : convSupport x y α ⊆ ↑s) :
    (x * y).coeff α = ∑ α' ∈ s, x.coeff α' * y.coeff (α - α') := by
  classical
  rw [mul_def, coeff_hahnEquiv_symm, HahnSeries.coeff_mul]
  have hsnd : ∀ p ∈ Finset.antidiagonal (hahnEquiv k τ R x).isPWO_support
      (hahnEquiv k τ R y).isPWO_support (psumEquiv τ α),
      (psumEquiv τ).symm p.2 = α - (psumEquiv τ).symm p.1 := by
    intro p hp
    have h2 : (psumEquiv τ).symm p.1 + (psumEquiv τ).symm p.2 = α := by
      rw [← map_add, (Finset.mem_antidiagonal.1 hp).2.2, AddEquiv.symm_apply_apply]
    rw [← h2]
    abel
  have hinj : ∀ p ∈ Finset.antidiagonal (hahnEquiv k τ R x).isPWO_support
      (hahnEquiv k τ R y).isPWO_support (psumEquiv τ α),
      ∀ q ∈ Finset.antidiagonal (hahnEquiv k τ R x).isPWO_support
      (hahnEquiv k τ R y).isPWO_support (psumEquiv τ α),
      (psumEquiv τ).symm p.1 = (psumEquiv τ).symm q.1 → p = q := by
    intro p hp q hq h
    have h1 : p.1 = q.1 := (psumEquiv τ).symm.injective h
    refine Prod.ext h1 ?_
    have hp2 := (Finset.mem_antidiagonal.1 hp).2.2
    have hq2 := (Finset.mem_antidiagonal.1 hq).2.2
    rw [← h1] at hq2
    exact add_left_cancel (hp2.trans hq2.symm)
  have hmem : ∀ p ∈ Finset.antidiagonal (hahnEquiv k τ R x).isPWO_support
      (hahnEquiv k τ R y).isPWO_support (psumEquiv τ α),
      (psumEquiv τ).symm p.1 ∈ convSupport x y α := by
    intro p hp
    refine ⟨?_, ?_⟩
    · rw [← coeff_hahnEquiv]
      exact (HahnSeries.mem_support _ _).1 (Finset.mem_antidiagonal.1 hp).1
    · rw [← hsnd p hp, ← coeff_hahnEquiv]
      exact (HahnSeries.mem_support _ _).1 (Finset.mem_antidiagonal.1 hp).2.1
  rw [show ∑ p ∈ Finset.antidiagonal (hahnEquiv k τ R x).isPWO_support
        (hahnEquiv k τ R y).isPWO_support (psumEquiv τ α),
        (hahnEquiv k τ R x).coeff p.1 * (hahnEquiv k τ R y).coeff p.2
      = ∑ α' ∈ (Finset.antidiagonal (hahnEquiv k τ R x).isPWO_support
        (hahnEquiv k τ R y).isPWO_support (psumEquiv τ α)).image
          (fun p => (psumEquiv τ).symm p.1), x.coeff α' * y.coeff (α - α') from ?_]
  · refine Finset.sum_subset (fun α' hα' => ?_) (fun α' _ hα' => ?_)
    · rw [Finset.mem_image] at hα'
      obtain ⟨p, hp, rfl⟩ := hα'
      exact hs (hmem p hp)
    · by_contra hne
      refine hα' ?_
      have : α' ∈ convSupport x y α := by
        refine ⟨fun h => hne ?_, fun h => hne ?_⟩ <;> simp [h]
      exact Finset.mem_coe.1 (convSupport_subset x y α this)
  · rw [Finset.sum_image hinj]
    refine Finset.sum_congr rfl fun p hp => ?_
    rw [← hsnd p hp, coeff_hahnEquiv, coeff_hahnEquiv]

/-- The product is the convolution of the two coefficient families. -/
@[hjo "def_bglx_cone_ring"]
theorem coeff_mul (x y : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    (x * y).coeff α = ∑ᶠ α' : Fin k →₀ ℤ, x.coeff α' * y.coeff (α - α') := by
  classical
  have hsub : convSupport x y α ⊆ ↑(finite_convSupport x y α).toFinset := by
    rw [Set.Finite.coe_toFinset]
  rw [coeff_mul_of_subset x y α _ hsub,
    finsum_eq_finsetSum_of_support_subset _ (s := (finite_convSupport x y α).toFinset) ?_]
  intro α' hα'
  rw [Function.mem_support] at hα'
  rw [Set.Finite.coe_toFinset]
  exact ⟨fun h => hα' (by simp [h]), fun h => hα' (by simp [h])⟩

/-- The scalar `r` as the constant formal sum `r z ^ 0`. -/
noncomputable def const (r : R) : ConeRing k τ R where
  coeff := Pi.single 0 r
  isConeBounded := by
    refine ⟨0, fun α hα => mem_vadd_cone_iff.2 ?_⟩
    rw [Function.mem_support, Pi.single_apply] at hα
    by_cases h : α = 0
    · rw [h]
      simp
    · exact absurd (ite_eq_right h) hα

@[simp] lemma coeff_const (r : R) (α : Fin k →₀ ℤ) :
    (const r : ConeRing k τ R).coeff α = if α = 0 then r else 0 := Pi.single_apply _ _ _

lemma convSupport_const_subset (r : R) (x : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    convSupport (const r : ConeRing k τ R) x α ⊆ (({0} : Finset (Fin k →₀ ℤ)) : Set _) := by
  intro α' hα'
  have h1 := hα'.1
  rw [coeff_const] at h1
  by_contra h
  exact h1 (ite_eq_right (by simpa using h))

lemma coeff_const_mul (r : R) (x : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    ((const r : ConeRing k τ R) * x).coeff α = r * x.coeff α := by
  rw [coeff_mul_of_subset _ _ _ _ (convSupport_const_subset r x α)]
  simp

/-- The structure map of the `Λ`-algebra: `r ↦ r z ^ 0`. -/
noncomputable def constRingHom (k : ℕ) (τ : Equiv.Perm (Fin k)) (R : Type*) [CommRing R] :
    R →+* ConeRing k τ R where
  toFun := const
  map_one' := by ext α; simp
  map_mul' r r' := by
    ext α
    rw [coeff_const_mul, coeff_const, coeff_const]
    split_ifs <;> simp
  map_zero' := by ext α; simp
  map_add' r r' := by
    ext α
    simp only [coeff_add, coeff_const]
    split_ifs <;> simp

/-- The `Λ`-algebra structure. -/
@[hjo "lem_bglx_cone_ring_algebra"]
noncomputable instance instAlgebra : Algebra R (ConeRing k τ R) :=
  (constRingHom k τ R).toAlgebra

lemma algebraMap_eq (r : R) : algebraMap R (ConeRing k τ R) r = const r := rfl

@[simp] lemma coeff_smul (r : R) (x : ConeRing k τ R) (α : Fin k →₀ ℤ) :
    (r • x).coeff α = r * x.coeff α := by
  rw [Algebra.smul_def, algebraMap_eq, coeff_const_mul]

/-- Reading a member of the cone ring as a formal sum is `Λ`-linear. -/
noncomputable def coeffLinear (k : ℕ) (τ : Equiv.Perm (Fin k)) (R : Type*) [CommRing R] :
    ConeRing k τ R →ₗ[R] Family k R where
  toFun := ConeRing.coeff
  map_add' x y := by funext α; simp
  map_smul' r x := by funext α; simp

private lemma exp_zero_vars (α : Fin 0 →₀ ℤ) : α = 0 := Finsupp.ext fun i => i.elim0

/-- At `k = 0` the cone ring is the coefficient ring itself. -/
noncomputable def zeroVarsAlgEquiv (τ : Equiv.Perm (Fin 0)) : ConeRing 0 τ R ≃ₐ[R] R where
  toFun x := x.coeff 0
  invFun r := const r
  left_inv x := by
    refine ConeRing.ext (funext fun α => ?_)
    rw [coeff_const, exp_zero_vars α]
    simp
  right_inv r := by simp
  map_mul' x y := by
    rw [coeff_mul_of_subset x y 0 {0} fun α' _ => by simp [exp_zero_vars α']]
    simp
  map_add' x y := by simp
  commutes' r := by simp [algebraMap_eq]

lemma coeff_hahn_transport (σ ρ : Equiv.Perm (Fin k)) (x : ConeRing k ρ R) (α : Fin k →₀ ℤ) :
    ((hahnEquiv k (σ * ρ) R).symm (hahnEquiv k ρ R x)).coeff α = relabel σ x.coeff α := by
  rw [coeff_hahnEquiv_symm, coeff_hahnEquiv, relabel_apply,
    psumEquiv_symm_relabelExp σ ρ (psumEquiv (σ * ρ) α), AddEquiv.symm_apply_apply]

/-- Relabelling carries the cone ring of `ρ` onto that of `σ * ρ`, as `Λ`-algebras. -/
@[hjo "lem_bglx_relabel_ring"]
noncomputable def relabelAlgEquiv (σ ρ : Equiv.Perm (Fin k)) :
    ConeRing k ρ R ≃ₐ[R] ConeRing k (σ * ρ) R where
  toFun x := (hahnEquiv k (σ * ρ) R).symm (hahnEquiv k ρ R x)
  invFun y := (hahnEquiv k ρ R).symm (hahnEquiv k (σ * ρ) R y)
  left_inv x := by simp
  right_inv y := by simp
  map_mul' x y := by simp only [mul_def, Equiv.apply_symm_apply]
  map_add' x y := by simp only [add_def, Equiv.apply_symm_apply]
  commutes' r := by
    refine ConeRing.ext (funext fun α => ?_)
    show ((hahnEquiv k (σ * ρ) R).symm (hahnEquiv k ρ R (algebraMap R (ConeRing k ρ R) r))).coeff α
        = (algebraMap R (ConeRing k (σ * ρ) R) r).coeff α
    rw [coeff_hahn_transport, algebraMap_eq, algebraMap_eq, relabel_apply, coeff_const,
      coeff_const]
    congr 1
    simp

/-- The algebra isomorphism of `relabelAlgEquiv` is the relabelling `τ_*` of `relabel`. -/
@[simp, hjo "lem_bglx_relabel_ring"]
lemma coeff_relabelAlgEquiv (σ ρ : Equiv.Perm (Fin k)) (x : ConeRing k ρ R) (α : Fin k →₀ ℤ) :
    (relabelAlgEquiv σ ρ x).coeff α = relabel σ x.coeff α :=
  coeff_hahn_transport σ ρ x α

end Ring

end ConeRing

end HJO.Bglx
