/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import Mathlib.Combinatorics.Enumerative.Partition.Basic
public import HJO.Collinear.ShiftEsymm
public import HJO.Symmetric.AxisFree
public meta import HJO.Attr

/-! # The elementary symmetric functions freely generate, and their monomials are independent

The last input the necessity half of the BGLX vanishing criterion waits on is the linear
independence of the elementary monomials `e_λ = e_{λ₁} ⋯ e_{λ_m}` over the coefficient field, and
this file supplies it.

The route is the one `HJO/Symmetric/AxisFree.lean` takes for the axis generators, and the two
files share the mechanism: the substitution `Φ : p_k ↦ e_k` is a *weight-graded* endomorphism of
`Λ = MvPolynomial ℕ 𝕜`, it is surjective because Newton's identity inverts, and a surjective
graded endomorphism of a space whose graded pieces are finite dimensional is injective on each
piece, hence injective. Injectivity of `Φ` is exactly the independence wanted, because `Φ` carries
the monomial `p_λ` to `e_λ` and the monomials of a polynomial ring are a basis.

The generic half of that argument is isolated here as
`HJO.Sym.injective_of_mem_lambdaComp_of_surjective`, so it is stated once rather than once per
substitution: it speaks of an arbitrary endomorphism of `Λ`, with the grading entering only through
membership in the graded pieces, so it does not mention the elementary symmetric functions. The one
graded fact it needs, that such an endomorphism commutes with the projection onto a graded piece,
is `HJO.Sym.weightedHomogeneousComponent_of_mem_lambdaComp`, which lives with the graded pieces in
`HJO/Symmetric/AxisFree.lean`.

The surjectivity is the only place Newton's identity is used, and it is used in the direction that
needs no coefficient extraction: the identity `(n+1) e_{n+1} = ∑_{k ≤ n} (-1)^k p_{k+1} e_{n-k}`
solves for its last term, `(-1)^n p_{n+1}`, so `p_{n+1}` lies in the subalgebra generated by the
`e_j` as soon as `p_1, …, p_n` do. That is a strong induction and nothing more; in particular no
triangularity of the change of generators, and no computation of the diagonal coefficient
`(-1)^{n}/(n+1)`, is needed.

## Main definitions

* `HJO.Sym.elemSymmSub`: the substitution `Φ : p_k ↦ e_k`.
* `HJO.Sym.elemSymmMonomial`: the elementary monomial `e_μ` of a multiset of parts.
* `HJO.Sym.partsExp`: the exponent vector of `p_μ`, the monomial of `Λ` that `Φ` carries to `e_μ`.
* `HJO.Sym.wordExp`: the exponent vector of the monomial that `Φ` carries to `e_{γ₁} ⋯ e_{γ_m}`, for
  a word `γ` of letters.

## Main statements

* `HJO.Sym.injective_of_mem_lambdaComp_of_surjective`: a surjective graded endomorphism of `Λ` is
  injective.
* `HJO.Sym.elemSymmSub_bijective`: the substitution `p_k ↦ e_k` is bijective; equivalently the
  elementary symmetric functions are a free system of generators of `Λ`.
* `HJO.Sym.linearIndependent_elemSymmMonomial`.

## Implementation notes

**The base is an arbitrary `ℚ`-algebra for the surjectivity and a field for the injectivity.**
Newton's identity needs the positive integers invertible, which `[Algebra ℚ K]` gives; the
injectivity argument needs the graded pieces finite dimensional, which
`HJO.Sym.lambdaComp_finiteDimensional` states over a field. Both hold at the standing field
`𝕜 = ℚ(q, u)`.

**The independence is stated over all degrees at once**, indexed by `Σ d, Nat.Partition d` -- the
range "all partitions `λ` of all `d ≥ 0`". The proof groups a relation by degree
and applies the elementary monomial basis of each graded piece; the proof here does not need the
grading at that point at all, the injectivity of `Φ` being already a statement about all of `Λ`.

## References

The file formalises Lemma `HJO.Sym.linearIndependent_elemSymmMonomial` and Definition
`HJO.Sym.elemSymmMonomial`. The generic injectivity argument is
the one Lemmas `HJO.Sym.eq_zero_of_mem_lambdaComp_of_axisSub_eq_zero` and
`HJO.Sym.axisSub_injective` run for the axis substitution.
-/

@[expose] public section

open MvPolynomial

namespace HJO.Sym

/-! ### A surjective graded endomorphism of `Λ` is injective -/

section Field

variable {L : Type*} [Field L] [Algebra ℚ L]

omit [Algebra ℚ L] in
/-- **Degreewise injectivity of a surjective graded endomorphism of `Λ`.** On the graded piece `Λ_d`
it restricts to a surjective linear endomorphism -- the degree `d` component of a preimage is a
preimage again, the projection commuting with `Φ` -- and `Λ_d` is finite dimensional, so that
restriction is injective. -/
theorem eq_zero_of_mem_lambdaComp_of_surjective (Φ : Lambda L →ₗ[L] Lambda L)
    (hgr : ∀ (d : ℕ) (f : Lambda L), f ∈ LambdaComp L d → Φ f ∈ LambdaComp L d)
    (hsurj : Function.Surjective Φ) (d : ℕ) {g : Lambda L} (hg : g ∈ LambdaComp L d)
    (h0 : Φ g = 0) : g = 0 := by
  have hcomp := weightedHomogeneousComponent_of_mem_lambdaComp Φ hgr
  have := lambdaComp_finiteDimensional L d
  set Ψ : LambdaComp L d →ₗ[L] LambdaComp L d := Φ.restrict fun _ hf => hgr d _ hf
  have hsurjΨ : Function.Surjective Ψ := by
    rintro ⟨f, hf⟩
    refine ⟨⟨weightedHomogeneousComponent (fun i => i + 1) d (hsurj f).choose,
      weightedHomogeneousComponent_mem _ _ d⟩, Subtype.ext ?_⟩
    change Φ (weightedHomogeneousComponent (fun i => i + 1) d (hsurj f).choose) = f
    rw [← hcomp, (hsurj f).choose_spec]
    exact (mem_lambdaComp.1 hf).weightedHomogeneousComponent_same
  have hval : Ψ ⟨g, hg⟩ = Ψ 0 := by
    rw [map_zero]
    exact Subtype.ext h0
  simpa using Subtype.ext_iff.1 (LinearMap.injective_iff_surjective.2 hsurjΨ hval)

omit [Algebra ℚ L] in
/-- **A surjective graded endomorphism of `Λ` is injective.** Each graded component of an element of
the kernel is again in the kernel, the projection commuting with `Φ`, and there it vanishes by
degreewise injectivity.

This is the mechanism `HJO.Sym.eq_zero_of_mem_lambdaComp_of_axisSub_eq_zero` and
`HJO.Sym.axisSub_injective` run for the axis substitution, stated once for any graded
endomorphism. -/
theorem injective_of_mem_lambdaComp_of_surjective (Φ : Lambda L →ₗ[L] Lambda L)
    (hgr : ∀ (d : ℕ) (f : Lambda L), f ∈ LambdaComp L d → Φ f ∈ LambdaComp L d)
    (hsurj : Function.Surjective Φ) : Function.Injective Φ := by
  have hcomp := weightedHomogeneousComponent_of_mem_lambdaComp Φ hgr
  refine (injective_iff_map_eq_zero Φ).2 fun h hh => ?_
  have hc : ∀ N : ℕ, weightedHomogeneousComponent (fun i => i + 1) N h = 0 := fun N =>
    eq_zero_of_mem_lambdaComp_of_surjective Φ hgr hsurj N
      (weightedHomogeneousComponent_mem _ h N) (by rw [← hcomp, hh, map_zero])
  rw [← sum_weightedHomogeneousComponent_range h, Finset.sum_eq_zero fun N _ => hc N]

end Field

/-! ### The substitution carrying the power sums to the elementary symmetric functions -/

/-- The substitution `Φ : p_k ↦ e_k`, the `K`-algebra endomorphism of `Λ` sending the generator of
index `i` -- which stands for `p_{i+1}` -- to the elementary symmetric function `e_{i+1}`. It exists
and is unique because `Lambda K` is the polynomial algebra on those generators. -/
noncomputable def elemSymmSub (K : Type*) [CommRing K] [Algebra ℚ K] :
    Lambda K →ₐ[K] Lambda K :=
  MvPolynomial.aeval fun i => elemSymm K (i + 1)

/-- The substitution sends the generator of index `i` to `e_{i+1}`. -/
@[simp] theorem elemSymmSub_X (K : Type*) [CommRing K] [Algebra ℚ K] (i : ℕ) :
    elemSymmSub K (MvPolynomial.X i) = elemSymm K (i + 1) :=
  MvPolynomial.aeval_X _ i

/-- The substitution sends `p_k` to `e_k` for every `k ≥ 1`. At `k = 0` it does not: `p_0` is the
same generator as `p_1`, by the truncated subtraction of `HJO.Sym.powerSum`, whereas `e_0 = 1`. -/
theorem elemSymmSub_powerSum (K : Type*) [CommRing K] [Algebra ℚ K] {k : ℕ} (hk : 1 ≤ k) :
    elemSymmSub K (powerSum K k) = elemSymm K k := by
  obtain ⟨m, rfl⟩ : ∃ m, k = m + 1 := ⟨k - 1, by omega⟩
  rw [Bglx.powerSum_succ_eq_X, elemSymmSub_X]

/-- **Every power sum lies in the subalgebra generated by the elementary symmetric functions.**
Newton's identity `(n+1) e_{n+1} = ∑_{k=0}^{n} (-1)^k p_{k+1} e_{n-k}` solves for its last term
`(-1)^n p_{n+1}`, so `p_{n+1}` is in that subalgebra as soon as `p_1, …, p_n` are, which is a strong
induction on `n`. Dividing by `n + 1` is what `[Algebra ℚ K]` is for; no triangularity of the change
of generators and no value of the diagonal coefficient are needed. -/
theorem powerSum_mem_adjoin_elemSymm (K : Type*) [CommRing K] [Algebra ℚ K] {k : ℕ} (hk : 1 ≤ k) :
    powerSum K k ∈ Algebra.adjoin K (Set.range fun i : ℕ => elemSymm K (i + 1)) := by
  obtain ⟨n, rfl⟩ : ∃ n, k = n + 1 := ⟨k - 1, by omega⟩
  clear hk
  set A := Algebra.adjoin K (Set.range fun i : ℕ => elemSymm K (i + 1))
  have heA : ∀ n : ℕ, elemSymm K n ∈ A := by
    intro n
    match n with
    | 0 => rw [Bglx.elemSymm_zero_eq_one]; exact one_mem _
    | m + 1 => exact Algebra.subset_adjoin ⟨m, rfl⟩
  have hsign : ∀ n : ℕ, (-1 : Lambda K) ^ n ∈ A := fun n => pow_mem (neg_mem (one_mem A)) n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    have hnewton : ((n : Lambda K) + 1) * elemSymm K (n + 1)
        = ∑ k ∈ Finset.range (n + 1),
          (-1 : Lambda K) ^ k * powerSum K (k + 1) * elemSymm K (n - k) := by
      rw [elemSymm, ← mul_assoc, ← MvPolynomial.algebraMap_eq,
        Bglx.natCast_mul_algebraMap_inv, one_mul]
    have hmem : (-1 : Lambda K) ^ n * powerSum K (n + 1) ∈ A := by
      have heq : (-1 : Lambda K) ^ n * powerSum K (n + 1)
          = ((n : Lambda K) + 1) * elemSymm K (n + 1)
            - ∑ k ∈ Finset.range n,
              (-1 : Lambda K) ^ k * powerSum K (k + 1) * elemSymm K (n - k) := by
        rw [hnewton, Finset.sum_range_succ, Nat.sub_self, Bglx.elemSymm_zero_eq_one, mul_one]
        ring
      rw [heq]
      refine sub_mem (mul_mem (add_mem (natCast_mem A n) (one_mem A)) (heA (n + 1)))
        (Subalgebra.sum_mem _ fun k hk => ?_)
      rw [Finset.mem_range] at hk
      exact mul_mem (mul_mem (hsign k) (ih k hk)) (heA (n - k))
    -- cancel the sign: `p_{n+1} = (-1)^n ((-1)^n p_{n+1})`
    rw [show powerSum K (n + 1)
        = (-1 : Lambda K) ^ n * ((-1 : Lambda K) ^ n * powerSum K (n + 1)) by
      rw [← mul_assoc, ← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow, one_mul]]
    exact mul_mem (hsign n) hmem

/-- **The elementary symmetric functions generate `Λ`**: the power sums generate it, and each of
them lies in the subalgebra generated by the `e_j`. -/
theorem adjoin_elemSymm_eq_top (K : Type*) [CommRing K] [Algebra ℚ K] :
    Algebra.adjoin K (Set.range fun i : ℕ => elemSymm K (i + 1)) = ⊤ := by
  rw [eq_top_iff, ← MvPolynomial.adjoin_range_X, Algebra.adjoin_le_iff]
  rintro f ⟨i, rfl⟩
  rw [show (MvPolynomial.X i : Lambda K) = powerSum K (i + 1) from
    (Bglx.powerSum_succ_eq_X i).symm]
  exact powerSum_mem_adjoin_elemSymm K (Nat.le_add_left 1 i)

/-- **The substitution `p_k ↦ e_k` is surjective**: its image is the subalgebra generated by the
elementary symmetric functions, and those generate. -/
theorem elemSymmSub_surjective (K : Type*) [CommRing K] [Algebra ℚ K] :
    Function.Surjective (elemSymmSub K) := by
  rw [← AlgHom.range_eq_top, elemSymmSub, ← Algebra.adjoin_range_eq_range_aeval]
  exact adjoin_elemSymm_eq_top K

/-- **The substitution `p_k ↦ e_k` is graded.** It sends a monomial of degree `d` to a product of
elementary symmetric functions whose degrees add up to `d` again, `e_n` being homogeneous of degree
`n`. -/
theorem elemSymmSub_mem_lambdaComp (K : Type*) [CommRing K] [Algebra ℚ K] {d : ℕ} {f : Lambda K}
    (hf : f ∈ LambdaComp K d) : elemSymmSub K f ∈ LambdaComp K d := by
  classical
  refine IsWeightedHomogeneous.induction_on
    (motive := fun p _ => elemSymmSub K p ∈ LambdaComp K d) ?_ ?_ ?_ (mem_lambdaComp.1 hf)
  · rw [map_zero]
    exact zero_mem _
  · intro p q _ _ hp hq
    rw [map_add]
    exact add_mem hp hq
  · intro e r hr
    rw [mem_lambdaComp, monomial_eq, map_mul, algHom_C, algebraMap_eq]
    refine IsWeightedHomogeneous.C_mul ?_ r
    rw [Finsupp.prod, map_prod, ← hr, Finsupp.weight_apply, Finsupp.sum]
    refine IsWeightedHomogeneous.prod _ _ _ fun i _ => ?_
    rw [map_pow, elemSymmSub_X]
    exact (Bglx.isWeightedHomogeneous_elemSymm K (i + 1)).pow (e i)

/-- **The substitution `p_k ↦ e_k` is injective**, over a field: it is a surjective graded
endomorphism of `Λ`, whose graded pieces are finite dimensional. -/
theorem elemSymmSub_injective (L : Type*) [Field L] [Algebra ℚ L] :
    Function.Injective (elemSymmSub L) :=
  injective_of_mem_lambdaComp_of_surjective (elemSymmSub L).toLinearMap
    (fun _ _ hf => elemSymmSub_mem_lambdaComp L hf) (elemSymmSub_surjective L)

/-- **The elementary symmetric functions freely generate `Λ`**, over a field of characteristic zero:
the substitution `p_k ↦ e_k` is bijective. -/
theorem elemSymmSub_bijective (L : Type*) [Field L] [Algebra ℚ L] :
    Function.Bijective (elemSymmSub L) :=
  ⟨elemSymmSub_injective L, elemSymmSub_surjective L⟩

/-! ### The elementary monomials -/

/-- The elementary monomial `e_μ` of a multiset `μ` of natural numbers: the product of the
elementary symmetric functions `e_i` over the members `i` of `μ`, the empty multiset giving the
empty product `1`. For a partition `λ` of `d`, i.e. `λ : Nat.Partition d`, the product
`e_λ = e_{λ₁}e_{λ₂}⋯e_{λ_m}` is `elemSymmMonomial K λ.parts`; the order of the parts is immaterial
because `Lambda K` is commutative. -/
@[hjo "def_cm_emonomial"]
noncomputable def elemSymmMonomial (K : Type*) [CommRing K] [Algebra ℚ K] (μ : Multiset ℕ) :
    Lambda K :=
  (μ.map (elemSymm K)).prod

/-- The elementary monomial of the empty multiset is `1`. -/
@[simp] theorem elemSymmMonomial_zero (K : Type*) [CommRing K] [Algebra ℚ K] :
    elemSymmMonomial K (0 : Multiset ℕ) = 1 := by
  rw [elemSymmMonomial, Multiset.map_zero, Multiset.prod_zero]

/-- Inserting a part multiplies the elementary monomial by the matching elementary symmetric
function. -/
theorem elemSymmMonomial_cons (K : Type*) [CommRing K] [Algebra ℚ K] (a : ℕ) (μ : Multiset ℕ) :
    elemSymmMonomial K (a ::ₘ μ) = elemSymm K a * elemSymmMonomial K μ := by
  rw [elemSymmMonomial, elemSymmMonomial, Multiset.map_cons, Multiset.prod_cons]

/-- The exponent vector of the power-sum monomial `p_μ = p_{μ₁} ⋯ p_{μ_l}`: the generator standing
for `p_j` has index `j - 1`, so the multiplicities are those of the parts of `μ` shifted down by
one. For a multiset of positive parts this is the monomial of `Λ` that the substitution `p_k ↦ e_k`
carries to `e_μ`. -/
noncomputable def partsExp (μ : Multiset ℕ) : ℕ →₀ ℕ :=
  Multiset.toFinsupp (μ.map fun i => i - 1)

/-- The exponent vector of the empty multiset is `0`. -/
@[simp] theorem partsExp_zero : partsExp 0 = 0 := by
  rw [partsExp, Multiset.map_zero, map_zero]

/-- Inserting a part adds the matching generator to the exponent vector. -/
theorem partsExp_cons (a : ℕ) (μ : Multiset ℕ) :
    partsExp (a ::ₘ μ) = Finsupp.single (a - 1) 1 + partsExp μ := by
  rw [partsExp, partsExp, Multiset.map_cons, ← Multiset.singleton_add, map_add,
    Multiset.toFinsupp_singleton]

/-- **The substitution `p_k ↦ e_k` carries `p_μ` to `e_μ`**, for a multiset `μ` of positive parts.
The positivity is needed at each part: the generator of index `a - 1` goes to `e_a` only because
`a ≥ 1`. -/
theorem elemSymmSub_monomial_partsExp (K : Type*) [CommRing K] [Algebra ℚ K] (μ : Multiset ℕ)
    (hμ : ∀ i ∈ μ, 1 ≤ i) :
    elemSymmSub K (MvPolynomial.monomial (partsExp μ) 1) = elemSymmMonomial K μ := by
  induction μ using Multiset.induction_on with
  | empty =>
    rw [partsExp_zero, elemSymmMonomial_zero, MvPolynomial.monomial_zero', map_one, map_one]
  | cons a s ih =>
    have ha : 1 ≤ a := hμ a (Multiset.mem_cons_self a s)
    have hs : ∀ i ∈ s, 1 ≤ i := fun i hi => hμ i (Multiset.mem_cons_of_mem hi)
    rw [partsExp_cons, MvPolynomial.monomial_single_add, pow_one, map_mul, elemSymmSub_X,
      show a - 1 + 1 = a from by omega, elemSymmMonomial_cons, ih hs]

/-- **The exponent vector determines a multiset of positive parts.** Shifting the parts down by one
is undone by shifting back up, which is where the positivity enters, and `Multiset.toFinsupp` is a
bijection. -/
theorem partsExp_inj {μ ν : Multiset ℕ} (hμ : ∀ i ∈ μ, 1 ≤ i) (hν : ∀ i ∈ ν, 1 ≤ i)
    (h : partsExp μ = partsExp ν) : μ = ν := by
  have hmap : μ.map (fun i => i - 1) = ν.map (fun i => i - 1) :=
    Multiset.toFinsupp.injective h
  have hback : ∀ σ : Multiset ℕ, (∀ i ∈ σ, 1 ≤ i) →
      (σ.map (fun i => i - 1)).map (fun i => i + 1) = σ := by
    intro σ hσ
    rw [Multiset.map_map]
    refine Eq.trans (Multiset.map_congr rfl fun i hi => ?_) (Multiset.map_id' σ)
    have := hσ i hi
    change i - 1 + 1 = i
    omega
  rw [← hback μ hμ, hmap, hback ν hν]

/-- **The elementary monomials of all degrees are independent.** The family `(e_λ)`, indexed by all
partitions `λ` of all `d ≥ 0`, is linearly independent over the coefficient field.

The proof does not group by degree. The substitution `p_k ↦ e_k` carries the monomial `p_λ` of `Λ`
to `e_λ`, distinct partitions give distinct monomials because the parts are positive, the monomials
of a polynomial ring are linearly independent, and the substitution is injective. -/
@[hjo "lem_bglx_emonomial_independent"]
theorem linearIndependent_elemSymmMonomial (L : Type*) [Field L] [Algebra ℚ L] :
    LinearIndependent L fun lam : Σ d : ℕ, Nat.Partition d =>
      elemSymmMonomial L lam.2.parts := by
  have hinj : Function.Injective fun lam : Σ d : ℕ, Nat.Partition d => partsExp lam.2.parts := by
    rintro ⟨d, p⟩ ⟨e, q⟩ h
    have hpq : p.parts = q.parts :=
      partsExp_inj (fun i hi => p.parts_pos hi) (fun i hi => q.parts_pos hi) h
    have hde : d = e := by rw [← p.parts_sum, ← q.parts_sum, hpq]
    subst hde
    exact congrArg (Sigma.mk d) (Nat.Partition.ext hpq)
  have hbasis : LinearIndependent L fun lam : Σ d : ℕ, Nat.Partition d =>
      MvPolynomial.monomial (partsExp lam.2.parts) (1 : L) := by
    have h := (MvPolynomial.basisMonomials ℕ L).linearIndependent.comp
      (fun lam : Σ d : ℕ, Nat.Partition d => partsExp lam.2.parts) hinj
    rwa [MvPolynomial.coe_basisMonomials] at h
  have hmap := hbasis.map' (elemSymmSub L).toLinearMap
    (LinearMap.ker_eq_bot.2 (elemSymmSub_injective L))
  have heq : (⇑(elemSymmSub L).toLinearMap ∘ fun lam : Σ d : ℕ, Nat.Partition d =>
      MvPolynomial.monomial (partsExp lam.2.parts) (1 : L))
      = fun lam : Σ d : ℕ, Nat.Partition d => elemSymmMonomial L lam.2.parts :=
    funext fun lam =>
      elemSymmSub_monomial_partsExp L lam.2.parts fun i hi => lam.2.parts_pos hi
  rwa [heq] at hmap

/-! ### The elementary monomial of a word, and when two words give the same one -/

/-- The exponent vector of the monomial of `Λ` that the substitution `p_k ↦ e_k` carries to
`e_{γ₁} e_{γ₂} ⋯ e_{γ_m}`: the letter `γ i` contributes the generator of index `γ i - 1` when it is
positive and contributes nothing when it is `0`, since `e_0 = 1`. Two words have the same exponent
vector exactly when they are permutations of one another. -/
noncomputable def wordExp {m : ℕ} (γ : Fin m → ℕ) : ℕ →₀ ℕ :=
  ∑ i : Fin m, if γ i = 0 then 0 else Finsupp.single (γ i - 1) 1

/-- **The exponent vector of a word counts its letters**: its value at `k` is the number of indices
carrying the letter `k + 1`. -/
theorem wordExp_apply {m : ℕ} (γ : Fin m → ℕ) (k : ℕ) :
    wordExp γ k = (Finset.univ.filter fun i : Fin m => γ i = k + 1).card := by
  classical
  rw [wordExp, Finsupp.finsetSum_apply, Finset.card_filter]
  refine Finset.sum_congr rfl fun i _ => ?_
  by_cases hi : γ i = 0
  · rw [ite_eq_left hi, ite_eq_right (show ¬ γ i = k + 1 from by omega)]
    exact Finsupp.zero_apply
  · rw [ite_eq_right hi, Finsupp.single_apply]
    split_ifs <;> omega

/-- **The substitution `p_k ↦ e_k` carries the monomial of a word to its elementary monomial.** -/
theorem elemSymmSub_monomial_wordExp (K : Type*) [CommRing K] [Algebra ℚ K] {m : ℕ}
    (γ : Fin m → ℕ) :
    elemSymmSub K (MvPolynomial.monomial (wordExp γ) 1) = ∏ i : Fin m, elemSymm K (γ i) := by
  rw [wordExp, MvPolynomial.monomial_sum_one, map_prod]
  refine Finset.prod_congr rfl fun i _ => ?_
  by_cases hi : γ i = 0
  · rw [ite_eq_left hi, hi, MvPolynomial.monomial_zero', map_one, map_one,
      Bglx.elemSymm_zero_eq_one]
  · rw [ite_eq_right hi, show (MvPolynomial.monomial (Finsupp.single (γ i - 1) 1) (1 : K))
      = MvPolynomial.X (γ i - 1) from by
        rw [← MvPolynomial.X_pow_eq_monomial, pow_one], elemSymmSub_X,
      show γ i - 1 + 1 = γ i from by omega]

/-- **Two words with the same exponent vector are permutations of one another.** The two words have
the same number of indices carrying each letter -- for a positive letter that is the exponent
vector, and for the letter `0` it follows because the two counts of all letters both add up to the
number of indices -- and the bijections between the fibres glue to a permutation. -/
theorem exists_perm_of_wordExp_eq {m : ℕ} {γ δ : Fin m → ℕ} (h : wordExp γ = wordExp δ) :
    ∃ σ : Equiv.Perm (Fin m), ∀ i : Fin m, δ i = γ (σ i) := by
  classical
  have hfil : ∀ k : ℕ, (Finset.univ.filter fun i : Fin m => γ i = k).card
      = (Finset.univ.filter fun i : Fin m => δ i = k).card := by
    have hsucc : ∀ j : ℕ, (Finset.univ.filter fun i : Fin m => γ i = j + 1).card
        = (Finset.univ.filter fun i : Fin m => δ i = j + 1).card := fun j => by
      rw [← wordExp_apply, ← wordExp_apply, h]
    intro k
    match k with
    | j + 1 => exact hsucc j
    | 0 =>
      set M := (Finset.univ.sup γ) ⊔ (Finset.univ.sup δ)
      have htotal : ∀ ε : Fin m → ℕ, (∀ i : Fin m, ε i ≤ M) →
          m = ∑ k ∈ Finset.range (M + 1),
            (Finset.univ.filter fun i : Fin m => ε i = k).card := by
        intro ε hε
        have hmaps : Set.MapsTo ε (Finset.univ : Finset (Fin m)) (Finset.range (M + 1)) :=
          fun i _ => Finset.mem_coe.2 (Finset.mem_range.2 (Nat.lt_succ_of_le (hε i)))
        have hcount := Finset.card_eq_sum_card_fiberwise hmaps
        rwa [Finset.card_univ, Fintype.card_fin] at hcount
      have hγ := htotal γ fun i => le_sup_of_le_left (Finset.le_sup (Finset.mem_univ i))
      have hδ := htotal δ fun i => le_sup_of_le_right (Finset.le_sup (Finset.mem_univ i))
      rw [Finset.sum_range_succ'] at hγ hδ
      rw [Finset.sum_congr rfl fun j _ => hsucc j] at hγ
      omega
  have hcard : ∀ k : ℕ,
      Fintype.card {i : Fin m // δ i = k} = Fintype.card {i : Fin m // γ i = k} := fun k => by
    rw [Fintype.card_subtype, Fintype.card_subtype]
    exact (hfil k).symm
  refine ⟨(Equiv.sigmaFiberEquiv δ).symm.trans
    ((Equiv.sigmaCongrRight fun k => Fintype.equivOfCardEq (hcard k)).trans
      (Equiv.sigmaFiberEquiv γ)), fun i => ?_⟩
  exact (Fintype.equivOfCardEq (hcard (δ i)) ⟨i, rfl⟩).2.symm

end HJO.Sym
