/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Symmetric.SymmetricFunctions
public meta import HJO.Attr

/-! # The starred vocabulary of the collinear commutation argument

The remaining vocabulary the collinear commutativity argument quotes: the starred plethystic
displacement `δ*`, the starred (adjoint) family of basic operators `D*_k`, the algebra `𝖠` the
basic operators `D_k` generate inside `End_𝕜(Λ)`, and the two structural data on that algebra
the argument uses -- a Macdonald conjugator and an index shift.

Both structural data are *predicates*: nothing here asserts that
such a `∇` or such an `𝖲` exists, and neither is constructed. A consumer that needs one takes it
as a hypothesis.

Like `Sym.plethShift` and `Sym.plethCreate`, the starred displacement is written in the variable
`w = z⁻¹`: it sends `p_k` to `p_k` minus a multiple of `z⁻ᵏ`, so its image is an honest
polynomial in `w` and the target is `Λ[w]` rather than a ring of Laurent polynomials. Extracting
the coefficient of `z^k` from a product with the power series `∑_{i ≥ 0} h_i zⁱ` is then the
finite pairing `Sym.coeffPairing` against `h_{k+j}`, which is what makes `D*_k` well posed
without any claim about where the support of `δ*(f)` sits.

The minus sign of `δ*` is a virtual difference of alphabets, so the scalar attached to `p_k` is
`-(1 - q⁻ᵏ)(1 - u⁻ᵏ)` and *not* `-M̃ᵏ` for `M̃ = (1 - q⁻¹)(1 - u⁻¹)`; the notation `f[X - M̃/z]`
names `δ*(f)` and nothing more, so `M̃` itself does not occur in any definition below.
-/

@[expose] public section

namespace HJO.Sym

/-! ### The starred plethystic displacement -/

section Displacement

variable {L : Type*} [Field L]

/-- The starred plethystic displacement `δ*`, sending `p_k` to
`p_k - (1 - q⁻ᵏ) * (1 - u⁻ᵏ) * z⁻ᵏ` and written `f[X - M̃/z]` on elements. The minus sign is a
virtual difference of alphabets, so the scalar attached to `p_k` is `-(1 - q⁻ᵏ)(1 - u⁻ᵏ)` and not
`-M̃ᵏ`. Its target is the polynomial ring on `w = z⁻¹`, since only non-negative powers of `w`
occur. -/
@[hjo "def_pleth_shift_star"]
noncomputable def plethShiftStar (q u : L) : Lambda L →ₐ[L] Polynomial (Lambda L) :=
  MvPolynomial.aeval fun i => Polynomial.C (powerSum L (i + 1)) -
    Polynomial.C (MvPolynomial.C ((1 - (q ^ (i + 1))⁻¹) * (1 - (u ^ (i + 1))⁻¹))) *
      Polynomial.X ^ (i + 1)

/-- The value of the starred displacement on the generator of index `i`, which stands for
`p_{i+1}`. -/
@[simp]
theorem plethShiftStar_X (q u : L) (i : ℕ) :
    plethShiftStar q u (MvPolynomial.X i) = Polynomial.C (powerSum L (i + 1)) -
      Polynomial.C (MvPolynomial.C ((1 - (q ^ (i + 1))⁻¹) * (1 - (u ^ (i + 1))⁻¹))) *
        Polynomial.X ^ (i + 1) := by
  rw [plethShiftStar, MvPolynomial.aeval_X]

/-- The value of the starred displacement on the power sum `p_k`, for `k ≥ 1`. -/
theorem plethShiftStar_powerSum (q u : L) {k : ℕ} (hk : 0 < k) :
    plethShiftStar q u (powerSum L k) = Polynomial.C (powerSum L k) -
      Polynomial.C (MvPolynomial.C ((1 - (q ^ k)⁻¹) * (1 - (u ^ k)⁻¹))) * Polynomial.X ^ k := by
  obtain ⟨j, rfl⟩ : ∃ j, k = j + 1 := ⟨k - 1, by omega⟩
  have h : powerSum L (j + 1) = MvPolynomial.X j := rfl
  rw [h, plethShiftStar_X, h]

end Displacement

/-! ### The starred basic operators -/

section DopStar

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- The starred basic operator `DopStar q u k`, the `L`-linear endomorphism of `Lambda L`
extracting the coefficient of `zᵏ` from `f[X - M̃/z] * ∑_{i ≥ 0} h_i zⁱ`. Written in `w = z⁻¹`
the coefficient of `wʲ` of the starred displacement is paired with `h_{k+j}`, a finite sum
because the displacement is a polynomial in `w` and `h_i = 0` for `i < 0`. -/
@[hjo "def_dop_star"]
noncomputable def DopStar (q u : L) (k : ℕ) : Module.End L (Lambda L) :=
  coeffPairing (fun j => completeHomog L (k + j)) ∘ₗ (plethShiftStar q u).toLinearMap

/-- The starred basic operator as the pairing it is, evaluated at an element. -/
theorem dopStar_apply (q u : L) (k : ℕ) (f : Lambda L) :
    DopStar q u k f =
      coeffPairing (fun j => completeHomog L (k + j)) (plethShiftStar q u f) := rfl

end DopStar

/-! ### The operator algebra and the two structural data on it -/

section Algebra

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- The operator algebra `𝖠`: the `L`-subalgebra of `End_L(Lambda L)` generated by the basic
operators `D_0, D_1, D_2, …`. -/
@[hjo "def_dop_algebra"]
noncomputable def DopAlgebra (q u : L) : Subalgebra L (Module.End L (Lambda L)) :=
  Algebra.adjoin L (Set.range (Dop q u))

/-- Each basic operator lies in the algebra it generates. -/
theorem dop_mem_dopAlgebra (q u : L) (k : ℕ) : Dop q u k ∈ DopAlgebra q u :=
  Algebra.subset_adjoin (Set.mem_range_self k)

/-- The basic operator `D_k` as an element of the operator algebra `𝖠`. -/
noncomputable def dopGen (q u : L) (k : ℕ) : DopAlgebra q u :=
  ⟨Dop q u k, dop_mem_dopAlgebra q u k⟩

@[simp]
theorem dopGen_coe (q u : L) (k : ℕ) : (dopGen q u k : Module.End L (Lambda L)) = Dop q u k := rfl

/-- A *Macdonald conjugator*: a bijective `L`-linear endomorphism `∇` of `Lambda L` that
commutes with `D_0`, turns multiplication by `e_1` into `-D_1` and turns `D*_1` into
multiplication by `e_1`. Bijectivity and these three equations are the whole condition: `∇` is
not asked to be an algebra map, and nothing here asserts that such a `∇` exists. -/
@[hjo "def_macdonald_conjugator"]
structure IsMacdonaldConjugator (q u : L) (nabla : Module.End L (Lambda L)) : Prop where
  /-- `∇` is bijective. -/
  bijective : Function.Bijective nabla
  /-- `∇(D_0 f) = D_0(∇ f)`. -/
  map_dop_zero : ∀ f : Lambda L, nabla (Dop q u 0 f) = Dop q u 0 (nabla f)
  /-- `∇(e_1 f) = -D_1(∇ f)`. -/
  map_elemSymm_one_mul : ∀ f : Lambda L,
    nabla (elemSymm L 1 * f) = -Dop q u 1 (nabla f)
  /-- `∇(D*_1 f) = e_1 · ∇ f`. -/
  map_dopStar_one : ∀ f : Lambda L,
    nabla (DopStar q u 1 f) = elemSymm L 1 * nabla f

/-- An *index shift*: an `L`-algebra endomorphism `𝖲` of the operator algebra `𝖠` sending `D_k`
to `D_{k+1}` for every `k ≥ 0`. An endomorphism, not an automorphism, and a single map rather
than a group action: this one shift is all the argument uses. -/
@[hjo "def_index_shift"]
def IsIndexShift (q u : L) (S : DopAlgebra q u →ₐ[L] DopAlgebra q u) : Prop :=
  ∀ k : ℕ, S (dopGen q u k) = dopGen q u (k + 1)

/-- An index shift, read in `End_L(Lambda L)` rather than in the subalgebra. -/
theorem isIndexShift_iff (q u : L) (S : DopAlgebra q u →ₐ[L] DopAlgebra q u) :
    IsIndexShift q u S ↔
      ∀ k : ℕ, (S (dopGen q u k) : Module.End L (Lambda L)) = Dop q u (k + 1) := by
  simp [IsIndexShift, Subtype.ext_iff]

end Algebra

end HJO.Sym
