/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Collinear.FiniteAlphabet
public import HJO.Collinear.LaurentNonpositive
public import HJO.Macdonald.DopZeroHtilde
public meta import HJO.Attr

/-! # The creation displacement has no positive power of `z`

`HJO.Sym.plethCreateQLaurent_mem_nonpositive`: for every `F ∈ Λ`, `qs(F)` lies in `Λ[z^{-1}]`, the
subalgebra of `Λ[z, z^{-1}]` of `HJO.Laurent.nonpositive` — the elements every monomial of which has
nonpositive exponent in `z`.

## Main definitions

* `HJO.Laurent.ofRecip`: the reading of a polynomial as a Laurent polynomial in the *reciprocal*
  variable, `w ↦ z^{-1}`, an `R`-algebra homomorphism `R[w] → R[z^{±1}]`.
* `HJO.Sym.plethCreateQLaurent`: the creation displacement `qs` with its values read inside
  `Λ[z, z^{-1}]`, which is the ring `HJO.Sym.plethCreateQ` names as its target.

## Main results

* `HJO.Laurent.ofRecip_mem_nonpositive`: the whole image of `ofRecip` is nonpositive.
* `HJO.Sym.plethCreateQLaurent_powerSum`: the value on a generator, `p_k - (1-q^k)z^{-k}`. This is
  the defining clause of `HJO.Sym.plethCreateQ` read in the Laurent ring, and it is what pins the
  object the main statement is about.
* `HJO.Sym.plethCreateQLaurent_mem_nonpositive`.

## Where the content sits

As usually defined, `qs` maps into `Λ[z, z^{-1}]` and its image is then proved nonpositive; the Lean
`HJO.Sym.plethCreateQ` of `HJO/Macdonald/DopZeroHtilde.lean` is defined instead into
`Λ[w]` with `w = z^{-1}`, so that the coefficient `[z^{-m}]qs(F)` is a `Polynomial.coeff`. The
statement is therefore *not* vacuous and *not* a restatement of that design choice: what it needs is
the bridge `ofRecip` into the Laurent ring `Λ[z, z^{-1}]`, and the fact that the bridge's whole
image is nonpositive. That fact is one membership — the monomial `z^{-1}` is nonpositive — pushed
along `Algebra.adjoin R {z^{-1}} ≤ nonpositive R 1`, since `ofRecip p` is by construction an
`aeval` at `z^{-1}`. The usual route (each generator lands in the subalgebra, the preimage of
a subalgebra is a subalgebra, `Λ` is generated by the `p_k`) is the same argument with the two
generation steps composed into one: `Λ[w]` is generated by `w`.

No parameter hypothesis is needed and none is carried. The exponents occurring are `0` and `-k`
whatever `q` is, so there is nothing to refute at `q = 0`, at `q = 1`, or at a root of unity: the
statement is unconditional, in contrast with the `u`-side identities of
`HJO/Macdonald/DopZeroHtilde.lean`, which are false at roots of unity and carry hypotheses
for it.
-/

@[expose] public section

namespace HJO.Laurent

variable {R : Type*} [CommRing R]

/-! ### A polynomial in `w` as a Laurent polynomial in `z = w^{-1}` -/

/-- **A polynomial read in the reciprocal variable**: the `R`-algebra homomorphism
`R[w] → R[z^{±1}]` sending `w` to `z^{-1}`, the Laurent ring being spelled
`AddMonoidAlgebra R (Fin 1 →₀ ℤ)` as everywhere in this library. It is `Polynomial.aeval` at
the monomial `z^{-1}`, so nothing has to be checked. -/
noncomputable def ofRecip (R : Type*) [CommRing R] :
    Polynomial R →ₐ[R] AddMonoidAlgebra R (Fin 1 →₀ ℤ) :=
  Polynomial.aeval (AddMonoidAlgebra.single (Finsupp.single (0 : Fin 1) (-1 : ℤ)) (1 : R))

@[simp]
theorem ofRecip_X :
    ofRecip R Polynomial.X =
      AddMonoidAlgebra.single (Finsupp.single (0 : Fin 1) (-1 : ℤ)) (1 : R) :=
  Polynomial.aeval_X _

@[simp]
theorem ofRecip_C (r : R) : ofRecip R (Polynomial.C r) = AddMonoidAlgebra.single 0 r :=
  Polynomial.aeval_C _ _

/-- The monomial `z^{-1}` is nonpositive: its one exponent vector takes the value `-1` at the one
variable and `0` elsewhere. -/
theorem single_recip_mem_nonpositive :
    AddMonoidAlgebra.single (Finsupp.single (0 : Fin 1) (-1 : ℤ)) (1 : R) ∈ nonpositive R 1 := by
  classical
  intro g hg i
  have hg' : g = Finsupp.single (0 : Fin 1) (-1 : ℤ) := by
    simpa using Finsupp.support_single_subset hg
  rw [hg', Finsupp.single_apply]
  split_ifs with h
  · norm_num
  · rfl

/-- **The whole image of `ofRecip` is nonpositive.** `ofRecip p` is an `aeval` at `z^{-1}`, hence
lies in `Algebra.adjoin R {z^{-1}}`, and that subalgebra is inside the nonpositive one because
`z^{-1}` is. -/
theorem ofRecip_mem_nonpositive (p : Polynomial R) : ofRecip R p ∈ nonpositive R 1 :=
  Algebra.adjoin_le (Set.singleton_subset_iff.2 single_recip_mem_nonpositive)
    (Polynomial.aeval_mem_adjoin_singleton (p := p) R _)

end HJO.Laurent

namespace HJO.Sym

open HJO.Bglx

variable {K : Type*} [Field K]

/-- The reciprocal variable of `HJO.Laurent.ofRecip` is BGLX's letter `z_1^{-1}`: the two spellings
of `z^{-1}` over `Λ` are the same monomial, so no second notion of the reciprocal variable is
introduced here. -/
theorem ofRecip_X_eq_recipVar :
    HJO.Laurent.ofRecip (Lambda K) Polynomial.X = recipVar K (0 : Fin 1) := by
  rw [HJO.Laurent.ofRecip_X, recipVar]

/-- **The creation displacement with its values in the Laurent ring**, which is the target
`Λ[z, z^{-1}]` that `HJO.Sym.plethCreateQ` names: `HJO.Sym.plethCreateQ` followed by the
reading `w ↦ z^{-1}` of `HJO.Laurent.ofRecip`. -/
noncomputable def plethCreateQLaurent (q : K) (F : Lambda K) : LaurentLambda K 1 :=
  HJO.Laurent.ofRecip (Lambda K) (plethCreateQ q F)

/-- **The displacement on a generator, inside the Laurent ring**: `p_k - (1 - q^k)z^{-k}`, the
defining clause of `HJO.Sym.plethCreateQ`. The hypothesis `k ≥ 1` is part of the definition and is
not removable, `p_0` being the generator `p_1`. -/
theorem plethCreateQLaurent_powerSum (q : K) {k : ℕ} (hk : 1 ≤ k) :
    plethCreateQLaurent q (powerSum K k) =
      AddMonoidAlgebra.single 0 (powerSum K k) -
        laurentConst K 1 (1 - q ^ k) * recipVar K (0 : Fin 1) ^ k := by
  rw [plethCreateQLaurent, plethCreateQ_powerSum q hk, map_sub, HJO.Laurent.ofRecip_C, map_mul,
    HJO.Laurent.ofRecip_C, map_pow, ofRecip_X_eq_recipVar, laurentConst_apply]

/-- The same value with the Laurent monomial written out: the coefficient `1 - q^k` sits on the
exponent `-k`, and the only other exponent occurring is `0`. This is the value check against the
formula as usually written -- the scalar subtracted from `p_k` is `1 - q^k` and not `(1 - q)^k`. -/
theorem plethCreateQLaurent_powerSum_single (q : K) {k : ℕ} (hk : 1 ≤ k) :
    plethCreateQLaurent q (powerSum K k) =
      AddMonoidAlgebra.single 0 (powerSum K k) -
        AddMonoidAlgebra.single (Finsupp.single (0 : Fin 1) (-(k : ℤ)))
          (MvPolynomial.C (1 - q ^ k)) := by
  rw [plethCreateQLaurent_powerSum q hk, recipVar_pow, laurentConst_apply,
    AddMonoidAlgebra.single_mul_single, zero_add, mul_one]

/-- **The displacement has no positive power of `z`.** For every
`F ∈ Λ`, `qs(F)` lies in the nonpositive subalgebra of `Λ[z, z^{-1}]` supplied by
`HJO.Laurent.nonpositive` at `R = Λ` and `n = 1`.

Unconditional in `q`: the exponents occurring in the image of a generator are `0` and `-k`. -/
@[hjo "lem_ght3_qshift_image"]
theorem plethCreateQLaurent_mem_nonpositive (q : K) (F : Lambda K) :
    plethCreateQLaurent q F ∈ HJO.Laurent.nonpositive (Lambda K) 1 :=
  HJO.Laurent.ofRecip_mem_nonpositive _

end HJO.Sym

end
