/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import Mathlib.Algebra.Group.Subgroup.Pointwise
public import Mathlib.GroupTheory.Perm.ClosureSwap
public import Mathlib.Order.Interval.Set.Defs
public meta import HJO.Attr

/-! # Adjacent transpositions generate the finitary permutations of an up-set

Fix a threshold `j₀ : ℕ` and consider the permutations of `ℕ` that fix every index below `j₀` and
move only finitely many indices — the finitary permutations of the up-set `{j | j ≥ j₀}`, extended
by the identity. Each interchange `Equiv.swap m (m + 1)` of two neighbours with `m ≥ j₀` is such a
permutation, and this file proves that every such permutation is a product of finitely many of
them, that is, lies in the *submonoid* they generate, so that no inverse is ever taken.

The route is Mathlib's orbit criterion `Equiv.Perm.mem_closure_isSwap`: the generating set consists
of transpositions and is closed under inversion, each generator being an involution, so
`Subgroup.closure_toSubmonoid` identifies the submonoid with the subgroup; membership then reduces
to finiteness of the support together with `ρ x` lying in the orbit of `x`, and `Set.Ici j₀` is a
single orbit because `Equiv.swap m (m + 1)` links `m` to `m + 1` for every `m ≥ j₀`.

## Main results

* `Equiv.Perm.mem_mclosure_swap_succ`: a permutation of `ℕ` fixing every index below `j₀` and all
  but finitely many indices lies in the submonoid generated by the transpositions
  `Equiv.swap m (m + 1)` with `m ≥ j₀`.
-/

@[expose] public section

open MulAction

namespace Equiv.Perm

/-- Every member of the generating set `{Equiv.swap m (m + 1) | m ≥ j₀}` is a transposition: it
interchanges the two distinct indices `m` and `m + 1` and fixes every other index. -/
theorem isSwap_of_mem_image_swap_succ {j₀ : ℕ} {f : Equiv.Perm ℕ}
    (hf : f ∈ (fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀) : f.IsSwap := by
  obtain ⟨m, -, rfl⟩ := hf
  exact ⟨m, m + 1, (Nat.succ_ne_self m).symm, rfl⟩

/-- The set of adjacent transpositions above `j₀` is unchanged by adjoining the inverses of its
members, each generator being an involution. This is the hypothesis of
`Subgroup.closure_toSubmonoid` in the present situation. -/
theorem union_inv_image_swap_succ (j₀ : ℕ) :
    (fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀ ∪
        ((fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀)⁻¹ =
      (fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀ := by
  refine Set.union_eq_self_of_subset_right ?_
  rintro f hf
  rw [Set.mem_inv] at hf
  obtain ⟨m, hm, hfm⟩ := hf
  refine ⟨m, hm, ?_⟩
  have := congrArg (·⁻¹) hfm
  simpa using this

/-- The submonoid generated by the adjacent transpositions above `j₀` is the underlying submonoid
of the subgroup they generate: the generating set is closed under inversion, so the `S ∪ S⁻¹` of
`Subgroup.closure_toSubmonoid` collapses to `S`. -/
theorem mclosure_swap_succ_eq_toSubmonoid (j₀ : ℕ) :
    Submonoid.closure ((fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀) =
      (Subgroup.closure ((fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀)).toSubmonoid := by
  rw [Subgroup.closure_toSubmonoid, union_inv_image_swap_succ]

/-- Each adjacent transposition above `j₀` lies in the group generated by all of them. -/
theorem swap_succ_mem_closure {j₀ m : ℕ} (hm : j₀ ≤ m) :
    Equiv.swap m (m + 1) ∈
      Subgroup.closure ((fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀) :=
  Subgroup.subset_closure (Set.mem_image_of_mem _ hm)

/-- Every index `n ≥ j₀` lies in the orbit of `j₀` under the group generated by the adjacent
transpositions above `j₀`: the generator `Equiv.swap n (n + 1)` carries `n` to `n + 1`, so an
induction starting at `j₀` walks `j₀` up to `n`. -/
theorem mem_orbit_closure_swap_succ {j₀ n : ℕ} (hn : j₀ ≤ n) :
    n ∈ orbit (Subgroup.closure ((fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀)) j₀ := by
  induction n, hn using Nat.le_induction with
  | base => exact mem_orbit_self _
  | succ n hn ih =>
    obtain ⟨g, hg⟩ := ih
    have hg' : (g : Equiv.Perm ℕ) j₀ = n := hg
    refine ⟨⟨Equiv.swap n (n + 1), swap_succ_mem_closure hn⟩ * g, ?_⟩
    change Equiv.swap n (n + 1) ((g : Equiv.Perm ℕ) j₀) = n + 1
    rw [hg', Equiv.swap_apply_left]

/-- A permutation of `ℕ` fixing every index below `j₀` maps every index `≥ j₀` again to an index
`≥ j₀`: were `ρ x < j₀`, then `ρ` would fix `ρ x`, and injectivity would force `ρ x = x < j₀`. -/
theorem le_apply_of_forall_lt_apply_eq {j₀ : ℕ} {ρ : Equiv.Perm ℕ} (hfix : ∀ j < j₀, ρ j = j)
    {x : ℕ} (hx : j₀ ≤ x) : j₀ ≤ ρ x := by
  by_contra h
  have h1 : ρ (ρ x) = ρ x := hfix (ρ x) (Nat.not_le.mp h)
  have h2 : ρ x = x := ρ.injective h1
  omega

/-- **Adjacent transpositions generate the finitary permutations of an up-set.** A permutation `ρ`
of `ℕ` that fixes every index below `j₀` and all but finitely many indices — that is, a permutation
of `{j | j ≥ j₀}` moving only finitely many indices — is a composite of finitely many
transpositions `Equiv.swap m (m + 1)` with `m ≥ j₀`, each interchanging two adjacent indices and
fixing every other one. -/
@[hjo "lem_cm_adjacent_generate"]
theorem mem_mclosure_swap_succ {j₀ : ℕ} {ρ : Equiv.Perm ℕ} (hfix : ∀ j < j₀, ρ j = j)
    (hsupport : (fixedBy ℕ ρ)ᶜ.Finite) :
    ρ ∈ Submonoid.closure ((fun m => Equiv.swap m (m + 1)) '' Set.Ici j₀) := by
  rw [mclosure_swap_succ_eq_toSubmonoid, Subgroup.mem_toSubmonoid,
    mem_closure_isSwap fun _ hf => isSwap_of_mem_image_swap_succ hf]
  refine ⟨hsupport, fun x => ?_⟩
  by_cases hx : x < j₀
  · rw [hfix x hx]
    exact mem_orbit_self _
  · have hx' : j₀ ≤ x := Nat.not_lt.mp hx
    rw [orbit_eq_iff.mpr (mem_orbit_closure_swap_succ hx')]
    exact mem_orbit_closure_swap_succ (le_apply_of_forall_lt_apply_eq hfix hx')

end Equiv.Perm
