/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.SweepModule
public meta import HJO.Attr

/-! # The alphabet-shift operator `Γ₊`

`HJO.Sweep.alphabetShift`: for an element `Z` of `V_k` that is a `𝕜`-linear combination of monomials
in the `y`-variables, `Γ₊(Z)` is the endomorphism `F ↦ F[X + Z]` of `V_k`, adding the virtual
alphabet `Z` to `X` only.

## The shift is parameterised by the letters of `Z`, not by the element `Z`

**`F[X + Z]` is not a function of the element `Z`**, and this is the one thing the usual
phrasing hides. Adding a virtual alphabet is prescribed on the power sums, `p_r ↦ p_r + p_r[Z]`, and
`p_r[Z]` depends on how `Z` is *presented* as a combination of letters and not on the value of the
sum: the element `2y_1` read as the two-letter alphabet `y_1 + y_1` gives `p_r[Z] = 2y_1^r`, but
read as the one-letter alphabet `2·y_1` it gives `2^ry_1^r`, and these differ at every `r ≥ 2`. The
same ambiguity is what `HJO.Sweep.qshift`'s docstring records for its own letter: `(q-1)y_i` is the
*virtual* alphabet `qy_i - y_i`, whose `r`-th power sum is `(q^r-1)y_i^r` and not `(q-1)^ry_i^r`;
two statements of the layer are false under the other reading.

So `HJO.Sweep.alphabetShift` takes the datum that actually determines the map: the family
`P : ℕ → V_*` of power sums of the virtual alphabet, `P r = p_r[Z]`. For the `Z`, a
`𝕜`-combination `∑_t ε_t c_tw_t` of monomials with signs, that family is
`P r = ∑_t ε_t c_t^rw_t^r`; the single-letter case used later is
`HJO.Sweep.letterPowerSums`. The datum is explicit rather than papered over: one must
say which letters `Z` is made of.

That the reading is the right one is pinned by `HJO.Sweep.qshift_eq_alphabetShift`: the
`τ_{k,i}` of `HJO.Sweep.qshift` *is* `Γ₊` at the letter family of `(q-1)y_i`, and the identification
holds by definition, not up to a rewrite.

## The inverse shift

`HJO.Sweep.alphabetShift_bopExt` uses that `Γ₊(-Z)` is inverse to `Γ₊(Z)` — "the composite sends `F`
to `F[X + w - w] = F` in either order". That is `HJO.Sweep.alphabetShift_neg_alphabetShift`, and it
needs each `P r` to be free of the alphabet `X`, i.e. to lie in the `𝕜`-subalgebra generated by the
`y`-variables (`HJO.Sweep.auxSubalg`): otherwise the outer shift moves the inner shift's own letters
and the two do not cancel. The phrase "a `𝕜`-linear combination of monomials in the
`y`-variables" is exactly that hypothesis, and it is load-bearing.

## Main definitions

* `HJO.Sweep.auxSubalg`: the `𝕜`-subalgebra of `V_*` generated by the `y`-variables, the elements
  usually called combinations of monomials in the `y`-variables.
* `HJO.Sweep.alphabetShift`: `Γ₊`, given the power sums of the virtual alphabet.
* `HJO.Sweep.letterPowerSums`: the power sums `p_r ↦ c^rw^r` of a single letter `cw`.

## Main results

* `HJO.Sweep.alphabetShift_powerSum`: the defining formula `p_r ↦ p_r + P r`.
* `HJO.Sweep.alphabetShift_auxVar_apply`: `Γ₊` moves the alphabet and nothing else.
* `HJO.Sweep.alphabetShift_neg_alphabetShift`, `HJO.Sweep.alphabetShift_alphabetShift_neg`:
  `Γ₊(-Z)` and `Γ₊(Z)` are mutually inverse.
* `HJO.Sweep.qshift_eq_alphabetShift`: `τ_{k,i}` is `Γ₊` at the letter `(q-1)y_i`.

## References

A. Mellit, *Toric braids and `(m,n)`-parking functions*, §3.6. -/

@[expose] public section

namespace HJO.Sweep

section Field

variable {L : Type*} [Field L]

/-- The `𝕜`-subalgebra of the total space generated by the auxiliary variables: the phrase
"`𝕜`-linear combination of monomials in the `y`-variables". An element of it involves no letter of
the alphabet `X`, which is what makes `HJO.Sweep.alphabetShift` fix it. -/
noncomputable def auxSubalg (L : Type*) [CommRing L] : Subalgebra L (Total L) :=
  Algebra.adjoin L (Set.range (MvPolynomial.X : ℕ → Total L))

/-- Each auxiliary variable lies in the subalgebra they generate. -/
theorem auxVar_mem_auxSubalg (i : ℕ) : (auxVar i : Total L) ∈ auxSubalg L :=
  Algebra.subset_adjoin ⟨i - 1, rfl⟩

/-- **The power sums of a single letter `cw`**: `p_r[cw] = c^rw^r`. This is the family
`HJO.Sweep.alphabetShift` reads for the one-monomial alphabets; the scalar `c` is a
letter of the base, so the `r`-th power sum carries `c^r` and not `c`. -/
noncomputable def letterPowerSums (c : L) (w : Total L) : ℕ → Total L := fun r => scal c ^ r * w ^ r

/-- A single letter built from an auxiliary monomial stays in the subalgebra generated by the
`y`-variables, which is the hypothesis `HJO.Sweep.alphabetShift_neg_alphabetShift` reads. -/
theorem letterPowerSums_mem_auxSubalg (c : L) {w : Total L} (hw : w ∈ auxSubalg L) (r : ℕ) :
    letterPowerSums c w r ∈ auxSubalg L :=
  mul_mem (pow_mem ((auxSubalg L).algebraMap_mem c) r) (pow_mem hw r)

/-- **The alphabet-shift operator `Γ₊`**, `HJO.Sweep.alphabetShift`: the `𝕜`-algebra
endomorphism of the total space with `Γ₊(p_r) = p_r + P r` for every `r ≥ 1` and `Γ₊(y_j) = y_j`,
which is the substitution `F ↦ F[X + Z]` for the virtual alphabet `Z` whose `r`-th power sum is
`P r`.

The argument is the *family of power sums* of `Z` and not the element `Z`, for the reason recorded
in the module docstring: `F[X + Z]` is not determined by the value of the sum `Z`. On the total
space the definition does not depend on `k`, exactly as `HJO.Sweep.qshift`'s does not: the
endomorphism of `V_k` is the restriction of this one. -/
@[hjo "def_cm_gamma_plus"]
noncomputable def alphabetShift (P : ℕ → Total L) : Total L →ₐ[L] Total L :=
  MvPolynomial.aevalTower
    (MvPolynomial.aeval fun j : ℕ => (MvPolynomial.C (MvPolynomial.X j) + P (j + 1) : Total L))
    MvPolynomial.X

/-- **The defining property of `Γ₊`**: it adds `P r` to the power sum `p_r`, for every `r ≥ 1`. -/
@[hjo "def_cm_gamma_plus"]
theorem alphabetShift_powerSum (P : ℕ → Total L) (r : ℕ) :
    alphabetShift P (MvPolynomial.C (Sym.powerSum L (r + 1)))
      = MvPolynomial.C (Sym.powerSum L (r + 1)) + P (r + 1) := by
  simp [alphabetShift, Sym.powerSum]

/-- **`Γ₊` fixes every auxiliary variable**: it adds the alphabet to `X` only, which is the clause
"the addition of the virtual alphabet `Z` to `X` only" of `HJO.Sweep.alphabetShift`. -/
@[hjo "def_cm_gamma_plus", simp]
theorem alphabetShift_X (P : ℕ → Total L) (j : ℕ) :
    alphabetShift P (MvPolynomial.X j : Total L) = MvPolynomial.X j := by
  simp [alphabetShift]

@[simp]
theorem alphabetShift_auxVar_apply (P : ℕ → Total L) (j : ℕ) :
    alphabetShift P (auxVar j : Total L) = auxVar j :=
  alphabetShift_X P (j - 1)

/-- `Γ₊` fixes a scalar of `𝕜`, being a `𝕜`-algebra map. -/
@[simp]
theorem alphabetShift_scal (P : ℕ → Total L) (x : L) :
    alphabetShift P (scal x : Total L) = scal x := by
  rw [scal_eq_algebraMap, AlgHom.commutes]

/-- **`Γ₊` fixes everything free of the alphabet.** An element of the subalgebra generated by the
`y`-variables is untouched, since `Γ₊` fixes the generators and the scalars. This is what makes the
two shifts of a monomial alphabet cancel. -/
theorem alphabetShift_of_mem_auxSubalg (P : ℕ → Total L) {Z : Total L} (hZ : Z ∈ auxSubalg L) :
    alphabetShift P Z = Z := by
  refine Algebra.adjoin_induction (p := fun Z _ => alphabetShift P Z = Z) ?_ ?_ ?_ ?_ hZ
  · rintro _ ⟨j, rfl⟩
    exact alphabetShift_X P j
  · intro x
    rw [AlgHom.commutes]
  · intro x y _ _ hx hy
    rw [map_add, hx, hy]
  · intro x y _ _ hx hy
    rw [map_mul, hx, hy]

/-- **`τ_{k,i}` is `Γ₊` at the letter `(q-1)y_i`**, and by definition rather than up to a rewrite.
This is the faithfulness check on the reading of `HJO.Sweep.alphabetShift`: the virtual alphabet
`(q-1)y_i` has `p_r ↦ (q^r-1)y_i^r`, which is the family below, and the substitution `τ_{k,i}` of
`HJO.Sweep.qshift` is `Γ₊` of it. -/
theorem qshift_eq_alphabetShift (q : L) (i : ℕ) (F : Total L) :
    qshift q i F = alphabetShift (fun r => scal (q ^ r - 1) * auxVar i ^ r) F := rfl

/-- **`Γ₊(-Z)` is a left inverse of `Γ₊(Z)`**, the "the composite sends `F` to
`F[X + Z - Z] = F`". Both composites are `𝕜`-algebra endomorphisms of
`Total L = MvPolynomial ℕ Λ`, so `MvPolynomial.algHom_ext'` reduces the claim to the auxiliary
variables, which both shifts fix, and to the power sums, where one adds `P r` and the other
subtracts it.

The hypothesis that each `P r` is free of the alphabet is load-bearing: without it the outer shift
moves the inner shift's own letters and the cancellation fails. -/
theorem alphabetShift_neg_alphabetShift {P : ℕ → Total L} (hP : ∀ r, P r ∈ auxSubalg L)
    (F : Total L) : alphabetShift (fun r => -P r) (alphabetShift P F) = F := by
  have key : (alphabetShift fun r => -P r).comp (alphabetShift P) = AlgHom.id L (Total L) := by
    refine MvPolynomial.algHom_ext' ?_ fun n => ?_
    · refine MvPolynomial.algHom_ext fun r => ?_
      have hC : (algebraMap (Sym.Lambda L) (Total L)) (MvPolynomial.X r)
          = MvPolynomial.C (Sym.powerSum L (r + 1)) := by
        simp [Sym.powerSum]
      simp only [AlgHom.comp_apply, IsScalarTower.coe_toAlgHom', hC, alphabetShift_powerSum,
        map_add, alphabetShift_of_mem_auxSubalg _ (hP (r + 1)), AlgHom.id_apply]
      ring
    · simp only [AlgHom.comp_apply, alphabetShift_X, AlgHom.id_apply]
  exact congrArg (fun f : Total L →ₐ[L] Total L => f F) key

/-- **`Γ₊(-Z)` is a right inverse of `Γ₊(Z)`**, so the two are mutually inverse automorphisms of the
total space. This is the other half of the "in either order". -/
theorem alphabetShift_alphabetShift_neg {P : ℕ → Total L} (hP : ∀ r, P r ∈ auxSubalg L)
    (F : Total L) : alphabetShift P (alphabetShift (fun r => -P r) F) = F := by
  have hneg : ∀ r, (fun s => -P s) r ∈ auxSubalg L := fun r => neg_mem (hP r)
  have h := alphabetShift_neg_alphabetShift hneg F
  simpa only [neg_neg] using h

/-- **`Γ₊(Z)` is injective**, off the inverse above. -/
theorem alphabetShift_injective {P : ℕ → Total L} (hP : ∀ r, P r ∈ auxSubalg L) :
    Function.Injective (alphabetShift P : Total L →ₐ[L] Total L) := fun F G h => by
  rw [← alphabetShift_neg_alphabetShift hP F, h, alphabetShift_neg_alphabetShift hP]

end Field

end HJO.Sweep
