/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.CMStructure.CmCommutator
public meta import HJO.Attr

/-! # Two operators that agree on the powers of the last variable agree on `V_k`

The reduction the starred relations are proved by. The proofs of
`HJO.Sweep.dminusCM_starCommCM_braidInv`, `HJO.Sweep.braidInv_starCommCM_dplusStar` and
`HJO.Sweep.starCommCM_cmDPlus` each say, of an operator `A` built from `d_-`, `d^*_+` and the braid
operators, that

* `A(f ∗_0 G) = f ∗_1 A(G)` — it intertwines the twisted multiplications
  (`HJO.Sweep.dplusStar_twistedActionMult`, `HJO.Sweep.dminusCM_twistedActionMult`), and
* `Ay_i = y_{i+1}A`, or `y_{i+2}A` for a composite of two raisings — it shifts the corner elements
  (`HJO.Sweep.dplusStar_braidInv`),

and conclude "so it is enough to evaluate `A` on the monomials `y_k^a`". That inference is
`HJO.Sweep.eq_of_agree_auxVar_pow`, stated as a lemma of its own and for two operators rather than
for one operator and zero, which is the form the relations are used in.

## Main results

* `HJO.Sweep.eq_of_agree_auxVar_pow`: two `𝕜`-linear endomorphisms of the total space that are
  linear over the twisting homomorphism in the sense above, shift the corner elements `y_1, …, y_k`,
  and agree on every power of `y_{k+1}`, agree on all of `V_{k+1}`.
* `HJO.Sweep.eq_of_agree_auxVar_pow_two`: the same with the last TWO variables free — agreement on
  the monomials `y_{k+1}^ay_{k+2}^b` propagates to `V_{k+2}`. This is the shape
  `HJO.Sweep.dminusCM_starCommCM_braidInv` needs, its evaluation being on `y_{k-1}^ay_k^b`.
* `HJO.Sweep.eq_of_agree_piece_of_base` and `HJO.Sweep.eq_of_agree_monomial_of_base`: both of the
  above with the base case left open — the corner shifts reach `y_1, …, y_k`, and whatever happens
  on the monomials in the remaining variables is the hypothesis.

## Implementation notes

**Why the twisted multiplication and not ordinary multiplication by `Λ`.** None of the operators is
`Λ`-linear — `d_-` extracts coefficients and `d^*_+` shifts the alphabet — so the hypothesis cannot
be `Φ(fG) = fΦ(G)`. What is true is linearity over the image of `tw_k`
(`HJO.Sweep.twist`), which is the `m = 0` twisted multiplication
(`HJO.Sweep.twistedMult_C`, `HJO.Sweep.twistedActionMult_zero`); and that suffices because
`tw_k` is an alphabet shift, hence the restriction to `V_k` of an automorphism of the total space
preserving `V_k` (`HJO.Sweep.alphabetShift_mem_piece`,
`HJO.Sweep.alphabetShift_alphabetShift_neg`), so `V_k` is generated by `tw_k(Λ)` and the
`y`-monomials. This is the same device as the proof of
`HJO.Sweep.dminusCM_cmDPlus_sub_cmDPlus_dminusCM`, where it is run inline for one operator; here it
is factored out.

**The image multiplication is left free.** The hypothesis is `Φ(tw_{k+1}(c)G) = T(c)Φ(G)` for an
arbitrary family `T : Λ → V_*`, rather than naming `∗_1`: its uses produce different target
multiplications — a composite of two starred raisings lands at `∗_2`, not `∗_1` — and nothing in the
argument uses what `T` is, only that `Φ` and `Ψ` share it.

**The shifts peel a whole variable at a time.** `Φ(y_i^eG) = S(i)^eΦ(G)` follows from the
hypothesis at `i` by induction on `e`, so a `y`-monomial is reduced by erasing one variable of its
support at a time and the induction is on the CARDINALITY of the support: each step removes an index
`j ≠ k` outright, and the base case is a support inside `{k}`, i.e. a power of `y_{k+1}` alone. No
truncated subtraction of exponents occurs, and the statement is written at `k + 1` throughout so
that `y_{k+1} = X_k` needs none either.

**The range of the shifts.** `1 ≤ i ≤ k` on `V_{k+1}`: the LAST variable is the one that is not
shifted, and it is the one the operators are evaluated on. An operator shifting `y_{k+1}` as well
would be determined by its value at `1`, which is false of the operators here.

## References

The inference appears inside the proofs of `HJO.Sweep.dminusCM_starCommCM_braidInv`,
`HJO.Sweep.braidInv_starCommCM_dplusStar` and `HJO.Sweep.starCommCM_cmDPlus`, each using
`HJO.Sweep.dplusStar_twistedActionMult`, `HJO.Sweep.dminusCM_twistedActionMult` and
`HJO.Sweep.dplusStar_braidInv` for the two hypotheses, and `HJO.Sweep.exists_basis_vstar_prod_bop`
for the spanning principle that licenses it. Transcribing E. Carlsson and A. Mellit, *A proof of the
shuffle conjecture*, §5.
-/

@[expose] public section

namespace HJO.Sweep

section Reduction

variable {L : Type*} [Field L]

/-- **A corner shift peels a whole power.** From `Φ(y_iG) = SΦ(G)` for every `G`, by induction on
the exponent: `Φ(y_i^eG) = S^eΦ(G)`. The multiplier `S` is free — its uses shift the index by
one or by two according to how many raisings the operator is built from. -/
theorem map_auxVar_pow_mul_of_map_auxVar_mul {Φ : Total L →ₗ[L] Total L} {i : ℕ} {S : Total L}
    (hΦ : ∀ G : Total L, Φ ((auxVar i : Total L) * G) = S * Φ G) (e : ℕ)
    (G : Total L) : Φ ((auxVar i : Total L) ^ e * G) = S ^ e * Φ G := by
  induction e with
  | zero => simp
  | succ e ih =>
    rw [pow_succ', show (auxVar i : Total L) * auxVar i ^ e * G
        = auxVar i * (auxVar i ^ e * G) from by ring, hΦ, ih, pow_succ']
    ring

/-- **The peel, with the base case left open.** Two operators that shift the corners with the same
multipliers agree on a `y`-monomial of `V_K` as soon as they agree on the monomials involving only
the variables `y_{k+1}, …, y_K` — the ones the shifts cannot reach. An index `j` of the support with
`j < k` is peeled by the hypothesis at `i = j + 1`, which erases it, so the induction is on the
CARDINALITY of the support and the base case is a support inside `[k, K)`. -/
theorem eq_of_agree_monomial_of_base {k K : ℕ} {Φ Ψ : Total L →ₗ[L] Total L} {S : ℕ → Total L}
    (hΦaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Φ ((auxVar i : Total L) * G) = S i * Φ G)
    (hΨaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Ψ ((auxVar i : Total L) * G) = S i * Ψ G)
    (hbase : ∀ e : ℕ →₀ ℕ, (∀ j ∈ e.support, k ≤ j ∧ j < K) →
      Φ (MvPolynomial.monomial e (1 : Sym.Lambda L))
        = Ψ (MvPolynomial.monomial e (1 : Sym.Lambda L)))
    {d : ℕ →₀ ℕ} (hd : ∀ j ∈ d.support, j < K) :
    Φ (MvPolynomial.monomial d (1 : Sym.Lambda L))
      = Ψ (MvPolynomial.monomial d (1 : Sym.Lambda L)) := by
  have key : ∀ n : ℕ, ∀ e : ℕ →₀ ℕ, e.support.card ≤ n → (∀ j ∈ e.support, j < K) →
      Φ (MvPolynomial.monomial e (1 : Sym.Lambda L))
        = Ψ (MvPolynomial.monomial e (1 : Sym.Lambda L)) := by
    intro n
    induction n with
    | zero =>
      intro e he heK
      exact hbase e (by simp [Finset.card_eq_zero.1 (Nat.le_zero.1 he)])
    | succ n ih =>
      intro e he heK
      by_cases hsub : ∀ j ∈ e.support, k ≤ j
      · exact hbase e fun j hj => ⟨hsub j hj, heK j hj⟩
      obtain ⟨j, hj, hjlt⟩ : ∃ j ∈ e.support, j < k := by
        by_contra h
        push Not at h
        exact hsub fun j hj => h j hj
      have hsplit : (MvPolynomial.monomial e (1 : Sym.Lambda L) : Total L)
          = (auxVar (j + 1) : Total L) ^ e j
            * MvPolynomial.monomial (Finsupp.erase j e) (1 : Sym.Lambda L) := by
        rw [show (auxVar (j + 1) : Total L) = MvPolynomial.X j from by
            rw [auxVar, Nat.add_sub_cancel], MvPolynomial.X_pow_eq_monomial,
          MvPolynomial.monomial_mul, one_mul, Finsupp.single_add_erase]
      have hcard : (Finsupp.erase j e).support.card ≤ n := by
        rw [Finsupp.support_erase]
        have := Finset.card_erase_of_mem hj
        omega
      have herase : ∀ i ∈ (Finsupp.erase j e).support, i < K := by
        intro i hi
        rw [Finsupp.support_erase] at hi
        exact heK i (Finset.mem_of_mem_erase hi)
      rw [hsplit,
        map_auxVar_pow_mul_of_map_auxVar_mul (hΦaux (j + 1) (Nat.succ_le_succ (Nat.zero_le j))
          (Nat.succ_le_of_lt hjlt)),
        map_auxVar_pow_mul_of_map_auxVar_mul (hΨaux (j + 1) (Nat.succ_le_succ (Nat.zero_le j))
          (Nat.succ_le_of_lt hjlt)),
        ih _ hcard herase]
  exact key d.support.card d le_rfl hd

/-- **The reduction, with the base case left open.** Two `𝕜`-linear endomorphisms of the total space
that are linear over the twisting homomorphism `tw_K` with one and the same image multiplication and
shift the corners `y_1, …, y_k` with one and the same multipliers agree on all of `V_K` as soon as
they agree on the `y`-monomials in the remaining variables `y_{k+1}, …, y_K`.

`tw_K` is an alphabet shift, hence an automorphism of the total space preserving `V_K`
(`HJO.Sweep.alphabetShift_mem_piece`, `HJO.Sweep.alphabetShift_alphabetShift_neg`), so `V_K` is
spanned over `𝕜` by the products `tw_K(c)y^d`: the first hypothesis strips `tw_K(c)` and
`HJO.Sweep.eq_of_agree_monomial_of_base` handles the monomial. -/
theorem eq_of_agree_piece_of_base (q u : L) {k K : ℕ} {Φ Ψ : Total L →ₗ[L] Total L}
    {T : Sym.Lambda L → Total L} {S : ℕ → Total L}
    (hΦmul : ∀ (c : Sym.Lambda L) (G : Total L), Φ (twist L q K c * G) = T c * Φ G)
    (hΨmul : ∀ (c : Sym.Lambda L) (G : Total L), Ψ (twist L q K c * G) = T c * Ψ G)
    (hΦaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Φ ((auxVar i : Total L) * G) = S i * Φ G)
    (hΨaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Ψ ((auxVar i : Total L) * G) = S i * Ψ G)
    (hbase : ∀ e : ℕ →₀ ℕ, (∀ j ∈ e.support, k ≤ j ∧ j < K) →
      Φ (MvPolynomial.monomial e (1 : Sym.Lambda L))
        = Ψ (MvPolynomial.monomial e (1 : Sym.Lambda L)))
    {F : Total L} (hF : F ∈ piece L K) : Φ F = Ψ F := by
  have hPaux : ∀ r, twistPowerSums q u 0 K r ∈ auxSubalg L :=
    fun r => twistPowerSums_mem_auxSubalg q u 0 K r
  have hPpiece : ∀ r, -twistPowerSums q u 0 K r ∈ piece L K :=
    fun r => neg_mem (twistPowerSums_mem_piece q u (Nat.zero_le _) r)
  obtain ⟨G, hGmem, hGF⟩ : ∃ G : Total L, G ∈ piece L K ∧
      alphabetShift (twistPowerSums q u 0 K) G = F :=
    ⟨alphabetShift (fun r => -twistPowerSums q u 0 K r) F,
      alphabetShift_mem_piece hPpiece hF, alphabetShift_alphabetShift_neg hPaux F⟩
  have hsub : ↑G.vars ⊆ Set.Iio K := by
    have h := hGmem
    rw [piece, MvPolynomial.mem_supported] at h
    exact h
  have hdk : ∀ d ∈ G.support, ∀ j ∈ d.support, j < K := fun d hd j hj =>
    hsub ((MvPolynomial.mem_vars_iff_mem_support j).2 ⟨d, hd, hj⟩)
  have hexp : F = ∑ d ∈ G.support,
      twist L q K (MvPolynomial.coeff d G) * MvPolynomial.monomial d 1 := by
    rw [← hGF]
    conv_lhs => rw [G.as_sum]
    rw [map_sum]
    refine Finset.sum_congr rfl fun d _ => ?_
    rw [show (MvPolynomial.monomial d (MvPolynomial.coeff d G) : Total L)
        = MvPolynomial.C (MvPolynomial.coeff d G) * MvPolynomial.monomial d 1 from by
      rw [MvPolynomial.C_mul_monomial, mul_one], map_mul,
      alphabetShift_of_mem_auxSubalg _ (monomial_one_mem_auxSubalg d)]
    congr 1
    exact twistedMult_C q u K (MvPolynomial.coeff d G)
  rw [hexp, map_sum, map_sum]
  refine Finset.sum_congr rfl fun d hd => ?_
  rw [hΦmul, hΨmul, eq_of_agree_monomial_of_base hΦaux hΨaux hbase (hdk d hd)]

/-- **Two operators shifting the corners and agreeing on the powers of `y_{k+1}` agree on every
`y`-monomial of `V_{k+1}`.** `HJO.Sweep.eq_of_agree_monomial_of_base` at `K = k + 1`, where the base
case is a support inside `{k}` — a power of `y_{k+1}` alone. -/
theorem eq_of_agree_auxVar_pow_monomial {k : ℕ} {Φ Ψ : Total L →ₗ[L] Total L} {S : ℕ → Total L}
    (hΦaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Φ ((auxVar i : Total L) * G) = S i * Φ G)
    (hΨaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Ψ ((auxVar i : Total L) * G) = S i * Ψ G)
    (hagree : ∀ a : ℕ,
      Φ ((auxVar (k + 1) : Total L) ^ a) = Ψ ((auxVar (k + 1) : Total L) ^ a))
    {d : ℕ →₀ ℕ} (hd : ∀ j ∈ d.support, j < k + 1) :
    Φ (MvPolynomial.monomial d (1 : Sym.Lambda L))
      = Ψ (MvPolynomial.monomial d (1 : Sym.Lambda L)) :=
  eq_of_agree_monomial_of_base hΦaux hΨaux (fun e he => by
    have hsupp : e.support ⊆ {k} :=
      fun j hj => Finset.mem_singleton.2 (by have := he j hj; omega)
    have he' : e = Finsupp.single k (e k) := Finsupp.support_subset_singleton.1 hsupp
    rw [he', show (MvPolynomial.monomial (Finsupp.single k (e k)) (1 : Sym.Lambda L) : Total L)
        = (auxVar (k + 1) : Total L) ^ e k from by
      rw [show (auxVar (k + 1) : Total L) = MvPolynomial.X k from by
        rw [auxVar, Nat.add_sub_cancel], MvPolynomial.X_pow_eq_monomial]]
    exact hagree _) hd

/-- **The reduction: agreement on the powers of `y_{k+1}` propagates to all of `V_{k+1}`.** Two
`𝕜`-linear endomorphisms `Φ`, `Ψ` of the total space which
* are linear over the twisting homomorphism with one and the same image multiplication,
  `Φ(tw_{k+1}(c)G) = T(c)Φ(G)` and `Ψ(tw_{k+1}(c)G) = T(c)Ψ(G)` for every `c ∈ Λ` and every `G`;
* shift the corner elements with one and the same multipliers, `Φ(y_iG) = S(i)Φ(G)` and
  `Ψ(y_iG) = S(i)Ψ(G)` for `1 ≤ i ≤ k` — for the relations `S(i)` is `y_{i+1}` or `y_{i+2}`
  according to how many starred raisings the operator carries;
* agree on `y_{k+1}^a` for every `a`,

agree on every `F ∈ V_{k+1}`. This is `HJO.Sweep.eq_of_agree_piece_of_base` at `K = k + 1`. -/
theorem eq_of_agree_auxVar_pow (q u : L) {k : ℕ} {Φ Ψ : Total L →ₗ[L] Total L}
    {T : Sym.Lambda L → Total L} {S : ℕ → Total L}
    (hΦmul : ∀ (c : Sym.Lambda L) (G : Total L), Φ (twist L q (k + 1) c * G) = T c * Φ G)
    (hΨmul : ∀ (c : Sym.Lambda L) (G : Total L), Ψ (twist L q (k + 1) c * G) = T c * Ψ G)
    (hΦaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Φ ((auxVar i : Total L) * G) = S i * Φ G)
    (hΨaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Ψ ((auxVar i : Total L) * G) = S i * Ψ G)
    (hagree : ∀ a : ℕ,
      Φ ((auxVar (k + 1) : Total L) ^ a) = Ψ ((auxVar (k + 1) : Total L) ^ a))
    {F : Total L} (hF : F ∈ piece L (k + 1)) : Φ F = Ψ F :=
  eq_of_agree_piece_of_base q u hΦmul hΨmul hΦaux hΨaux
    (fun _ he => eq_of_agree_auxVar_pow_monomial hΦaux hΨaux hagree
      (fun j hj => (he j hj).2)) hF

/-- **The two-variable reduction**: agreement on the monomials `y_{k+1}^ay_{k+2}^b` propagates to
all of `V_{k+2}`, for operators whose corner shifts reach only `y_1, …, y_k`. This is the shape
`HJO.Sweep.dminusCM_starCommCM_braidInv` and `HJO.Sweep.starCommCM_cmDPlus` need — there the last
TWO variables are free, the evaluation being on `y_{k-1}^ay_k^b` in the indexing — and it is
`HJO.Sweep.eq_of_agree_piece_of_base` at `K = k + 2`, where the base case is a support inside
`{k, k+1}`. -/
theorem eq_of_agree_auxVar_pow_two (q u : L) {k : ℕ} {Φ Ψ : Total L →ₗ[L] Total L}
    {T : Sym.Lambda L → Total L} {S : ℕ → Total L}
    (hΦmul : ∀ (c : Sym.Lambda L) (G : Total L), Φ (twist L q (k + 2) c * G) = T c * Φ G)
    (hΨmul : ∀ (c : Sym.Lambda L) (G : Total L), Ψ (twist L q (k + 2) c * G) = T c * Ψ G)
    (hΦaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Φ ((auxVar i : Total L) * G) = S i * Φ G)
    (hΨaux : ∀ i : ℕ, 1 ≤ i → i ≤ k → ∀ G : Total L,
      Ψ ((auxVar i : Total L) * G) = S i * Ψ G)
    (hagree : ∀ a b : ℕ,
      Φ ((auxVar (k + 1) : Total L) ^ a * (auxVar (k + 2) : Total L) ^ b)
        = Ψ ((auxVar (k + 1) : Total L) ^ a * (auxVar (k + 2) : Total L) ^ b))
    {F : Total L} (hF : F ∈ piece L (k + 2)) : Φ F = Ψ F := by
  refine eq_of_agree_piece_of_base q u hΦmul hΨmul hΦaux hΨaux (fun e he => ?_) hF
  have hsplit : (MvPolynomial.monomial e (1 : Sym.Lambda L) : Total L)
      = (auxVar (k + 1) : Total L) ^ e k * (auxVar (k + 2) : Total L) ^ e (k + 1) := by
    have hX1 : (auxVar (k + 1) : Total L) = MvPolynomial.X k := by
      rw [auxVar, Nat.add_sub_cancel]
    have hX2 : (auxVar (k + 2) : Total L) = MvPolynomial.X (k + 1) := by
      have hsub : k + 2 - 1 = k + 1 := by omega
      rw [auxVar, hsub]
    have he : e = Finsupp.single k (e k) + Finsupp.single (k + 1) (e (k + 1)) := by
      refine Finsupp.ext fun i => ?_
      by_cases h1 : i = k
      · subst h1
        rw [Finsupp.add_apply, Finsupp.single_eq_same, Finsupp.single_eq_of_ne (by omega), add_zero]
      by_cases h2 : i = k + 1
      · subst h2
        rw [Finsupp.add_apply, Finsupp.single_eq_of_ne (by omega), Finsupp.single_eq_same, zero_add]
      have h0 : e i = 0 := by
        by_contra hne
        have := he i (Finsupp.mem_support_iff.2 hne)
        omega
      rw [h0, Finsupp.add_apply, Finsupp.single_eq_of_ne (by omega),
        Finsupp.single_eq_of_ne (by omega), add_zero]
    rw [hX1, hX2, MvPolynomial.X_pow_eq_monomial, MvPolynomial.X_pow_eq_monomial,
      MvPolynomial.monomial_mul, one_mul, ← he]
  rw [hsplit]
  exact hagree _ _

end Reduction

end HJO.Sweep
