/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.CMStructure.DemazureIdentities
public import HJO.Shuffle.BraidRelations
public meta import HJO.Attr

/-! # The braid words of the interchanges and of the Demazure–Lusztig operators

On `V_k` the adjacent interchange `s_i` and the Demazure–Lusztig operator
`T_i(F) = s_i(F) + (q-1)y_i∂_i(F)` both satisfy the `S_3` braid relation at consecutive indices.
This file records what the two three-fold words *are*, rather than only that they agree.

For the interchanges the answer is a single permutation: `s_is_{i+1}s_i` and `s_{i+1}s_is_{i+1}` are
both the interchange of `y_i` and `y_{i+2}`, which is what the usual argument actually
computes and is stronger than the equality of the two composites.

The interchange is read here on `Λ ⊗_𝕜 𝕜(y_1, …, y_k)` as well as on `V_k`, because that is the ring
in which the quotient `∂_iF = (F - s_iF)/(y_{i+1}-y_i)` literally stands and in which the six-term
expansions are stated. There the one-line symmetry `s_i(∂_iF) = ∂_iF` is exactly the observation
that `s_i` changes the sign of the numerator and the sign of the denominator, so that the quotient
is unchanged.

For the operators the answer is a six-term expansion. Writing
`α = (q-1)y_i/(y_{i+1}-y_i)`, `β = (y_{i+1}-qy_i)/(y_{i+1}-y_i)`,
`γ = (q-1)y_{i+1}/(y_{i+2}-y_{i+1})` and `δ = (y_{i+2}-qy_{i+1})/(y_{i+2}-y_{i+1})`, so that
`T_i(G) = αG + βs_i(G)` and `T_{i+1}(G) = γG + δs_{i+1}(G)`, each three-fold word unfolds into a
combination of the six images of `F` under the group generated by `s_i` and `s_{i+1}`, with
coefficients rational in `y_i, y_{i+1}, y_{i+2}`. The two expansions share their last four
coefficients; comparing the first two is what the braid relation for `T_i` comes down to.

## Main definitions

* `HJO.Sweep.swapFrac`: the interchange `s_i` of `y_i` and `y_{i+1}`, read on
  `Λ ⊗_𝕜 𝕜(y_1, …, y_k)`.

## Main results

* `HJO.Sweep.swapAux_swapAux_succ_swapAux` and `HJO.Sweep.swapAux_succ_swapAux_swapAux_succ`:
  the two three-fold words of interchanges are both the interchange of `y_i` and `y_{i+2}`.
* `HJO.Sweep.toFrac_dividedDiff`: `∂_iF` is the quotient `(F - s_iF)/(y_{i+1}-y_i)` of
  `Λ ⊗_𝕜 𝕜(y_1, …, y_k)`, and `HJO.Sweep.swapFrac_toFrac_dividedDiff`: that quotient is fixed
  by `s_i`.
* `HJO.Sweep.auxVar_sub_mul_braid_braid_succ_braid` and
  `HJO.Sweep.auxVar_sub_mul_braid_succ_braid_braid_succ`: the two expansions with the common
  denominator cleared, as identities of `HJO.Sweep.Total`.
* `HJO.Sweep.toFrac_braid_braid_succ_braid` and
  `HJO.Sweep.toFrac_braid_succ_braid_braid_succ`: the same two expansions divided, in
  `HJO.Sweep.TotalFrac`, which is the shape they are usually stated in.

## Implementation notes

**The composite is named, not just compared.** The usual argument for the braid relation of the
interchanges evaluates both composites on the generators `y_1, …, y_k` and finds `y_i ↦ y_{i+2}`,
`y_{i+1} ↦ y_{i+1}` and `y_{i+2} ↦ y_i` for each. That computation proves more than the equality of
the two composites: it identifies each with the transposition of `y_i` and `y_{i+2}`, which is
`MvPolynomial.rename (Equiv.swap (i-1) (i+1))` in the internal `0`-based indexing of
`HJO.Sweep.auxVar`. The equality of the two composites is the conjunction of the two statements
below, and is also available on its own as `HJO.Sweep.swapAux_braid`.

**The symmetry of the divided difference is stated where its quotient stands.** `∂_i` is constructed
inside the polynomial ring in `HJO.Shuffle.SweepModule`, so `s_i(∂_iF) = ∂_iF` is available there as
`HJO.Sweep.swapAux_dividedDiff`, proved by cancelling `y_{i+1}-y_i`. The usual argument states and
proves it one step later, in `Λ ⊗_𝕜 𝕜(y_1, …, y_k)`, where `∂_iF` *is* a quotient and the two sign
changes are visible; that is `HJO.Sweep.swapFrac_toFrac_dividedDiff`, and it is the form the
six-term expansions live alongside. Reading `s_i` there needs no new construction beyond
`HJO.Sweep.fracLift`: `s_i` is injective, so it extends to the fraction field in exactly one way.

**The cleared expansion is the primitive, the divided one is read off it.** `HJO.Sweep.braid` takes
its divided difference inside the polynomial ring, so each three-fold word is an element of
`HJO.Sweep.Total`, and the natural identity is the one multiplied through by
`(y_{i+1}-y_i)^2(y_{i+2}-y_{i+1})(y_{i+2}-y_i)` — respectively
`(y_{i+2}-y_{i+1})^2(y_{i+1}-y_i)(y_{i+2}-y_i)` — where no denominator occurs. The usual
statement lives in `Λ ⊗ 𝕜(y_1, …, y_k)`; it is obtained here by mapping the cleared identity into
`HJO.Sweep.TotalFrac` and dividing, which is the one place the three differences have to be
invertible.

**The algebra is separated from the operators.** Each expansion is seven instances of the cleared
two-term form `(y_{i+1}-y_i)T_i(F) = (q-1)y_iF + (y_{i+1}-qy_i)s_i(F)` of
`HJO.Sweep.auxVar_sub_mul_braid`, four of them transported by `s_i` or `s_{i+1}`; with the operators
replaced by opaque atoms those seven relations become the hypotheses of
`HJO.Sweep.braid_expand_left_of_split` and `HJO.Sweep.braid_expand_right_of_split`, whose
conclusions `linear_combination` verifies by `ring`. The division is likewise abstract, in
`HJO.Sweep.braid_expand_left_of_cleared` and `HJO.Sweep.braid_expand_right_of_cleared`, which keeps
`field_simp` away from the `FractionRing` instance tower — the convention
`HJO.CMStructure.BraidScalars` already follows for the scalar identities these expansions
produce.

**The hypothesis is `1 ≤ i` and nothing else.** Each identity is usually stated for `k ≥ 3` and
`1 ≤ i ≤ k-2` in `V_k`. In the one-total-space convention of `HJO.Shuffle.SweepModule` the
three variables `y_i, y_{i+1}, y_{i+2}` live in the ambient space for every `i` and lie in `V_k`
exactly when `i + 2 ≤ k`, by `HJO.Sweep.auxVar_mem_piece`; the identities themselves do not see `k`.
What `1 ≤ i` is needed for is that the three indices name distinct variables, the convention
`y_0 = y_1` making `y_{i+1} - y_i` vanish at `i = 0`.

## References

E. Carlsson and A. Mellit, *A proof of the shuffle conjecture*, §5.
-/

@[expose] public section

namespace HJO.Sweep

/-! ### The three interchanges braid -/

section Swap

variable {L : Type*} [Field L]

/-- **`s_is_{i+1}s_i` is the interchange of `y_i` and `y_{i+2}`.** Half of the braid
relation for the interchanges, in the sharper form its proof establishes: evaluating on the
generators gives `y_i ↦ y_{i+2}`, `y_{i+1} ↦ y_{i+1}` and `y_{i+2} ↦ y_i`, which
is the transposition of `y_i` and `y_{i+2}` — written here through the internal `0`-based index of
`HJO.Sweep.auxVar`, where `y_i` is `X (i-1)` and `y_{i+2}` is `X (i+1)`.

No hypothesis on `i` is needed: at the unread index `0` the convention `y_0 = y_1` makes `s_0` the
identity, and the identity degenerates to the true statement that `s_1` interchanges `y_1` and
`y_2`. Its companion `HJO.Sweep.swapAux_succ_swapAux_swapAux_succ` does need `1 ≤ i`, the outer
interchanges cancelling there instead. -/
@[hjo "lem_cm_swap_braid"]
theorem swapAux_swapAux_succ_swapAux {i : ℕ} (F : Total L) :
    swapAux L i (swapAux L (i + 1) (swapAux L i F))
      = MvPolynomial.rename (Equiv.swap (i - 1) (i + 1)) F := by
  have hsucc : i + 1 - 1 = i := by omega
  have key : ∀ n : ℕ, Equiv.swap (i - 1) i (Equiv.swap i (i + 1) (Equiv.swap (i - 1) i n))
      = Equiv.swap (i - 1) (i + 1) n := by
    intro n
    simp only [Equiv.swap_apply_def]
    split_ifs <;> omega
  have h : ((swapAux L i).toAlgHom.comp (swapAux L (i + 1)).toAlgHom).comp (swapAux L i).toAlgHom
      = MvPolynomial.rename (Equiv.swap (i - 1) (i + 1)) := by
    refine MvPolynomial.algHom_ext fun n => ?_
    simp only [AlgHom.comp_apply, AlgEquiv.coe_toAlgHom, swapAux_X, hsucc,
      MvPolynomial.rename_X]
    rw [key]
  exact congrArg (fun f : Total L →ₐ[Sym.Lambda L] Total L => f F) h

/-- **`s_{i+1}s_is_{i+1}` is the interchange of `y_i` and `y_{i+2}`.** The other half of the
braid relation for the interchanges; together with
`HJO.Sweep.swapAux_swapAux_succ_swapAux` it says that the two three-fold words agree. -/
@[hjo "lem_cm_swap_braid"]
theorem swapAux_succ_swapAux_swapAux_succ {i : ℕ} (hi : 1 ≤ i) (F : Total L) :
    swapAux L (i + 1) (swapAux L i (swapAux L (i + 1) F))
      = MvPolynomial.rename (Equiv.swap (i - 1) (i + 1)) F := by
  have hsucc : i + 1 - 1 = i := by omega
  have key : ∀ n : ℕ, Equiv.swap i (i + 1) (Equiv.swap (i - 1) i (Equiv.swap i (i + 1) n))
      = Equiv.swap (i - 1) (i + 1) n := by
    intro n
    simp only [Equiv.swap_apply_def]
    split_ifs <;> omega
  have h : ((swapAux L (i + 1)).toAlgHom.comp (swapAux L i).toAlgHom).comp
        (swapAux L (i + 1)).toAlgHom
      = MvPolynomial.rename (Equiv.swap (i - 1) (i + 1)) := by
    refine MvPolynomial.algHom_ext fun n => ?_
    simp only [AlgHom.comp_apply, AlgEquiv.coe_toAlgHom, swapAux_X, hsucc,
      MvPolynomial.rename_X]
    rw [key]
  exact congrArg (fun f : Total L →ₐ[Sym.Lambda L] Total L => f F) h

end Swap

/-! ### The interchange and the divided difference on the fraction field -/

section Frac

variable {L : Type*} [Field L]

/-- **The interchange `s_i` on `Λ ⊗_𝕜 𝕜(y_1, …, y_k)`.** `HJO.Sweep.swapAux` read on the
fraction field of the total space: `s_i` is injective, so it extends there in exactly one way, and
`HJO.Sweep.swapFrac_toFrac` says the extension agrees with the polynomial interchange. It is again
an involution (`HJO.Sweep.swapFrac_swapFrac`), interchanging `y_i` and `y_{i+1}` and fixing every
other variable. -/
noncomputable def swapFrac (L : Type*) [Field L] (i : ℕ) : TotalFrac L →+* TotalFrac L :=
  fracLift (D := (swapAux L i).toAlgHom.restrictScalars L) (swapAux L i).injective

/-- `s_i` on the fraction field extends `s_i` on the total space. -/
@[simp] theorem swapFrac_toFrac (i : ℕ) (F : Total L) :
    swapFrac L i (toFrac F) = toFrac (swapAux L i F) :=
  fracLift_toFrac _ F

/-- `s_i` is an involution of the fraction field. -/
theorem swapFrac_swapFrac (i : ℕ) (x : TotalFrac L) : swapFrac L i (swapFrac L i x) = x := by
  have h : (swapFrac L i).comp (swapFrac L i) = RingHom.id (TotalFrac L) := by
    refine IsLocalization.ringHom_ext (nonZeroDivisors (Total L)) (RingHom.ext fun G => ?_)
    simp only [RingHom.comp_apply, RingHom.id_apply]
    change swapFrac L i (swapFrac L i (toFrac G)) = toFrac G
    rw [swapFrac_toFrac, swapFrac_toFrac, swapAux_swapAux]
  exact congrArg (fun f : TotalFrac L →+* TotalFrac L => f x) h

/-- `s_i` sends `y_i` to `y_{i+1}`, for `i ≥ 1`. -/
theorem swapFrac_auxFrac_self {i : ℕ} (hi : 1 ≤ i) :
    swapFrac L i (auxFrac L i) = auxFrac L (i + 1) := by
  rw [auxFrac, swapFrac_toFrac, swapAux_auxVar_self hi]

/-- `s_i` sends `y_{i+1}` to `y_i`, for `i ≥ 1`. -/
theorem swapFrac_auxFrac_succ {i : ℕ} (hi : 1 ≤ i) :
    swapFrac L i (auxFrac L (i + 1)) = auxFrac L i := by
  rw [auxFrac, swapFrac_toFrac, swapAux_auxVar_succ hi]

/-- `s_i` fixes every auxiliary variable other than `y_i` and `y_{i+1}`. -/
theorem swapFrac_auxFrac_of_ne {i j : ℕ} (hj : 1 ≤ j) (h1 : j ≠ i) (h2 : j ≠ i + 1) :
    swapFrac L i (auxFrac L j) = auxFrac L j := by
  rw [auxFrac, swapFrac_toFrac, swapAux_auxVar_of_ne hj h1 h2]

/-- **`∂_i` is the quotient `(F - s_iF)/(y_{i+1}-y_i)` of `Λ ⊗_𝕜 𝕜(y_1, …, y_k)`.** This is
`HJO.Sweep.dividedDiffₗ` in the ring it is written in, obtained from the polynomial identity
`HJO.Sweep.dividedDiff_spec` by dividing. At the unread index `0` both sides are `0`, the
convention `y_0 = y_1` making the denominator vanish there. -/
theorem toFrac_dividedDiff (i : ℕ) (F : Total L) :
    toFrac (dividedDiff i F)
      = (toFrac F - toFrac (swapAux L i F)) / (auxFrac L (i + 1) - auxFrac L i) := by
  rcases Nat.eq_zero_or_pos i with rfl | hi
  · rw [dividedDiff_zero_index, swapAux_zero, sub_self, zero_div]
    exact map_zero _
  · have hd : auxFrac L (i + 1) - auxFrac L i ≠ 0 :=
      auxFrac_sub_ne_zero (by omega) (by omega) (by omega)
    have hspec : ((auxVar (i + 1) : Total L) - auxVar i) * dividedDiff i F
        = F - swapAux L i F := dividedDiff_spec i F
    have h := congrArg (algebraMap (Total L) (TotalFrac L)) hspec
    rw [map_mul, map_sub, map_sub] at h
    rw [eq_div_iff hd]
    linear_combination h

/-- **The divided difference is fixed by the interchange**: `s_i(∂_iF) = ∂_iF`, in
`Λ ⊗_𝕜 𝕜(y_1, …, y_k)`. The usual one-line argument: by `HJO.Sweep.toFrac_dividedDiff`, `∂_iF`
is the quotient `(F - s_iF)/(y_{i+1}-y_i)`, and `s_i` is a ring automorphism of order two, so it
carries the numerator `F - s_iF` to `s_iF - F` and the denominator `y_{i+1}-y_i` to `y_i-y_{i+1}`;
both change sign and the quotient does not.

The hypotheses `k ≥ 2` and `1 ≤ i ≤ k-1` are not needed: the identity holds at every
index, at the unread `0` because `∂_0 = 0` there. -/
@[hjo "lem_dem_divided_symmetric"]
theorem swapFrac_toFrac_dividedDiff (i : ℕ) (F : Total L) :
    swapFrac L i (toFrac (dividedDiff i F)) = toFrac (dividedDiff i F) := by
  rcases Nat.eq_zero_or_pos i with rfl | hi
  · rw [swapFrac_toFrac, swapAux_zero]
  rw [toFrac_dividedDiff, map_div₀, map_sub, map_sub, swapFrac_toFrac, swapFrac_toFrac,
    swapAux_swapAux, swapFrac_auxFrac_succ hi, swapFrac_auxFrac_self hi,
    ← neg_sub (toFrac F) (toFrac (swapAux L i F)),
    ← neg_sub (auxFrac L (i + 1)) (auxFrac L i), neg_div_neg_eq]

end Frac

/-! ### The two expansions, with the operators stripped out -/

section Abstract

variable {K : Type*}

/-- **The left braid word expanded, with the operators replaced by opaque atoms.** The seven
hypotheses are the cleared two-term form of the operator at `F`, at `T_i(F)` and at
`T_{i+1}(T_i(F))`, together with four of those transported by an interchange; the conclusion is the
expansion multiplied by `(y-x)^2(z-y)(z-x)`. With the operators gone it is a polynomial identity in
fourteen indeterminates, which `linear_combination` verifies by `ring`. -/
theorem braid_expand_left_of_split [CommRing K]
    {x y z Q a b c p r s w f₀ f₁ f₂ f₃ f₄ f₅ : K}
    (hc : (y - x) * c = (Q - 1) * x * f₀ + (y - Q * x) * f₁)
    (hb : (z - y) * b = (Q - 1) * y * c + (z - Q * y) * w)
    (hw : (z - x) * w = (Q - 1) * x * f₂ + (z - Q * x) * f₃)
    (ha : (y - x) * a = (Q - 1) * x * b + (y - Q * x) * p)
    (hp : (z - x) * p = (Q - 1) * x * r + (z - Q * x) * s)
    (hr : -((y - x) * r) = (Q - 1) * y * f₁ + (x - Q * y) * f₀)
    (hs : (z - y) * s = (Q - 1) * y * f₄ + (z - Q * y) * f₅) :
    (y - x) ^ 2 * (z - y) * (z - x) * a
      = ((Q - 1) ^ 3 * x ^ 2 * y * (z - x)
            - (Q - 1) * x * (y - Q * x) * (x - Q * y) * (z - y)) * f₀
        + (Q - 1) ^ 2 * x * y * (y - Q * x) * (y - x) * f₁
        + (Q - 1) ^ 2 * x ^ 2 * (z - Q * y) * (y - x) * f₂
        + (Q - 1) * x * (z - Q * y) * (z - Q * x) * (y - x) * f₃
        + (Q - 1) * y * (y - Q * x) * (z - Q * x) * (y - x) * f₄
        + (y - Q * x) * (z - Q * x) * (z - Q * y) * (y - x) * f₅ := by
  linear_combination ((y - x) * (z - y) * (z - x)) * ha
    + ((Q - 1) * x * (y - x) * (z - x)) * hb
    + ((Q - 1) ^ 2 * x * y * (z - x)) * hc
    + ((Q - 1) * x * (z - Q * y) * (y - x)) * hw
    + ((y - Q * x) * (y - x) * (z - y)) * hp
    - ((Q - 1) * x * (y - Q * x) * (z - y)) * hr
    + ((y - Q * x) * (y - x) * (z - Q * x)) * hs

/-- **The right braid word expanded, with the operators replaced by opaque atoms.** The mirror of
`HJO.Sweep.braid_expand_left_of_split`: the same seven shapes, read with the two indices exchanged,
and the conclusion multiplied by `(z-y)^2(y-x)(z-x)`. -/
theorem braid_expand_right_of_split [CommRing K]
    {x y z Q a b c p r s w f₀ f₁ f₂ f₃ f₄ f₅ : K}
    (hc : (z - y) * c = (Q - 1) * y * f₀ + (z - Q * y) * f₁)
    (hb : (y - x) * b = (Q - 1) * x * c + (y - Q * x) * w)
    (hw : (z - x) * w = (Q - 1) * x * f₂ + (z - Q * x) * f₄)
    (ha : (z - y) * a = (Q - 1) * y * b + (z - Q * y) * p)
    (hp : (z - x) * p = (Q - 1) * x * r + (z - Q * x) * s)
    (hr : -((z - y) * r) = (Q - 1) * z * f₁ + (y - Q * z) * f₀)
    (hs : (y - x) * s = (Q - 1) * x * f₃ + (y - Q * x) * f₅) :
    (z - y) ^ 2 * (y - x) * (z - x) * a
      = ((Q - 1) ^ 3 * x * y ^ 2 * (z - x)
            - (Q - 1) * x * (z - Q * y) * (y - Q * z) * (y - x)) * f₀
        + ((Q - 1) ^ 2 * x * y * (z - Q * y) * (z - x)
            - (Q - 1) ^ 2 * x * z * (z - Q * y) * (y - x)) * f₁
        + (Q - 1) ^ 2 * x * y * (y - Q * x) * (z - y) * f₂
        + (Q - 1) * x * (z - Q * y) * (z - Q * x) * (z - y) * f₃
        + (Q - 1) * y * (y - Q * x) * (z - Q * x) * (z - y) * f₄
        + (y - Q * x) * (z - Q * x) * (z - Q * y) * (z - y) * f₅ := by
  linear_combination ((z - y) * (y - x) * (z - x)) * ha
    + ((Q - 1) * y * (z - y) * (z - x)) * hb
    + ((Q - 1) ^ 2 * x * y * (z - x)) * hc
    + ((Q - 1) * y * (y - Q * x) * (z - y)) * hw
    + ((z - Q * y) * (z - y) * (y - x)) * hp
    - ((Q - 1) * x * (z - Q * y) * (y - x)) * hr
    + ((z - Q * y) * (z - Q * x) * (z - y)) * hs

/-- **Dividing the left expansion**, in an arbitrary field where the three differences are
invertible. -/
theorem braid_expand_left_of_cleared [Field K] {x y z Q a f₀ f₁ f₂ f₃ f₄ f₅ : K}
    (hyx : y - x ≠ 0) (hzy : z - y ≠ 0) (hzx : z - x ≠ 0)
    (h : (y - x) ^ 2 * (z - y) * (z - x) * a
      = ((Q - 1) ^ 3 * x ^ 2 * y * (z - x)
            - (Q - 1) * x * (y - Q * x) * (x - Q * y) * (z - y)) * f₀
        + (Q - 1) ^ 2 * x * y * (y - Q * x) * (y - x) * f₁
        + (Q - 1) ^ 2 * x ^ 2 * (z - Q * y) * (y - x) * f₂
        + (Q - 1) * x * (z - Q * y) * (z - Q * x) * (y - x) * f₃
        + (Q - 1) * y * (y - Q * x) * (z - Q * x) * (y - x) * f₄
        + (y - Q * x) * (z - Q * x) * (z - Q * y) * (y - x) * f₅) :
    a = ((Q - 1) ^ 3 * x ^ 2 * y / ((y - x) ^ 2 * (z - y))
            - (Q - 1) * x * (y - Q * x) * (x - Q * y) / ((y - x) ^ 2 * (z - x))) * f₀
        + ((Q - 1) ^ 2 * x * y * (y - Q * x) / ((y - x) ^ 2 * (z - y))
            - (Q - 1) ^ 2 * x * y * (y - Q * x) / ((y - x) ^ 2 * (z - x))) * f₁
        + (Q - 1) ^ 2 * x ^ 2 * (z - Q * y) / ((y - x) * (z - y) * (z - x)) * f₂
        + (Q - 1) * x * (z - Q * y) * (z - Q * x) / ((y - x) * (z - y) * (z - x)) * f₃
        + (Q - 1) * y * (y - Q * x) * (z - Q * x) / ((y - x) * (z - y) * (z - x)) * f₄
        + (y - Q * x) * (z - Q * x) * (z - Q * y) / ((y - x) * (z - y) * (z - x)) * f₅ := by
  refine mul_left_cancel₀ (show ((y - x) ^ 2 * (z - y) * (z - x) : K) ≠ 0 from
    mul_ne_zero (mul_ne_zero (pow_ne_zero 2 hyx) hzy) hzx) ?_
  rw [h]
  field_simp
  ring

/-- **Dividing the right expansion**, in an arbitrary field where the three differences are
invertible. -/
theorem braid_expand_right_of_cleared [Field K] {x y z Q a f₀ f₁ f₂ f₃ f₄ f₅ : K}
    (hyx : y - x ≠ 0) (hzy : z - y ≠ 0) (hzx : z - x ≠ 0)
    (h : (z - y) ^ 2 * (y - x) * (z - x) * a
      = ((Q - 1) ^ 3 * x * y ^ 2 * (z - x)
            - (Q - 1) * x * (z - Q * y) * (y - Q * z) * (y - x)) * f₀
        + ((Q - 1) ^ 2 * x * y * (z - Q * y) * (z - x)
            - (Q - 1) ^ 2 * x * z * (z - Q * y) * (y - x)) * f₁
        + (Q - 1) ^ 2 * x * y * (y - Q * x) * (z - y) * f₂
        + (Q - 1) * x * (z - Q * y) * (z - Q * x) * (z - y) * f₃
        + (Q - 1) * y * (y - Q * x) * (z - Q * x) * (z - y) * f₄
        + (y - Q * x) * (z - Q * x) * (z - Q * y) * (z - y) * f₅) :
    a = ((Q - 1) ^ 3 * x * y ^ 2 / ((z - y) ^ 2 * (y - x))
            - (Q - 1) * x * (z - Q * y) * (y - Q * z) / ((z - y) ^ 2 * (z - x))) * f₀
        + ((Q - 1) ^ 2 * x * y * (z - Q * y) / ((z - y) ^ 2 * (y - x))
            - (Q - 1) ^ 2 * x * z * (z - Q * y) / ((z - y) ^ 2 * (z - x))) * f₁
        + (Q - 1) ^ 2 * x * y * (y - Q * x) / ((y - x) * (z - y) * (z - x)) * f₂
        + (Q - 1) * x * (z - Q * y) * (z - Q * x) / ((y - x) * (z - y) * (z - x)) * f₃
        + (Q - 1) * y * (y - Q * x) * (z - Q * x) / ((y - x) * (z - y) * (z - x)) * f₄
        + (y - Q * x) * (z - Q * x) * (z - Q * y) / ((y - x) * (z - y) * (z - x)) * f₅ := by
  refine mul_left_cancel₀ (show ((z - y) ^ 2 * (y - x) * (z - x) : K) ≠ 0 from
    mul_ne_zero (mul_ne_zero (pow_ne_zero 2 hzy) hyx) hzx) ?_
  rw [h]
  field_simp

end Abstract

/-! ### The two expansions on the total space and its fraction field -/

section Words

variable {L : Type*} [Field L]

/-- **The left braid word `T_iT_{i+1}T_i`, cleared of its denominator.** Multiplied through by
`(y_{i+1}-y_i)^2(y_{i+2}-y_{i+1})(y_{i+2}-y_i)`, the word is a combination of the six images of `F`
under the group generated by `s_i` and `s_{i+1}` with coefficients polynomial in
`y_i, y_{i+1}, y_{i+2}`. This is the form that lives in `HJO.Sweep.Total`, where
`HJO.Sweep.dividedDiff` already takes its quotient; the divided form is
`HJO.Sweep.toFrac_braid_braid_succ_braid`. -/
theorem auxVar_sub_mul_braid_braid_succ_braid (q : L) {i : ℕ} (hi : 1 ≤ i) (F : Total L) :
    ((auxVar (i + 1) : Total L) - auxVar i) ^ 2 * ((auxVar (i + 2) : Total L) - auxVar (i + 1))
        * ((auxVar (i + 2) : Total L) - auxVar i)
        * braid q i (braid q (i + 1) (braid q i F))
      = ((scal q - 1) ^ 3 * auxVar i ^ 2 * auxVar (i + 1)
              * ((auxVar (i + 2) : Total L) - auxVar i)
            - (scal q - 1) * auxVar i * ((auxVar (i + 1) : Total L) - scal q * auxVar i)
                * ((auxVar i : Total L) - scal q * auxVar (i + 1))
                * ((auxVar (i + 2) : Total L) - auxVar (i + 1))) * F
        + (scal q - 1) ^ 2 * auxVar i * auxVar (i + 1)
            * ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 1) : Total L) - auxVar i) * swapAux L i F
        + (scal q - 1) ^ 2 * auxVar i ^ 2
            * ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
            * ((auxVar (i + 1) : Total L) - auxVar i) * swapAux L (i + 1) F
        + (scal q - 1) * auxVar i * ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
            * ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 1) : Total L) - auxVar i) * swapAux L (i + 1) (swapAux L i F)
        + (scal q - 1) * auxVar (i + 1) * ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 1) : Total L) - auxVar i) * swapAux L i (swapAux L (i + 1) F)
        + ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
            * ((auxVar (i + 1) : Total L) - auxVar i)
            * swapAux L i (swapAux L (i + 1) (swapAux L i F)) := by
  have hi2 : i + 1 + 1 = i + 2 := by omega
  have hQ : (scal (q - 1) : Total L) = scal q - 1 := by rw [scal_sub, scal_one]
  have hsx : swapAux L i (auxVar i : Total L) = auxVar (i + 1) := swapAux_auxVar_self hi
  have hsy : swapAux L i (auxVar (i + 1) : Total L) = auxVar i := swapAux_auxVar_succ hi
  have hsz : swapAux L i (auxVar (i + 2) : Total L) = auxVar (i + 2) :=
    swapAux_auxVar_of_ne (by omega) (by omega) (by omega)
  have htx : swapAux L (i + 1) (auxVar i : Total L) = auxVar i :=
    swapAux_auxVar_of_ne (by omega) (by omega) (by omega)
  have hty : swapAux L (i + 1) (auxVar (i + 1) : Total L) = auxVar (i + 2) := by
    have h := swapAux_auxVar_self (L := L) (i := i + 1) (by omega)
    rwa [hi2] at h
  have htz : swapAux L (i + 1) (auxVar (i + 2) : Total L) = auxVar (i + 1) := by
    have h := swapAux_auxVar_succ (L := L) (i := i + 1) (by omega)
    rwa [hi2] at h
  have hc : ((auxVar (i + 1) : Total L) - auxVar i) * braid q i F
      = (scal q - 1) * auxVar i * F
        + ((auxVar (i + 1) : Total L) - scal q * auxVar i) * swapAux L i F := by
    have h := auxVar_sub_mul_braid q i F
    rwa [hQ] at h
  have hb : ((auxVar (i + 2) : Total L) - auxVar (i + 1)) * braid q (i + 1) (braid q i F)
      = (scal q - 1) * auxVar (i + 1) * braid q i F
        + ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
            * swapAux L (i + 1) (braid q i F) := by
    have h := auxVar_sub_mul_braid q (i + 1) (braid q i F)
    rwa [hi2, hQ] at h
  have hw : ((auxVar (i + 2) : Total L) - auxVar i) * swapAux L (i + 1) (braid q i F)
      = (scal q - 1) * auxVar i * swapAux L (i + 1) F
        + ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * swapAux L (i + 1) (swapAux L i F) := by
    have h := congrArg (swapAux L (i + 1)) hc
    simp only [map_mul, map_sub, map_add, map_one, swapAux_scal, htx, hty] at h
    exact h
  have ha : ((auxVar (i + 1) : Total L) - auxVar i)
        * braid q i (braid q (i + 1) (braid q i F))
      = (scal q - 1) * auxVar i * braid q (i + 1) (braid q i F)
        + ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * swapAux L i (braid q (i + 1) (braid q i F)) := by
    have h := auxVar_sub_mul_braid q i (braid q (i + 1) (braid q i F))
    rwa [hQ] at h
  have hp : ((auxVar (i + 2) : Total L) - auxVar i)
        * swapAux L i (braid q (i + 1) (braid q i F))
      = (scal q - 1) * auxVar i * swapAux L i (braid q i F)
        + ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * swapAux L i (swapAux L (i + 1) (braid q i F)) := by
    have h := congrArg (swapAux L i) hb
    simp only [map_mul, map_sub, map_add, map_one, swapAux_scal, hsy, hsz] at h
    exact h
  have hr : -(((auxVar (i + 1) : Total L) - auxVar i) * swapAux L i (braid q i F))
      = (scal q - 1) * auxVar (i + 1) * swapAux L i F
        + ((auxVar i : Total L) - scal q * auxVar (i + 1)) * F := by
    have h := congrArg (swapAux L i) hc
    simp only [map_mul, map_sub, map_add, map_one, swapAux_scal, hsx, hsy,
      swapAux_swapAux] at h
    linear_combination h
  have hs : ((auxVar (i + 2) : Total L) - auxVar (i + 1))
        * swapAux L i (swapAux L (i + 1) (braid q i F))
      = (scal q - 1) * auxVar (i + 1) * swapAux L i (swapAux L (i + 1) F)
        + ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
            * swapAux L i (swapAux L (i + 1) (swapAux L i F)) := by
    have h := congrArg (swapAux L i) hw
    simp only [map_mul, map_sub, map_add, map_one, swapAux_scal, hsx, hsz] at h
    exact h
  exact braid_expand_left_of_split hc hb hw ha hp hr hs

/-- **The right braid word `T_{i+1}T_iT_{i+1}`, cleared of its denominator.** The mirror of
`HJO.Sweep.auxVar_sub_mul_braid_braid_succ_braid`, multiplied through by
`(y_{i+2}-y_{i+1})^2(y_{i+1}-y_i)(y_{i+2}-y_i)`. Its last four coefficients are those of the left
word; only the coefficients of `F` and of the image of `F` under the outer interchange differ. -/
theorem auxVar_sub_mul_braid_succ_braid_braid_succ (q : L) {i : ℕ} (hi : 1 ≤ i) (F : Total L) :
    ((auxVar (i + 2) : Total L) - auxVar (i + 1)) ^ 2 * ((auxVar (i + 1) : Total L) - auxVar i)
        * ((auxVar (i + 2) : Total L) - auxVar i)
        * braid q (i + 1) (braid q i (braid q (i + 1) F))
      = ((scal q - 1) ^ 3 * auxVar i * auxVar (i + 1) ^ 2
              * ((auxVar (i + 2) : Total L) - auxVar i)
            - (scal q - 1) * auxVar i * ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
                * ((auxVar (i + 1) : Total L) - scal q * auxVar (i + 2))
                * ((auxVar (i + 1) : Total L) - auxVar i)) * F
        + ((scal q - 1) ^ 2 * auxVar i * auxVar (i + 1)
              * ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
              * ((auxVar (i + 2) : Total L) - auxVar i)
            - (scal q - 1) ^ 2 * auxVar i * auxVar (i + 2)
                * ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
                * ((auxVar (i + 1) : Total L) - auxVar i)) * swapAux L (i + 1) F
        + (scal q - 1) ^ 2 * auxVar i * auxVar (i + 1)
            * ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - auxVar (i + 1)) * swapAux L i F
        + (scal q - 1) * auxVar i * ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
            * ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - auxVar (i + 1)) * swapAux L (i + 1) (swapAux L i F)
        + (scal q - 1) * auxVar (i + 1) * ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - auxVar (i + 1)) * swapAux L i (swapAux L (i + 1) F)
        + ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
            * ((auxVar (i + 2) : Total L) - auxVar (i + 1))
            * swapAux L (i + 1) (swapAux L i (swapAux L (i + 1) F)) := by
  have hi2 : i + 1 + 1 = i + 2 := by omega
  have hQ : (scal (q - 1) : Total L) = scal q - 1 := by rw [scal_sub, scal_one]
  have hsx : swapAux L i (auxVar i : Total L) = auxVar (i + 1) := swapAux_auxVar_self hi
  have hsy : swapAux L i (auxVar (i + 1) : Total L) = auxVar i := swapAux_auxVar_succ hi
  have hsz : swapAux L i (auxVar (i + 2) : Total L) = auxVar (i + 2) :=
    swapAux_auxVar_of_ne (by omega) (by omega) (by omega)
  have htx : swapAux L (i + 1) (auxVar i : Total L) = auxVar i :=
    swapAux_auxVar_of_ne (by omega) (by omega) (by omega)
  have hty : swapAux L (i + 1) (auxVar (i + 1) : Total L) = auxVar (i + 2) := by
    have h := swapAux_auxVar_self (L := L) (i := i + 1) (by omega)
    rwa [hi2] at h
  have htz : swapAux L (i + 1) (auxVar (i + 2) : Total L) = auxVar (i + 1) := by
    have h := swapAux_auxVar_succ (L := L) (i := i + 1) (by omega)
    rwa [hi2] at h
  have hc : ((auxVar (i + 2) : Total L) - auxVar (i + 1)) * braid q (i + 1) F
      = (scal q - 1) * auxVar (i + 1) * F
        + ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1)) * swapAux L (i + 1) F := by
    have h := auxVar_sub_mul_braid q (i + 1) F
    rwa [hi2, hQ] at h
  have hb : ((auxVar (i + 1) : Total L) - auxVar i) * braid q i (braid q (i + 1) F)
      = (scal q - 1) * auxVar i * braid q (i + 1) F
        + ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * swapAux L i (braid q (i + 1) F) := by
    have h := auxVar_sub_mul_braid q i (braid q (i + 1) F)
    rwa [hQ] at h
  have hw : ((auxVar (i + 2) : Total L) - auxVar i) * swapAux L i (braid q (i + 1) F)
      = (scal q - 1) * auxVar i * swapAux L i F
        + ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * swapAux L i (swapAux L (i + 1) F) := by
    have h := congrArg (swapAux L i) hc
    simp only [map_mul, map_sub, map_add, map_one, swapAux_scal, hsy, hsz] at h
    exact h
  have ha : ((auxVar (i + 2) : Total L) - auxVar (i + 1))
        * braid q (i + 1) (braid q i (braid q (i + 1) F))
      = (scal q - 1) * auxVar (i + 1) * braid q i (braid q (i + 1) F)
        + ((auxVar (i + 2) : Total L) - scal q * auxVar (i + 1))
            * swapAux L (i + 1) (braid q i (braid q (i + 1) F)) := by
    have h := auxVar_sub_mul_braid q (i + 1) (braid q i (braid q (i + 1) F))
    rwa [hi2, hQ] at h
  have hp : ((auxVar (i + 2) : Total L) - auxVar i)
        * swapAux L (i + 1) (braid q i (braid q (i + 1) F))
      = (scal q - 1) * auxVar i * swapAux L (i + 1) (braid q (i + 1) F)
        + ((auxVar (i + 2) : Total L) - scal q * auxVar i)
            * swapAux L (i + 1) (swapAux L i (braid q (i + 1) F)) := by
    have h := congrArg (swapAux L (i + 1)) hb
    simp only [map_mul, map_sub, map_add, map_one, swapAux_scal, htx, hty] at h
    exact h
  have hr : -(((auxVar (i + 2) : Total L) - auxVar (i + 1))
        * swapAux L (i + 1) (braid q (i + 1) F))
      = (scal q - 1) * auxVar (i + 2) * swapAux L (i + 1) F
        + ((auxVar (i + 1) : Total L) - scal q * auxVar (i + 2)) * F := by
    have h := congrArg (swapAux L (i + 1)) hc
    simp only [map_mul, map_sub, map_add, map_one, swapAux_scal, hty, htz,
      swapAux_swapAux] at h
    linear_combination h
  have hs : ((auxVar (i + 1) : Total L) - auxVar i)
        * swapAux L (i + 1) (swapAux L i (braid q (i + 1) F))
      = (scal q - 1) * auxVar i * swapAux L (i + 1) (swapAux L i F)
        + ((auxVar (i + 1) : Total L) - scal q * auxVar i)
            * swapAux L (i + 1) (swapAux L i (swapAux L (i + 1) F)) := by
    have h := congrArg (swapAux L (i + 1)) hw
    simp only [map_mul, map_sub, map_add, map_one, swapAux_scal, htx, htz] at h
    exact h
  exact braid_expand_right_of_split hc hb hw ha hp hr hs

/-- **The expansion of the left braid word.**
`HJO.Sweep.toFrac_braid_braid_succ_braid`: in `Λ ⊗_𝕜 𝕜(y_1, …, y_k)`, `T_i(T_{i+1}(T_i(F)))` is the
combination of `F`, `s_i(F)`, `s_{i+1}(F)`, `s_{i+1}(s_i(F))`, `s_i(s_{i+1}(F))` and
`s_i(s_{i+1}(s_i(F)))` whose six coefficients are displayed below.

Writing `α = (q-1)y_i/(y_{i+1}-y_i)`, `β = (y_{i+1}-qy_i)/(y_{i+1}-y_i)`,
`γ = (q-1)y_{i+1}/(y_{i+2}-y_{i+1})` and `δ = (y_{i+2}-qy_{i+1})/(y_{i+2}-y_{i+1})`, so that
`HJO.Sweep.toFrac_braid` reads `T_i(G) = αG + βs_i(G)` and `T_{i+1}(G) = γG + δs_{i+1}(G)`, the six
coefficients are `α²γ + βs_i(γ)s_i(β)`, `αβγ + βs_i(α)s_i(γ)`, `αδs_{i+1}(α)`, `αδs_{i+1}(β)`,
`βs_i(δ)γ` and `βs_i(δ)δ`, evaluated from the action of the two interchanges on the three
variables. -/
@[hjo "lem_cm_braid_expand_left"]
theorem toFrac_braid_braid_succ_braid (q : L) {i : ℕ} (hi : 1 ≤ i) (F : Total L) :
    toFrac (braid q i (braid q (i + 1) (braid q i F)))
      = ((toFrac (scal q) - 1) ^ 3 * auxFrac L i ^ 2 * auxFrac L (i + 1)
              / ((auxFrac L (i + 1) - auxFrac L i) ^ 2
                * (auxFrac L (i + 2) - auxFrac L (i + 1)))
            - (toFrac (scal q) - 1) * auxFrac L i
                * (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L i)
                * (auxFrac L i - toFrac (scal q) * auxFrac L (i + 1))
              / ((auxFrac L (i + 1) - auxFrac L i) ^ 2
                * (auxFrac L (i + 2) - auxFrac L i))) * toFrac F
        + ((toFrac (scal q) - 1) ^ 2 * auxFrac L i * auxFrac L (i + 1)
                * (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L i)
              / ((auxFrac L (i + 1) - auxFrac L i) ^ 2
                * (auxFrac L (i + 2) - auxFrac L (i + 1)))
            - (toFrac (scal q) - 1) ^ 2 * auxFrac L i * auxFrac L (i + 1)
                * (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L i)
              / ((auxFrac L (i + 1) - auxFrac L i) ^ 2
                * (auxFrac L (i + 2) - auxFrac L i))) * toFrac (swapAux L i F)
        + (toFrac (scal q) - 1) ^ 2 * auxFrac L i ^ 2
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L (i + 1))
            / ((auxFrac L (i + 1) - auxFrac L i) * (auxFrac L (i + 2) - auxFrac L (i + 1))
              * (auxFrac L (i + 2) - auxFrac L i)) * toFrac (swapAux L (i + 1) F)
        + (toFrac (scal q) - 1) * auxFrac L i
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L (i + 1))
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L i)
            / ((auxFrac L (i + 1) - auxFrac L i) * (auxFrac L (i + 2) - auxFrac L (i + 1))
              * (auxFrac L (i + 2) - auxFrac L i))
            * toFrac (swapAux L (i + 1) (swapAux L i F))
        + (toFrac (scal q) - 1) * auxFrac L (i + 1)
            * (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L i)
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L i)
            / ((auxFrac L (i + 1) - auxFrac L i) * (auxFrac L (i + 2) - auxFrac L (i + 1))
              * (auxFrac L (i + 2) - auxFrac L i))
            * toFrac (swapAux L i (swapAux L (i + 1) F))
        + (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L i)
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L i)
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L (i + 1))
            / ((auxFrac L (i + 1) - auxFrac L i) * (auxFrac L (i + 2) - auxFrac L (i + 1))
              * (auxFrac L (i + 2) - auxFrac L i))
            * toFrac (swapAux L i (swapAux L (i + 1) (swapAux L i F))) := by
  refine braid_expand_left_of_cleared (auxFrac_sub_ne_zero (by omega) (by omega) (by omega))
    (auxFrac_sub_ne_zero (by omega) (by omega) (by omega))
    (auxFrac_sub_ne_zero (by omega) (by omega) (by omega)) ?_
  have h := congrArg (algebraMap (Total L) (TotalFrac L))
    (auxVar_sub_mul_braid_braid_succ_braid q hi F)
  simpa only [map_mul, map_add, map_sub, map_pow, map_one] using h

/-- **The expansion of the right braid word.**
`HJO.Sweep.toFrac_braid_succ_braid_braid_succ`: in `Λ ⊗_𝕜 𝕜(y_1, …, y_k)`,
`T_{i+1}(T_i(T_{i+1}(F)))` is the combination of `F`, `s_{i+1}(F)`, `s_i(F)`, `s_{i+1}(s_i(F))`,
`s_i(s_{i+1}(F))` and `s_{i+1}(s_i(s_{i+1}(F)))` whose six coefficients are displayed below.

With `α, β, γ, δ` as in `HJO.Sweep.toFrac_braid_braid_succ_braid` the six coefficients are
`γ²α + δs_{i+1}(α)s_{i+1}(δ)`, `αγδ + δs_{i+1}(γ)s_{i+1}(α)`, `βγs_i(γ)`, `δs_{i+1}(β)α`,
`βγs_i(δ)` and `δs_{i+1}(β)β`. The last four agree with the left word's, because
`s_{i+1}(s_i(γ)) = α` and `s_{i+1}(s_i(δ)) = β`; the braid relation for the operators is therefore
the comparison of the first two. -/
@[hjo "lem_cm_braid_expand_right"]
theorem toFrac_braid_succ_braid_braid_succ (q : L) {i : ℕ} (hi : 1 ≤ i) (F : Total L) :
    toFrac (braid q (i + 1) (braid q i (braid q (i + 1) F)))
      = ((toFrac (scal q) - 1) ^ 3 * auxFrac L i * auxFrac L (i + 1) ^ 2
              / ((auxFrac L (i + 2) - auxFrac L (i + 1)) ^ 2
                * (auxFrac L (i + 1) - auxFrac L i))
            - (toFrac (scal q) - 1) * auxFrac L i
                * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L (i + 1))
                * (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L (i + 2))
              / ((auxFrac L (i + 2) - auxFrac L (i + 1)) ^ 2
                * (auxFrac L (i + 2) - auxFrac L i))) * toFrac F
        + ((toFrac (scal q) - 1) ^ 2 * auxFrac L i * auxFrac L (i + 1)
                * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L (i + 1))
              / ((auxFrac L (i + 2) - auxFrac L (i + 1)) ^ 2
                * (auxFrac L (i + 1) - auxFrac L i))
            - (toFrac (scal q) - 1) ^ 2 * auxFrac L i * auxFrac L (i + 2)
                * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L (i + 1))
              / ((auxFrac L (i + 2) - auxFrac L (i + 1)) ^ 2
                * (auxFrac L (i + 2) - auxFrac L i))) * toFrac (swapAux L (i + 1) F)
        + (toFrac (scal q) - 1) ^ 2 * auxFrac L i * auxFrac L (i + 1)
            * (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L i)
            / ((auxFrac L (i + 1) - auxFrac L i) * (auxFrac L (i + 2) - auxFrac L (i + 1))
              * (auxFrac L (i + 2) - auxFrac L i)) * toFrac (swapAux L i F)
        + (toFrac (scal q) - 1) * auxFrac L i
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L (i + 1))
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L i)
            / ((auxFrac L (i + 1) - auxFrac L i) * (auxFrac L (i + 2) - auxFrac L (i + 1))
              * (auxFrac L (i + 2) - auxFrac L i))
            * toFrac (swapAux L (i + 1) (swapAux L i F))
        + (toFrac (scal q) - 1) * auxFrac L (i + 1)
            * (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L i)
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L i)
            / ((auxFrac L (i + 1) - auxFrac L i) * (auxFrac L (i + 2) - auxFrac L (i + 1))
              * (auxFrac L (i + 2) - auxFrac L i))
            * toFrac (swapAux L i (swapAux L (i + 1) F))
        + (auxFrac L (i + 1) - toFrac (scal q) * auxFrac L i)
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L i)
            * (auxFrac L (i + 2) - toFrac (scal q) * auxFrac L (i + 1))
            / ((auxFrac L (i + 1) - auxFrac L i) * (auxFrac L (i + 2) - auxFrac L (i + 1))
              * (auxFrac L (i + 2) - auxFrac L i))
            * toFrac (swapAux L (i + 1) (swapAux L i (swapAux L (i + 1) F))) := by
  refine braid_expand_right_of_cleared (auxFrac_sub_ne_zero (by omega) (by omega) (by omega))
    (auxFrac_sub_ne_zero (by omega) (by omega) (by omega))
    (auxFrac_sub_ne_zero (by omega) (by omega) (by omega)) ?_
  have h := congrArg (algebraMap (Total L) (TotalFrac L))
    (auxVar_sub_mul_braid_succ_braid_braid_succ q hi F)
  simpa only [map_mul, map_add, map_sub, map_pow, map_one] using h

end Words

end HJO.Sweep
