/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import Mathlib.Data.Int.Interval
public import HJO.Series.Gaps
public meta import HJO.Attr

/-! # Further definitions attached to the gap set

This file records six objects attached to the gap set that the base library `QSeriesLib` does not
already carry:
the symmetric bilinear form polarising the quadratic form of the gap set, the distance from an
integer to the multiples of `d`, the cylindric weight,
the Gaussian binomial coefficient at integer arguments, the layers (superlevel sets) of a vector
and their multiplicities. It opens with the membership criterion for the semigroup itself, in the
combination form the library uses.

The bilinear form takes *half*-integer values -- for a single pair of distinct gaps `g`, `h` with
`0 ≤ h - g < a` it is `1/2` -- so it is valued in `ℚ`, not `ℤ`; the literature's cross-dinv
statistic is exactly this half-integer. Its integral numerator is `two_mul_bilin`.

The Gaussian binomial lives in `ℤ⟦X⟧` with `q = X`, matching `HJO.multiplicand`: `(q)_m` is
`(X; X)_m` and dividing by `(q)_m` means multiplying by its power series inverse. Its integer
arguments are needed because consumers feed it differences of coordinates that leave the range
`0 ≤ k ≤ m`, where the value is `0`.
-/

@[expose] public section

open Finset NumericalSemigroup PowerSeries
open scoped QTheory

namespace HJO.Defs

/-! ### The semigroup

The semigroup `Γ = {ua + vb : u, v ≥ 0}` is `AddSubmonoid.closure {a, b}`, which for coprime
generators is `finspan {a, b}`. The criterion below is the positive counterpart of
`HJO.Gaps.mem_gaps_iff_not_exists`. -/

/-- The semigroup generated by `a` and `b` consists of exactly the nonnegative combinations
`u * a + v * b`. -/
@[hjo "def_semigroup"]
theorem mem_finspan_iff_exists (a b : ℕ) (hab : a.Coprime b) (n : ℕ) :
    n ∈ finspan {a, b} ↔ ∃ u v : ℕ, u * a + v * b = n := by
  have hgcd : ({a, b} : Finset ℕ).gcd id = 1 := by gcd_tac
  rw [mem_finspan_iff _ hgcd]
  simp [AddSubmonoid.mem_closure_pair]

/-! ### The bilinear form -/

/-- The symmetric bilinear form of the gap set,
`B x y = ½ ∑_{g, h ∈ G} (K (h - g) + K (g - h)) * x g * y h`, where `K = HJO.U a b` is the
kernel of the quadratic form `HJO.Q'`. It polarises that quadratic form, hence the halving, and
so is valued in `ℚ`: the symmetrised kernel is odd on a single pair of distinct indices. -/
@[hjo "def_bilinear_form"]
def bilin (G : Finset ℕ) (a b : ℕ) (x y : G → ℤ) : ℚ :=
  ((∑ g : G, ∑ h : G,
    (HJO.U a b ((h : ℕ) - (g : ℕ)) + HJO.U a b ((g : ℕ) - (h : ℕ))) * x g * y h : ℤ) : ℚ) / 2

/-- Twice the bilinear form is the integral sum of the symmetrised kernel, with no division:
the shape in which the literature states its evaluations. -/
theorem two_mul_bilin (G : Finset ℕ) (a b : ℕ) (x y : G → ℤ) :
    2 * bilin G a b x y = ((∑ g : G, ∑ h : G,
      (HJO.U a b ((h : ℕ) - (g : ℕ)) + HJO.U a b ((g : ℕ) - (h : ℕ))) * x g * y h : ℤ) : ℚ) := by
  rw [bilin]
  ring

/-! ### The distance to a multiple of `d` -/

/-- The distance from `x : ℤ` to the multiples of `d`, `dist (x, dℤ) = min_{j ∈ ℤ} |x - dj|`, as a
natural number. The values `|x - dj|` form a nonempty set of natural numbers (`j = 0` gives `|x|`),
so this infimum is attained: `Nat.sInf_le` bounds it above by every `|x - dj|` and `Nat.sInf_mem`
returns a `j` realising it. No hypothesis is put on `d`: at `d = 0` the value is `|x|`, and `d`,
`-d` give the same value. For `0 < d` it is realised by the least absolute residue
`(Int.bmod x d).natAbs`, the form `cylWeight` is written in. -/
@[hjo "def_dist"]
noncomputable def distMultiples (x d : ℤ) : ℕ := ⨅ j : ℤ, (x - d * j).natAbs

/-! ### The cylindric weight -/

/-- The cylindric weight `w a b m = min {a, b, dist (a * m, (a + b) ℤ)}`, the distance from `x`
to the nearest multiple of `d` being realised as `|Int.bmod x d|`; see `cylWeight_eq` for that
distance written out in terms of the remainder of `x` modulo `d`. This is the exponent of the
cylindric product, one more than `HJO.negR` away from a multiple of `d`. -/
@[hjo "def_cyl_weight"]
def cylWeight (a b m : ℕ) : ℕ := min (min a b) (Int.bmod (a * m) (a + b)).natAbs

/-- **The cylindric weight in remainder form**: the distance from `a * m` to the nearest multiple
of `d = a + b` is `min (x % d) (d - x % d)`. -/
@[hjo "def_cyl_weight"]
theorem cylWeight_eq (a b m : ℕ) :
    (cylWeight a b m : ℤ) =
      min (min (a : ℤ) b)
        (min ((a : ℤ) * m % ((a : ℤ) + b)) ((a : ℤ) + b - (a : ℤ) * m % ((a : ℤ) + b))) := by
  rcases Nat.eq_zero_or_pos (a + b) with hd | hd
  · obtain ⟨rfl, rfl⟩ : a = 0 ∧ b = 0 := by omega
    simp [cylWeight]
  · have habs := HJO.Gaps.abs_bmod_eq ((a : ℤ) * m) (a + b) hd
    push_cast at habs
    rw [cylWeight]
    push_cast
    rw [habs]

/-- The product exponent `HJO.negR` is the cylindric weight, less one, corrected at the
multiples of `d`. -/
theorem negR_eq_cylWeight (a b m : ℕ) :
    HJO.negR a b m = cylWeight a b m + (if a + b ∣ m then 1 else 0) - 1 := rfl

/-! ### The Gaussian binomial coefficient -/

/-- The Gaussian binomial coefficient at integer arguments,
`[m, k]_q = (q)_m / ((q)_k (q)_{m - k})` when `0 ≤ k ≤ m` and `0` otherwise, where `(q)_n` is
`(X; X)_n` and dividing by `(q)_n` means multiplying by its power series inverse. -/
@[hjo "def_gauss_binomial"]
noncomputable def gaussBinom (m k : ℤ) : ℤ⟦X⟧ :=
  if 0 ≤ k ∧ k ≤ m then
    (X; X)_(m.toNat) * invOfUnit (X; X)_(k.toNat) 1 * invOfUnit (X; X)_((m - k).toNat) 1
  else 0

/-- The Gaussian binomial vanishes off the range `0 ≤ k ≤ m`. -/
theorem gaussBinom_eq_zero {m k : ℤ} (h : ¬ (0 ≤ k ∧ k ≤ m)) : gaussBinom m k = 0 := by
  simp [gaussBinom, h]

/-- The guard in the Gaussian binomial is redundant against the extended `q`-Pochhammer
conventions: those already vanish at negative indices, which is exactly where the guard fails.
This is the form in which the gap product consumes it. -/
theorem gaussBinom_eq_extended (m k : ℤ) :
    gaussBinom m k = HJO.extendedSelfQPochhammer m * HJO.extendedSelfQPochhammerInv k *
      HJO.extendedSelfQPochhammerInv (m - k) := by
  rw [gaussBinom, HJO.extendedSelfQPochhammer, HJO.extendedSelfQPochhammerInv,
    HJO.extendedSelfQPochhammerInv]
  split_ifs <;> simp_all <;> omega

/-! ### Layers and their multiplicities -/

section Layer
variable {ι α : Type*} [Fintype ι] [LE α] [DecidableLE α]

/-- The layer `D t n` of `n` at level `t`: the superlevel set `{i | t ≤ n i}`. -/
@[hjo "def_layer"]
def layer (n : ι → α) (t : α) : Finset ι := Finset.univ.filter fun i => t ≤ n i

/-- Membership in a layer is the defining inequality. -/
@[simp]
theorem mem_layer {n : ι → α} {t : α} {i : ι} : i ∈ layer n t ↔ t ≤ n i := by
  simp [layer]

end Layer

variable {a b : ℕ}

/-- The layer multiplicity `m E n`: the number of levels `t` with `1 ≤ t ≤ n f` whose layer is
exactly `E`, where `f` is the Frobenius gap and `n f` is read through the extension by zero. -/
@[hjo "def_layer_multiplicity"]
noncomputable def layerMult (a b : ℕ) (n : (finspan {a, b}).gaps → ℤ)
    (E : Finset (finspan {a, b}).gaps) : ℕ :=
  ((Finset.Icc 1 (HJO.extend n (HJO.Gaps.frobeniusGap a b))).filter fun t => layer n t = E).card

/-- A multiplicity vanishes exactly when `E` is not a layer at any admissible level. -/
theorem layerMult_eq_zero_iff (n : (finspan {a, b}).gaps → ℤ)
    (E : Finset (finspan {a, b}).gaps) :
    layerMult a b n E = 0 ↔
      ∀ t ∈ Finset.Icc 1 (HJO.extend n (HJO.Gaps.frobeniusGap a b)), layer n t ≠ E := by
  rw [layerMult, Finset.card_eq_zero, Finset.filter_eq_empty_iff]

/-- Every multiplicity is bounded by the length of the range of levels. -/
theorem layerMult_le (n : (finspan {a, b}).gaps → ℤ) (E : Finset (finspan {a, b}).gaps) :
    layerMult a b n E ≤ (HJO.extend n (HJO.Gaps.frobeniusGap a b)).toNat :=
  (Finset.card_filter_le _ _).trans (by simp [Int.card_Icc])

end HJO.Defs
