/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import Mathlib.Data.Int.ConditionallyCompleteOrder
public import QSeriesLib.NumberTheory.HJO.Basic
public meta import HJO.Attr
public import HJO.Defs

/-! # Gap data of the numerical semigroup generated by two coprime numbers

For coprime `a < b` this file records the gap set `G` of `⟨a, b⟩` and the objects attached to it:
the monotonicity cone, the kernel and the quadratic form, the gap product, the finite and
infinite HJO series, the product exponent and the HJO product.
-/

@[expose] public section

open Finset NumericalSemigroup PowerSeries
open scoped QTheory PowerSeries.DiscreteTopology

namespace HJO.Gaps

/-! ### The gap set -/

/-- The gap set of `⟨a, b⟩`: the naturals that are not of the form `u * a + v * b`. -/
@[hjo "def_gap_set"]
theorem mem_gaps_iff_not_exists (a b : ℕ) (hab : a.Coprime b) (n : ℕ) :
    n ∈ (finspan {a, b}).gaps ↔ ¬ ∃ u v : ℕ, u * a + v * b = n := by
  have hgcd : ({a, b} : Finset ℕ).gcd id = 1 := by gcd_tac
  rw [mem_gaps_iff, mem_finspan_iff _ hgcd]
  simp [AddSubmonoid.mem_closure_pair]

/-! ### The monotonicity cone -/

/-- The first generator lies in the semigroup it generates. -/
theorem mem_finspan_left {a b : ℕ} (hgcd : ({a, b} : Finset ℕ).gcd id = 1) :
    a ∈ finspan {a, b} :=
  mem_finspan_of_mem (by simp) hgcd

/-- The second generator lies in the semigroup it generates. -/
theorem mem_finspan_right {a b : ℕ} (hgcd : ({a, b} : Finset ℕ).gcd id = 1) :
    b ∈ finspan {a, b} :=
  mem_finspan_of_mem (by simp) hgcd

/-- A point of the cone is monotone along the gap order, in the shape needed for induction:
the value only grows when `u` copies of `a` and `v` copies of `b` are added to a gap. -/
theorem cone_mono {a b : ℕ} (hgcd : ({a, b} : Finset ℕ).gcd id = 1)
    {n : (finspan {a, b}).gaps → ℤ} (hn : n ∈ HJO.cone a b) :
    ∀ (u v g h : ℕ) (hg : g ∈ (finspan {a, b}).gaps) (hh : h ∈ (finspan {a, b}).gaps),
      g + u * a + v * b = h → n ⟨g, hg⟩ ≤ n ⟨h, hh⟩ := by
  intro u
  induction u with
  | zero =>
    intro v
    induction v with
    | zero =>
      intro g h hg hh hgh
      have hgh' : g = h := by rw [← hgh]; ring
      subst hgh'
      exact le_refl _
    | succ v ih =>
      intro g h hg hh hgh
      have hp : g + 0 * a + v * b + b = h := by rw [← hgh]; ring
      have hbh : b ≤ h := hp ▸ Nat.le_add_left b _
      have hpG : g + 0 * a + v * b ∈ (finspan {a, b}).gaps := by
        have h1 := sub_mem_gaps_of_mem hh (mem_finspan_right hgcd) hbh
        rwa [Nat.sub_eq_of_eq_add hp.symm] at h1
      have hpbG : g + 0 * a + v * b + b ∈ (finspan {a, b}).gaps := hp ▸ hh
      refine (ih g _ hg hpG rfl).trans ?_
      rw [show (⟨h, hh⟩ : (finspan {a, b}).gaps) = ⟨_, hpbG⟩ from Subtype.ext hp.symm]
      exact hn.2.2 ⟨_, hpG⟩ hpbG
  | succ u ih =>
    intro v g h hg hh hgh
    have hp : g + u * a + v * b + a = h := by rw [← hgh]; ring
    have hah : a ≤ h := hp ▸ Nat.le_add_left a _
    have hpG : g + u * a + v * b ∈ (finspan {a, b}).gaps := by
      have h1 := sub_mem_gaps_of_mem hh (mem_finspan_left hgcd) hah
      rwa [Nat.sub_eq_of_eq_add hp.symm] at h1
    have hpaG : g + u * a + v * b + a ∈ (finspan {a, b}).gaps := hp ▸ hh
    refine (ih v g _ hg hpG rfl).trans ?_
    rw [show (⟨h, hh⟩ : (finspan {a, b}).gaps) = ⟨_, hpaG⟩ from Subtype.ext hp.symm]
    exact hn.2.1 ⟨_, hpG⟩ hpaG

/-- The monotonicity cone: the nonnegative points of `ℤ^G` that are monotone for the gap
order. -/
@[hjo "def_cone"]
theorem cone_eq (a b : ℕ) (hab : a.Coprime b) :
    HJO.cone a b =
      {n | (∀ g, 0 ≤ n g) ∧ ∀ g h : (finspan {a, b}).gaps, GapLE a b g h → n g ≤ n h} := by
  have hgcd : ({a, b} : Finset ℕ).gcd id = 1 := by gcd_tac
  ext n
  refine ⟨fun hn => ⟨hn.1, ?_⟩, fun hn => ⟨hn.1, ?_, ?_⟩⟩
  · rintro ⟨g, hg⟩ ⟨h, hh⟩ ⟨u, v, huv⟩
    have huv' : g + (u * a + v * b) = h := huv
    rw [← Nat.add_assoc] at huv'
    exact cone_mono hgcd hn u v g h hg hh huv'
  · exact fun i hia => hn.2 i ⟨_, hia⟩ ⟨1, 0, by ring⟩
  · exact fun i hib => hn.2 i ⟨_, hib⟩ ⟨0, 1, by ring⟩

/-! ### The kernel and the quadratic form -/

/-- The kernel of the quadratic form: `K s = 1_{s ≥ 0} - 1_{s ≥ a} - 1_{s ≥ b} + 1_{s ≥ a + b}`. -/
@[hjo "def_kernel"]
theorem u_eq_kernel (a b : ℕ) (s : ℤ) :
    HJO.U a b s = (if 0 ≤ s then 1 else 0) - (if (a : ℤ) ≤ s then 1 else 0)
      - (if (b : ℤ) ≤ s then 1 else 0) + (if (a : ℤ) + b ≤ s then 1 else 0) := by
  simp [HJO.U]

/-- The quadratic form of the gap set: `Q n = ∑_{g, h ∈ G} K (h - g) * n g * n h`. -/
@[hjo "def_quadratic_form"]
theorem q_eq_sum_sum (a b : ℕ) (n : (finspan {a, b}).gaps → ℤ) :
    HJO.Q a b n = ∑ g : (finspan {a, b}).gaps, ∑ h : (finspan {a, b}).gaps,
      HJO.U a b ((h : ℕ) - (g : ℕ)) * n g * n h := by
  simp [HJO.Q, HJO.Q', Matrix.toQuadraticForm_eq_sum_sum, HJO.qMatrix]

/-! ### The gap product -/

/-- The gap product `P_G n = ∏_{g ∈ G} (q)_{n g - n (g-a-b)} / ((q)_{n g - n (g-a)}
(q)_{n g - n (g-b)})`, where `(q)_m` is `(X; X)_m` for `m ≥ 0` and `0` for `m < 0`, and dividing
by `(q)_m` means multiplying by its power series inverse. -/
@[hjo "def_gap_product"]
theorem prod_multiplicand_eq (a b : ℕ) (n : (finspan {a, b}).gaps → ℤ) :
    ∏ g : (finspan {a, b}).gaps, HJO.multiplicand _ a b n g =
      ∏ g : (finspan {a, b}).gaps,
        (if 0 ≤ n g - HJO.extend n ((g : ℕ) - (a + b)) then
            (X; X)_((n g - HJO.extend n ((g : ℕ) - (a + b))).toNat) else 0) *
          (if 0 ≤ n g - HJO.extend n ((g : ℕ) - a) then
            invOfUnit (X; X)_((n g - HJO.extend n ((g : ℕ) - a)).toNat) 1 else 0) *
          (if 0 ≤ n g - HJO.extend n ((g : ℕ) - b) then
            invOfUnit (X; X)_((n g - HJO.extend n ((g : ℕ) - b)).toNat) 1 else 0) := by
  simp [HJO.multiplicand, HJO.extendedSelfQPochhammer, HJO.extendedSelfQPochhammerInv]

/-! ### The HJO series -/

/-- The finite HJO polynomial `F N = ∑_{n ∈ C, n f ≤ N} [N; n] q^{Q n}`, the sum running over
the points of the cone whose value at the Frobenius gap is at most `N`. -/
@[hjo "def_finite_series"]
noncomputable def finiteSeries (a b N : ℕ) : ℤ⟦X⟧ :=
  ∑ᶠ n ∈ {n ∈ HJO.cone a b | HJO.extend n (frobeniusGap a b) ≤ (N : ℤ)},
    multinomial a b N n * X ^ (HJO.Q a b n).toNat

/-- The HJO series `Z = ∑_{n ∈ C} P_G n * q^{Q n}`: the sum defining `HJO.Z` may be restricted
to the monotonicity cone, off which every gap product vanishes. -/
@[hjo "def_hjo_series"]
theorem z_eq_tsum_cone (a b : ℕ) :
    HJO.Z a b = ∑' n : HJO.cone a b,
      ((∏ g : (finspan {a, b}).gaps, HJO.multiplicand _ a b (n : _) g : ℤ⟦X⟧) :
        LaurentSeries₁ ℤ) * LaurentSeries₁.xPow (HJO.Q a b n) := by
  have hsupp : Function.support (fun n : (finspan {a, b}).gaps → ℤ =>
      ((∏ g : (finspan {a, b}).gaps, HJO.multiplicand _ a b n g : ℤ⟦X⟧) : LaurentSeries₁ ℤ) *
        LaurentSeries₁.xPow (HJO.Q a b n)) ⊆ HJO.cone a b := by
    refine fun n hn => HJO.iInter_support_multiplicand_subset_cone _ a b rfl
      (Set.mem_iInter.mpr fun i hi => Function.mem_support.mp hn ?_)
    rw [Finset.prod_eq_zero (Finset.mem_univ i) hi]
    simp
  rw [HJO.Z, HJO.Z']
  exact (tsum_subtype_eq_of_support_subset hsupp).symm

/-! ### The product side -/

/-- The absolute value of `Int.bmod x m` is the distance from `x` to the nearest multiple
of `m`. -/
theorem abs_bmod_eq (x : ℤ) (m : ℕ) (hm : 0 < m) :
    |Int.bmod x m| = min (x % (m : ℤ)) ((m : ℤ) - x % (m : ℤ)) := by
  have h1 : 0 ≤ x % (m : ℤ) := Int.emod_nonneg _ (by omega)
  have h2 : x % (m : ℤ) < m := Int.emod_lt_of_pos _ (by omega)
  rw [Int.bmod_def]
  split_ifs with h
  · rw [abs_of_nonneg h1]; omega
  · rw [abs_of_nonpos (by omega)]; omega

/-- The product exponent `ρ m = min {a, b, dist (a * m, (a+b)ℤ)} - 1 + 1_{a + b ∣ m}`, where
the distance from `x` to the nearest multiple of `d` is `min (x % d) (d - x % d)`. -/
@[hjo "def_rho"]
theorem negR_eq (a b m : ℕ) (hab : a.Coprime b) :
    (HJO.negR a b m : ℤ) =
      min (min (a : ℤ) b)
          (min ((a : ℤ) * m % ((a : ℤ) + b)) ((a : ℤ) + b - (a : ℤ) * m % ((a : ℤ) + b)))
        - 1 + (if (a + b) ∣ m then 1 else 0) := by
  have hd : 0 < a + b := by
    by_contra hc
    have ha : a = 0 := by omega
    have hb : b = 0 := by omega
    rw [ha, hb] at hab
    simp [Nat.Coprime] at hab
  have habs := abs_bmod_eq ((a : ℤ) * m) (a + b) hd
  push_cast at habs
  rw [HJO.negR, ← habs]
  split_ifs with hdvd
  · have hb0 : Int.bmod ((a : ℤ) * m) (a + b) = 0 :=
      Int.dvd_iff_bmod_eq_zero.mp ((Int.natCast_dvd_natCast.mpr hdvd).mul_left (a : ℤ))
    rw [hb0, Nat.add_sub_cancel]
    simp
  · have ha1 : 1 ≤ a := by
      rcases Nat.eq_zero_or_pos a with rfl | h
      · rw [Nat.Coprime, Nat.gcd_zero_left] at hab
        exact absurd (by simp [hab]) hdvd
      · exact h
    have hb1 : 1 ≤ b := by
      rcases Nat.eq_zero_or_pos b with rfl | h
      · rw [Nat.Coprime, Nat.gcd_zero_right] at hab
        exact absurd (by simp [hab]) hdvd
      · exact h
    have hbm : Int.bmod ((a : ℤ) * m) (a + b) ≠ 0 := by
      intro h0
      have h1 : ((a + b : ℕ) : ℤ) ∣ (a : ℤ) * m := Int.dvd_iff_bmod_eq_zero.mpr h0
      have h2 : (a + b) ∣ a * m := by exact_mod_cast h1
      have hcop : Nat.Coprime (a + b) a := by
        rw [Nat.add_comm, Nat.coprime_add_self_left]
        exact hab.symm
      exact hdvd (hcop.dvd_of_dvd_mul_left h2)
    have hbm' : 1 ≤ (Int.bmod ((a : ℤ) * m) (a + b)).natAbs :=
      Nat.one_le_iff_ne_zero.mpr fun h => hbm (Int.natAbs_eq_zero.mp h)
    rw [Nat.add_zero, Nat.cast_sub (le_min (le_min ha1 hb1) hbm')]
    push_cast
    ring

/-- The HJO product `P = ∏_{m ≥ 1} (1 - q^m)^{-ρ m}`, the exponent `-ρ m` being realised by the
power series inverse of `1 - q^m`. -/
@[hjo "def_hjo_product"]
theorem charge_eq_tprod (a b : ℕ) :
    HJO.charge a b =
      ∏' m : (Set.Ici 1 : Set ℕ), invOfUnit (1 - X ^ (m : ℕ)) 1 ^ HJO.negR a b (m : ℕ) := by
  rw [HJO.charge]
  refine (tprod_subtype_eq_of_mulSupport_subset
    (Function.mulSupport_subset_iff'.mpr fun m hm => ?_)).symm
  simp only [Set.mem_Ici, not_le, Nat.lt_one_iff] at hm
  simp [hm, HJO.negR_zero]

end HJO.Gaps
