/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Main.Endgame
public import HJO.Evaluation.PhiPoly
public import HJO.Determinant.DetCoeffSolves
public import HJO.Series.Limits

/-! # The final chain over one hypothesis

The evaluation map attached to a slope homomorphism reads the value of a symmetric function off a
two-variable integer polynomial witnessing the scalar the homomorphism attaches to it: the variable
is substituted for the first parameter and `1` for the second. The substitution is performed on the
witness, an integer polynomial, and not on the base field, where the second parameter cannot be `1`
without collapsing every slope operator.

That forces the domain of the evaluation map. Its values on constants assemble into a ring
homomorphism out of the coefficient ring, so a domain containing the constant `u - 1` would carry a
ring homomorphism killing an invertible element. The coefficient ring is therefore the field
generated by the *first* parameter alone, which is where the complete homogeneous and elementary
symmetric functions, the divided alphabet and the iterated return seed all live; the second
parameter enters only through the slope homomorphism, over the larger field.

On that domain the single open input is that the evaluation map is a ring homomorphism. Everything
else is discharged: the return evaluation and the all-path evaluation of `HJO.PhiPoly`, the
determinant equation, its coefficient count, the uniqueness of the normalised solution and the
limits of the finite data. The conclusions are the exponential forms of the two generating series,
the `q`-difference equation the first of them satisfies, the finite identity and the conjecture. The
scalar recurrence, the coefficientwise form of that equation, is stated alongside them for the
record: the finite identity is read off the equation itself, not off the recurrence.
-/

@[expose] public section

open Finset

namespace HJO.Assembly

/-! ### Consequences of the genericity of the two parameters -/

section Generic

variable {K L : Type*} [Field K] [Field L] [Algebra K L] {q : K} {u : L}

/-- Extension of a coefficient field is injective. -/
theorem algebraMap_injective : Function.Injective (algebraMap K L) :=
  (algebraMap K L).injective

/-- Algebraically independent parameters are nonzero. -/
theorem ne_zero_of_algebraicIndependent (hqu : AlgebraicIndependent ℤ ![algebraMap K L q, u]) :
    q ≠ 0 := by
  intro hq
  have h0 : (MvPolynomial.X 0 : MvPolynomial (Fin 2) ℤ) = 0 :=
    PhiPoly.eq_of_aeval_eq hqu (by
      rw [MvPolynomial.aeval_X, Matrix.cons_val_zero, hq, map_zero, map_zero])
  have h1 := congrArg (MvPolynomial.aeval ![(1 : ℤ), 0]) h0
  rw [MvPolynomial.aeval_X, Matrix.cons_val_zero, map_zero] at h1
  exact one_ne_zero h1

/-- No positive power of an algebraically independent parameter is `1`. -/
theorem pow_succ_ne_one_of_algebraicIndependent
    (hqu : AlgebraicIndependent ℤ ![algebraMap K L q, u]) (j : ℕ) : q ^ (j + 1) ≠ 1 := by
  intro hq
  have hL : (algebraMap K L q) ^ (j + 1) = 1 := by rw [← map_pow, hq, map_one]
  have h0 : (MvPolynomial.X 0 : MvPolynomial (Fin 2) ℤ) ^ (j + 1) = 1 :=
    PhiPoly.eq_of_aeval_eq hqu (by
      rw [map_pow, map_one, MvPolynomial.aeval_X, Matrix.cons_val_zero, hL])
  have h1 := congrArg (MvPolynomial.aeval ![(0 : ℤ), 0]) h0
  rw [map_pow, map_one, MvPolynomial.aeval_X, Matrix.cons_val_zero,
    zero_pow (Nat.succ_ne_zero j)] at h1
  exact zero_ne_one h1

/-- Algebraically independent parameters have a product that is neither `0` nor `1` and is not a
root of unity, and the second of them is not `1`: the degenerate values at which the slope operators
collapse are excluded, and so are the roots of unity at which the axis generators fail to be a
triangular change of generators. The last conjunct is what the corrected virtual alphabet of the
axis generators needs, and it is strictly stronger than the second. The conjunction is stated for
the record; the results below use the two parameters through the preceding two lemmas. -/
theorem generic_of_algebraicIndependent (hqu : AlgebraicIndependent ℤ ![algebraMap K L q, u]) :
    algebraMap K L q * u ≠ 0 ∧ algebraMap K L q * u ≠ 1 ∧ u ≠ 1 ∧
      ∀ j : ℕ, (algebraMap K L q * u) ^ (j + 1) ≠ 1 := by
  refine ⟨fun h => ?_, fun h => ?_, fun h => ?_, fun j h => ?_⟩
  · have h0 : (MvPolynomial.X 0 * MvPolynomial.X 1 : MvPolynomial (Fin 2) ℤ) = 0 :=
      PhiPoly.eq_of_aeval_eq hqu (by simp [h])
    have h1 := congrArg (MvPolynomial.aeval ![(1 : ℤ), 1]) h0
    simp at h1
  · have h0 : (MvPolynomial.X 0 * MvPolynomial.X 1 : MvPolynomial (Fin 2) ℤ) = 1 :=
      PhiPoly.eq_of_aeval_eq hqu (by simp [h])
    have h1 := congrArg (MvPolynomial.aeval ![(0 : ℤ), 0]) h0
    simp at h1
  · have h0 : (MvPolynomial.X 1 : MvPolynomial (Fin 2) ℤ) = 1 :=
      PhiPoly.eq_of_aeval_eq hqu (by simp [h])
    have h1 := congrArg (MvPolynomial.aeval ![(0 : ℤ), 0]) h0
    simp at h1
  · have h0 : (MvPolynomial.X 0 * MvPolynomial.X 1 : MvPolynomial (Fin 2) ℤ) ^ (j + 1) = 1 :=
      PhiPoly.eq_of_aeval_eq hqu (by simp [h])
    have h1 := congrArg (MvPolynomial.aeval ![(0 : ℤ), 0]) h0
    simp at h1

end Generic

/-! ### Extension of the coefficient field -/

section BaseChange

variable {K L : Type*} [Field K] [Algebra ℚ K] [Field L] [Algebra ℚ L] [Algebra K L]
  [IsScalarTower ℚ K L]

/-- A rational scalar is the same in a coefficient field and in an extension of it. -/
theorem algebraMap_algebraMap_rat (x : ℚ) : algebraMap K L (algebraMap ℚ K x) = algebraMap ℚ L x :=
  (IsScalarTower.algebraMap_apply ℚ K L x).symm

omit [Algebra ℚ K] [Algebra ℚ L] [IsScalarTower ℚ K L] in
/-- The power sums are unchanged by extension of the coefficient field. -/
theorem map_powerSum (j : ℕ) :
    MvPolynomial.map (algebraMap K L) (Sym.powerSum K j) = Sym.powerSum L j := by
  rw [Sym.powerSum, Sym.powerSum, MvPolynomial.map_X]

/-- The complete homogeneous symmetric functions are unchanged by extension of the coefficient
field. -/
theorem map_completeHomog (n : ℕ) :
    MvPolynomial.map (algebraMap K L) (Sym.completeHomog K n) = Sym.completeHomog L n := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    match n with
    | 0 => rw [CopPower.completeHomog_zero, CopPower.completeHomog_zero, map_one]
    | m + 1 =>
      rw [UkRegular.completeHomog_succ, UkRegular.completeHomog_succ, map_mul, MvPolynomial.map_C,
        algebraMap_algebraMap_rat, map_sum]
      refine congrArg _ (Finset.sum_congr rfl fun j hj => ?_)
      rw [map_mul, map_powerSum, ih (m - j) (by omega)]

/-- The elementary symmetric functions are unchanged by extension of the coefficient field. -/
theorem map_elemSymm (n : ℕ) :
    MvPolynomial.map (algebraMap K L) (Sym.elemSymm K n) = Sym.elemSymm L n := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    match n with
    | 0 => rw [PhiE.elemSymm_zero, PhiE.elemSymm_zero, map_one]
    | m + 1 =>
      rw [PhiE.elemSymm_succ, PhiE.elemSymm_succ, map_mul, MvPolynomial.map_C,
        algebraMap_algebraMap_rat, map_sum]
      refine congrArg _ (Finset.sum_congr rfl fun j hj => ?_)
      rw [map_mul, map_mul, map_pow, map_neg, map_one, map_powerSum, ih (m - j) (by omega)]

/-- Dividing the alphabet by `1 - q` fixes the constants. -/
theorem plethDiv_C {F : Type*} [Field F] [Algebra ℚ F] (q c : F) :
    CopPower.plethDiv q (MvPolynomial.C c) = MvPolynomial.C c := by
  rw [← MvPolynomial.algebraMap_eq, AlgHom.commutes]

omit [IsScalarTower ℚ K L] in
/-- Dividing the alphabet by `1 - q` commutes with extension of the coefficient field. -/
theorem map_plethDiv (q : K) (f : Sym.Lambda K) :
    MvPolynomial.map (algebraMap K L) (CopPower.plethDiv q f)
      = CopPower.plethDiv (algebraMap K L q) (MvPolynomial.map (algebraMap K L) f) := by
  induction f using MvPolynomial.induction_on with
  | C c => rw [plethDiv_C, MvPolynomial.map_C, plethDiv_C]
  | add p r hp hr => simp only [map_add, hp, hr]
  | mul_X p i hp =>
    have hX : MvPolynomial.map (algebraMap K L) (CopPower.plethDiv q (MvPolynomial.X i))
        = CopPower.plethDiv (algebraMap K L q) (MvPolynomial.X i) := by
      rw [CopPower.plethDiv_X, CopPower.plethDiv_X, map_mul, MvPolynomial.map_C,
        MvPolynomial.map_X, map_inv₀, map_sub, map_one, map_pow]
    simp only [map_mul]
    rw [hp, hX, MvPolynomial.map_X]

/-- The iterated return seed is unchanged by extension of the coefficient field. -/
theorem map_cop_one_pow_apply_one (q : K) (hq0 : q ≠ 0) (hq : ∀ j : ℕ, q ^ (j + 1) ≠ 1) (N : ℕ) :
    MvPolynomial.map (algebraMap K L) ((Sym.Cop q 1 ^ N) 1)
      = (Sym.Cop (algebraMap K L q) 1 ^ N) 1 := by
  have hq0' : algebraMap K L q ≠ 0 := fun h =>
    hq0 (algebraMap_injective (L := L) (by rw [h, map_zero]))
  have hq' : ∀ j : ℕ, (algebraMap K L q) ^ (j + 1) ≠ 1 := fun j h =>
    hq j (algebraMap_injective (L := L) (by rw [map_pow, h, map_one]))
  have hc : algebraMap K L (q ^ (-(N.choose 2 : ℤ)) * qPochhammer q q N)
      = (algebraMap K L q) ^ (-(N.choose 2 : ℤ)) *
        qPochhammer (algebraMap K L q) (algebraMap K L q) N := by
    rw [map_mul, zpow_neg, zpow_natCast, map_inv₀, map_pow, zpow_neg, zpow_natCast,
      map_qPochhammer]
  rw [CopPower.cop_one_pow_apply_one q hq0 hq N,
    CopPower.cop_one_pow_apply_one (algebraMap K L q) hq0' hq' N, map_mul, MvPolynomial.map_C, hc,
    map_plethDiv, map_completeHomog]

end BaseChange

/-! ### The evaluation map -/

section Evaluation

variable {a b : ℕ} {K L : Type*} [Field K] [Algebra ℚ K] [Field L] [Algebra ℚ L] [Algebra K L]
  [IsScalarTower ℚ K L] {q : K} {u : L}
  {Θ : Sym.Lambda L →ₐ[L] Module.End L (Sym.Lambda L)}
  {Φ : Sym.Lambda K →+* LaurentSeries ℚ}

/-- The evaluation map of a slope homomorphism, as a ring homomorphism on the symmetric functions
whose coefficients lie in the field generated by the first parameter: on a homogeneous element of
degree `n` its value is the value read off any two-variable integer polynomial whose value at the
two parameters is the scalar the slope homomorphism attaches to that element. -/
def IsEvaluationHom (b : ℕ) (q : K) (u : L)
    (Θ : Sym.Lambda L →ₐ[L] Module.End L (Sym.Lambda L))
    (Φ : Sym.Lambda K →+* LaurentSeries ℚ) : Prop :=
  ∀ (n : ℕ) (f : Sym.Lambda K) (π : MvPolynomial (Fin 2) ℤ),
    MvPolynomial.IsWeightedHomogeneous Multiplication.degWeight f n →
    Sym.signExtract L (Θ (MvPolynomial.map (algebraMap K L) f) 1)
        = MvPolynomial.aeval ![algebraMap K L q, u] π →
      Φ f = Determinant.qOfInt (PhiPoly.phiValue b n π)

/-- The specialisation of the coefficients induced by the evaluation map: its restriction to the
constants. -/
noncomputable def specOf (Φ : Sym.Lambda K →+* LaurentSeries ℚ) : K →+* LaurentSeries ℚ :=
  Φ.comp (MvPolynomial.C : K →+* Sym.Lambda K)

omit [Algebra ℚ K] in
/-- The evaluation map on a constant is the specialisation of that constant. -/
theorem specOf_apply (c : K) : specOf Φ c = Φ (MvPolynomial.C c) := rfl

omit [Algebra ℚ L] in
/-- A slope homomorphism attaches to a constant that constant itself. -/
theorem signExtract_apply_C (c : L) : Sym.signExtract L (Θ (MvPolynomial.C c) 1) = c := by
  have h : Θ (MvPolynomial.C c) = c • (1 : Module.End L (Sym.Lambda L)) := by
    rw [← MvPolynomial.algebraMap_eq, AlgHom.commutes, Algebra.algebraMap_eq_smul_one]
  rw [h, LinearMap.smul_apply, Module.End.one_apply, MvPolynomial.smul_eq_C_mul, mul_one,
    PhiHom.signExtract_C]

omit [Algebra ℚ K] [Algebra ℚ L] [IsScalarTower ℚ K L] in
/-- The evaluation map sends the first parameter to the variable of the field of `q`-Laurent
series. -/
theorem specOf_q (hmul : IsEvaluationHom b q u Θ Φ) : specOf Φ q = Determinant.qVar := by
  rw [specOf_apply,
    hmul 0 (MvPolynomial.C q) (MvPolynomial.X 0) (MvPolynomial.isWeightedHomogeneous_C _ _)
      (by rw [MvPolynomial.map_C, signExtract_apply_C, MvPolynomial.aeval_X,
        Matrix.cons_val_zero]),
    PhiPoly.phiValue, Determinant.qVar]
  simp

omit [Algebra ℚ K] [Algebra ℚ L] [IsScalarTower ℚ K L] in
/-- The evaluation map sends the `q`-Pochhammer symbol of the first parameter to the image of the
integral one. -/
theorem specOf_qPochhammer (hmul : IsEvaluationHom b q u Θ Φ) (N : ℕ) :
    specOf Φ (qPochhammer q q N)
      = Determinant.qOfInt (qPochhammer PowerSeries.X PowerSeries.X N) := by
  rw [map_qPochhammer, specOf_q hmul, map_qPochhammer, Determinant.qVar]

variable (rankOne : External.RankOneDinv) (goodTraverse : External.GoodTraverse)
  (coercivity : HJO.Literature.HuangCoercivity) (shuffle : External.Shuffle L)
  (epsilonGessel : External.EpsilonGessel L) (creationExpansion : External.CreationExpansion L)
  (ι : Sym.Lambda L →ₐ[L] Sym.AlphabetSeries L) (hι : Sym.IsRealisation ι)
  (hab : Nat.Coprime a b) (ha : 1 < a) (hb : a < b)
  (hqu : AlgebraicIndependent ℤ ![algebraMap K L q, u])
  (hΘ : Sym.IsSlopeHom a b (algebraMap K L q) u Θ) (hmul : IsEvaluationHom b q u Θ Φ)

include rankOne goodTraverse coercivity shuffle epsilonGessel hι hab ha hb hqu hΘ hmul in
/-- The return evaluation: the evaluation map takes the `N`-fold iterate of the creation operator of
a single block, applied to `1`, to the finite polynomial shifted by the block hook count. -/
theorem phi_cop_one_pow {N : ℕ} (hN : 0 < N) :
    Φ ((Sym.Cop q 1 ^ N) 1)
      = Determinant.qOfInt
        (PowerSeries.X ^ Paths.kappaShift a b N * Gaps.finiteSeries a b N) := by
  have hq0 := ne_zero_of_algebraicIndependent hqu
  have hq := pow_succ_ne_one_of_algebraicIndependent hqu
  obtain ⟨hwit, hall⟩ := PhiPoly.phiValue_cop_one_pow rankOne goodTraverse coercivity shuffle
    epsilonGessel hab ha hb hqu ι hι Θ hΘ hN
  rw [hmul N _ _ (Endgame.isWeightedHomogeneous_cop_one_pow q hq0 hq N)
    (by rw [map_cop_one_pow_apply_one q hq0 hq]; exact hwit)]
  exact congrArg Determinant.qOfInt (hall _ hwit)

include shuffle epsilonGessel creationExpansion hι hab ha hb hqu hΘ hmul in
/-- The all-path evaluation: the evaluation map takes the elementary symmetric function of degree
`N` to the area polynomial of all below-diagonal `(aN, bN)`-paths. -/
theorem phi_elemSymm (N : ℕ) :
    Φ (Sym.elemSymm K N) = Determinant.qOfInt (Paths.areaPoly a b N) := by
  rcases Nat.eq_zero_or_pos N with rfl | hN
  · rw [PhiE.elemSymm_zero, map_one, AExponential.areaPoly_zero, map_one]
  · obtain ⟨hval, hall⟩ := PhiPoly.phiValue_elemSymm shuffle epsilonGessel creationExpansion
      hab ha hb hqu ι hι Θ hΘ hN
    rw [hmul N _ _ (PhiE.isWeightedHomogeneous_elemSymm K N)
      (by rw [map_elemSymm]; exact hval)]
    exact congrArg Determinant.qOfInt (hall _ hval)

/-- The evaluation map on the divided alphabet, a ring homomorphism because the division is an
algebra endomorphism. -/
noncomputable def phiDiv (q : K) (Φ : Sym.Lambda K →+* LaurentSeries ℚ) :
    Sym.Lambda K →+* LaurentSeries ℚ :=
  Φ.comp (CopPower.plethDiv q).toRingHom

omit [Algebra ℚ K] in
/-- The evaluation map on the divided alphabet is the evaluation of the divided alphabet. -/
theorem phiDiv_apply (q : K) (f : Sym.Lambda K) :
    phiDiv q Φ f = Φ (CopPower.plethDiv q f) := rfl

include rankOne goodTraverse coercivity shuffle epsilonGessel hι hab ha hb hqu hΘ hmul in
/-- The evaluation map takes the complete homogeneous symmetric function of degree `N` on the
divided alphabet to the finite polynomial shifted by the rank shift, divided by the `q`-Pochhammer
symbol: the iterated return seed differs from it by the constant that the rank shift absorbs. -/
theorem phiDiv_completeHomog_mul_qPochhammer (N : ℕ) :
    phiDiv q Φ (Sym.completeHomog K N)
        * Determinant.qOfInt (qPochhammer PowerSeries.X PowerSeries.X N)
      = Determinant.qOfInt
        (PowerSeries.X ^ Paths.gammaShift a b N * Gaps.finiteSeries a b N) := by
  have hq0 := ne_zero_of_algebraicIndependent hqu
  have hq := pow_succ_ne_one_of_algebraicIndependent hqu
  rcases Nat.eq_zero_or_pos N with rfl | hN
  · rw [phiDiv_apply, CopPower.completeHomog_zero, map_one, map_one, qPochhammer_zero, map_one,
      one_mul, Paths.gammaShift, Endgame.finiteSeries_zero a b hab ha hb]
    simp
  · have hr := phi_cop_one_pow rankOne goodTraverse coercivity shuffle epsilonGessel ι hι hab ha hb
      hqu hΘ hmul hN
    rw [CopPower.cop_one_pow_apply_one q hq0 hq N, map_mul, ← specOf_apply, map_mul, map_zpow₀,
      specOf_q hmul, specOf_qPochhammer hmul, zpow_neg, zpow_natCast, ← phiDiv_apply] at hr
    have hgam : (PowerSeries.X : PowerSeries ℤ) ^ Paths.gammaShift a b N *
          Gaps.finiteSeries a b N
        = PowerSeries.X ^ N.choose 2 *
          (PowerSeries.X ^ Paths.kappaShift a b N * Gaps.finiteSeries a b N) := by
      rw [Endgame.gammaShift_eq a b N (by omega), pow_add, mul_assoc]
    have hpow : (Determinant.qVar : LaurentSeries ℚ) ^ N.choose 2 ≠ 0 :=
      pow_ne_zero _ Endgame.qVar_ne_zero
    rw [hgam, map_mul, map_pow, ← Determinant.qVar, ← hr]
    field_simp

include rankOne goodTraverse coercivity shuffle epsilonGessel hι hab ha hb hqu hΘ hmul in
/-- The `z^N` coefficient of the generating series of the finite polynomials is the evaluation of
the complete homogeneous symmetric function of degree `N` on the divided alphabet. -/
theorem coeff_genH (N : ℕ) :
    PowerSeries.coeff N (Determinant.genH a b) = phiDiv q Φ (Sym.completeHomog K N) := by
  rw [Determinant.genH, PowerSeries.coeff_mk,
    div_eq_iff (Endgame.qOfInt_qPochhammer_ne_zero N)]
  exact (phiDiv_completeHomog_mul_qPochhammer rankOne goodTraverse coercivity shuffle epsilonGessel
    ι hι hab ha hb hqu hΘ hmul N).symm

include rankOne goodTraverse coercivity shuffle epsilonGessel hι hab ha hb hqu hΘ hmul in
/-- `ℋ(z;q) = exp(∑_{k ≥ 1} r_k z^k / (k (1 - q^k)))`: the generating series of the finite
polynomials is the formal exponential of the series built from the evaluation coefficients. -/
theorem genH_eq_formalExp :
    Determinant.genH a b = AExponential.formalExp
      (Endgame.coeffLog fun j => Φ (Sym.powerSum K j) / (1 - Determinant.qVar ^ j)) := by
  have hmk : Determinant.genH a b
      = PowerSeries.mk fun N => phiDiv q Φ (Sym.completeHomog K N) :=
    PowerSeries.ext fun N => by
      rw [PowerSeries.coeff_mk, coeff_genH rankOne goodTraverse coercivity shuffle epsilonGessel
        ι hι hab ha hb hqu hΘ hmul N]
  refine Endgame.eq_formalExp_coeffLog ?_ ?_
  · rw [hmk, CopPower.derivative_mk_completeHomog (phiDiv q Φ)]
    congr 1
    refine PowerSeries.ext fun j => ?_
    rw [PowerSeries.coeff_mk, PowerSeries.coeff_mk, phiDiv_apply, CopPower.powerSum_succ,
      CopPower.plethDiv_X, map_mul, ← specOf_apply, map_inv₀, map_sub, map_one, map_pow,
      specOf_q hmul, div_eq_inv_mul]
  · rw [hmk, PowerSeries.coeff_mk, phiDiv_apply, CopPower.completeHomog_zero, map_one, map_one]

include shuffle epsilonGessel creationExpansion hι hab ha hb hqu hΘ hmul in
/-- `𝒜(z;q) = exp(∑_{k ≥ 1} (-1)^{k-1} r_k z^k / k)`: the area generating series is the formal
exponential of the alternating series built from the evaluation coefficients. -/
theorem genA_eq_formalExp :
    Determinant.genA a b
      = AExponential.formalExp (AExponential.logSeries fun j => Φ (Sym.powerSum K j)) := by
  have hmk : Determinant.genA a b = PowerSeries.mk fun n => Φ (Sym.elemSymm K n) :=
    PowerSeries.ext fun n => by
      rw [Determinant.genA, PowerSeries.coeff_mk, PowerSeries.coeff_mk,
        phi_elemSymm shuffle epsilonGessel creationExpansion ι hι hab ha hb hqu hΘ hmul n]
  rw [hmk]
  refine AExponential.eq_formalExp_logSeries (AExponential.derivative_mk_elemSymm Φ) ?_
  rw [PowerSeries.coeff_mk, PhiE.elemSymm_zero, map_one]

include rankOne goodTraverse coercivity shuffle epsilonGessel creationExpansion hι hab ha hb hqu hΘ
  hmul in
/-- The generating series of the finite polynomials satisfies the common `q`-difference equation:
both it and the area series are exponentials in the same evaluation coefficients, and subtracting
the logarithm of the first from its value at `qz` telescopes to the logarithm of the second read at
`-z`. -/
theorem isCommonSolution_genH : Determinant.IsCommonSolution a b (Determinant.genH a b) :=
  Endgame.isCommonSolution_genH (fun j => Φ (Sym.powerSum K j))
    (genH_eq_formalExp rankOne goodTraverse coercivity shuffle epsilonGessel ι hι hab ha hb hqu hΘ
      hmul)
    (genA_eq_formalExp shuffle epsilonGessel creationExpansion ι hι hab ha hb hqu hΘ hmul)

include rankOne goodTraverse coercivity shuffle epsilonGessel creationExpansion hι hab ha hb hqu hΘ
  hmul in
/-- The scalar recurrence: the coefficientwise form of the common equation for the generating
series of the finite polynomials. -/
theorem finiteSeries_recurrence (N : ℕ) (hN : 0 < N) :
    (PowerSeries.X : PowerSeries ℤ) ^ Paths.gammaShift a b N * Gaps.finiteSeries a b N
      = ∑ j ∈ Icc 1 N, (-1 : PowerSeries ℤ) ^ (j + 1) * Paths.areaPoly a b j *
          PowerSeries.X ^ Paths.gammaShift a b (N - j) * Gaps.finiteSeries a b (N - j) *
          ∏ i ∈ Ico (N - j + 1) N, (1 - PowerSeries.X ^ i) :=
  Endgame.finiteSeries_recurrence
    (isCommonSolution_genH rankOne goodTraverse coercivity shuffle epsilonGessel creationExpansion
      ι hι hab ha hb hqu hΘ hmul) N hN

include rankOne goodTraverse coercivity shuffle epsilonGessel creationExpansion hι hab ha hb hqu hΘ
  hmul in
/-- The finite identity `F_N(q) = (q)_N C_{𝐜,≤N}(q)`: the determinant series read at `-z` satisfies
the same `q`-difference equation, uniqueness of the normalised solution identifies the two, and the
rank shift cancels against the coefficient count of the determinant. -/
theorem finiteSeries_eq_qPochhammer_mul_boundedGF (N : ℕ) :
    Gaps.finiteSeries a b N
      = qPochhammer PowerSeries.X PowerSeries.X N * HJO.Cylindric.boundedGF a b N := by
  have hdet : ∀ M : ℕ, PowerSeries.coeff M
        (PowerSeries.rescale (-1) (Determinant.detSeries a b))
      = Determinant.qOfInt (PowerSeries.X ^ Paths.gammaShift a b M *
        HJO.Cylindric.boundedGF a b M) := fun M => by
    rw [DetCoeffSolves.coeff_rescale_neg_one_detSeries a b M hab (by omega) (by omega), map_mul,
      map_pow, ← Determinant.qVar]
  exact Endgame.finiteSeries_eq_qPochhammer_mul_boundedGF hab (by omega) (by omega)
    (isCommonSolution_genH rankOne goodTraverse coercivity shuffle epsilonGessel creationExpansion
      ι hι hab ha hb hqu hΘ hmul) hdet N

include rankOne goodTraverse coercivity shuffle epsilonGessel creationExpansion hι hab ha hb hqu hΘ
  hmul in
/-- The Huang--Jiang--Oblomkov conjecture: passing to the coefficientwise limit in the finite
identity gives `Z = (q)_∞ C_𝐜`, and the cylindric product identifies the right side with the
Huang--Jiang--Oblomkov product. -/
theorem conjecture (cylindricProduct : HJO.Literature.CylindricProduct) : HJO.Conjecture a b := by
  refine (HJO.conjecture_iff_conjecture' a b (Limits.posDefOn_Q coercivity hab ha hb)).mpr ?_
  change HJO.zNat a b = HJO.charge a b
  rw [Limits.zNat_eq_qPochhammerInf_mul_unboundedGF coercivity hab ha hb
    (finiteSeries_eq_qPochhammer_mul_boundedGF rankOne goodTraverse coercivity shuffle
      epsilonGessel creationExpansion ι hι hab ha hb hqu hΘ hmul),
    Limits.qPochhammerInf_mul_unboundedGF_eq_charge cylindricProduct hab ha hb]

end Evaluation

end HJO.Assembly
