/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.BraidWords
public import Mathlib.GroupTheory.Congruence.Hom
public meta import HJO.Attr

/-! # The braid monoid of the punctured torus

Mellit's `𝔹_k^+(𝕋_0)` (his Theorem 5.1) is the quotient of the free monoid on `T_1, …, T_{k-1}`,
`T̄_1, …, T̄_{k-1}`, `y_1`, `z_1` by nine families of relations. This file builds it, names its
generators, records the braid system it contains, and defines the commuting lifts `ỹ_i`.

## Main definitions

* `HJO.Braid.Letter.InRank` — which letters the `F_k` admits at rank `k`.
* `HJO.Braid.BraidRel`, `HJO.Braid.braidCon`, `HJO.Braid.BraidMonoid` — the relations, the
  congruence they generate, and the quotient: `HJO.Braid.BraidMonoid`.
* `HJO.Braid.braidGenT`, `HJO.Braid.braidGenTinv`, `HJO.Braid.braidGenY`,
  `HJO.Braid.braidGenZ` — the generators `T_i`, `T̄_i`, `y_i`, `z_i`.
* `HJO.Braid.braidYtilde`.

## Main results

* `HJO.Braid.braidMonoid_zero` — `𝔹_0^+(𝕋_0)` is trivial, as `F_0` is.
* `HJO.Braid.monoidHom_ext` — a homomorphism out of the quotient is determined by its values on the
  letters, which is the uniqueness half of "induced by an assignment on the generators".
* `HJO.Braid.isBraidSystem_braidGenT`: the images of the `T_i` form a braid
  system of rank `k`, so the whole train algebra of `HJO.Braid.trainUp` and
  `HJO.Braid.trainDown` applies inside the quotient.
* `HJO.Braid.braidGen_zy` and the other relation lemmas — each family of `HJO.Braid.BraidMonoid` as
  an equation between the named generators.

## Implementation notes

### The alphabet is the whole of `HJO.Braid.Letter`, and the surplus letters are killed

The `F_k` is the free monoid on `2k` symbols when `k ≥ 1` and the trivial monoid at
`k = 0`; `HJO.Braid.Letter` carries `T i` and `T̄ i` for **every** natural `i`, because that is
what `HJO.Braid.yWord` and `HJO.Braid.zWord` are written in. Quotienting the free monoid on the
whole alphabet by the nine families alone would **not** give `𝔹_k^+(𝕋_0)`: no relation mentions a
letter outside the rank, so the result would be the free product of the monoid with a
free monoid on the surplus letters, and `𝔹_0^+(𝕋_0)` would be free of infinite rank rather than
trivial.

So a tenth family is imposed, `HJO.Braid.BraidRel.out_of_rank`: every letter outside the rank is
sent to the identity. Adjoining `b = 1` for each letter `b` of a subalphabet `B` to the free monoid
on `A ⊔ B` gives exactly the free monoid on `A` — the quotient map is surjective and its kernel
congruence is generated by those relations — so `HJO.Braid.BraidMonoid k` is the intended
quotient of the `F_k`, and not a larger monoid. `HJO.Braid.braidMonoid_zero` is the
check at the rank where the difference is loudest, and `HJO.Braid.braidGenT_of_lt` records what the
family does at a surplus letter.

Every relation of the nine families lives in the subalphabet, and so does every word formed
here: `HJO.Braid.yWord i` and `HJO.Braid.zWord i` for `1 ≤ i ≤ k` use only
`T_j`, `T̄_j` with `j ≤ i - 1 ≤ k - 1`, and the trains of `HJO.Braid.braidStep` use only `T_j` with
`j < max(a, a') ≤ k`. So the tenth family never fires on anything a statement reads.

### The relations, and the two that are usually left implicit

`y_{i+1} = T̄_i y_i T̄_i` and `z_{i+1} = T_i z_i T_i` are **not** relations: `HJO.Braid.yWord` and
`HJO.Braid.zWord` are the words those recursions name, so the equations hold in the quotient by
construction (`HJO.Braid.braidGenY_succ`, `HJO.Braid.braidGenZ_succ`), which is the
reading of Mellit's list adopted here.

The bounds are written as `i + 1 ≤ k` for the `i ≤ k - 1` and `i + 2 ≤ k` for
`i ≤ k - 2`, avoiding the truncated subtraction of `ℕ`; they agree with the usual bounds for `k ≥ 1`
and make the families vacuous at `k = 0` under either reading, which is what the `F_0`
needs. Far commutation is imposed once, for `i + 2 ≤ j`, the `|i - j| ≥ 2` adding only
the same equation read backwards; `HJO.Braid.braidGenT_far_comm'` is that reading. The last family
carries the side condition `k ≥ 2`, without which `T_1` is not a symbol of `F_k`.

### `ỹ_i` is a definition and not a theorem

`HJO.Braid.braidYtilde` is displayed as an equation, `ỹ_i = T_{i↘1} T_{1↗k} y_k T_{k↗i}`, but it is
the definition of the symbol `ỹ_i`; here it is a `def`, and `HJO.Braid.braidYtilde_self`
is the boundary case `ỹ_k = T_{k↘1} T_{1↗k} y_k`.

## References

A. Mellit, *Toric braids and `(m, n)`-parking functions*, Theorem 5.1.
-/

@[expose] public section

namespace HJO.Braid

/-! ### The letters of a given rank -/

/-- **The letters of the `F_k`.** At rank `k` the free monoid is on `T_i` and `T̄_i`
for `1 ≤ i ≤ k - 1` together with `y_1` and `z_1` when `k ≥ 1`; the bounds are written additively,
so at `k = 0` no letter is in rank, which is the trivial `F_0`. -/
def Letter.InRank (k : ℕ) : Letter → Prop
  | Letter.T i => 1 ≤ i ∧ i + 1 ≤ k
  | Letter.Tbar i => 1 ≤ i ∧ i + 1 ≤ k
  | Letter.y1 => 1 ≤ k
  | Letter.z1 => 1 ≤ k

instance (k : ℕ) (c : Letter) : Decidable (Letter.InRank k c) := by
  cases c <;> unfold Letter.InRank <;> infer_instance

/-- At rank `0` no letter is in rank: the `F_0` is the trivial monoid. -/
theorem not_inRank_zero (c : Letter) : ¬ Letter.InRank 0 c := by
  cases c <;> simp only [Letter.InRank] <;> omega

/-- At rank `1` the two loops are in rank and no braid letter is: the monoid
`𝔹_1^+(𝕋_0)` is free on `y_1` and `z_1`. -/
theorem inRank_one_iff (c : Letter) : Letter.InRank 1 c ↔ c = Letter.y1 ∨ c = Letter.z1 := by
  cases c <;> simp [Letter.InRank] <;> omega

/-! ### The relations -/

/-- **The nine relation families of `HJO.Braid.BraidMonoid`, together with the trivialisation of the
letters outside the rank.** Mellit's Theorem 5.1, read off the statement: the two cancellations,
the braid relation, far commutation, the `T`-commutation of the `y`- and `z`-words, the internal
commutation of each family, and the one mixed relation
`𝗓_1 T_1 𝗒_1 T̄_1 = T̄_1 𝗒_1 T̄_1 𝗓_1`.

`HJO.Braid.BraidRel.out_of_rank` is not one of Mellit's: it is what cuts the free monoid on the
whole of `HJO.Braid.Letter` down to the `F_k`; see the module docstring. -/
inductive BraidRel (k : ℕ) : FreeMonoid Letter → FreeMonoid Letter → Prop where
  /-- `T_i T̄_i = 1` for `1 ≤ i ≤ k - 1`. -/
  | mul_inv (i : ℕ) (hi : 1 ≤ i) (hik : i + 1 ≤ k) :
      BraidRel k (FreeMonoid.of (Letter.T i) * FreeMonoid.of (Letter.Tbar i)) 1
  /-- `T̄_i T_i = 1` for `1 ≤ i ≤ k - 1`. -/
  | inv_mul (i : ℕ) (hi : 1 ≤ i) (hik : i + 1 ≤ k) :
      BraidRel k (FreeMonoid.of (Letter.Tbar i) * FreeMonoid.of (Letter.T i)) 1
  /-- `T_i T_{i+1} T_i = T_{i+1} T_i T_{i+1}` for `1 ≤ i ≤ k - 2`. -/
  | braid (i : ℕ) (hi : 1 ≤ i) (hik : i + 2 ≤ k) :
      BraidRel k
        (FreeMonoid.of (Letter.T i) * FreeMonoid.of (Letter.T (i + 1)) *
          FreeMonoid.of (Letter.T i))
        (FreeMonoid.of (Letter.T (i + 1)) * FreeMonoid.of (Letter.T i) *
          FreeMonoid.of (Letter.T (i + 1)))
  /-- `T_i T_j = T_j T_i` for `1 ≤ i`, `i + 2 ≤ j` and `j ≤ k - 1`. -/
  | far_comm (i j : ℕ) (hi : 1 ≤ i) (hij : i + 2 ≤ j) (hjk : j + 1 ≤ k) :
      BraidRel k (FreeMonoid.of (Letter.T i) * FreeMonoid.of (Letter.T j))
        (FreeMonoid.of (Letter.T j) * FreeMonoid.of (Letter.T i))
  /-- `𝗒_i T_j = T_j 𝗒_i` for `1 ≤ i ≤ k`, `1 ≤ j ≤ k - 1` and `i ∉ {j, j+1}`. -/
  | yWord_comm_T (i j : ℕ) (hi : 1 ≤ i) (hik : i ≤ k) (hj : 1 ≤ j) (hjk : j + 1 ≤ k)
      (hne : i ≠ j) (hne' : i ≠ j + 1) :
      BraidRel k (yWord i * FreeMonoid.of (Letter.T j)) (FreeMonoid.of (Letter.T j) * yWord i)
  /-- `𝗓_i T_j = T_j 𝗓_i` for `1 ≤ i ≤ k`, `1 ≤ j ≤ k - 1` and `i ∉ {j, j+1}`. -/
  | zWord_comm_T (i j : ℕ) (hi : 1 ≤ i) (hik : i ≤ k) (hj : 1 ≤ j) (hjk : j + 1 ≤ k)
      (hne : i ≠ j) (hne' : i ≠ j + 1) :
      BraidRel k (zWord i * FreeMonoid.of (Letter.T j)) (FreeMonoid.of (Letter.T j) * zWord i)
  /-- `𝗒_i 𝗒_j = 𝗒_j 𝗒_i` for `1 ≤ i, j ≤ k`. -/
  | yWord_comm (i j : ℕ) (hi : 1 ≤ i) (hik : i ≤ k) (hj : 1 ≤ j) (hjk : j ≤ k) :
      BraidRel k (yWord i * yWord j) (yWord j * yWord i)
  /-- `𝗓_i 𝗓_j = 𝗓_j 𝗓_i` for `1 ≤ i, j ≤ k`. -/
  | zWord_comm (i j : ℕ) (hi : 1 ≤ i) (hik : i ≤ k) (hj : 1 ≤ j) (hjk : j ≤ k) :
      BraidRel k (zWord i * zWord j) (zWord j * zWord i)
  /-- `𝗓_1 T_1 𝗒_1 T̄_1 = T̄_1 𝗒_1 T̄_1 𝗓_1`, for `k ≥ 2`. -/
  | zy (hk : 2 ≤ k) :
      BraidRel k
        (zWord 1 * FreeMonoid.of (Letter.T 1) * yWord 1 * FreeMonoid.of (Letter.Tbar 1))
        (FreeMonoid.of (Letter.Tbar 1) * yWord 1 * FreeMonoid.of (Letter.Tbar 1) * zWord 1)
  /-- Every letter outside the rank is the identity: this is what cuts the alphabet down to
  `F_k`, and it is not one of Mellit's relations. -/
  | out_of_rank (c : Letter) (h : ¬ Letter.InRank k c) : BraidRel k (FreeMonoid.of c) 1

/-- The congruence on the free monoid generated by `HJO.Braid.BraidRel`. -/
def braidCon (k : ℕ) : Con (FreeMonoid Letter) := conGen (BraidRel k)

/-- **The braid monoid of the punctured torus.** `HJO.Braid.BraidMonoid`,
`𝔹_k^+(𝕋_0)`: the free monoid on the letters of rank `k` modulo the congruence generated by
Mellit's nine families. -/
@[hjo "def_braid_monoid"]
abbrev BraidMonoid (k : ℕ) : Type := (braidCon k).Quotient

/-- The quotient map of `HJO.Braid.BraidMonoid`, the monoid homomorphism carrying a word to the
element it names. -/
def toBraidMonoid (k : ℕ) : FreeMonoid Letter →* BraidMonoid k := (braidCon k).mk'

/-- Two words related by one of the families name the same element. -/
theorem toBraidMonoid_eq_of_rel {k : ℕ} {x y : FreeMonoid Letter} (h : BraidRel k x y) :
    toBraidMonoid k x = toBraidMonoid k y :=
  (Con.eq (braidCon k)).2 (ConGen.Rel.of _ _ h)

theorem toBraidMonoid_surjective (k : ℕ) : Function.Surjective (toBraidMonoid k) :=
  Con.mk'_surjective

/-- **A homomorphism out of `𝔹_k^+(𝕋_0)` is determined by its values on the letters**, the
quotient map being surjective. This is the uniqueness half of "the homomorphism induced by an
assignment on the generators", which is how `HJO.Sweep.braidRep` and `HJO.Braid.phiPlusStar` name
their maps. -/
theorem monoidHom_ext {k : ℕ} {M : Type*} [Monoid M] {f g : BraidMonoid k →* M}
    (h : ∀ c : Letter,
      f (toBraidMonoid k (FreeMonoid.of c)) = g (toBraidMonoid k (FreeMonoid.of c))) :
    f = g := by
  have hcomp : f.comp (toBraidMonoid k) = g.comp (toBraidMonoid k) := FreeMonoid.hom_eq h
  refine MonoidHom.ext fun x => ?_
  obtain ⟨w, rfl⟩ := toBraidMonoid_surjective k x
  exact DFunLike.congr_fun hcomp w

/-! ### The generators -/

/-- **The generator `T_i`**: the image in `𝔹_k^+(𝕋_0)` of the symbol `T_i`.
Total in `i`, the bound `1 ≤ i ≤ k - 1` being carried by the lemmas; outside it the value is `1`
by `HJO.Braid.braidGenT_of_not_inRank`. -/
@[hjo "def_braid_gens"]
def braidGenT (k i : ℕ) : BraidMonoid k := toBraidMonoid k (FreeMonoid.of (Letter.T i))

/-- **The generator `T̄_i`**: the image of the symbol `T̄_i`, which the
relations make a two-sided inverse of `HJO.Braid.braidGenT`. -/
@[hjo "def_braid_gens"]
def braidGenTinv (k i : ℕ) : BraidMonoid k := toBraidMonoid k (FreeMonoid.of (Letter.Tbar i))

/-- **The generator `y_i`**: the image of the word `𝗒_i` of
`HJO.Braid.yWord`. -/
@[hjo "def_braid_gens"]
def braidGenY (k i : ℕ) : BraidMonoid k := toBraidMonoid k (yWord i)

/-- **The generator `z_i`**: the image of the word `𝗓_i` of
`HJO.Braid.zWord`. -/
@[hjo "def_braid_gens"]
def braidGenZ (k i : ℕ) : BraidMonoid k := toBraidMonoid k (zWord i)

/-- A letter outside the rank names the identity. -/
theorem braidGenT_of_not_inRank {k i : ℕ} (h : ¬ Letter.InRank k (Letter.T i)) :
    braidGenT k i = 1 := by
  rw [braidGenT, toBraidMonoid_eq_of_rel (BraidRel.out_of_rank _ h), map_one]

theorem braidGenTinv_of_not_inRank {k i : ℕ} (h : ¬ Letter.InRank k (Letter.Tbar i)) :
    braidGenTinv k i = 1 := by
  rw [braidGenTinv, toBraidMonoid_eq_of_rel (BraidRel.out_of_rank _ h), map_one]

/-- The braid letters above the rank are trivial: `T_i = 1` unless `1 ≤ i ≤ k - 1`. -/
theorem braidGenT_of_lt {k i : ℕ} (h : k < i + 1) : braidGenT k i = 1 :=
  braidGenT_of_not_inRank (by simp only [Letter.InRank]; omega)

/-- **`𝔹_0^+(𝕋_0)` is trivial**, which is the `F_0` and the rank the tenth family of
`HJO.Braid.BraidRel` exists for: every letter is out of rank at `k = 0`, so every word names the
identity. -/
theorem braidMonoid_zero (x : BraidMonoid 0) : x = 1 := by
  obtain ⟨w, rfl⟩ := toBraidMonoid_surjective 0 x
  induction w using FreeMonoid.inductionOn' with
  | one => exact map_one _
  | of_mul c w ih =>
    rw [map_mul, ih, mul_one,
      toBraidMonoid_eq_of_rel (BraidRel.out_of_rank c (not_inRank_zero c)), map_one]

/-- `y_1` is the image of the letter `y_1`: the base of `HJO.Braid.yWord`. -/
theorem braidGenY_one (k : ℕ) : braidGenY k 1 = toBraidMonoid k (FreeMonoid.of Letter.y1) := rfl

/-- `z_1` is the image of the letter `z_1`. -/
theorem braidGenZ_one (k : ℕ) : braidGenZ k 1 = toBraidMonoid k (FreeMonoid.of Letter.z1) := rfl

/-- **`y_{i+1} = T̄_i y_i T̄_i` holds in the quotient by construction**, which is why Mellit's list
does not carry it: it is what `HJO.Braid.yWord` uses to name the word. -/
theorem braidGenY_succ (k i : ℕ) :
    braidGenY k (i + 2)
      = braidGenTinv k (i + 1) * braidGenY k (i + 1) * braidGenTinv k (i + 1) := by
  rw [braidGenY, yWord_succ, map_mul, map_mul]
  rfl

/-- **`z_{i+1} = T_i z_i T_i` holds in the quotient by construction.** -/
theorem braidGenZ_succ (k i : ℕ) :
    braidGenZ k (i + 2) = braidGenT k (i + 1) * braidGenZ k (i + 1) * braidGenT k (i + 1) := by
  rw [braidGenZ, zWord_succ, map_mul, map_mul]
  rfl

/-! ### The relations, read on the generators -/

theorem braidGenT_mul_inv {k i : ℕ} (hi : 1 ≤ i) (hik : i + 1 ≤ k) :
    braidGenT k i * braidGenTinv k i = 1 := by
  rw [braidGenT, braidGenTinv, ← map_mul,
    toBraidMonoid_eq_of_rel (BraidRel.mul_inv i hi hik), map_one]

theorem braidGenT_inv_mul {k i : ℕ} (hi : 1 ≤ i) (hik : i + 1 ≤ k) :
    braidGenTinv k i * braidGenT k i = 1 := by
  rw [braidGenT, braidGenTinv, ← map_mul,
    toBraidMonoid_eq_of_rel (BraidRel.inv_mul i hi hik), map_one]

theorem braidGenT_braid {k i : ℕ} (hi : 1 ≤ i) (hik : i + 2 ≤ k) :
    braidGenT k i * braidGenT k (i + 1) * braidGenT k i
      = braidGenT k (i + 1) * braidGenT k i * braidGenT k (i + 1) := by
  simp only [braidGenT, ← map_mul]
  exact toBraidMonoid_eq_of_rel (BraidRel.braid i hi hik)

theorem braidGenT_far_comm {k i j : ℕ} (hi : 1 ≤ i) (hij : i + 2 ≤ j) (hjk : j + 1 ≤ k) :
    braidGenT k i * braidGenT k j = braidGenT k j * braidGenT k i := by
  simp only [braidGenT, ← map_mul]
  exact toBraidMonoid_eq_of_rel (BraidRel.far_comm i j hi hij hjk)

/-- The `|i - j| ≥ 2` read the other way round, which adds no relation. -/
theorem braidGenT_far_comm' {k i j : ℕ} (hj : 1 ≤ j) (hij : j + 2 ≤ i) (hik : i + 1 ≤ k) :
    braidGenT k i * braidGenT k j = braidGenT k j * braidGenT k i :=
  (braidGenT_far_comm hj hij hik).symm

theorem braidGenY_comm_T {k i j : ℕ} (hi : 1 ≤ i) (hik : i ≤ k) (hj : 1 ≤ j) (hjk : j + 1 ≤ k)
    (hne : i ≠ j) (hne' : i ≠ j + 1) :
    braidGenY k i * braidGenT k j = braidGenT k j * braidGenY k i := by
  simp only [braidGenY, braidGenT, ← map_mul]
  exact toBraidMonoid_eq_of_rel (BraidRel.yWord_comm_T i j hi hik hj hjk hne hne')

theorem braidGenZ_comm_T {k i j : ℕ} (hi : 1 ≤ i) (hik : i ≤ k) (hj : 1 ≤ j) (hjk : j + 1 ≤ k)
    (hne : i ≠ j) (hne' : i ≠ j + 1) :
    braidGenZ k i * braidGenT k j = braidGenT k j * braidGenZ k i := by
  simp only [braidGenZ, braidGenT, ← map_mul]
  exact toBraidMonoid_eq_of_rel (BraidRel.zWord_comm_T i j hi hik hj hjk hne hne')

theorem braidGenY_comm {k i j : ℕ} (hi : 1 ≤ i) (hik : i ≤ k) (hj : 1 ≤ j) (hjk : j ≤ k) :
    braidGenY k i * braidGenY k j = braidGenY k j * braidGenY k i := by
  simp only [braidGenY, ← map_mul]
  exact toBraidMonoid_eq_of_rel (BraidRel.yWord_comm i j hi hik hj hjk)

theorem braidGenZ_comm {k i j : ℕ} (hi : 1 ≤ i) (hik : i ≤ k) (hj : 1 ≤ j) (hjk : j ≤ k) :
    braidGenZ k i * braidGenZ k j = braidGenZ k j * braidGenZ k i := by
  simp only [braidGenZ, ← map_mul]
  exact toBraidMonoid_eq_of_rel (BraidRel.zWord_comm i j hi hik hj hjk)

/-- **The one mixed relation**, Mellit's `z_1 T_1 y_1 T_1^{-1} = T_1^{-1} y_1 T_1^{-1} z_1` with
`T̄_1` written for `T_1^{-1}`. It names `T_1`, so it is imposed only for `k ≥ 2`. -/
theorem braidGen_zy {k : ℕ} (hk : 2 ≤ k) :
    braidGenZ k 1 * braidGenT k 1 * braidGenY k 1 * braidGenTinv k 1
      = braidGenTinv k 1 * braidGenY k 1 * braidGenTinv k 1 * braidGenZ k 1 := by
  simp only [braidGenZ, braidGenY, braidGenT, braidGenTinv, ← map_mul]
  exact toBraidMonoid_eq_of_rel (BraidRel.zy hk)

/-! ### The braid system inside the quotient -/

/-- **The images of the `T_i` form a braid system of rank `k`.** The first
family of `HJO.Braid.BraidMonoid` makes `T̄_i` a two-sided inverse of `T_i`, and the second and
third are the two conditions of `HJO.Braid.IsBraidSystem` verbatim. This is what puts the whole
train algebra of `HJO.Braid.trainUp` and `HJO.Braid.trainDown` at the disposal of
`HJO.Braid.braidStep`. -/
@[hjo "lem_braid_system"]
theorem isBraidSystem_braidGenT (k : ℕ) : IsBraidSystem k (braidGenT k) (braidGenTinv k) where
  mul_inv _i hi hik := braidGenT_mul_inv hi hik
  inv_mul _i hi hik := braidGenT_inv_mul hi hik
  braid _i hi hik := braidGenT_braid hi hik
  far_comm _i _j hi hij hjk := braidGenT_far_comm hi hij hjk

/-- The ascending train `T_{a↗b}` of `HJO.Braid.trainUp`, formed inside `𝔹_k^+(𝕋_0)`. -/
abbrev braidTrainUp (k a b : ℕ) : BraidMonoid k := trainUp (braidGenT k) (braidGenTinv k) a b

/-- The descending train `T_{a↘b}` of `HJO.Braid.trainDown`, formed inside `𝔹_k^+(𝕋_0)`. -/
abbrev braidTrainDown (k a b : ℕ) : BraidMonoid k := trainDown (braidGenT k) (braidGenTinv k) a b

@[simp]
theorem braidTrainUp_self (k a : ℕ) : braidTrainUp k a a = 1 := trainUp_self _ _ _

@[simp]
theorem braidTrainDown_self (k a : ℕ) : braidTrainDown k a a = 1 := trainDown_self _ _ _

/-! ### The commuting lifts -/

/-- **The commuting lift `ỹ_i`**:
`ỹ_i = T_{i↘1} T_{1↗k} y_k T_{k↗i}` in `𝔹_k^+(𝕋_0)`, the trains being formed from the images of
`HJO.Braid.braidGenT`.

Total in `i`, the `1 ≤ i ≤ k` being carried by the lemmas; the trains are words and
need no side condition to be formed. -/
@[hjo "def_braid_ytilde"]
def braidYtilde (k i : ℕ) : BraidMonoid k :=
  braidTrainDown k i 1 * braidTrainUp k 1 k * braidGenY k k * braidTrainUp k k i

/-- At the top index both outer trains are empty on one side: `ỹ_k = T_{k↘1} T_{1↗k} y_k`. -/
theorem braidYtilde_self (k : ℕ) :
    braidYtilde k k = braidTrainDown k k 1 * braidTrainUp k 1 k * braidGenY k k := by
  rw [braidYtilde, braidTrainUp_self, mul_one]

/-- At rank `1` there are no braid letters, every train is empty, and `ỹ_1 = y_1`. -/
theorem braidYtilde_one_one : braidYtilde 1 1 = braidGenY 1 1 := by
  simp [braidYtilde]

end HJO.Braid
