/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitNablaPrime

/-! # The operator form of the left-hand-side clause

`HJO.Mellit.lhsRewrite_sweepWitness` (`HJO.Mellit.LhsWord`) is a statement about vectors: the slope
operator side `Θ(C_α 1)` and the stage word, both applied to the vacuum. Mellit's argument (§3.7
of *Toric braids and (m,n)-parking functions*) runs through the `SL_2(ℤ)_+` monoid generated by `N`
and `S`, and the `S`-step (`τ^*τ`) does not preserve evaluation at `1`: `τ^*τ 1 = Exp[-X/M] ≠ 1`. So
the clause is carried at the level of operators on `Λ`.

## Main definitions

* `HJO.Mellit.LhsDesign.stageFromEnd`: the stage word `G_ℓ ⋯ G_{k+1}` as an endomorphism.
* `HJO.Mellit.LhsDesign.lhsOp`: `f ↦ ct(d_-^ℓ G_ℓ ⋯ G_1(Cf))`, the right-hand side as an operator.
* `HJO.Mellit.LhsDesign.OpClause`: the clause in `End(Λ)`.

## Main results

* `HJO.Mellit.LhsDesign.lhsOp_apply_one`: at `f = 1`, `lhsOp` is the right-hand side of
  `HJO.Mellit.LhsWord`.
* `HJO.Mellit.LhsDesign.lhsWord_of_opClause`: the operator clause gives the vector clause.
* `HJO.Sweep.lowerRun_mem_piece_zero`, `HJO.Sweep.stageFromEnd_mem_piece`: the lowering run lands
  in `V_0`, and the stage word raises the grading by the length of the composition.
-/

@[expose] public section

namespace HJO.Mellit.LhsDesign

open HJO.Sym HJO.Sweep HJO.Ascent MvPolynomial

/-! ### The operator form of the right-hand side -/

section Defs

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- The stage word `G_ℓ ⋯ G_{k+1}` from grading `k`, as an endomorphism of the total space
(`HJO.Mellit.stageFromTotal` read as a linear map). -/
noncomputable def stageFromEnd (q u : L) (a b : ℕ) : ℕ → List ℕ → Module.End L (Total L)
  | _, [] => 1
  | k, A :: α => stageFromEnd q u a b (k + 1) α * stageTotal q u a b k A

/-- Applying `stageFromEnd q u a b k α` to `F` is `HJO.Mellit.stageFromTotal q u a b k F α`. -/
theorem stageFromEnd_apply (q u : L) (a b : ℕ) (α : List ℕ) :
    ∀ (k : ℕ) (F : Total L), stageFromEnd q u a b k α F = stageFromTotal q u a b k F α := by
  induction α with
  | nil => intro k F; rfl
  | cons A α ih =>
    intro k F
    rw [stageFromEnd, Module.End.mul_apply, ih, stageFromTotal]

/-- **The right-hand side of the clause as an operator on `Λ`**:
`lhsOp a b α f = ct(d_-^ℓ (G_ℓ ⋯ G_1 (C f)))`. -/
noncomputable def lhsOp (q u : L) (a b : ℕ) (α : List ℕ) : Module.End L (Sym.Lambda L) :=
  constantCoeffLin ∘ₗ (lowerRun q α.length * stageFromEnd q u a b 0 α) ∘ₗ constLin

/-- `lhsOp q u a b α f` is the constant coefficient of the lowering run applied to the stage word
applied to `C f`. -/
theorem lhsOp_apply (q u : L) (a b : ℕ) (α : List ℕ) (f : Sym.Lambda L) :
    lhsOp q u a b α f
      = constantCoeff (lowerRun q α.length (stageFromTotal q u a b 0 (C f) α)) := by
  change constantCoeff ((lowerRun q α.length * stageFromEnd q u a b 0 α) (C f)) = _
  rw [Module.End.mul_apply, stageFromEnd_apply]

/-- At `f = 1`, `lhsOp q u a b α` evaluates to `ct(d_-^ℓ G_ℓ ⋯ G_1 1)`, the right-hand side of
`HJO.Mellit.LhsWord`. -/
theorem lhsOp_apply_one (q u : L) (a b : ℕ) (α : List ℕ) :
    lhsOp q u a b α 1 = constantCoeff (lowerRun q α.length (stageWordTotal q u a b α)) := by
  rw [lhsOp_apply, map_one, stageWordTotal]

/-- **The operator clause** at `(a,b)`: for every slope homomorphism and every composition,
`(-1)^{N(b+1)} Θ(C_α 1) = (-1)^{(a-1)N} q^{ℓ-N} · lhsOp a b α` in `End(Λ)`. -/
def OpClause (q u : L) (a b : ℕ) : Prop :=
  ∀ Θ : Sym.Lambda L →ₐ[L] Module.End L (Sym.Lambda L), IsSlopeHom a b q u Θ →
    ∀ N : ℕ, 0 < N → ∀ α : List ℕ, (∀ x ∈ α, 0 < x) → α.sum = N →
      (-1 : L) ^ (N * (b + 1)) • Θ (CopComp q α 1)
        = ((-1 : L) ^ ((a - 1) * N) * q ^ ((α.length : ℤ) - (N : ℤ))) • lhsOp q u a b α

/-- The operator clause gives the clause at the vacuum. -/
theorem lhsWord_of_opClause {q u : L} {a b : ℕ} (h : OpClause q u a b) : LhsWord q u a b := by
  intro Θ hΘ N hN α hpos hsum
  have := LinearMap.congr_fun (h Θ hΘ N hN α hpos hsum) 1
  rw [LinearMap.smul_apply, LinearMap.smul_apply, lhsOp_apply_one] at this
  exact this

end Defs

end HJO.Mellit.LhsDesign

namespace HJO.Sweep

open HJO.Mellit HJO.Mellit.LhsDesign

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- The image of the lowering run of a vector of `V_ℓ` lies in `V_0`. -/
theorem lowerRun_mem_piece_zero (q : L) :
    ∀ (l : ℕ) {G : Total L}, G ∈ piece L l → lowerRun q l G ∈ piece L 0 := by
  intro l
  induction l with
  | zero => intro G hG; simpa [lowerRun] using hG
  | succ l ih =>
    intro G hG
    rw [lowerRun, Module.End.mul_apply]
    exact ih (by simpa using dminus_mem_piece q (l + 1) hG)

/-- The stage word from the grading `k` raises the grading by the length of the composition. -/
theorem stageFromEnd_mem_piece (q u : L) (a b : ℕ) :
    ∀ (α : List ℕ) (k : ℕ) {F : Total L}, F ∈ piece L k →
      stageFromEnd q u a b k α F ∈ piece L (k + α.length) := by
  intro α
  induction α with
  | nil => intro k F hF; simpa [stageFromEnd] using hF
  | cons A α ih =>
    intro k F hF
    rw [stageFromEnd, Module.End.mul_apply, List.length_cons,
      show k + (α.length + 1) = k + 1 + α.length from by omega]
    exact ih (k + 1) (stageTotal_mem_piece q u a b k A hF)

end HJO.Sweep
