/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.LhsAscent

/-! # Slope homomorphisms under the two Euclidean steps, at the standing field

The operator form of `HJO.Mellit.lhsRewrite_sweepWitness` runs along Euclid's algorithm on the slope
`(a, b)`, starting at `(1, 1)` and using the steps `N : (m, n) ↦ (m + n, n)` and
`S : (m, n) ↦ (m, n + m)`. This file supplies the side of that induction that lives on `Λ`, at the
standing field `𝕜 = ℚ(q, u)`:

* a slope homomorphism `Θ` exists at every positive coprime slope, because the collinear slope
  operators `Q_{ka,kb}` commute;
* a slope homomorphism at `(m + n, n)` is the `∇`-conjugate of one at `(m, n)`, since conjugation
  by `∇` carries `Q_{m,n}` to `Q_{m+n,n}` and slope homomorphisms are unique;
* at `(1, 1)` a slope homomorphism is the `∇`-conjugate of multiplication, since `Q_{k,k}` is the
  `∇`-conjugate of multiplication by the axis generator `U_k`;
* for `g ∈ Λ_N`, `τ^*τ` transports `(-1)^{mN} Θ'(g)` along `Θ(g)`, for `Θ` at `(m, n)` and `Θ'`
  at `(m, n + m)`. Here `Θ(g)` lies in the bidegree-`(mN, nN)` part of the algebra `𝖠` generated by
  the basic operators, an index shift `𝖲` carries it to `Θ'(g)`, and Mellit's transport identity
  `τ^*τ ∘ ((-1)^{mN} 𝖲 E) = Ê ∘ τ^*τ` on that part applies.

The bigrading of the slope operators, `Q_{m,n} ∈ 𝖠_{(m,n)}`, is proved here along the recursion
`Q_{m,n} = M⁻¹(Q_{m-r,n-s} Q_{r,s} - Q_{r,s} Q_{m-r,n-s})`.

## Main results

* `HJO.Sym.qop_mem_dopGenSpanBi`: `Q_{m,n}` lies in the bidegree-`(m, n)` part of `𝖠`.
* `HJO.Mellit.LhsDesign.exists_slopeHom`: slope homomorphisms exist at every positive coprime
  slope.
* `HJO.Mellit.LhsDesign.exists_nabla`: the Macdonald conjugator normalised by `∇1 = 1`.
* `HJO.Mellit.LhsDesign.theta_add_left`: the `N`-step on slope homomorphisms.
* `HJO.Mellit.LhsDesign.theta_add_self_nsTransports`: the `S`-step on slope homomorphisms.
* `HJO.Mellit.LhsDesign.theta_one_one`: the base slope.

## References

* [A. Mellit, *Toric braids and (m,n)-parking functions*][mellit2016], Sections 3.6–3.7.
-/

@[expose] public section

namespace HJO.Sym

variable {K : Type*} [Field K] [Algebra ℚ K]

/-! ### The bigrading of `𝖠` is multiplicative, and the slope operators are bihomogeneous -/

/-- The basic-operator word of a concatenation is the product of the words. -/
theorem dopGenWord_append (q u : K) (ns ns' : List ℕ) :
    dopGenWord q u (ns ++ ns') = dopGenWord q u ns * dopGenWord q u ns' := by
  simp [dopGenWord, List.map_append, List.prod_append]

/-- The identity lies in the bidegree-`(0, 0)` part of `𝖠`. -/
theorem one_mem_dopGenSpanBi (q u : K) : (1 : DopAlgebra q u) ∈ dopGenSpanBi q u 0 0 := by
  have h := dopGenWord_mem_dopGenSpanBi q u []
  simpa [dopGenWord] using h

/-- **The bigrading of `𝖠` is multiplicative**: concatenating words adds both the number of
letters and the sum of the indices. -/
theorem mul_mem_dopGenSpanBi {q u : K} {a c a' c' : ℕ} {x y : DopAlgebra q u}
    (hx : x ∈ dopGenSpanBi q u a c) (hy : y ∈ dopGenSpanBi q u a' c') :
    x * y ∈ dopGenSpanBi q u (a + a') (c + c') := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨ns, hlen, hsum, rfl⟩ := hx
    induction hy using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨ns', hlen', hsum', rfl⟩ := hy
      rw [← dopGenWord_append]
      exact Submodule.subset_span ⟨ns ++ ns', by simp [hlen, hlen'], by simp [hsum, hsum'], rfl⟩
    | zero => rw [mul_zero]; exact Submodule.zero_mem _
    | add y y' _ _ h h' => rw [mul_add]; exact Submodule.add_mem _ h h'
    | smul r y _ h => rw [mul_smul_comm]; exact Submodule.smul_mem _ r h
  | zero => rw [zero_mul]; exact Submodule.zero_mem _
  | add x x' _ _ h h' => rw [add_mul]; exact Submodule.add_mem _ h h'
  | smul r x _ h => rw [smul_mul_assoc]; exact Submodule.smul_mem _ r h

/-- **The slope operators are bihomogeneous**: for `m ≥ 1` and `n ≥ 0` with `n ≥ 1` or `m = 1`,
`Q_{m,n}` lies in the bidegree-`(m, n)` part of `𝖠`. -/
theorem qop_mem_dopGenSpanBi (q u : K) : ∀ m : ℕ, ∀ hm : 0 < m, ∀ n : ℕ, ∀ hn : (0 < n ∨ m = 1),
    (⟨Qop q u m n, qop_mem_dopAlgebra q u m hm n hn⟩ : DopAlgebra q u) ∈ dopGenSpanBi q u m n := by
  intro m
  induction m using Nat.strong_induction_on with
  | _ m ih =>
    intro hm n hn
    rcases Nat.lt_or_ge m 2 with h1 | h1
    · have hm1 : m = 1 := by omega
      subst hm1
      have hx : (⟨Qop q u 1 n, qop_mem_dopAlgebra q u 1 hm n hn⟩ : DopAlgebra q u)
          = dopGen q u n := Subtype.ext (by change Qop q u 1 n = Dop q u n; rw [qop_one])
      rw [hx]
      exact dopGen_mem_dopGenSpanBi q u n
    · have hm1 : 1 < m := by omega
      have hn1 : 0 < n := by omega
      obtain ⟨hr1, hrm⟩ := one_le_slopeSplit_fst_lt hm1 hn1
      have he := one_le_sub_slopeSplit_snd hm1 hn1
      have hsn : (slopeSplit m n).2 < n := by omega
      have hn2 : 0 < (slopeSplit m n).2 ∨ (slopeSplit m n).1 = 1 := by
        rcases Nat.eq_zero_or_pos (slopeSplit m n).2 with hs | hs
        · exact Or.inr (slopeSplit_fst_eq_one hm1 hn1 hs)
        · exact Or.inl hs
      have hz := ih _ hrm hr1 _ hn2
      have hy := ih (m - (slopeSplit m n).1) (by omega) (by omega) (n - (slopeSplit m n).2)
        (Or.inl (by omega))
      set y : DopAlgebra q u := ⟨_, qop_mem_dopAlgebra q u (m - (slopeSplit m n).1) (by omega)
        (n - (slopeSplit m n).2) (Or.inl (by omega))⟩
      set z : DopAlgebra q u := ⟨_, qop_mem_dopAlgebra q u _ hr1 _ hn2⟩
      have hxeq : (⟨Qop q u m n, qop_mem_dopAlgebra q u m hm n hn⟩ : DopAlgebra q u)
          = ((1 - q) * (1 - u))⁻¹ • (y * z - z * y) :=
        Subtype.ext (by change Qop q u m n = _; rw [qop_rec q u hm1 hn1]; rfl)
      have hyz := mul_mem_dopGenSpanBi hy hz
      have hzy := mul_mem_dopGenSpanBi hz hy
      rw [show m - (slopeSplit m n).1 + (slopeSplit m n).1 = m by omega,
        show n - (slopeSplit m n).2 + (slopeSplit m n).2 = n by omega] at hyz
      rw [show (slopeSplit m n).1 + (m - (slopeSplit m n).1) = m by omega,
        show (slopeSplit m n).2 + (n - (slopeSplit m n).2) = n by omega] at hzy
      rw [hxeq]
      exact Submodule.smul_mem _ _ (Submodule.sub_mem _ hyz hzy)

end HJO.Sym

namespace HJO.Mellit.LhsDesign

open HJO.Sym HJO.Sweep HJO.Ascent MvPolynomial

variable (K : Type*) [Field K] [Algebra ParamRing K] [IsFractionRing ParamRing K] [Algebra ℚ K]

local notation "𝗊" => paramQ K
local notation "𝗎" => paramU K

/-- **A slope homomorphism exists at every positive coprime slope**: for coprime `a, b ≥ 1` there
is a slope homomorphism `Θ` at `(a, b)` over `K`. -/
theorem exists_slopeHom (a b : ℕ) (hab : Nat.Coprime a b) (ha : 1 ≤ a) (hb : 1 ≤ b) :
    ∃ Θ : Sym.Lambda K →ₐ[K] Module.End K (Sym.Lambda K), IsSlopeHom a b 𝗊 𝗎 Θ := by
  have := HJO.Ascent.charZero_of_algebra_rat K
  have hA := isAdmissible_standing K
  have hv0 : 𝗊 * 𝗎 ≠ 0 := mul_ne_zero hA.fst_ne_zero hA.snd_ne_zero
  have hv1 : 𝗊 * 𝗎 ≠ 1 := by simpa using hA.mul_pow_succ_ne_one 0
  obtain ⟨nabla, hnab, -⟩ := exists_isMacdonaldConjugator_one_param K
  refine HJO.Sym.exists_isSlopeHom hv0 hA.mul_pow_succ_ne_one fun k l hk hl => ?_
  have h := collinear_commute_of_diag hA.mparam_ne_zero ⟨nabla, hnab⟩
    (HJO.Bglx.exists_isIndexShift_param K)
    (fun k l hk hl => qop_diag_commute hA.mparam_ne_zero hv0 hv1 ⟨nabla, hnab⟩ hk hl)
    a b hab ha hb k l hk hl
  rwa [mul_comm k a, mul_comm k b, mul_comm l a, mul_comm l b] at h

/-- **The normalised Macdonald conjugator exists**, `∇1 = 1`. -/
theorem exists_nabla :
    ∃ nabla : Module.End K (Sym.Lambda K), IsMacdonaldConjugator 𝗊 𝗎 nabla ∧ nabla 1 = 1 :=
  exists_isMacdonaldConjugator_one_param K

/-- **`N` on slope homomorphisms**: a slope homomorphism at `(m+n,n)` is the `∇`-conjugate of
one at `(m,n)`. -/
theorem theta_add_left {nabla : Module.End K (Sym.Lambda K)}
    (hnab : IsMacdonaldConjugator 𝗊 𝗎 nabla) {m n : ℕ} (hm : 1 ≤ m) (hn : 1 ≤ n)
    {Θ Θ' : Sym.Lambda K →ₐ[K] Module.End K (Sym.Lambda K)}
    (hΘ : IsSlopeHom m n 𝗊 𝗎 Θ) (hΘ' : IsSlopeHom (m + n) n 𝗊 𝗎 Θ') (g f : Sym.Lambda K) :
    Θ' g (nabla f) = nabla (Θ g f) := by
  have := HJO.Ascent.charZero_of_algebra_rat K
  have hA := isAdmissible_standing K
  have hv0 : 𝗊 * 𝗎 ≠ 0 := mul_ne_zero hA.fst_ne_zero hA.snd_ne_zero
  set e := LinearEquiv.ofBijective nabla hnab.bijective with he
  have hΘc : IsSlopeHom (m + n) n 𝗊 𝗎 ((e.conjAlgEquiv K).toAlgHom.comp Θ) := by
    intro k hk
    refine LinearMap.ext fun x => ?_
    rw [AlgHom.comp_apply, hΘ k hk]
    change (e.conjAlgEquiv K) (Qop 𝗊 𝗎 (m * k) (n * k)) x = _
    rw [LinearEquiv.conjAlgEquiv_apply, add_mul,
      qop_conj_up hnab hA.mparam_ne_zero (Nat.mul_pos hm hk) (Nat.mul_pos hn hk) x]
    rfl
  rw [isSlopeHom_unique hv0 hA.mul_pow_succ_ne_one hΘ' hΘc, AlgHom.comp_apply]
  change (e.conjAlgEquiv K) (Θ g) (nabla f) = _
  rw [LinearEquiv.conjAlgEquiv_apply]
  change e (Θ g (e.symm (e f))) = nabla (Θ g f)
  rw [LinearEquiv.symm_apply_apply]
  rfl

/-- **The base slope on `Λ`**: a slope homomorphism at `(1,1)` is the `∇`-conjugate of
multiplication. -/
theorem theta_one_one {nabla : Module.End K (Sym.Lambda K)}
    (hnab : IsMacdonaldConjugator 𝗊 𝗎 nabla)
    {Θ : Sym.Lambda K →ₐ[K] Module.End K (Sym.Lambda K)} (hΘ : IsSlopeHom 1 1 𝗊 𝗎 Θ)
    (g f : Sym.Lambda K) :
    Θ g (nabla f) = nabla (g * f) := by
  have := HJO.Ascent.charZero_of_algebra_rat K
  have hA := isAdmissible_standing K
  have hv0 : 𝗊 * 𝗎 ≠ 0 := mul_ne_zero hA.fst_ne_zero hA.snd_ne_zero
  have hv1 : 𝗊 * 𝗎 ≠ 1 := by simpa using hA.mul_pow_succ_ne_one 0
  set e := LinearEquiv.ofBijective nabla hnab.bijective with he
  have hΘc : IsSlopeHom 1 1 𝗊 𝗎
      ((e.conjAlgEquiv K).toAlgHom.comp (Algebra.lmul K (Sym.Lambda K))) := by
    intro k hk
    refine LinearMap.ext fun x => ?_
    rw [AlgHom.comp_apply]
    change (e.conjAlgEquiv K) (Algebra.lmul K (Sym.Lambda K) (axisGen (𝗊 * 𝗎) k)) x = _
    rw [LinearEquiv.conjAlgEquiv_apply, one_mul,
      qop_diag_conj hnab hA.mparam_ne_zero hv0 hv1 hk x]
    rfl
  rw [isSlopeHom_unique hv0 hA.mul_pow_succ_ne_one hΘ hΘc, AlgHom.comp_apply]
  change (e.conjAlgEquiv K) (Algebra.lmul K (Sym.Lambda K) g) (nabla f) = _
  rw [LinearEquiv.conjAlgEquiv_apply]
  change e (g * e.symm (e f)) = nabla (g * f)
  rw [LinearEquiv.symm_apply_apply]
  rfl

omit [Algebra ℚ K] in
/-- For `k ≥ 1`, the factor `(1 - q^k)(1 - u^k)` is nonzero in `K`. -/
theorem one_sub_pow_mul_one_sub_pow_ne_zero (k : ℕ) (hk : 1 ≤ k) :
    (1 - (𝗊 : K) ^ k) * (1 - (𝗎 : K) ^ k) ≠ 0 := by
  obtain ⟨j, rfl⟩ : ∃ j, k = j + 1 := ⟨k - 1, by omega⟩
  exact mul_ne_zero (sub_ne_zero.2 (HJO.Standing.paramQ_pow_succ_ne_one K j).symm)
    (sub_ne_zero.2 (HJO.Standing.paramU_pow_succ_ne_one K j).symm)

/-- **`S` on slope homomorphisms, through `τ^*τ`**: for `g ∈ Λ_N`, `τ^*τ` transports
`(-1)^{mN}Θ'(g)` along `Θ(g)`, for `Θ` at `(m,n)` and `Θ'` at `(m,n+m)`. -/
theorem theta_add_self_nsTransports {m n : ℕ} (hm : 1 ≤ m) (hn : 1 ≤ n)
    {Θ Θ' : Sym.Lambda K →ₐ[K] Module.End K (Sym.Lambda K)}
    (hΘ : IsSlopeHom m n 𝗊 𝗎 Θ) (hΘ' : IsSlopeHom m (n + m) 𝗊 𝗎 Θ') {N : ℕ} {g : Sym.Lambda K}
    (hg : g ∈ LambdaComp K N) (hD : ShiftsDegree ((n : ℤ) * N) (Θ g)) :
    NsTransports 𝗊 𝗎 hD (((-1 : K) ^ (m * N)) • Θ' g) := by
  have := HJO.Ascent.charZero_of_algebra_rat K
  have hA := isAdmissible_standing K
  have hv0 : 𝗊 * 𝗎 ≠ 0 := mul_ne_zero hA.fst_ne_zero hA.snd_ne_zero
  obtain ⟨S, hS⟩ := HJO.Bglx.exists_isIndexShift_param K
  have hmem : ∀ i : ℕ, Qop 𝗊 𝗎 (m * (i + 1)) (n * (i + 1)) ∈ DopAlgebra 𝗊 𝗎 := fun i =>
    qop_mem_dopAlgebra _ _ _ (Nat.mul_pos hm (Nat.succ_pos i)) _
      (Or.inl (Nat.mul_pos hn (Nat.succ_pos i)))
  let T : ℕ → DopAlgebra 𝗊 𝗎 := fun i => ⟨_, hmem i⟩
  have hT : ∀ i, (T i : Module.End K (Sym.Lambda K)) = Θ (axisGen (𝗊 * 𝗎) (i + 1)) :=
    fun i => (hΘ (i + 1) (Nat.succ_pos i)).symm
  obtain ⟨Ψ, hΨ⟩ := exists_algHom_of_commute (L := K) T fun i j => Subtype.ext (by
    change (T i : Module.End K (Sym.Lambda K)) * T j = T j * T i
    rw [hT, hT, ← map_mul, ← map_mul, mul_comm])
  have h1 : (DopAlgebra 𝗊 𝗎).val.comp Ψ = Θ.comp (axisSub (𝗊 * 𝗎)) :=
    MvPolynomial.algHom_ext fun i => by
      rw [AlgHom.comp_apply, AlgHom.comp_apply, hΨ, axisSub_X, Subalgebra.coe_val, hT]
  have h2 : (DopAlgebra 𝗊 𝗎).val.comp (S.comp Ψ) = Θ'.comp (axisSub (𝗊 * 𝗎)) :=
    MvPolynomial.algHom_ext fun i => by
      rw [AlgHom.comp_apply, AlgHom.comp_apply, AlgHom.comp_apply, hΨ, axisSub_X,
        Subalgebra.coe_val, hΘ' (i + 1) (Nat.succ_pos i)]
      have h := qop_shift_right hS (Nat.mul_pos hm (Nat.succ_pos i))
        (n := n * (i + 1)) (Or.inl (Nat.mul_pos hn (Nat.succ_pos i)))
      rwa [show n * (i + 1) + m * (i + 1) = (n + m) * (i + 1) by ring] at h
  obtain ⟨g', hg', rfl⟩ := exists_mem_lambdaComp_axisSub_eq hv0 hA.mul_pow_succ_ne_one N hg
  let G : ℤ → Submodule K (DopAlgebra 𝗊 𝗎) := fun c =>
    if c < 0 then ⊥ else dopGenSpanBi 𝗊 𝗎 (m * c.toNat) (n * c.toNat)
  have hE : Ψ g' ∈ dopGenSpanBi 𝗊 𝗎 (m * N) (n * N) := by
    have key := mem_of_mem_lambdaComp G ?_ ?_ Ψ ?_ hg'
    · simpa [G, show ¬ ((N : ℤ) < 0) by omega] using key
    · simpa [G] using one_mem_dopGenSpanBi 𝗊 𝗎
    · intro c c' x y hx hy
      by_cases hc : c < 0
      · simp_all [G]
      by_cases hc' : c' < 0
      · simp_all [G]
      simp only [G, hc, hc', ite_false] at hx hy
      simp only [G, show ¬ c + c' < 0 by omega, ite_false]
      have h := mul_mem_dopGenSpanBi hx hy
      rwa [← mul_add, ← mul_add, ← Int.toNat_add (by omega) (by omega)] at h
    · intro i
      simp only [G, show ¬ ((i : ℤ) + 1) < 0 by omega, ite_false,
        show ((i : ℤ) + 1).toNat = i + 1 by omega, hΨ]
      exact qop_mem_dopGenSpanBi 𝗊 𝗎 _ (Nat.mul_pos hm (Nat.succ_pos i)) _
        (Or.inl (Nat.mul_pos hn (Nat.succ_pos i)))
  have hΘg : (Ψ g' : Module.End K (Sym.Lambda K)) = Θ (axisSub (𝗊 * 𝗎) g') :=
    AlgHom.congr_fun h1 g'
  have hΘ'g : (S (Ψ g') : Module.End K (Sym.Lambda K)) = Θ' (axisSub (𝗊 * 𝗎) g') :=
    AlgHom.congr_fun h2 g'
  refine NsTransports.congr (by push_cast; ring) hΘg ?_
    (nsTransports_smul_map_of_mem_dopGenSpanBi 𝗊 𝗎 (one_sub_pow_mul_one_sub_pow_ne_zero K) hS hE
      (shiftsDegree_of_mem_dopGenSpanBi hE))
  rw [Subalgebra.coe_smul, hΘ'g]

omit [Algebra ℚ K] in
/-- The parameter `q` is nonzero in `K`. -/
theorem paramQ_ne_zero : (𝗊 : K) ≠ 0 :=
  HJO.Standing.paramQ_ne_zero K

/-- For `b ≥ 1`, a slope homomorphism `Θ` at `(a, b)` sends each `f ∈ Λ_d` to an operator raising
degree by `b * d`. -/
theorem isSlopeHom_shiftsDegree' {a b : ℕ} (hb : 1 ≤ b)
    {Θ : Sym.Lambda K →ₐ[K] Module.End K (Sym.Lambda K)} (hΘ : IsSlopeHom a b 𝗊 𝗎 Θ) {d : ℕ}
    {f : Sym.Lambda K} (hf : f ∈ LambdaComp K d) : ShiftsDegree ((b : ℤ) * d) (Θ f) := by
  have := HJO.Ascent.charZero_of_algebra_rat K
  have hA := isAdmissible_standing K
  exact isSlopeHom_shiftsDegree hb (mul_ne_zero hA.fst_ne_zero hA.snd_ne_zero)
    hA.mul_pow_succ_ne_one hΘ hf

end HJO.Mellit.LhsDesign
