/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitShiftDop
public import HJO.Symmetric.DopCommutator
public meta import HJO.Attr

/-! # The sign of the shift, pinned down

`HJO.Sym.nsShiftComp_comp_smul_map` reads `τ^*τ S(L) = L τ^*τ`, and the one thing a reader has to
know before repairing that statement is which sign `S` carries. The sign is argued from
`HJO.Sym.nsShiftComp_comp_dopInt`, with the conclusion `S(D̂_n) = -D_{n+1}`. This file turns that
argument into theorems, so the sign is a proved fact rather than a paragraph.

## What is here

* `HJO.Sym.eq_neg_dopInt_of_nsShiftComp` — **the sign is forced.** If `E` is *any* `𝕜`-linear
  endomorphism of `Λ` with `τ^*τ E = D̂_n τ^*τ`, then `E = -D_{n+1}`. Nothing is assumed about `E`
  beyond that identity: `HJO.Sym.nsShiftComp_comp_dopInt` exhibits `-D_{n+1}` as a
  solution and `HJO.Sym.nsShiftComp_eq_of_eq` says there is at most one, so the solution set is the
  singleton `{-D_{n+1}}`.
* `HJO.Sym.not_nsShiftComp_dopInt_neg_one` — **the other sign is refuted, outright.** At `n = -1`
  the unsigned candidate `D_{n+1} = D_0` does *not* satisfy the identity. No hypothesis on `q`, `u`
  beyond the standing `hM`: `D_0(1) = 1`, so `D_0 = -D_0` would make `1 = -1` in `Λ`.
* `HJO.Sym.dopInt_eq_neg_self_of_nsShiftComp` — the general form of the same obstruction: at any
  `n`, the unsigned candidate satisfies the identity only where `D_{n+1} = -D_{n+1}`.

## Why the shifted identity itself is not here

`HJO.Sym.nsShiftComp_comp_smul_map`, in Mellit's form on `e_0Ãe_0`, **cannot be stated** from what
this file uses, and the obstruction is in that statement rather than in anything below it. It needs
three things, none of them a proof:

* the *action* of `e_0Ã e_0` on `Λ`, which is `HJO.Sweep.exists_isDpaAction_mellit`;
* an ambient for the per-`k` extensions, which is `HJO.Sweep.pieceHat` (see the
  module docstring of `HJO.Shuffle.MellitCompletionFrac` for why the fraction field there is
  not it);
* a shift on the *arrows of* `Ã`. `HJO.Sym.IsIndexShift` is
  about the subalgebra `𝖠` of `End(Λ)` generated by the `D_k`, not about `Ã`, so it assigns no value
  to an arrow at all, and the two values a proof of that form spends, `S(D̂_n) = -D_{n+1}` and
  `S(d^*_+) = -y_1d^*_+`, are used and never stated.

The statement is proved on `𝖠`, with the twisted shift, in `HJO/Shuffle/MellitShiftTwisted.lean`.

The sign is *not* a fourth defect, and the apparent conflict with `HJO.Sym.IsIndexShift`, which asks
`S(D_k) = +D_{k+1}`, is not one either: `HJO.Dyck.Tilde.rel_biHomogeneous` records that the shift on
`Ã` and the normalisation of `HJO.Sym.IsIndexShift` differ by `(-1)^m` on the bidegree-`(m,n)`
component, and `D_n` sits at `m = 1`. So the two readings are the same map up to exactly the sign
proved here.

## References

A. Mellit, *Toric braids and `(m,n)`-parking functions*, §3.7.
-/

@[expose] public section

namespace HJO.Sym

section Field

variable {K : Type*} [Field K] [Algebra ℚ K]

/-- `HJO.Sym.nsShiftComp_comp_dopInt` read pointwise: `-D_{n+1}` is transported by `D̂_n`. -/
theorem nsShiftComp_neg_dopInt (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) (n : ℤ) (f : Lambda K) :
    nsShiftComp q u ((-(DopInt q u (n + 1))) f)
      = completionExtension (dopInt_shiftsDegree q u n) (nsShiftComp q u f) :=
  LinearMap.congr_fun (nsShiftComp_comp_dopInt q u hM n) f

/-- **The sign of the shift is forced, and it is the minus.** Any `𝕜`-linear endomorphism `E` of `Λ`
satisfying the identity `HJO.Sym.nsShiftComp_comp_smul_map` asks of `S(L)` at `L = D̂_n`, namely
`τ^*τE = D̂_nτ^*τ`, is `-D_{n+1}` — on the nose, with no hypothesis on `E` beyond that identity.

`HJO.Sym.nsShiftComp_comp_dopInt` supplies one solution and `HJO.Sym.nsShiftComp_eq_of_eq` says
there is at most one, so the solution set is a singleton and the sign is not a convention that could
be chosen otherwise. -/
theorem eq_neg_dopInt_of_nsShiftComp (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) (n : ℤ)
    {E : Module.End K (Lambda K)}
    (hE : ∀ f, nsShiftComp q u (E f)
      = completionExtension (dopInt_shiftsDegree q u n) (nsShiftComp q u f)) :
    E = -DopInt q u (n + 1) :=
  nsShiftComp_eq_of_eq q u (dopInt_shiftsDegree q u n) hE (nsShiftComp_neg_dopInt q u hM n)

/-- **The unsigned candidate is transported only where it is its own negative.** If `D_{n+1}` itself
satisfied the identity, it would be `-D_{n+1}` by `HJO.Sym.eq_neg_dopInt_of_nsShiftComp`. -/
theorem dopInt_eq_neg_self_of_nsShiftComp (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) (n : ℤ)
    (hE : ∀ f, nsShiftComp q u (DopInt q u (n + 1) f)
      = completionExtension (dopInt_shiftsDegree q u n) (nsShiftComp q u f)) :
    DopInt q u (n + 1) = -DopInt q u (n + 1) :=
  eq_neg_dopInt_of_nsShiftComp q u hM n hE

/-- **The plus sign is refuted.** At `n = -1` the unsigned candidate `D_{n+1} = D_0` does not
satisfy `τ^*τE = D̂_nτ^*τ`: it would have to equal its own negative, and `D_0(1) = 1`
(`HJO.DopCommutator.Witness.dop_zero_apply_one`), so `1 = -1` in `Λ` and hence `2 = 0` in `𝕜`,
which a `ℚ`-algebra forbids.

So the shift `S` genuinely carries a minus, and `S(D̂_n) = +D_{n+1}` is false — not merely
unproved. -/
theorem not_nsShiftComp_dopInt_neg_one (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) :
    ¬ ∀ f, nsShiftComp q u (DopInt q u (-1 + 1) f)
      = completionExtension (dopInt_shiftsDegree q u (-1)) (nsShiftComp q u f) := by
  intro hE
  have hself := dopInt_eq_neg_self_of_nsShiftComp q u hM (-1) hE
  have hone : DopInt q u (-1 + 1) (1 : Lambda K) = 1 := by
    rw [show (-1 : ℤ) + 1 = ((0 : ℕ) : ℤ) from by norm_num, dopInt_natCast]
    exact DopCommutator.Witness.dop_zero_apply_one q u
  have hneg : (1 : Lambda K) = -1 := by
    have h := congrArg (fun P : Module.End K (Lambda K) => P (1 : Lambda K)) hself
    simp only [LinearMap.neg_apply] at h
    rw [hone] at h
    exact h
  have hchar : CharZero K := charZero_of_injective_algebraMap (algebraMap ℚ K).injective
  have h2 : (2 : K) = 0 := by
    have hc := congrArg (MvPolynomial.constantCoeff (σ := ℕ) (R := K)) hneg
    rw [map_one, map_neg, map_one] at hc
    linear_combination hc
  exact two_ne_zero h2

end Field

end HJO.Sym

end
