/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitLhsSlopeThreeFour
public import HJO.Shuffle.MellitZopOneV1
public import HJO.Shuffle.Euclid
public meta import HJO.Attr

/-! # The mediant step of the general-slope gluing identity

`HJO/Shuffle/MellitLhsSlopeBase.lean` and `HJO/Shuffle/MellitLhsSlopeThreeFour.lean`
settle the `α = (1)` base case of `HJO.Mellit.lhsRewrite_sweepWitness` at the two smallest slopes
with `a > 1`. This file carries out the **mediant induction** those two instances exhibit: it states
the general clause at a general `f`, proves the `a = 1` column, and reduces the mediant step to a
single identity about the `N` term of `z_1`.

## Main definitions

* `HJO.Mellit.LhsSlope`: the general clause at `(a, b)` — for every `f ∈ Λ`,
  `C(Q_{a,b}f) = (-1)^{b+1}d_-(Ξ^{(1)}_{a,b}(y_1d^*_+{}^{(0)}(Cf)))`. The `f` is general because
  `HJO.Sym.Qop`'s recursion evaluates `Q_{r,s}` at `Q_{a-r,b-s}(1) ≠ 1`, so an `f = 1` statement
  cannot induct.
* `HJO.Mellit.NTermGlue`: the residual identity of the mediant step, isolated.

## Main results

* `HJO.Mellit.lhsSlope_one_left`: the clause at `(1, n)` at a general `f` — the `a = 1` column and
  the base of the induction, from `HJO.Sweep.dop_eq_neg_dminusCM_auxVar_pow_dplusStar`.
* `HJO.Mellit.dminus_slopeOperator_mediant`: **the mediant step computed**, with no hypothesis on
  the parameters: given the clause at both Stern–Brocot parents, the sweep side at the mediant is
  `-(qu)^{-1}(q/(1-q))` times `(-1)^{p₂+r₂}C(Q_rQ_pf)` minus the `N` term.
* `HJO.Mellit.lhsSlope_mediant`: the clause at the mediant, from the clause at both parents and
  `NTermGlue`. **All of the scalar and sign bookkeeping of the induction is discharged here**; the
  scalar identity spent is `((1-q)(1-u))^{-1} = (qu)^{-1}(q/(1-q))(u/(1-u))`, and it is the only
  place `q ∉ {0,1}`, `u ∉ {0,1}` are used.
* `HJO.Mellit.nTermGlue_of_lhsSlope`: the converse — the clause at the two parents and at the
  mediant forces `NTermGlue`. So `NTermGlue` is not one convenient sufficient condition among many
  but the **exact** residual content of the step.
* `HJO.Mellit.lhsBase_of_lhsSlope`: the clause implies the base case in the shape
  `HJO.Mellit.qop_apply_one_of_lhsComputes` asks for, so `HJO.Mellit.lhsBase_two_three` and
  `HJO.Mellit.lhsBase_three_four` are its `(2,3)` and `(3,4)` instances read at `f = 1`.
* `HJO.Mellit.auxVar_mul_dminus_two_dplusStar_one`, `HJO.Mellit.nTerm_eq_of_lhsSlope`,
  `HJO.Mellit.nTermGlue_iff_lhsSlope`: **the `N` term eliminated.** `y_1N = P - ((1-q)/q)y_1z_1` and
  `y_1z_1` is the letter pair, so `NTermGlue` is equivalent to the clause at the mediant and is not
  a statement about `z_1`'s second half.
* `HJO.Mellit.lhsSlope_of_prod_elemSymm`: the clause need only be checked on products of `e_n`,
  both sides being `L`-linear in `f`. So a general `f` is bookkeeping and the slope is the content.
* `HJO.Sym.dop_elemSymm_mul`: the **full Pieri rule** `D_k(e_nf) = ∑_{s≤n}κ(e_s)e_{n-s}D_{k+s}f`,
  generalising `HJO.Sym.dop_elemSymm_one_mul` from `e_1` to every `e_n`, with no hypothesis on
  `q, u`. This is the `Λ`-side lemma a general-`f` computation needs.

## Where the induction stands

The step is **not** blocked on bookkeeping. `HJO.Mellit.lhsSlope_mediant` is a theorem, so the two
signs, the mediant factorisation and the mismatch between `HJO.Sym.Qop`'s `M^{-1}` and
`HJO.Sweep.slopeOperator`'s `(u(1-q))^{-1}` all reconcile exactly, the difference
`M^{-1} - (u(1-q))^{-1} = (2u-1)/((1-q)u(1-u))` being absorbed by the `N` term and by nothing else.

What is left is one operator identity, `HJO.Mellit.NTermGlue`:

`d_-Ξ_r(y_1·N(Ξ_p(y_1d^*_+Cf))) = (-1)^{p₂+r₂}((1-u)^{-1}C(Q_rQ_pf) - (u/(1-u))C(Q_pQ_rf))`.

Two facts about it record why it is hard.

**It does not follow from either mediant factorisation.** `HJO.Mellit.slopeEval_mediant` and
`HJO.Mellit.slopeEval_mediant_rev` give `Ξ_rYZΞ_p = Ξ_pZYΞ_r`, and `YZ` is
`-(u(1-q))^{-1}(P - y_1N)` with `P := y_1d^*_+{}^{(0)}d_-^{(1)}`: only the *difference* `P - y_1N`
lies in the monoid generated by the two letters, so neither `P` nor `y_1N` alone is constrained by
the word combinatorics. The `P` half is exactly what the induction hypothesis consumes
(`HJO.Mellit.dminus_slopeOperator_mediant`), and the `N` half is what is left over.

**It is not local in `Ξ_p(y_1d^*_+Cf)`.** `N` on a general element of `V_1` *is* computable —
`HJO.Sweep.zopOneStar_one_auxVar_pow_mul_C` says `N(y_1^mCA) = B_m(d^*_+{}^{(0)}(CA))`
coefficientwise in `y_1` — and so is the outer `d_-`. But the right-hand side contains `Q_pQ_rf`,
which is `Ξ_p` re-run on the *different* vector `y_1d^*_+C(Q_rf)`; no information about the single
element `Ξ_p(y_1d^*_+Cf)` can determine it. So the identity is a commutation statement between `Ξ_p`
and the outer `d_-`/`y_1d^*_+` structure — in effect the elliptic Hall relation for these operators
— and not a computation with the evaluations proved so far.

At `(2,3)`, where `r = Split 2 3 = (1,1)` and `Ξ_r = 1`, `Q_p = D_2` and `Q_r = D_1`, it reads
`d_-(y_1N(y_1^2d^*_+Cf)) = (1-u)^{-1}C(D_1D_2f) - (u/(1-u))C(D_2D_1f)`; at `f = 1` that is
`B_1(e_2) = (1-u)^{-1}D_1(e_2) + u(1-u)^{-1}D_2(e_1)`, which the closed forms
`HJO.Sym.dop_one_elemSymm_two` and the Pieri rule `HJO.Sym.dop_elemSymm_one_mul` satisfy identically
in `q` and `u` — that is `HJO.Mellit.nTermGlue_two_three_apply_one`, and it is the check that the
coefficients `(1-u)^{-1}` and `u/(1-u)` above are the right *pair*: `HJO.Mellit.lhsSlope_mediant`
constrains only their difference, so a wrong split between them passes every other check here.

**The `N` term is not independent data, so there is nothing smaller to prove.**
`HJO.Mellit.auxVar_mul_dminus_two_dplusStar_one` shows `y_1N = P - ((1-q)/q)y_1z_1` on the whole
total space, and `y_1z_1 = -qu·(YZ)` is the letter pair itself; so
`HJO.Mellit.nTerm_eq_of_lhsSlope` evaluates the `N` term as the `P` term plus `u(1-q)` times the
sweep side at the mediant. Consequently `HJO.Mellit.nTermGlue_iff_lhsSlope`: the residual identity
is *equivalent* to the clause at the mediant. **`NTermGlue` is therefore not a statement about the
second half of `z_1` at all**, and no evaluation of `N` — however general — can discharge it. The
content is the commutator recursion of `HJO.Sym.Qop` for the sweep-side composites
`f ↦ ct(d_-(Ξ_{a,b}(y_1d^*_+Cf)))`, and nothing else. At `(2,3)` it reads
`d_-(y_1z_1(y_1^2d^*_+Cf)) = qu·C(Q_{2,3}f)`, which is the clause at `(2,3)` again.

## Which of the two generalisations is the hard one: the slope, not `f`

`HJO.Mellit.lhsSlope_of_prod_elemSymm` settles this. The clause is `L`-linear in `f`
(`HJO.Mellit.lhsSlopeCarrier`) and the products of the `e_{i+1}` span `Λ`
(`HJO.Sym.adjoin_elemSymm_eq_top` with `Algebra.adjoin_eq_span`), so **a general `f` is
bookkeeping**: it is enough to prove the clause on `e`-monomials. Both halves are then known in
closed form on such an `f`:

* sweep side — `HJO.Sweep.dplusStar_C_prod_elemSymm` expands `d^*_+` on an arbitrary `e`-monomial
  unconditionally, and `d^*_+` is an `AlgHom` by `rfl`
  (`HJO.Sweep.dplusStarAlg_eq_dplusStar`), so a *list* product is the matching shape, via
  `map_list_prod`;
* `Q` side — `HJO.Sym.dop_elemSymm_mul`, the full Pieri rule
  `D_k(e_nf) = ∑_{s≤n}κ(e_s)e_{n-s}D_{k+s}f` proved below. Without it, the basic operator against a
  product is known only for `e_1` (`HJO.Sym.dop_elemSymm_one_mul`), so a general `e`-monomial could
  not be pushed through `HJO.Sym.Qop`'s commutator at all. It is checked at `n = 1` and at `n = 2`
  against the two known values, by `HJO.Sym.dop_elemSymm_one_mul_of_pieri` and
  `HJO.Sym.dop_one_elemSymm_two_of_pieri`.

The **slope** is the content: nothing here reduces a slope to smaller ones except
`HJO.Mellit.lhsSlope_mediant`, whose residual hypothesis is the clause itself. So proving the clause
at general `f` for one fixed slope — the `(2,3)` case, whose two sides are both available — is a
finite computation that will *not* generalise in the slope, and the uniform statement needs the
commutator relation above.

## The column this file does *not* reach

`HJO.Mellit.lhsSlope_mediant` needs `1 ≤ p₂` and `1 ≤ r₂`, because
`HJO.Mellit.slopeWord_mediant` is stated for two positive coprime pairs. By
`HJO.Mellit.isSBParent_pos` that holds exactly when `a, b ≥ 2`. So the three cases of the induction
are the three of the induction behind `HJO.Mellit.euclid`, and their status here is:

* `(1,n)`: **proved**, at a general `f`, by `HJO.Mellit.lhsSlope_one_left`;
* `(a,b)` with `a, b ≥ 2`: **reduced** to `NTermGlue`, by `HJO.Mellit.lhsSlope_mediant`;
* `(a,1)` with `a ≥ 2`: **not treated at a general `f`**, but settled at the two smallest
  coefficients, uniformly in `a`: at `f = 1` by
  `HJO.Sweep.dminus_straightMonomial_slopeArg_one` with `HJO.Sym.qop_apply_one_of_snd_one`
  (`MellitStraightMonomial.lean`), and at `f = e_1` by
  `HJO.Sweep.lhsSlopeAt_succ_one_elemSymm_one` (`MellitVertexStepGeneral.lean`), where the value
  does depend on `a` and so is a real test of the slope. What follows is why a general `f` needs
  its own residual identity. Its Stern–Brocot parents are `(a-1,1)` and `(1,0)`, and
  `Ξ_{1,0}` is outside the range of `HJO.Mellit.slopeEval_one_left`, so the mediant step cannot be
  applied; the recursion available there is `HJO.Mellit.slopeEval_succ_right`,
  `Ξ_{a,1} = Z·Ξ_{a-1,1}`, whose `Q`-side is `Q_{a,1} = M^{-1}(Q_{a-1,1}D_0 - D_0Q_{a-1,1})`
  (`HJO.Sym.split_snd_one`), and it needs its own residual identity, with one `Z` rather than a
  `YZ` pair. This column is not optional: at `(3,2)` the parents are `(1,1)` and `(2,1)`, so every
  slope with `a > b` reaches it.

## Genericity

`q ∉ {0,1}` and `u ∉ {0,1}`, exactly as at `(2,3)` and `(3,4)`: `(qu)^{-1}` from
`HJO.Sweep.slopeOperator`, `(1-q)^{-1}` from `HJO.Sweep.zop`, `((1-q)(1-u))^{-1}` from
`HJO.Sym.Qop`. `u ≠ 1` is necessary on a curve, not at isolated points
(`HJO.Mellit.not_lhsBase_two_three_of_u_eq_one`). `HJO.Mellit.dminus_slopeOperator_mediant` and
`HJO.Mellit.lhsSlope_one_left` need no hypothesis on the parameters at all.

## Implementation notes

The identity is proved at `a = 1` by `HJO.Sweep.dop_eq_neg_dminusCM_auxVar_pow_dplusStar`; its
general-slope form is what `HJO.Mellit.LhsSlope` states, and it is not proved here, only reduced.
`HJO.Mellit.lhsSlope_mediant` carries hypotheses the general-slope statement does not have —
`NTermGlue`, and the value of `HJO.Sym.Split` at the slope.

## References

Declarations involved: `HJO.Sweep.dop_eq_neg_dminusCM_auxVar_pow_dplusStar` (general slope),
`HJO.Mellit.lhsRewrite_sweepWitness` (base case), `HJO.Sym.Qop`, `HJO.Sweep.slopeOperator`,
`HJO.Sweep.zop`, `HJO.Mellit.slopeWord_mediant`. Transcribing A. Mellit, *Toric braids and
`(m, n)`-parking functions*, §3, §6.
-/

@[expose] public section

open HJO.Sym HJO.Sweep HJO.Bglx

namespace HJO.Sym

variable {L : Type*} [Field L] [Algebra ℚ L]

/-! ### The basic operator against multiplication by `e_n` -/

/-- **The full Pieri rule for the basic operator.** For every `k, n ≥ 0` and every `f ∈ Λ`,

`D_k(e_nf) = ∑_{s ≤ n} κ(e_s)·e_{n-s}·D_{k+s}f`,

with `κ = HJO.Bglx.paramPleth` the kernel of `HJO.Sym.plethShift` — `κ(e_0) = 1`, `κ(e_1) = M`,
`κ(e_2) = -(q+u)M`, and so on.

`HJO.Sym.dop_elemSymm_one_mul` is the case `n = 1`, where the sum has two terms and
reads `D_k(e_1f) = e_1D_kf + MD_{k+1}f`; this is the same argument at every `n`. The displacement of
`HJO.Sym.plethShift` is an algebra map, so it carries `e_nf` to `(∑_s e_{n-s}κ(e_s)w^s)·f[X + M/z]`
(`HJO.Sym.plethShift_elemSymm`), and a factor `w^s` shifts the extracted coefficient from `z^k` to
`z^{k+s}`, which is `D_{k+s}` — the sign `(-1)^{k+j}` of `HJO.Sym.DopInt` needs no correction,
because `(-1)^{k+(j+s)}` is already the sign of `D_{k+s}` at `j`.

**No hypothesis on `q` or `u`.** Read at `n = 2, k = 1, f = 1` it reproduces
`HJO.Sym.dop_one_elemSymm_two`, and at `n = 1` it reproduces `HJO.Sym.dop_elemSymm_one_mul`.

This is the `Λ`-side lemma the general-`f` gluing identity needs: by
`HJO.Mellit.lhsSlope_of_prod_elemSymm` the clause reduces to `e`-monomials, and on the `Q` side that
requires the basic operator against a product of `e`'s, not only against `e_1`. -/
theorem dop_elemSymm_mul (q u : L) (k n : ℕ) (f : Lambda L) :
    Dop q u k (elemSymm L n * f)
      = ∑ s ∈ Finset.range (n + 1),
          paramPleth q u (elemSymm L s) • (elemSymm L (n - s) * Dop q u (k + s) f) := by
  rw [dop_apply, map_mul, plethShift_elemSymm, Finset.sum_mul, map_sum]
  refine Finset.sum_congr rfl fun s _ => ?_
  rw [coeffPairing_C_mul_X_pow_mul _ _ s _
    (fun j => (-1) ^ (k + s + j) * elemSymm L (k + s + j))
    (fun i => by rw [show k + (i + s) = k + s + i from by omega]), ← dop_apply,
    MvPolynomial.smul_eq_C_mul]
  ring

/-- **Cross-check: the Pieri rule at `n = 1` reproves `HJO.Sym.dop_elemSymm_one_mul`.** The two
terms of the sum are `κ(e_0) = 1` against `e_1D_kf` and `κ(e_1) = M` against `e_0D_{k+1}f`
(`HJO.Bglx.paramPleth_elemSymm_zero`, `HJO.Bglx.paramPleth_elemSymm_one_eq`). Nothing here appeals
to `HJO.Sym.dop_elemSymm_one_mul`, so this is an independent check of the indexing `e_{n-s}` and of
the absent sign correction, not a restatement. -/
theorem dop_elemSymm_one_mul_of_pieri (q u : L) (k : ℕ) (f : Lambda L) :
    Dop q u k (elemSymm L 1 * f)
      = elemSymm L 1 * Dop q u k f + ((1 - q) * (1 - u)) • Dop q u (k + 1) f := by
  rw [dop_elemSymm_mul, Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_zero,
    paramPleth_elemSymm_zero, paramPleth_elemSymm_one_eq]
  norm_num [elemSymm_zero]

/-- **Cross-check: the Pieri rule at `n = 2`, `k = 1`, `f = 1` reproves
`HJO.Sym.dop_one_elemSymm_two`.** This is the sharper of the two checks: it reads all three kernel
coefficients `1`, `M`, `-(q+u)M` and all three of `e_2, e_1, e_0` in the `e_{n-s}` slot, so a
misindexed sum would not survive it. -/
theorem dop_one_elemSymm_two_of_pieri (q u : L) :
    Dop q u 1 (elemSymm L 2)
      = ((1 - q) * (1 - u) - 1) • (elemSymm L 1 * elemSymm L 2)
        + ((q + u) * ((1 - q) * (1 - u))) • elemSymm L 3 := by
  have hd1 : Dop q u 1 (1 : Lambda L) = -elemSymm L 1 := by rw [dop_apply_one]; ring
  have hd2 : Dop q u 2 (1 : Lambda L) = elemSymm L 2 := by rw [dop_apply_one]; ring
  have hd3 : Dop q u 3 (1 : Lambda L) = -elemSymm L 3 := by rw [dop_apply_one]; ring
  have h := dop_elemSymm_mul q u 1 2 (1 : Lambda L)
  rw [mul_one] at h
  rw [h, Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_succ,
    Finset.sum_range_zero, paramPleth_elemSymm_zero, paramPleth_elemSymm_one_eq,
    paramPleth_elemSymm_two_eq]
  norm_num only [Nat.sub_zero, Nat.sub_self, elemSymm_zero, one_mul, zero_add]
  rw [hd1, hd2, hd3]
  simp only [MvPolynomial.smul_eq_C_mul, map_sub, map_add, map_mul, map_neg, map_one]
  ring

end HJO.Sym

namespace HJO.Mellit

variable {L : Type*} [Field L] [Algebra ℚ L] {q u : L}

/-! ### Scalar and sign bookkeeping -/

omit [Algebra ℚ L] in
private theorem neg_one_pow_mul_self (k : ℕ) : ((-1 : L) ^ k * (-1 : L) ^ k) = 1 := by
  rw [← pow_add]
  exact Even.neg_one_pow ⟨k, rfl⟩

omit [Algebra ℚ L] in
private theorem neg_one_pow_succ_mul (c : L) (k : ℕ) :
    ((-1 : L) ^ (k + 1) * -c * (-1 : L) ^ k) = c := by
  have h : ((-1 : L) ^ (k + 1) * (-1 : L) ^ k) = -1 := by
    rw [pow_succ, mul_comm ((-1 : L) ^ k) (-1), mul_assoc, neg_one_pow_mul_self, mul_one]
  linear_combination (-c) * h

omit [Algebra ℚ L] in
private theorem C_smul (c : L) (x : Sym.Lambda L) :
    (MvPolynomial.C (c • x) : Total L) = c • MvPolynomial.C x := by
  rw [Algebra.smul_def, Algebra.smul_def, map_mul,
    IsScalarTower.algebraMap_apply L (Sym.Lambda L) (Total L) c, MvPolynomial.algebraMap_eq,
    MvPolynomial.algebraMap_eq]

omit [Algebra ℚ L] in
/-- **The one scalar identity the mediant step spends**, in the form it is used:
`M^{-1} = (qu)^{-1}(q/(1-q))(u/(1-u))` together with `1 - (1-u)^{-1} = -u/(1-u)`, read on two
free vectors `A = C(Q_pQ_rf)` and `B = C(Q_rQ_pf)`. This is where `q ∉ {0,1}`, `u ∉ {0,1}` are
spent, and the whole reason `HJO.Sym.Qop`'s antisymmetric commutator can be matched against the
slope side's single value. -/
private theorem mediant_scalar (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) (hu1 : u ≠ 1)
    (A B : Total L) :
    (((1 - q) * (1 - u))⁻¹ : L) • (A - B)
      = ((q * u)⁻¹ * (q / (1 - q))) • (B - ((1 - u)⁻¹ • B - (u / (1 - u)) • A)) := by
  have h1q : (1 : L) - q ≠ 0 := sub_ne_zero.mpr (Ne.symm hq1)
  have h1u : (1 : L) - u ≠ 0 := sub_ne_zero.mpr (Ne.symm hu1)
  match_scalars <;> (field_simp; try ring)

omit [Algebra ℚ L] in
private theorem neg_mulLeft_pow_apply_smul (y x : Total L) (m : ℕ) :
    ((-LinearMap.mulLeft L y) ^ m) x = (-1 : L) ^ m • (y ^ m * x) := by
  induction m generalizing x with
  | zero => simp
  | succ n ih =>
    rw [pow_succ, Module.End.mul_apply, LinearMap.neg_apply, LinearMap.mulLeft_apply, ih,
      mul_neg, pow_succ y n, mul_assoc]
    module

/-! ### The vacuum at a general symmetric function -/

/-- **The argument the slope operator is fed in the base case**, `y_1·d^*_+{}^{(0)}(Cf) ∈ V_1`.
At `f = 1` it is the vacuum `y_1d^*_+(1) = y_1` of `HJO.Mellit.stageWordTotal_singleton_one`
(`HJO.Mellit.slopeArg_one`); a general `f` is forced, because `HJO.Sym.Qop`'s recursion evaluates a
slope operator at the value of another one, which is not the vacuum. -/
noncomputable def slopeArg (q u : L) (f : Sym.Lambda L) : Total L :=
  (auxVar 1 : Total L) * dplusStar q u 0 (MvPolynomial.C f)

omit [Algebra ℚ L] in
theorem slopeArg_def (q u : L) (f : Sym.Lambda L) :
    slopeArg q u f = (auxVar 1 : Total L) * dplusStar q u 0 (MvPolynomial.C f) := rfl

omit [Algebra ℚ L] in
/-- At `f = 1` the argument is the vacuum `y_1` that the stage word carries. -/
theorem slopeArg_one (q u : L) : slopeArg q u (1 : Sym.Lambda L) = (auxVar 1 : Total L) := by
  rw [slopeArg_def, MvPolynomial.C_1, dplusStar_one, mul_one]

/-! ### The general clause, and the residual identity of its mediant step -/

/-- **The general clause of `HJO.Sweep.dop_eq_neg_dminusCM_auxVar_pow_dplusStar` at the slope
`(a, b)`:** for every `f ∈ Λ`,

`C(Q_{a,b}f) = (-1)^{b+1}·d_-(Ξ^{(1)}_{a,b}(y_1d^*_+{}^{(0)}(Cf)))`.

At `a = 1` this is `HJO.Sweep.dop_eq_neg_dminusCM_auxVar_pow_dplusStar`
(`HJO.Mellit.lhsSlope_one_left`); at `f = 1` it is the base case of
`HJO.Mellit.lhsRewrite_sweepWitness` (`HJO.Mellit.lhsBase_of_lhsSlope`), whose `(2,3)` and `(3,4)`
instances are proved.

The two `a`-dependent signs of the base case have already cancelled: `stageWordTotal` carries
`-(-1)^{a-1}` and the clause `(-1)^{a-1}`, so what is left is the single `(-1)^{b+1}` — which is
`+1` at `(2,3)` and `-1` at `(3,4)`, the two data points this reading is calibrated against. -/
def LhsSlope (q u : L) (a b : ℕ) : Prop :=
  ∀ f : Sym.Lambda L, MvPolynomial.C (Sym.Qop q u a b f)
    = (-1 : L) ^ (b + 1) • dminus q 1 (slopeOperator q u 1 a b (slopeArg q u f))

/-- **The residual identity of the mediant step**, at the Stern–Brocot parent `(p₁,p₂)` — the inner
factor of `HJO.Mellit.slopeWord_mediant` — and its complement `(r₁,r₂)`, which is `HJO.Sym.Split`:

`d_-(Ξ_r(y_1·d_-^{(2)}d^*_+{}^{(1)}(Ξ_p(y_1d^*_+Cf))))`
`  = (-1)^{p₂+r₂}((1-u)^{-1}C(Q_rQ_pf) - (u/(1-u))C(Q_pQ_rf))`.

The operator `N = d_-^{(2)}d^*_+{}^{(1)}` is the second half of `HJO.Sweep.zop`; the first half is
what the induction hypothesis at the two parents consumes, leaving exactly this. Both orders of the
parents' composite appear on the right, with unequal coefficients whose difference is `1` — that is
the precise form of "`N` is load-bearing and the matching is not term by term", and it is where
`u ≠ 1` enters. -/
def NTermGlue (q u : L) (p₁ p₂ r₁ r₂ : ℕ) : Prop :=
  ∀ f : Sym.Lambda L,
    dminus q 1 (slopeOperator q u 1 r₁ r₂ ((auxVar 1 : Total L) *
        dminus q 2 (dplusStar q u 1 (slopeOperator q u 1 p₁ p₂ (slopeArg q u f)))))
      = (-1 : L) ^ (p₂ + r₂) •
          ((1 - u)⁻¹ • (MvPolynomial.C (Sym.Qop q u r₁ r₂ (Sym.Qop q u p₁ p₂ f)) : Total L)
            - (u / (1 - u)) • (MvPolynomial.C (Sym.Qop q u p₁ p₂ (Sym.Qop q u r₁ r₂ f)) : Total L))

/-! ### The `a = 1` column -/

/-- **The clause holds at `(1, n)` for every `f`.** This is the `a = 1` column and the base of the
mediant induction, and it is `HJO.Sweep.dop_eq_neg_dminusCM_auxVar_pow_dplusStar` itself:
the slope word is `β_{1,n} = y^{n-1}` (`HJO.Mellit.slopeWord_one_left`), so
`Ξ^{(1)}_{1,n}(y_1d^*_+Cf) = (-1)^{n-1}y_1^nd^*_+(Cf)`, whose `d_-` is `C(D_nf)` by
`HJO.Sweep.dop_succ_eq_dminus_auxVar_pow_dplusStar`. The sign `(-1)^{n-1}` meets the clause's
`(-1)^{n+1}` and cancels, and `Q_{1,n} = D_n` by `HJO.Sym.qop_one`.

No hypothesis on `q` or `u`. -/
theorem lhsSlope_one_left (q u : L) {n : ℕ} (hn : 1 ≤ n) : LhsSlope q u 1 n := by
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  intro f
  rw [Sym.qop_one, slopeArg_def, slopeOperator_eq_slopeEval,
    Mellit.slopeEval_one_left _ _ (by omega), show m + 1 - 1 = m from rfl,
    neg_mulLeft_pow_apply_smul, map_smul, ← mul_assoc, ← pow_succ (auxVar 1 : Total L) m,
    ← dop_succ_eq_dminus_auxVar_pow_dplusStar q u m f, smul_smul,
    show ((-1 : L) ^ (m + 1 + 1) * (-1 : L) ^ m) = 1 from by
      rw [← pow_add]
      exact Even.neg_one_pow ⟨m + 1, by ring⟩,
    one_smul]

/-! ### The mediant step -/

/-- **The mediant step of the sweep side, computed.** With `(p₁,p₂)` the Stern–Brocot parent and
`(r₁,r₂)` its complement, the clause at both parents gives

`d_-(Ξ_{p+r}(y_1d^*_+Cf)) = -(qu)^{-1}(q/(1-q))·((-1)^{p₂+r₂}C(Q_rQ_pf) - 𝒩(f))`,

where `𝒩(f)` is the left-hand side of `HJO.Mellit.NTermGlue`.

Three proved facts do the work. `HJO.Mellit.slopeEval_mediant` factors `Ξ_{p+r} = Ξ_r·Y·Z·Ξ_p`;
`HJO.Sweep.zop` at `k = 1` has an empty train (`HJO.Braid.trainUp_self`), so
`Z = (qu)^{-1}(q/(1-q))(d^*_+{}^{(0)}d_-^{(1)} - N)`; and the `d^*_+{}^{(0)}d_-^{(1)}` half turns
the clause at `p` into the argument of the clause at `r`, because `y_1d^*_+{}^{(0)}` is exactly how
the clause wraps its input. The `N` half is untouched and becomes `𝒩(f)`.

**No hypothesis on `q` or `u`**: every scalar is carried symbolically, which is what makes this the
clean half of the step. -/
theorem dminus_slopeOperator_mediant {p₁ p₂ r₁ r₂ : ℕ} (hp₁ : 1 ≤ p₁) (hp₂ : 1 ≤ p₂)
    (hr₁ : 1 ≤ r₁) (hr₂ : 1 ≤ r₂) (hdet : r₁ * p₂ = p₁ * r₂ + 1) (hcp : Nat.Coprime p₁ p₂)
    (hcr : Nat.Coprime r₁ r₂) (hp : LhsSlope q u p₁ p₂) (hr : LhsSlope q u r₁ r₂)
    (f : Sym.Lambda L) :
    dminus q 1 (slopeOperator q u 1 (p₁ + r₁) (p₂ + r₂) (slopeArg q u f))
      = (-((q * u)⁻¹ * (q / (1 - q)))) •
        ((-1 : L) ^ (p₂ + r₂) • (MvPolynomial.C (Sym.Qop q u r₁ r₂ (Sym.Qop q u p₁ p₂ f)) : Total L)
          - dminus q 1 (slopeOperator q u 1 r₁ r₂ ((auxVar 1 : Total L) *
              dminus q 2 (dplusStar q u 1 (slopeOperator q u 1 p₁ p₂ (slopeArg q u f)))))) := by
  -- the mediant factorisation of the slope operator
  have hmed : slopeOperator q u 1 (p₁ + r₁) (p₂ + r₂)
      = slopeOperator q u 1 r₁ r₂ * ((-LinearMap.mulLeft L (auxVar 1 : Total L))
          * (((q * u)⁻¹ • zop q u 1 1) * slopeOperator q u 1 p₁ p₂)) := by
    rw [slopeOperator_eq_slopeEval, slopeOperator_eq_slopeEval, slopeOperator_eq_slopeEval]
    exact Mellit.slopeEval_mediant _ _ hp₁ hp₂ hr₁ hr₂ hdet hcp hcr
  -- `z_1` at `k = 1` is the difference of its two halves, the train being empty
  have hz : ∀ G : Total L, zop q u 1 1 G
      = (q / (1 - q)) • (dplusStar q u 0 (dminus q 1 G) - dminus q 2 (dplusStar q u 1 G)) := by
    intro G
    rw [zop_one, zopOneStar, show trainUpEnd q 1 1 = 1 from Braid.trainUp_self _ _ 1, mul_one]
    simp only [LinearMap.smul_apply, LinearMap.sub_apply, Module.End.mul_apply, pow_one,
      Nat.sub_self]
  -- the clause at each parent, read as a value of `d_-`
  have hdp : ∀ g : Sym.Lambda L, dminus q 1 (slopeOperator q u 1 p₁ p₂ (slopeArg q u g))
      = (-1 : L) ^ (p₂ + 1) • (MvPolynomial.C (Sym.Qop q u p₁ p₂ g) : Total L) := fun g => by
    rw [hp g, smul_smul, neg_one_pow_mul_self, one_smul]
  have hdr : ∀ g : Sym.Lambda L, dminus q 1 (slopeOperator q u 1 r₁ r₂ (slopeArg q u g))
      = (-1 : L) ^ (r₂ + 1) • (MvPolynomial.C (Sym.Qop q u r₁ r₂ g) : Total L) := fun g => by
    rw [hr g, smul_smul, neg_one_pow_mul_self, one_smul]
  -- the `d^*_+d_-` half of `z_1` feeds the clause at `p` into the clause at `r`
  have hhalf : dminus q 1 (slopeOperator q u 1 r₁ r₂ ((auxVar 1 : Total L) *
        dplusStar q u 0 (dminus q 1 (slopeOperator q u 1 p₁ p₂ (slopeArg q u f)))))
      = (-1 : L) ^ (p₂ + r₂) •
        (MvPolynomial.C (Sym.Qop q u r₁ r₂ (Sym.Qop q u p₁ p₂ f)) : Total L) := by
    rw [hdp f, map_smul, mul_smul_comm, ← slopeArg_def, map_smul, map_smul,
      hdr (Sym.Qop q u p₁ p₂ f), smul_smul]
    congr 1
    rw [← pow_add, show p₂ + 1 + (r₂ + 1) = p₂ + r₂ + 2 from by ring, pow_add]
    norm_num
  -- assemble
  rw [hmed]
  simp only [Module.End.mul_apply, LinearMap.neg_apply, LinearMap.mulLeft_apply,
    LinearMap.smul_apply]
  rw [hz, smul_smul, mul_smul_comm, ← smul_neg, map_smul, map_smul, mul_sub, neg_sub, map_sub,
    map_sub, hhalf]
  module

/-- **The mediant step of the clause, from the two parents and `NTermGlue`.**

`HJO.Sym.Qop`'s recursion at a coprime slope is `Q_{a,b} = M^{-1}(Q_pQ_r - Q_rQ_p)` with
`r = Split a b` and `p = (a,b) - r` the Stern–Brocot parent (`HJO.Sym.qop_of_coprime`), while the
sweep side is `HJO.Mellit.dminus_slopeOperator_mediant`. The two meet on the single scalar identity

`((1-q)(1-u))^{-1} = (qu)^{-1}·(q/(1-q))·(u/(1-u))`,

which is where all four hypotheses `q ∉ {0,1}`, `u ∉ {0,1}` are spent and nowhere else: the
coefficients `1 - (1-u)^{-1} = -u/(1-u)` of `Q_rQ_p` and `u/(1-u)` of `Q_pQ_r` inside `NTermGlue`
are exactly what turns the sweep side's *single* value into `HJO.Sym.Qop`'s antisymmetric
commutator. So the mediant induction is bookkeeping-complete, and `NTermGlue` is the whole of what
remains. -/
theorem lhsSlope_mediant (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) (hu1 : u ≠ 1)
    {p₁ p₂ r₁ r₂ : ℕ} (hp₁ : 1 ≤ p₁) (hp₂ : 1 ≤ p₂) (hr₁ : 1 ≤ r₁) (hr₂ : 1 ≤ r₂)
    (hdet : r₁ * p₂ = p₁ * r₂ + 1) (hcp : Nat.Coprime p₁ p₂) (hcr : Nat.Coprime r₁ r₂)
    (hc : Nat.Coprime (p₁ + r₁) (p₂ + r₂)) (ha : 1 < p₁ + r₁)
    (hsplit : Sym.Split (p₁ + r₁) (p₂ + r₂) = (r₁, r₂))
    (hp : LhsSlope q u p₁ p₂) (hr : LhsSlope q u r₁ r₂) (hN : NTermGlue q u p₁ p₂ r₁ r₂) :
    LhsSlope q u (p₁ + r₁) (p₂ + r₂) := by
  intro f
  have hQ : Sym.Qop q u (p₁ + r₁) (p₂ + r₂)
      = ((1 - q) * (1 - u))⁻¹ • (Sym.Qop q u p₁ p₂ * Sym.Qop q u r₁ r₂
          - Sym.Qop q u r₁ r₂ * Sym.Qop q u p₁ p₂) := by
    rw [Sym.qop_of_coprime q u ha hc, hsplit]
    simp only [Nat.add_sub_cancel]
  rw [dminus_slopeOperator_mediant hp₁ hp₂ hr₁ hr₂ hdet hcp hcr hp hr f, hN f, hQ]
  simp only [LinearMap.smul_apply, LinearMap.sub_apply, Module.End.mul_apply]
  rw [C_smul, map_sub, ← smul_sub, smul_smul, smul_smul, neg_one_pow_succ_mul]
  exact mediant_scalar hq0 hu0 hq1 hu1 _ _

/-- **`NTermGlue` is the exact residual content of the mediant step**, not merely sufficient for it:
the clause at both parents *and* at the mediant forces it. The scalar
`-(qu)^{-1}(q/(1-q))` of `HJO.Mellit.dminus_slopeOperator_mediant` is invertible under the same four
hypotheses, so there the two statements are interchangeable.

So nothing weaker than `NTermGlue` will do. -/
theorem nTermGlue_of_lhsSlope (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) (hu1 : u ≠ 1)
    {p₁ p₂ r₁ r₂ : ℕ} (hp₁ : 1 ≤ p₁) (hp₂ : 1 ≤ p₂) (hr₁ : 1 ≤ r₁) (hr₂ : 1 ≤ r₂)
    (hdet : r₁ * p₂ = p₁ * r₂ + 1) (hcp : Nat.Coprime p₁ p₂) (hcr : Nat.Coprime r₁ r₂)
    (hc : Nat.Coprime (p₁ + r₁) (p₂ + r₂)) (ha : 1 < p₁ + r₁)
    (hsplit : Sym.Split (p₁ + r₁) (p₂ + r₂) = (r₁, r₂))
    (hp : LhsSlope q u p₁ p₂) (hr : LhsSlope q u r₁ r₂)
    (hab : LhsSlope q u (p₁ + r₁) (p₂ + r₂)) : NTermGlue q u p₁ p₂ r₁ r₂ := by
  have h1q : (1 : L) - q ≠ 0 := sub_ne_zero.mpr (Ne.symm hq1)
  have hs : ((-1 : L) ^ (p₂ + r₂ + 1) * (-((q * u)⁻¹ * (q / (1 - q))))) ≠ 0 := by
    refine mul_ne_zero (pow_ne_zero _ (neg_ne_zero.2 one_ne_zero)) ?_
    rw [neg_ne_zero]
    exact mul_ne_zero (inv_ne_zero (mul_ne_zero hq0 hu0)) (div_ne_zero hq0 h1q)
  intro f
  have hQ : Sym.Qop q u (p₁ + r₁) (p₂ + r₂)
      = ((1 - q) * (1 - u))⁻¹ • (Sym.Qop q u p₁ p₂ * Sym.Qop q u r₁ r₂
          - Sym.Qop q u r₁ r₂ * Sym.Qop q u p₁ p₂) := by
    rw [Sym.qop_of_coprime q u ha hc, hsplit]
    simp only [Nat.add_sub_cancel]
  -- the clause at the mediant, read against the computed sweep side
  have key := hab f
  rw [dminus_slopeOperator_mediant hp₁ hp₂ hr₁ hr₂ hdet hcp hcr hp hr f, smul_smul] at key
  -- the same value, computed from `HJO.Sym.Qop` with the claimed `N` term in place
  have key' : MvPolynomial.C (Sym.Qop q u (p₁ + r₁) (p₂ + r₂) f)
      = ((-1 : L) ^ (p₂ + r₂ + 1) * (-((q * u)⁻¹ * (q / (1 - q))))) •
        ((-1 : L) ^ (p₂ + r₂) •
            (MvPolynomial.C (Sym.Qop q u r₁ r₂ (Sym.Qop q u p₁ p₂ f)) : Total L)
          - (-1 : L) ^ (p₂ + r₂) •
            ((1 - u)⁻¹ • (MvPolynomial.C (Sym.Qop q u r₁ r₂ (Sym.Qop q u p₁ p₂ f)) : Total L)
              - (u / (1 - u)) •
                (MvPolynomial.C (Sym.Qop q u p₁ p₂ (Sym.Qop q u r₁ r₂ f)) : Total L))) := by
    rw [hQ]
    simp only [LinearMap.smul_apply, LinearMap.sub_apply, Module.End.mul_apply]
    rw [C_smul, map_sub, ← smul_sub, smul_smul, neg_one_pow_succ_mul]
    exact mediant_scalar hq0 hu0 hq1 hu1 _ _
  have hcancel := smul_right_injective (Total L) hs (key.symm.trans key')
  exact (sub_right_inj).1 hcancel

/-! ### General `f` is not the obstruction: reduction to products of `e_n` -/

/-- The clause at one `f`. `HJO.Mellit.LhsSlope` is this quantified over `f`, and the point of
naming it is that it is `L`-linear in `f` on both sides, which
`HJO.Mellit.lhsSlope_of_prod_elemSymm` exploits. -/
def LhsSlopeAt (q u : L) (a b : ℕ) (f : Sym.Lambda L) : Prop :=
  MvPolynomial.C (Sym.Qop q u a b f)
    = (-1 : L) ^ (b + 1) • dminus q 1 (slopeOperator q u 1 a b (slopeArg q u f))

theorem lhsSlope_iff_forall (q u : L) (a b : ℕ) :
    LhsSlope q u a b ↔ ∀ f : Sym.Lambda L, LhsSlopeAt q u a b f := Iff.rfl

omit [Algebra ℚ L] in
theorem slopeArg_add (q u : L) (f g : Sym.Lambda L) :
    slopeArg q u (f + g) = slopeArg q u f + slopeArg q u g := by
  rw [slopeArg_def, slopeArg_def, slopeArg_def, map_add, map_add, mul_add]

omit [Algebra ℚ L] in
theorem slopeArg_smul (q u : L) (c : L) (f : Sym.Lambda L) :
    slopeArg q u (c • f) = c • slopeArg q u f := by
  rw [slopeArg_def, slopeArg_def, C_smul, map_smul, mul_smul_comm]

omit [Algebra ℚ L] in
theorem slopeArg_zero (q u : L) : slopeArg q u (0 : Sym.Lambda L) = 0 := by
  rw [slopeArg_def, map_zero, map_zero, mul_zero]

/-- **The `f` satisfying the clause form a submodule of `Λ`.** Both sides of `LhsSlopeAt` are
`L`-linear in `f`: the left through `HJO.Sym.Qop` and `MvPolynomial.C`, the right through
`HJO.Mellit.slopeArg_add`/`HJO.Mellit.slopeArg_smul` and the two linear maps `Ξ^{(1)}_{a,b}` and
`d_-`. -/
noncomputable def lhsSlopeCarrier (q u : L) (a b : ℕ) : Submodule L (Sym.Lambda L) where
  carrier := {f | LhsSlopeAt q u a b f}
  zero_mem' := by
    simp only [Set.mem_ofPred_eq, LhsSlopeAt, map_zero, slopeArg_zero, smul_zero]
  add_mem' := by
    intro f g hf hg
    simp only [Set.mem_ofPred_eq, LhsSlopeAt] at hf hg ⊢
    rw [map_add, map_add, slopeArg_add, map_add, map_add, smul_add]
    exact congrArg₂ (· + ·) hf hg
  smul_mem' := by
    intro c f hf
    simp only [Set.mem_ofPred_eq, LhsSlopeAt] at hf ⊢
    rw [map_smul, C_smul, slopeArg_smul, map_smul, map_smul, smul_comm]
    exact congrArg (c • ·) hf

private theorem exists_list_nat_of_mem_range (l : List (Sym.Lambda L))
    (hl : ∀ y ∈ l, y ∈ Set.range fun i : ℕ => Sym.elemSymm L (i + 1)) :
    ∃ l' : List ℕ, l = l'.map fun i => Sym.elemSymm L (i + 1) := by
  induction l with
  | nil => exact ⟨[], rfl⟩
  | cons y t ih =>
    obtain ⟨i, rfl⟩ := hl y (List.mem_cons_self ..)
    obtain ⟨t', rfl⟩ := ih fun z hz => hl z (List.mem_cons_of_mem _ hz)
    exact ⟨i :: t', rfl⟩

/-- **It is enough to prove the clause on products of elementary symmetric functions.**

Both sides are `L`-linear in `f` (`HJO.Mellit.lhsSlopeCarrier`), the `e_{i+1}` generate `Λ` as an
`L`-algebra (`HJO.Sym.adjoin_elemSymm_eq_top`), and `Algebra.adjoin` is the span of the monoid
closure — so the products of the `e_{i+1}` span `Λ` as an `L`-module and the clause propagates.

**This settles which of the two generalisations is the hard one.** A general `f` is *bookkeeping*:
the clause reduces to `e`-monomials, and on an `e`-monomial `d^*_+` is known in closed form —
`HJO.Sweep.dplusStar_C_prod_elemSymm` expands an arbitrary one unconditionally, and `d^*_+` is an
`AlgHom` by `rfl` (`HJO.Sweep.dplusStarAlg_eq_dplusStar`), so a *list* product is the shape that
matches, via `map_list_prod`. The general **slope** is the content: nothing above reduces a slope to
smaller ones except `HJO.Mellit.lhsSlope_mediant`, whose residual hypothesis
`HJO.Mellit.nTermGlue_iff_lhsSlope` shows is the clause itself.

So the first concrete case — the `(2,3)` clause at general `f` — is reachable, and reaching it
is a finite computation once `z_1` is expanded on `y_1^2d^*_+{}^{(0)}(C(∏e))`; what it will *not* do
is generalise in the slope. -/
theorem lhsSlope_of_prod_elemSymm (q u : L) (a b : ℕ)
    (h : ∀ l : List ℕ,
      LhsSlopeAt q u a b ((l.map fun i : ℕ => Sym.elemSymm L (i + 1)).prod)) :
    LhsSlope q u a b := by
  intro f
  have hspan : f ∈ Submodule.span L
      (Submonoid.closure (Set.range fun i : ℕ => Sym.elemSymm L (i + 1)) : Set (Sym.Lambda L)) := by
    have hh := Algebra.adjoin_eq_span L (Set.range fun i : ℕ => Sym.elemSymm L (i + 1))
    rw [Sym.adjoin_elemSymm_eq_top] at hh
    rw [← hh]
    simp
  refine (?_ : Submodule.span L
      (Submonoid.closure (Set.range fun i : ℕ => Sym.elemSymm L (i + 1)) : Set (Sym.Lambda L))
      ≤ lhsSlopeCarrier q u a b) hspan
  rw [Submodule.span_le]
  intro x hx
  obtain ⟨l, hl, rfl⟩ := Submonoid.exists_list_of_mem_closure hx
  obtain ⟨l', rfl⟩ := exists_list_nat_of_mem_range l hl
  exact h l'

/-! ### What the residual identity is about: the `N` term is not independent data -/

/-- **`y_1N = P - ((1-q)/q)·y_1z_1` on the whole total space**, with `P = y_1d^*_+{}^{(0)}d_-^{(1)}`
and `N = d_-^{(2)}d^*_+{}^{(1)}` — and since the letter pair of `HJO.Sweep.slopeOperator` is
`YZ = -(qu)^{-1}y_1z_1`, this reads

`y_1·N(X) = y_1·d^*_+{}^{(0)}(d_-^{(1)}X) + u(1-q)·(YZ)(X)`.

**This is what `HJO.Mellit.NTermGlue` is about, and the answer is that it is not about `N`.** The
`N` term of the mediant step is the `P` term plus a multiple of the *two letters themselves*, so
once `HJO.Mellit.slopeEval_mediant` is applied it is the `P` term plus a multiple of the slope
operator at the mediant. No evaluation of `N` — not
`HJO.Sweep.zopOneStar_one_auxVar_pow_mul_C`, not `HJO.Sweep.zopOneStar_one_of_mem_piece` — can
therefore contribute anything the `P` half and `Ξ_{a,b}` do not already carry: see
`HJO.Mellit.nTerm_eq_of_lhsSlope`.

It is an identity on all of `HJO.Sweep.Total L`, with no restriction to `V_1`: it is `HJO.Sweep.zop`
at `k = 1` rearranged, the train being empty (`HJO.Braid.trainUp_self`).

**Genericity: three hypotheses are spent, and they are not all necessary.** The proof spends exactly
`u(1-q)·(qu)^{-1}(q/(1-q)) = 1`, which needs `q ≠ 0`, `u ≠ 0` and `q ≠ 1`. Evaluating at the
degenerate parameters, they are not on the same footing, and not all three are real exclusions:

* `q = 0` — a **real** exclusion. There `q/(1-q) = 0` and `(qu)^{-1} = 0`, so `z_1 = 0`, the `YZ`
  term vanishes and the statement degenerates to `y_1N = P`. That is false: at `X = y_1^2` with
  `u ≠ 0`, `N(y_1^2) = Ce_2` while `P(y_1^2) = y_1d^*_+{}^{(0)}(Ce_2)`, and
  `HJO.Sweep.dplusStar_C_elemSymm` at `n = 2`, `q = 0` gives
  `d^*_+(Ce_2) = Ce_2 - uy_1Ce_1 + (uy_1)^2`, which is not `Ce_2`.
* `q = 1` and `u = 0` — **artefacts of this proof, not exclusions.** At either, the displacement
  letter `(q-1)uy_1` of `HJO.Sweep.dplusStar_C_eq_starGamma` vanishes, so `d^*_+` is the identity on
  the constants; then `N(y_1^mCA) = C(B_mA) = d_-^{(1)}(y_1^mCA)` pushed forward, and both sides
  reduce to `y_1C(B_mA)` on every monomial of `V_1`, hence on `V_1` by linearity. So on `V_1` — the
  only place the mediant step reads this identity — the statement is true there too; it is the
  scalar cancellation above, not the identity, that fails.

Neither degenerate reading is formalized below; they are stated as what they are, an evaluation of
the hypotheses rather than a theorem. What *is* formalized needs all three, and its use in
`HJO.Mellit.nTerm_eq_of_lhsSlope` has them anyway. -/
theorem auxVar_mul_dminus_two_dplusStar_one (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1)
    (X : Total L) :
    (auxVar 1 : Total L) * dminus q 2 (dplusStar q u 1 X)
      = (auxVar 1 : Total L) * dplusStar q u 0 (dminus q 1 X)
        + (u * (1 - q)) • ((-LinearMap.mulLeft L (auxVar 1 : Total L))
            * ((q * u)⁻¹ • zop q u 1 1)) X := by
  have h1q : (1 : L) - q ≠ 0 := sub_ne_zero.mpr (Ne.symm hq1)
  have hz : zop q u 1 1 X
      = (q / (1 - q)) • (dplusStar q u 0 (dminus q 1 X) - dminus q 2 (dplusStar q u 1 X)) := by
    rw [zop_one, zopOneStar, show trainUpEnd q 1 1 = 1 from Braid.trainUp_self _ _ 1, mul_one]
    simp only [LinearMap.smul_apply, LinearMap.sub_apply, Module.End.mul_apply, pow_one,
      Nat.sub_self]
  simp only [Module.End.mul_apply, LinearMap.neg_apply, LinearMap.mulLeft_apply,
    LinearMap.smul_apply]
  rw [hz]
  simp only [mul_smul_comm, smul_sub, mul_sub, neg_sub]
  match_scalars <;> (field_simp; try ring)

/-- **The `N` term of the mediant step, with `N` eliminated.** Given the clause at both
Stern–Brocot parents,

`𝒩(f) = (-1)^{p₂+r₂}C(Q_rQ_pf) + u(1-q)·d_-(Ξ_{a,b}(y_1d^*_+Cf))`,

by `HJO.Mellit.auxVar_mul_dminus_two_dplusStar_one` and `HJO.Mellit.slopeEval_mediant`. So the
left-hand side of `HJO.Mellit.NTermGlue` is *determined* by the `P` half — which the induction
hypothesis already evaluates — together with the sweep side at the mediant, which is the thing being
computed. That is why `NTermGlue` cannot be split off and proved separately, and why
`HJO.Mellit.nTermGlue_iff_lhsSlope` is an equivalence rather than a reduction. -/
theorem nTerm_eq_of_lhsSlope (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1)
    {p₁ p₂ r₁ r₂ : ℕ} (hp₁ : 1 ≤ p₁) (hp₂ : 1 ≤ p₂) (hr₁ : 1 ≤ r₁) (hr₂ : 1 ≤ r₂)
    (hdet : r₁ * p₂ = p₁ * r₂ + 1) (hcp : Nat.Coprime p₁ p₂) (hcr : Nat.Coprime r₁ r₂)
    (hp : LhsSlope q u p₁ p₂) (hr : LhsSlope q u r₁ r₂) (f : Sym.Lambda L) :
    dminus q 1 (slopeOperator q u 1 r₁ r₂ ((auxVar 1 : Total L) *
        dminus q 2 (dplusStar q u 1 (slopeOperator q u 1 p₁ p₂ (slopeArg q u f)))))
      = (-1 : L) ^ (p₂ + r₂) •
          (MvPolynomial.C (Sym.Qop q u r₁ r₂ (Sym.Qop q u p₁ p₂ f)) : Total L)
        + (u * (1 - q)) •
          dminus q 1 (slopeOperator q u 1 (p₁ + r₁) (p₂ + r₂) (slopeArg q u f)) := by
  have h1q : (1 : L) - q ≠ 0 := sub_ne_zero.mpr (Ne.symm hq1)
  have hscal : (-(u * (1 - q))) * (-((q * u)⁻¹ * (q / (1 - q)))) = 1 := by
    field_simp
  have hcore := dminus_slopeOperator_mediant hp₁ hp₂ hr₁ hr₂ hdet hcp hcr hp hr f
  have h := congrArg (fun z : Total L => (-(u * (1 - q))) • z) hcore
  simp only [smul_smul, hscal, one_smul] at h
  linear_combination (norm := module) h

/-- **`NTermGlue` is equivalent to the clause at the mediant**, given the clause at both parents.
Both directions are already proved — `HJO.Mellit.lhsSlope_mediant` and
`HJO.Mellit.nTermGlue_of_lhsSlope` — and stating the equivalence is the point: together with
`HJO.Mellit.nTerm_eq_of_lhsSlope` it says the mediant step admits **no** decomposition into a
statement about `z_1`'s second half plus bookkeeping. The residual identity is the clause, no weaker
and no stronger, so the content is the commutator recursion of `HJO.Sym.Qop` for the sweep-side
composites `f ↦ ct(d_-(Ξ_{a,b}(y_1d^*_+Cf)))` and nothing else. -/
theorem nTermGlue_iff_lhsSlope (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) (hu1 : u ≠ 1)
    {p₁ p₂ r₁ r₂ : ℕ} (hp₁ : 1 ≤ p₁) (hp₂ : 1 ≤ p₂) (hr₁ : 1 ≤ r₁) (hr₂ : 1 ≤ r₂)
    (hdet : r₁ * p₂ = p₁ * r₂ + 1) (hcp : Nat.Coprime p₁ p₂) (hcr : Nat.Coprime r₁ r₂)
    (hc : Nat.Coprime (p₁ + r₁) (p₂ + r₂)) (ha : 1 < p₁ + r₁)
    (hsplit : Sym.Split (p₁ + r₁) (p₂ + r₂) = (r₁, r₂))
    (hp : LhsSlope q u p₁ p₂) (hr : LhsSlope q u r₁ r₂) :
    NTermGlue q u p₁ p₂ r₁ r₂ ↔ LhsSlope q u (p₁ + r₁) (p₂ + r₂) :=
  ⟨fun hN => lhsSlope_mediant hq0 hu0 hq1 hu1 hp₁ hp₂ hr₁ hr₂ hdet hcp hcr hc ha hsplit hp hr hN,
    fun hab => nTermGlue_of_lhsSlope hq0 hu0 hq1 hu1 hp₁ hp₂ hr₁ hr₂ hdet hcp hcr hc ha hsplit
      hp hr hab⟩

/-! ### The residual identity at `(2,3)`, read at the vacuum -/

/-- **The `(2,3)` instance of `HJO.Mellit.NTermGlue`, at `f = 1`, from the closed forms.**

At `(a,b) = (2,3)` the parent is `p = (1,2)` and its complement `r = Split 2 3 = (1,1)`
(`HJO.Sym.split_succ_one`), so `Ξ_r = 1`, `Q_p = D_2` and `Q_r = D_1`. At the vacuum the left-hand
side collapses to `-C(B_1e_2)`: `Ξ_{1,2}(y_1) = -y_1^2`, then
`HJO.Sweep.dminus_two_dplusStar_one_auxVar_pow_mul_C` gives `N(y_1^2) = Ce_2`, and
`HJO.Sweep.dminus_one_auxVar_pow_mul_C` with `HJO.Sym.bop_natCast` gives the outer `d_-`. The
right-hand side is `-(1-u)^{-1}D_1(e_2) - u(1-u)^{-1}D_2(e_1)` by `HJO.Sym.dop_apply_one`.

So the identity asserted here is

`B_1(e_2) = (1-u)^{-1}D_1(e_2) + u(1-u)^{-1}D_2(e_1)`,

between the Hall--Littlewood operator and two values of the basic operator, and it holds because
`M - 1 + u = -q(1-u)` and `(q+u) - u = q`. **This is the check that the two coefficients
`(1-u)^{-1}` and `u/(1-u)` of `NTermGlue` are the right ones** — they are not determined by
`HJO.Mellit.lhsSlope_mediant`, which only fixes their difference, and a wrong split between them
would pass every scalar test in this file and fail here.

Only `u ≠ 1` is needed: the left-hand side carries no inverse at all. -/
theorem nTermGlue_two_three_apply_one (hu1 : u ≠ 1) :
    dminus q 1 (slopeOperator q u 1 1 1 ((auxVar 1 : Total L) *
        dminus q 2 (dplusStar q u 1 (slopeOperator q u 1 1 2 (slopeArg q u (1 : Sym.Lambda L))))))
      = (-1 : L) ^ (2 + 1) •
          ((1 - u)⁻¹ • (MvPolynomial.C (Sym.Qop q u 1 1 (Sym.Qop q u 1 2 (1 : Sym.Lambda L)))
              : Total L)
            - (u / (1 - u)) •
              (MvPolynomial.C (Sym.Qop q u 1 2 (Sym.Qop q u 1 1 1)) : Total L)) := by
  have h1u : (1 : L) - u ≠ 0 := sub_ne_zero.mpr (Ne.symm hu1)
  have hd1 : Sym.Dop q u 1 (1 : Sym.Lambda L) = -Sym.elemSymm L 1 := by
    rw [Sym.dop_apply_one]; ring
  have hd2 : Sym.Dop q u 2 (1 : Sym.Lambda L) = Sym.elemSymm L 2 := by
    rw [Sym.dop_apply_one]; ring
  have hd3 : Sym.Dop q u 3 (1 : Sym.Lambda L) = -Sym.elemSymm L 3 := by
    rw [Sym.dop_apply_one]; ring
  have hd2e1 : Sym.Dop q u 2 (Sym.elemSymm L 1)
      = Sym.elemSymm L 1 * Sym.elemSymm L 2 - ((1 - q) * (1 - u)) • Sym.elemSymm L 3 := by
    have h := Sym.dop_elemSymm_one_mul q u 2 (1 : Sym.Lambda L)
    rw [mul_one, hd2, hd3, smul_neg, ← sub_eq_add_neg] at h
    exact h
  -- the slope operator at the parent, on the vacuum
  have hxi : slopeOperator q u 1 1 2 (slopeArg q u (1 : Sym.Lambda L))
      = -((auxVar 1 : Total L) ^ 2 * MvPolynomial.C (1 : Sym.Lambda L)) := by
    rw [slopeArg_one, slopeOperator_eq_slopeEval, Mellit.slopeEval_one_left _ _ (by omega),
      show (2 : ℕ) - 1 = 1 from rfl, pow_one, LinearMap.neg_apply, LinearMap.mulLeft_apply,
      MvPolynomial.C_1, mul_one, sq]
  -- the `N` term on the vacuum is `Ce_2`
  have hb2 : Sym.Bop q ((2 : ℕ) : ℤ) (1 : Sym.Lambda L) = Sym.elemSymm L 2 := by
    rw [Sym.bop_one, Sym.elemSymmAlt_natCast]
    norm_num
  have hN : dminus q 2 (dplusStar q u 1
        (-((auxVar 1 : Total L) ^ 2 * MvPolynomial.C (1 : Sym.Lambda L))))
      = -(MvPolynomial.C (Sym.elemSymm L 2) : Total L) := by
    rw [map_neg, map_neg, dminus_two_dplusStar_one_auxVar_pow_mul_C, MvPolynomial.C_1,
      show dplusStar q u 0 (1 : Total L) = 1 from by rw [dplusStar_apply, map_one, map_one],
      ← MvPolynomial.C_1, bopExt_C, hb2]
  rw [hxi, hN, mul_neg, show slopeOperator q u 1 1 1 = 1 from slopeOperator_one_one q u 1,
    Module.End.one_apply, map_neg,
    show (auxVar 1 : Total L) * MvPolynomial.C (Sym.elemSymm L 2)
      = (auxVar 1 : Total L) ^ 1 * MvPolynomial.C (Sym.elemSymm L 2) from by rw [pow_one],
    dminus_one_auxVar_pow_mul_C, Sym.bop_natCast, Sym.qop_one, Sym.qop_one, hd1, hd2, map_neg,
    hd2e1, Sym.dop_one_elemSymm_two q u, Sym.dop_one_elemSymm_two q 0]
  simp only [map_add, map_sub, map_neg, C_smul]
  match_scalars <;> (field_simp; try ring)

/-! ### Reading the clause at the vacuum -/

/-- **The clause implies the base case of `HJO.Mellit.lhsRewrite_sweepWitness` in the shape
`HJO.Mellit.qop_apply_one_of_lhsComputes` asks for.** At `α = (1)` the stage word is
`HJO.Mellit.stageWordTotal_singleton_one`, whose `-(-1)^{a-1}` cancels the outer sign; the
descending train at `(1,1)` is the identity and `d^*_+` fixes the unit
(`HJO.Mellit.slopeArg_one`), so what is left is the clause at `f = 1`.

`HJO.Mellit.lhsBase_two_three` and `HJO.Mellit.lhsBase_three_four` are this read at `(2,3)` and
`(3,4)`; conversely they cannot *start* the induction, since they fix `f = 1`. -/
theorem lhsBase_of_lhsSlope (q u : L) {a b : ℕ} (h : LhsSlope q u a b) :
    (-1 : L) ^ b • Sym.Qop q u a b (1 : Sym.Lambda L)
      = (-1 : L) ^ (a - 1 : ℕ) •
        MvPolynomial.constantCoeff (lowerRun q 1 (stageWordTotal q u a b [1])) := by
  have hd : dminus q 1 (slopeOperator q u 1 a b (slopeArg q u (1 : Sym.Lambda L)))
      = (-1 : L) ^ (b + 1) • (MvPolynomial.C (Sym.Qop q u a b (1 : Sym.Lambda L)) : Total L) := by
    rw [h 1, smul_smul, neg_one_pow_mul_self, one_smul]
  rw [stageWordTotal_singleton_one, show lowerRun q 1 = dminus q 1 from by simp [lowerRun],
    show trainDownEnd q 1 1 = 1 from Braid.trainDown_self _ _ 1, Module.End.one_apply,
    show (auxVar 1 : Total L) * dplusStar q u 0 (1 : Total L)
      = slopeArg q u (1 : Sym.Lambda L) from by rw [slopeArg_def, MvPolynomial.C_1],
    map_neg, map_smul, hd]
  simp only [MvPolynomial.constantCoeff_smul, MvPolynomial.constantCoeff_C, smul_smul, ← neg_smul]
  congr 1
  rw [mul_neg, ← mul_assoc, neg_one_pow_mul_self, one_mul, pow_succ]
  ring

end HJO.Mellit
