/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitSlopeLadderLhs
public import HJO.Shuffle.MellitLhsSlopeMediant
public import HJO.Shuffle.MellitQopThreeFour
public import HJO.Symmetric.DiffOrder
public meta import HJO.Attr

/-! # The `(2,3)` ladder at a non-vacuum argument: the `e_1` ray closes, the others do not

`HJO.Sym.qop_two_three_axis_eq_ladder` (`HJO/Shuffle/MellitSlopeLadderLhs.lean`) makes every
collinear slope operator a normalised bracket of one ladder rung against `D_1`,

  `Q_{2k,3k} = M⁻¹ ( L_{k-1} D_1 - D_1 L_{k-1} )`,  `L_j = (ad_{2,3})^j (D_2)`,  `k ≥ 1`,

with no case split, and `HJO.Sym.theta_mem_dopTwoAlgebra` puts the whole image of a `(2,3)` slope
homomorphism inside `L[D_1, D_2]`. Because `Θ` is an algebra map into **operators**, an expansion of
`CopComp q α 1` in the axis generators does not by itself deliver `Θ(CopComp q α 1)(1)`: each factor
of the resulting word is handed a non-vacuum vector. This file evaluates the ladder at non-vacuum
arguments, and says exactly how far that goes.

## The engine: `e_1` is the index shift

`HJO.Sym.dop_elemSymm_one_mul` reads `D_k(e_1f) = e_1D_kf + MD_{k+1}f`. As an
operator identity that is a statement about one commutator, and it is the only input this file has:

  `HJO.Sym.shiftStep_dop`:  `T(D_k) = -M·D_{k+1}`,   `T A := ad(e_1) A = E_1A - AE_1`,

with `HJO.DiffOrder.ad` the commutator against a multiplication operator. `HJO.DiffOrder.ad_mul`
makes `T` a derivation of the operator algebra, so `T` is a *derivation that shifts the index of
`HJO.Sym.DopInt` by one*. Everything below is that one fact plus Leibniz.

Four consequences, all of them unconditional in `q` and `u`:

* `HJO.Sym.apply_elemSymm_one_mul` — `A(e_1f) = e_1·Af - (TA)f` for **every** operator `A`. This is
  `HJO.DiffOrder.ad_apply` rearranged; the content is that `T` of a `D`-word is again a `D`-word.
* `HJO.Sym.apply_elemSymm_one_pow_mul` — the Taylor formula on the `e_1` ray,
  `A(e_1^m f) = ∑_{i≤m} (-1)^i binom(m,i)·e_1^{m-i}·(T^iA)f`. Iterating the one-step rule and
  collecting by Pascal. Note the spelling: keeping the *unnormalised* `T = ad(e_1)` rather than
  `M⁻¹ad(e_1)` makes this true with no hypothesis on `q, u` at all, the factors of `M` being carried
  by `HJO.Sym.iterate_shiftStep_dop` (`T^i(D_k) = (-M)^i·D_{k+i}`) where they are visible.
* `HJO.Sym.shiftStep_mem_dopAlgebra` — `T` maps `HJO.Sym.DopAlgebra` into itself, by induction over
  `Algebra.adjoin`. With `HJO.Sym.dopTwoAlgebra_le_dopAlgebra` this covers `L[D_1,D_2]` and hence
  the whole image of `Θ`.
* `HJO.Sym.shiftStep_ladderTwoThree` — `T` against one rung of the ladder:
  `T(ad_{2,3}A) = ad_{2,3}(TA) + M⁻¹(A·T(Q_{2,3}) - T(Q_{2,3})·A)`, so the `T`-images of the rungs
  satisfy a recursion of the same shape as the rungs themselves, driven by the single new operator
  `T(Q_{2,3}) = -(D_3D_1 - D_1D_3)` (`HJO.Sym.shiftStep_qop_two_three`).

## What that gives at `(2,3)`

`HJO.Sym.shiftStep_qop_two_three_axis` closes the bracket at every `k ≥ 1`:

  `T(Q_{2k,3k}) = M⁻¹((TL_{k-1})D_1 - D_1(TL_{k-1})) - (L_{k-1}D_2 - D_2L_{k-1})`,

an operator of `L[D_1,D_2]` again, with `TL_{k-1}` computed by the recursion above from
`TL_0 = -M·D_3` (`HJO.Sym.shiftStep_iterate_ladderTwoThree`,
`HJO.Sym.shiftStep_iterate_ladderTwoThree_zero`). So:

* `HJO.Sym.qop_two_three_axis_apply_elemSymm_one` — `Q_{2k,3k}(e_1)` in closed form at **every**
  `k ≥ 1`, as `e_1·Q_{2k,3k}(1)` corrected by two brackets read at the vacuum.
* `HJO.Sym.qop_two_three_axis_apply_elemSymm_one_pow` — `Q_{2k,3k}(e_1^m)` at every `k` and `m`, as
  the binomial sum in the vacuum values of `T^iQ_{2k,3k}`.
* `HJO.Sym.theta_apply_elemSymm_one_pow` — the same for every value of every `(2,3)` slope
  homomorphism, together with the statement that each operator the sum names is still in
  `HJO.Sym.DopAlgebra`. This is the closure the creation side wanted: on the `e_1` ray, no value of
  `Θ` ever leaves the algebra generated by the basic operators, and every such value is a
  combination of **vacuum** values of operators in that algebra.

The reduction is *not* to the orbit `Q_{2,3}^m(1)`, and it cannot be: that is exactly what
`HJO.Sym.collinearBracket_apply_one_not_determined_by_orbit` forbids. It is to the vacuum values of
a strictly larger, explicitly generated family — the words in `D_1, D_2` whose length grows with the
degree, which is the object `HJO/Shuffle/MellitSlopeLadderLhs.lean` already identified as what
the creation side actually needs.

## The pin

`HJO.Sym.qop_two_three_apply_elemSymm_one_pin` recomputes `Q_{2,3}(e_1)` by this route alone —
`HJO.Sym.apply_elemSymm_one_mul` at `f = 1` and `HJO.Sym.shiftStep_qop_two_three`, giving
`Q_{2,3}(e_1) = e_1·Q_{2,3}(1) - D_3(e_1) + D_1(e_3)` — and then evaluates that from the Pieri rule
and the vacuum values, arriving at the expression
`HJO.Sym.qop_two_three_apply_elemSymm_one` obtained in
`HJO/Shuffle/MellitQopThreeFour.lean` by grinding the commutator. The two routes share nothing
but `HJO.Sym.DopInt` itself, so the agreement of all four coefficients — including the `e_4`
coefficient, which needs `κ(e_3)` on one side and `κ(e_1)` alone on the other — pins the signs and
the index bookkeeping of the whole chain.

## What is *not* obtained, and why

**The clause at general `α` is not obtained**, and the obstruction is sharp rather than a matter of
effort. `Λ` is generated by `e_1, e_2, e_3, …`, and the powers `e_1^m` span only `L[e_1]`, a single
line of generators. Passing to a general `h`-monomial needs the shift in the `e_n` direction for
`n ≥ 2`, and there is no such shift *inside the operator algebra*:

  `HJO.Sym.ad_elemSymm_dop`:  `ad(e_n)(D_k) = -∑_{1≤s≤n} κ(e_s)·E_{n-s}D_{k+s}`

— every term carries a multiplication operator `E_{n-s}` standing to the **left** of a basic
operator, and only at `n = 1` is that factor `E_0 = 1`. So `ad(e_n)` does not map
`HJO.Sym.DopAlgebra` into itself for `n ≥ 2`, there is no Taylor formula in the `e_n` direction with
coefficients in that algebra, and the induction that produced
`HJO.Sym.apply_elemSymm_one_pow_mul` has nothing to run on. What `HJO.Sym.ad_elemSymm_dop` does
supply is the straightening rule for the *larger* algebra generated by the basic operators together
with the multiplication operators; whether that algebra is spanned by `E_g·(D\text{-word})`, which
would settle a general argument, is not proved here.

Nothing in this file touches the equation the `hlhs` clause asserts. It computes one side of it on a
ray.

## Genericity

`HJO.Sym.shiftStep_dop`, `HJO.Sym.iterate_shiftStep_dop`, `HJO.Sym.apply_elemSymm_one_mul`,
`HJO.Sym.apply_elemSymm_one_pow_mul`, `HJO.Sym.shiftStep_bracket_dop_two_one`,
`HJO.Sym.shiftStep_ladderTwoThree`, `HJO.Sym.shiftStep_iterate_ladderTwoThree`,
`HJO.Sym.shiftStep_iterate_ladderTwoThree_zero`, `HJO.Sym.ad_elemSymm_dop`,
`HJO.Sym.shiftStep_mem_dopAlgebra`, `HJO.Sym.iterate_shiftStep_mem_dopAlgebra`,
`HJO.Sym.dopTwoAlgebra_le_dopAlgebra`, `HJO.Sym.qop_two_three_axis_apply_elemSymm_one_pow`,
`HJO.Sym.qop_two_three_axis_mem_dopAlgebra`: **none**. Every `M⁻¹` that appears is `HJO.Sym.Qop`'s
own and is carried in the statement rather than cancelled, so at `M = 0` these read `0 = 0` for
`k ≥ 2` — `HJO.Sym.Qop`'s totalisation, true and empty, not a false clause. In particular
`HJO.Sym.qop_two_three_axis_apply_elemSymm_one_pow` is unconditional *and* degenerate at `M = 0`,
where `T` kills every generator and both sides vanish.

`HJO.Sym.shiftStep_qop_two_three`, `HJO.Sym.shiftStep_qop_two_three_axis`,
`HJO.Sym.qop_two_three_axis_apply_elemSymm_one`,
`HJO.Sym.qop_two_three_apply_elemSymm_one_of_shiftStep`,
`HJO.Sym.elemSymm_one_mul_qop_two_three_sub_dop_three_add_dop_one`,
`HJO.Sym.qop_two_three_apply_elemSymm_one_pin`: `M = (1-q)(1-u) ≠ 0`, and nothing else. It is used
for exactly one thing, the cancellation `M⁻¹M = 1` that turns `M⁻¹·(-M)·B` into `-B`; the hypothesis
is explicit in each statement and no letter here silently becomes the zero map. `M ≠ 0` is `q ≠ 1`
and `u ≠ 1`, and holds at algebraically independent `q, u`.

`HJO.Sym.theta_apply_elemSymm_one_pow`: `CharZero L`, `qu ≠ 0` and `(qu)^{j+1} ≠ 1` for every `j` —
verbatim `HJO.Sym.theta_mem_dopTwoAlgebra`'s, i.e. the free generation of `Λ` by the axis
generators, without which `Θf` is not determined at all. Algebraic independence of `q, u` supplies
them. The evaluation half of the conjunction needs nothing; the membership half needs all three.

## Implementation notes

These are structural facts about `HJO.Sym.DopInt`, `HJO.Sym.Qop`, `HJO.Sym.DopAlgebra` and
`HJO.Sym.IsSlopeHom`, and a negative fact about one route.

## References

The objects involved are `HJO.Sym.DopInt`, `HJO.Sym.Qop`, `HJO.Sym.DopAlgebra`,
`HJO.Sym.IsSlopeHom`, `HJO.Sym.axisGen`, `HJO.Sym.Cop`,
`HJO.Sym.plethShift`, `HJO.Sym.dop_elemSymm_one_mul`, `HJO.Sym.coprime_ladder`,
`HJO.Mellit.lhsRewrite_sweepWitness`.
-/

@[expose] public section

namespace HJO.Sym

open HJO.Bglx HJO.DiffOrder

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- **The shift step `T`**: the commutator against multiplication by `e_1`,
`TA = e_1A - Ae_1`, as a map on the operators of `Λ`. `HJO.Sym.shiftStep_dop` is what earns the
name: on a basic operator of `HJO.Sym.DopInt` it is `-M·D_{k+1}`, so `T` is a derivation of the
operator algebra that moves the index of `HJO.Sym.DopInt` up by one. -/
noncomputable def shiftStep (L : Type*) [Field L] [Algebra ℚ L] :
    Module.End L (Lambda L) → Module.End L (Lambda L) := fun A => ad (elemSymm L 1) A

/-- The shift step is `HJO.DiffOrder.ad` at `e_1`, by definition. -/
theorem shiftStep_def (A : Module.End L (Lambda L)) :
    shiftStep L A = ad (elemSymm L 1) A := rfl

/-- The shift step evaluated on a symmetric function. -/
theorem shiftStep_apply (A : Module.End L (Lambda L)) (f : Lambda L) :
    shiftStep L A f = elemSymm L 1 * A f - A (elemSymm L 1 * f) := rfl

/-- The shift step respects differences. -/
theorem shiftStep_sub (A B : Module.End L (Lambda L)) :
    shiftStep L (A - B) = shiftStep L A - shiftStep L B := ad_sub _ A B

/-- The shift step respects scalars. -/
theorem shiftStep_smul (a : L) (A : Module.End L (Lambda L)) :
    shiftStep L (a • A) = a • shiftStep L A := ad_smul _ a A

/-- **The shift step is a derivation**, from `HJO.DiffOrder.ad_mul`. This is the Leibniz rule every
recursion below runs on. -/
theorem shiftStep_mul (A B : Module.End L (Lambda L)) :
    shiftStep L (A * B) = shiftStep L A * B + A * shiftStep L B := ad_mul _ A B

/-- The shift step respects negation. -/
theorem shiftStep_neg (A : Module.End L (Lambda L)) :
    shiftStep L (-A) = -shiftStep L A := map_neg (ad (elemSymm L 1)) A

/-- **The whole engine: `e_1` shifts the index of a basic operator.** `T(D_k) = -M·D_{k+1}`, which
is `HJO.Sym.dop_elemSymm_one_mul` read as a statement about one commutator. Unconditional in `q` and
`u`; at `M = 0` the shift step kills every generator. -/
theorem shiftStep_dop (q u : L) (k : ℕ) :
    shiftStep L (Dop q u k) = -(((1 - q) * (1 - u)) • Dop q u (k + 1)) := by
  refine LinearMap.ext fun f => ?_
  rw [shiftStep_apply, dop_elemSymm_one_mul]
  simp only [LinearMap.neg_apply, LinearMap.smul_apply]
  abel

/-- **Iterating the shift step on a basic operator just moves the index.** The factors of `M` are
carried here, in the coefficient `(-M)^i`, rather than divided out of the step; that is what keeps
`HJO.Sym.apply_elemSymm_one_pow_mul` free of any hypothesis on `q` and `u`. -/
theorem iterate_shiftStep_dop (q u : L) (k i : ℕ) :
    (shiftStep L)^[i] (Dop q u k) = (-((1 - q) * (1 - u))) ^ i • Dop q u (k + i) := by
  induction i with
  | zero => rw [Function.iterate_zero_apply, pow_zero, one_smul, Nat.add_zero]
  | succ i ih =>
    rw [Function.iterate_succ_apply', ih, shiftStep_smul, shiftStep_dop, smul_neg, smul_smul,
      pow_succ, show k + i + 1 = k + (i + 1) from by omega]
    rw [show (-((1 - q) * (1 - u))) ^ i * ((1 - q) * (1 - u))
      = -((-((1 - q) * (1 - u))) ^ i * -((1 - q) * (1 - u))) from by ring, neg_smul, neg_neg]

/-- **The one-step evaluation rule at a non-vacuum argument.** `A(e_1f) = e_1·Af - (TA)f`, for
*every* operator `A` and every `f` — a rearrangement of `HJO.DiffOrder.ad_apply`, whose content is
supplied by `HJO.Sym.shiftStep_dop`: on the operators this file cares about, `TA` is again a word in
the basic operators. Unconditional. -/
theorem apply_elemSymm_one_mul (A : Module.End L (Lambda L)) (f : Lambda L) :
    A (elemSymm L 1 * f) = elemSymm L 1 * A f - shiftStep L A f := by
  rw [shiftStep_apply]; abel

omit [Algebra ℚ L] in
private theorem pascal_telescope (m : ℕ) (X : ℕ → Lambda L) :
    (∑ i ∈ Finset.range (m + 1), ((-1 : L) ^ i * (m.choose i : L)) • X i)
      - (∑ i ∈ Finset.range (m + 1), ((-1 : L) ^ i * (m.choose i : L)) • X (i + 1))
    = ∑ i ∈ Finset.range (m + 2), ((-1 : L) ^ i * ((m + 1).choose i : L)) • X i := by
  have hR : ∑ i ∈ Finset.range (m + 2), ((-1 : L) ^ i * ((m + 1).choose i : L)) • X i
      = (∑ i ∈ Finset.range (m + 1),
          ((-1 : L) ^ (i + 1) * ((m + 1).choose (i + 1) : L)) • X (i + 1)) + X 0 := by
    rw [Finset.sum_range_succ']; simp
  have hR2 : (∑ i ∈ Finset.range (m + 1),
        ((-1 : L) ^ (i + 1) * ((m + 1).choose (i + 1) : L)) • X (i + 1))
      = (∑ i ∈ Finset.range m, ((-1 : L) ^ (i + 1) * ((m + 1).choose (i + 1) : L)) • X (i + 1))
        + -(((-1 : L) ^ m) • X (m + 1)) := by
    rw [Finset.sum_range_succ, Nat.choose_self, Nat.cast_one, mul_one, pow_succ, mul_neg_one,
      neg_smul]
  have hL1 : ∑ i ∈ Finset.range (m + 1), ((-1 : L) ^ i * (m.choose i : L)) • X i
      = (∑ i ∈ Finset.range m, ((-1 : L) ^ (i + 1) * (m.choose (i + 1) : L)) • X (i + 1))
        + X 0 := by
    rw [Finset.sum_range_succ']; simp
  have hL2 : (∑ i ∈ Finset.range (m + 1), ((-1 : L) ^ i * (m.choose i : L)) • X (i + 1))
      = (∑ i ∈ Finset.range m, ((-1 : L) ^ i * (m.choose i : L)) • X (i + 1))
        + ((-1 : L) ^ m) • X (m + 1) := by
    rw [Finset.sum_range_succ]; simp
  have hmain : (∑ i ∈ Finset.range m, ((-1 : L) ^ (i + 1) * (m.choose (i + 1) : L)) • X (i + 1))
      - (∑ i ∈ Finset.range m, ((-1 : L) ^ i * (m.choose i : L)) • X (i + 1))
      = ∑ i ∈ Finset.range m,
          ((-1 : L) ^ (i + 1) * ((m + 1).choose (i + 1) : L)) • X (i + 1) := by
    rw [← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun i _ => ?_
    have hc : ((-1 : L) ^ (i + 1) * (m.choose (i + 1) : L)) - ((-1 : L) ^ i * (m.choose i : L))
        = (-1 : L) ^ (i + 1) * ((m + 1).choose (i + 1) : L) := by
      rw [Nat.choose_succ_succ m i]
      push_cast
      ring
    rw [← sub_smul, hc]
  rw [hR, hR2, hL1, hL2, ← hmain]
  abel

/-- **The Taylor formula in the `e_1` direction.**

`A(e_1^mf) = ∑_{i≤m} (-1)^i binom(m,i)·e_1^{m-i}·(T^iA)f`

for every operator `A`, every `m` and every `f`: iterate `HJO.Sym.apply_elemSymm_one_mul` and
collect by Pascal's rule. At `f = 1` the right-hand side reads only *vacuum* values, of the iterated
shifts of `A`. Unconditional in `q` and `u` — the spelling with the unnormalised step is what buys
that, the factors of `M` being carried by `HJO.Sym.iterate_shiftStep_dop`. -/
theorem apply_elemSymm_one_pow_mul (A : Module.End L (Lambda L)) (m : ℕ) (f : Lambda L) :
    A (elemSymm L 1 ^ m * f)
      = ∑ i ∈ Finset.range (m + 1), ((-1 : L) ^ i * (m.choose i : L)) •
          (elemSymm L 1 ^ (m - i) * ((shiftStep L)^[i] A) f) := by
  induction m generalizing A with
  | zero => simp
  | succ m ih =>
    have hstep : A (elemSymm L 1 ^ (m + 1) * f)
        = elemSymm L 1 * A (elemSymm L 1 ^ m * f) - shiftStep L A (elemSymm L 1 ^ m * f) := by
      rw [pow_succ', mul_assoc, apply_elemSymm_one_mul]
    have hX1 : ∀ i ∈ Finset.range (m + 1),
        elemSymm L 1 * (((-1 : L) ^ i * (m.choose i : L)) •
            (elemSymm L 1 ^ (m - i) * ((shiftStep L)^[i] A) f))
          = ((-1 : L) ^ i * (m.choose i : L)) •
              (elemSymm L 1 ^ (m + 1 - i) * ((shiftStep L)^[i] A) f) := by
      intro i hi
      rw [Finset.mem_range] at hi
      rw [mul_smul_comm, ← mul_assoc, ← pow_succ', show m - i + 1 = m + 1 - i from by omega]
    have hX2 : ∀ i ∈ Finset.range (m + 1),
        ((-1 : L) ^ i * (m.choose i : L)) •
            (elemSymm L 1 ^ (m - i) * ((shiftStep L)^[i] (shiftStep L A)) f)
          = ((-1 : L) ^ i * (m.choose i : L)) •
              (elemSymm L 1 ^ (m + 1 - (i + 1)) * ((shiftStep L)^[i + 1] A) f) := by
      intro i _
      rw [← Function.iterate_succ_apply, show m + 1 - (i + 1) = m - i from by omega]
    rw [hstep, ih A, ih (shiftStep L A), Finset.mul_sum, Finset.sum_congr rfl hX1,
      Finset.sum_congr rfl hX2]
    exact pascal_telescope m fun i => elemSymm L 1 ^ (m + 1 - i) * ((shiftStep L)^[i] A) f

/-! ### The shift step preserves the algebra generated by the basic operators -/

/-- The shift step kills the identity operator: multiplication operators commute with it. -/
theorem shiftStep_one : shiftStep L (1 : Module.End L (Lambda L)) = 0 := by
  rw [shiftStep_def, ad_def, mul_one, one_mul, sub_self]

/-- The shift step respects sums. -/
theorem shiftStep_add (A B : Module.End L (Lambda L)) :
    shiftStep L (A + B) = shiftStep L A + shiftStep L B := ad_add _ A B

/-- The two-generator algebra of `HJO/Shuffle/MellitSlopeLadderLhs.lean` sits inside the full
operator algebra `HJO.Sym.DopAlgebra`, so everything proved about the latter applies to the image of
a `(2,3)` slope homomorphism. -/
theorem dopTwoAlgebra_le_dopAlgebra (q u : L) : dopTwoAlgebra q u ≤ DopAlgebra q u := by
  rw [dopTwoAlgebra]
  refine Algebra.adjoin_le ?_
  rintro A (rfl | rfl)
  · exact dop_mem_dopAlgebra q u 1
  · exact dop_mem_dopAlgebra q u 2

/-- **The shift step never leaves the algebra generated by the basic operators.** Induction over
`Algebra.adjoin`: on a generator it is `HJO.Sym.shiftStep_dop`, on a scalar it is zero, and on a
product it is Leibniz. Unconditional in `q` and `u`. This is the structural reason the `e_1`
recursion closes. -/
theorem shiftStep_mem_dopAlgebra (q u : L) {A : Module.End L (Lambda L)}
    (hA : A ∈ DopAlgebra q u) : shiftStep L A ∈ DopAlgebra q u := by
  induction hA using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨k, rfl⟩ := hx
    rw [shiftStep_dop]
    exact neg_mem (Subalgebra.smul_mem _ (dop_mem_dopAlgebra q u (k + 1)) _)
  | algebraMap r =>
    rw [Algebra.algebraMap_eq_smul_one, shiftStep_smul, shiftStep_one, smul_zero]
    exact zero_mem _
  | add x y _ _ ihx ihy =>
    rw [shiftStep_add]
    exact add_mem ihx ihy
  | mul x y hx hy ihx ihy =>
    rw [shiftStep_mul]
    exact add_mem (mul_mem ihx hy) (mul_mem hx ihy)

/-- Every iterate of the shift step stays in `HJO.Sym.DopAlgebra`. -/
theorem iterate_shiftStep_mem_dopAlgebra (q u : L) {A : Module.End L (Lambda L)}
    (hA : A ∈ DopAlgebra q u) (i : ℕ) : (shiftStep L)^[i] A ∈ DopAlgebra q u := by
  induction i with
  | zero => rwa [Function.iterate_zero_apply]
  | succ i ih => rw [Function.iterate_succ_apply']; exact shiftStep_mem_dopAlgebra q u ih

/-! ### Why only the `e_1` direction closes -/

/-- **The general Pieri commutator, as an operator identity — and the precise obstruction off the
`e_1` ray.**

`ad(e_n)(D_k) = -∑_{1≤s≤n} κ(e_s)·E_{n-s}D_{k+s}`,

with `κ = HJO.Bglx.paramPleth` and `E_m` multiplication by `e_m`. This is `HJO.Sym.dop_elemSymm_mul`
with its `s = 0` term moved across. Read it as a statement about *where* the commutator lands: every
term carries a multiplication operator standing to the **left** of a basic operator, and only at
`n = 1`, where the sum has one term and `E_0 = 1`, is that factor absent. So `ad(e_n)` does not map
`HJO.Sym.DopAlgebra` into itself for `n ≥ 2`, and the induction behind
`HJO.Sym.apply_elemSymm_one_pow_mul` has no analogue in the `e_n` direction. Unconditional in `q`
and `u`. -/
theorem ad_elemSymm_dop (q u : L) (k n : ℕ) :
    ad (elemSymm L n) (Dop q u k)
      = -∑ s ∈ Finset.range n, paramPleth q u (elemSymm L (s + 1)) •
          (LinearMap.mulLeft L (elemSymm L (n - (s + 1))) * Dop q u (k + (s + 1))) := by
  refine LinearMap.ext fun f => ?_
  rw [ad_apply, dop_elemSymm_mul, Finset.sum_range_succ']
  simp only [paramPleth_elemSymm_zero, one_smul, Nat.sub_zero, Nat.add_zero,
    LinearMap.neg_apply, LinearMap.sum_apply, LinearMap.smul_apply, Module.End.mul_apply,
    LinearMap.mulLeft_apply]
  abel

/-! ### The shift step on the base rung of the `(2,3)` ladder -/

/-- The shift step on the bracket `D_2D_1 - D_1D_2` raises both indices of the left factor at once:
the two cross terms `D_2D_2` cancel, leaving `-M(D_3D_1 - D_1D_3)`. Unconditional in `q` and `u`. -/
theorem shiftStep_bracket_dop_two_one (q u : L) :
    shiftStep L (Dop q u 2 * Dop q u 1 - Dop q u 1 * Dop q u 2)
      = (-((1 - q) * (1 - u))) • (Dop q u 3 * Dop q u 1 - Dop q u 1 * Dop q u 3) := by
  rw [shiftStep_sub, shiftStep_mul, shiftStep_mul, shiftStep_dop, shiftStep_dop]
  simp only [neg_mul, mul_neg, smul_mul_assoc, mul_smul_comm, smul_sub, neg_smul]
  abel

/-- **The shift step on the base rung**: `T(Q_{2,3}) = -(D_3D_1 - D_1D_3)`. This single new operator
drives the recursion for the `T`-images of all the higher rungs. The hypothesis `M ≠ 0` is used only
to cancel `HJO.Sym.Qop`'s own `M⁻¹` against the `M` produced by `HJO.Sym.shiftStep_dop`. -/
theorem shiftStep_qop_two_three (q u : L) (hM : (1 - q) * (1 - u) ≠ 0) :
    shiftStep L (Qop q u 2 3) = -(Dop q u 3 * Dop q u 1 - Dop q u 1 * Dop q u 3) := by
  rw [qop_two_three_eq_bracket_dop, shiftStep_smul, shiftStep_bracket_dop_two_one, smul_smul,
    show ((1 - q) * (1 - u))⁻¹ * -((1 - q) * (1 - u)) = -1 from by
      rw [mul_neg, inv_mul_cancel₀ hM], neg_smul, one_smul]

/-! ### The shift step against one rung of the ladder -/

/-- **The shift step against one rung of the ladder.** Leibniz splits the ladder step in two: the
step applied to `TA`, plus a normalised bracket of `A` against the one new operator
`T(Q_{2,3})`. Unconditional in `q` and `u`. -/
theorem shiftStep_ladderTwoThree (q u : L) (A : Module.End L (Lambda L)) :
    shiftStep L (ladderTwoThree q u A)
      = ladderTwoThree q u (shiftStep L A)
        + ((1 - q) * (1 - u))⁻¹ •
            (A * shiftStep L (Qop q u 2 3) - shiftStep L (Qop q u 2 3) * A) := by
  rw [ladderTwoThree_apply, shiftStep_smul, shiftStep_sub, shiftStep_mul, shiftStep_mul,
    ladderTwoThree_apply]
  simp only [smul_sub, smul_add]
  abel

/-- **The recursion for the `T`-images of the rungs**, which is
`HJO.Sym.shiftStep_ladderTwoThree` at `A = L_j`: `TL_{j+1}` is one ladder step off `TL_j`,
corrected by a bracket of `L_j` against `T(Q_{2,3})`. With
`HJO.Sym.shiftStep_iterate_ladderTwoThree_zero` this computes `TL_j` at every `j`. -/
theorem shiftStep_iterate_ladderTwoThree (q u : L) (j : ℕ) :
    shiftStep L ((ladderTwoThree q u)^[j + 1] (Dop q u 2))
      = ladderTwoThree q u (shiftStep L ((ladderTwoThree q u)^[j] (Dop q u 2)))
        + ((1 - q) * (1 - u))⁻¹ •
            ((ladderTwoThree q u)^[j] (Dop q u 2) * shiftStep L (Qop q u 2 3)
              - shiftStep L (Qop q u 2 3) * (ladderTwoThree q u)^[j] (Dop q u 2)) := by
  rw [Function.iterate_succ_apply', shiftStep_ladderTwoThree]

/-- The base of that recursion: `TL_0 = T(D_2) = -M·D_3`. -/
theorem shiftStep_iterate_ladderTwoThree_zero (q u : L) :
    shiftStep L ((ladderTwoThree q u)^[0] (Dop q u 2))
      = -(((1 - q) * (1 - u)) • Dop q u 3) := by
  rw [Function.iterate_zero_apply, shiftStep_dop]

/-! ### The shift step against a collinear slope operator -/

/-- **The shift step against a collinear slope operator, at every `k ≥ 1`.** Leibniz on
`HJO.Sym.qop_two_three_axis_eq_ladder`: the first term is the same bracket with `L_{k-1}` replaced
by `TL_{k-1}`, and the second is the bracket of `L_{k-1}` against `D_2` with the `M⁻¹` cancelled
by the `M` of `HJO.Sym.shiftStep_dop`. That cancellation is the only use of `M ≠ 0`. -/
theorem shiftStep_qop_two_three_axis (q u : L) (hM : (1 - q) * (1 - u) ≠ 0) {k : ℕ} (hk : 1 ≤ k) :
    shiftStep L (Qop q u (2 * k) (3 * k))
      = ((1 - q) * (1 - u))⁻¹ •
          (shiftStep L ((ladderTwoThree q u)^[k - 1] (Dop q u 2)) * Dop q u 1
            - Dop q u 1 * shiftStep L ((ladderTwoThree q u)^[k - 1] (Dop q u 2)))
        - ((ladderTwoThree q u)^[k - 1] (Dop q u 2) * Dop q u 2
            - Dop q u 2 * (ladderTwoThree q u)^[k - 1] (Dop q u 2)) := by
  have hMM : ((1 - q) * (1 - u))⁻¹ * ((1 - q) * (1 - u)) = 1 := inv_mul_cancel₀ hM
  rw [qop_two_three_axis_eq_ladder q u hk, shiftStep_smul, shiftStep_sub, shiftStep_mul,
    shiftStep_mul, shiftStep_dop]
  simp only [neg_mul, mul_neg, smul_mul_assoc, mul_smul_comm, smul_sub, smul_add, smul_neg,
    smul_smul, hMM, one_smul]
  abel

/-! ### The collinear slope operators on non-vacuum arguments -/

/-- **The collinear slope operators on the `e_1` ray, at every `k` and every `m`**: the binomial sum
in the vacuum values of the iterated shifts of `Q_{2k,3k}`. Unconditional in `q` and `u`; at `M = 0`
both sides vanish for `k ≥ 2`, which is `HJO.Sym.Qop`'s totalisation. -/
theorem qop_two_three_axis_apply_elemSymm_one_pow (q u : L) (k m : ℕ) :
    Qop q u (2 * k) (3 * k) (elemSymm L 1 ^ m)
      = ∑ i ∈ Finset.range (m + 1), ((-1 : L) ^ i * (m.choose i : L)) •
          (elemSymm L 1 ^ (m - i) * ((shiftStep L)^[i] (Qop q u (2 * k) (3 * k))) 1) := by
  have h := apply_elemSymm_one_pow_mul (Qop q u (2 * k) (3 * k)) m (1 : Lambda L)
  rw [mul_one] at h
  exact h

/-- **`Q_{2k,3k}(e_1)` in closed form at every `k ≥ 1`**: the vacuum value multiplied by `e_1`,
corrected by the two brackets `HJO.Sym.shiftStep_qop_two_three_axis` names, each read at the vacuum.
Every operator on the right is a word in `D_1, D_2` — `TL_{k-1}` by
`HJO.Sym.shiftStep_iterate_ladderTwoThree` — so the right-hand side is a finite combination of
vacuum values of `HJO.Sym.DopAlgebra`, not of the orbit `Q_{2,3}^m(1)`. `M ≠ 0` only for the
cancellation. -/
theorem qop_two_three_axis_apply_elemSymm_one (q u : L) (hM : (1 - q) * (1 - u) ≠ 0) {k : ℕ}
    (hk : 1 ≤ k) :
    Qop q u (2 * k) (3 * k) (elemSymm L 1)
      = elemSymm L 1 * Qop q u (2 * k) (3 * k) 1
        - ((1 - q) * (1 - u))⁻¹ •
            (shiftStep L ((ladderTwoThree q u)^[k - 1] (Dop q u 2)) (Dop q u 1 1)
              - Dop q u 1 (shiftStep L ((ladderTwoThree q u)^[k - 1] (Dop q u 2)) 1))
        + ((ladderTwoThree q u)^[k - 1] (Dop q u 2) (Dop q u 2 1)
            - Dop q u 2 ((ladderTwoThree q u)^[k - 1] (Dop q u 2) 1)) := by
  have h := apply_elemSymm_one_mul (Qop q u (2 * k) (3 * k)) (1 : Lambda L)
  rw [mul_one] at h
  rw [h, shiftStep_qop_two_three_axis q u hM hk]
  simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.mul_apply]
  abel

/-! ### Pin at `k = 1` against the independently computed value -/

/-- The base rung on `e_1` as the shift step gives it:
`Q_{2,3}(e_1) = e_1Q_{2,3}(1) - D_3(e_1) + D_1(e_3)`, from `HJO.Sym.apply_elemSymm_one_mul` at
`f = 1` and `HJO.Sym.shiftStep_qop_two_three`. -/
theorem qop_two_three_apply_elemSymm_one_of_shiftStep (q u : L) (hM : (1 - q) * (1 - u) ≠ 0) :
    Qop q u 2 3 (elemSymm L 1)
      = elemSymm L 1 * Qop q u 2 3 1 - Dop q u 3 (elemSymm L 1)
        + Dop q u 1 (elemSymm L 3) := by
  have hd1 : Dop q u 1 (1 : Lambda L) = -elemSymm L 1 := by rw [dop_apply_one]; ring
  have hd3 : Dop q u 3 (1 : Lambda L) = -elemSymm L 3 := by rw [dop_apply_one]; ring
  have h := apply_elemSymm_one_mul (Qop q u 2 3) (1 : Lambda L)
  rw [mul_one] at h
  rw [h, shiftStep_qop_two_three q u hM]
  simp only [LinearMap.neg_apply, LinearMap.sub_apply, Module.End.mul_apply, hd1, hd3, map_neg]
  abel

/-- That expression evaluated from the Pieri rule and the vacuum values. `D_3(e_1)` needs only
`κ(e_1)`, `D_1(e_3)` needs `κ(e_1), κ(e_2), κ(e_3)`, and the two `e_1e_3` terms produced by the
subtraction cancel outright; nothing here appeals to the known value of `Q_{2,3}(e_1)`. -/
theorem elemSymm_one_mul_qop_two_three_sub_dop_three_add_dop_one (q u : L)
    (hM : (1 - q) * (1 - u) ≠ 0) :
    elemSymm L 1 * Qop q u 2 3 1 - Dop q u 3 (elemSymm L 1) + Dop q u 1 (elemSymm L 3)
      = -(elemSymm L 1 * elemSymm L 1 * elemSymm L 2)
        + ((1 - q) * (1 - u)) • (elemSymm L 2 * elemSymm L 2)
        + (1 - q - u + (q + u) * ((1 - q) * (1 - u))) • (elemSymm L 1 * elemSymm L 3)
        + ((q ^ 2 + q * u + u ^ 2 - 1) * ((1 - q) * (1 - u))) • elemSymm L 4 := by
  have hd1 : Dop q u 1 (1 : Lambda L) = -elemSymm L 1 := by rw [dop_apply_one]; ring
  have hd2 : Dop q u 2 (1 : Lambda L) = elemSymm L 2 := by rw [dop_apply_one]; ring
  have hd3 : Dop q u 3 (1 : Lambda L) = -elemSymm L 3 := by rw [dop_apply_one]; ring
  have hd4 : Dop q u 4 (1 : Lambda L) = elemSymm L 4 := by rw [dop_apply_one]; ring
  have hD3e1 : Dop q u 3 (elemSymm L 1)
      = elemSymm L 1 * -elemSymm L 3 + ((1 - q) * (1 - u)) • elemSymm L 4 := by
    have h := dop_elemSymm_one_mul q u 3 (1 : Lambda L)
    rw [mul_one] at h
    rw [h, hd3, show (3 : ℕ) + 1 = 4 from rfl, hd4]
  have hD1e3 : Dop q u 1 (elemSymm L 3)
      = elemSymm L 3 * -elemSymm L 1
        + ((1 - q) * (1 - u)) • (elemSymm L 2 * elemSymm L 2)
        + (-((q + u) * ((1 - q) * (1 - u)))) • (elemSymm L 1 * -elemSymm L 3)
        + ((q ^ 2 + q * u + u ^ 2) * ((1 - q) * (1 - u))) • (1 * elemSymm L 4) := by
    have h := dop_elemSymm_mul q u 1 3 (1 : Lambda L)
    rw [mul_one] at h
    rw [h, Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_succ,
      Finset.sum_range_one, paramPleth_elemSymm_zero, paramPleth_elemSymm_one_eq,
      paramPleth_elemSymm_two_eq, paramPleth_elemSymm_three_eq]
    norm_num only [Nat.sub_zero, Nat.sub_self, elemSymm_zero, one_smul]
    rw [hd1, hd2, hd3, hd4]
  rw [qop_two_three_apply_one hM, hD3e1, hD1e3]
  simp only [MvPolynomial.smul_eq_C_mul, map_sub, map_add, map_mul, map_neg, map_one, map_pow]
  ring

/-- **The `e_1` route reproves the known value of `Q_{2,3}(e_1)`.** The right-hand side is verbatim
`HJO.Sym.qop_two_three_apply_elemSymm_one` of `HJO/Shuffle/MellitQopThreeFour.lean`, which is
obtained there by grinding the commutator of `HJO.Sym.Qop` directly. The two derivations share
nothing but `HJO.Sym.DopInt`, so the agreement of all four coefficients pins the signs and the index
bookkeeping of the shift step, of the ladder bracket, and of the Pieri rule at once. -/
theorem qop_two_three_apply_elemSymm_one_pin (q u : L) (hM : (1 - q) * (1 - u) ≠ 0) :
    Qop q u 2 3 (elemSymm L 1)
      = -(elemSymm L 1 * elemSymm L 1 * elemSymm L 2)
        + ((1 - q) * (1 - u)) • (elemSymm L 2 * elemSymm L 2)
        + (1 - q - u + (q + u) * ((1 - q) * (1 - u))) • (elemSymm L 1 * elemSymm L 3)
        + ((q ^ 2 + q * u + u ^ 2 - 1) * ((1 - q) * (1 - u))) • elemSymm L 4 :=
  (qop_two_three_apply_elemSymm_one_of_shiftStep q u hM).trans
    (elemSymm_one_mul_qop_two_three_sub_dop_three_add_dop_one q u hM)

/-! ### The whole creation side on the `e_1` ray -/

/-- Every collinear slope operator at `(2,3)` lies in the full operator algebra
`HJO.Sym.DopAlgebra`. -/
theorem qop_two_three_axis_mem_dopAlgebra (q u : L) {k : ℕ} (hk : 1 ≤ k) :
    Qop q u (2 * k) (3 * k) ∈ DopAlgebra q u :=
  dopTwoAlgebra_le_dopAlgebra q u (qop_two_three_axis_mem_dopTwoAlgebra q u hk)

/-- **The whole creation side on the `e_1` ray.** For every value `Θf` of a `(2,3)` slope
homomorphism and every `m`, `Θf(e_1^m)` is the binomial sum in the vacuum values of the iterated
shifts of `Θf`, and every operator that sum names is still in `HJO.Sym.DopAlgebra`. So on this ray
no value of `Θ` ever leaves the algebra generated by the basic operators, and each is determined by
vacuum values inside it. Nothing here extends off the ray: see
`HJO.Sym.ad_elemSymm_dop` for the reason. -/
theorem theta_apply_elemSymm_one_pow [CharZero L] {q u : L} (hv0 : q * u ≠ 0)
    (hv1 : ∀ j : ℕ, (q * u) ^ (j + 1) ≠ 1)
    {Θ : Lambda L →ₐ[L] Module.End L (Lambda L)} (hΘ : IsSlopeHom 2 3 q u Θ) (f : Lambda L)
    (m : ℕ) :
    Θ f (elemSymm L 1 ^ m)
        = ∑ i ∈ Finset.range (m + 1), ((-1 : L) ^ i * (m.choose i : L)) •
            (elemSymm L 1 ^ (m - i) * ((shiftStep L)^[i] (Θ f)) 1)
      ∧ ∀ i, (shiftStep L)^[i] (Θ f) ∈ DopAlgebra q u := by
  refine ⟨?_, fun i => iterate_shiftStep_mem_dopAlgebra q u
    (dopTwoAlgebra_le_dopAlgebra q u (theta_mem_dopTwoAlgebra hv0 hv1 hΘ f)) i⟩
  have h := apply_elemSymm_one_pow_mul (Θ f) m (1 : Lambda L)
  rw [mul_one] at h
  exact h

end HJO.Sym
