/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitShiftAlgebra
public meta import HJO.Attr

/-! # The twisted index shift, and `HJO.Sym.nsShiftComp_comp_smul_map`

`HJO.Sym.nsShiftComp_comp_smul_map` asks for `τ^*τ S(E) = Ê τ^*τ` for `E` in the algebra the basic
operators generate and `S` the index shift. `HJO/Shuffle/MellitShiftAlgebra.lean` proved the
assembly one step short of that statement — for every degree-homogeneous `E` there is exactly one
operator transported by it — and stopped there for three reasons. This file states the result and
proves it, by repairing two of those three in the only way the sign allows, and by reading the third
as the vocabulary of `HJO.Sym.IsIndexShift` reads it.

## The three points, and what happens to each here

**The sign.** `HJO.Sym.IsIndexShift` asks `S(D_k) = +D_{k+1}`, and that reading
is refuted: `HJO.Sym.not_nsTransports_isIndexShift`. The repair is forced to be
the `(-1)^m`-twist of `HJO.Dyck.Tilde.rel_biHomogeneous`, `m` being the number of raising arrows. So
the statement below is `(-1)^mS(E)` for `S` an index shift and `m` the number of basic operators in
a word: a word of `m` letters carries `(-1)^m` (`HJO.Sym.dopGenWordShift_eq`), and at `m = 1` this
is the `S(D_k) = -D_{k+1}` the sign refutations pin. The normalisation is therefore Mellit's (whose
shift differs from the unsigned one by `(-1)^m` on the bidegree-`(m, n)` component, §3.7) and not a
third one, and the shift itself is still `HJO.Sym.IsIndexShift` — which matters, because an index
shift is known to exist here and a twisted one is not.

**The generating set.** Mellit's statement quantifies over the subalgebra generated by the
operators that `T_i`, `d_-`, `d^*_+` and the corner elements act as. Those are not given directly
as endomorphisms of `Λ`; making them into endomorphisms of `Λ` is
`HJO.Sweep.exists_isDpaAction_mellit`. The shift `HJO.Sym.IsIndexShift`, however, *names its own*
generating set: it is an endomorphism of `HJO.Sym.DopAlgebra`, i.e. of
`𝖠 = Algebra.adjoin 𝕜 (range (Dop q u))`, so its `S` is only defined on the subalgebra the
`D_k` generate. That is the subalgebra used here. **This is the one point at which the Lean
statement is weaker than the printed one**, and it is weaker in the direction of the vocabulary of
`HJO.Sym.IsIndexShift`; the identification of `𝖠` with the image of `e_0Ãe_0` is what
`HJO.Sweep.exists_isDpaAction_mellit` would add.

**The grading.** `Ê` is `HJO.Sym.completionExtension`, which takes `ShiftsDegree c E` as data, so a
mixed-degree element of `𝖠` has no `Ê` and the right-hand side cannot be written for it. And
the twist above is the constant `(-1)^m` only at a fixed word length. So the side condition is
`E ∈ HJO.Sym.dopGenSpanBi q u m c`, the `𝕜`-span of the words of `m` letters summing to `c` — which
is the bidegree `HJO.Dyck.Tilde.rel_biHomogeneous` already attaches the twist to. It is not a
restriction to a subalgebra: `HJO.Sym.mem_iSup_dopGenSpanBi` says the bigraded pieces span all of
`𝖠`, so every element of `𝖠` is a finite sum of elements the statement covers, and
`HJO.Sym.nsTransports_sum_of_mem_dopGenSpanBi` is the statement read on such a sum, with the
right-hand side the sum of the extensions of the parts. That is the whole of what the grading costs.

## Main results

* `HJO.Sym.nsShiftComp_comp_smul_map` — **the main result**: for `S` an index shift of
  `HJO.Sym.IsIndexShift` and `E` in the bidegree-`(m, c)` part of `𝖠`,
  `τ^*τ ∘ ((-1)^mS(E)) = Ê ∘ τ^*τ` as maps `Λ → Λ̂`. The hypothesis is satisfiable: an index shift
  exists, with no hypothesis at the standing field (`HJO.Bglx.exists_isIndexShift_param`).
* `HJO.Sym.nsTransports_dopWord` — the same identity with the value written out and no `S` in it:
  `τ^*τ((-D_{n_1+1})⋯(-D_{n_r+1})) = (D_{n_1}⋯D_{n_r})^ τ^*τ`. This is the unconditional content;
  the theorem above is that content read along an index shift.
* `HJO.Sym.IsNsIndexShift` and `HJO.Sym.nsShiftComp_comp_map` — the same statement with the
  `(-1)^m` carried inside a single algebra map `S(D_k) = -D_{k+1}` instead of written beside an
  index shift. Nothing here exhibits such a map, which is why this form is not the main result;
  `HJO.Sym.coe_map_eq_smul_coe_map` shows the two readings agree wherever both apply.
* `HJO.Sym.mem_iSup_dopGenSpanBi` — the bigraded pieces span `𝖠`.
* `HJO.Sym.nsTransports_sum_of_mem_dopGenSpanBi` — the statement on an element that is not
  bihomogeneous, stated against a decomposition into bihomogeneous parts.

The generator case is `HJO.Sym.nsShiftComp_comp_dopInt`, the induction over the letters
of a word is `HJO.Sym.nsShiftComp_mul`, and the passage from words to their span is
`HJO.Sym.NsTransports.add`/`.smul` of `HJO/Shuffle/MellitShiftAlgebra.lean`. The hypothesis
`hM` is inherited from `HJO.Sym.nsShiftComp_comp_dopInt` and is read nowhere else.

## References

Declarations involved: `HJO.Sym.nsShiftComp_comp_smul_map`, `HJO.Sym.nsShiftComp_comp_dopInt`,
`HJO.Sym.nsShiftComp_eq_of_eq`, `HJO.Sym.nsShiftComp_mul`, `HJO.Dyck.Tilde.rel_biHomogeneous`;
`HJO.Sym.IsIndexShift`, `HJO.Sym.DopAlgebra`, `HJO.Sym.DopInt`, `HJO.Sym.completionExtension`.
Transcribing A. Mellit, *Toric braids and `(m,n)`-parking functions*, §3.7.
-/

@[expose] public section

namespace HJO.Sym

section Field

variable {K : Type*} [Field K] [Algebra ℚ K]

/-! ### Moving the transport relation along equalities

`HJO.Sym.NsTransports` carries its degree and its transported operator in the *type* of its
`ShiftsDegree` argument, so an equality of operators has to be moved by hand. Proof irrelevance
does the rest: two `ShiftsDegree` proofs of the same degree at the same operator are
interchangeable. -/

/-- The coercion out of `𝖠` is additive, by definition of the addition on a subalgebra. Stated so
that `rw` can use it: the two sides are definitionally equal but not syntactically. -/
private theorem coe_add_dopAlgebra {q u : K} (x y : DopAlgebra q u) :
    ((x + y : DopAlgebra q u) : Module.End K (Lambda K)) = x + y := rfl

theorem NsTransports.congr {q u : K} {c c' : ℤ} {D D' : Module.End K (Lambda K)}
    {hD : ShiftsDegree c D} {hD' : ShiftsDegree c' D'} {E E' : Module.End K (Lambda K)}
    (hc : c = c') (hDD : D = D') (hEE : E = E') (h : NsTransports q u hD E) :
    NsTransports q u hD' E' := by
  subst hc
  subst hDD
  subst hEE
  exact h

/-! ### Words in the basic operators at natural indices

`HJO/Shuffle/MellitShiftAlgebra.lean` works with `HJO.Sym.DopInt`, the basic operator at an
integer index, because `HJO.Sym.nsShiftComp_comp_dopInt` quantifies over `ℤ`. The algebra `𝖠` of
`HJO.Sym.DopAlgebra` is generated by the `HJO.Sym.Dop q u k` for `k : ℕ`, and the shift raises an
index inside `ℕ`, so the words below are indexed by `List ℕ`. -/

/-- The word `D_{n_1}⋯D_{n_r}` in the basic operators. -/
noncomputable def dopWord (q u : K) (ns : List ℕ) : Module.End K (Lambda K) :=
  (ns.map (Dop q u)).prod

theorem dopWord_nil (q u : K) : dopWord q u [] = 1 := rfl

theorem dopWord_cons (q u : K) (n : ℕ) (ns : List ℕ) :
    dopWord q u (n :: ns) = Dop q u n * dopWord q u ns := rfl

/-- The word the twisted shift assigns to `D_{n_1}⋯D_{n_r}`, namely `(-D_{n_1+1})⋯(-D_{n_r+1})`. -/
noncomputable def dopWordShift (q u : K) (ns : List ℕ) : Module.End K (Lambda K) :=
  (ns.map fun n => -(Dop q u (n + 1))).prod

theorem dopWordShift_nil (q u : K) : dopWordShift q u [] = 1 := rfl

theorem dopWordShift_cons (q u : K) (n : ℕ) (ns : List ℕ) :
    dopWordShift q u (n :: ns) = -(Dop q u (n + 1)) * dopWordShift q u ns := rfl

/-- A word shifts degree by the sum of its letters. -/
theorem dopWord_shiftsDegree (q u : K) (ns : List ℕ) :
    ShiftsDegree (ns.sum : ℤ) (dopWord q u ns) := by
  induction ns with
  | nil => rw [dopWord_nil, List.sum_nil, Nat.cast_zero]; exact shiftsDegree_one
  | cons n ns ih =>
    rw [dopWord_cons, List.sum_cons, Nat.cast_add]
    exact (dop_shiftsDegree q u n).comp ih

/-- **The generator case**, `HJO.Sym.nsShiftComp_comp_dopInt` at a natural index: `D_n`
transports `-D_{n+1}`. -/
theorem nsTransports_dop (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) (n : ℕ) :
    NsTransports q u (dop_shiftsDegree q u n) (-(Dop q u (n + 1))) := by
  refine NsTransports.congr rfl (dopInt_natCast q u n) ?_ (nsTransports_dopInt q u hM (n : ℤ))
  rw [show ((n : ℤ) + 1) = ((n + 1 : ℕ) : ℤ) from by push_cast; ring, dopInt_natCast]

/-- **The assembly on a word**, with the transported operator written out and no shift map in
sight: `τ^*τ((-D_{n_1+1})⋯(-D_{n_r+1})) = (D_{n_1}⋯D_{n_r})^ τ^*τ`. The letter case is
`HJO.Sym.nsShiftComp_comp_dopInt` and the induction step is `HJO.Sym.nsShiftComp_mul`. -/
theorem nsTransports_dopWord (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) (ns : List ℕ) :
    NsTransports q u (dopWord_shiftsDegree q u ns) (dopWordShift q u ns) := by
  induction ns with
  | nil =>
    exact NsTransports.congr (by rw [List.sum_nil, Nat.cast_zero]) (dopWord_nil q u).symm
      (dopWordShift_nil q u).symm (NsTransports.one q u)
  | cons n ns ih =>
    refine NsTransports.congr ?_ (dopWord_cons q u n ns).symm (dopWordShift_cons q u n ns).symm
      ((nsTransports_dop q u hM n).mul ih)
    rw [List.sum_cons, Nat.cast_add]

/-! ### The same words inside the operator algebra `𝖠` -/

/-- The word `D_{n_1}⋯D_{n_r}` as an element of the operator algebra `𝖠` of
`HJO.Sym.DopAlgebra`. -/
noncomputable def dopGenWord (q u : K) (ns : List ℕ) : DopAlgebra q u :=
  (ns.map (dopGen q u)).prod

theorem dopGenWord_coe (q u : K) (ns : List ℕ) :
    ((dopGenWord q u ns : DopAlgebra q u) : Module.End K (Lambda K)) = dopWord q u ns := by
  induction ns with
  | nil => rfl
  | cons n ns ih =>
    change (dopGen q u n : Module.End K (Lambda K))
      * ((dopGenWord q u ns : DopAlgebra q u) : Module.End K (Lambda K)) = _
    rw [ih, dopGen_coe, dopWord_cons]

/-- The word the twisted shift assigns, as an element of `𝖠`. -/
noncomputable def dopGenWordShift (q u : K) (ns : List ℕ) : DopAlgebra q u :=
  (ns.map fun n => -dopGen q u (n + 1)).prod

theorem dopGenWordShift_coe (q u : K) (ns : List ℕ) :
    ((dopGenWordShift q u ns : DopAlgebra q u) : Module.End K (Lambda K))
      = dopWordShift q u ns := by
  induction ns with
  | nil => rfl
  | cons n ns ih =>
    change -(dopGen q u (n + 1) : Module.End K (Lambda K))
      * ((dopGenWordShift q u ns : DopAlgebra q u) : Module.End K (Lambda K)) = _
    rw [ih, dopGen_coe, dopWordShift_cons]

/-- **The sign on a word is `(-1)^r`**, one minus for each letter: the `(-1)^m`-twist of
`HJO.Dyck.Tilde.rel_biHomogeneous` read on a word of `r` raising arrows. -/
theorem dopGenWordShift_eq (q u : K) (ns : List ℕ) :
    dopGenWordShift q u ns
      = (-1 : K) ^ ns.length • (ns.map fun n => dopGen q u (n + 1)).prod := by
  induction ns with
  | nil =>
    rw [dopGenWordShift, List.map_nil, List.prod_nil, List.length_nil, pow_zero, one_smul,
      List.map_nil, List.prod_nil]
  | cons n ns ih =>
    rw [dopGenWordShift, List.map_cons, List.prod_cons, ← dopGenWordShift, ih, List.map_cons,
      List.prod_cons, List.length_cons, pow_succ, neg_mul, mul_smul_comm, ← neg_smul, mul_neg_one]

/-! ### The twisted index shift -/

/-- **A twisted index shift**: a `𝕜`-algebra endomorphism `S` of the operator algebra `𝖠` with
`S(D_k) = -D_{k+1}` for every `k ≥ 0`.

This is `HJO.Sym.IsIndexShift` twisted by the `(-1)^m` of `HJO.Dyck.Tilde.rel_biHomogeneous`, `m`
being the number of raising arrows, at `m = 1` where the basic operators sit. The untwisted
normalisation does not satisfy `HJO.Sym.nsShiftComp_comp_smul_map`'s identity — that is
`HJO.Sym.not_nsTransports_isIndexShift` — and this one does, which is the theorem below. As with
`HJO.Sym.IsIndexShift`, nothing here asserts that such an `S` exists; the statement takes its
shift as a hypothesis too. -/
def IsNsIndexShift (q u : K) (S : DopAlgebra q u →ₐ[K] DopAlgebra q u) : Prop :=
  ∀ k : ℕ, S (dopGen q u k) = -dopGen q u (k + 1)

/-- A twisted index shift read in `End_𝕜(Λ)` rather than in the subalgebra, the companion of
`HJO.Sym.isIndexShift_iff`. -/
theorem isNsIndexShift_iff (q u : K) (S : DopAlgebra q u →ₐ[K] DopAlgebra q u) :
    IsNsIndexShift q u S ↔
      ∀ k : ℕ, (S (dopGen q u k) : Module.End K (Lambda K)) = -Dop q u (k + 1) := by
  simp [IsNsIndexShift, Subtype.ext_iff]

/-- **A twisted index shift is determined on the words**, and its value there is the word with a
minus on every letter. -/
theorem map_dopGenWord {q u : K} {S : DopAlgebra q u →ₐ[K] DopAlgebra q u}
    (hS : IsNsIndexShift q u S) (ns : List ℕ) :
    S (dopGenWord q u ns) = dopGenWordShift q u ns := by
  induction ns with
  | nil => rw [dopGenWord, List.map_nil, List.prod_nil, map_one, dopGenWordShift, List.map_nil,
      List.prod_nil]
  | cons n ns ih =>
    rw [dopGenWordShift, List.map_cons, List.prod_cons, ← dopGenWordShift, dopGenWord,
      List.map_cons, List.prod_cons, ← dopGenWord, map_mul, ih, hS n]

/-! ### The graded pieces of `𝖠` -/

/-- **The degree-`c` part of the operator algebra `𝖠`**: the `𝕜`-span of the words
`D_{n_1}⋯D_{n_r}` whose letters sum to `c`. This is where `HJO.Sym.nsShiftComp_comp_smul_map` can be
stated: an element of `𝖠` mixing degrees has no extension to the completion, so the statement's
right-hand side is undefined on it. -/
noncomputable def dopGenSpan (q u : K) (c : ℕ) : Submodule K (DopAlgebra q u) :=
  Submodule.span K {E | ∃ ns : List ℕ, ns.sum = c ∧ dopGenWord q u ns = E}

theorem dopGenWord_mem_dopGenSpan (q u : K) (ns : List ℕ) :
    dopGenWord q u ns ∈ dopGenSpan q u ns.sum :=
  Submodule.subset_span ⟨ns, rfl, rfl⟩

/-- The degree-`c` part is not empty of content: it holds the basic operator `D_c` itself. -/
theorem dopGen_mem_dopGenSpan (q u : K) (n : ℕ) : dopGen q u n ∈ dopGenSpan q u n :=
  Submodule.subset_span ⟨[n], by simp, by rw [dopGenWord]; simp⟩

/-- Everything in the degree-`c` part shifts degree by `c`, so it has an extension to the
completion and the statement's right-hand side exists. -/
theorem shiftsDegree_of_mem_dopGenSpan {q u : K} {c : ℕ} {E : DopAlgebra q u}
    (hE : E ∈ dopGenSpan q u c) :
    ShiftsDegree (c : ℤ) ((E : Module.End K (Lambda K))) := by
  induction hE using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨ns, hsum, rfl⟩ := hx
    subst hsum
    rw [dopGenWord_coe]
    exact dopWord_shiftsDegree q u ns
  | zero => exact (degreeShifting K (c : ℤ)).zero_mem
  | add x y _ _ ihx ihy => exact (degreeShifting K (c : ℤ)).add_mem ihx ihy
  | smul r x _ ih => exact (degreeShifting K (c : ℤ)).smul_mem r ih

/-! ### The bigraded pieces of `𝖠`

`HJO.Dyck.Tilde.rel_biHomogeneous` puts the twist on the bidegree-`(m, n)` component, `m` counting
the raising arrows; a word of `m` basic operators has `m` of them and `n` is the sum of its indices.
So the domain on which the twist of `HJO.Sym.IsIndexShift` can be read is the *bi*graded piece, and
that is what the repair of the sign asks for. -/

/-- **The bidegree-`(m, c)` part of the operator algebra `𝖠`**: the `𝕜`-span of the words
`D_{n_1}⋯D_{n_m}` of `m` letters whose indices sum to `c`. -/
noncomputable def dopGenSpanBi (q u : K) (m c : ℕ) : Submodule K (DopAlgebra q u) :=
  Submodule.span K {E | ∃ ns : List ℕ, ns.length = m ∧ ns.sum = c ∧ dopGenWord q u ns = E}

theorem dopGenWord_mem_dopGenSpanBi (q u : K) (ns : List ℕ) :
    dopGenWord q u ns ∈ dopGenSpanBi q u ns.length ns.sum :=
  Submodule.subset_span ⟨ns, rfl, rfl, rfl⟩

/-- The basic operator `D_n` is the whole of the bidegree `(1, n)` that it occupies. -/
theorem dopGen_mem_dopGenSpanBi (q u : K) (n : ℕ) : dopGen q u n ∈ dopGenSpanBi q u 1 n :=
  Submodule.subset_span ⟨[n], by simp, by simp, by rw [dopGenWord]; simp⟩

theorem dopGenSpanBi_le_dopGenSpan (q u : K) (m c : ℕ) :
    dopGenSpanBi q u m c ≤ dopGenSpan q u c := by
  refine Submodule.span_le.2 ?_
  rintro E ⟨ns, -, hsum, rfl⟩
  exact hsum ▸ dopGenWord_mem_dopGenSpan q u ns

/-- Everything in a bigraded piece shifts degree by its second index, so it has an extension to the
completion and the statement's right-hand side exists. -/
theorem shiftsDegree_of_mem_dopGenSpanBi {q u : K} {m c : ℕ} {E : DopAlgebra q u}
    (hE : E ∈ dopGenSpanBi q u m c) :
    ShiftsDegree (c : ℤ) ((E : Module.End K (Lambda K))) :=
  shiftsDegree_of_mem_dopGenSpan (dopGenSpanBi_le_dopGenSpan q u m c hE)

/-- **An index shift on a word** raises every letter:
`S(D_{n_1}⋯D_{n_r}) = D_{n_1+1}⋯D_{n_r+1}`, with no sign. -/
theorem map_dopGenWord_of_isIndexShift {q u : K} {S : DopAlgebra q u →ₐ[K] DopAlgebra q u}
    (hS : IsIndexShift q u S) (ns : List ℕ) :
    S (dopGenWord q u ns) = (ns.map fun n => dopGen q u (n + 1)).prod := by
  induction ns with
  | nil => rw [dopGenWord, List.map_nil, List.prod_nil, map_one, List.map_nil, List.prod_nil]
  | cons n ns ih =>
    rw [List.map_cons, List.prod_cons, dopGenWord, List.map_cons, List.prod_cons, ← dopGenWord,
      map_mul, ih, hS n]

/-- **The `(-1)^m`-twist of an index shift on a word** is the word with a minus on every letter,
which is the operator `HJO.Sym.nsShiftComp_comp_dopInt` transports. Here `m` is the
length of the word — the number of raising arrows — so this is `HJO.Dyck.Tilde.rel_biHomogeneous`'s
twist at bidegree `(m, c)` and not a normalisation of its own. -/
theorem smul_map_dopGenWord_of_isIndexShift {q u : K} {S : DopAlgebra q u →ₐ[K] DopAlgebra q u}
    (hS : IsIndexShift q u S) (ns : List ℕ) :
    (-1 : K) ^ ns.length • S (dopGenWord q u ns) = dopGenWordShift q u ns := by
  rw [map_dopGenWord_of_isIndexShift hS, dopGenWordShift_eq]

/-! ### The main result -/

/-- **`HJO.Sym.nsShiftComp_comp_smul_map`, pointwise.** For `S` an index shift of
`HJO.Sym.IsIndexShift` and `E` in the bidegree-`(m, c)` part of the algebra the basic operators
generate, `E` transports the `(-1)^m`-twist of `S(E)`: `τ^*τ((-1)^mS(E)f) = Ê(τ^*τ f)` for every
`f ∈ Λ`.

The words are `HJO.Sym.nsTransports_dopWord` — `HJO.Sym.nsShiftComp_comp_dopInt` closed
under `HJO.Sym.nsShiftComp_mul` — matched to the twist by
`HJO.Sym.smul_map_dopGenWord_of_isIndexShift`; the span is `HJO.Sym.NsTransports.add` and
`HJO.Sym.NsTransports.smul`. Both indices of the bidegree are spent, and each exactly once: `c`
because `Ê` exists only at a fixed degree, and `m` because the twist is the *constant* `(-1)^m` only
at a fixed word length, which is what lets it pass through a sum. -/
theorem nsTransports_smul_map_of_mem_dopGenSpanBi (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsIndexShift q u S)
    {m c : ℕ} {E : DopAlgebra q u} (hE : E ∈ dopGenSpanBi q u m c)
    (hEs : ShiftsDegree (c : ℤ) ((E : Module.End K (Lambda K)))) :
    NsTransports q u hEs ((((-1 : K) ^ m • S E : DopAlgebra q u) : Module.End K (Lambda K))) := by
  revert hEs
  induction hE using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨ns, hlen, hsum, rfl⟩ := hx
    subst hlen
    subst hsum
    intro _
    refine NsTransports.congr rfl (dopGenWord_coe q u ns).symm ?_
      (nsTransports_dopWord q u hM ns)
    rw [smul_map_dopGenWord_of_isIndexShift hS, dopGenWordShift_coe]
  | zero =>
    intro _
    rw [map_zero, smul_zero]
    exact nsTransports_zero q u _
  | add x y hx hy ihx ihy =>
    intro _
    rw [map_add, smul_add]
    exact (ihx (shiftsDegree_of_mem_dopGenSpanBi hx)).add
      (ihy (shiftsDegree_of_mem_dopGenSpanBi hy))
  | smul r x hx ih =>
    intro _
    rw [map_smul, smul_comm]
    exact (ih (shiftsDegree_of_mem_dopGenSpanBi hx)).smul r

/-- **Mellit, the shift realises the second homomorphism on the finite part.** This is
`HJO.Sym.nsShiftComp_comp_smul_map`: for `S` an index shift of `HJO.Sym.IsIndexShift` and `E` in the
bidegree-`(m, c)` part of the algebra the basic operators generate,

    τ^*τ ∘ ((-1)^m S(E)) = Ê ∘ τ^*τ

as maps `Λ → Λ̂`. Informally it reads `τ^*τ S(E) = E τ^*τ`, the `E` on the right being read on the
completion, which is `Ê = HJO.Sym.completionExtension`; the orientation is the one of
`HJO.Sym.nsShiftComp_comp_dopInt`.

**The `(-1)^m` is not an ad hoc correction but the forced repair.**
`HJO.Sym.IsIndexShift`'s unsigned normalisation does *not* satisfy this identity —
`HJO.Sym.not_nsTransports_isIndexShift` refutes it at `E = D_0`, and
`HJO.Sym.not_nsShiftComp_dopInt_neg_one` refutes the unsigned candidate outright — and the repair
is the `(-1)^m`-twist of `HJO.Dyck.Tilde.rel_biHomogeneous` on the bidegree-`(m, n)` component,
which is the sign by which Mellit's shift differs from the unsigned one (§3.7). That is what this
is, at `m` = the number of basic operators in a word = the number of raising arrows.

Three things the printed statement does not carry. The bidegree: `c` is what makes `Ê` exist and `m`
is what makes the twist constant, and between them they cost nothing beyond homogeneity, since
`HJO.Sym.mem_iSup_dopGenSpanBi` says the bigraded pieces span `𝖠` and
`HJO.Sym.nsTransports_sum_of_mem_dopGenSpanBi` reads the identity on a mixed element against a
decomposition. `hM` is inherited from `HJO.Sym.nsShiftComp_comp_dopInt`, where the displaced
`Exp[-X/M]` splits; the `𝕜` discharges it by algebraic independence. And the generating set is the
`D_k`, which is the generating set of the algebra `HJO.Sym.IsIndexShift` is an endomorphism of — see
the module docstring for why that is the reading `HJO.Sym.IsIndexShift` imposes and what
`HJO.Sweep.exists_isDpaAction_mellit` would add. -/
@[hjo "lem_mellit_ns_shift_algebra"]
theorem nsShiftComp_comp_smul_map (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsIndexShift q u S)
    {m c : ℕ} {E : DopAlgebra q u} (hE : E ∈ dopGenSpanBi q u m c) :
    (nsShiftComp q u).comp (((-1 : K) ^ m • S E : DopAlgebra q u) : Module.End K (Lambda K))
      = (completionExtension (shiftsDegree_of_mem_dopGenSpanBi hE)).comp (nsShiftComp q u) :=
  LinearMap.ext (nsTransports_smul_map_of_mem_dopGenSpanBi q u hM hS hE
    (shiftsDegree_of_mem_dopGenSpanBi hE))

/-- **The main result at a basic operator is `HJO.Sym.nsShiftComp_comp_dopInt`.** `D_n` occupies
the bidegree `(1, n)`, where the twist is a single minus, so the identity reads
`τ^*τ(-D_{n+1}) = D̂_nτ^*τ` — which is exactly `HJO.Sym.nsShiftComp_comp_dopInt`. Stated to pin the
statement against the one case where its content is already known, since a statement whose
hypotheses could not be met would read the same as this one and prove nothing. -/
theorem coe_map_dopGen_eq {q u : K}
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsIndexShift q u S) (n : ℕ) :
    (((-1 : K) ^ 1 • S (dopGen q u n) : DopAlgebra q u) : Module.End K (Lambda K))
      = -Dop q u (n + 1) := by
  rw [hS n]
  change (-1 : K) ^ 1 • (Dop q u (n + 1) : Module.End K (Lambda K)) = _
  rw [pow_one, neg_one_smul]

/-- **The twisted shift is the only solution**, `HJO.Sym.nsShiftComp_eq_of_eq` read against the
main result. -/
theorem eq_smul_map_of_nsTransports (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsIndexShift q u S)
    {m c : ℕ} {E : DopAlgebra q u} (hE : E ∈ dopGenSpanBi q u m c)
    {F : Module.End K (Lambda K)}
    (hF : NsTransports q u (shiftsDegree_of_mem_dopGenSpanBi hE) F) :
    F = (((-1 : K) ^ m • S E : DopAlgebra q u) : Module.End K (Lambda K)) :=
  nsShiftComp_eq_of_eq q u _ hF (nsTransports_smul_map_of_mem_dopGenSpanBi q u hM hS hE _)

/-! ### The same statement with the twist carried by a single algebra map -/

/-- **`HJO.Sym.nsShiftComp_comp_smul_map`, pointwise.** For `S` a twisted index shift and `E` in the
degree-`c` part of the algebra the basic operators generate, `E` transports `S(E)`:
`τ^*τ(S(E)f) = Ê(τ^*τ f)` for every `f ∈ Λ`.

The words are `HJO.Sym.nsTransports_dopWord` — `HJO.Sym.nsShiftComp_comp_dopInt` closed
under `HJO.Sym.nsShiftComp_mul` — and the span is `HJO.Sym.NsTransports.add` and
`HJO.Sym.NsTransports.smul`, which is where the fixed degree is spent: the two sides are linear in
the pair `(E, S(E))` only at a fixed degree, since otherwise the left-hand `Ê` does not exist. -/
theorem nsTransports_map_of_mem_dopGenSpan (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsNsIndexShift q u S)
    {c : ℕ} {E : DopAlgebra q u} (hE : E ∈ dopGenSpan q u c)
    (hEs : ShiftsDegree (c : ℤ) ((E : Module.End K (Lambda K)))) :
    NsTransports q u hEs ((S E : Module.End K (Lambda K))) := by
  revert hEs
  induction hE using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨ns, hsum, rfl⟩ := hx
    subst hsum
    intro _
    refine NsTransports.congr rfl (dopGenWord_coe q u ns).symm ?_
      (nsTransports_dopWord q u hM ns)
    rw [map_dopGenWord hS, dopGenWordShift_coe]
  | zero =>
    intro _
    rw [map_zero]
    exact nsTransports_zero q u _
  | add x y hx hy ihx ihy =>
    intro _
    rw [map_add]
    exact (ihx (shiftsDegree_of_mem_dopGenSpan hx)).add (ihy (shiftsDegree_of_mem_dopGenSpan hy))
  | smul r x hx ih =>
    intro _
    rw [map_smul]
    exact (ih (shiftsDegree_of_mem_dopGenSpan hx)).smul r

/-- **The statement with the twist inside the map.** For `S` a twisted index shift and `E` in the
degree-`c` part of the algebra the basic operators generate,

    τ^*τ ∘ S(E) = Ê ∘ τ^*τ

as maps `Λ → Λ̂`. This is `HJO.Sym.nsShiftComp_comp_smul_map` with the `(-1)^m` carried by `S`
rather than written beside it, and the word length correspondingly free: a single algebra map can
mix lengths, so only the degree `c` is fixed here.

The main result is the other form, because `HJO.Sym.IsIndexShift` is satisfiable
(`HJO.Bglx.exists_isIndexShift_param`, with no hypothesis at the standing field), while nothing here
exhibits a twisted index shift — it would be the descent of `x_k ↦ -x_{k+1}` along
`HJO.Sym.dopFreeHom`, which needs a stability statement not proved here.
`HJO.Sym.coe_map_eq_smul_coe_map` says the two readings agree wherever both apply, so this is not a
third normalisation. -/
theorem nsShiftComp_comp_map (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsNsIndexShift q u S)
    {c : ℕ} {E : DopAlgebra q u} (hE : E ∈ dopGenSpan q u c) :
    (nsShiftComp q u).comp (S E : Module.End K (Lambda K))
      = (completionExtension (shiftsDegree_of_mem_dopGenSpan hE)).comp (nsShiftComp q u) :=
  LinearMap.ext
    (nsTransports_map_of_mem_dopGenSpan q u hM hS hE (shiftsDegree_of_mem_dopGenSpan hE))

/-- **The shift is the only solution**, `HJO.Sym.nsShiftComp_eq_of_eq` read against the statement:
no other endomorphism of `Λ` satisfies the identity `HJO.Sym.nsShiftComp_comp_map` states for
`S(E)`. -/
theorem eq_map_of_nsTransports (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsNsIndexShift q u S)
    {c : ℕ} {E : DopAlgebra q u} (hE : E ∈ dopGenSpan q u c)
    {F : Module.End K (Lambda K)} (hF : NsTransports q u (shiftsDegree_of_mem_dopGenSpan hE) F) :
    F = (S E : Module.End K (Lambda K)) :=
  nsShiftComp_eq_of_eq q u _ hF
    (nsTransports_map_of_mem_dopGenSpan q u hM hS hE (shiftsDegree_of_mem_dopGenSpan hE))

/-! ### The two readings agree -/

/-- **The twist written beside the map and the twist carried inside it give the same operator.**
Both transport the same `E`, so `HJO.Sym.nsShiftComp_eq_of_eq` identifies them. So
`HJO.Sym.IsNsIndexShift` is the `(-1)^m`-twist of `HJO.Sym.IsIndexShift` on the nose, and not a
second normalisation that would have to be reconciled. -/
theorem coe_map_eq_smul_coe_map (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S T : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsIndexShift q u S)
    (hT : IsNsIndexShift q u T)
    {m c : ℕ} {E : DopAlgebra q u} (hE : E ∈ dopGenSpanBi q u m c) :
    ((T E : DopAlgebra q u) : Module.End K (Lambda K))
      = (((-1 : K) ^ m • S E : DopAlgebra q u) : Module.End K (Lambda K)) :=
  eq_smul_map_of_nsTransports q u hM hS hE
    (nsTransports_map_of_mem_dopGenSpan q u hM hT (dopGenSpanBi_le_dopGenSpan q u m c hE)
      (shiftsDegree_of_mem_dopGenSpanBi hE))

/-! ### The bigraded pieces span the algebra -/

theorem exists_dopWord_of_mem_closure (q u : K) {x : Module.End K (Lambda K)}
    (hx : x ∈ Submonoid.closure (Set.range (Dop q u))) :
    ∃ ns : List ℕ, dopWord q u ns = x := by
  induction hx using Submonoid.closure_induction with
  | mem x hx =>
    obtain ⟨n, rfl⟩ := hx
    exact ⟨[n], by rw [dopWord_cons, dopWord_nil, mul_one]⟩
  | one => exact ⟨[], dopWord_nil q u⟩
  | mul x y _ _ ihx ihy =>
    obtain ⟨nsx, rfl⟩ := ihx
    obtain ⟨nsy, rfl⟩ := ihy
    exact ⟨nsx ++ nsy, by rw [dopWord, dopWord, dopWord, List.map_append, List.prod_append]⟩

/-- **The bigraded pieces span `𝖠`.** Every element of the algebra the basic operators generate is a
finite sum of elements of the `HJO.Sym.dopGenSpanBi q u m c`, so the bihomogeneity side condition of
`HJO.Sym.nsShiftComp_comp_smul_map` restricts the statement to no subalgebra: it restricts it to the
elements for which its own right-hand side, and its own twist, are defined. -/
theorem mem_iSup_dopGenSpanBi (q u : K) (E : DopAlgebra q u) :
    E ∈ ⨆ p : ℕ × ℕ, dopGenSpanBi q u p.1 p.2 := by
  have key : Subalgebra.toSubmodule (DopAlgebra q u)
      ≤ Submodule.map (Subalgebra.val (DopAlgebra q u)).toLinearMap
        (⨆ p : ℕ × ℕ, dopGenSpanBi q u p.1 p.2) := by
    have hspan : Subalgebra.toSubmodule (DopAlgebra q u)
        = Submodule.span K (Submonoid.closure (Set.range (Dop q u))) :=
      Algebra.adjoin_eq_span K (Set.range (Dop q u))
    rw [hspan]
    refine Submodule.span_le.2 fun x hx => ?_
    obtain ⟨ns, rfl⟩ := exists_dopWord_of_mem_closure q u hx
    exact ⟨dopGenWord q u ns,
      Submodule.mem_iSup_of_mem (ns.length, ns.sum) (dopGenWord_mem_dopGenSpanBi q u ns),
      dopGenWord_coe q u ns⟩
  obtain ⟨y, hy, hyE⟩ := key E.2
  exact Subtype.ext hyE ▸ hy

/-- **The statement on an element that is not bihomogeneous.** Such an element has no single
extension to the completion and no single twist, but it is a finite sum of bihomogeneous parts
(`HJO.Sym.mem_iSup_dopGenSpanBi`), and against any such decomposition the identity reads: `τ^*τ` of
the twisted shift of the parts is the sum of their extensions, applied to `τ^*τ`. This is the whole
of what the two side conditions of `HJO.Sym.nsShiftComp_comp_smul_map` cost. -/
theorem nsTransports_sum_of_mem_dopGenSpanBi (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsIndexShift q u S)
    {P : ℕ × ℕ → DopAlgebra q u} (hP : ∀ p : ℕ × ℕ, P p ∈ dopGenSpanBi q u p.1 p.2)
    (s : Finset (ℕ × ℕ)) (f : Lambda K) :
    nsShiftComp q u (((∑ p ∈ s, (-1 : K) ^ p.1 • S (P p) : DopAlgebra q u) :
        Module.End K (Lambda K)) f)
      = ∑ p ∈ s, completionExtension (shiftsDegree_of_mem_dopGenSpanBi (hP p))
          (nsShiftComp q u f) := by
  induction s using Finset.induction_on with
  | empty =>
    rw [Finset.sum_empty, Finset.sum_empty]
    exact map_zero _
  | insert a s ha ih =>
    rw [Finset.sum_insert ha, Finset.sum_insert ha, coe_add_dopAlgebra, LinearMap.add_apply,
      map_add, nsTransports_smul_map_of_mem_dopGenSpanBi q u hM hS (hP a)
        (shiftsDegree_of_mem_dopGenSpanBi (hP a)) f, ih]

end Field

end HJO.Sym

end
