/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitCompletionFrac
public meta import HJO.Attr

/-! # The generator checks of `HJO.Sym.nsShiftComp_comp_smul_map`

`HJO.Sym.nsShiftComp_comp_smul_map` reduces, by `HJO.Sym.nsShiftComp_mul` and
`HJO.Sym.nsShiftComp_eq_of_eq`, to checking `ττ^*S(g) = gττ^*` at each generator `g` of the
subalgebra — `y_i`, `T_i`, `d_-`, `d^*_+` — with both shifts read on every `V_k`. This file is those
checks. The
two relations at `d^*_+` are proved elsewhere (`HJO.Sweep.hatFracDplusStar_nsShiftStarFrac`,
`HJO.Sweep.fracDplusStar_nsShiftExt`); what is here is everything the other three need, and two
lemmas fall out on the way.

## The four checks, and what each one costs

* **`y_i`** is free: both extensions are multiplication by a fixed element composed (for `τ_k`) with
  `ϑ`, and `ϑ` fixes every auxiliary variable while multiplication is commutative. No lemma below
  is needed for it.
* **`T_i`** needs that the two multipliers are symmetric in `y_i, y_{i+1}` and that `T_i` is linear
  over a symmetric multiplier. The second is `HJO.Sweep.braid_symmetric_mul`. The first is
  `HJO.Sweep.swapAux_cornerAlphabet` and `HJO.Sweep.swapAux_auxProd`. That `ϑ` commutes with `T_i`
  is `HJO.Sweep.unitShiftTotal_braid`.
* **`d_-` against `τ^*_k`** is `HJO.Sweep.dminusCM_cornerAlphabet_mul`, and it has its
  own derivation: `τ^-_{k,k}(E_k) = E_{k-1}` (`HJO.Sweep.hatMap_qshiftNeg_cornerMultiplier`),
  `E_{k-1}` is free of `y_k`, and the coefficient extraction is linear over anything free of `y_k`
  (`HJO.Sweep.lowerCoeffShift_mul_of_mem_piece`).
* **`d_-` against `τ_k`** is `HJO.Sweep.dminusCM_unitShiftTotal_core` and its `k`-fold form
  `HJO.Sweep.dminusCM_auxProd_unitShiftTotal`. This is the branch that looks as
  though no one-line reason will serve, and its last step is `ϑ(e_{m+1}) = e_{m+1} + e_m`. Both
  halves are proved: `HJO.Sweep.unitShiftTotal_dminusCM` and — proved here, the other lemma
  this file contributes — `HJO.Sweep.dminusCM_eq_neg_dminus_auxVar_mul`, `d_-F = -d^♭_-(y_kF)`.

## The one-line reason the fourth check is short

`ϑ d_- = d_-ϑ + d^♭_-ϑ` is `HJO.Sweep.unitShiftTotal_dminusCM`, and `d^♭_-(y_kG) = -d_-(G)` is
`HJO.Sweep.dminusCM_eq_neg_dminus_auxVar_mul`. Put `G = y_{k+1}H` in the first and the second turns
its correction term into `-d_-(ϑH)`, which is exactly the term the factor `y_{k+1} - 1` of `τ_{k+1}`
contributes. So the check is `sub_mul` and two rewrites — **the whole content of the longest
paragraph in Section 3.7 is those two identities meeting.**

Each of the two `d_-` checks is proved twice, once for `d_-` of `HJO.Sweep.dminusCM` and once for
`d^♭_-` of `HJO.Sweep.dminus`: `HJO.Sweep.exists_isDpaAction_mellit` sends the quiver's lowering
arrow to the second while `HJO.Sym.nsShiftComp_comp_smul_map`'s proof computes with the first, and
the two statements do not agree on which operator the check is owed.

## What else `HJO.Sym.nsShiftComp_comp_smul_map` needs

In Mellit's form the statement quantifies over `L` in the subalgebra of `e_0Ãe_0` **acting on
`Λ`**, and that action is `HJO.Sweep.exists_isDpaAction_mellit`. Two further points separate that
form from the one proved in `HJO/Shuffle/MellitShiftTwisted.lean`: `HJO.Sym.IsIndexShift` has as
domain the algebra `𝖠` generated by the `D_k` inside `End(Λ)`, not `Ã`; and an unsigned conclusion
would carry no sign where `HJO.Sym.nsShiftComp_comp_dopInt` carries one, so the shift has to carry
it.

## References

Transcribing A. Mellit, *Toric braids and
`(m,n)`-parking functions*, §§3.2, 3.7.
-/

@[expose] public section

open Finset MvPolynomial

namespace HJO.Sweep

/-! ### The coefficient extraction against a multiplier free of the last letter -/

section Extraction

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- **Multiplying by `y_{j+1}` turns one extraction into the other, with a sign.** On a `y`-monomial
the exponent at `j` goes up by one, so the elementary function `HJO.Sweep.lowerCoeff` picks up is
the one `HJO.Sweep.lowerCoeffShift` picks up already, and the sign flips. -/
theorem lowerCoeff_auxVar_mul (j : ℕ) (H : Total L) :
    lowerCoeff L j ((MvPolynomial.X j : Total L) * H) = -lowerCoeffShift L j H := by
  induction H using MvPolynomial.induction_on' with
  | monomial m a =>
    set m' : ℕ →₀ ℕ := Finsupp.single j 1 + m with hm'
    have hmul : (MvPolynomial.X j : Total L) * MvPolynomial.monomial m a
        = MvPolynomial.monomial m' a := by
      rw [MvPolynomial.X, hm', MvPolynomial.monomial_mul, one_mul]
    have hj : m' j = m j + 1 := by
      rw [hm']
      simp [add_comm]
    have herase : Finsupp.erase j m' = Finsupp.erase j m := by
      refine Finsupp.ext fun i => ?_
      by_cases hi : i = j
      · subst hi; rw [Finsupp.erase_same, Finsupp.erase_same]
      · rw [Finsupp.erase_ne hi, Finsupp.erase_ne hi, hm', Finsupp.add_apply]
        simp [show ¬(j = i) from fun h => hi h.symm]
    rw [hmul, lowerCoeff_monomial', lowerCoeffShift_monomial', hj, herase]
    ring
  | add p q hp hq => rw [mul_add, map_add, map_add, hp, hq]; ring

/-- The extraction is linear over a `y`-monomial that does not involve `y_{j+1}`. -/
theorem lowerCoeffShift_monomial_mul {j : ℕ} {n : ℕ →₀ ℕ} (hn : n j = 0) (b : Sym.Lambda L)
    (H : Total L) :
    lowerCoeffShift L j (MvPolynomial.monomial n b * H)
      = MvPolynomial.monomial n b * lowerCoeffShift L j H := by
  induction H using MvPolynomial.induction_on' with
  | monomial m a =>
    have hsum : (n + m) j = m j := by rw [Finsupp.add_apply, hn, zero_add]
    have herase : Finsupp.erase j (n + m) = n + Finsupp.erase j m := by
      refine Finsupp.ext fun i => ?_
      by_cases hi : i = j
      · subst hi
        rw [Finsupp.erase_same, Finsupp.add_apply, Finsupp.erase_same, hn, add_zero]
      · rw [Finsupp.erase_ne hi, Finsupp.add_apply, Finsupp.add_apply, Finsupp.erase_ne hi]
    have h1 : (MvPolynomial.monomial (n + Finsupp.erase j m) (1 : Sym.Lambda L) : Total L)
        = MvPolynomial.monomial n 1 * MvPolynomial.monomial (Finsupp.erase j m) 1 := by
      rw [MvPolynomial.monomial_mul, one_mul]
    have h2 : (MvPolynomial.monomial n b : Total L)
        = MvPolynomial.C b * MvPolynomial.monomial n 1 := by
      rw [MvPolynomial.C_mul_monomial, mul_one]
    rw [MvPolynomial.monomial_mul, lowerCoeffShift_monomial', lowerCoeffShift_monomial',
      hsum, herase, MvPolynomial.C_mul, h1, h2]
    ring
  | add p q hp hq => rw [mul_add, map_add, map_add, hp, hq, mul_add]

omit [Algebra ℚ L] in
/-- An element of `V_j` uses no `y`-monomial with an exponent at the variable `y_{j+1}`. -/
theorem exponent_eq_zero_of_mem_piece {j : ℕ} {A : Total L} (hA : A ∈ piece L j) {m : ℕ →₀ ℕ}
    (hm : m ∈ A.support) : m j = 0 := by
  by_contra hne
  have hj : j ∈ A.vars :=
    (MvPolynomial.mem_vars_iff_mem_support j).2 ⟨m, hm, Finsupp.mem_support_iff.2 hne⟩
  have hsub : ↑A.vars ⊆ Set.Iio j := MvPolynomial.mem_supported.1 hA
  exact absurd (hsub hj) (by simp)

/-- **The extraction of `d_-` is linear over `V_j`**, which is what "`E_{k-1}` is free of `y_k`, so
it comes out of the coefficient extraction" means. -/
theorem lowerCoeffShift_mul_of_mem_piece {j : ℕ} {A : Total L} (hA : A ∈ piece L j)
    (H : Total L) : lowerCoeffShift L j (A * H) = A * lowerCoeffShift L j H := by
  conv_lhs => rw [A.as_sum]
  conv_rhs => rw [A.as_sum]
  rw [Finset.sum_mul, map_sum, Finset.sum_mul]
  exact Finset.sum_congr rfl fun m hm =>
    lowerCoeffShift_monomial_mul (exponent_eq_zero_of_mem_piece hA hm) _ H

theorem dminusCM_succ_apply (q : L) (k : ℕ) (F : Total L) :
    dminusCM q (k + 1) F = lowerCoeffShift L k (qshiftNeg q (k + 1) F) := rfl

theorem dminus_succ_apply (q : L) (k : ℕ) (F : Total L) :
    dminus q (k + 1) F = lowerCoeff L k (qshiftNeg q (k + 1) F) := rfl

/-- **The two lowering operators.** `HJO.Sweep.dminusCM_eq_neg_dminus_auxVar_mul`:
`d_-F = -d^♭_-(y_kF)`, with `d_-` the operator of `HJO.Sweep.dminusCM` and `d^♭_-` the modified one
of `HJO.Sweep.dminus`.

`τ^-_{k,k}` fixes `y_k`, so multiplying by `y_k` before the extraction shifts every `y_k`-exponent
up by one; the modified extraction then meets the elementary function the unmodified one would have
met, and the sign of the `y_k`-exponent flips. That is
`HJO.Sweep.lowerCoeff_auxVar_mul`. -/
@[hjo "lem_vmod_dminus_compare"]
theorem dminusCM_eq_neg_dminus_auxVar_mul (q : L) (k : ℕ) (F : Total L) :
    dminusCM q (k + 1) F = -dminus q (k + 1) ((auxVar (k + 1) : Total L) * F) := by
  have hav : (auxVar (k + 1) : Total L) = MvPolynomial.X k := by
    rw [auxVar, Nat.add_sub_cancel]
  rw [dminus_succ_apply, map_mul, qshiftNeg_auxVar_apply, hav, lowerCoeff_auxVar_mul,
    dminusCM_succ_apply, neg_neg]

end Extraction

/-! ### The corner multiplier inside `V_k` -/

section Piece

variable {L : Type*} [Field L] [Algebra ℚ L]

omit [Algebra ℚ L] in
/-- **The alphabet substitution lands in `V_k`.** Every generator goes to a combination of a
constant of `Λ` and of `y_1, …, y_k`, and `V_k` is a `Λ`-subalgebra. -/
theorem cornerAlphabet_mem_piece (q u : L) (k : ℕ) (f : Sym.Lambda L) :
    cornerAlphabet q u k f ∈ piece L k := by
  induction f using MvPolynomial.induction_on with
  | C a =>
    have h : (cornerAlphabet q u k) (MvPolynomial.C a) = algebraMap L (Total L) a := by
      rw [← MvPolynomial.algebraMap_eq, AlgHom.commutes]
    rw [h, show (algebraMap L (Total L)) a
      = algebraMap (Sym.Lambda L) (Total L) (algebraMap L (Sym.Lambda L) a) from rfl]
    exact Subalgebra.algebraMap_mem _ _
  | add p r hp hr => rw [map_add]; exact add_mem hp hr
  | mul_X p i hp =>
    rw [map_mul]
    refine mul_mem hp ?_
    rw [show (MvPolynomial.X i : Sym.Lambda L) = Sym.powerSum L (i + 1) by
      rw [Sym.powerSum, Nat.add_sub_cancel], cornerAlphabet_powerSum]
    refine neg_mem (add_mem (mul_mem ?_ ?_) (mul_mem ?_ ?_))
    · exact Subalgebra.algebraMap_mem _ _
    · exact Subalgebra.algebraMap_mem _ _
    · exact Subalgebra.algebraMap_mem _ _
    · refine Subalgebra.sum_mem _ fun j hj => pow_mem (auxVar_mem_piece (by omega) ?_) _
      rw [Finset.mem_range] at hj
      omega

omit [Algebra ℚ L] in
/-- **`τ^-_{k+1,k+1}` retracts the alphabet**, the elementwise form of
`HJO.Sweep.hatMap_qshiftNeg_cornerMultiplier`. -/
theorem qshiftNeg_cornerAlphabet (q u : L) (hq : ∀ r : ℕ, 1 ≤ r → q ^ r ≠ 1) (k : ℕ)
    (f : Sym.Lambda L) :
    qshiftNeg q (k + 1) (cornerAlphabet q u (k + 1) f) = cornerAlphabet q u k f := by
  have h := congrArg (fun g : Sym.Lambda L →ₐ[L] Total L => g f)
    (qshift_cornerAlphabet q u hq k)
  rw [← h, AlgHom.comp_apply, qshiftNeg_qshift]

/-- **The check at `d_-` against `τ^*_k`**: `d_-(E_kF) = E_{k-1}d_-(F)`, memberwise.

Three steps: `τ^-_{k,k}` is multiplicative, it carries `E_k` to `E_{k-1}`, and
`E_{k-1}` lies in `V_{k-1}` so it comes out of the coefficient extraction. -/
theorem dminusCM_cornerAlphabet_mul (q u : L) (hq : ∀ r : ℕ, 1 ≤ r → q ^ r ≠ 1) (k : ℕ)
    (f : Sym.Lambda L) (F : Total L) :
    dminusCM q (k + 1) (cornerAlphabet q u (k + 1) f * F)
      = cornerAlphabet q u k f * dminusCM q (k + 1) F := by
  rw [dminusCM_succ_apply, dminusCM_succ_apply, map_mul, qshiftNeg_cornerAlphabet q u hq k,
    lowerCoeffShift_mul_of_mem_piece (cornerAlphabet_mem_piece q u k f)]

end Piece

/-! ### The check at `d_-` against the unit shift -/

section UnitShift

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- `∏_{i=1}^{k}(y_i - 1)`, the polynomial form of `τ_k`'s multiplier: the product
`y_1⋯y_k∏_{i≤k}(1-y_i^{-1})` is this product, which is why `τ_k` takes `y_1⋯y_kV_k` into `V_k`. -/
noncomputable def auxProd (L : Type*) [Field L] (k : ℕ) : Total L :=
  ∏ i ∈ range k, ((auxVar (i + 1) : Total L) - 1)

omit [Algebra ℚ L] in
theorem auxProd_mem_piece (k : ℕ) : auxProd L k ∈ piece L k :=
  Subalgebra.prod_mem _ fun i hi => sub_mem
    (auxVar_mem_piece (by omega) (by rw [Finset.mem_range] at hi; omega)) (one_mem _)

omit [Algebra ℚ L] in
theorem qshiftNeg_auxProd (q : L) (m k : ℕ) :
    qshiftNeg q m (auxProd L k) = auxProd L k := by
  rw [auxProd, map_prod]
  exact Finset.prod_congr rfl fun i _ => by rw [map_sub, map_one, qshiftNeg_auxVar_apply]

omit [Algebra ℚ L] in
theorem unitShiftTotal_auxProd (k : ℕ) :
    unitShiftTotal L (auxProd L k) = auxProd L k := by
  rw [auxProd, map_prod]
  exact Finset.prod_congr rfl fun i _ => by rw [map_sub, map_one, unitShiftTotal_auxVar]

/-- `d_-` is linear over the first `k` factors of `τ_{k+1}`'s multiplier, which involve no
`y_{k+1}`. -/
theorem dminusCM_auxProd_mul (q : L) (k : ℕ) (H : Total L) :
    dminusCM q (k + 1) (auxProd L k * H) = auxProd L k * dminusCM q (k + 1) H := by
  rw [dminusCM_succ_apply, dminusCM_succ_apply, map_mul, qshiftNeg_auxProd,
    lowerCoeffShift_mul_of_mem_piece (auxProd_mem_piece k)]

/-- **The check at `d_-` against `τ_k`, in one letter**:
`d_-((y_{k+1}-1)ϑG) = ϑ(d_-(y_{k+1}G))`.

This is the longest paragraph in Section 3.7, and it is two proved identities meeting.
`HJO.Sweep.unitShiftTotal_dminusCM` turns `ϑ(d_-(y_{k+1}G))` into
`d_-(y_{k+1}ϑG) + d^♭_-(y_{k+1}ϑG)`, and `HJO.Sweep.dminusCM_eq_neg_dminus_auxVar_mul` turns the
second summand into `-d_-(ϑG)` — which is exactly what the factor `y_{k+1} - 1` contributes on the
left. -/
theorem dminusCM_unitShiftTotal_core (q : L) (k : ℕ) (G : Total L) :
    dminusCM q (k + 1) (((auxVar (k + 1) : Total L) - 1) * unitShiftTotal L G)
      = unitShiftTotal L (dminusCM q (k + 1) ((auxVar (k + 1) : Total L) * G)) := by
  have hcompare : dminus q (k + 1) ((auxVar (k + 1) : Total L) * unitShiftTotal L G)
      = -dminusCM q (k + 1) (unitShiftTotal L G) := by
    rw [dminusCM_eq_neg_dminus_auxVar_mul q k (unitShiftTotal L G), neg_neg]
  have hmul : unitShiftTotal L ((auxVar (k + 1) : Total L) * G)
      = (auxVar (k + 1) : Total L) * unitShiftTotal L G := by
    rw [map_mul, unitShiftTotal_auxVar]
  rw [unitShiftTotal_dminusCM, hmul, hcompare, sub_mul, one_mul, map_sub, sub_eq_add_neg]

/-- **The check at `d_-` against `τ_k`, in the `k`-fold form**:
`d_-(τ_{k+1}F) = τ_k(d_-F)` for `F = y_1⋯y_{k+1}G`, both sides written in the polynomial form the
multiplier takes there. The first `k` factors pass through `d_-` and the last one is the identity
above. -/
theorem dminusCM_auxProd_unitShiftTotal (q : L) (k : ℕ) (G : Total L) :
    dminusCM q (k + 1) (auxProd L (k + 1) * unitShiftTotal L G)
      = auxProd L k * unitShiftTotal L (dminusCM q (k + 1) ((auxVar (k + 1) : Total L) * G)) := by
  have hprod : auxProd L (k + 1) = auxProd L k * ((auxVar (k + 1) : Total L) - 1) := by
    rw [auxProd, auxProd, Finset.prod_range_succ]
  rw [hprod, mul_assoc, dminusCM_auxProd_mul, dminusCM_unitShiftTotal_core]

end UnitShift

/-! ### The check at `T_i` -/

section Braid

variable {L : Type*} [Field L]

/-- `∂_i` is linear over a multiplier symmetric in `y_i` and `y_{i+1}`: `s_i` being a ring
homomorphism, the numerator `gF - s_i(gF)` is `g(F - s_iF)`. -/
theorem dividedDiff_symmetric_mul {i : ℕ} (hi : 1 ≤ i) {g : Total L}
    (hg : swapAux L i g = g) (F : Total L) :
    dividedDiff i (g * F) = g * dividedDiff i F := by
  refine (dividedDiff_unique hi ?_).symm
  rw [map_mul, hg, ← mul_sub, ← dividedDiff_spec i F]
  ring

/-- **The braid operator is linear over a symmetric multiplier.** This is
`HJO.Sweep.braid_symmetric_mul`: for `s_ig = g`, `T_i(gF) = gT_iF`.

`T_i = s_i + (q-1)y_i∂_i`, `s_i` is multiplicative and fixes `g`, and `∂_i` is linear over `g` by
`HJO.Sweep.dividedDiff_symmetric_mul`. The `k ≥ 2` and `1 ≤ i ≤ k-1` carry no content
here: at the unread index `0` both operators are the identity. -/
@[hjo "lem_vmod_braid_symmetric_mult"]
theorem braid_symmetric_mul (q : L) {i : ℕ} {g : Total L} (hg : swapAux L i g = g)
    (F : Total L) : braid q i (g * F) = g * braid q i F := by
  rcases Nat.eq_zero_or_pos i with rfl | hi
  · rw [braid_zero_index, braid_zero_index]
  rw [braid_apply, braid_apply, map_mul, hg, dividedDiff_symmetric_mul hi hg]
  ring

end Braid

/-! ### Both multipliers are symmetric -/

section Symmetric

variable {L : Type*} [Field L] [Algebra ℚ L]

omit [Algebra ℚ L] in
/-- **The corner multiplier is symmetric in `y_1, …, y_k`.** `cy` aside, `s_i` fixes every `p_r` and
permutes the letters `y_1, …, y_k` among themselves, which is the sum the alphabet adds. -/
theorem swapAux_cornerAlphabet (q u : L) {i k : ℕ} (hi : 1 ≤ i) (hik : i + 1 ≤ k)
    (f : Sym.Lambda L) :
    swapAux L i (cornerAlphabet q u k f) = cornerAlphabet q u k f := by
  set A : Total L →ₐ[L] Total L := (swapAux L i).toAlgHom.restrictScalars L with hA
  have hAapp : ∀ G : Total L, A G = swapAux L i G := fun _ => rfl
  have key : A.comp (cornerAlphabet q u k) = cornerAlphabet q u k := by
    refine MvPolynomial.algHom_ext fun j => ?_
    have hx : (MvPolynomial.X j : Sym.Lambda L) = Sym.powerSum L (j + 1) := by
      rw [Sym.powerSum, Nat.add_sub_cancel]
    have hsum : swapAux L i (∑ m ∈ range k, (auxVar (m + 1) : Total L) ^ (j + 1))
        = ∑ m ∈ range k, (auxVar (m + 1) : Total L) ^ (j + 1) := by
      rw [map_sum]
      refine Finset.sum_equiv (Equiv.swap (i - 1) i) (fun m => ?_) (fun m _ => ?_)
      · simp only [Finset.mem_range]
        rcases eq_or_ne m (i - 1) with rfl | h1
        · rw [Equiv.swap_apply_left]; omega
        rcases eq_or_ne m i with rfl | h2
        · rw [Equiv.swap_apply_right]; omega
        · rw [Equiv.swap_apply_of_ne_of_ne h1 h2]
      · rw [map_pow, auxVar, Nat.add_sub_cancel, swapAux_X, auxVar, Nat.add_sub_cancel]
    rw [AlgHom.comp_apply, hAapp, hx, cornerAlphabet_powerSum, map_neg, map_add, map_mul, map_mul,
      hsum, swapAux_scal, swapAux_scal, swapAux_C]
  exact congrArg (fun g : Sym.Lambda L →ₐ[L] Total L => g f) key

omit [Algebra ℚ L] in
/-- **`τ_k`'s multiplier is symmetric in `y_1, …, y_k`.** -/
theorem swapAux_auxProd {i k : ℕ} (hi : 1 ≤ i) (hik : i + 1 ≤ k) :
    swapAux L i (auxProd L k) = auxProd L k := by
  rw [auxProd, map_prod]
  refine Finset.prod_equiv (Equiv.swap (i - 1) i) (fun m => ?_) (fun m _ => ?_)
  · simp only [Finset.mem_range]
    rcases eq_or_ne m (i - 1) with rfl | h1
    · rw [Equiv.swap_apply_left]; omega
    rcases eq_or_ne m i with rfl | h2
    · rw [Equiv.swap_apply_right]; omega
    · rw [Equiv.swap_apply_of_ne_of_ne h1 h2]
  · rw [map_sub, map_one, auxVar, Nat.add_sub_cancel, swapAux_X, auxVar, Nat.add_sub_cancel]

omit [Algebra ℚ L] in
/-- **The check at `T_i` against `τ^*_k`**: the corner multiplier passes through `T_i`. -/
theorem braid_cornerAlphabet_mul (q u : L) {i k : ℕ} (hi : 1 ≤ i) (hik : i + 1 ≤ k)
    (f : Sym.Lambda L) (F : Total L) :
    braid q i (cornerAlphabet q u k f * F) = cornerAlphabet q u k f * braid q i F :=
  braid_symmetric_mul q (swapAux_cornerAlphabet q u hi hik f) F

omit [Algebra ℚ L] in
/-- **The check at `T_i` against `τ_k`**: `τ_k`'s multiplier passes through `T_i`, and `ϑ` commutes
with `T_i` by `HJO.Sweep.unitShiftTotal_braid`. -/
theorem braid_auxProd_mul (q : L) {i k : ℕ} (hi : 1 ≤ i) (hik : i + 1 ≤ k) (F : Total L) :
    braid q i (auxProd L k * F) = auxProd L k * braid q i F :=
  braid_symmetric_mul q (swapAux_auxProd hi hik) F

end Symmetric

/-! ### The same two checks for the *modified* lowering operator

`HJO.Sweep.exists_isDpaAction_mellit` sends the quiver's lowering arrow to `d^♭_-` of
`HJO.Sweep.dminus`, not to `d_-` of `HJO.Sweep.dminusCM`, while
`HJO.Sym.nsShiftComp_comp_smul_map`'s proof computes with `d_-`. Which operator the generator check
is owed therefore depends on a reading the two statements do not agree on, so it is proved here for
both.
The modified version is if anything shorter: `d^♭_-(y_{k+1}H)` is `-d_-(H)` by
`HJO.Sweep.dminusCM_eq_neg_dminus_auxVar_mul`, so the factor `y_{k+1}-1` turns the left side into
`-(d_-(ϑG) + d^♭_-(ϑG))`, which is `-ϑ(d_-G)` by `HJO.Sweep.unitShiftTotal_dminusCM` — and that is
the right side by `HJO.Sweep.dminusCM_eq_neg_dminus_auxVar_mul` again. -/

section Modified

variable {L : Type*} [Field L] [Algebra ℚ L]

theorem lowerCoeff_monomial_mul {j : ℕ} {n : ℕ →₀ ℕ} (hn : n j = 0) (b : Sym.Lambda L)
    (H : Total L) :
    lowerCoeff L j (MvPolynomial.monomial n b * H)
      = MvPolynomial.monomial n b * lowerCoeff L j H := by
  induction H using MvPolynomial.induction_on' with
  | monomial m a =>
    have hsum : (n + m) j = m j := by rw [Finsupp.add_apply, hn, zero_add]
    have herase : Finsupp.erase j (n + m) = n + Finsupp.erase j m := by
      refine Finsupp.ext fun i => ?_
      by_cases hi : i = j
      · subst hi
        rw [Finsupp.erase_same, Finsupp.add_apply, Finsupp.erase_same, hn, add_zero]
      · rw [Finsupp.erase_ne hi, Finsupp.add_apply, Finsupp.add_apply, Finsupp.erase_ne hi]
    have h1 : (MvPolynomial.monomial (n + Finsupp.erase j m) (1 : Sym.Lambda L) : Total L)
        = MvPolynomial.monomial n 1 * MvPolynomial.monomial (Finsupp.erase j m) 1 := by
      rw [MvPolynomial.monomial_mul, one_mul]
    have h2 : (MvPolynomial.monomial n b : Total L)
        = MvPolynomial.C b * MvPolynomial.monomial n 1 := by
      rw [MvPolynomial.C_mul_monomial, mul_one]
    rw [MvPolynomial.monomial_mul, lowerCoeff_monomial', lowerCoeff_monomial',
      hsum, herase, MvPolynomial.C_mul, h1, h2]
    ring
  | add p q hp hq => rw [mul_add, map_add, map_add, hp, hq, mul_add]

theorem lowerCoeff_mul_of_mem_piece {j : ℕ} {A : Total L} (hA : A ∈ piece L j)
    (H : Total L) : lowerCoeff L j (A * H) = A * lowerCoeff L j H := by
  conv_lhs => rw [A.as_sum]
  conv_rhs => rw [A.as_sum]
  rw [Finset.sum_mul, map_sum, Finset.sum_mul]
  exact Finset.sum_congr rfl fun m hm =>
    lowerCoeff_monomial_mul (exponent_eq_zero_of_mem_piece hA hm) _ H

theorem dminus_cornerAlphabet_mul (q u : L) (hq : ∀ r : ℕ, 1 ≤ r → q ^ r ≠ 1) (k : ℕ)
    (f : Sym.Lambda L) (F : Total L) :
    dminus q (k + 1) (cornerAlphabet q u (k + 1) f * F)
      = cornerAlphabet q u k f * dminus q (k + 1) F := by
  rw [dminus_succ_apply, dminus_succ_apply, map_mul, qshiftNeg_cornerAlphabet q u hq k,
    lowerCoeff_mul_of_mem_piece (cornerAlphabet_mem_piece q u k f)]

theorem dminus_unitShiftTotal_core (q : L) (k : ℕ) (G : Total L) :
    dminus q (k + 1) (((auxVar (k + 1) : Total L) - 1) * unitShiftTotal L G)
      = unitShiftTotal L (dminus q (k + 1) ((auxVar (k + 1) : Total L) * G)) := by
  have hcompare : ∀ H : Total L, dminus q (k + 1) ((auxVar (k + 1) : Total L) * H)
      = -dminusCM q (k + 1) H := fun H => by
    rw [dminusCM_eq_neg_dminus_auxVar_mul q k H, neg_neg]
  rw [sub_mul, one_mul, map_sub, hcompare, hcompare, map_neg, unitShiftTotal_dminusCM]
  ring

theorem dminus_auxProd_mul (q : L) (k : ℕ) (H : Total L) :
    dminus q (k + 1) (auxProd L k * H) = auxProd L k * dminus q (k + 1) H := by
  rw [dminus_succ_apply, dminus_succ_apply, map_mul, qshiftNeg_auxProd,
    lowerCoeff_mul_of_mem_piece (auxProd_mem_piece k)]

theorem dminus_auxProd_unitShiftTotal (q : L) (k : ℕ) (G : Total L) :
    dminus q (k + 1) (auxProd L (k + 1) * unitShiftTotal L G)
      = auxProd L k * unitShiftTotal L (dminus q (k + 1) ((auxVar (k + 1) : Total L) * G)) := by
  have hprod : auxProd L (k + 1) = auxProd L k * ((auxVar (k + 1) : Total L) - 1) := by
    rw [auxProd, auxProd, Finset.prod_range_succ]
  rw [hprod, mul_assoc, dminus_auxProd_mul, dminus_unitShiftTotal_core]

end Modified

end HJO.Sweep

end
