/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitSlopeTwoRow
public import HJO.Shuffle.MellitShiftTwisted
public import HJO.Shuffle.MellitLhsCompInduction

/-! # Mellit's `S` on the base-case clause of `HJO.Mellit.lhsRewrite_sweepWitness`

The clause `HJO.Mellit.LhsSlope q u a b` states, for every `f ∈ Λ`,
`C(Q_{a,b}f) = (-1)^{b+1}·d_-(Ξ^{(1)}_{a,b}(y_1d^*_+(Cf)))`: the slope operator `Q_{a,b}` of
`HJO.Sym.Qop` on `Λ` is the bottom action of the slope word `Ξ_{a,b}` of `HJO.Sweep.slopeOperator`.
At `f = 1` it is the base case of `HJO.Mellit.lhsRewrite_sweepWitness`
(`HJO.Mellit.lhsBase_of_lhsSlope`). Before this file it was known on the `(1,b)` row, the `(a,1)`
column and the `(2,b)` row.

In Mellit's Section 3.7 the slopes are reached from the axis by the monoid generated by
`N = (1 1; 0 1)` and `S = (1 0; 1 1)`, acting compatibly on both sides. This file carries out the
`S` half, on both sides of the clause, and transports the clause along it:
`LhsSlope q u a b → LhsSlope q u a (b + a)`.

* **On `Λ`.** `S` is realised by `τ^*τ`, with `τ^*τ(-D_{n+1}) = D̂_nτ^*τ`
  (`HJO.Sym.nsShiftComp_comp_dopInt`). Since `S` is multiplicative and carries the split `(r,s)` of
  `(a,b)` to the split `(r, s+r)` of `(a, b+a)`, induction through `HJO.Sym.Qop`'s commutator
  recursion gives `τ^*τ((-1)^aQ_{a,b+a}) = Q̂_{a,b}τ^*τ`.
* **On the sweep side.** `S` shears the slope word, `β_{a,b+a} = 𝗒·β_{a,b}[𝗓 ↦ 𝗓𝗒]`, by
  Stern–Brocot induction from `HJO.Mellit.slopeWord_mediant`. A word applied to `y_1d^*_+(Cf)` and
  read by `d_-` is a nest of basic operators `D_n` (one `D` for each `z` and one for the final
  `d_-`), by `HJO.Sweep.exists_forall_dminus_auxVar_pow_mul_vertexStep_pow_eq_chain`; the shear
  raises every index of that nest by one, so the nest of `(a,b+a)` is `(-1)^a` times the
  index-raised nest of `(a,b)`, which `τ^*τ` transports from the nest of `(a,b)` exactly as it
  transports `Q`.

The two transports are compared degree by degree in the completion `Λ̂`, where the clause at
`(a,b)` applies to each graded component, and `τ^*τ` is injective (`HJO.Sym.nsShiftComp_injective`).

## Main definitions

* `HJO.Mellit.shiftWord`: the shear `S` on a word written in the order its letters act.
* `HJO.Sweep.lhsNest`: the nest of basic operators a word produces on `Λ`, with indices offset.

## Main results

* `HJO.Sym.nsTransports_qop_add_self`: `Q_{a,b}` transports `(-1)^aQ_{a,b+a}` along `τ^*τ`.
* `HJO.Mellit.slopeWord_add_self`: `β_{a,b+a} = 𝗒·β_{a,b}[𝗓 ↦ 𝗓𝗒]`.
* `HJO.Sweep.exists_forall_dminus_sweepWordOp`: the sweep side of a word is its nest.
* `HJO.Sweep.nsTransports_lhsNest`: a nest transports its index-raised copy along `τ^*τ`.
* `HJO.Sweep.lhsSlope_add_self`: `LhsSlope q u a b → LhsSlope q u a (b + a)`.
* `HJO.Sweep.lhsSlope_mul_add_one`: the clause at every slope `(a, ka+1)`, at every `f`.
* `HJO.Sweep.lhsSlope_of_lt`: the clause at every positive coprime slope follows from its
  instances strictly below the diagonal.
* `HJO.Sweep.lhsAt_singleton_one_mul_add_one`: the base case of
  `HJO.Mellit.lhsRewrite_sweepWitness`, the composition `(1)`, at every slope `(a, ka+1)` and every
  slope homomorphism.

## Implementation notes

The nest is truncated: each `z` contributes `∑_{l ≤ R}`, and the sweep side equals the nest only
for `R` large in terms of the argument. A fixed truncation therefore cannot be extended to `Λ̂`,
whose components have unbounded degree; the comparison is made one component at a time, with a
truncation chosen for that component, the value of the nest at the original argument being
independent of the truncation once it is large enough.

The clause is the bottom action of a *primitive* slope on a general `f`. It is not
`HJO.Mellit.lhsRewrite_sweepWitness` itself: that needs `Θ` on the generators `Q_{ak,bk}` of every
multiplicity and every composition `α`, and `HJO.Mellit.qop_double_apply_one_of_lhsWord` shows
already at `α = (1,1)` that the non-primitive `Q_{2a,2b}` enters. The `N` half of Section 3.7, which
reaches the slopes below the diagonal, is not treated here.

## References

* [A. Mellit, *Toric braids and (m,n)-parking functions*][mellit2016], §3.7.
-/

@[expose] public section

namespace HJO.Mellit

/-! ### Stern–Brocot induction on coprime pairs -/

/-- **Induction over the Stern–Brocot tree.** A property of positive coprime pairs holding on the
two boundary rays `(1,n)` and `(m,1)`, and passing from two Stern–Brocot neighbours
(`m₂n₁ = m₁n₂ + 1`) to their mediant, holds at every positive coprime pair. -/
theorem coprime_induction {P : ℕ → ℕ → Prop}
    (h1 : ∀ n, 1 ≤ n → P 1 n) (h2 : ∀ m, 1 ≤ m → P m 1)
    (hmed : ∀ m₁ n₁ m₂ n₂ : ℕ, 1 ≤ m₁ → 1 ≤ n₁ → 1 ≤ m₂ → 1 ≤ n₂ → m₂ * n₁ = m₁ * n₂ + 1 →
      Nat.Coprime m₁ n₁ → Nat.Coprime m₂ n₂ → P m₁ n₁ → P m₂ n₂ → P (m₁ + m₂) (n₁ + n₂)) :
    ∀ m n, Nat.Coprime m n → 1 ≤ m → 1 ≤ n → P m n := by
  intro m n
  induction h : m + n using Nat.strong_induction_on generalizing m n with
  | _ N ih =>
    intro hc hm hn
    rcases Nat.lt_or_ge m 2 with hm2 | hm2
    · obtain rfl : m = 1 := by omega
      exact h1 n hn
    rcases Nat.lt_or_ge n 2 with hn2 | hn2
    · obtain rfl : n = 1 := by omega
      exact h2 m hm
    obtain ⟨m₁, n₁, hp⟩ := exists_isSBParent hc hm hn
    obtain ⟨hm₁, hn₁, hm₁lt, hn₁lt⟩ := isSBParent_pos hm2 hn2 hp
    obtain ⟨hc₁, hc₂⟩ := isSBParent_coprime hp
    have hdet := isSBParent_det hp
    have key := hmed m₁ n₁ (m - m₁) (n - n₁) hm₁ hn₁ (by omega) (by omega) hdet hc₁ hc₂
      (ih (m₁ + n₁) (by omega) m₁ n₁ rfl hc₁ hm₁ hn₁)
      (ih (m - m₁ + (n - n₁)) (by omega) _ _ rfl hc₂ (by omega) (by omega))
    rwa [Nat.add_sub_cancel' (by omega), Nat.add_sub_cancel' (by omega)] at key

/-! ### Letter counts -/

/-- The slope word `β_{m,n}` has `n - 1` letters `𝗒` and `m - 1` letters `𝗓`. -/
theorem count_slopeWord {m n : ℕ} (hc : Nat.Coprime m n) (hm : 1 ≤ m) (hn : 1 ≤ n) :
    (slopeWord m n).count .y = n - 1 ∧ (slopeWord m n).count .z = m - 1 := by
  refine coprime_induction (P := fun m n =>
    (slopeWord m n).count .y = n - 1 ∧ (slopeWord m n).count .z = m - 1) ?_ ?_ ?_ m n hc hm hn
  · intro n hn
    rw [slopeWord_one_left hn]
    simp [List.count_replicate]
  · intro m hm
    rw [slopeWord_one_right hm]
    simp [List.count_replicate]
  · intro m₁ n₁ m₂ n₂ hm₁ hn₁ hm₂ hn₂ hdet hc₁ hc₂ ih₁ ih₂
    rw [(slopeWord_mediant hm₁ hn₁ hm₂ hn₂ hdet hc₁ hc₂).2]
    simp only [List.count_append, List.count_cons, ih₁.1, ih₁.2, ih₂.1, ih₂.2]
    simp
    omega

/-! ### The slope word of `(m, n + m)` -/

/-- The letter substitution by which the slope word of `(m, n+m)` is read off that of `(m, n)`,
in the order in which the slope word is written. -/
def shiftSubst : SlopeLetter → List SlopeLetter
  | .y => [.y]
  | .z => [.z, .y]

/-- A run of `𝗒` is fixed by the substitution. -/
theorem flatMap_shiftSubst_replicate_y (k : ℕ) :
    (List.replicate k SlopeLetter.y).flatMap shiftSubst = List.replicate k .y := by
  induction k with
  | zero => rfl
  | succ k ih => rw [List.replicate_succ, List.flatMap_cons, ih]; rfl

/-- **The shear `S` on slope words**: `β_{m,n+m} = 𝗒·β_{m,n}[𝗓 ↦ 𝗓𝗒]`, by Stern–Brocot induction
from `HJO.Mellit.slopeWord_mediant`; the two parents of `(m, n+m)` are the shears of the two
parents of `(m,n)`. -/
theorem slopeWord_add_self {m n : ℕ} (hc : Nat.Coprime m n) (hm : 1 ≤ m) (hn : 1 ≤ n) :
    slopeWord m (n + m) = .y :: (slopeWord m n).flatMap shiftSubst := by
  refine coprime_induction (P := fun m n =>
    slopeWord m (n + m) = .y :: (slopeWord m n).flatMap shiftSubst) ?_ ?_ ?_ m n hc hm hn
  · intro n hn
    rw [slopeWord_one_left hn, slopeWord_one_left (by omega), flatMap_shiftSubst_replicate_y,
      show n + 1 - 1 = (n - 1) + 1 by omega, List.replicate_succ]
  · intro m hm
    induction m with
    | zero => omega
    | succ k ih =>
      rcases Nat.eq_zero_or_pos k with rfl | hk
      · rw [slopeWord_one_right le_rfl, slopeWord_one_left (by omega)]
        rfl
      · have hmed := (slopeWord_mediant (m₁ := k) (n₁ := k + 1) (m₂ := 1) (n₂ := 1) hk
          (by omega) le_rfl le_rfl (by ring)
          (Nat.coprime_self_add_right.2 (Nat.coprime_one_right _))
          (Nat.coprime_one_left _)).2
        rw [show 1 + (k + 1) = k + 1 + 1 by ring, hmed, show slopeWord 1 1 = [] from rfl,
          show k + 1 = 1 + k by ring, ih hk, slopeWord_one_right hk,
          slopeWord_one_right (by omega), show 1 + k - 1 = (k - 1) + 1 by omega,
          List.replicate_succ, List.flatMap_cons]
        rfl
  · intro m₁ n₁ m₂ n₂ hm₁ hn₁ hm₂ hn₂ hdet hc₁ hc₂ ih₁ ih₂
    have hdet' : m₂ * (n₁ + m₁) = m₁ * (n₂ + m₂) + 1 := by
      rw [mul_add, mul_add]; linarith [Nat.mul_comm m₁ m₂]
    have hmed := (slopeWord_mediant hm₁ (by omega : 1 ≤ n₁ + m₁) hm₂ (by omega : 1 ≤ n₂ + m₂)
      hdet' (Nat.coprime_add_self_right.2 hc₁) (Nat.coprime_add_self_right.2 hc₂)).2
    rw [show n₁ + n₂ + (m₁ + m₂) = (n₁ + m₁) + (n₂ + m₂) by ring, hmed, ih₁, ih₂,
      (slopeWord_mediant hm₁ hn₁ hm₂ hn₂ hdet hc₁ hc₂).2]
    simp [List.flatMap_append, shiftSubst]

/-- The same substitution in the order in which the letters act: each `z` is preceded by one `y`
and one further `y` is applied last. -/
def shiftWord (t : List SlopeLetter) : List SlopeLetter :=
  t.flatMap (fun l => match l with
    | .y => [.y]
    | .z => [.y, .z]) ++ [.y]

@[simp] theorem shiftWord_nil : shiftWord [] = [.y] := rfl

/-- The shear `S` fixes a leading `y`. -/
@[simp] theorem shiftWord_cons_y (t : List SlopeLetter) :
    shiftWord (.y :: t) = .y :: shiftWord t := rfl

/-- The shear `S` replaces a leading `z` by `y z`. -/
@[simp] theorem shiftWord_cons_z (t : List SlopeLetter) :
    shiftWord (.z :: t) = .y :: .z :: shiftWord t := rfl

/-- `HJO.Mellit.slopeWord_add_self` read in the order in which the letters act. -/
theorem reverse_slopeWord_add_self {m n : ℕ} (hc : Nat.Coprime m n) (hm : 1 ≤ m) (hn : 1 ≤ n) :
    (slopeWord m (n + m)).reverse = shiftWord (slopeWord m n).reverse := by
  rw [slopeWord_add_self hc hm hn]
  generalize slopeWord m n = w
  induction w with
  | nil => rfl
  | cons x w ih =>
    rw [List.flatMap_cons, List.reverse_cons, List.reverse_append] at *
    rw [List.reverse_cons, shiftWord, List.flatMap_append]
    rw [shiftWord] at ih
    cases x <;> simp_all [shiftSubst]

end HJO.Mellit

namespace HJO.Sym

variable {L : Type*} [Field L] [Algebra ℚ L]

omit [Algebra ℚ L] in
/-- `neg_one_smul` at the operators on `Λ`, in a form `rw` can match. -/
theorem neg_one_smul_end (X : Module.End L (Lambda L)) : (-1 : L) • X = -X := neg_one_smul L X

/-- **The split of `(m, n+m)` is the split of `(m,n)` moved by the same shear**: if
`(r,s) = Split m n` then `Split m (n+m) = (r, s+r)`, because `ms + 1 = nr` gives
`m(s+r) + 1 = (n+m)r`. -/
theorem split_add_self {m n : ℕ} (hm : 1 < m) (hc : Nat.Coprime m n) :
    Split m (n + m) = ((Split m n).1, (Split m n).2 + (Split m n).1) := by
  obtain ⟨h1, h2, h3, h4⟩ := split_spec hm hc
  exact split_eq_of_spec (by omega) (Nat.coprime_add_self_right.2 hc) h1 h2 (by omega) (by omega)
    (by rw [mul_add, add_mul]; linarith)

/-- Both halves of the split of a coprime pair are coprime. -/
theorem coprime_split {m n : ℕ} (hm : 1 < m) (hc : Nat.Coprime m n) :
    Nat.Coprime (Split m n).1 (Split m n).2 ∧
      Nat.Coprime (m - (Split m n).1) (n - (Split m n).2) := by
  obtain ⟨h1, h2, h3, h4⟩ := split_spec hm hc
  set r := (Split m n).1
  set s := (Split m n).2
  refine ⟨?_, ?_⟩
  · have hd : Nat.gcd r s ∣ n * r - m * s :=
      Nat.dvd_sub ((Nat.gcd_dvd_left r s).mul_left n) ((Nat.gcd_dvd_right r s).mul_left m)
    rw [show n * r - m * s = 1 by omega] at hd
    exact Nat.eq_one_of_dvd_one hd
  · have key : r * (n - s) = s * (m - r) + 1 := by
      zify [h3.le, h2.le]
      have h4' : (m : ℤ) * s + 1 = n * r := by exact_mod_cast h4
      linarith
    have hd : Nat.gcd (m - r) (n - s) ∣ r * (n - s) - s * (m - r) :=
      Nat.dvd_sub ((Nat.gcd_dvd_right _ _).mul_left r) ((Nat.gcd_dvd_left _ _).mul_left s)
    rw [show r * (n - s) - s * (m - r) = 1 by omega] at hd
    exact Nat.eq_one_of_dvd_one hd

/-- `HJO.Sym.Qop`'s recursion at a coprime pair, with both halves read through `Qop`. -/
theorem qop_eq_of_one_lt (q u : L) {m n : ℕ} (hm : 1 < m) (hc : Nat.Coprime m n) :
    Qop q u m n = ((1 - q) * (1 - u))⁻¹ •
      (Qop q u (m - (Split m n).1) (n - (Split m n).2) * Qop q u (Split m n).1 (Split m n).2 -
        Qop q u (Split m n).1 (Split m n).2 * Qop q u (m - (Split m n).1) (n - (Split m n).2)) := by
  obtain ⟨hc₁, hc₂⟩ := coprime_split hm hc
  rw [qop_eq_qopPrim q u hc, qopPrim_of_one_lt q u n hm, qop_eq_qopPrim q u hc₁,
    qop_eq_qopPrim q u hc₂]

/-- **Mellit's `S` on the slope operators.** For a positive coprime pair `(m,n)`, the operator
`Q_{m,n}` transports `(-1)^m Q_{m,n+m}` along `τ^*τ`:
`τ^*τ((-1)^mQ_{m,n+m}f) = Q̂_{m,n}(τ^*τf)`.

This is the action of the matrix `S = (1 0; 1 1)` of Mellit's Section 3.7 on the slope operators of
`HJO.Sym.Qop`, with the sign `(-1)^m` of `HJO.Dyck.Tilde.rel_biHomogeneous`. The base case `m = 1`
is `HJO.Sym.nsShiftComp_comp_dopInt`; the induction runs through `HJO.Sym.Qop`'s commutator
recursion, which `S` preserves because it carries the split of `(m,n)` to the split of `(m, n+m)`
(`HJO.Sym.split_add_self`) and is multiplicative (`HJO.Sym.nsShiftComp_mul`). -/
theorem nsTransports_qop_add_self (q u : L)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) :
    ∀ m n : ℕ, Nat.Coprime m n → 1 ≤ m →
      NsTransports q u (qop_shiftsDegree q u m n) ((-1 : L) ^ m • Qop q u m (n + m)) := by
  intro m
  induction m using Nat.strong_induction_on with
  | _ m ih =>
    intro n hc hm
    rcases Nat.lt_or_ge m 2 with hm2 | hm2
    · obtain rfl : m = 1 := by omega
      refine NsTransports.congr rfl (by rw [qop_one, dopInt_natCast]) ?_
        (nsTransports_dopInt q u hM (n : ℤ))
      rw [qop_one, pow_one, Sym.neg_one_smul_end, ← dopInt_natCast]
      push_cast
      rfl
    obtain ⟨h1, h2, h3, h4⟩ := split_spec hm2 hc
    obtain ⟨hc₁, hc₂⟩ := coprime_split hm2 hc
    set r := (Split m n).1 with hr
    set s := (Split m n).2 with hs
    set A := Qop q u (m - r) (n - s)
    set B := Qop q u r s
    set A' := (-1 : L) ^ (m - r) • Qop q u (m - r) (n - s + (m - r))
    set B' := (-1 : L) ^ r • Qop q u r (s + r)
    have T1 : NsTransports q u (qop_shiftsDegree q u (m - r) (n - s)) A' :=
      ih (m - r) (by omega) (n - s) hc₂ (by omega)
    have T2 : NsTransports q u (qop_shiftsDegree q u r s) B' := ih r h2 s hc₁ h1
    have hAB : ShiftsDegree (n : ℤ) (A * B) := by
      have h := (qop_shiftsDegree q u (m - r) (n - s)).comp (qop_shiftsDegree q u r s)
      rwa [show ((n - s : ℕ) : ℤ) + (s : ℤ) = n by omega] at h
    have hBA0 : ShiftsDegree (n : ℤ) (B * A) := by
      have h := (qop_shiftsDegree q u r s).comp (qop_shiftsDegree q u (m - r) (n - s))
      rwa [show (s : ℤ) + ((n - s : ℕ) : ℤ) = n by omega] at h
    have hBA : ShiftsDegree (n : ℤ) ((-1 : L) • (B * A)) :=
      Submodule.smul_mem (degreeShifting L n) (-1 : L) hBA0
    have hsum : ShiftsDegree (n : ℤ) (A * B + (-1 : L) • (B * A)) :=
      Submodule.add_mem (degreeShifting L n) hAB hBA
    have hsm : ShiftsDegree (n : ℤ)
        (((1 - q) * (1 - u))⁻¹ • (A * B + (-1 : L) • (B * A))) :=
      Submodule.smul_mem (degreeShifting L n) _ hsum
    have TAB : NsTransports q u hAB (A' * B') := NsTransports.congr (by omega) rfl rfl (T1.mul T2)
    have TBA0 : NsTransports q u hBA0 (B' * A') := NsTransports.congr (by omega) rfl rfl (T2.mul T1)
    have Tsm : NsTransports q u hsm
        (((1 - q) * (1 - u))⁻¹ • (A' * B' + (-1 : L) • (B' * A'))) :=
      (TAB.add (hsum := hsum) (TBA0.smul (hrD := hBA) (-1 : L))).smul _
    refine NsTransports.congr rfl ?_ ?_ Tsm
    · rw [qop_eq_of_one_lt q u hm2 hc, Sym.neg_one_smul_end, ← sub_eq_add_neg]
    · rw [qop_eq_of_one_lt q u hm2 (Nat.coprime_add_self_right.2 hc), split_add_self hm2 hc,
        Sym.neg_one_smul_end, ← sub_eq_add_neg, smul_comm, ← hr, ← hs,
        show n + m - (s + r) = n - s + (m - r) by omega]
      simp only [A', B', smul_mul_smul_comm, smul_sub, smul_smul, ← pow_add,
        show m - r + r = m by omega, show r + (m - r) = m by omega]

end HJO.Sym

namespace HJO.Sym

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- Transport passes to finite sums at a fixed degree. -/
theorem nsTransports_sum (q u : L) {ι : Type*} (s : Finset ι) {c : ℤ}
    (D E : ι → Module.End L (Lambda L)) (hD : ∀ i, ShiftsDegree c (D i))
    (hT : ∀ i, NsTransports q u (hD i) (E i)) (h : ShiftsDegree c (∑ i ∈ s, D i)) :
    NsTransports q u h (∑ i ∈ s, E i) := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    exact NsTransports.congr rfl (Finset.sum_empty).symm (Finset.sum_empty).symm
      (nsTransports_zero q u (zero_mem (degreeShifting L c)))
  | @insert a s ha ih =>
    have hs : ShiftsDegree c (∑ i ∈ s, D i) :=
      Submodule.sum_mem (degreeShifting L c) fun i _ => hD i
    have hadd : ShiftsDegree c (D a + ∑ i ∈ s, D i) :=
      Submodule.add_mem (degreeShifting L c) (hD a) hs
    exact NsTransports.congr rfl (Finset.sum_insert ha).symm (Finset.sum_insert ha).symm
      ((hT a).add (hsum := hadd) (ih hs))

end HJO.Sym

namespace HJO.Sweep

open Mellit (SlopeLetter)

variable {L : Type*} [Field L] [Algebra ℚ L] {q u : L}

/-! ### The slope operator as a word read in the order its letters act -/

/-- The operator `HJO.Sweep.slopeOperator` substitutes for a letter at `k = 1`. -/
noncomputable def sweepLetter (q u : L) : SlopeLetter → Module.End L (Total L)
  | .y => -LinearMap.mulLeft L (auxVar 1 : Total L)
  | .z => (q * u)⁻¹ • zop q u 1 1

/-- A word in the two letters, read in the order in which its letters **act**: the head acts
first. -/
noncomputable def sweepWordOp (q u : L) (t : List SlopeLetter) : Module.End L (Total L) :=
  ((t.map (sweepLetter q u)).reverse).prod

/-- The empty word acts as the identity. -/
theorem sweepWordOp_nil (q u : L) : sweepWordOp q u [] = 1 := rfl

/-- The head letter of a word acts first. -/
theorem sweepWordOp_cons (q u : L) (x : SlopeLetter) (t : List SlopeLetter) :
    sweepWordOp q u (x :: t) = sweepWordOp q u t * sweepLetter q u x := by
  simp [sweepWordOp, List.prod_append]

/-- The slope operator at `k = 1` is its slope word read backwards. -/
theorem slopeOperator_eq_sweepWordOp (q u : L) (a b : ℕ) :
    slopeOperator q u 1 a b = sweepWordOp q u (Mellit.slopeWord a b).reverse := by
  rw [sweepWordOp, List.map_reverse, List.reverse_reverse, slopeOperator]
  congr 2

/-! ### The nest of basic operators a word produces -/

/-- **The nest of basic operators produced by a word**, with every index offset by `e`.

A vector `y_1^m d^*_+(Cg)` of `V_1` is the pair `(m, g)`. The letter `y` sends it to
`-(m+1, g)`; the letter `z` sends it to `∑_l (qu)^l (l+1, D_{m-1-l}g)` (one `y_1` passing the
letter by `zLetter_auxVar_mul`, then
`HJO.Sweep.exists_forall_dminus_auxVar_pow_mul_vertexStep_pow_eq_chain`); and the final `d_-` reads
`(m, g)` as `D_m g`. `lhsNest q u 0 R t m` is the resulting operator on `Λ`, every sum truncated at
`R`; `lhsNest q u e R t m` is the same nest with each index raised by `e`. -/
noncomputable def lhsNest (q u : L) (e : ℤ) (R : ℕ) :
    List SlopeLetter → ℕ → Module.End L (Sym.Lambda L)
  | [], m => Sym.DopInt q u ((m : ℤ) + e)
  | .y :: t, m => -lhsNest q u e R t (m + 1)
  | .z :: t, m => ∑ l ∈ Finset.range (R + 1),
      ((q * u) ^ l) • (lhsNest q u e R t (l + 1) * Sym.DopInt q u ((m : ℤ) - 1 - (l : ℤ) + e))

/-- **The sweep side of a word is its nest**, for every large enough truncation. -/
theorem exists_forall_dminus_sweepWordOp (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) :
    ∀ (t : List SlopeLetter) (m : ℕ) (g : Sym.Lambda L), 1 ≤ m → ∃ R₀ : ℕ, ∀ R : ℕ, R₀ ≤ R →
      dminus q 1 (sweepWordOp q u t
          ((auxVar 1 : Total L) ^ m * dplusStar q u 0 (MvPolynomial.C g : Total L)))
        = MvPolynomial.C (lhsNest q u 0 R t m g) := by
  intro t
  induction t with
  | nil =>
    intro m g _
    refine ⟨0, fun R _ => ?_⟩
    rw [sweepWordOp_nil, Module.End.one_apply, dminus_auxVar_pow_mul_dplusStar_C, lhsNest,
      add_zero, Sym.dopInt_natCast]
  | cons x t ih =>
    intro m g hm
    cases x with
    | y =>
      obtain ⟨R₀, hR₀⟩ := ih (m + 1) g (by omega)
      refine ⟨R₀, fun R hR => ?_⟩
      rw [sweepWordOp_cons, Module.End.mul_apply, sweepLetter, LinearMap.neg_apply,
        LinearMap.mulLeft_apply, map_neg, map_neg, ← mul_assoc, ← pow_succ', hR₀ R hR, lhsNest,
        LinearMap.neg_apply, map_neg]
    | z =>
      classical
      set N := (Sym.plethShift q u g).natDegree with hN
      obtain ⟨R₁, hR₁⟩ := exists_forall_bopExt_dplusStar_coeff_eq_zero q u (m - 1)
        (dplusStar q u 0 (MvPolynomial.C g : Total L))
      choose S hS using fun l : ℕ =>
        ih (l + 1) (Sym.DopInt q u (((m - 1 : ℕ) : ℤ) - (l : ℤ)) g) (by omega)
      refine ⟨max R₁ ((Finset.range (m + N + 1)).sup S), fun R hR => ?_⟩
      have hvan : ∀ l : ℕ, m + N < l → Sym.DopInt q u (((m - 1 : ℕ) : ℤ) - (l : ℤ)) g = 0 :=
        fun l hl => Sym.dopInt_eq_zero_of_lt q u g (by rw [← hN]; omega)
      have hmem : (auxVar 1 : Total L) ^ (m - 1) * dplusStar q u 0 (MvPolynomial.C g : Total L)
          ∈ piece L 1 :=
        Subalgebra.mul_mem _ (pow_mem (auxVar_mem_piece le_rfl le_rfl) _)
          (dplusStar_zero_C_mem_piece_one q u g)
      have hsplit : (auxVar 1 : Total L) ^ m * dplusStar q u 0 (MvPolynomial.C g : Total L)
          = (auxVar 1 : Total L) * ((auxVar 1 : Total L) ^ (m - 1)
              * dplusStar q u 0 (MvPolynomial.C g : Total L)) := by
        rw [← mul_assoc, ← pow_succ', Nat.sub_add_cancel hm]
      rw [sweepWordOp_cons, Module.End.mul_apply, hsplit, sweepLetter,
        zLetter_auxVar_mul hq0 hu0 hq1 hmem,
        vertexStep_auxVar_pow_mul_dplusStar_C_eq_sum hq1 (m - 1) R g
          (hR₁ R (le_trans (le_max_left _ _) hR)),
        Finset.mul_sum, map_sum, map_sum, lhsNest, LinearMap.sum_apply, map_sum]
      refine Finset.sum_congr rfl fun l _ => ?_
      rw [mul_smul_comm, map_smul, map_smul, ← mul_assoc, ← pow_succ', LinearMap.smul_apply,
        Module.End.mul_apply, C_smul,
        show (m : ℤ) - 1 - (l : ℤ) + 0 = ((m - 1 : ℕ) : ℤ) - (l : ℤ) by omega]
      refine congrArg (fun x => ((q * u) ^ l) • x) ?_
      rcases le_or_gt l (m + N) with hl | hl
      · exact hS l R (le_trans (le_trans (Finset.le_sup (f := S)
          (Finset.mem_range.2 (by omega))) (le_max_right _ _)) hR)
      · rw [hvan l hl]
        simp

/-- **The shear on words becomes the index shift on nests.** Inserting a `y` before every `z` and
one at the end raises every index of the nest by one, at the cost of one sign per letter of the
nest. -/
theorem lhsNest_shiftWord (q u : L) (e : ℤ) (R : ℕ) :
    ∀ (t : List SlopeLetter) (m : ℕ),
      lhsNest q u e R (Mellit.shiftWord t) m
        = (-1 : L) ^ (t.count .z + 1) • lhsNest q u (e + 1) R t m := by
  intro t
  induction t with
  | nil =>
    intro m
    rw [Mellit.shiftWord_nil, lhsNest, lhsNest, lhsNest, List.count_nil, zero_add, pow_one,
      Sym.neg_one_smul_end]
    congr 2
    push_cast
    ring
  | cons x t ih =>
    intro m
    cases x with
    | y =>
      rw [Mellit.shiftWord_cons_y, lhsNest, ih, lhsNest, smul_neg,
        List.count_cons_of_ne (by decide)]
    | z =>
      rw [Mellit.shiftWord_cons_z, lhsNest, lhsNest, lhsNest, List.count_cons_self,
        Finset.smul_sum, ← Finset.sum_neg_distrib]
      refine Finset.sum_congr rfl fun l _ => ?_
      rw [ih, smul_mul_assoc, smul_comm, pow_succ, mul_smul, Sym.neg_one_smul_end,
        show ((m + 1 : ℕ) : ℤ) - 1 - (l : ℤ) + e = (m : ℤ) - 1 - (l : ℤ) + (e + 1) by
          push_cast; ring]
      simp only [smul_neg, neg_neg]
      rw [show ((-1 : L)) ^ (t.count .z + 1 + 1) = (-1) ^ t.count .z by ring]

/-- The degree by which a nest shifts, beyond its starting index. -/
def nestDegree (e : ℤ) (t : List SlopeLetter) : ℤ := (t.count .y : ℤ) + e * ((t.count .z : ℤ) + 1)

/-- The empty word has nest degree `e`. -/
@[simp] theorem nestDegree_nil (e : ℤ) : nestDegree e [] = e := by simp [nestDegree]

/-- A leading `y` raises the nest degree by one. -/
@[simp] theorem nestDegree_cons_y (e : ℤ) (t : List SlopeLetter) :
    nestDegree e (.y :: t) = nestDegree e t + 1 := by
  simp [nestDegree]; ring

/-- A leading `z` raises the nest degree by `e`. -/
@[simp] theorem nestDegree_cons_z (e : ℤ) (t : List SlopeLetter) :
    nestDegree e (.z :: t) = nestDegree e t + e := by
  simp [nestDegree]; ring

/-- The nest `lhsNest q u e R t m` shifts degree by `m + nestDegree e t`: each `𝗒` adds one, and
each letter of the nest adds the offset `e`. -/
theorem lhsNest_shiftsDegree (q u : L) (e : ℤ) (R : ℕ) :
    ∀ (t : List SlopeLetter) (m : ℕ),
      Sym.ShiftsDegree ((m : ℤ) + nestDegree e t) (lhsNest q u e R t m) := by
  intro t
  induction t with
  | nil =>
    intro m
    rw [lhsNest, nestDegree_nil]
    exact Sym.dopInt_shiftsDegree q u _
  | cons x t ih =>
    intro m
    cases x with
    | y =>
      rw [lhsNest]
      have h := Submodule.neg_mem (Sym.degreeShifting L _) (ih (m + 1))
      rwa [show ((m + 1 : ℕ) : ℤ) + nestDegree e t = (m : ℤ) + nestDegree e (.y :: t) by
        simp only [nestDegree_cons_y]; push_cast; ring] at h
    | z =>
      rw [lhsNest]
      refine Submodule.sum_mem (Sym.degreeShifting L _) fun l _ => ?_
      refine Submodule.smul_mem (Sym.degreeShifting L _) _ ?_
      have h := (ih (l + 1)).comp (Sym.dopInt_shiftsDegree q u ((m : ℤ) - 1 - (l : ℤ) + e))
      rwa [show ((l + 1 : ℕ) : ℤ) + nestDegree e t + ((m : ℤ) - 1 - (l : ℤ) + e)
          = (m : ℤ) + nestDegree e (.z :: t) by
        simp only [nestDegree_cons_z]; push_cast; ring] at h

/-- **Mellit's `S` on the nests.** Every nest transports its index-raised copy, with one sign per
letter: `τ^*τ((-1)^{#z+1} nest_{e+1}) = nest_e^ τ^*τ`. Induction on the word, the letter case
being `HJO.Sym.nsShiftComp_comp_dopInt` and the induction step `HJO.Sym.nsShiftComp_mul`. -/
theorem nsTransports_lhsNest (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    (e : ℤ) (R : ℕ) :
    ∀ (t : List SlopeLetter) (m : ℕ) (h : Sym.ShiftsDegree ((m : ℤ) + nestDegree e t)
      (lhsNest q u e R t m)),
      Sym.NsTransports q u h ((-1 : L) ^ (t.count .z + 1) • lhsNest q u (e + 1) R t m) := by
  intro t
  induction t with
  | nil =>
    intro m h
    refine Sym.NsTransports.congr (by simp) rfl ?_
      (Sym.nsTransports_dopInt q u hM ((m : ℤ) + e))
    rw [lhsNest, List.count_nil, zero_add, pow_one, Sym.neg_one_smul_end]
    congr 2
    ring
  | cons x t ih =>
    intro m h
    cases x with
    | y =>
      have h' := ih (m + 1) (lhsNest_shiftsDegree q u e R t (m + 1))
      have hs : Sym.ShiftsDegree (((m + 1 : ℕ) : ℤ) + nestDegree e t)
          ((-1 : L) • lhsNest q u e R t (m + 1)) :=
        Submodule.smul_mem (Sym.degreeShifting L _) (-1 : L)
          (lhsNest_shiftsDegree q u e R t (m + 1))
      refine Sym.NsTransports.congr ?_ ?_ ?_ (h'.smul (hrD := hs) (-1 : L))
      · simp only [nestDegree_cons_y]; push_cast; ring
      · rw [lhsNest, Sym.neg_one_smul_end]
      · rw [lhsNest, List.count_cons_of_ne (by decide), Sym.neg_one_smul_end, smul_neg]
    | z =>
      set c : ℤ := (m : ℤ) + nestDegree e (.z :: t)
      have hterm : ∀ l : ℕ, Sym.ShiftsDegree c ((q * u) ^ l •
          (lhsNest q u e R t (l + 1) * Sym.DopInt q u ((m : ℤ) - 1 - (l : ℤ) + e))) := by
        intro l
        refine Submodule.smul_mem (Sym.degreeShifting L _) _ ?_
        have h := (lhsNest_shiftsDegree q u e R t (l + 1)).comp
          (Sym.dopInt_shiftsDegree q u ((m : ℤ) - 1 - (l : ℤ) + e))
        rwa [show ((l + 1 : ℕ) : ℤ) + nestDegree e t + ((m : ℤ) - 1 - (l : ℤ) + e) = c by
          simp only [c, nestDegree_cons_z]; push_cast; ring] at h
      have hT : ∀ l : ℕ, Sym.NsTransports q u (hterm l) ((q * u) ^ l •
          (((-1 : L) ^ (t.count .z + 1) • lhsNest q u (e + 1) R t (l + 1))
            * -(Sym.DopInt q u ((m : ℤ) - 1 - (l : ℤ) + e + 1)))) := by
        intro l
        have hmul := (ih (l + 1) (lhsNest_shiftsDegree q u e R t (l + 1))).mul
          (Sym.nsTransports_dopInt q u hM ((m : ℤ) - 1 - (l : ℤ) + e))
        have hc : Sym.ShiftsDegree c
            (lhsNest q u e R t (l + 1) * Sym.DopInt q u ((m : ℤ) - 1 - (l : ℤ) + e)) := by
          have h := (lhsNest_shiftsDegree q u e R t (l + 1)).comp
            (Sym.dopInt_shiftsDegree q u ((m : ℤ) - 1 - (l : ℤ) + e))
          rwa [show ((l + 1 : ℕ) : ℤ) + nestDegree e t + ((m : ℤ) - 1 - (l : ℤ) + e) = c by
            simp only [c, nestDegree_cons_z]; push_cast; ring] at h
        exact (Sym.NsTransports.congr (hD' := hc) (by
          simp only [c, nestDegree_cons_z]; push_cast; ring) rfl rfl hmul).smul _
      have hsum := Sym.nsTransports_sum q u (Finset.range (R + 1)) _ _ hterm hT
        (by rw [← lhsNest]; exact h)
      refine Sym.NsTransports.congr rfl (by rw [lhsNest]) ?_ hsum
      rw [lhsNest, List.count_cons_self, Finset.smul_sum]
      refine Finset.sum_congr rfl fun l _ => ?_
      rw [show (m : ℤ) - 1 - (l : ℤ) + e + 1 = (m : ℤ) - 1 - (l : ℤ) + (e + 1) by ring]
      refine LinearMap.ext fun f => ?_
      simp only [LinearMap.smul_apply, Module.End.mul_apply, LinearMap.neg_apply, map_neg]
      module

/-! ### The clause carried along `S` -/

/-- **The clause of `HJO.Mellit.LhsSlope` at `(a,b)`, read in the nest of its slope word.** -/
theorem exists_forall_smul_qop_eq_lhsNest (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) {a b : ℕ}
    (h : Mellit.LhsSlope q u a b) (g : Sym.Lambda L) :
    ∃ R₀ : ℕ, ∀ R : ℕ, R₀ ≤ R →
      (-1 : L) ^ (b + 1) • Sym.Qop q u a b g
        = lhsNest q u 0 R (Mellit.slopeWord a b).reverse 1 g := by
  obtain ⟨R₀, hR₀⟩ :=
    exists_forall_dminus_sweepWordOp hq0 hu0 hq1 (Mellit.slopeWord a b).reverse 1 g le_rfl
  refine ⟨R₀, fun R hR => MvPolynomial.C_injective ℕ (Sym.Lambda L) ?_⟩
  have harg : Mellit.slopeArg q u g
      = (auxVar 1 : Total L) ^ 1 * dplusStar q u 0 (MvPolynomial.C g : Total L) := by
    rw [Mellit.slopeArg_def, pow_one]
  rw [C_smul, h g, slopeOperator_eq_sweepWordOp, harg, hR₀ R hR, smul_smul, ← pow_add,
    show b + 1 + (b + 1) = 2 * (b + 1) by ring, pow_mul, neg_one_sq, one_pow, one_smul]

/-- **The clause of `HJO.Mellit.lhsRewrite_sweepWitness`'s base case is carried along Mellit's
`S`:** the clause `HJO.Mellit.LhsSlope` at a positive coprime pair `(a,b)` implies it at `(a, b+a)`.

This is the compatibility of the two sides of the clause with the matrix `S = (1 0; 1 1)` of
Mellit's Section 3.7. On the `Λ` side `S` carries `Q_{a,b}` to `(-1)^aQ_{a,b+a}` along `τ^*τ`
(`HJO.Sym.nsTransports_qop_add_self`). On the sweep side `S` is the shear of the slope word
`β_{a,b+a} = 𝗒·β_{a,b}[𝗓 ↦ 𝗓𝗒]` (`HJO.Mellit.slopeWord_add_self`), which raises every index of the
nest of basic operators the word produces by one (`HJO.Sweep.lhsNest_shiftWord`), and the nest
carries its raised copy along `τ^*τ` with the same sign (`HJO.Sweep.nsTransports_lhsNest`). The two
transported operators are then compared degree by degree in the completion, and `τ^*τ` is injective
(`HJO.Sym.nsShiftComp_injective`).

`hM` is the nondegeneracy `HJO.Sym.nsShiftComp_comp_dopInt` needs; `q ≠ 0`, `u ≠ 0`, `q ≠ 1` are
those of the evaluation of the slope operator (`HJO.Sweep.zLetter_auxVar_mul`). -/
theorem lhsSlope_add_self (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) {a b : ℕ} (hab : Nat.Coprime a b) (ha : 1 ≤ a)
    (hb : 1 ≤ b) (h : Mellit.LhsSlope q u a b) : Mellit.LhsSlope q u a (b + a) := by
  set t := (Mellit.slopeWord a b).reverse with ht
  obtain ⟨hcy, hcz⟩ := Mellit.count_slopeWord hab ha hb
  have hz : t.count .z + 1 = a := by rw [ht, List.count_reverse, hcz]; omega
  have hc : ((1 : ℕ) : ℤ) + nestDegree 0 t = b := by
    rw [nestDegree, ht, List.count_reverse, hcy, zero_mul, add_zero]; push_cast; omega
  have hdeg : ∀ R : ℕ, Sym.ShiftsDegree (b : ℤ) (lhsNest q u 0 R t 1) := fun R => by
    have h' := lhsNest_shiftsDegree q u 0 R t 1
    rwa [hc] at h'
  have hT : ∀ R : ℕ, Sym.NsTransports q u (hdeg R) ((-1 : L) ^ a • lhsNest q u 1 R t 1) :=
    fun R => Sym.NsTransports.congr hc rfl (by rw [hz, zero_add])
      (nsTransports_lhsNest hM 0 R t 1 (lhsNest_shiftsDegree q u 0 R t 1))
  have hTQ := Sym.nsTransports_qop_add_self q u hM a b hab ha
  intro f
  obtain ⟨R₀, hR₀⟩ :=
    exists_forall_dminus_sweepWordOp hq0 hu0 hq1 (Mellit.shiftWord t) 1 f le_rfl
  have hsweep : ∀ R : ℕ, R₀ ≤ R →
      dminus q 1 (slopeOperator q u 1 a (b + a) (Mellit.slopeArg q u f))
        = MvPolynomial.C (((-1 : L) ^ a • lhsNest q u 1 R t 1) f) := by
    intro R hR
    rw [slopeOperator_eq_sweepWordOp, Mellit.reverse_slopeWord_add_self hab ha hb,
      Mellit.slopeArg_def, ← pow_one (auxVar 1 : Total L), hR₀ R hR, lhsNest_shiftWord, hz,
      zero_add]
  have hstab : ∀ R : ℕ, R₀ ≤ R →
      ((-1 : L) ^ a • lhsNest q u 1 R t 1) f = ((-1 : L) ^ a • lhsNest q u 1 R₀ t 1) f :=
    fun R hR => MvPolynomial.C_injective ℕ (Sym.Lambda L)
      ((hsweep R hR).symm.trans (hsweep R₀ le_rfl))
  have key : ((-1 : L) ^ a • Sym.Qop q u a (b + a)) f
      = (-1 : L) ^ (b + 1) • ((-1 : L) ^ a • lhsNest q u 1 R₀ t 1) f := by
    apply Sym.nsShiftComp_injective q u
    refine Sym.LambdaHat.ext fun e => ?_
    rw [hTQ f, Sym.coe_completionExtension_apply]
    rcases lt_or_ge (e : ℤ) (b : ℤ) with he | he
    · rw [Sym.extVal_of_lt _ _ _ he, map_smul, Sym.LambdaHat.coe_smul, hT R₀ f,
        Sym.coe_completionExtension_apply, Sym.extVal_of_lt _ _ _ he, smul_zero]
    · obtain ⟨n, hn⟩ : ∃ n : ℕ, (n : ℤ) + b = e := ⟨((e : ℤ) - b).toNat, by omega⟩
      set g : Sym.Lambda L := (Sym.nsShiftComp q u f n : Sym.Lambda L)
      obtain ⟨R₂, hR₂⟩ := exists_forall_smul_qop_eq_lhsNest hq0 hu0 hq1 h g
      rw [← hstab (max R₀ R₂) (le_max_left _ _), map_smul, Sym.LambdaHat.coe_smul,
        hT (max R₀ R₂) f, Sym.coe_completionExtension_apply, Sym.extVal_of_add_eq _ _ _ hn,
        Sym.extVal_of_add_eq _ _ _ hn, ← hR₂ (max R₀ R₂) (le_max_right _ _), smul_smul, ← pow_add,
        show b + 1 + (b + 1) = 2 * (b + 1) by ring, pow_mul, neg_one_sq, one_pow, one_smul]
  rw [hsweep R₀ le_rfl, ← C_smul]
  congr 1
  rw [LinearMap.smul_apply] at key
  calc Sym.Qop q u a (b + a) f
      = ((-1 : L) ^ a * (-1 : L) ^ a) • Sym.Qop q u a (b + a) f := by
        rw [← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow, one_smul]
    _ = (-1 : L) ^ a • ((-1 : L) ^ (b + 1) • ((-1 : L) ^ a • lhsNest q u 1 R₀ t 1) f) := by
        rw [mul_smul, key]
    _ = (-1 : L) ^ (b + a + 1) • ((-1 : L) ^ a • lhsNest q u 1 R₀ t 1) f := by
        rw [smul_smul, ← pow_add, show a + (b + 1) = b + a + 1 by ring]

/-- **The clause along a whole `S`-orbit**: from `(a,c)` to every `(a, ka+c)`. -/
theorem lhsSlope_mul_add (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) {a c : ℕ} (hac : Nat.Coprime a c) (ha : 1 ≤ a)
    (hc : 1 ≤ c) (h : Mellit.LhsSlope q u a c) (k : ℕ) :
    Mellit.LhsSlope q u a (k * a + c) := by
  induction k with
  | zero => simpa using h
  | succ k ih =>
    have hcop : Nat.Coprime a (k * a + c) := by
      rw [Nat.coprime_comm, add_comm, Nat.coprime_add_mul_right_left, Nat.coprime_comm]
      exact hac
    have h' := lhsSlope_add_self hM hq0 hu0 hq1 hcop ha (by omega) ih
    rwa [show k * a + c + a = (k + 1) * a + c by ring] at h'

/-- **The clause on every slope `(a, ka+1)`.** For `1 ≤ a` and every `k`, `LhsSlope q u a (ka+1)`
holds: the clause holds on the `S`-orbit of the slope `(a,1)`. -/
theorem lhsSlope_mul_add_one (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) {a : ℕ} (ha : 1 ≤ a) (k : ℕ) :
    Mellit.LhsSlope q u a (k * a + 1) := by
  have hM1 : (1 - q) * (1 - u) ≠ 0 := by simpa using hM 1 le_rfl
  obtain ⟨c, rfl⟩ : ∃ c, a = c + 1 := ⟨a - 1, by omega⟩
  exact lhsSlope_mul_add hM hq0 hu0 hq1 (Nat.coprime_one_right _) ha le_rfl
    (lhsSlope_succ_one hM1 hq0 hu0 hq1 c) k

/-- **The clause at every positive coprime slope, from the slopes below the diagonal.** Every
positive coprime `(a,b)` with `a ≥ 2` is in the `S`-orbit of `(a, b mod a)`, and `1 ≤ b mod a < a`.
So the general clause needs, beyond what is proved here, exactly its instances strictly below the
diagonal; in Mellit's Section 3.7 those are the ones the other generator `N = (1 1; 0 1)`
reaches. -/
theorem lhsSlope_of_lt (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1)
    (hbelow : ∀ a c : ℕ, Nat.Coprime a c → 1 ≤ c → c < a → Mellit.LhsSlope q u a c)
    {a b : ℕ} (hab : Nat.Coprime a b) (ha : 1 ≤ a) (hb : 1 ≤ b) : Mellit.LhsSlope q u a b := by
  rcases Nat.lt_or_ge a 2 with ha2 | ha2
  · obtain rfl : a = 1 := by omega
    exact Mellit.lhsSlope_one_left q u hb
  have hc : Nat.Coprime a (b % a) := by
    rw [Nat.Coprime, Nat.gcd_comm, ← Nat.gcd_rec]
    exact hab
  have hc1 : 1 ≤ b % a := by
    by_contra h0
    have h0' : b % a = 0 := by omega
    rw [h0', Nat.coprime_zero_right] at hc
    omega
  have h := lhsSlope_mul_add hM hq0 hu0 hq1 hc ha hc1
    (hbelow a (b % a) hc hc1 (Nat.mod_lt _ (by omega))) (b / a)
  rwa [Nat.div_add_mod'] at h

/-- **The base case of `HJO.Mellit.lhsRewrite_sweepWitness` on every slope `(a, ka+1)`**: the clause
`HJO.Mellit.LhsAt` at the composition `(1)`, for every slope homomorphism. -/
theorem lhsAt_singleton_one_mul_add_one (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) (hv1 : q * u ≠ 1) {a : ℕ} (ha : 1 ≤ a) (k : ℕ)
    {Θ : Sym.Lambda L →ₐ[L] Module.End L (Sym.Lambda L)}
    (hΘ : Sym.IsSlopeHom a (k * a + 1) q u Θ) :
    Mellit.LhsAt q u a (k * a + 1) Θ [1] :=
  Mellit.lhsAt_singleton_one_of_base (mul_ne_zero hq0 hu0) hv1 hΘ
    (Mellit.lhsBase_of_lhsSlope q u (lhsSlope_mul_add_one hM hq0 hu0 hq1 ha k))

end HJO.Sweep
