/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitShiftSign
public import HJO.Collinear.Vocabulary
public meta import HJO.Attr

/-! # The shift on the algebra the basic operators generate

`HJO.Sym.nsShiftComp_comp_smul_map`, stated inside `End_𝕜(Λ)`, asks for
`τ^*τ S(E) = E τ^*τ` for `E` in a subalgebra of `End_𝕜(Λ)`. This file is the assembly that
statement calls for, carried out on the generating set the basic operators `D_n` provide, together
with the two facts that keep it from being that statement in its first formulation; the statement
itself is proved, with the twisted shift, in `HJO/Shuffle/MellitShiftTwisted.lean`.

## The orientation, which is transposed from `HJO.Sym.nsShiftComp_comp_smul_map`'s

The transport relation, in the form of `HJO.Sym.nsShiftComp_comp_dopInt`, is

    ∀ f, nsShiftComp q u (E f) = completionExtension hD (nsShiftComp q u f),

i.e. `τ^*τ ∘ E = D̂ ∘ τ^*τ`, where `D` is the endomorphism being *extended* to the completion and
`E` is the plain endomorphism of `Λ`. That statement writes the same identity as
`τ^*τ S(E) = E τ^*τ`. **The two letters are transposed:** the `E` is this file's `D`
(the operator whose extension `Ê = D̂` appears on the right), and the `S(E)` is this
file's `E` (the plain operator on the left). `HJO.Sym.NsTransports` below is named for the
orientation of `HJO.Sym.nsShiftComp_comp_dopInt`: `NsTransports q u hD E` reads "`D` transports
`E`", and the shift is the map `D ↦ E`, so `S` runs from the `D`-slot to the `E`-slot.

With that dictionary the settled sign reads `S(D̂_n) = -D_{n+1}`: `D = D_n` transports
`E = -D_{n+1}`. It is proved in `HJO/Shuffle/MellitShiftSign.lean`
(`HJO.Sym.eq_neg_dopInt_of_nsShiftComp`, `HJO.Sym.not_nsShiftComp_dopInt_neg_one`) and nothing here
re-derives or contradicts it.

## What is proved

* `HJO.Sym.NsTransports` — the transport relation as a predicate, and its closure properties:
  `HJO.Sym.NsTransports.one`, `.mul` (which is `HJO.Sym.nsShiftComp_mul`), `.add`, `.smul`,
  and `HJO.Sym.nsTransports_zero`. The two linear ones are new here and are what makes the
  passage from products of generators to their span possible at all.
* `HJO.Sym.nsTransports_dopIntWord` — **the assembly.** Every word `D_{n_1}⋯D_{n_r}` in the basic
  operators transports the word `(-D_{n_1+1})⋯(-D_{n_r+1})`, which is
  `(-1)^r D_{n_1+1}⋯D_{n_r+1}` (`HJO.Sym.dopIntWordShift_eq`): the generator case is
  `HJO.Sym.nsShiftComp_comp_dopInt` and the induction step is `HJO.Sym.nsShiftComp_mul`.
* `HJO.Sym.existsUnique_nsTransports_of_mem_dopIntSpan` — **the assembly in the form the statement
  wants**: for every `D` in `HJO.Sym.dopIntSpan q u c`, the `𝕜`-span of the words of total degree
  `c`, there is exactly one `E` with `τ^*τ E = D̂ τ^*τ`. Existence is the previous item closed
  under the span; uniqueness is `HJO.Sym.nsShiftComp_eq_of_eq`.
* `HJO.Sym.adjoin_dopInt_toSubmodule` — the span family exhausts the subalgebra: the subalgebra
  generated by all the `D_n` is `⨆ c, dopIntSpan q u c` as a `𝕜`-submodule. So the theorem above
  covers every *degree-homogeneous* element of that subalgebra, and the only elements it does not
  reach are the mixed-degree ones.

## Why this is not `HJO.Sym.nsShiftComp_comp_smul_map`

Three separate obstructions, in increasing order of how much they matter.

**The grading.** `D̂` is `HJO.Sym.completionExtension hD`, and `hD : ShiftsDegree c D` is part of
the data: a sum of operators shifting by *different* degrees shifts by no degree, so it has no
extension to `Λ̂` and the statement's right-hand side cannot even be written for it. The natural
domain is therefore a graded piece, not the whole subalgebra — `HJO.Sym.dopIntSpan q u c` — and
`HJO.Sym.adjoin_dopInt_toSubmodule` says precisely how much of the subalgebra that is. This is a
defect of the statement rather than of its proof: quantifying over the subalgebra presumes an
extension that only the homogeneous elements have.

**The generators.** The statement, formulated inside `End_𝕜(Λ)`, quantifies over the subalgebra
generated by "the operators the `T_i`, `d_-`, `d^*_+` and the corner elements act as". Those
operators are not given directly as endomorphisms of `Λ`. `T_i`, `d_-` and `d^*_+` are maps of
`HJO.Sweep.TotalFrac`/`HJO.Sweep.HatFrac`, the `y`-inverted total space with the auxiliary
variables — that is where `HJO.Sweep.fracDplusStar_nsShiftExt` and
`HJO.Sweep.hatFracDplusStar_nsShiftStarFrac` live, and neither
is an identity in `End_𝕜(Λ)`. Turning them into operators on `Λ` is exactly the action
`HJO.Sweep.exists_isDpaAction_mellit`. So moving the statement from `e_0Ãe_0` into
`End_𝕜(Λ)` does not by itself remove the dependence on that action: it relocates it from
the *quantifier* to the
*generating set*. What `End_𝕜(Λ)` does have is the family `D_n`, and that is the generating set
used here.

**The sign, in the vocabulary the formulation names.** The formulation inside `End_𝕜(Λ)` points at
`HJO.Sym.IsIndexShift` on `HJO.Sym.DopAlgebra`, and `HJO.Sym.IsIndexShift` asks `S(D_k) = +D_{k+1}`.
That normalisation does not satisfy the statement's identity:
`HJO.Sym.not_nsTransports_isIndexShift` below shows that for *any* index shift `S`,
`τ^*τ S(D_0) = D̂_0 τ^*τ` is false — `HJO.Sym.nsShiftComp_eq_of_eq` forces `S(D_0) = -D_1`, so
`D_1 = -D_1`, and `D_1(1) = -e_1 = -p_1` is not its own negative in a `ℚ`-algebra. This is the
`n = 0` companion of `HJO.Sym.not_nsShiftComp_dopInt_neg_one`, moved inside `DopAlgebra`
so that it refutes the reading that formulation names. The resolution —
the shift on `Ã` and `HJO.Sym.IsIndexShift` differ by the `(-1)^m` twist of
`HJO.Dyck.Tilde.rel_biHomogeneous` — is carried out in `HJO/Shuffle/MellitShiftTwisted.lean`; that
twisted shift is not `HJO.Sym.IsIndexShift`, and no lemma here states it.

So this file proves the assembly on the generating set `End_𝕜(Λ)` provides and on the graded
pieces where the statement can be typed: the statement in its first formulation quantifies over
operators not given directly on `Λ` and over mixed-degree elements for which its own right-hand side
is undefined.

## References

A. Mellit, *Toric braids and `(m,n)`-parking functions*, §3.7.
-/

@[expose] public section

namespace HJO.Sym

section CommRingBase

variable {K : Type*} [CommRing K]

/-! ### The linear behaviour of the extension to the completion

`HJO.Sym.completionExtension_mul` records that the extension is multiplicative in the operator.
These three record that at a *fixed* degree it is also linear in it, which is what carries the
assembly below from the words in the basic operators to their span. The fixed degree is not a
convenience: `HJO.Sym.completionExtension` takes `ShiftsDegree c D` as an argument, and a sum of
operators shifting by different degrees shifts by none. -/

/-- The extension of the identity is the identity. -/
theorem completionExtension_one :
    completionExtension (shiftsDegree_one (K := K)) = 1 := by
  refine LinearMap.ext fun F => LambdaHat.ext fun e => ?_
  rw [coe_completionExtension_apply, extVal_of_add_eq (n := e) _ _ _ (by ring)]
  rfl

/-- The extension of the zero operator is zero. -/
theorem completionExtension_zero {c : ℤ}
    (h : ShiftsDegree c (0 : Module.End K (Lambda K))) : completionExtension h = 0 := by
  refine LinearMap.ext fun F => LambdaHat.ext fun e => ?_
  rw [coe_completionExtension_apply, extVal]
  split_ifs
  · rfl
  · rfl

/-- **The extension is additive in the operator at a fixed degree.** -/
theorem completionExtension_add {c : ℤ} {D D' : Module.End K (Lambda K)}
    (hD : ShiftsDegree c D) (hD' : ShiftsDegree c D') (hsum : ShiftsDegree c (D + D')) :
    completionExtension hsum = completionExtension hD + completionExtension hD' := by
  refine LinearMap.ext fun F => LambdaHat.ext fun e => ?_
  rw [coe_completionExtension_apply, LinearMap.add_apply, LambdaHat.coe_add,
    coe_completionExtension_apply, coe_completionExtension_apply, extVal, extVal, extVal]
  split_ifs
  · rfl
  · rw [add_zero]

/-- **The extension is homogeneous in the operator.** The companion of
`HJO.Sym.completionExtension_add`. -/
theorem completionExtension_smul {c : ℤ} (r : K) {D : Module.End K (Lambda K)}
    (hD : ShiftsDegree c D) (hrD : ShiftsDegree c (r • D)) :
    completionExtension hrD = r • completionExtension hD := by
  refine LinearMap.ext fun F => LambdaHat.ext fun e => ?_
  rw [coe_completionExtension_apply, LinearMap.smul_apply, LambdaHat.coe_smul,
    coe_completionExtension_apply, extVal, extVal]
  split_ifs
  · rfl
  · rw [smul_zero]

end CommRingBase

section Field

variable {K : Type*} [Field K] [Algebra ℚ K]

/-! ### The transport relation and its closure properties -/

/-- **`D` transports `E`**: the relation `τ^*τ E = D̂ τ^*τ` of Mellit's Section 3.7, with `D`
the operator extended to the completion and `E` the plain operator on `Λ`. Its shift form is
`τ^*τ S(E) = E τ^*τ`, whose `E` is this `D` and whose `S(E)` is this `E`; see the module
docstring. -/
def NsTransports (q u : K) {c : ℤ} {D : Module.End K (Lambda K)} (hD : ShiftsDegree c D)
    (E : Module.End K (Lambda K)) : Prop :=
  ∀ f : Lambda K, nsShiftComp q u (E f) = completionExtension hD (nsShiftComp q u f)

/-- The identity transports the identity. -/
theorem NsTransports.one (q u : K) : NsTransports q u (shiftsDegree_one (K := K)) 1 := by
  intro f
  rw [completionExtension_one]
  rfl

/-- The zero operator transports the zero operator. -/
theorem nsTransports_zero (q u : K) {c : ℤ}
    (h : ShiftsDegree c (0 : Module.End K (Lambda K))) : NsTransports q u h 0 := by
  intro f
  rw [completionExtension_zero]
  simp

/-- **Transport is multiplicative**, which is `HJO.Sym.nsShiftComp_mul` read in this
vocabulary. -/
theorem NsTransports.mul {q u : K} {c₁ c₂ : ℤ} {D₁ D₂ : Module.End K (Lambda K)}
    {hD₁ : ShiftsDegree c₁ D₁} {hD₂ : ShiftsDegree c₂ D₂} {E₁ E₂ : Module.End K (Lambda K)}
    (h₁ : NsTransports q u hD₁ E₁) (h₂ : NsTransports q u hD₂ E₂) :
    NsTransports q u (hD₁.comp hD₂) (E₁ * E₂) :=
  nsShiftComp_mul q u hD₁ hD₂ h₁ h₂

/-- **Transport is additive at a fixed degree.** Both sides of the transport relation are linear in
the pair `(D, E)`, and `HJO.Sym.completionExtension_add` is what lets the right-hand side split; the
common degree is essential, since otherwise `D₁ + D₂` has no extension. -/
theorem NsTransports.add {q u : K} {c : ℤ} {D₁ D₂ : Module.End K (Lambda K)}
    {hD₁ : ShiftsDegree c D₁} {hD₂ : ShiftsDegree c D₂} {hsum : ShiftsDegree c (D₁ + D₂)}
    {E₁ E₂ : Module.End K (Lambda K)}
    (h₁ : NsTransports q u hD₁ E₁) (h₂ : NsTransports q u hD₂ E₂) :
    NsTransports q u hsum (E₁ + E₂) := by
  intro f
  rw [completionExtension_add hD₁ hD₂ hsum, LinearMap.add_apply, map_add, h₁ f, h₂ f,
    LinearMap.add_apply]

/-- **Transport is homogeneous.** The companion of `HJO.Sym.NsTransports.add`. -/
theorem NsTransports.smul {q u : K} (r : K) {c : ℤ} {D : Module.End K (Lambda K)}
    {hD : ShiftsDegree c D} {hrD : ShiftsDegree c (r • D)} {E : Module.End K (Lambda K)}
    (h : NsTransports q u hD E) : NsTransports q u hrD (r • E) := by
  intro f
  rw [completionExtension_smul r hD hrD, LinearMap.smul_apply, map_smul, h f,
    LinearMap.smul_apply]

/-- **The generator case**, `HJO.Sym.nsShiftComp_comp_dopInt`: `D_n` transports
`-D_{n+1}`. -/
theorem nsTransports_dopInt (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) (n : ℤ) :
    NsTransports q u (dopInt_shiftsDegree q u n) (-(DopInt q u (n + 1))) :=
  nsShiftComp_neg_dopInt q u hM n

/-! ### Words in the basic operators -/

/-- The word `D_{n_1}⋯D_{n_r}` in the basic operators. -/
noncomputable def dopIntWord (q u : K) (ns : List ℤ) : Module.End K (Lambda K) :=
  (ns.map (DopInt q u)).prod

theorem dopIntWord_nil (q u : K) : dopIntWord q u [] = 1 := rfl

theorem dopIntWord_cons (q u : K) (n : ℤ) (ns : List ℤ) :
    dopIntWord q u (n :: ns) = DopInt q u n * dopIntWord q u ns := rfl

/-- The word the shift assigns to `D_{n_1}⋯D_{n_r}`, namely `(-D_{n_1+1})⋯(-D_{n_r+1})`. -/
noncomputable def dopIntWordShift (q u : K) (ns : List ℤ) : Module.End K (Lambda K) :=
  (ns.map fun n => -(DopInt q u (n + 1))).prod

theorem dopIntWordShift_nil (q u : K) : dopIntWordShift q u [] = 1 := rfl

theorem dopIntWordShift_cons (q u : K) (n : ℤ) (ns : List ℤ) :
    dopIntWordShift q u (n :: ns) = -(DopInt q u (n + 1)) * dopIntWordShift q u ns := rfl

/-- **The sign the shift carries on a word is `(-1)^r`**, one minus for each letter. This is the
`(-1)^m`-twist of `HJO.Dyck.Tilde.rel_biHomogeneous` read on a word: the shifted word is the
unsigned word `D_{n_1+1}⋯D_{n_r+1}` times `(-1)^r`. -/
theorem dopIntWordShift_eq (q u : K) (ns : List ℤ) :
    dopIntWordShift q u ns
      = (-1 : K) ^ ns.length • (ns.map fun n => DopInt q u (n + 1)).prod := by
  induction ns with
  | nil => rw [dopIntWordShift_nil, List.length_nil, pow_zero, one_smul, List.map_nil,
      List.prod_nil]
  | cons n ns ih =>
    rw [dopIntWordShift_cons, ih, List.map_cons, List.prod_cons, List.length_cons, pow_succ,
      neg_mul, mul_smul_comm, ← neg_smul, mul_neg_one]

/-- A word shifts degree by the sum of its letters. -/
theorem dopIntWord_shiftsDegree (q u : K) (ns : List ℤ) :
    ShiftsDegree ns.sum (dopIntWord q u ns) := by
  induction ns with
  | nil => exact shiftsDegree_one
  | cons n ns ih =>
    rw [dopIntWord_cons, List.sum_cons]
    exact (dopInt_shiftsDegree q u n).comp ih

/-- **The assembly on the words.** Every word `D_{n_1}⋯D_{n_r}` in the basic operators transports
`(-D_{n_1+1})⋯(-D_{n_r+1})`: the base case is `HJO.Sym.NsTransports.one`, the letter case is
`HJO.Sym.nsShiftComp_comp_dopInt` and the induction step is
`HJO.Sym.nsShiftComp_mul`. -/
theorem nsTransports_dopIntWord (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) (ns : List ℤ) :
    NsTransports q u (dopIntWord_shiftsDegree q u ns) (dopIntWordShift q u ns) := by
  induction ns with
  | nil => exact NsTransports.one q u
  | cons n ns ih => exact (nsTransports_dopInt q u hM n).mul ih

/-! ### The graded pieces of the algebra the basic operators generate -/

/-- **The degree-`c` part of the algebra the basic operators generate**: the `𝕜`-span of the words
`D_{n_1}⋯D_{n_r}` whose letters sum to `c`. This is the domain on which
`HJO.Sym.nsShiftComp_comp_smul_map` can be stated at all: an element of the subalgebra mixing
degrees has no extension to the completion, so the statement's right-hand side is undefined on
it. -/
noncomputable def dopIntSpan (q u : K) (c : ℤ) : Submodule K (Module.End K (Lambda K)) :=
  Submodule.span K {D | ∃ ns : List ℤ, ns.sum = c ∧ dopIntWord q u ns = D}

theorem dopIntWord_mem_dopIntSpan (q u : K) (ns : List ℤ) :
    dopIntWord q u ns ∈ dopIntSpan q u ns.sum :=
  Submodule.subset_span ⟨ns, rfl, rfl⟩

/-- The degree-`c` part is not empty of content: it contains the basic operator `D_c` itself
whenever `c` is one of the indices. -/
theorem dopInt_mem_dopIntSpan (q u : K) (n : ℤ) : DopInt q u n ∈ dopIntSpan q u n :=
  Submodule.subset_span ⟨[n], by simp, by rw [dopIntWord_cons, dopIntWord_nil, mul_one]⟩

theorem dopIntSpan_le_degreeShifting (q u : K) (c : ℤ) :
    dopIntSpan q u c ≤ degreeShifting K c := by
  refine Submodule.span_le.2 ?_
  rintro D ⟨ns, hsum, rfl⟩
  exact hsum ▸ dopIntWord_shiftsDegree q u ns

/-- Everything in the degree-`c` part shifts degree by `c`, so it has an extension to the
completion. -/
theorem shiftsDegree_of_mem_dopIntSpan {q u : K} {c : ℤ} {D : Module.End K (Lambda K)}
    (hD : D ∈ dopIntSpan q u c) : ShiftsDegree c D :=
  dopIntSpan_le_degreeShifting q u c hD

/-- **The assembly on a graded piece.** Every `D` in the degree-`c` part of the algebra the basic
operators generate transports some `E`. The generators are covered by
`HJO.Sym.nsTransports_dopIntWord` and the span by the closure properties: products are
`HJO.Sym.nsShiftComp_mul`, and sums and scalars are `HJO.Sym.NsTransports.add` and
`HJO.Sym.NsTransports.smul`, which need the fixed degree. -/
theorem exists_nsTransports_of_mem_dopIntSpan (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) {c : ℤ}
    {D : Module.End K (Lambda K)} (hD : D ∈ dopIntSpan q u c) :
    ∃ E, NsTransports q u (shiftsDegree_of_mem_dopIntSpan hD) E := by
  suffices h : ∀ D ∈ dopIntSpan q u c,
      ∀ hDs : ShiftsDegree c D, ∃ E, NsTransports q u hDs E from h D hD _
  intro D hD
  induction hD using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨ns, hsum, rfl⟩ := hx
    subst hsum
    exact fun _ => ⟨_, nsTransports_dopIntWord q u hM ns⟩
  | zero => exact fun h => ⟨0, nsTransports_zero q u h⟩
  | add x y hx hy ihx ihy =>
    intro _
    obtain ⟨Ex, hEx⟩ := ihx (shiftsDegree_of_mem_dopIntSpan hx)
    obtain ⟨Ey, hEy⟩ := ihy (shiftsDegree_of_mem_dopIntSpan hy)
    exact ⟨Ex + Ey, hEx.add hEy⟩
  | smul r x hx ih =>
    intro _
    obtain ⟨Ex, hEx⟩ := ih (shiftsDegree_of_mem_dopIntSpan hx)
    exact ⟨r • Ex, hEx.smul r⟩

/-- **`HJO.Sym.nsShiftComp_comp_smul_map` on a graded piece**: for every `D` in the degree-`c` part
of the algebra the basic operators generate there is exactly one `E` with `τ^*τ E = D̂ τ^*τ`.
Existence is `HJO.Sym.exists_nsTransports_of_mem_dopIntSpan` — the generators closed under products,
sums and scalars — and uniqueness is `HJO.Sym.nsShiftComp_eq_of_eq`, from the injectivity
of `τ^*τ`.

Read against `HJO.Sym.nsShiftComp_comp_smul_map`, `D` is its `E` and the unique `E` here is its
`S(E)`;
the value on a word is `HJO.Sym.nsTransports_dopIntWord`, with the sign of
`HJO.Sym.dopIntWordShift_eq`. -/
theorem existsUnique_nsTransports_of_mem_dopIntSpan (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) {c : ℤ}
    {D : Module.End K (Lambda K)} (hD : D ∈ dopIntSpan q u c) :
    ∃! E, NsTransports q u (shiftsDegree_of_mem_dopIntSpan hD) E := by
  obtain ⟨E, hE⟩ := exists_nsTransports_of_mem_dopIntSpan q u hM hD
  exact ⟨E, hE, fun E' hE' => nsShiftComp_eq_of_eq q u _ hE' hE⟩

/-- **The value at a generator is the settled `-D_{n+1}`.** The previous theorem read at
`D = D_n ∈ dopIntSpan q u n`: the unique `E` it produces is the one
`HJO/Shuffle/MellitShiftSign.lean` pins down. Nothing here chooses the sign; it is
`HJO.Sym.nsShiftComp_comp_dopInt` and `HJO.Sym.nsShiftComp_eq_of_eq` that do. -/
theorem nsTransports_dopInt_mem (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0) (n : ℤ) :
    NsTransports q u (shiftsDegree_of_mem_dopIntSpan (dopInt_mem_dopIntSpan q u n))
      (-(DopInt q u (n + 1))) :=
  nsTransports_dopInt q u hM n

/-! ### The graded pieces exhaust the subalgebra -/

theorem dopIntWord_mem_closure (q u : K) (ns : List ℤ) :
    dopIntWord q u ns ∈ Submonoid.closure (Set.range (DopInt q u)) := by
  induction ns with
  | nil => rw [dopIntWord_nil]; exact one_mem _
  | cons n ns ih =>
    rw [dopIntWord_cons]
    exact mul_mem (Submonoid.subset_closure ⟨n, rfl⟩) ih

theorem exists_dopIntWord_of_mem_closure (q u : K) {x : Module.End K (Lambda K)}
    (hx : x ∈ Submonoid.closure (Set.range (DopInt q u))) :
    ∃ ns : List ℤ, dopIntWord q u ns = x := by
  induction hx using Submonoid.closure_induction with
  | mem x hx =>
    obtain ⟨n, rfl⟩ := hx
    exact ⟨[n], by rw [dopIntWord_cons, dopIntWord_nil, mul_one]⟩
  | one => exact ⟨[], dopIntWord_nil q u⟩
  | mul x y _ _ ihx ihy =>
    obtain ⟨nsx, rfl⟩ := ihx
    obtain ⟨nsy, rfl⟩ := ihy
    exact ⟨nsx ++ nsy, by rw [dopIntWord, dopIntWord, dopIntWord, List.map_append,
      List.prod_append]⟩

/-- **The graded pieces exhaust the subalgebra.** The `𝕜`-subalgebra of `End_𝕜(Λ)` generated by all
the basic operators is, as a `𝕜`-submodule, the sum of its degree-`c` parts. So
`HJO.Sym.existsUnique_nsTransports_of_mem_dopIntSpan` covers every degree-homogeneous element of the
subalgebra `HJO.Sym.nsShiftComp_comp_smul_map` quantifies over, and what it does not cover is
exactly the mixed-degree elements — for which the statement's `D̂` does not exist. -/
theorem adjoin_dopInt_toSubmodule (q u : K) :
    Subalgebra.toSubmodule (Algebra.adjoin K (Set.range (DopInt q u)))
      = ⨆ c : ℤ, dopIntSpan q u c := by
  rw [Algebra.adjoin_eq_span]
  refine le_antisymm (Submodule.span_le.2 fun x hx => ?_) (iSup_le fun c => ?_)
  · obtain ⟨ns, rfl⟩ := exists_dopIntWord_of_mem_closure q u hx
    exact Submodule.mem_iSup_of_mem ns.sum (Submodule.subset_span ⟨ns, rfl, rfl⟩)
  · refine Submodule.span_le.2 ?_
    rintro D ⟨ns, -, rfl⟩
    exact Submodule.subset_span (dopIntWord_mem_closure q u ns)

/-! ### The `HJO.Sym.IsIndexShift` normalisation does not transport -/

/-- The first elementary symmetric function is the generator of index zero. A local copy of
`HJO.Sym.elemSymm_one_eq_X`, which lives in `HJO/Collinear/Commutation.lean` and is not
imported here. -/
private theorem elemSymm_one_eq_X' : elemSymm K 1 = MvPolynomial.X 0 := by
  rw [show (1 : ℕ) = 0 + 1 from rfl, elemSymm]
  simp [powerSum, show elemSymm K 0 = 1 from by rw [elemSymm]]

/-- **`D_1(1) = -e_1`**, the one value of a basic operator the sign refutation below reads: the
displacement of a constant is that constant, so only the `w^0`-piece survives and it is
multiplication by `(-1)^1e_1`. -/
theorem dop_one_apply_one (q u : K) : Dop q u 1 (1 : Lambda K) = -elemSymm K 1 := by
  rw [DopRees.dop_apply_eq_sum q u 1 1 (N := 1) (by rw [map_one]; simp), Finset.sum_range_one,
    DopRees.dopPiece_apply, map_one]
  simp

/-- **The `HJO.Sym.IsIndexShift` normalisation does not satisfy
`HJO.Sym.nsShiftComp_comp_smul_map`'s identity.** For any index shift `S` of `HJO.Sym.IsIndexShift`
— that is, any `𝕜`-algebra endomorphism of `𝖠` with `S(D_k) = +D_{k+1}` — the statement's identity
fails already at `E = D_0`: `τ^*τ S(D_0) = D̂_0 τ^*τ` is false.

`HJO.Sym.nsShiftComp_eq_of_eq` forces any solution to be `-D_1`
(`HJO.Sym.eq_neg_dopInt_of_nsShiftComp`), so `S(D_0) = D_1` would give `D_1 = -D_1`; evaluating at
`1` gives `-e_1 = e_1`, hence `2 = 0` in `𝕜`, which a `ℚ`-algebra forbids.

This is the `n = 0` companion of `HJO.Sym.not_nsShiftComp_dopInt_neg_one`, placed inside
`DopAlgebra` so that it refutes the reading the formulation inside `End_𝕜(Λ)` names rather than an
integer-indexed one. The `D` here is `DopInt q u 0`, which is `Dop q u 0`
(`HJO.Sym.dopInt_natCast`). -/
theorem not_nsTransports_isIndexShift (q u : K)
    (hM : ∀ k : ℕ, 1 ≤ k → (1 - q ^ k) * (1 - u ^ k) ≠ 0)
    {S : DopAlgebra q u →ₐ[K] DopAlgebra q u} (hS : IsIndexShift q u S) :
    ¬ NsTransports q u (dopInt_shiftsDegree q u 0)
      (S (dopGen q u 0) : Module.End K (Lambda K)) := by
  intro h
  rw [(isIndexShift_iff q u S).1 hS 0] at h
  have hEq : Dop q u (0 + 1) = -DopInt q u ((0 : ℤ) + 1) :=
    eq_neg_dopInt_of_nsShiftComp q u hM 0 h
  rw [show (0 : ℤ) + 1 = ((1 : ℕ) : ℤ) from by norm_num, dopInt_natCast,
    show (0 : ℕ) + 1 = 1 from rfl] at hEq
  have happ := congrArg (fun P : Module.End K (Lambda K) => P (1 : Lambda K)) hEq
  simp only [LinearMap.neg_apply, dop_one_apply_one] at happ
  have hx : (MvPolynomial.X 0 : Lambda K) + MvPolynomial.X 0 = 0 := by
    rw [elemSymm_one_eq_X'] at happ
    linear_combination -happ
  have hchar : CharZero K := charZero_of_injective_algebraMap (algebraMap ℚ K).injective
  have h2 : (2 : K) = 0 := by
    have hc := congrArg (MvPolynomial.coeff (Finsupp.single 0 1)) hx
    simp only [MvPolynomial.coeff_add, MvPolynomial.coeff_X, MvPolynomial.coeff_zero,
      ite_true] at hc
    linear_combination hc
  exact two_ne_zero h2

end Field

end HJO.Sym

end
