/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitLhsSlopeCompat

/-! # Mellit's `N` on the base-case clause of `HJO.Mellit.lhsRewrite_sweepWitness`

**`HJO.Sweep.IsNOperator` is unsatisfiable.**
`HJO.Sweep.not_exists_isNOperator` (`HJO/Shuffle/MellitNablaPrime.lean`) proves that no
Macdonald conjugator `∇` and operator `Nt` satisfy it under the standing nondegeneracy hypotheses:
on the total space the pieces are nested, so one `Nt` meets each constant both in `V_0` and in
`V_1`, which forces `∇` to commute with `D_0`. So `lhsSlope_add_left` below is vacuous under
those hypotheses. The word identity `HJO.Mellit.slopeWord_add_left` is unaffected. The repaired
hypothesis is `HJO.Sweep.IsNOperatorOnPieces` (one operator per piece), with
`HJO.Sweep.lhsSlope_of_coprime_of_isNOperatorOnPieces` and `HJO.Sweep.lhsSlope_of_coprime_of_bar`
in `HJO/Shuffle/MellitNablaPrime.lean`.

The clause `HJO.Mellit.LhsSlope q u a b` states, for every `f ∈ Λ`,
`C(Q_{a,b}f) = (-1)^{b+1}·d_-(Ξ^{(1)}_{a,b}(y_1d^*_+(Cf)))`. In Mellit's Section 3.7 the positive
coprime slopes are reached from the axis by the monoid generated by `N = (1 1; 0 1)` and
`S = (1 0; 1 1)`. The `S` half is `HJO.Sweep.lhsSlope_add_self`; this file carries out the `N`
half, `LhsSlope q u m n → LhsSlope q u (m + n) n`, relative to an operator realising `N` on the
whole space.

* **On `Λ`.** `N` is conjugation by the Macdonald conjugator:
  `Q_{m+n,n}∇ = ∇Q_{m,n}` (`HJO.Sym.qop_add_apply_nabla`, `HJO.Sym.qop_conj_up`).
* **On the slope word.** `N` shears the word, `β_{m+n,n} = 𝗓·β_{m,n}[𝗒 ↦ 𝗒𝗓]`, by Stern–Brocot
  induction from `HJO.Mellit.slopeWord_mediant`.
* **On the sweep side.** Unlike `S`, the shear `𝗒 ↦ 𝗒𝗓` is not a substitution of basic operators
  on `Λ`: `∇D_k∇^{-1} = Q_{k+1,k}` is not a `D`. So `N` has to be realised on `V_1` itself, by an
  operator `𝒩'` that is `∇` on `V_0`, commutes with `d_-` and `d^*_+` (hence with `z_1`), and
  carries `y_1` to `(qu)^{-1}z_1y_1` (`HJO.Sweep.IsNOperator`). Such an operator carries the word
  of `(m,n)` to the word of `(m+n,n)` letter by letter, the extra leading `𝗓` coming from the
  argument `y_1d^*_+Cf`.

## Main definitions

* `HJO.Mellit.addLeftSubst`: the substitution `𝗒 ↦ 𝗒𝗓`, `𝗓 ↦ 𝗓`.
* `HJO.Sweep.IsNOperator`: an operator realising `N` on `V_0 ⊕ V_1 ⊕ V_2`, over a given `∇`.

## Main results

* `HJO.Mellit.slopeWord_add_left`: `β_{m+n,n} = 𝗓·β_{m,n}[𝗒 ↦ 𝗒𝗓]`.
* `HJO.Sweep.IsNOperator.map_sweepWordOp`: `𝒩'` carries a word on `V_1` to its shear.
* `HJO.Sweep.lhsSlope_add_left`: `LhsSlope q u m n → LhsSlope q u (m + n) n`, given `∇` and `𝒩'`.

## Implementation notes

The existence of an operator `𝒩'` with `HJO.Sweep.IsNOperator` is not proved here. In Mellit's
proof of `∇L∇^{-1} = N(L)` it is the endomorphism of `V_*` induced, through the structure theorem
`V_* ≅ 𝔸e_0/𝓘`, by the algebra endomorphism `N` of `𝔸_{q,t}` fixing `d_-`, `d^*_+`, `T_i` and
`z_i` and sending `d_+` to `-(qt)^{-1}z_1d_+`, identified with `∇` on `V_0` through the conjugation
operator of Carlsson–Mellit. Two conventions are absorbed into the hypothesis. Mellit's `∇` carries
the sign `(-1)^{|λ|}`, which the Macdonald conjugator here does not; correspondingly the operator
asked for is Mellit's composed with the sign `(-1)^{\deg}` of the grading in which `y_1` has degree
one, and so its clause at `y_1` carries the scalar `(qu)^{-1}` rather than `-(qu)^{-1}`. The sign
is not a free choice: with the opposite one the hypothesis would contradict
`HJO.Sym.qop_succ_apply_nabla` already at `(1,1) ↦ (2,1)`.

The hypothesis does not mention a slope. It is a property of one operator on `V_0 ⊕ V_1 ⊕ V_2`
against the generators `d_-`, `d^*_+` and `y_1`, whereas its consequence
`HJO.Sweep.lhsSlope_add_left` is an identity at every coprime slope; in particular
the clause at `y_1` is required on all of `V_1`, not on the vectors the slope words reach.

## References

* [A. Mellit, *Toric braids and (m,n)-parking functions*][mellit2016], §3.7.
-/

@[expose] public section

namespace HJO.Mellit

/-- The letter substitution by which the slope word of `(m + n, n)` is read off that of `(m, n)`:
every `𝗒` is followed by one `𝗓`. -/
def addLeftSubst : SlopeLetter → List SlopeLetter
  | .y => [.y, .z]
  | .z => [.z]

/-- The slope words on the ray `(n + 1, n)`. -/
theorem slopeWord_succ_self {n : ℕ} (hn : 1 ≤ n) :
    slopeWord (n + 1) n = .z :: (List.replicate (n - 1) SlopeLetter.y).flatMap addLeftSubst := by
  induction n with
  | zero => omega
  | succ k ih =>
    rcases Nat.eq_zero_or_pos k with rfl | hk
    · rfl
    · have hmed := (slopeWord_mediant (m₁ := 1) (n₁ := 1) (m₂ := k + 1) (n₂ := k) le_rfl le_rfl
        (by omega) hk (by ring) (Nat.coprime_one_left _)
        (Nat.coprime_self_add_left.2 (Nat.coprime_one_left _))).2
      rw [show 1 + (k + 1) = k + 1 + 1 from by ring, show 1 + k = k + 1 from by ring] at hmed
      rw [hmed, ih hk, show slopeWord 1 1 = [] from rfl,
        show k + 1 - 1 = (k - 1) + 1 from by omega, List.replicate_succ', List.flatMap_append]
      simp [addLeftSubst]

/-- A run of `𝗓` is fixed by the substitution. -/
theorem flatMap_addLeftSubst_replicate_z (k : ℕ) :
    (List.replicate k SlopeLetter.z).flatMap addLeftSubst = List.replicate k .z := by
  induction k with
  | zero => rfl
  | succ k ih => rw [List.replicate_succ, List.flatMap_cons, ih]; rfl

/-- **The shear `N` on slope words**: `β_{m+n,n} = 𝗓·β_{m,n}[𝗒 ↦ 𝗒𝗓]`, by Stern–Brocot induction
from `HJO.Mellit.slopeWord_mediant`; the two parents of `(m+n, n)` are the shears of the two
parents of `(m,n)`. -/
theorem slopeWord_add_left {m n : ℕ} (hc : Nat.Coprime m n) (hm : 1 ≤ m) (hn : 1 ≤ n) :
    slopeWord (m + n) n = .z :: (slopeWord m n).flatMap addLeftSubst := by
  refine coprime_induction (P := fun m n =>
    slopeWord (m + n) n = .z :: (slopeWord m n).flatMap addLeftSubst) ?_ ?_ ?_ m n hc hm hn
  · intro n hn
    rw [slopeWord_one_left hn, add_comm, slopeWord_succ_self hn]
  · intro m hm
    rw [slopeWord_one_right hm, slopeWord_one_right (by omega), flatMap_addLeftSubst_replicate_z,
      show m + 1 - 1 = (m - 1) + 1 from by omega, List.replicate_succ]
  · intro m₁ n₁ m₂ n₂ hm₁ hn₁ hm₂ hn₂ hdet hc₁ hc₂ ih₁ ih₂
    have hdet' : (m₂ + n₂) * n₁ = (m₁ + n₁) * n₂ + 1 := by
      rw [add_mul, add_mul]; linarith [Nat.mul_comm n₁ n₂]
    have hmed := (slopeWord_mediant (by omega : 1 ≤ m₁ + n₁) hn₁ (by omega : 1 ≤ m₂ + n₂) hn₂
      hdet' (Nat.coprime_add_self_left.2 hc₁) (Nat.coprime_add_self_left.2 hc₂)).2
    rw [show m₁ + m₂ + (n₁ + n₂) = (m₁ + n₁) + (m₂ + n₂) from by ring, hmed, ih₁, ih₂,
      (slopeWord_mediant hm₁ hn₁ hm₂ hn₂ hdet hc₁ hc₂).2]
    simp [List.flatMap_append, addLeftSubst]

/-- The substitution commutes with reversal once the leading `𝗓` is moved to the end: the word
`𝗓·w[𝗒 ↦ 𝗒𝗓]` read backwards is `𝗓·w^{rev}[𝗒 ↦ 𝗒𝗓]`. -/
theorem reverse_cons_z_flatMap_addLeftSubst (w : List SlopeLetter) :
    (SlopeLetter.z :: w.flatMap addLeftSubst).reverse
      = .z :: w.reverse.flatMap addLeftSubst := by
  induction w with
  | nil => rfl
  | cons x w ih =>
    rw [List.reverse_cons] at ih
    rw [List.flatMap_cons, List.reverse_cons, List.reverse_append, List.reverse_cons,
      List.flatMap_append, ← List.cons_append, ← ih]
    cases x <;> simp [addLeftSubst]

/-- `HJO.Mellit.slopeWord_add_left` read in the order in which the letters act: a `𝗓` acts first,
and every `𝗒` is followed by a `𝗓`. -/
theorem reverse_slopeWord_add_left {m n : ℕ} (hc : Nat.Coprime m n) (hm : 1 ≤ m) (hn : 1 ≤ n) :
    (slopeWord (m + n) n).reverse = .z :: (slopeWord m n).reverse.flatMap addLeftSubst := by
  rw [slopeWord_add_left hc hm hn, reverse_cons_z_flatMap_addLeftSubst]

end HJO.Mellit

namespace HJO.Sweep

open Mellit (SlopeLetter)

variable {L : Type*} [Field L] [Algebra ℚ L] {q u : L}

/-! ### The whole-space operator of Mellit's `N` -/

/-- **An operator realising Mellit's `N` on `V_0 ⊕ V_1 ⊕ V_2`**, over a given operator `∇` on `Λ`.

`N = (1 1; 0 1)` fixes the `d_-, d^*_+`-part of the algebra and sends the bidegree `(m,n)` to
`(m+n,n)`. On `V_*` it is realised by an operator `𝒩'` with `𝒩'L = N(L)𝒩'`, which on `V_0` is
`∇`. The four clauses are what the slope word at grading one reads:

* `map_C`: on `V_0 = Λ` the operator is `∇`;
* `map_dplusStar`, `map_dminus`: it commutes with `d^*_+` out of `V_0` and `V_1` and with `d_-`
  out of `V_1` and `V_2`, so in particular with `z_1` on `V_1`
  (`HJO.Sweep.IsNOperator.map_zop_one`);
* `map_auxVar_mul`: it carries multiplication by `y_1` on `V_1` to `(qu)^{-1}z_1y_1`, the shear of
  the letter `𝗒` into `𝗒𝗓`. -/
structure IsNOperator (q u : L) (nabla : Module.End L (Sym.Lambda L))
    (Nt : Module.End L (Total L)) : Prop where
  /-- On `V_0` the operator is `∇`. -/
  map_C : ∀ f : Sym.Lambda L, Nt (MvPolynomial.C f) = MvPolynomial.C (nabla f)
  /-- `𝒩'd^*_+ = d^*_+𝒩'` out of `V_0` and `V_1`. -/
  map_dplusStar : ∀ k : ℕ, k ≤ 1 → ∀ F : Total L, F ∈ piece L k →
    Nt (dplusStar q u k F) = dplusStar q u k (Nt F)
  /-- `𝒩'd_- = d_-𝒩'` out of `V_1` and `V_2`. -/
  map_dminus : ∀ k : ℕ, k ≤ 1 → ∀ F : Total L, F ∈ piece L (k + 1) →
    Nt (dminus q (k + 1) F) = dminus q (k + 1) (Nt F)
  /-- `𝒩'y_1 = (qu)^{-1}z_1y_1𝒩'` on `V_1`. -/
  map_auxVar_mul : ∀ F : Total L, F ∈ piece L 1 →
    Nt ((auxVar 1 : Total L) * F) = ((q * u)⁻¹ • zop q u 1 1) ((auxVar 1 : Total L) * Nt F)

/-- `z_1` on `V_1` is `q/(1-q)(d^*_+d_- - d_-d^*_+)`, the train being empty. -/
theorem zop_one_one_apply (q u : L) (G : Total L) :
    zop q u 1 1 G = (q / (1 - q)) • (dplusStar q u 0 (dminus q 1 G)
      - dminus q 2 (dplusStar q u 1 G)) := by
  rw [zop_one, zopOneStar, show trainUpEnd q 1 1 = 1 from Braid.trainUp_self _ _ 1, mul_one]
  simp only [LinearMap.smul_apply, LinearMap.sub_apply, Module.End.mul_apply, pow_one,
    Nat.sub_self]

/-- **`𝒩'` commutes with `z_1` on `V_1`**, `z_1` lying in the `d_-, d^*_+`-part. -/
theorem IsNOperator.map_zop_one {nabla : Module.End L (Sym.Lambda L)}
    {Nt : Module.End L (Total L)} (hN : IsNOperator q u nabla Nt) {F : Total L}
    (hF : F ∈ piece L 1) : Nt (zop q u 1 1 F) = zop q u 1 1 (Nt F) := by
  have h0 : dminus q 1 F ∈ piece L 0 := by simpa using dminus_mem_piece q 1 hF
  have h2 : dplusStar q u 1 F ∈ piece L 2 := dplusStar_mem_piece q u hF
  rw [zop_one_one_apply, zop_one_one_apply, map_smul, map_sub, hN.map_dplusStar 0 (by omega) _ h0,
    hN.map_dminus 0 (by omega) _ hF, hN.map_dminus 1 le_rfl _ h2,
    hN.map_dplusStar 1 le_rfl _ hF]

/-- Each letter of the slope operator preserves `V_1`. -/
theorem sweepLetter_mem_piece (q u : L) (x : SlopeLetter) {F : Total L} (hF : F ∈ piece L 1) :
    sweepLetter q u x F ∈ piece L 1 := by
  cases x with
  | y =>
    change (-LinearMap.mulLeft L (auxVar 1 : Total L)) F ∈ piece L 1
    rw [LinearMap.neg_apply, LinearMap.mulLeft_apply]
    exact neg_mem (mul_mem (auxVar_mem_piece le_rfl le_rfl) hF)
  | z =>
    change ((q * u)⁻¹ • zop q u 1 1) F ∈ piece L 1
    rw [LinearMap.smul_apply, zop_one]
    exact smul_mem_piece (zopOneStar_mem_piece q u le_rfl hF)

/-- A word preserves `V_1`. -/
theorem sweepWordOp_mem_piece (q u : L) :
    ∀ (t : List SlopeLetter) {F : Total L}, F ∈ piece L 1 → sweepWordOp q u t F ∈ piece L 1 := by
  intro t
  induction t with
  | nil => intro F hF; simpa [sweepWordOp_nil] using hF
  | cons x t ih =>
    intro F hF
    rw [sweepWordOp_cons, Module.End.mul_apply]
    exact ih (sweepLetter_mem_piece q u x hF)

/-- Reading a concatenation: the first word acts first. -/
theorem sweepWordOp_append (q u : L) (s t : List SlopeLetter) :
    sweepWordOp q u (s ++ t) = sweepWordOp q u t * sweepWordOp q u s := by
  simp [sweepWordOp, List.prod_append]

/-- **`𝒩'` on a letter**: it fixes `𝗓` and shears `𝗒` into `𝗒𝗓`. -/
theorem IsNOperator.map_sweepLetter {nabla : Module.End L (Sym.Lambda L)}
    {Nt : Module.End L (Total L)} (hN : IsNOperator q u nabla Nt) (x : SlopeLetter)
    {F : Total L} (hF : F ∈ piece L 1) :
    Nt (sweepLetter q u x F) = sweepWordOp q u (Mellit.addLeftSubst x) (Nt F) := by
  cases x with
  | y =>
    change Nt ((-LinearMap.mulLeft L (auxVar 1 : Total L)) F) = _
    rw [LinearMap.neg_apply, LinearMap.mulLeft_apply, map_neg, hN.map_auxVar_mul F hF]
    simp [Mellit.addLeftSubst, sweepWordOp, sweepLetter]
  | z =>
    change Nt (((q * u)⁻¹ • zop q u 1 1) F) = _
    rw [LinearMap.smul_apply, map_smul, hN.map_zop_one hF]
    simp [Mellit.addLeftSubst, sweepWordOp, sweepLetter]

/-- **`𝒩'` on a word**: the word acting on `V_1` is carried to its shear `t[𝗒 ↦ 𝗒𝗓]`. -/
theorem IsNOperator.map_sweepWordOp {nabla : Module.End L (Sym.Lambda L)}
    {Nt : Module.End L (Total L)} (hN : IsNOperator q u nabla Nt) :
    ∀ (t : List SlopeLetter) {F : Total L}, F ∈ piece L 1 →
      Nt (sweepWordOp q u t F) = sweepWordOp q u (t.flatMap Mellit.addLeftSubst) (Nt F) := by
  intro t
  induction t with
  | nil => intro F _; simp [sweepWordOp_nil]
  | cons x t ih =>
    intro F hF
    rw [sweepWordOp_cons, Module.End.mul_apply, ih (sweepLetter_mem_piece q u x hF),
      hN.map_sweepLetter x hF, List.flatMap_cons, sweepWordOp_append, Module.End.mul_apply]

/-- **`𝒩'` on the argument of the clause**: `𝒩'(y_1d^*_+Cg) = (qu)^{-1}z_1(y_1d^*_+C(∇g))`. -/
theorem IsNOperator.map_slopeArg {nabla : Module.End L (Sym.Lambda L)}
    {Nt : Module.End L (Total L)} (hN : IsNOperator q u nabla Nt) (g : Sym.Lambda L) :
    Nt (Mellit.slopeArg q u g) = sweepLetter q u .z (Mellit.slopeArg q u (nabla g)) := by
  rw [Mellit.slopeArg_def, hN.map_auxVar_mul _ (dplusStar_zero_C_mem_piece_one q u g),
    hN.map_dplusStar 0 (by omega) _ (C_mem_piece_zero g), hN.map_C, Mellit.slopeArg_def]
  rfl

/-- **The shadow of `IsNOperator` on `V_0`**: since `d_-d^*_+ = D_0` on `V_0`
(`HJO.Sweep.dop_zero_eq_dminus_dplusStar`), an operator realising `N` forces `∇` to commute with
`D_0`. This is the first clause of a Macdonald conjugator, so the hypothesis is consistent with
`HJO.Sym.IsMacdonaldConjugator` at the bottom grading. -/
theorem IsNOperator.nabla_dop_zero {nabla : Module.End L (Sym.Lambda L)}
    {Nt : Module.End L (Total L)} (hN : IsNOperator q u nabla Nt) (f : Sym.Lambda L) :
    nabla (Sym.Dop q u 0 f) = Sym.Dop q u 0 (nabla f) := by
  apply MvPolynomial.C_injective ℕ (Sym.Lambda L)
  have h1 : dplusStar q u 0 (MvPolynomial.C f : Total L) ∈ piece L (0 + 1) :=
    dplusStar_zero_C_mem_piece_one q u f
  rw [← hN.map_C, dop_zero_eq_dminus_dplusStar, hN.map_dminus 0 (by omega) _ h1,
    hN.map_dplusStar 0 (by omega) _ (C_mem_piece_zero f), hN.map_C,
    ← dop_zero_eq_dminus_dplusStar]

/-! ### The clause carried along `N` -/

/-- **The clause of `HJO.Mellit.lhsRewrite_sweepWitness`'s base case is carried along Mellit's
`N`**, given an operator realising `N` on the whole space: the clause `HJO.Mellit.LhsSlope` at a
positive coprime pair `(m,n)` implies it at `(m+n, n)`.

On `Λ`, conjugation by the Macdonald conjugator carries `Q_{m,n}` to `Q_{m+n,n}`
(`HJO.Sym.qop_add_apply_nabla`). On the sweep side `N` is the shear
`β_{m+n,n} = 𝗓·β_{m,n}[𝗒 ↦ 𝗒𝗓]` (`HJO.Mellit.slopeWord_add_left`), and `𝒩'` carries the word of
`(m,n)` to the word of `(m+n,n)` letter by letter (`HJO.Sweep.IsNOperator.map_sweepWordOp`), the
extra leading `𝗓` coming from the argument `y_1d^*_+Cf` (`HJO.Sweep.IsNOperator.map_slopeArg`).
Since `n` is unchanged the sign `(-1)^{n+1}` of the clause is unchanged. -/
theorem lhsSlope_add_left {nabla : Module.End L (Sym.Lambda L)} {Nt : Module.End L (Total L)}
    (hnab : Sym.IsMacdonaldConjugator q u nabla) (hN : IsNOperator q u nabla Nt)
    (hM : (1 - q) * (1 - u) ≠ 0) {m n : ℕ} (hmn : Nat.Coprime m n) (hm : 1 ≤ m) (hn : 1 ≤ n)
    (h : Mellit.LhsSlope q u m n) : Mellit.LhsSlope q u (m + n) n := by
  intro f
  obtain ⟨g, rfl⟩ := hnab.bijective.2 f
  have harg : Mellit.slopeArg q u g ∈ piece L 1 :=
    mul_mem (auxVar_mem_piece le_rfl le_rfl) (dplusStar_zero_C_mem_piece_one q u g)
  have hW : slopeOperator q u 1 m n (Mellit.slopeArg q u g) ∈ piece L 1 :=
    slopeOperator_mem_piece q u le_rfl harg
  have hd : Nt (dminus q 1 (slopeOperator q u 1 m n (Mellit.slopeArg q u g)))
      = dminus q 1 (Nt (slopeOperator q u 1 m n (Mellit.slopeArg q u g))) :=
    hN.map_dminus 0 (by omega) _ hW
  rw [Sym.qop_add_apply_nabla hnab hM m hm n hn g, ← hN.map_C, h g, map_smul, hd,
    slopeOperator_eq_sweepWordOp,
    hN.map_sweepWordOp _ harg, hN.map_slopeArg, slopeOperator_eq_sweepWordOp,
    Mellit.reverse_slopeWord_add_left hmn hm hn, sweepWordOp_cons,
    Module.End.mul_apply]

end HJO.Sweep
