/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.MellitLadderNonVacuum
public meta import HJO.Attr

/-! # Straightening: the mixed algebra IS spanned by `E_g·(D`-word`)`

This file settles the question `HJO.Sym.ad_elemSymm_dop`
(`HJO/Shuffle/MellitLadderNonVacuum.lean`) left open. That lemma reads

  `ad(e_n)(D_k) = -∑_{1≤s≤n} κ(e_s)·E_{n-s}D_{k+s}`,   `κ = HJO.Bglx.paramPleth`,

and its point there was negative: for `n ≥ 2` the multiplication operator `E_{n-s}` does not vanish,
so `ad(e_n)` does **not** map `HJO.Sym.DopAlgebra` into itself, the Taylor engine of
`HJO.Sym.apply_elemSymm_one_pow_mul` has no analogue off the `e_1` ray, and the whole creation side
was settled on `L[e_1]` only. What the same identity *does* supply is a rewriting rule for the
larger
algebra generated by the basic operators **together with** the multiplication operators, and the
question was whether that algebra is spanned by `E_g·(D`-word`)`.

**It is**, and unconditionally in `q` and `u`: `HJO.Sym.mixedAlgebra_toSubmodule_eq_straightSpan`.

## Why the straightening terminates

The rule to iterate is not the commutator but the Pieri rule read as an operator identity,
`HJO.Sym.dop_mul_mulLeft_elemSymm`:

  `D_k·E_{e_n} = ∑_{s ≤ n} κ(e_s)·E_{e_{n-s}}·D_{k+s}`.

This is `HJO.Sym.dop_elemSymm_mul` with nothing moved across, and the structural fact is that
**every
term on the right carries exactly one basic operator**, as the left-hand side does. So one
application of the rule moves one `D` past one `E` and creates neither a new `D` nor a longer word:
the number of pairs `(E, D)` in the wrong order strictly drops, the index of the `D` rises and the
degree of the `E` falls, and the process stops. That is the whole content, and it is why the
obstruction recorded in `HJO.Sym.ad_elemSymm_dop` is an obstruction to `ad(e_n)` preserving
`HJO.Sym.DopAlgebra` and *not* an obstruction to straightening.

The no-lengthening half is formalized: `HJO.Sym.dopList_mul_mulLeft_mem_straightSpanLen` says that
for every `g ∈ Λ` — not just `g = e_n` — the straightening of a `D`-word of length `ℓ` is a
combination of `E_h` times `D`-words of length **exactly** `ℓ`.

## What is proved

* `HJO.Sym.dop_mul_mulLeft_elemSymm` — the rule, as an identity of operators.
* `HJO.Sym.dop_mul_mulLeft_mem_oneDopSpan` — the rule at an **arbitrary** `g ∈ Λ`:
  `D_k·E_g` is a combination of `E_h·D_j`, still with one basic operator. The `e_{i+1}` generate `Λ`
  (`HJO.Sym.adjoin_elemSymm_eq_top`) and the set of `g` for which the conclusion holds at every `k`
  is a subalgebra, so `Algebra.adjoin_induction` reaches every `g`; the multiplicative step is where
  the one-`D` shape is spent.
* `HJO.Sym.mixedAlgebra_toSubmodule_eq_straightSpan` — **the straightening theorem.** The
  `L`-subalgebra of `End_L(Λ)` generated by the basic operators together with *all* multiplication
  operators equals, as a module, the span of the products `E_g·w` with `w` a `D`-word. The `≤`
  direction is `Algebra.adjoin_eq_span` plus closure of the span under right multiplication by each
  generator; the `≥` direction is that each `E_g·w` is a product of generators.
* `HJO.Sym.exists_straight_normalForm` — the same as a normal form: `A = ∑_i c_i·E_{g_i}·w_i`.
* `HJO.Sym.apply_eq_sum_vacuum`, `HJO.Sym.dopAlgebra_apply_eq_sum_vacuum`,
  `HJO.Sym.theta_apply_eq_sum_vacuum` — the consequence for **values**. Since
  `Af = (A·E_f)(1)`, straightening `A·E_f` writes `Af` as `∑_i c_i·g_i·(w_i1)`: every value of every
  operator of `HJO.Sym.DopAlgebra`, at *every* `f ∈ Λ` and not only on the `e_1` ray, is a
  combination of **vacuum** values of `D`-words. With `HJO.Sym.theta_mem_dopTwoAlgebra` this covers
  every value of every `(2,3)` slope homomorphism at every argument.

  **Read that with the caveat it deserves.** As a statement *inside* `Λ` it says nothing: the
  `Λ`-coefficients `g_i` are unconstrained, and the span of `{g·x}` over all `g` is all of `Λ`. The
  content is on the operator side — it is a normal form for `A·E_f`, and what makes a value
  computable is the normal form together with the explicit rule, not the existence statement.

## The explicit side, and the pin

The rule is run out in closed form for words of length two, which is what the base rung of the
`(2,3)` ladder is:

* `HJO.Sym.dop_dop_elemSymm_mul`, `HJO.Sym.dop_dop_apply_elemSymm` — the double sum straightening
  `D_aD_b` past `e_n`, over `s + t ≤ n`.
* `HJO.Sym.dop_dop_apply_one` — the two-letter vacuum values in `e`-monomials,
  `D_aD_b(1) = ∑_{r≤b} (-1)^{a+b+r}κ(e_r)·e_{b-r}e_{a+r}`.
* `HJO.Sym.qop_two_three_apply_elemSymm` and `HJO.Sym.qop_two_three_apply_elemSymm_closed` —
  **`Q_{2,3}(e_n)` at every `n`**, first as a double sum of two-letter vacuum values and then fully
  expanded into a triple sum of `e`-monomials with `κ`-coefficients. This is a
  computation off the `e_1` ray: at `n = 2` it is `Q_{2,3}(e_2)`, at every `n` it is
  `Q_{2,3}(e_n)`, and nothing in it is a `(2,3)`-specific trick.
* `HJO.Sym.qop_two_three_apply_elemSymm_pin` — **the pin.** The general formula read at `n = 1`,
  evaluated by this file's machinery alone, lands on the polynomial
  `-e_1^2e_2 + Me_2^2 + (1-q-u+(q+u)M)e_1e_3 + (q^2+qu+u^2-1)Me_4`, which is verbatim the
  right-hand side of `HJO.Sym.qop_two_three_apply_elemSymm_one`
  (`HJO/Shuffle/MellitQopThreeFour.lean`), obtained there by grinding the commutator of
  `HJO.Sym.Qop`. All four coefficients agree, the `e_4` one included.
  `HJO.Sym.qop_two_three_apply_elemSymm_pin_agrees` additionally equates the straightening normal
  form with the shift-step route's expression `e_1Q_{2,3}(1) - D_3(e_1) + D_1(e_3)` of
  `HJO.Sym.qop_two_three_apply_elemSymm_one_of_shiftStep`.

## What is *not* obtained

* **No `hlhs` clause at general `α`.** Nothing here touches the equation that clause asserts. This
  file computes one side of it, and removes the restriction to one ray; the creation side and the
  equality between them are untouched.
* **No closed form for `Q_{2k,3k}(e_n)` at general `k`.** The straightening theorem says the
  value is
  a combination of vacuum values of `D`-words, and
  `HJO.Sym.dopList_mul_mulLeft_mem_straightSpanLen` says which lengths occur, but the explicit
  expansion is carried out only for words of length two, i.e. for `k = 1`. The `ℓ`-fold sum is
  written below only as a term count, in prose, and is not formalized.
* **The term count is paper arithmetic, not a theorem here.** Straightening
  `D_{k_1}···D_{k_ℓ}` past `E_{e_n}` produces exactly the terms indexed by `(s_1,…,s_ℓ)` with
  `s_i ≥ 0` and `∑_i s_i ≤ n` — coefficient `∏_i κ(e_{s_i})`, multiplication operator
  `E_{e_{n-∑s}}`, word `D_{k_1+s_1}···D_{k_ℓ+s_ℓ}` — hence `binom(n+ℓ, ℓ)` terms: `ℓ+1` at `n = 1`,
  `(ℓ+1)(ℓ+2)/2` at `n = 2`, polynomial in `ℓ` at each fixed `n`. Only the length statement is
  formalized; the count is not.

## Genericity

No definition in this file contains an inverse, so no letter here degenerates to the zero map, and
every span and every membership statement is a statement about the same operators at every `q, u`.

* **Unconditional in `q` and `u`** — everything except the three items below. In particular
  `HJO.Sym.mixedAlgebra_toSubmodule_eq_straightSpan`, `HJO.Sym.dop_mul_mulLeft_mem_oneDopSpan`,
  `HJO.Sym.exists_straight_normalForm`, `HJO.Sym.apply_eq_sum_vacuum`,
  `HJO.Sym.dop_dop_apply_one`, `HJO.Sym.dopList_mul_mulLeft_mem_straightSpanLen`,
  `HJO.Sym.qop_two_three_apply_elemSymm` and `HJO.Sym.qop_two_three_apply_elemSymm_closed`: the
  last two carry `HJO.Sym.Qop`'s own `M⁻¹` in the statement rather than cancelling it, so at `M = 0`
  they read `0 = 0`, which is that definition's totalisation and not a false clause.
* `HJO.Sym.qop_two_three_apply_elemSymm_pin` and
  `HJO.Sym.qop_two_three_apply_elemSymm_pin_agrees`: `M = (1-q)(1-u) ≠ 0`, and nothing else, spent
  on the single cancellation `M⁻¹M = 1` that turns the bracket into a polynomial. `M ≠ 0` is `q ≠ 1`
  and `u ≠ 1`, and holds at algebraically independent `q, u`.
* `HJO.Sym.theta_apply_eq_sum_vacuum`: `CharZero L`, `qu ≠ 0` and `(qu)^{j+1} ≠ 1` for every `j` —
  verbatim `HJO.Sym.theta_mem_dopTwoAlgebra`'s, i.e. the free generation of `Λ` by the axis
  generators, without which `Θf` is not determined at all.

## References

This file concerns `HJO.Sym.DopInt`, `HJO.Sym.Qop`, `HJO.Sym.DopAlgebra`, `HJO.Sym.IsSlopeHom`,
`HJO.Sym.plethShift`, `HJO.Sym.dop_elemSymm_one_mul`, `HJO.Sym.coprime_ladder`.
-/

@[expose] public section

namespace HJO.Sym

open HJO.Bglx HJO.DiffOrder

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- **The `D`-words**: the multiplicative submonoid of `End_L(Λ)` generated by the basic operators
of `HJO.Sym.DopInt`, i.e. the products `D_{k_1}···D_{k_ℓ}` including the empty one. -/
noncomputable def dopMonoid (q u : L) : Submonoid (Module.End L (Lambda L)) :=
  Submonoid.closure (Set.range (Dop q u))

/-- Each basic operator is a `D`-word. -/
theorem dop_mem_dopMonoid (q u : L) (k : ℕ) : Dop q u k ∈ dopMonoid q u :=
  Submonoid.subset_closure (Set.mem_range_self k)

/-- The span of `E_g·D_j` — a multiplication operator times **one** basic operator. This is where
the straightening rule lands, and that it lands here rather than in a span of longer words is what
makes the iteration terminate. -/
noncomputable def oneDopSpan (q u : L) : Submodule L (Module.End L (Lambda L)) :=
  Submodule.span L
    {A | ∃ (g : Lambda L) (j : ℕ), A = LinearMap.mulLeft L g * Dop q u j}

/-- **The straightened span**: the `L`-span of the products `E_g·w`, `g ∈ Λ` and `w` a `D`-word.
Every multiplication operator stands to the left of every basic operator. -/
noncomputable def straightSpan (q u : L) : Submodule L (Module.End L (Lambda L)) :=
  Submodule.span L
    {A | ∃ (g : Lambda L), ∃ w ∈ dopMonoid q u, A = LinearMap.mulLeft L g * w}

/-- **The mixed algebra**: the `L`-subalgebra of `End_L(Λ)` generated by the basic operators of
`HJO.Sym.DopInt` together with *all* the multiplication operators `E_g`, `g ∈ Λ`. It contains
`HJO.Sym.DopAlgebra` (`HJO.Sym.dopAlgebra_le_mixedAlgebra`), so it contains the image of every
`(2,3)` slope homomorphism. -/
noncomputable def mixedAlgebra (q u : L) : Subalgebra L (Module.End L (Lambda L)) :=
  Algebra.adjoin L (Set.range (Dop q u) ∪ Set.range fun g : Lambda L => LinearMap.mulLeft L g)

/-! ### Elementary algebra of the multiplication operators -/

omit [Algebra ℚ L] in
/-- The multiplication operators form a commutative image of `Λ`: composing two of them multiplies
the functions. -/
theorem mulLeft_mul_mulLeft (g h : Lambda L) :
    LinearMap.mulLeft L g * LinearMap.mulLeft L h = LinearMap.mulLeft L (g * h) := by
  ext f; simp [Module.End.mul_apply]

omit [Algebra ℚ L] in
/-- Multiplication by a scalar of `L` is that scalar acting on the identity operator. -/
theorem mulLeft_algebraMap (r : L) :
    LinearMap.mulLeft L (algebraMap L (Lambda L) r) = r • (1 : Module.End L (Lambda L)) := by
  ext f; simp [Algebra.smul_def]

omit [Algebra ℚ L] in
/-- The multiplication operator is additive in the function. -/
theorem mulLeft_add' (g h : Lambda L) :
    LinearMap.mulLeft L (g + h) = LinearMap.mulLeft L g + LinearMap.mulLeft L h := by
  ext f; simp [add_mul]

/-! ### The two spans, and what they are closed under -/

/-- Left multiplication by a multiplication operator preserves `HJO.Sym.oneDopSpan`. -/
theorem mulLeft_mul_mem_oneDopSpan (q u : L) (g : Lambda L) {A : Module.End L (Lambda L)}
    (hA : A ∈ oneDopSpan q u) : LinearMap.mulLeft L g * A ∈ oneDopSpan q u := by
  induction hA using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, j, rfl⟩ := hx
    rw [← mul_assoc, mulLeft_mul_mulLeft]
    exact Submodule.subset_span ⟨g * h, j, rfl⟩
  | zero => rw [mul_zero]; exact zero_mem _
  | add x y _ _ ihx ihy => rw [mul_add]; exact add_mem ihx ihy
  | smul a x _ ih => rw [mul_smul_comm]; exact Submodule.smul_mem _ a ih

/-- Left multiplication by a multiplication operator preserves the straightened span: the two
multiplication operators merge. -/
theorem mulLeft_mul_mem_straightSpan (q u : L) (g : Lambda L) {A : Module.End L (Lambda L)}
    (hA : A ∈ straightSpan q u) : LinearMap.mulLeft L g * A ∈ straightSpan q u := by
  induction hA using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, w, hw, rfl⟩ := hx
    rw [← mul_assoc, mulLeft_mul_mulLeft]
    exact Submodule.subset_span ⟨g * h, w, hw, rfl⟩
  | zero => rw [mul_zero]; exact zero_mem _
  | add x y _ _ ihx ihy => rw [mul_add]; exact add_mem ihx ihy
  | smul a x _ ih => rw [mul_smul_comm]; exact Submodule.smul_mem _ a ih

/-- One basic operator is a `D`-word of length one. -/
theorem oneDopSpan_le_straightSpan (q u : L) : oneDopSpan q u ≤ straightSpan q u := by
  rw [oneDopSpan, Submodule.span_le]
  rintro x ⟨g, j, rfl⟩
  exact Submodule.subset_span ⟨g, Dop q u j, dop_mem_dopMonoid q u j, rfl⟩

/-- Right multiplication by a `D`-word preserves the straightened span: the words concatenate and no
straightening is needed. -/
theorem straightSpan_mul_dopMonoid (q u : L) {A w : Module.End L (Lambda L)}
    (hA : A ∈ straightSpan q u) (hw : w ∈ dopMonoid q u) : A * w ∈ straightSpan q u := by
  induction hA using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, v, hv, rfl⟩ := hx
    rw [mul_assoc]
    exact Submodule.subset_span ⟨h, v * w, mul_mem hv hw, rfl⟩
  | zero => rw [zero_mul]; exact zero_mem _
  | add x y _ _ ihx ihy => rw [add_mul]; exact add_mem ihx ihy
  | smul a x _ ih => rw [smul_mul_assoc]; exact Submodule.smul_mem _ a ih

/-- The identity operator is straightened: `E_1` times the empty word. -/
theorem one_mem_straightSpan (q u : L) : (1 : Module.End L (Lambda L)) ∈ straightSpan q u := by
  refine Submodule.subset_span ⟨1, 1, one_mem _, ?_⟩
  rw [mul_one, LinearMap.mulLeft_one]; rfl

/-- A multiplication operator is straightened: itself times the empty word. -/
theorem mulLeft_mem_straightSpan (q u : L) (g : Lambda L) :
    LinearMap.mulLeft L g ∈ straightSpan q u :=
  Submodule.subset_span ⟨g, 1, one_mem _, (mul_one _).symm⟩

/-- A basic operator is `E_1` times itself. -/
theorem dop_mem_oneDopSpan (q u : L) (k : ℕ) : Dop q u k ∈ oneDopSpan q u := by
  refine Submodule.subset_span ⟨1, k, ?_⟩
  rw [LinearMap.mulLeft_one]; exact (one_mul _).symm

/-! ### The straightening rule -/

/-- **The straightening rule.** `D_k·E_{e_n} = ∑_{s≤n} κ(e_s)·E_{e_{n-s}}·D_{k+s}`, with
`κ = HJO.Bglx.paramPleth`. This is `HJO.Sym.dop_elemSymm_mul` read as an identity of operators, with
nothing moved across — unlike `HJO.Sym.ad_elemSymm_dop`, which subtracts the `s = 0` term to make a
commutator and thereby hides the one fact that matters: **each term carries exactly one basic
operator**, as the left-hand side does. So the rule moves a `D` past an `E` without creating a `D`
and without lengthening the word, and iterating it terminates. Unconditional in `q` and `u`. -/
theorem dop_mul_mulLeft_elemSymm (q u : L) (k n : ℕ) :
    Dop q u k * LinearMap.mulLeft L (elemSymm L n)
      = ∑ s ∈ Finset.range (n + 1), paramPleth q u (elemSymm L s) •
          (LinearMap.mulLeft L (elemSymm L (n - s)) * Dop q u (k + s)) := by
  refine LinearMap.ext fun f => ?_
  simp only [Module.End.mul_apply, LinearMap.mulLeft_apply, LinearMap.sum_apply,
    LinearMap.smul_apply]
  exact dop_elemSymm_mul q u k n f

/-- The multiplicative step of the induction below: if a single `E_g` can be straightened past every
basic operator, it can be straightened past anything already in `HJO.Sym.oneDopSpan`. -/
private theorem oneDopSpan_mul_mulLeft_aux (q u : L) {g : Lambda L}
    (hg : ∀ k, Dop q u k * LinearMap.mulLeft L g ∈ oneDopSpan q u)
    {A : Module.End L (Lambda L)} (hA : A ∈ oneDopSpan q u) :
    A * LinearMap.mulLeft L g ∈ oneDopSpan q u := by
  induction hA using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, j, rfl⟩ := hx
    rw [mul_assoc]
    exact mulLeft_mul_mem_oneDopSpan q u h (hg j)
  | zero => rw [zero_mul]; exact zero_mem _
  | add x y _ _ ihx ihy => rw [add_mul]; exact add_mem ihx ihy
  | smul a x _ ih => rw [smul_mul_assoc]; exact Submodule.smul_mem _ a ih

/-- **The straightening rule at an arbitrary `g ∈ Λ`**: `D_k·E_g` is an `L`-combination of `E_h·D_j`
— still with one basic operator per term, so the rule has not grown in passing from the generators
of `Λ` to all of `Λ`.

The `e_{i+1}` generate `Λ` (`HJO.Sym.adjoin_elemSymm_eq_top`), and the set of `g` satisfying the
conclusion at every `k` is a subalgebra: the sum and scalar steps are the additivity of
`HJO.Sym.mulLeft_add'`, and the product step factors `E_{gg'} = E_gE_{g'}` and applies the two
hypotheses in turn, which is exactly where the one-`D` shape of `HJO.Sym.dop_mul_mulLeft_elemSymm`
is spent. Unconditional in `q` and `u`. -/
theorem dop_mul_mulLeft_mem_oneDopSpan (q u : L) (g : Lambda L) (k : ℕ) :
    Dop q u k * LinearMap.mulLeft L g ∈ oneDopSpan q u := by
  have hg : g ∈ Algebra.adjoin L (Set.range fun i : ℕ => elemSymm L (i + 1)) := by
    rw [adjoin_elemSymm_eq_top]; exact Algebra.mem_top
  revert k
  induction hg using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    intro k
    rw [dop_mul_mulLeft_elemSymm]
    exact Submodule.sum_mem _ fun s _ =>
      Submodule.smul_mem _ _ (Submodule.subset_span ⟨_, _, rfl⟩)
  | algebraMap r =>
    intro k
    rw [mulLeft_algebraMap, mul_smul_comm, mul_one]
    exact Submodule.smul_mem _ _ (dop_mem_oneDopSpan q u k)
  | add x y _ _ ihx ihy =>
    intro k
    rw [mulLeft_add', mul_add]
    exact add_mem (ihx k) (ihy k)
  | mul x y _ _ ihx ihy =>
    intro k
    rw [← mulLeft_mul_mulLeft, ← mul_assoc]
    exact oneDopSpan_mul_mulLeft_aux q u ihy (ihx k)

/-! ### From one basic operator to a whole word -/

/-- Left multiplication by a basic operator preserves the straightened span. -/
theorem dop_mul_mem_straightSpan (q u : L) (k : ℕ) {A : Module.End L (Lambda L)}
    (hA : A ∈ straightSpan q u) : Dop q u k * A ∈ straightSpan q u := by
  induction hA using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨g, w, hw, rfl⟩ := hx
    rw [← mul_assoc]
    exact straightSpan_mul_dopMonoid q u
      (oneDopSpan_le_straightSpan q u (dop_mul_mulLeft_mem_oneDopSpan q u g k)) hw
  | zero => rw [mul_zero]; exact zero_mem _
  | add x y _ _ ihx ihy => rw [mul_add]; exact add_mem ihx ihy
  | smul a x _ ih => rw [mul_smul_comm]; exact Submodule.smul_mem _ a ih

/-- Left multiplication by a whole `D`-word preserves the straightened span. -/
theorem dopMonoid_mul_mem_straightSpan (q u : L) {w : Module.End L (Lambda L)}
    (hw : w ∈ dopMonoid q u) {A : Module.End L (Lambda L)} (hA : A ∈ straightSpan q u) :
    w * A ∈ straightSpan q u := by
  rw [dopMonoid] at hw
  induction hw using Submonoid.closure_induction generalizing A with
  | mem x hx => obtain ⟨k, rfl⟩ := hx; exact dop_mul_mem_straightSpan q u k hA
  | one => rwa [one_mul]
  | mul x y _ _ ihx ihy => rw [mul_assoc]; exact ihx (ihy hA)

/-- **Straightening one multiplication operator past a whole `D`-word.** Induction on the word,
with `HJO.Sym.dop_mul_mulLeft_mem_oneDopSpan` at a single letter. Unconditional. -/
theorem dopMonoid_mul_mulLeft_mem_straightSpan (q u : L) {w : Module.End L (Lambda L)}
    (hw : w ∈ dopMonoid q u) (g : Lambda L) :
    w * LinearMap.mulLeft L g ∈ straightSpan q u := by
  rw [dopMonoid] at hw
  induction hw using Submonoid.closure_induction generalizing g with
  | mem x hx =>
    obtain ⟨k, rfl⟩ := hx
    exact oneDopSpan_le_straightSpan q u (dop_mul_mulLeft_mem_oneDopSpan q u g k)
  | one => rw [one_mul]; exact mulLeft_mem_straightSpan q u g
  | mul x y hx _ ihx ihy =>
    rw [mul_assoc]
    exact dopMonoid_mul_mem_straightSpan q u (by rw [dopMonoid]; exact hx) (ihy g)

/-- Right multiplication by a multiplication operator preserves the straightened span. With
`HJO.Sym.straightSpan_mul_dopMonoid` this is closure under right multiplication by every generator
of the mixed algebra. -/
theorem straightSpan_mul_mulLeft (q u : L) {A : Module.End L (Lambda L)}
    (hA : A ∈ straightSpan q u) (g : Lambda L) :
    A * LinearMap.mulLeft L g ∈ straightSpan q u := by
  induction hA using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, w, hw, rfl⟩ := hx
    rw [mul_assoc]
    exact mulLeft_mul_mem_straightSpan q u h (dopMonoid_mul_mulLeft_mem_straightSpan q u hw g)
  | zero => rw [zero_mul]; exact zero_mem _
  | add x y _ _ ihx ihy => rw [add_mul]; exact add_mem ihx ihy
  | smul a x _ ih => rw [smul_mul_assoc]; exact Submodule.smul_mem _ a ih

/-! ### The straightening theorem -/

/-- Closure of the straightened span under right multiplication by any product of generators. The
product step is the reason the induction is run on the right-hand factor. -/
private theorem straightSpan_mul_closure (q u : L) {y : Module.End L (Lambda L)}
    (hy : y ∈ Submonoid.closure
      (Set.range (Dop q u) ∪ Set.range fun g : Lambda L => LinearMap.mulLeft L g))
    {A : Module.End L (Lambda L)} (hA : A ∈ straightSpan q u) : A * y ∈ straightSpan q u := by
  induction hy using Submonoid.closure_induction generalizing A with
  | mem x hx =>
    rcases hx with ⟨k, rfl⟩ | ⟨g, rfl⟩
    · exact straightSpan_mul_dopMonoid q u hA (dop_mem_dopMonoid q u k)
    · exact straightSpan_mul_mulLeft q u hA g
  | one => rwa [mul_one]
  | mul x y _ _ ihx ihy => rw [← mul_assoc]; exact ihy (ihx hA)

/-- **The straightening theorem.** The mixed algebra, as an `L`-module, is exactly the span of the
products `E_g·w` with `w` a `D`-word: every element of the algebra generated by the basic operators
and the multiplication operators can be straightened so that all multiplication operators stand to
the left of all basic operators.

`Algebra.adjoin_eq_span` turns the `≤` direction into a statement about products of generators, and
`HJO.Sym.straightSpan_mul_closure` discharges it from closure under right multiplication by one
generator at a time — `HJO.Sym.straightSpan_mul_dopMonoid` for a basic operator,
`HJO.Sym.straightSpan_mul_mulLeft` for a multiplication operator, the latter resting on the
straightening rule. The `≥` direction is that `E_g·w` is a product of generators.

Unconditional in `q` and `u`; neither side of the equality mentions an inverse. -/
theorem mixedAlgebra_toSubmodule_eq_straightSpan (q u : L) :
    Subalgebra.toSubmodule (mixedAlgebra q u) = straightSpan q u := by
  refine le_antisymm ?_ ?_
  · rw [mixedAlgebra, Algebra.adjoin_eq_span, Submodule.span_le]
    intro y hy
    have h := straightSpan_mul_closure q u hy (one_mem_straightSpan q u)
    rwa [one_mul] at h
  · have hword : dopMonoid q u ≤ (mixedAlgebra q u).toSubmonoid := by
      rw [dopMonoid]
      exact Submonoid.closure_le.2 fun x hx => Algebra.subset_adjoin (Or.inl hx)
    rw [straightSpan, Submodule.span_le]
    rintro x ⟨g, w, hw, rfl⟩
    exact (Subalgebra.mem_toSubmodule _).2
      (mul_mem (Algebra.subset_adjoin (Or.inr ⟨g, rfl⟩)) (hword hw))

/-! ### The normal form, and values at a general argument -/

/-- `HJO.Sym.DopAlgebra` sits inside the mixed algebra. -/
theorem dopAlgebra_le_mixedAlgebra (q u : L) : DopAlgebra q u ≤ mixedAlgebra q u := by
  rw [DopAlgebra]
  exact Algebra.adjoin_le fun x hx => Algebra.subset_adjoin (Or.inl hx)

/-- Every multiplication operator is in the mixed algebra, by construction. -/
theorem mulLeft_mem_mixedAlgebra (q u : L) (g : Lambda L) :
    LinearMap.mulLeft L g ∈ mixedAlgebra q u :=
  Algebra.subset_adjoin (Or.inr ⟨g, rfl⟩)

/-- **The normal form.** Every element of the mixed algebra is a finite `L`-combination
`∑_i c_i·E_{g_i}·w_i` with each `w_i` a `D`-word. This is
`HJO.Sym.mixedAlgebra_toSubmodule_eq_straightSpan` unpacked through `Submodule.mem_span_set'`;
it is an existence statement, and the computation of the `c_i, g_i, w_i` is what
`HJO.Sym.dop_mul_mulLeft_elemSymm` supplies. Unconditional. -/
theorem exists_straight_normalForm (q u : L) {A : Module.End L (Lambda L)}
    (hA : A ∈ mixedAlgebra q u) :
    ∃ (n : ℕ) (c : Fin n → L) (g : Fin n → Lambda L) (w : Fin n → Module.End L (Lambda L)),
      (∀ i, w i ∈ dopMonoid q u) ∧ A = ∑ i, c i • (LinearMap.mulLeft L (g i) * w i) := by
  have hA' : A ∈ straightSpan q u := by
    rw [← mixedAlgebra_toSubmodule_eq_straightSpan]
    exact (Subalgebra.mem_toSubmodule _).2 hA
  rw [straightSpan] at hA'
  obtain ⟨n, c, x, hx⟩ := Submodule.mem_span_set'.1 hA'
  choose g w hw hxw using fun i => (x i).2
  refine ⟨n, c, g, w, hw, ?_⟩
  rw [← hx]
  exact Finset.sum_congr rfl fun i _ => by rw [hxw i]

/-- **Every value is a combination of vacuum values.** For `A` in the mixed algebra and any
`f ∈ Λ`, `Af = ∑_i c_i·g_i·(w_i1)` with each `w_i` a `D`-word: apply the normal form to `A·E_f`,
which is again in the mixed algebra, and read it at the vacuum, using `Af = (A·E_f)(1)`.

Note what the statement is and is not. Inside `Λ` it asserts nothing — the coefficients `g_i` are
arbitrary elements of `Λ` and such combinations exhaust `Λ`. The content is the normal form for the
*operator* `A·E_f`, and it is the explicit rule, not this existence statement, that computes a
value. Unconditional in `q` and `u`. -/
theorem apply_eq_sum_vacuum (q u : L) {A : Module.End L (Lambda L)}
    (hA : A ∈ mixedAlgebra q u) (f : Lambda L) :
    ∃ (n : ℕ) (c : Fin n → L) (g : Fin n → Lambda L) (w : Fin n → Module.End L (Lambda L)),
      (∀ i, w i ∈ dopMonoid q u) ∧ A f = ∑ i, c i • (g i * w i 1) := by
  obtain ⟨n, c, g, w, hw, heq⟩ :=
    exists_straight_normalForm q u (mul_mem hA (mulLeft_mem_mixedAlgebra q u f))
  refine ⟨n, c, g, w, hw, ?_⟩
  have h1 : (A * LinearMap.mulLeft L f) 1 = A f := by
    rw [Module.End.mul_apply, LinearMap.mulLeft_apply, mul_one]
  rw [← h1, heq]
  simp only [LinearMap.sum_apply, LinearMap.smul_apply, Module.End.mul_apply,
    LinearMap.mulLeft_apply]

/-- The same for an operator of `HJO.Sym.DopAlgebra`, at **every** argument — not only on the `e_1`
ray of `HJO.Sym.apply_elemSymm_one_pow_mul`. Unconditional. -/
theorem dopAlgebra_apply_eq_sum_vacuum (q u : L) {A : Module.End L (Lambda L)}
    (hA : A ∈ DopAlgebra q u) (f : Lambda L) :
    ∃ (n : ℕ) (c : Fin n → L) (g : Fin n → Lambda L) (w : Fin n → Module.End L (Lambda L)),
      (∀ i, w i ∈ dopMonoid q u) ∧ A f = ∑ i, c i • (g i * w i 1) :=
  apply_eq_sum_vacuum q u (dopAlgebra_le_mixedAlgebra q u hA) f

/-- **The whole creation side, at every argument.** For every value `Θf` of a `(2,3)` slope
homomorphism and every `h ∈ Λ`, `Θf(h)` is a finite combination of vacuum values of `D`-words with
coefficients in `Λ`. This is `HJO.Sym.theta_mem_dopTwoAlgebra` composed with
`HJO.Sym.dopAlgebra_apply_eq_sum_vacuum`, and it removes the restriction to `L[e_1]` that
`HJO.Sym.theta_apply_elemSymm_one_pow` carried.

It does **not** prove the `hlhs` clause at general `α`: nothing here says anything about the
equation that clause asserts, only about one side of it.

Genericity: `CharZero L`, `qu ≠ 0` and `(qu)^{j+1} ≠ 1` for every `j`, verbatim
`HJO.Sym.theta_mem_dopTwoAlgebra`'s and needed there for `Θ` to be determined at all. Nothing is
spent on `M`. -/
theorem theta_apply_eq_sum_vacuum [CharZero L] {q u : L} (hv0 : q * u ≠ 0)
    (hv1 : ∀ j : ℕ, (q * u) ^ (j + 1) ≠ 1)
    {Θ : Lambda L →ₐ[L] Module.End L (Lambda L)} (hΘ : IsSlopeHom 2 3 q u Θ) (f h : Lambda L) :
    ∃ (n : ℕ) (c : Fin n → L) (g : Fin n → Lambda L) (w : Fin n → Module.End L (Lambda L)),
      (∀ i, w i ∈ dopMonoid q u) ∧ (Θ f) h = ∑ i, c i • (g i * w i 1) :=
  dopAlgebra_apply_eq_sum_vacuum q u
    (dopTwoAlgebra_le_dopAlgebra q u (theta_mem_dopTwoAlgebra hv0 hv1 hΘ f)) h

/-! ### Straightening a two-letter word, explicitly -/

/-- **The straightening rule run twice**: `D_aD_b` past `e_n`,

`D_aD_b(e_nf) = ∑_{s+t≤n} κ(e_s)κ(e_t)·e_{n-s-t}·D_{a+t}D_{b+s}f`.

Two letters in, two letters out — the length is unchanged and the shifts are independent, one per
letter. Unconditional in `q` and `u`. -/
theorem dop_dop_elemSymm_mul (q u : L) (a b n : ℕ) (f : Lambda L) :
    Dop q u a (Dop q u b (elemSymm L n * f))
      = ∑ s ∈ Finset.range (n + 1), ∑ t ∈ Finset.range (n - s + 1),
          (paramPleth q u (elemSymm L s) * paramPleth q u (elemSymm L t)) •
            (elemSymm L (n - s - t) * Dop q u (a + t) (Dop q u (b + s) f)) := by
  rw [dop_elemSymm_mul, map_sum]
  refine Finset.sum_congr rfl fun s _ => ?_
  rw [map_smul, dop_elemSymm_mul, Finset.smul_sum]
  exact Finset.sum_congr rfl fun t _ => by rw [smul_smul]

/-- The previous rule at `f = 1`, which is the shape a value at `e_n` needs. -/
theorem dop_dop_apply_elemSymm (q u : L) (a b n : ℕ) :
    Dop q u a (Dop q u b (elemSymm L n))
      = ∑ s ∈ Finset.range (n + 1), ∑ t ∈ Finset.range (n - s + 1),
          (paramPleth q u (elemSymm L s) * paramPleth q u (elemSymm L t)) •
            (elemSymm L (n - s - t) * Dop q u (a + t) (Dop q u (b + s) 1)) := by
  have h := dop_dop_elemSymm_mul q u a b n (1 : Lambda L)
  rwa [mul_one] at h

/-- `HJO.Sym.DopInt` at the vacuum with the sign carried as a scalar of `L` rather than of `Λ`,
which is the
spelling the sums below need. -/
theorem dop_apply_one_smul (q u : L) (k : ℕ) :
    Dop q u k (1 : Lambda L) = ((-1 : L) ^ k) • elemSymm L k := by
  rw [dop_apply_one, Algebra.smul_def, map_pow, map_neg, map_one]

/-- **Two-letter vacuum values in closed form**:

`D_aD_b(1) = ∑_{r≤b} (-1)^{a+b+r}κ(e_r)·e_{b-r}e_{a+r}`.

One Pieri rule on top of `HJO.Sym.DopInt` at the vacuum. Unconditional in `q` and `u`. -/
theorem dop_dop_apply_one (q u : L) (a b : ℕ) :
    Dop q u a (Dop q u b 1)
      = ∑ r ∈ Finset.range (b + 1), ((-1 : L) ^ (a + b + r) * paramPleth q u (elemSymm L r)) •
          (elemSymm L (b - r) * elemSymm L (a + r)) := by
  rw [dop_apply_one_smul, map_smul, show elemSymm L b = elemSymm L b * 1 from (mul_one _).symm,
    dop_elemSymm_mul, Finset.smul_sum]
  refine Finset.sum_congr rfl fun r _ => ?_
  rw [dop_apply_one_smul, mul_smul_comm, smul_smul, smul_smul]
  congr 1
  ring

/-! ### `Q_{2,3}` at every elementary symmetric function -/

/-- **`Q_{2,3}(e_n)` at every `n`**, as a double sum of two-letter vacuum values.

`HJO.Sym.Qop` at the coprime slope `(2,3)` is the normalised bracket `M⁻¹(D_2D_1 - D_1D_2)`
(`HJO.Sym.qop_two_three_eq_bracket_dop`), and `HJO.Sym.dop_dop_apply_elemSymm` straightens each half
past `e_n` with the *same* coefficients and the *same* leftover `e_{n-s-t}`, so the two double sums
combine term by term into a bracket of shifted words.

This is a value off the `e_1` ray: at `n = 2` it is `Q_{2,3}(e_2)`, and there is no
`n`-specific input. Unconditional in `q` and `u` — `HJO.Sym.Qop`'s own `M⁻¹` is carried in the
statement, so at `M = 0` both sides are zero. -/
theorem qop_two_three_apply_elemSymm (q u : L) (n : ℕ) :
    Qop q u 2 3 (elemSymm L n)
      = ((1 - q) * (1 - u))⁻¹ • ∑ s ∈ Finset.range (n + 1), ∑ t ∈ Finset.range (n - s + 1),
          (paramPleth q u (elemSymm L s) * paramPleth q u (elemSymm L t)) •
            (elemSymm L (n - s - t) *
              (Dop q u (2 + t) (Dop q u (1 + s) 1) - Dop q u (1 + t) (Dop q u (2 + s) 1))) := by
  rw [qop_two_three_eq_bracket_dop]
  simp only [LinearMap.smul_apply, LinearMap.sub_apply, Module.End.mul_apply]
  congr 1
  rw [dop_dop_apply_elemSymm, dop_dop_apply_elemSymm, ← Finset.sum_sub_distrib]
  refine Finset.sum_congr rfl fun s _ => ?_
  rw [← Finset.sum_sub_distrib]
  exact Finset.sum_congr rfl fun t _ => by rw [← smul_sub, ← mul_sub]

/-! ### The pin at `n = 1` -/

/-- `D_2D_1(1) = -e_1e_2 + Me_3`, from `HJO.Sym.dop_dop_apply_one` at `(a,b) = (2,1)`. -/
theorem dop_two_dop_one_apply_one (q u : L) :
    Dop q u 2 (Dop q u 1 (1 : Lambda L))
      = -(elemSymm L 1 * elemSymm L 2) + ((1 - q) * (1 - u)) • elemSymm L 3 := by
  rw [dop_dop_apply_one]
  norm_num only [Finset.sum_range_succ, Finset.sum_range_zero, paramPleth_elemSymm_zero,
    paramPleth_elemSymm_one_eq, elemSymm_zero, zero_add, one_mul, mul_one]
  simp only [MvPolynomial.smul_eq_C_mul, map_sub, map_mul, map_neg, map_one]
  ring

/-- `D_1D_2(1) = -e_1e_2 + Me_1e_2 + (q+u)Me_3`, from `HJO.Sym.dop_dop_apply_one` at `(1,2)`. The
`κ(e_2)` coefficient is read here. -/
theorem dop_one_dop_two_apply_one (q u : L) :
    Dop q u 1 (Dop q u 2 (1 : Lambda L))
      = -(elemSymm L 1 * elemSymm L 2) + ((1 - q) * (1 - u)) • (elemSymm L 1 * elemSymm L 2)
        + ((q + u) * ((1 - q) * (1 - u))) • elemSymm L 3 := by
  rw [dop_dop_apply_one]
  norm_num only [Finset.sum_range_succ, Finset.sum_range_zero, paramPleth_elemSymm_zero,
    paramPleth_elemSymm_one_eq, paramPleth_elemSymm_two_eq, elemSymm_zero, zero_add, one_mul,
    mul_one]
  simp only [MvPolynomial.smul_eq_C_mul, map_sub, map_add, map_mul, map_neg, map_one]
  ring

/-- `D_3D_1(1) = e_1e_3 - Me_4`, from `HJO.Sym.dop_dop_apply_one` at `(3,1)`. -/
theorem dop_three_dop_one_apply_one (q u : L) :
    Dop q u 3 (Dop q u 1 (1 : Lambda L))
      = elemSymm L 1 * elemSymm L 3 - ((1 - q) * (1 - u)) • elemSymm L 4 := by
  rw [dop_dop_apply_one]
  norm_num only [Finset.sum_range_succ, Finset.sum_range_zero, paramPleth_elemSymm_zero,
    paramPleth_elemSymm_one_eq, elemSymm_zero, zero_add, one_mul, mul_one]
  simp only [MvPolynomial.smul_eq_C_mul, map_sub, map_mul, map_neg, map_one]
  ring

/-- `D_1D_3(1) = e_1e_3 - Me_2^2 - (q+u)Me_1e_3 - (q^2+qu+u^2)Me_4`, from
`HJO.Sym.dop_dop_apply_one` at `(1,3)`. All of `κ(e_1), κ(e_2), κ(e_3)` are read here, which is what
makes the `e_4` coefficient of the pin a real check. -/
theorem dop_one_dop_three_apply_one (q u : L) :
    Dop q u 1 (Dop q u 3 (1 : Lambda L))
      = elemSymm L 1 * elemSymm L 3 - ((1 - q) * (1 - u)) • (elemSymm L 2 * elemSymm L 2)
        - ((q + u) * ((1 - q) * (1 - u))) • (elemSymm L 1 * elemSymm L 3)
        - ((q ^ 2 + q * u + u ^ 2) * ((1 - q) * (1 - u))) • elemSymm L 4 := by
  rw [dop_dop_apply_one]
  norm_num only [Finset.sum_range_succ, Finset.sum_range_zero, paramPleth_elemSymm_zero,
    paramPleth_elemSymm_one_eq, paramPleth_elemSymm_two_eq, paramPleth_elemSymm_three_eq,
    elemSymm_zero, zero_add, one_mul, mul_one]
  simp only [MvPolynomial.smul_eq_C_mul, map_sub, map_add, map_mul, map_neg, map_one, map_pow]
  ring

/-- **The pin.** `HJO.Sym.qop_two_three_apply_elemSymm` read at `n = 1` and evaluated by this file's
machinery alone — the straightening rule, the two-letter vacuum values, and the three `κ`-values —
lands on

`Q_{2,3}(e_1) = -e_1^2e_2 + Me_2^2 + (1-q-u+(q+u)M)e_1e_3 + (q^2+qu+u^2-1)Me_4`,

which is verbatim the right-hand side of `HJO.Sym.qop_two_three_apply_elemSymm_one`
(`HJO/Shuffle/MellitQopThreeFour.lean`), obtained there by grinding the commutator of `HJO.Sym.Qop`
directly, and of `HJO.Sym.qop_two_three_apply_elemSymm_one_pin`
(`HJO/Shuffle/MellitLadderNonVacuum.lean`), obtained there by the shift step. All four
coefficients agree, including the `e_4` one, so the signs `(-1)^{a+b+r}` and the two independent
index shifts of `HJO.Sym.dop_dop_elemSymm_mul` are pinned.

The `D_2D_2(1)` terms produced at `(s,t) = (0,1)` and `(1,0)` cancel outright, which is why the
answer is the `e_1` multiple of `Q_{2,3}(1)` corrected by a single bracket.

`M ≠ 0` is spent once, on `M⁻¹M = 1`. -/
theorem qop_two_three_apply_elemSymm_pin (q u : L) (hM : (1 - q) * (1 - u) ≠ 0) :
    Qop q u 2 3 (elemSymm L 1)
      = -(elemSymm L 1 * elemSymm L 1 * elemSymm L 2)
        + ((1 - q) * (1 - u)) • (elemSymm L 2 * elemSymm L 2)
        + (1 - q - u + (q + u) * ((1 - q) * (1 - u))) • (elemSymm L 1 * elemSymm L 3)
        + ((q ^ 2 + q * u + u ^ 2 - 1) * ((1 - q) * (1 - u))) • elemSymm L 4 := by
  rw [qop_two_three_apply_elemSymm]
  refine (inv_smul_eq_iff₀ hM).2 ?_
  norm_num only [Finset.sum_range_succ, Finset.sum_range_zero, paramPleth_elemSymm_zero,
    paramPleth_elemSymm_one_eq, elemSymm_zero, zero_add, one_mul, mul_one]
  rw [dop_two_dop_one_apply_one, dop_one_dop_two_apply_one, dop_three_dop_one_apply_one,
    dop_one_dop_three_apply_one]
  simp only [MvPolynomial.smul_eq_C_mul, map_sub, map_add, map_mul, map_one, map_pow]
  ring

/-- **The two routes off the vacuum agree as expressions.** The left-hand side is the straightening
normal form of `Q_{2,3}(e_1)`, the right-hand side is the shift-step route's
`e_1Q_{2,3}(1) - D_3(e_1) + D_1(e_3)` of
`HJO.Sym.qop_two_three_apply_elemSymm_one_of_shiftStep`. `M ≠ 0` comes from that lemma. -/
theorem qop_two_three_apply_elemSymm_pin_agrees (q u : L) (hM : (1 - q) * (1 - u) ≠ 0) :
    ((1 - q) * (1 - u))⁻¹ • (∑ s ∈ Finset.range (1 + 1), ∑ t ∈ Finset.range (1 - s + 1),
        (paramPleth q u (elemSymm L s) * paramPleth q u (elemSymm L t)) •
          (elemSymm L (1 - s - t) *
            (Dop q u (2 + t) (Dop q u (1 + s) 1) - Dop q u (1 + t) (Dop q u (2 + s) 1))))
      = elemSymm L 1 * Qop q u 2 3 1 - Dop q u 3 (elemSymm L 1) + Dop q u 1 (elemSymm L 3) :=
  (qop_two_three_apply_elemSymm q u 1).symm.trans
    (qop_two_three_apply_elemSymm_one_of_shiftStep q u hM)

/-! ### `Q_{2,3}` at every `e_n`, in `e`-monomials -/

/-- **`Q_{2,3}(e_n)` fully expanded, at every `n`**: a triple sum of `e`-monomials with
coefficients in `κ` and `±1`, obtained by substituting `HJO.Sym.dop_dop_apply_one` into
`HJO.Sym.qop_two_three_apply_elemSymm`. Nothing is left to evaluate but the `κ(e_r)`, which the
recursion `HJO.Bglx.paramPleth_elemSymm_add_two` gives at every `r`. Unconditional in `q` and `u`,
with `HJO.Sym.Qop`'s `M⁻¹` carried in the statement. -/
theorem qop_two_three_apply_elemSymm_closed (q u : L) (n : ℕ) :
    Qop q u 2 3 (elemSymm L n)
      = ((1 - q) * (1 - u))⁻¹ • ∑ s ∈ Finset.range (n + 1), ∑ t ∈ Finset.range (n - s + 1),
          (paramPleth q u (elemSymm L s) * paramPleth q u (elemSymm L t)) •
            (elemSymm L (n - s - t) *
              ((∑ r ∈ Finset.range (1 + s + 1),
                  ((-1 : L) ^ (2 + t + (1 + s) + r) * paramPleth q u (elemSymm L r)) •
                    (elemSymm L (1 + s - r) * elemSymm L (2 + t + r)))
                - ∑ r ∈ Finset.range (2 + s + 1),
                  ((-1 : L) ^ (1 + t + (2 + s) + r) * paramPleth q u (elemSymm L r)) •
                    (elemSymm L (2 + s - r) * elemSymm L (1 + t + r)))) := by
  rw [qop_two_three_apply_elemSymm]
  congr 1
  refine Finset.sum_congr rfl fun s _ => Finset.sum_congr rfl fun t _ => ?_
  rw [dop_dop_apply_one, dop_dop_apply_one]

/-! ### Straightening does not lengthen the word -/

/-- The `D`-word read off a list of indices, which is the spelling that carries a length. -/
noncomputable def dopList (q u : L) (l : List ℕ) : Module.End L (Lambda L) :=
  (l.map (Dop q u)).prod

/-- The empty word is the identity. -/
theorem dopList_nil (q u : L) : dopList q u [] = 1 := by rw [dopList]; simp

/-- A word splits off its first letter on the left. -/
theorem dopList_cons (q u : L) (k : ℕ) (l : List ℕ) :
    dopList q u (k :: l) = Dop q u k * dopList q u l := by rw [dopList, dopList]; simp

/-- Every listed word is a `D`-word. -/
theorem dopList_mem_dopMonoid (q u : L) (l : List ℕ) : dopList q u l ∈ dopMonoid q u := by
  induction l with
  | nil => rw [dopList_nil]; exact one_mem _
  | cons k l ih => rw [dopList_cons]; exact mul_mem (dop_mem_dopMonoid q u k) ih

/-- The span of `E_g` times a `D`-word of length **exactly** `m`: the graded piece of
`HJO.Sym.straightSpan` that records how long the words are. -/
noncomputable def straightSpanLen (q u : L) (m : ℕ) : Submodule L (Module.End L (Lambda L)) :=
  Submodule.span L
    {A | ∃ (g : Lambda L) (l : List ℕ), l.length = m ∧ A = LinearMap.mulLeft L g * dopList q u l}

/-- Each graded piece sits in the straightened span. -/
theorem straightSpanLen_le_straightSpan (q u : L) (m : ℕ) :
    straightSpanLen q u m ≤ straightSpan q u := by
  rw [straightSpanLen, Submodule.span_le]
  rintro x ⟨g, l, -, rfl⟩
  exact Submodule.subset_span ⟨g, dopList q u l, dopList_mem_dopMonoid q u l, rfl⟩

/-- One straightened letter in front of a word of length `m` makes a word of length `m + 1`. -/
private theorem oneDopSpan_mul_dopList_mem (q u : L) {l : List ℕ} {m : ℕ} (hl : l.length = m)
    {A : Module.End L (Lambda L)} (hA : A ∈ oneDopSpan q u) :
    A * dopList q u l ∈ straightSpanLen q u (m + 1) := by
  induction hA using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, j, rfl⟩ := hx
    rw [mul_assoc, ← dopList_cons]
    exact Submodule.subset_span ⟨h, j :: l, by rw [List.length_cons, hl], rfl⟩
  | zero => rw [zero_mul]; exact zero_mem _
  | add x y _ _ ihx ihy => rw [add_mul]; exact add_mem ihx ihy
  | smul a x _ ih => rw [smul_mul_assoc]; exact Submodule.smul_mem _ a ih

/-- A basic operator in front of a straightened length-`m` element straightens to length `m + 1`:
the straightening rule replaces `D_kE_h` by `E_{h'}D_j`, which is one letter again. -/
private theorem dop_mul_mem_straightSpanLen_succ (q u : L) (k m : ℕ)
    {A : Module.End L (Lambda L)} (hA : A ∈ straightSpanLen q u m) :
    Dop q u k * A ∈ straightSpanLen q u (m + 1) := by
  induction hA using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨g, l, hl, rfl⟩ := hx
    rw [← mul_assoc]
    exact oneDopSpan_mul_dopList_mem q u hl (dop_mul_mulLeft_mem_oneDopSpan q u g k)
  | zero => rw [mul_zero]; exact zero_mem _
  | add x y _ _ ihx ihy => rw [mul_add]; exact add_mem ihx ihy
  | smul a x _ ih => rw [mul_smul_comm]; exact Submodule.smul_mem _ a ih

/-- **Straightening preserves the length of the `D`-word.** For every `g ∈ Λ` — not just for
`g = e_n` — straightening `E_g` past a `D`-word of length `ℓ` produces a combination of `E_h` times
`D`-words of length **exactly** `ℓ`. This is the formal half of the termination argument: the rule
neither creates a basic operator nor destroys one, so an induction on the length closes, and it
bounds which vacuum values can appear in a value computed by
`HJO.Sym.dopAlgebra_apply_eq_sum_vacuum`.

The number of terms is not part of the statement; see this file's header for the count.
Unconditional in `q` and `u`. -/
theorem dopList_mul_mulLeft_mem_straightSpanLen (q u : L) (l : List ℕ) (g : Lambda L) :
    dopList q u l * LinearMap.mulLeft L g ∈ straightSpanLen q u l.length := by
  induction l generalizing g with
  | nil =>
    rw [dopList_nil, one_mul]
    exact Submodule.subset_span ⟨g, [], rfl, by rw [dopList_nil, mul_one]⟩
  | cons k l ih =>
    rw [dopList_cons, mul_assoc, List.length_cons]
    exact dop_mul_mem_straightSpanLen_succ q u k l.length (ih g)

end HJO.Sym
