/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.SweepTrainPairValues
public import HJO.Shuffle.SweepAppendTwoThree
public import HJO.Shuffle.MellitVertexStepGeneral
public import HJO.Shuffle.SweepShiftConjugate

/-! # `d_+`, `Δ` and `d_-` on the monomials the `4 × 6` sweep words present

The four above-diagonal paths of the `4 × 6` rectangle coloured `c_{(1,1)}` at the level `9/2` hand
the event operators of `HJO.Mellit.sweepOperator` a definite short list of vectors, each a monomial
in `y_1, …, y_4` with at most one symmetric-function coefficient. This file evaluates every one of
them.

## How each value is obtained

`HJO.Sweep.dplus` and `HJO.Sweep.corner` both put their argument inside the ascending train — the
first after multiplying by `y_{k+1}` and the `q`-shift, the second after multiplying by `y_{k+1}`
alone (`HJO.Sweep.corner_eq_neg_cmAscWord_auxVar_mul`). The `q`-shift is the identity on a monomial
(`HJO.Sweep.qshift_of_mem_auxSubalg`), so in both cases the whole content is one train value, and
`HJO/Shuffle/SweepTrainPairValues.lean` supplies those letter by letter.

`HJO.Sweep.dminus` is `HJO.Sweep.dminus_auxVar_pow_mul`: on `y_{k+1}F` with `F ∈ V_k` it is the
Hall–Littlewood operator `B_1` applied to `F`, and on a monomial `B_1` acts on the `Λ`-coefficient
alone (`HJO.Sweep.bopExt_auxSubalg_mul`). So the two `d_-` shapes needed reduce to `B_1(1) = -e_1`
and `B_1(e_1) = -e_1^2 + (1-q)e_2`, which are already proved.

## What is *not* covered by the collected closed form

`HJO/Shuffle/SweepTrainMonomialClosed.lean` evaluates the train on `Sy_{k+1}^{n+1}` with `S`
symmetric in `y_1, …, y_{k+1}`; the span of those vectors is exactly what is symmetric in
`y_1, …, y_k`. Of the corner values below, `Δ^{(3)}(y_1y_2y_3^2)` and `Δ^{(4)}(y_1y_2y_3y_4)` lie
inside it and the rest — every one with an unbalanced pair of *lower* exponents — do not. That is
why this file goes through the pair table rather than the closed form.

## Genericity

The `d_+` and `d_-` values are unconditional polynomial identities, holding at `q = 0` and `q = 1`.
Every `Δ` value carries `q ≠ 0` and `q ≠ 1` and cannot avoid them: `HJO.Sweep.corner` divides by
`q - 1` outright, and the train identity it is read through names inverted braid letters. `u` does
not occur anywhere here.

## References

This file evaluates `HJO.Sweep.dplus`, `HJO.Sweep.dminus` and `HJO.Sweep.corner` on the inputs of
`HJO.Mellit.sweepOperator`, using `HJO.Sweep.dminus_auxVar_pow_mul` and `HJO.Sym.Bop`.
-/

@[expose] public section

namespace HJO.Sweep

open MvPolynomial HJO.Sym

section Membership

variable {L : Type*} [Field L]

/-! ### The monomials, as members of a graded piece and of the auxiliary subalgebra -/

/-- A power of `y_i` lies in the subalgebra generated by the auxiliary variables. -/
theorem auxVar_pow_mem_auxSubalg (i n : ℕ) : (auxVar i : Total L) ^ n ∈ auxSubalg L :=
  pow_mem (auxVar_mem_auxSubalg i) n

/-- `y_1^ay_2^b ∈ V_2`. -/
theorem monoTwo_mem_piece (a b : ℕ) :
    ((auxVar 1 : Total L) ^ a * (auxVar 2 : Total L) ^ b) ∈ piece L 2 :=
  mul_mem (pow_mem (auxVar_mem_piece (by omega) (by omega)) a)
    (pow_mem (auxVar_mem_piece (by omega) (by omega)) b)

/-- `y_1^ay_2^b` is a polynomial in the auxiliary variables. -/
theorem monoTwo_mem_auxSubalg (a b : ℕ) :
    ((auxVar 1 : Total L) ^ a * (auxVar 2 : Total L) ^ b) ∈ auxSubalg L :=
  mul_mem (auxVar_pow_mem_auxSubalg 1 a) (auxVar_pow_mem_auxSubalg 2 b)

/-- `y_1^ay_2^by_3^c ∈ V_3`. -/
theorem monoThree_mem_piece (a b c : ℕ) :
    ((auxVar 1 : Total L) ^ a * (auxVar 2 : Total L) ^ b * (auxVar 3 : Total L) ^ c)
      ∈ piece L 3 :=
  mul_mem (piece_mono (by omega) (monoTwo_mem_piece a b))
    (pow_mem (auxVar_mem_piece (by omega) (by omega)) c)

/-- `y_1^ay_2^by_3^c` is a polynomial in the auxiliary variables. -/
theorem monoThree_mem_auxSubalg (a b c : ℕ) :
    ((auxVar 1 : Total L) ^ a * (auxVar 2 : Total L) ^ b * (auxVar 3 : Total L) ^ c)
      ∈ auxSubalg L :=
  mul_mem (monoTwo_mem_auxSubalg a b) (auxVar_pow_mem_auxSubalg 3 c)

/-- `y_1^ay_2^by_3^cy_4^d ∈ V_4`. -/
theorem monoFour_mem_piece (a b c d : ℕ) :
    ((auxVar 1 : Total L) ^ a * (auxVar 2 : Total L) ^ b * (auxVar 3 : Total L) ^ c
        * (auxVar 4 : Total L) ^ d) ∈ piece L 4 :=
  mul_mem (piece_mono (by omega) (monoThree_mem_piece a b c))
    (pow_mem (auxVar_mem_piece (by omega) (by omega)) d)

/-- `y_1^ay_2^by_3^cy_4^d` is a polynomial in the auxiliary variables. -/
theorem monoFour_mem_auxSubalg (a b c d : ℕ) :
    ((auxVar 1 : Total L) ^ a * (auxVar 2 : Total L) ^ b * (auxVar 3 : Total L) ^ c
        * (auxVar 4 : Total L) ^ d) ∈ auxSubalg L :=
  mul_mem (monoThree_mem_auxSubalg a b c) (auxVar_pow_mem_auxSubalg 4 d)

/-! ### The staircase in the `auxVar` spelling -/

theorem auxVarProd_two' : auxVarProd L 2 = (auxVar 1 : Total L) * auxVar 2 := auxVarProd_two

theorem auxVarProd_three' :
    auxVarProd L 3 = (auxVar 1 : Total L) * auxVar 2 * auxVar 3 := auxVarProd_three

theorem auxVarProd_four' :
    auxVarProd L 4 = (auxVar 1 : Total L) * auxVar 2 * auxVar 3 * auxVar 4 := auxVarProd_four

end Membership

/-! ### The train of width `3`, and the two operators as explicit letter products -/

section Reduce

variable {L : Type*} [Field L] {q : L}

/-- `T_{1↗4} = T_1T_2T_3`. -/
theorem cmAscWord_one_three_apply (q : L) (F : Total L) :
    cmAscWord q 1 3 F = braid q 1 (braid q 2 (braid q 3 F)) := by
  rw [show (3 : ℕ) = 2 + 1 from rfl, cmAscWord_one_succ_apply, cmAscWord_one_two_apply]

/-- **`d_+^{(k)}F = -T_{1↗k+1}(y_{k+1}F)` on a monomial.** `HJO.Sweep.dplus`'s `q`-shift is the
identity on a polynomial in the auxiliary variables alone, so on such an `F` the raising operator is
one train value. -/
theorem dplus_of_mem_auxSubalg (q : L) (k : ℕ) {F : Total L} (hF : F ∈ auxSubalg L) :
    dplus q k F = -(cmAscWord q 1 k ((auxVar (k + 1) : Total L) * F)) := by
  rw [dplus_apply, qshift_of_mem_auxSubalg q (k + 1) hF, cmAscWord]

/-- `d_+^{(1)}` on a monomial, as one braid letter. -/
theorem dplus_one_eq_neg_braid (q : L) {F : Total L} (hF : F ∈ auxSubalg L) :
    dplus q 1 F = -(braid q 1 ((auxVar 2 : Total L) * F)) := by
  have h := dplus_of_mem_auxSubalg q 1 hF
  rw [cmAscWord_one_one_apply] at h
  exact h

/-- `d_+^{(2)}` on a monomial, as two braid letters. -/
theorem dplus_two_eq_neg_braid (q : L) {F : Total L} (hF : F ∈ auxSubalg L) :
    dplus q 2 F = -(braid q 1 (braid q 2 ((auxVar 3 : Total L) * F))) := by
  have h := dplus_of_mem_auxSubalg q 2 hF
  rw [cmAscWord_one_two_apply] at h
  exact h

end Reduce

section CornerReduce

variable {L : Type*} [Field L] [Algebra ℚ L] {q : L}

/-- `Δ^{(2)}` as one braid letter. -/
theorem corner_two_eq_neg_braid (hq0 : q ≠ 0) (hq1 : q ≠ 1) {F : Total L} (hF : F ∈ piece L 2) :
    corner q 2 F = -(braid q 1 ((auxVar 2 : Total L) * F)) := by
  have h := corner_eq_neg_cmAscWord_auxVar_mul hq0 hq1 1 hF
  rw [cmAscWord_one_one_apply] at h
  exact h

/-- `Δ^{(3)}` as two braid letters. -/
theorem corner_three_eq_neg_braid (hq0 : q ≠ 0) (hq1 : q ≠ 1) {F : Total L} (hF : F ∈ piece L 3) :
    corner q 3 F = -(braid q 1 (braid q 2 ((auxVar 3 : Total L) * F))) := by
  have h := corner_eq_neg_cmAscWord_auxVar_mul hq0 hq1 2 hF
  rw [cmAscWord_one_two_apply] at h
  exact h

/-- `Δ^{(4)}` as three braid letters. -/
theorem corner_four_eq_neg_braid (hq0 : q ≠ 0) (hq1 : q ≠ 1) {F : Total L} (hF : F ∈ piece L 4) :
    corner q 4 F = -(braid q 1 (braid q 2 (braid q 3 ((auxVar 4 : Total L) * F)))) := by
  have h := corner_eq_neg_cmAscWord_auxVar_mul hq0 hq1 3 hF
  rw [cmAscWord_one_three_apply] at h
  exact h

end CornerReduce

/-! ### The pair table at the two indices the `4 × 6` words use

Each entry is `HJO.Sweep.braid_eq_of` at a concrete pair of exponents: one `swapAux` computation and
one `ring` check on the divided difference. Written at the literal indices `1` and `2` so that the
values rewrite directly into the operator computations below. -/

section Pairs

variable {L : Type*} [Field L] {q : L}

theorem braid_one_eq_of (q : L) {F H G : Total L} (hs : swapAux L 1 F = H)
    (hd : ((auxVar 2 : Total L) - auxVar 1) * G = F - H) :
    braid q 1 F = H + scal (q - 1) * ((auxVar 1 : Total L) * G) :=
  braid_eq_of q le_rfl hs hd

theorem braid_two_eq_of (q : L) {F H G : Total L} (hs : swapAux L 2 F = H)
    (hd : ((auxVar 3 : Total L) - auxVar 2) * G = F - H) :
    braid q 2 F = H + scal (q - 1) * ((auxVar 2 : Total L) * G) :=
  braid_eq_of q (by omega) hs hd

theorem swapAux_one_auxVar_one' : swapAux L 1 (auxVar 1 : Total L) = auxVar 2 :=
  swapAux_auxVar_self le_rfl

theorem swapAux_one_auxVar_two' : swapAux L 1 (auxVar 2 : Total L) = auxVar 1 :=
  swapAux_auxVar_succ le_rfl

theorem swapAux_two_auxVar_two' : swapAux L 2 (auxVar 2 : Total L) = auxVar 3 :=
  swapAux_auxVar_self (by omega)

theorem swapAux_two_auxVar_three' : swapAux L 2 (auxVar 3 : Total L) = auxVar 2 :=
  swapAux_auxVar_succ (by omega)

/-! #### Index `1`: the pair `(y_1, y_2)` -/

theorem braid_one_pair_one_one (q : L) :
    braid q 1 ((auxVar 1 : Total L) * auxVar 2) = (auxVar 1 : Total L) * auxVar 2 := by
  refine braid_eq_of_swap q ?_
  rw [map_mul, swapAux_one_auxVar_one', swapAux_one_auxVar_two']
  ring

theorem braid_one_pair_two_two (q : L) :
    braid q 1 ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2)
      = (auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 := by
  refine braid_eq_of_swap q ?_
  rw [map_mul, map_pow, map_pow, swapAux_one_auxVar_one', swapAux_one_auxVar_two']
  ring

theorem braid_one_pair_three_three (q : L) :
    braid q 1 ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 3)
      = (auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 3 := by
  refine braid_eq_of_swap q ?_
  rw [map_mul, map_pow, map_pow, swapAux_one_auxVar_one', swapAux_one_auxVar_two']
  ring

theorem braid_one_pair_one_two (q : L) :
    braid q 1 ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2)
      = scal q * ((auxVar 1 : Total L) ^ 2 * auxVar 2) := by
  have hs : swapAux L 1 ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2)
      = (auxVar 1 : Total L) ^ 2 * auxVar 2 := by
    rw [map_mul, map_pow, swapAux_one_auxVar_one', swapAux_one_auxVar_two']
    ring
  rw [braid_one_eq_of q hs (G := (auxVar 1 : Total L) * auxVar 2) (by ring)]
  simp only [scal_eq_algebraMap, map_sub, map_one]
  ring

theorem braid_one_pair_two_one (q : L) :
    braid q 1 ((auxVar 1 : Total L) ^ 2 * auxVar 2)
      = (auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2
        - scal (q - 1) * ((auxVar 1 : Total L) ^ 2 * auxVar 2) := by
  have hs : swapAux L 1 ((auxVar 1 : Total L) ^ 2 * auxVar 2)
      = (auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2 := by
    rw [map_mul, map_pow, swapAux_one_auxVar_one', swapAux_one_auxVar_two']
    ring
  rw [braid_one_eq_of q hs (G := -((auxVar 1 : Total L) * auxVar 2)) (by ring)]
  ring

theorem braid_one_pair_two_three (q : L) :
    braid q 1 ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 3)
      = scal q * ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2) := by
  have hs : swapAux L 1 ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 3)
      = (auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2 := by
    rw [map_mul, map_pow, map_pow, swapAux_one_auxVar_one', swapAux_one_auxVar_two']
    ring
  rw [braid_one_eq_of q hs
    (G := (auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2) (by ring)]
  simp only [scal_eq_algebraMap, map_sub, map_one]
  ring

theorem braid_one_pair_three_two (q : L) :
    braid q 1 ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2)
      = (auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 3
        - scal (q - 1) * ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2) := by
  have hs : swapAux L 1 ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2)
      = (auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 3 := by
    rw [map_mul, map_pow, map_pow, swapAux_one_auxVar_one', swapAux_one_auxVar_two']
    ring
  rw [braid_one_eq_of q hs
    (G := -((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2)) (by ring)]
  ring

theorem braid_one_pair_one_three (q : L) :
    braid q 1 ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 3)
      = scal (q - 1) * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2)
        + scal q * ((auxVar 1 : Total L) ^ 3 * auxVar 2) := by
  have hs : swapAux L 1 ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 3)
      = (auxVar 1 : Total L) ^ 3 * auxVar 2 := by
    rw [map_mul, map_pow, swapAux_one_auxVar_one', swapAux_one_auxVar_two']
    ring
  rw [braid_one_eq_of q hs
    (G := (auxVar 1 : Total L) * auxVar 2 * ((auxVar 1 : Total L) + auxVar 2)) (by ring)]
  simp only [scal_eq_algebraMap, map_sub, map_one]
  ring

/-! #### Index `2`: the pair `(y_2, y_3)` -/

theorem braid_two_pair_one_one (q : L) :
    braid q 2 ((auxVar 2 : Total L) * auxVar 3) = (auxVar 2 : Total L) * auxVar 3 := by
  refine braid_eq_of_swap q ?_
  rw [map_mul, swapAux_two_auxVar_two', swapAux_two_auxVar_three']
  ring

theorem braid_two_pair_two_two (q : L) :
    braid q 2 ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 2)
      = (auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 2 := by
  refine braid_eq_of_swap q ?_
  rw [map_mul, map_pow, map_pow, swapAux_two_auxVar_two', swapAux_two_auxVar_three']
  ring

theorem braid_two_pair_one_two (q : L) :
    braid q 2 ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2)
      = scal q * ((auxVar 2 : Total L) ^ 2 * auxVar 3) := by
  have hs : swapAux L 2 ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2)
      = (auxVar 2 : Total L) ^ 2 * auxVar 3 := by
    rw [map_mul, map_pow, swapAux_two_auxVar_two', swapAux_two_auxVar_three']
    ring
  rw [braid_two_eq_of q hs (G := (auxVar 2 : Total L) * auxVar 3) (by ring)]
  simp only [scal_eq_algebraMap, map_sub, map_one]
  ring

theorem braid_two_pair_two_one (q : L) :
    braid q 2 ((auxVar 2 : Total L) ^ 2 * auxVar 3)
      = (auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2
        - scal (q - 1) * ((auxVar 2 : Total L) ^ 2 * auxVar 3) := by
  have hs : swapAux L 2 ((auxVar 2 : Total L) ^ 2 * auxVar 3)
      = (auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2 := by
    rw [map_mul, map_pow, swapAux_two_auxVar_two', swapAux_two_auxVar_three']
    ring
  rw [braid_two_eq_of q hs (G := -((auxVar 2 : Total L) * auxVar 3)) (by ring)]
  ring

theorem braid_two_pair_two_three (q : L) :
    braid q 2 ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 3)
      = scal q * ((auxVar 2 : Total L) ^ 3 * (auxVar 3 : Total L) ^ 2) := by
  have hs : swapAux L 2 ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 3)
      = (auxVar 2 : Total L) ^ 3 * (auxVar 3 : Total L) ^ 2 := by
    rw [map_mul, map_pow, map_pow, swapAux_two_auxVar_two', swapAux_two_auxVar_three']
    ring
  rw [braid_two_eq_of q hs
    (G := (auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 2) (by ring)]
  simp only [scal_eq_algebraMap, map_sub, map_one]
  ring

theorem braid_two_pair_one_three (q : L) :
    braid q 2 ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 3)
      = scal (q - 1) * ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 2)
        + scal q * ((auxVar 2 : Total L) ^ 3 * auxVar 3) := by
  have hs : swapAux L 2 ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 3)
      = (auxVar 2 : Total L) ^ 3 * auxVar 3 := by
    rw [map_mul, map_pow, swapAux_two_auxVar_two', swapAux_two_auxVar_three']
    ring
  rw [braid_two_eq_of q hs
    (G := (auxVar 2 : Total L) * auxVar 3 * ((auxVar 2 : Total L) + auxVar 3)) (by ring)]
  simp only [scal_eq_algebraMap, map_sub, map_one]
  ring

end Pairs

/-! ### `d_+` on the three monomials the words present -/

section DplusValues

variable {L : Type*} [Field L] {q : L}

/-- **`d_+^{(1)}(y_1^2) = -y_1y_2^2 + (q-1)y_1^2y_2`.** The first raising value that is not a single
monomial: the train's one letter meets the unbalanced pair `(2,1)`. -/
theorem dplus_one_auxVar_one_sq (q : L) :
    dplus q 1 ((auxVar 1 : Total L) ^ 2)
      = -((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2)
        + scal (q - 1) * ((auxVar 1 : Total L) ^ 2 * auxVar 2) := by
  have hstep : braid q 1 ((auxVar 2 : Total L) * (auxVar 1 : Total L) ^ 2)
      = (auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2
        - scal (q - 1) * ((auxVar 1 : Total L) ^ 2 * auxVar 2) := by
    rw [show (auxVar 2 : Total L) * (auxVar 1 : Total L) ^ 2
        = (auxVar 1 : Total L) ^ 2 * auxVar 2 from by ring, braid_one_pair_two_one]
  rw [dplus_one_eq_neg_braid q (auxVar_pow_mem_auxSubalg 1 2), hstep]
  ring

/-- **`d_+^{(2)}(y_1y_2^2) = -y_1y_2y_3^2 + q(q-1)y_1^2y_2y_3`.** -/
theorem dplus_two_auxVar_one_mul_auxVar_two_sq (q : L) :
    dplus q 2 ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2)
      = -((auxVar 1 : Total L) * auxVar 2 * (auxVar 3 : Total L) ^ 2)
        + scal (q * (q - 1)) * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3) := by
  have haux : ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2) ∈ auxSubalg L :=
    mul_mem (auxVar_mem_auxSubalg 1) (auxVar_pow_mem_auxSubalg 2 2)
  have h2 : braid q 2 ((auxVar 3 : Total L) * ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2))
      = (auxVar 1 : Total L) * ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2)
        - scal (q - 1) * ((auxVar 1 : Total L)
            * ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L))) := by
    rw [show (auxVar 3 : Total L) * ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2)
        = (auxVar 1 : Total L) ^ 1 * ((auxVar 2 : Total L) ^ 2 * auxVar 3) from by ring,
      braid_two_auxVar_one_pow_mul, braid_two_pair_two_one]
    ring
  have h1 : braid q 1 ((auxVar 1 : Total L) * ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2)
        - scal (q - 1) * ((auxVar 1 : Total L)
            * ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L))))
      = (auxVar 1 : Total L) * auxVar 2 * (auxVar 3 : Total L) ^ 2
        - scal (q * (q - 1)) * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3) := by
    rw [map_sub, braid_scal_mul,
      show (auxVar 1 : Total L) * ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2)
        = (auxVar 3 : Total L) ^ 2 * ((auxVar 1 : Total L) * auxVar 2) from by ring,
      show (auxVar 1 : Total L) * ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L))
        = (auxVar 3 : Total L) ^ 1 * ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2) from by ring,
      braid_one_auxVar_three_pow_mul, braid_one_auxVar_three_pow_mul,
      braid_one_pair_one_one, braid_one_pair_one_two]
    simp only [scal_eq_algebraMap, map_sub, map_mul, map_one]
    ring
  rw [dplus_two_eq_neg_braid q haux, h2, h1]
  ring

/-- **`d_+^{(2)}(y_1^2y_2) = -y_1y_2^2y_3 + (q-1)y_1^2y_2y_3`.** -/
theorem dplus_two_auxVar_one_sq_mul_auxVar_two (q : L) :
    dplus q 2 ((auxVar 1 : Total L) ^ 2 * auxVar 2)
      = -((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2 * auxVar 3)
        + scal (q - 1) * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3) := by
  have haux : ((auxVar 1 : Total L) ^ 2 * auxVar 2) ∈ auxSubalg L :=
    mul_mem (auxVar_pow_mem_auxSubalg 1 2) (auxVar_mem_auxSubalg 2)
  have h2 : braid q 2 ((auxVar 3 : Total L) * ((auxVar 1 : Total L) ^ 2 * auxVar 2))
      = (auxVar 3 : Total L) ^ 1 * ((auxVar 1 : Total L) ^ 2 * auxVar 2) := by
    rw [show (auxVar 3 : Total L) * ((auxVar 1 : Total L) ^ 2 * auxVar 2)
        = (auxVar 1 : Total L) ^ 2 * ((auxVar 2 : Total L) * auxVar 3) from by ring,
      braid_two_auxVar_one_pow_mul, braid_two_pair_one_one]
    ring
  rw [dplus_two_eq_neg_braid q haux, h2, braid_one_auxVar_three_pow_mul,
    braid_one_pair_two_one]
  ring

end DplusValues

/-! ### `Δ` on the monomials the words present -/

section CornerValues

variable {L : Type*} [Field L] [Algebra ℚ L] {q : L}

/-! #### Width `2` -/

/-- **`Δ^{(2)}(y_1y_2) = -qy_1^2y_2`**, the width-`2` reading of `HJO.Sweep.corner_auxVarProd`. -/
theorem corner_two_prod (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 2 ((auxVar 1 : Total L) * auxVar 2)
      = -(scal q * ((auxVar 1 : Total L) ^ 2 * auxVar 2)) := by
  have hF : ((auxVar 1 : Total L) * auxVar 2) ∈ piece L 2 :=
    mul_mem (auxVar_mem_piece (by omega) (by omega)) (auxVar_mem_piece (by omega) (by omega))
  rw [corner_two_eq_neg_braid hq0 hq1 hF,
    show (auxVar 2 : Total L) * ((auxVar 1 : Total L) * auxVar 2)
      = (auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2 from by ring,
    braid_one_pair_one_two]

/-- **`Δ^{(2)}(y_1^2y_2) = -y_1^2y_2^2`**: the inserted `y_2` balances the pair, so the letter is
the
identity and no power of `q` appears — the one corner value of these words with no `q` in it. -/
theorem corner_two_auxVar_one_sq_mul_auxVar_two (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 2 ((auxVar 1 : Total L) ^ 2 * auxVar 2)
      = -((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2) := by
  have hF : ((auxVar 1 : Total L) ^ 2 * auxVar 2) ∈ piece L 2 :=
    mul_mem (pow_mem (auxVar_mem_piece (by omega) (by omega)) 2)
      (auxVar_mem_piece (by omega) (by omega))
  rw [corner_two_eq_neg_braid hq0 hq1 hF,
    show (auxVar 2 : Total L) * ((auxVar 1 : Total L) ^ 2 * auxVar 2)
      = (auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 from by ring,
    braid_one_pair_two_two]

/-- **`Δ^{(2)}(y_1^2y_2^2) = -qy_1^3y_2^2`**: the inserted `y_2` makes the pair `(2,3)`, which emits
one `q`. -/
theorem corner_two_auxVar_one_sq_mul_auxVar_two_sq (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 2 ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2)
      = -(scal q * ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2)) := by
  rw [corner_two_eq_neg_braid hq0 hq1 (monoTwo_mem_piece 2 2),
    show (auxVar 2 : Total L) * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2)
      = (auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 3 from by ring,
    braid_one_pair_two_three]

/-- **`Δ^{(2)}(y_1^3y_2^2) = -y_1^3y_2^3`**: balanced again, so no `q`. -/
theorem corner_two_auxVar_one_cube_mul_auxVar_two_sq (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 2 ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2)
      = -((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 3) := by
  rw [corner_two_eq_neg_braid hq0 hq1 (monoTwo_mem_piece 3 2),
    show (auxVar 2 : Total L) * ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2)
      = (auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 3 from by ring,
    braid_one_pair_three_three]

/-! #### Width `3` -/

/-- **`Δ^{(3)}(y_1y_2y_3^2) = -q(q-1)y_1^2y_2y_3^2 - q(q-1)y_1^2y_2^2y_3 - q^2y_1^3y_2y_3`**: the
one width-`3` corner value of these words that the collected closed form does reach, its argument
being `(y_1y_2y_3)y_3` with a symmetric factor. -/
theorem corner_three_prod_mul_auxVar_three (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 3 ((auxVar 1 : Total L) * auxVar 2 * (auxVar 3 : Total L) ^ 2)
      = -(scal (q * (q - 1)) * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * (auxVar 3 : Total L) ^ 2))
        - scal (q * (q - 1)) * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 * auxVar 3)
        - scal (q ^ 2) * ((auxVar 1 : Total L) ^ 3 * auxVar 2 * auxVar 3) := by
  have hF : ((auxVar 1 : Total L) * auxVar 2 * (auxVar 3 : Total L) ^ 2) ∈ piece L 3 :=
    mul_mem (mul_mem (auxVar_mem_piece (by omega) (by omega))
        (auxVar_mem_piece (by omega) (by omega)))
      (pow_mem (auxVar_mem_piece (by omega) (by omega)) 2)
  have h2 : braid q 2 ((auxVar 3 : Total L)
        * ((auxVar 1 : Total L) * auxVar 2 * (auxVar 3 : Total L) ^ 2))
      = scal (q - 1) * ((auxVar 3 : Total L) ^ 2 * ((auxVar 1 : Total L)
            * (auxVar 2 : Total L) ^ 2))
        + scal q * ((auxVar 3 : Total L) ^ 1 * ((auxVar 1 : Total L)
            * (auxVar 2 : Total L) ^ 3)) := by
    rw [show (auxVar 3 : Total L) * ((auxVar 1 : Total L) * auxVar 2 * (auxVar 3 : Total L) ^ 2)
        = (auxVar 1 : Total L) ^ 1 * ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 3) from by ring,
      braid_two_auxVar_one_pow_mul, braid_two_pair_one_three]
    ring
  rw [corner_three_eq_neg_braid hq0 hq1 hF, h2, map_add, braid_scal_mul, braid_scal_mul,
    braid_one_auxVar_three_pow_mul, braid_one_auxVar_three_pow_mul,
    braid_one_pair_one_two, braid_one_pair_one_three]
  simp only [scal_eq_algebraMap, map_sub, map_mul, map_one, map_pow]
  ring

/-- **`Δ^{(3)}(y_1y_2^2y_3) = -qy_1^2y_2y_3^2`.** -/
theorem corner_three_auxVar_one_mul_auxVar_two_sq_mul_auxVar_three (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 3 ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2 * auxVar 3)
      = -(scal q * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * (auxVar 3 : Total L) ^ 2)) := by
  have hF : ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2 * auxVar 3) ∈ piece L 3 :=
    mul_mem (mul_mem (auxVar_mem_piece (by omega) (by omega))
        (pow_mem (auxVar_mem_piece (by omega) (by omega)) 2))
      (auxVar_mem_piece (by omega) (by omega))
  have h2 : braid q 2 ((auxVar 3 : Total L)
        * ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2 * auxVar 3))
      = (auxVar 3 : Total L) ^ 2 * ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2) := by
    rw [show (auxVar 3 : Total L) * ((auxVar 1 : Total L) * (auxVar 2 : Total L) ^ 2 * auxVar 3)
        = (auxVar 1 : Total L) ^ 1 * ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 2) from by
        ring,
      braid_two_auxVar_one_pow_mul, braid_two_pair_two_two]
    ring
  rw [corner_three_eq_neg_braid hq0 hq1 hF, h2, braid_one_auxVar_three_pow_mul,
    braid_one_pair_one_two]
  ring

/-- **`Δ^{(3)}(y_1^2y_2y_3) = -qy_1^2y_2^2y_3`.** -/
theorem corner_three_auxVar_one_sq_mul_auxVar_two_mul_auxVar_three (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 3 ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3)
      = -(scal q * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 * auxVar 3)) := by
  have hF : ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3) ∈ piece L 3 :=
    mul_mem (mul_mem (pow_mem (auxVar_mem_piece (by omega) (by omega)) 2)
        (auxVar_mem_piece (by omega) (by omega)))
      (auxVar_mem_piece (by omega) (by omega))
  have h2 : braid q 2 ((auxVar 3 : Total L)
        * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3))
      = scal q * ((auxVar 3 : Total L) ^ 1 * ((auxVar 1 : Total L) ^ 2
          * (auxVar 2 : Total L) ^ 2)) := by
    rw [show (auxVar 3 : Total L) * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3)
        = (auxVar 1 : Total L) ^ 2 * ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2) from by ring,
      braid_two_auxVar_one_pow_mul, braid_two_pair_one_two]
    ring
  rw [corner_three_eq_neg_braid hq0 hq1 hF, h2, braid_scal_mul,
    braid_one_auxVar_three_pow_mul, braid_one_pair_two_two]
  ring

/-- **`Δ^{(3)}(y_1^3y_2y_3) = -qy_1^2y_2^3y_3 + q(q-1)y_1^3y_2^2y_3`.** -/
theorem corner_three_auxVar_one_cube_mul_auxVar_two_mul_auxVar_three (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 3 ((auxVar 1 : Total L) ^ 3 * auxVar 2 * auxVar 3)
      = -(scal q * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 3 * auxVar 3))
        + scal (q * (q - 1)) * ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2
            * auxVar 3) := by
  have hF : ((auxVar 1 : Total L) ^ 3 * auxVar 2 * auxVar 3) ∈ piece L 3 :=
    mul_mem (mul_mem (pow_mem (auxVar_mem_piece (by omega) (by omega)) 3)
        (auxVar_mem_piece (by omega) (by omega)))
      (auxVar_mem_piece (by omega) (by omega))
  have h2 : braid q 2 ((auxVar 3 : Total L) * ((auxVar 1 : Total L) ^ 3 * auxVar 2 * auxVar 3))
      = scal q * ((auxVar 3 : Total L) ^ 1 * ((auxVar 1 : Total L) ^ 3
          * (auxVar 2 : Total L) ^ 2)) := by
    rw [show (auxVar 3 : Total L) * ((auxVar 1 : Total L) ^ 3 * auxVar 2 * auxVar 3)
        = (auxVar 1 : Total L) ^ 3 * ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 2) from by ring,
      braid_two_auxVar_one_pow_mul, braid_two_pair_one_two]
    ring
  rw [corner_three_eq_neg_braid hq0 hq1 hF, h2, braid_scal_mul,
    braid_one_auxVar_three_pow_mul, braid_one_pair_three_two]
  simp only [scal_eq_algebraMap, map_sub, map_mul, map_one]
  ring

/-- **`Δ^{(3)}(y_1^2y_2y_3^2) = -(q-1)y_1^2y_2^2y_3^2 - q^2y_1^3y_2^2y_3`.** -/
theorem corner_three_auxVar_one_sq_mul_auxVar_two_mul_auxVar_three_sq (hq0 : q ≠ 0)
    (hq1 : q ≠ 1) :
    corner q 3 ((auxVar 1 : Total L) ^ 2 * auxVar 2 * (auxVar 3 : Total L) ^ 2)
      = -(scal (q - 1) * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2
            * (auxVar 3 : Total L) ^ 2))
        - scal (q ^ 2) * ((auxVar 1 : Total L) ^ 3 * (auxVar 2 : Total L) ^ 2 * auxVar 3) := by
  have hF : ((auxVar 1 : Total L) ^ 2 * auxVar 2 * (auxVar 3 : Total L) ^ 2) ∈ piece L 3 :=
    mul_mem (mul_mem (pow_mem (auxVar_mem_piece (by omega) (by omega)) 2)
        (auxVar_mem_piece (by omega) (by omega)))
      (pow_mem (auxVar_mem_piece (by omega) (by omega)) 2)
  have h2 : braid q 2 ((auxVar 3 : Total L)
        * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * (auxVar 3 : Total L) ^ 2))
      = scal (q - 1) * ((auxVar 3 : Total L) ^ 2 * ((auxVar 1 : Total L) ^ 2
            * (auxVar 2 : Total L) ^ 2))
        + scal q * ((auxVar 3 : Total L) ^ 1 * ((auxVar 1 : Total L) ^ 2
            * (auxVar 2 : Total L) ^ 3)) := by
    rw [show (auxVar 3 : Total L)
          * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * (auxVar 3 : Total L) ^ 2)
        = (auxVar 1 : Total L) ^ 2 * ((auxVar 2 : Total L) * (auxVar 3 : Total L) ^ 3) from by ring,
      braid_two_auxVar_one_pow_mul, braid_two_pair_one_three]
    ring
  rw [corner_three_eq_neg_braid hq0 hq1 hF, h2, map_add, braid_scal_mul, braid_scal_mul,
    braid_one_auxVar_three_pow_mul, braid_one_auxVar_three_pow_mul,
    braid_one_pair_two_two, braid_one_pair_two_three]
  simp only [scal_eq_algebraMap, map_sub, map_one, map_pow]
  ring

/-- **`Δ^{(3)}(y_1^2y_2^2y_3) = -y_1^2y_2^2y_3^2`**: every pair the two letters meet is balanced, so
neither emits anything. -/
theorem corner_three_auxVar_one_sq_mul_auxVar_two_sq_mul_auxVar_three (hq0 : q ≠ 0)
    (hq1 : q ≠ 1) :
    corner q 3 ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 * auxVar 3)
      = -((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 2) := by
  have hF : ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 * auxVar 3) ∈ piece L 3 :=
    mul_mem (mul_mem (pow_mem (auxVar_mem_piece (by omega) (by omega)) 2)
        (pow_mem (auxVar_mem_piece (by omega) (by omega)) 2))
      (auxVar_mem_piece (by omega) (by omega))
  have h2 : braid q 2 ((auxVar 3 : Total L)
        * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 * auxVar 3))
      = (auxVar 3 : Total L) ^ 2 * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2) := by
    rw [show (auxVar 3 : Total L)
          * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 * auxVar 3)
        = (auxVar 1 : Total L) ^ 2 * ((auxVar 2 : Total L) ^ 2 * (auxVar 3 : Total L) ^ 2) from by
        ring,
      braid_two_auxVar_one_pow_mul, braid_two_pair_two_two]
    ring
  rw [corner_three_eq_neg_braid hq0 hq1 hF, h2, braid_one_auxVar_three_pow_mul,
    braid_one_pair_two_two]
  ring

/-! #### Width `4` -/

/-- **`Δ^{(4)}(y_1y_2y_3y_4) = -q^3y_1^2y_2y_3y_4`**, the width-`4` reading of
`HJO.Sweep.corner_auxVarProd`. -/
theorem corner_four_prod' (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 4 ((auxVar 1 : Total L) * auxVar 2 * auxVar 3 * auxVar 4)
      = -(scal (q ^ 3) * ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3 * auxVar 4)) := by
  have h := corner_auxVarProd (L := L) hq0 hq1 3
  rw [show (3 : ℕ) + 1 = 4 from rfl, auxVarProd_four'] at h
  rw [h]
  ring

/-- **`Δ^{(4)}(y_1^2y_2y_3y_4) = -q^2y_1^2y_2^2y_3y_4`**, the width-`4` reading of
`HJO.Sweep.corner_auxVar_one_mul_auxVarProd`. The exponent is `q^2`, not `q^3`: the doubled bottom
variable costs the train's cascade its last step. -/
theorem corner_four_auxVar_one_mul_prod (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 4 ((auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3 * auxVar 4)
      = -(scal (q ^ 2) * ((auxVar 1 : Total L) ^ 2 * (auxVar 2 : Total L) ^ 2 * auxVar 3
          * auxVar 4)) := by
  have h := corner_auxVar_one_mul_auxVarProd (L := L) hq0 hq1 2
  rw [show (2 : ℕ) + 2 = 4 from rfl, auxVarProd_four'] at h
  rw [show (auxVar 1 : Total L) ^ 2 * auxVar 2 * auxVar 3 * auxVar 4
      = (auxVar 1 : Total L) * ((auxVar 1 : Total L) * auxVar 2 * auxVar 3 * auxVar 4) from by ring,
    h]
  ring

end CornerValues

/-! ### `d_-` on a monomial with its top variable to the first power -/

section DminusValues

variable {L : Type*} [Field L] [Algebra ℚ L] {q : L}

/-- **`d_-^{(k+1)}(y_{k+1}F) = -e_1F`** for every `F ∈ V_k` that is a polynomial in the auxiliary
variables alone.

`HJO.Sweep.dminus_auxVar_pow_mul` reads `HJO.Sweep.dminus` on `y_{k+1}^1F` as the Hall–Littlewood
operator `B_1` applied to `F`; `F` carries no symmetric function for `B_1` to act on
(`HJO.Sweep.bopExt_auxSubalg_mul`), so what is left is `B_1(1) = -e_1`. Unconditional in `q`: no
inverse occurs, the displacement `τ^-` being read on a vector it fixes. -/
theorem dminus_auxVar_succ_mul (q : L) (k : ℕ) {F : Total L} (hp : F ∈ piece L k)
    (ha : F ∈ auxSubalg L) :
    dminus q (k + 1) ((auxVar (k + 1) : Total L) * F)
      = -(MvPolynomial.C (elemSymm L 1) * F) := by
  have hb : bopExt q ((1 : ℕ) : ℤ) F = -(MvPolynomial.C (elemSymm L 1) * F) := by
    rw [← mul_one F, bopExt_auxSubalg_mul q _ ha, bopExt_one, Nat.cast_one, elemSymmAlt_one,
      map_neg]
    ring
  rw [show (auxVar (k + 1) : Total L) * F = (auxVar (k + 1) : Total L) ^ 1 * F from by rw [pow_one],
    dminus_auxVar_pow_mul q k 1 hp, hb]

/-- **`d_-^{(k+1)}(y_{k+1}fF) = (B_1f)F`** for a symmetric function `f` and a monomial `F ∈ V_k`:
the lowering operator acts on the `Λ`-coefficient alone. This is where the `q`-displacement of
`HJO.Sweep.qshiftNeg` is felt — `B_1` is not multiplication by `-e_1` once there is a coefficient
for it to displace. -/
theorem dminus_auxVar_succ_mul_C_mul (q : L) (k : ℕ) (f : Sym.Lambda L) {F : Total L}
    (hp : F ∈ piece L k) (ha : F ∈ auxSubalg L) :
    dminus q (k + 1) ((auxVar (k + 1) : Total L) * (MvPolynomial.C f * F))
      = MvPolynomial.C (Sym.Bop q 1 f) * F := by
  have hmem : (MvPolynomial.C f * F : Total L) ∈ piece L k := mul_mem ((piece L k).algebraMap_mem
  f) hp
  have hb : bopExt q ((1 : ℕ) : ℤ) (MvPolynomial.C f * F)
      = MvPolynomial.C (Sym.Bop q 1 f) * F := by
    rw [show (MvPolynomial.C f * F : Total L) = F * MvPolynomial.C f from mul_comm _ _,
      bopExt_auxSubalg_mul q _ ha, bopExt_C, Nat.cast_one]
    ring
  rw [show (auxVar (k + 1) : Total L) * (MvPolynomial.C f * F)
      = (auxVar (k + 1) : Total L) ^ 1 * (MvPolynomial.C f * F) from by rw [pow_one],
    dminus_auxVar_pow_mul q k 1 hmem, hb]

/-- **`d_-^{(k+1)}(y_{k+1}e_1F) = -e_1^2F + (1-q)e_2F`** for a monomial `F ∈ V_k`: the reading of
`HJO.Sweep.dminus_auxVar_succ_mul_C_mul` at `f = e_1`, where `B_1(e_1)` is
`HJO.Sym.bop_one_elemSymm_one`. This is the step that produces the `e_2` of the answer, and the only
place in these four words where `e_2` appears at all. -/
theorem dminus_auxVar_succ_mul_C_elemSymm_one_mul (q : L) (k : ℕ) {F : Total L}
    (hp : F ∈ piece L k) (ha : F ∈ auxSubalg L) :
    dminus q (k + 1) ((auxVar (k + 1) : Total L) * (MvPolynomial.C (elemSymm L 1) * F))
      = -(MvPolynomial.C (elemSymm L 1 * elemSymm L 1) * F)
        + scal (1 - q) * (MvPolynomial.C (elemSymm L 2) * F) := by
  rw [dminus_auxVar_succ_mul_C_mul q k (elemSymm L 1) hp ha, bop_one_elemSymm_one, map_add,
    map_neg, map_mul, map_mul, scal]
  ring

end DminusValues

end HJO.Sweep

end
