/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.SweepConsumeRuleA
public meta import HJO.Attr

/-!
# The braid operators preserve the `𝕜`-polynomials in the auxiliary variables

`HJO.Sweep.auxSubalg` is the `𝕜`-subalgebra of the total space generated by the auxiliary
variables — the "`𝕜`-linear combination of monomials in the `y`". This file proves that
every braid letter `T_i` maps it into itself, and draws the consequence that rule `A`'s absorption
was carrying as a hypothesis.

## The proof is the twisted Leibniz rule, not the retraction

`T_iF = s_iF + (q-1)y_i∂_iF` (`HJO.Sweep.braid_apply`), so two things have to be shown: that the
interchange `s_i` preserves the subalgebra, and that the divided difference `∂_i` does.

The interchange is immediate — it permutes the generators. For the divided difference the argument
used here is **not** a constant-term retraction argument, and not the
monomial formula `HJO.Sweep.dividedDiff_auxVar_pow_mul_auxVar_pow` either. It is the twisted
Leibniz rule

`∂_i(FG) = (∂_iF)G + (s_iF)(∂_iG)`

(`HJO.Sweep.dividedDiff_mul`, proved in `HJO/Shuffle/BraidRelations.lean`), which turns the
generation of `HJO.Sweep.auxSubalg` by the `y` into an induction: the
subalgebra's own induction principle `Algebra.adjoin_induction` has one case per generator, one for
a scalar, one for a sum and one for a product, and the twisted Leibniz rule closes the product case
because the twist `s_iF` is handled by the interchange half. On a generator `∂_i(y_j)` is `-1`, `1`
or `0` (`HJO.Sweep.dividedDiff_X_mem_auxSubalg`), and on a scalar it vanishes.

The retraction route would need the subalgebra to be a retract of the total space *and* the quotient
by `y_{i+1} - y_i` to commute with the retraction; the induction needs neither, and in particular
needs no statement about `Λ` at all.

## What this costs

**Nothing.** No hypothesis on `q` and none on the index: the statement holds at `i = 0` as well,
where `T_0` is the identity, so the `i ≥ 1` is not carried.

The word statement `HJO.Sweep.cmAscWord_mem_auxSubalg` is restricted to `i ≤ j + 1`, the range on
which `HJO.Sweep.cmAscWord` is a word in the *uninverted* letters, and that range covers every word
`HJO.Sweep.stairWord` is built from, at every shift. The restriction is not a cost either: outside
it the word is built from `HJO.Sweep.braidInv`, whose scalar `q⁻¹` the subalgebra contains whatever
`q` is, so the inverted range is unproved here only because nothing below needs it.

## Main results

* `HJO.Sweep.braid_mem_auxSubalg`: `T_i` preserves `HJO.Sweep.auxSubalg`.
* `HJO.Sweep.dividedDiff_mem_auxSubalg`: so does the divided difference `∂_i`, by the
  twisted Leibniz rule `HJO.Sweep.dividedDiff_mul`.
* `HJO.Sweep.stairWord_mem_auxSubalg`: hence so does every staircase word.
* `HJO.Sweep.dplus_stairWord_consume`: rule `A`'s absorption with the second membership
  hypothesis of `HJO.Sweep.dplus_stairWord_consume_of_mem_auxSubalg` discharged once and for all,
  rather than by computation at each use.

## What this does not do

It does not revive the staircase-consumption route to the induction: that route is closed by the
shift, the absorption being a braid sandwich around a single letter and so living only at `δ = 1`
while the geometry supplies `δ ≥ 2` once `a ≥ 2`
(`HJO.Mellit.card_tailLiveSteps_tailTwoThreeA_two`). What it does is remove a hypothesis
from an earlier lemma.

## References

A. Mellit, *Toric braids and
`(m, n)`-parking functions*, sections 3 and 4.
-/

@[expose] public section

namespace HJO.Sweep

variable {L : Type*} [Field L]

/-! ### The interchange permutes the generators -/

/-- **The interchange `s_i` preserves the `𝕜`-polynomials in the `y`.** It sends a generator to a
generator and fixes the scalars, which is all the subalgebra's induction principle asks. No
hypothesis on the index: at `i = 0` the interchange is the identity. -/
theorem swapAux_mem_auxSubalg (i : ℕ) {F : Total L} (hF : F ∈ auxSubalg L) :
    swapAux L i F ∈ auxSubalg L := by
  have hF' : F ∈ Algebra.adjoin L (Set.range (MvPolynomial.X : ℕ → Total L)) := hF
  clear hF
  induction hF' using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨j, rfl⟩ := hx
    rw [swapAux_X]
    exact Algebra.subset_adjoin ⟨_, rfl⟩
  | algebraMap r =>
    rw [← scal_eq_algebraMap, scal, swapAux_C]
    exact (auxSubalg L).algebraMap_mem r
  | add x y _ _ ihx ihy => rw [map_add]; exact add_mem ihx ihy
  | mul x y _ _ ihx ihy => rw [map_mul]; exact mul_mem ihx ihy

/-! ### What the divided difference does to a scalar and to a generator

The product case is the twisted Leibniz rule `HJO.Sweep.dividedDiff_mul`; nothing about it is
re-proved here. -/

/-- **`∂_i` kills a symmetric function.** Its numerator `F - s_iF` vanishes there, and the quotient
by `y_{i+1} - y_i` is unique. -/
theorem dividedDiff_C_eq_zero (i : ℕ) (c : Sym.Lambda L) :
    dividedDiff i (MvPolynomial.C c : Total L) = 0 := by
  rcases Nat.eq_zero_or_pos i with rfl | hi
  · exact dividedDiff_zero_index _
  exact (dividedDiff_unique hi (by rw [swapAux_C, sub_self, mul_zero])).symm

/-- **`∂_i` of a generator is `-1`, `1` or `0`**, hence a `𝕜`-polynomial in the `y`: the numerator
`y_j - s_iy_j` is `±(y_{i+1} - y_i)` when `j` is one of the two swapped indices and `0` otherwise.
This is the generator case of `HJO.Sweep.dividedDiff_mem_auxSubalg`. -/
theorem dividedDiff_X_mem_auxSubalg (i j : ℕ) :
    dividedDiff i (MvPolynomial.X j : Total L) ∈ auxSubalg L := by
  rcases Nat.eq_zero_or_pos i with rfl | hi
  · rw [dividedDiff_zero_index]; exact zero_mem _
  rcases eq_or_ne j (i - 1) with rfl | hj1
  · rw [← dividedDiff_unique hi (G := -1)
      (by rw [swapAux_X, Equiv.swap_apply_left]; ring)]
    exact neg_mem (one_mem (auxSubalg L))
  rcases eq_or_ne j i with rfl | hj2
  · rw [← dividedDiff_unique hi (G := 1)
      (by rw [swapAux_X, Equiv.swap_apply_right]; ring)]
    exact one_mem _
  · rw [← dividedDiff_unique hi (G := 0)
      (by rw [swapAux_X, Equiv.swap_apply_of_ne_of_ne hj1 hj2, sub_self, mul_zero])]
    exact zero_mem _

/-- **The divided difference `∂_i` preserves the `𝕜`-polynomials in the `y`.** By induction over the
generation of `HJO.Sweep.auxSubalg` by the auxiliary variables: `HJO.Sweep.dividedDiff_add` gives
the sum, `HJO.Sweep.dividedDiff_mul` the product (its twist landing inside the subalgebra by
`HJO.Sweep.swapAux_mem_auxSubalg`), `HJO.Sweep.dividedDiff_X_mem_auxSubalg` the generators and
`HJO.Sweep.dividedDiff_C_eq_zero` the scalars.

This is the half of `HJO.Sweep.braid_mem_auxSubalg` that has content: `∂_i` is defined as a
quotient, and nothing about the *shape* of that quotient is used — only that it is one. -/
theorem dividedDiff_mem_auxSubalg (i : ℕ) {F : Total L} (hF : F ∈ auxSubalg L) :
    dividedDiff i F ∈ auxSubalg L := by
  have hF' : F ∈ Algebra.adjoin L (Set.range (MvPolynomial.X : ℕ → Total L)) := hF
  clear hF
  induction hF' using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨j, rfl⟩ := hx
    exact dividedDiff_X_mem_auxSubalg i j
  | algebraMap r =>
    rw [← scal_eq_algebraMap, scal, dividedDiff_C_eq_zero]
    exact zero_mem _
  | add x y _ _ ihx ihy => rw [dividedDiff_add]; exact add_mem ihx ihy
  | mul x y hx hy ihx ihy =>
    rw [dividedDiff_mul]
    exact add_mem (mul_mem ihx (show y ∈ auxSubalg L from hy))
      (mul_mem (swapAux_mem_auxSubalg i (show x ∈ auxSubalg L from hx)) ihy)

/-! ### The braid letter, and the words built from it -/

/-- **THE BRAID OPERATORS PRESERVE THE AUXILIARY SUBALGEBRA.**
`HJO.Sweep.braid_mem_auxSubalg`: `T_i` carries every `𝕜`-polynomial in the auxiliary variables to a
`𝕜`-polynomial in the auxiliary variables.

`T_iF = s_iF + (q-1)y_i∂_iF` by `HJO.Sweep.braid_apply`, and each of the three factors of the second
term lies in the subalgebra: the scalar by `Subalgebra.algebraMap_mem`, the variable by
`HJO.Sweep.auxVar_mem_auxSubalg`, the divided difference by
`HJO.Sweep.dividedDiff_mem_auxSubalg`.

**Spends nothing**: no hypothesis on `q`, and the `i ≥ 1` is not needed — at the unread
index `0` the letter is the identity. The proof is the Leibniz induction described in the module
docstring, not a constant-term retraction argument. -/
@[hjo "lem_sweep_braid_preserves_aux"]
theorem braid_mem_auxSubalg (q : L) (i : ℕ) {F : Total L} (hF : F ∈ auxSubalg L) :
    braid q i F ∈ auxSubalg L := by
  rw [braid_apply]
  refine add_mem (swapAux_mem_auxSubalg i hF) (mul_mem (mul_mem ?_ (auxVar_mem_auxSubalg i))
    (dividedDiff_mem_auxSubalg i hF))
  rw [scal_eq_algebraMap]
  exact (auxSubalg L).algebraMap_mem _

/-- `HJO.Sweep.braid_mem_auxSubalg` for the letter read as an `L`-linear endomorphism, the form the
words of the sweep are built from. -/
theorem braidEnd_mem_auxSubalg (q : L) (i : ℕ) {F : Total L} (hF : F ∈ auxSubalg L) :
    braidEnd q i F ∈ auxSubalg L :=
  braid_mem_auxSubalg q i hF

private theorem cmAscWord_mem_auxSubalg_aux (q : L) (j : ℕ) {F : Total L} (hF : F ∈ auxSubalg L) :
    ∀ n i, j + 1 - i ≤ n → i ≤ j + 1 → cmAscWord q i j F ∈ auxSubalg L := by
  intro n
  induction n with
  | zero =>
    intro i h1 h2
    have hij : i = j + 1 := by omega
    subst hij
    rw [cmAscWord_self_pred, Module.End.one_apply]
    exact hF
  | succ n ih =>
    intro i h1 h2
    rcases le_or_gt i j with hle | hgt
    · rw [cmAscWord_apply_succ_left q hle]
      exact braid_mem_auxSubalg q i (ih (i + 1) (by omega) (by omega))
    · have hij : i = j + 1 := by omega
      subst hij
      rw [cmAscWord_self_pred, Module.End.one_apply]
      exact hF

/-- **An ascending word of braid letters preserves the auxiliary subalgebra**, on the range
`i ≤ j + 1` where `HJO.Sweep.cmAscWord` is a word in the *uninverted* letters — the empty word at
`i = j + 1` and `T_i ⋯ T_j` below it (`HJO.Sweep.cmAscWord_apply_succ_left`). Outside that range
`HJO.Sweep.cmAscWord` is a word of the inverted letters `T_i^{-1} = q^{-1}(T_i + q - 1)`, which the
subalgebra would also absorb — it contains `q⁻¹` whatever `q` is — so the restriction costs nothing
and is only the range the induction here covers. -/
theorem cmAscWord_mem_auxSubalg (q : L) {i j : ℕ} (hij : i ≤ j + 1) {F : Total L}
    (hF : F ∈ auxSubalg L) : cmAscWord q i j F ∈ auxSubalg L :=
  cmAscWord_mem_auxSubalg_aux q j hF (j + 1) i (Nat.sub_le _ _) hij

/-- **The staircase word preserves the auxiliary subalgebra**, at every shift `δ`, offset `c` and
height `m`: each of its blocks is the ascending word `T_{[c+m+1, c+m+δ]}`, whose left index is at
most one more than its right, so `HJO.Sweep.cmAscWord_mem_auxSubalg` applies to it. -/
theorem stairWord_mem_auxSubalg (q : L) (δ c : ℕ) :
    ∀ (m : ℕ) {H : Total L}, H ∈ auxSubalg L → stairWord q δ c m H ∈ auxSubalg L
  | 0, _, hH => by rw [stairWord_zero, Module.End.one_apply]; exact hH
  | m + 1, _, hH => by
    rw [stairWord_succ_apply]
    exact cmAscWord_mem_auxSubalg q (by omega) (stairWord_mem_auxSubalg q δ c m hH)

/-! ### The hypothesis rule `A`'s absorption was carrying -/

/-- **RULE `A` CONSUMES THE STAIRCASE ON EVERY `Λ`-FREE VECTOR, WITH NO SIDE CONDITION.**
`HJO.Sweep.dplus_stairWord_consume_of_mem_auxSubalg` asks for two memberships — that of `H` and
that of `S_{c,m}H` — and the second was discharged by computation at each use. It is now a theorem:
the staircase word is built from braid letters, and those preserve the subalgebra
(`HJO.Sweep.stairWord_mem_auxSubalg`, resting on `HJO.Sweep.braid_mem_auxSubalg`). So

`d^♭_+{}^{(c+m)}(S_{c,m}H) = q^m·d^♭_+{}^{(c)}(H)` for every `H ∈ HJO.Sweep.auxSubalg`.

**Spends nothing beyond the cited lemma**: no hypothesis on `q`, no hypothesis on the offset or the
height. Stated here, next to the membership lemmas it rests on, rather than in
`HJO/Shuffle/SweepConsumeRuleA.lean`, which keeps the version with both hypotheses. -/
theorem dplus_stairWord_consume (q : L) (c m : ℕ) {H : Total L} (hH : H ∈ auxSubalg L) :
    dplus q (c + m) (stairWord q 1 c m H) = q ^ m • dplus q c H :=
  dplus_stairWord_consume_of_mem_auxSubalg q c m hH (stairWord_mem_auxSubalg q 1 c m hH)

end HJO.Sweep
