/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.SweepTrainWidth
public import HJO.Shuffle.SweepQshiftElemSymm
public import HJO.CMStructure.StarConjRel1

/-! # `d_-`, `d_+` and `Δ` read at widths `3` and `4`

`HJO/Shuffle/SweepBraidMonomial.lean` and `HJO/Shuffle/SweepTrainWidth.lean` give the
braid letter and the ascending train at every index and every width. This file spends that machinery
on the shapes a sweep word at width `3` or `4` presents, and reads each off at those two widths.
Every general statement here is proved at general `k`; the width-`3` and width-`4` corollaries carry
no separate argument.

## The three shapes

* **The staircase with a symmetric-function coefficient.**
  `HJO.Sweep.dplus_C_elemSymm_one_mul_auxVarProd`:
  `d_+^{(k)}(e_1y_1⋯y_k) = -e_1y_1⋯y_{k+1} - (q-1)q^ky_1^2y_2⋯y_{k+1}`, at every width. This is the
  general-width form of the width-`1` computation
  `HJO.Sweep.dplus_one_C_elemSymm_one_mul_X_zero`, and it is where the displacement
  `HJO.Sweep.qshift_C_elemSymm_one` enters: the extra letter `(q-1)y_{k+1}` that `τ_{k+1,k+1}` puts
  into `e_1` makes the train see `y_{k+1}` twice, and the second copy walks down to `y_1` emitting
  `q^k`.
* **The square of the last variable.** `HJO.Sweep.cmAscWord_one_auxVar_last_sq`:
  `T_{1↗k+2}(y_{k+2}^2) = q^{k+1}y_1^2 + (q-1)q^ky_1(y_2 + ⋯ + y_{k+2})`. This is the first shape at
  which the train **branches** — the letter `T_i` on `y_{i+1}^2` produces two monomials, not one —
  and the sum on the right is the whole of that branching, one term per letter. It gives the corner
  on the staircase times its last variable, `HJO.Sweep.corner_mul_auxVar_last_of_swapAux_eq`.
* **The staircase itself**, where the train is the identity: `HJO.Sweep.corner_auxVarProd` and the
  earlier `HJO.Sweep.dplus_auxVarProd`.

## The consistency checks

Three earlier values are the ones the general statements above must reproduce, and each pins
something a general statement could have got wrong:

* `HJO.Sweep.dplus_one_C_elemSymm_one_mul_X_zero` is
  `HJO.Sweep.dplus_C_elemSymm_one_mul_auxVarProd` at `k = 1`, whose coefficient `(q-1)q^k` is then
  `q(q-1)`. A missing `q^k` would break it.
* `HJO.Sweep.corner_two_X_zero_mul_X_one` is `HJO.Sweep.corner_auxVarProd` at `k = 1`, which pins
  the exponent of `q`.
* `HJO.Sweep.dminus_three_prod` is `HJO.Sweep.dminus_auxVarProd` at `k = 2`, which pins the sign.

## Genericity

`q ≠ 0` and `q ≠ 1` are spent exactly where `HJO.Sweep.corner` occurs, for the reasons recorded in
`HJO/Shuffle/SweepTrainWidth.lean`: `HJO.Sweep.corner` carries `(q-1)^{-1}`, so at `q = 1` the
operator is the zero map in a field and the statements are false rather than vacuous, and the
general closed form for the corner reads `q ≠ 0` through `HJO.Sweep.dplus_eq_neg_cmAscWord_cmDPlus`.
The statements about `d_-`, `d_+` and the train spend **nothing**: no inverse of `q` occurs in them,
and they hold at `q = 0` and `q = 1` as written. `u` does not occur anywhere in this file — none of
`HJO.Sweep.dminus`, `HJO.Sweep.dplus`, `HJO.Sweep.corner` reads it.

## What is *not* here

A sweep word reaching width `4` composes eight or more of these letters, and the trace sums of
`HJO/Shuffle/SweepInductionInstanceTwo.lean` are not evaluated here. What is supplied is the
per-operator evaluation at those widths, which is the input such an evaluation needs; the assembly
is not carried out here.

## References

A. Mellit, *Toric braids and `(m,n)`-parking functions*, §3.
-/

@[expose] public section

namespace HJO.Sweep

open MvPolynomial HJO.Sym

section Field

variable {L : Type*} [Field L] {q : L}

/-! ### The staircase at small width, unfolded -/

theorem auxVarProd_one : auxVarProd L 1 = (MvPolynomial.X 0 : Total L) := by
  rw [auxVarProd]
  simp

theorem auxVarProd_two :
    auxVarProd L 2 = (MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 := by
  rw [auxVarProd]
  simp [Finset.prod_range_succ]

theorem auxVarProd_three :
    auxVarProd L 3 = (MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2 := by
  rw [auxVarProd]
  simp [Finset.prod_range_succ]

theorem auxVarProd_four :
    auxVarProd L 4
      = (MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2 * MvPolynomial.X 3 := by
  rw [auxVarProd]
  simp [Finset.prod_range_succ]

/-- `y_1⋯y_k` lies in the subalgebra generated by the auxiliary variables. -/
theorem auxVarProd_mem_auxSubalg (k : ℕ) : auxVarProd L k ∈ auxSubalg L := by
  rw [auxVarProd]
  refine prod_mem fun j _ => ?_
  have h : (MvPolynomial.X j : Total L) = auxVar (j + 1) := by rw [auxVar, Nat.add_sub_cancel]
  rw [h]
  exact auxVar_mem_auxSubalg (j + 1)

/-! ### The braid letter on the square of the variable it raises -/

/-- **`T_i(y_{i+1}^2) = qy_i^2 + (q-1)y_iy_{i+1}`.** The first shape at which one letter produces
*two* monomials: `HJO.Sweep.braid_auxVar_pow_mul_auxVar_pow'` at `b = 0`, `c = 2`, where the
geometric sum has two terms. Unconditional in `q`. -/
theorem braid_auxVar_succ_sq (q : L) {i : ℕ} (hi : 1 ≤ i) :
    braid q i ((auxVar (i + 1) : Total L) ^ 2)
      = scal q * (auxVar i : Total L) ^ 2
        + scal (q - 1) * ((auxVar i : Total L) * auxVar (i + 1)) := by
  have hqs : (scal q : Total L) = 1 + scal (q - 1) := by
    rw [← scal_one (L := L), ← scal_add]
    congr 1
    ring
  have h := braid_auxVar_pow_mul_auxVar_pow' q hi (L := L) 0 2
  rw [Finset.sum_range_succ, Finset.sum_range_one] at h
  simp only [pow_zero, one_mul, mul_one, zero_add,
    show (2 : ℕ) - 1 - 0 = 1 from rfl, show (2 : ℕ) - 1 - 1 = 0 from rfl, pow_one] at h
  rw [h, hqs]
  ring

/-! ### The ascending train on the square of the last variable: the branching shape -/

/-- **`T_{1↗k+2}(y_{k+2}^2) = q^{k+1}y_1^2 + (q-1)q^k y_1(y_2 + y_3 + ⋯ + y_{k+2})`**, at every
width and for every `q`.

The train **branches** here, and the sum is exactly that branching. At each letter the argument is
`y_i^0y_{i+1}^2`, which `HJO.Sweep.braid_auxVar_succ_sq` splits into `qy_i^2` — the branch that
walks on down — and `(q-1)y_iy_{i+1}`, which is symmetric-times-one-variable and is finished by
`HJO.Sweep.cmAscWord_one_auxVar_last` in one step. So the sum has one term per letter, the term of
the `t`-th letter being `y_1y_{t+1}`, and every term carries the same power `q^k`: the recursion is
`A_{k+1} = qA_k + (q-1)q^ky_1y_{k+2}`, which multiplies the previously accumulated terms by `q`
while the new one arrives already carrying `q^k`.

No hypothesis on `q`: nothing is inverted. -/
theorem cmAscWord_one_auxVar_last_sq (q : L) (m : ℕ) :
    cmAscWord q 1 (m + 1) ((auxVar (m + 2) : Total L) ^ 2)
      = scal (q ^ (m + 1)) * (auxVar 1 : Total L) ^ 2
        + scal ((q - 1) * q ^ m) * ((auxVar 1 : Total L)
            * ∑ j ∈ Finset.range (m + 1), (auxVar (j + 2) : Total L)) := by
  have hbe : ∀ (i : ℕ) (G : Total L), braidEnd q i G = braid q i G := fun _ _ => rfl
  have hpow : ∀ n : ℕ, (scal (q ^ n) : Total L) = scal q ^ n := by
    intro n
    rw [scal, scal, ← map_pow, ← map_pow]
  induction m with
  | zero =>
    rw [cmAscWord_self q 1, hbe, braid_auxVar_succ_sq q (i := 1) le_rfl, Finset.sum_range_one,
      pow_zero, mul_one, pow_one]
  | succ m ih =>
    have hstep : braid q (m + 2) ((auxVar (m + 1 + 2) : Total L) ^ 2)
        = scal q * (auxVar (m + 2) : Total L) ^ 2
          + scal (q - 1) * ((auxVar (m + 2) : Total L) * auxVar (m + 3)) := by
      have h := braid_auxVar_succ_sq q (i := m + 2) (L := L) (by omega)
      simpa using h
    have hfix : ∀ j, 1 ≤ j → j ≤ m + 1 →
        swapAux L j (auxVar (m + 3) : Total L) = auxVar (m + 3) :=
      fun _ _ _ => swapAux_auxVar_of_ne (by omega) (by omega) (by omega)
    have hlast : cmAscWord q 1 (m + 1) ((auxVar (m + 3) : Total L) * auxVar (m + 2))
        = (auxVar (m + 3) : Total L) * (scal (q ^ (m + 1)) * auxVar 1) := by
      rw [cmAscWord_mul_of_swapAux_eq q (by omega) hfix]
      congr 1
      exact cmAscWord_one_auxVar_last q (m + 1)
    have hsum : (∑ j ∈ Finset.range (m + 1 + 1), (auxVar (j + 2) : Total L))
        = (∑ j ∈ Finset.range (m + 1), (auxVar (j + 2) : Total L)) + auxVar (m + 1 + 2) :=
      Finset.sum_range_succ _ _
    rw [cmAscWord_one_succ_apply, hstep, map_add, cmAscWord_scal_mul, cmAscWord_scal_mul, ih,
      show (auxVar (m + 2) : Total L) * auxVar (m + 3)
        = (auxVar (m + 3) : Total L) * auxVar (m + 2) from mul_comm _ _, hlast, hsum,
      show (auxVar (m + 1 + 2) : Total L) = auxVar (m + 3) from by norm_num]
    simp only [scal_mul, hpow]
    ring

/-- **`T_{1↗k+2}(Sy_{k+2}^2)`** for `S` symmetric in `y_1, …, y_{k+2}`: the train is linear over
what its every letter fixes, so `HJO.Sweep.cmAscWord_one_auxVar_last_sq` carries over with `S`
riding through. -/
theorem cmAscWord_one_mul_auxVar_last_sq (q : L) (m : ℕ) {S : Total L}
    (hS : ∀ j, 1 ≤ j → j ≤ m + 1 → swapAux L j S = S) :
    cmAscWord q 1 (m + 1) (S * (auxVar (m + 2) : Total L) ^ 2)
      = S * (scal (q ^ (m + 1)) * (auxVar 1 : Total L) ^ 2
          + scal ((q - 1) * q ^ m) * ((auxVar 1 : Total L)
              * ∑ j ∈ Finset.range (m + 1), (auxVar (j + 2) : Total L))) := by
  rw [cmAscWord_mul_of_swapAux_eq q (by omega) hS, cmAscWord_one_auxVar_last_sq]

/-- **`d_+^{(3)}(y_1y_2y_3) = -y_1y_2y_3y_4`**, the width-`3` reading of
`HJO.Sweep.dplus_auxVarProd`. No power of `q` appears: the target is symmetric in all four
variables. -/
theorem dplus_three_prod (q : L) :
    dplus q 3 ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2)
      = -((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2
          * MvPolynomial.X 3) := by
  have h := dplus_auxVarProd (L := L) q 3
  rwa [auxVarProd_three, show (3 : ℕ) + 1 = 4 from rfl, auxVarProd_four] at h

/-- **`d_+^{(4)}(y_1y_2y_3y_4) = -y_1y_2y_3y_4y_5`**, the width-`4` reading of
`HJO.Sweep.dplus_auxVarProd`. -/
theorem dplus_four_prod (q : L) :
    dplus q 4 ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2
        * MvPolynomial.X 3)
      = -(auxVarProd L 5) := by
  have h := dplus_auxVarProd (L := L) q 4
  rwa [auxVarProd_four, show (4 : ℕ) + 1 = 5 from rfl] at h

end Field

section Newton

variable {L : Type*} [Field L] [Algebra ℚ L] {q : L}

/-! ### `d_+` on the staircase with an `e_1` coefficient, at every width -/

/-- **`d_+^{(k)}(e_1y_1⋯y_k) = -e_1y_1⋯y_{k+1} - (q-1)q^k y_1^2y_2⋯y_{k+1}`**, at every width and
for every `q`.

`τ_{k+1,k+1}` displaces `e_1` to `e_1 + (q-1)y_{k+1}` (`HJO.Sweep.qshift_C_elemSymm_one`), so
`HJO.Sweep.dplus` hands the train two vectors: the symmetric `e_1y_1⋯y_{k+1}`, which it fixes, and
`(q-1)y_1⋯y_{k+1}·y_{k+1}`, whose extra last variable walks down to `y_1` emitting `q^k`
(`HJO.Sweep.cmAscWord_one_mul_auxVar_last`).

At `k = 1` this is `HJO.Sweep.dplus_one_C_elemSymm_one_mul_X_zero`, whose coefficient
`q(q-1)` is what pins the `q^k`. -/
theorem dplus_C_elemSymm_one_mul_auxVarProd (q : L) (k : ℕ) :
    dplus q k (MvPolynomial.C (elemSymm L 1) * auxVarProd L k)
      = -(MvPolynomial.C (elemSymm L 1) * auxVarProd L (k + 1))
        - scal ((q - 1) * q ^ k) * (auxVarProd L (k + 1) * (auxVar 1 : Total L)) := by
  have hw : ∀ G : Total L, trainUpEnd q 1 (k + 1) G = cmAscWord q 1 k G := fun _ => rfl
  have hsym : ∀ j, 1 ≤ j → j ≤ k → swapAux L j (auxVarProd L (k + 1)) = auxVarProd L (k + 1) :=
    fun _ _ hj2 => swapAux_auxVarProd hj2
  have hsymC : ∀ j, 1 ≤ j → j ≤ k →
      swapAux L j (MvPolynomial.C (elemSymm L 1) : Total L) = MvPolynomial.C (elemSymm L 1) :=
    fun _ _ _ => swapAux_C _ _
  have hq : qshift q (k + 1) (MvPolynomial.C (elemSymm L 1) * auxVarProd L k)
      = (MvPolynomial.C (elemSymm L 1) + scal (q - 1) * auxVar (k + 1)) * auxVarProd L k := by
    rw [map_mul, qshift_auxVarProd, qshift_C_elemSymm_one]
  have hexp : (auxVar (k + 1) : Total L)
        * ((MvPolynomial.C (elemSymm L 1) + scal (q - 1) * auxVar (k + 1)) * auxVarProd L k)
      = MvPolynomial.C (elemSymm L 1) * auxVarProd L (k + 1)
        + scal (q - 1) * (auxVarProd L (k + 1) * (auxVar (k + 1) : Total L)) := by
    rw [auxVarProd_succ]
    ring
  rw [dplus_apply, hq, hexp, hw, map_add, cmAscWord_mul_of_swapAux_eq q (by omega) hsymC,
    cmAscWord_one_eq_self_of_swapAux_eq q k hsym, cmAscWord_scal_mul,
    cmAscWord_one_mul_auxVar_last q k hsym, scal_mul]
  ring

/-! ### `d_-` on the staircase, at every width -/

/-- **`d_-^{(k+1)}(y_1⋯y_{k+1}) = -e_1y_1⋯y_k`**, at every width and for every `q`.

`HJO.Sweep.dminus` at a single power of the last variable is `HJO.Sweep.dminus_auxVar_pow_mul`,
whose value is `B_1` of the Hall--Littlewood family applied to the remaining monomial; on a monomial
`B_1` is multiplication by `Ω_1 = -e_1`. At `k = 2` this is
`HJO.Sweep.dminus_three_prod`, which is what pins the sign. -/
theorem dminus_auxVarProd (q : L) (k : ℕ) :
    dminus q (k + 1) (auxVarProd L (k + 1))
      = -(MvPolynomial.C (elemSymm L 1) * auxVarProd L k) := by
  have hmem : auxVarProd L k ∈ piece L k := auxVarProd_mem_piece L k
  have hZ : auxVarProd L k ∈ auxSubalg L := auxVarProd_mem_auxSubalg k
  have halt : (MvPolynomial.C (elemSymmAlt L (1 : ℤ)) : Total L)
      = -MvPolynomial.C (elemSymm L 1) := by
    rw [show ((1 : ℤ)) = ((1 : ℕ) : ℤ) from rfl, elemSymmAlt_natCast, pow_one, map_mul, map_neg,
      map_one, neg_one_mul]
  rw [show auxVarProd L (k + 1) = (auxVar (k + 1) : Total L) ^ 1 * auxVarProd L k from by
      rw [auxVarProd_succ, pow_one]; ring,
    dminus_auxVar_pow_mul q k 1 hmem, ← mul_one (auxVarProd L k),
    bopExt_auxSubalg_mul q _ hZ, bopExt_one, Nat.cast_one, halt]
  ring

/-! ### `Δ` on the staircase times its last variable -/

/-- **`Δ^{(k+2)}(Sy_{k+2}) = -S(q^{k+1}y_1^2 + (q-1)q^ky_1(y_2 + ⋯ + y_{k+2}))`** for `S ∈ V_{k+2}`
symmetric in `y_1, …, y_{k+2}`, whenever `q ∉ {0, 1}`.

The first corner value whose answer is not a single monomial: `HJO.Sweep.corner` inserts a second
`y_{k+2}` and the train branches, which is `HJO.Sweep.cmAscWord_one_auxVar_last_sq`. -/
theorem corner_mul_auxVar_last_of_swapAux_eq (hq0 : q ≠ 0) (hq1 : q ≠ 1) (m : ℕ) {S : Total L}
    (hS : S ∈ piece L (m + 2)) (hsym : ∀ j, 1 ≤ j → j ≤ m + 1 → swapAux L j S = S) :
    corner q (m + 2) (S * (auxVar (m + 2) : Total L))
      = -(S * (scal (q ^ (m + 1)) * (auxVar 1 : Total L) ^ 2
          + scal ((q - 1) * q ^ m) * ((auxVar 1 : Total L)
              * ∑ j ∈ Finset.range (m + 1), (auxVar (j + 2) : Total L)))) := by
  have hmem : S * (auxVar (m + 2) : Total L) ∈ piece L (m + 1 + 1) :=
    mul_mem hS (auxVar_mem_piece (by omega) le_rfl)
  rw [show (m : ℕ) + 2 = m + 1 + 1 from rfl,
    corner_eq_neg_cmAscWord_auxVar_mul hq0 hq1 (m + 1) hmem,
    show (auxVar (m + 1 + 1) : Total L) * (S * auxVar (m + 1 + 1))
      = S * (auxVar (m + 2) : Total L) ^ 2 from by ring,
    cmAscWord_one_mul_auxVar_last_sq q m hsym]

/-- **`Δ^{(k+2)}(y_1⋯y_{k+2}·y_{k+2})`**: `HJO.Sweep.corner_mul_auxVar_last_of_swapAux_eq` at the
staircase. -/
theorem corner_auxVarProd_mul_auxVar_last (hq0 : q ≠ 0) (hq1 : q ≠ 1) (m : ℕ) :
    corner q (m + 2) (auxVarProd L (m + 2) * (auxVar (m + 2) : Total L))
      = -(auxVarProd L (m + 2) * (scal (q ^ (m + 1)) * (auxVar 1 : Total L) ^ 2
          + scal ((q - 1) * q ^ m) * ((auxVar 1 : Total L)
              * ∑ j ∈ Finset.range (m + 1), (auxVar (j + 2) : Total L)))) :=
  corner_mul_auxVar_last_of_swapAux_eq hq0 hq1 m (auxVarProd_mem_piece L (m + 2))
    fun _ _ hj2 => swapAux_auxVarProd (by omega)

/-! ### The readings at widths `3` and `4`

Nothing below is new content: each is one of the general statements above with `k` set to `2` or `3`
and the staircase unfolded. They are stated because they are the shape a sweep word at those widths
presents, and because a width-specific statement is checkable against a hand computation. -/

/-- **`d_+^{(3)}(e_1y_1y_2y_3) = -e_1y_1y_2y_3y_4 - (q-1)q^3y_1^2y_2y_3y_4`**, the width-`3` reading
of `HJO.Sweep.dplus_C_elemSymm_one_mul_auxVarProd`. -/
theorem dplus_three_C_elemSymm_one_mul_prod (q : L) :
    dplus q 3 (MvPolynomial.C (elemSymm L 1)
        * ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2))
      = -(MvPolynomial.C (elemSymm L 1) * ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1
            * MvPolynomial.X 2 * MvPolynomial.X 3))
        - scal ((q - 1) * q ^ 3) * ((MvPolynomial.X 0 : Total L) ^ 2 * MvPolynomial.X 1
            * MvPolynomial.X 2 * MvPolynomial.X 3) := by
  have h := dplus_C_elemSymm_one_mul_auxVarProd (L := L) q 3
  rw [auxVarProd_three, show (3 : ℕ) + 1 = 4 from rfl, auxVarProd_four] at h
  rw [h, show (auxVar 1 : Total L) = MvPolynomial.X 0 from rfl]
  ring

/-- **`d_+^{(4)}(e_1y_1y_2y_3y_4) = -e_1y_1⋯y_5 - (q-1)q^4y_1^2y_2y_3y_4y_5`**, the width-`4`
reading of `HJO.Sweep.dplus_C_elemSymm_one_mul_auxVarProd`. -/
theorem dplus_four_C_elemSymm_one_mul_prod (q : L) :
    dplus q 4 (MvPolynomial.C (elemSymm L 1)
        * ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2 * MvPolynomial.X 3))
      = -(MvPolynomial.C (elemSymm L 1) * auxVarProd L 5)
        - scal ((q - 1) * q ^ 4) * (auxVarProd L 5 * (MvPolynomial.X 0 : Total L)) := by
  have h := dplus_C_elemSymm_one_mul_auxVarProd (L := L) q 4
  rwa [auxVarProd_four, show (4 : ℕ) + 1 = 5 from rfl,
    show (auxVar 1 : Total L) = MvPolynomial.X 0 from rfl] at h

/-- **`d_-^{(4)}(y_1y_2y_3y_4) = -e_1y_1y_2y_3`**, the width-`4` reading of
`HJO.Sweep.dminus_auxVarProd`. The width-`3` reading is
`HJO.Sweep.dminus_three_prod`. -/
theorem dminus_four_prod (q : L) :
    dminus q 4 ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2
        * MvPolynomial.X 3)
      = -(MvPolynomial.C (elemSymm L 1) * ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1
          * MvPolynomial.X 2)) := by
  have h := dminus_auxVarProd (L := L) q 3
  rwa [show (3 : ℕ) + 1 = 4 from rfl, auxVarProd_four, auxVarProd_three] at h

/-- **`Δ^{(3)}(y_1y_2y_3) = -q^2y_1^2y_2y_3`**, the width-`3` reading of
`HJO.Sweep.corner_auxVarProd`. -/
theorem corner_three_prod (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 3 ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2)
      = -(scal (q ^ 2) * ((MvPolynomial.X 0 : Total L) ^ 2 * MvPolynomial.X 1
          * MvPolynomial.X 2)) := by
  have h := corner_auxVarProd (L := L) hq0 hq1 2
  rw [show (2 : ℕ) + 1 = 3 from rfl, auxVarProd_three,
    show (auxVar 1 : Total L) = MvPolynomial.X 0 from rfl] at h
  rw [h]
  ring

/-- **`Δ^{(4)}(y_1y_2y_3y_4) = -q^3y_1^2y_2y_3y_4`**, the width-`4` reading of
`HJO.Sweep.corner_auxVarProd`. -/
theorem corner_four_prod (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 4 ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2
        * MvPolynomial.X 3)
      = -(scal (q ^ 3) * ((MvPolynomial.X 0 : Total L) ^ 2 * MvPolynomial.X 1
          * MvPolynomial.X 2 * MvPolynomial.X 3)) := by
  have h := corner_auxVarProd (L := L) hq0 hq1 3
  rw [show (3 : ℕ) + 1 = 4 from rfl, auxVarProd_four,
    show (auxVar 1 : Total L) = MvPolynomial.X 0 from rfl] at h
  rw [h]
  ring

/-- **`Δ^{(3)}(y_1y_2y_3^2) = -q^2y_1^3y_2y_3 - q(q-1)y_1^2y_2y_3(y_2+y_3)`**, the width-`3`
reading of `HJO.Sweep.corner_auxVarProd_mul_auxVar_last` — the first corner value at width `3` whose
answer is not a single monomial. -/
theorem corner_three_prod_mul_X_two (hq0 : q ≠ 0) (hq1 : q ≠ 1) :
    corner q 3 ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2
        * MvPolynomial.X 2)
      = -(scal (q ^ 2) * ((MvPolynomial.X 0 : Total L) ^ 3 * MvPolynomial.X 1 * MvPolynomial.X 2))
        - scal ((q - 1) * q) * ((MvPolynomial.X 0 : Total L) ^ 2 * MvPolynomial.X 1
            * MvPolynomial.X 2 * (MvPolynomial.X 1 + MvPolynomial.X 2)) := by
  have h := corner_auxVarProd_mul_auxVar_last (L := L) hq0 hq1 1
  rw [show (1 : ℕ) + 2 = 3 from rfl, auxVarProd_three,
    show (auxVar 3 : Total L) = MvPolynomial.X 2 from by rw [auxVar],
    show (auxVar 1 : Total L) = MvPolynomial.X 0 from rfl,
    show (1 : ℕ) + 1 = 2 from rfl] at h
  rw [h, Finset.sum_range_succ, Finset.sum_range_one,
    show (auxVar (0 + 2) : Total L) = MvPolynomial.X 1 from by rw [auxVar],
    show (auxVar (1 + 2) : Total L) = MvPolynomial.X 2 from by rw [auxVar], pow_one]
  ring

/-! ### The consistency checks

Two earlier values re-derived from the general statements above, their conclusions being verbatim
those of the earlier theorems. The third check, `HJO.Sweep.corner_two_X_zero_mul_X_one` from the
general corner, is already proved as `HJO.Sweep.corner_two_X_zero_mul_X_one_of_general`
(`HJO/Shuffle/CornerClosedForm.lean`) and is not repeated. -/

/-- **Check at width `1`: `d_+^{(1)}(e_1y_1) = -e_1y_1y_2 - q(q-1)y_1^2y_2`**, the conclusion of
`HJO.Sweep.dplus_one_C_elemSymm_one_mul_X_zero`, obtained from
`HJO.Sweep.dplus_C_elemSymm_one_mul_auxVarProd` at `k = 1`.

This is the data point that pins the factor `q^k`. The general statement puts the extra `y_{k+1}`
*inside* the train, so the train walks it down to `y_1` and emits one `q` per letter; had the power
been placed outside, the coefficient here would be `(q-1)` rather than `q(q-1)` and this check would
fail. -/
theorem dplus_one_C_elemSymm_one_mul_X_zero_of_general (q : L) :
    dplus q 1 (MvPolynomial.C (elemSymm L 1) * (MvPolynomial.X 0 : Total L))
      = -(MvPolynomial.C (elemSymm L 1) * ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1))
        - scal (q * (q - 1)) * ((MvPolynomial.X 0 : Total L) ^ 2 * MvPolynomial.X 1) := by
  have h := dplus_C_elemSymm_one_mul_auxVarProd (L := L) q 1
  rw [auxVarProd_one, show (1 : ℕ) + 1 = 2 from rfl, auxVarProd_two,
    show (auxVar 1 : Total L) = MvPolynomial.X 0 from rfl] at h
  rw [h, show q * (q - 1) = (q - 1) * q ^ 1 from by ring]
  ring

/-- **Check at width `3`: `d_-^{(3)}(y_1y_2y_3) = -e_1y_1y_2`**, the conclusion of
`HJO.Sweep.dminus_three_prod`, obtained from `HJO.Sweep.dminus_auxVarProd` at `k = 2`. This is the
data point that pins the sign: `Ω_1 = -e_1`, and a lost negation would break it. -/
theorem dminus_three_prod_of_general (q : L) :
    dminus q 3 ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1 * MvPolynomial.X 2)
      = -(MvPolynomial.C (elemSymm L 1) * ((MvPolynomial.X 0 : Total L) * MvPolynomial.X 1)) := by
  have h := dminus_auxVarProd (L := L) q 2
  rwa [show (2 : ℕ) + 1 = 3 from rfl, auxVarProd_three, auxVarProd_two] at h

end Newton

end HJO.Sweep

end
