/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import HJO.Shuffle.SweepStageWordTwoThreeTwoValue
public meta import HJO.Attr

/-! # The one-part recursion does not descend to the clause's own values

The `hlhs` clause at `(a,b) = (2,3)` and a one-part composition `[A]` is, by
`HJO.Mellit.lhsAt_two_three_singleton_iff_bop`, the single identity

  `Θ(h_A)(1) = -∑_m B_m((G_A)_m)`,

and both sides now have a recursion in `A`:

* the **sweep** side is generated by one fixed operator — `HJO.Mellit.stageWordTotal_singleton_succ`
  says `G_{A+1} = Z^{(1)}_{2,3}(G_A)`, unconditionally and at every `A`, and the sweep value is
  `S_A = ct(d_-^{(1)}G_A)` (`HJO.Sweep.constantCoeff_dminus_one_of_mem_piece`);
* the **creation** side is `HJO.Mellit.theta_completeHomog_apply_one_smul_eq_sum_qop`,
  `(1 - v^A)Θ(h_A)(1) = (v-1)v^{A-1}∑_{s=1}^{A}Θ(h_{A-s})(Q_{2s,3s}(1))` with `v = qu`.

An induction on `A` that carries only the clause's own data — the value `S_A` on one side, the value
`Θ(h_A)(1)` on the other — needs each recursion to be a function of that value. **Neither is**, and
this file proves this for the sweep side.

## What is proved

* `HJO.Sweep.not_exists_factorization_replicated_two_three` — **`ct ∘ d_-^{(1)} ∘ Z^{(1)}_{2,3}`
  does not factor through `ct ∘ d_-^{(1)}` on `V_1`.** So the one-part recursion
  `G_{A+1} = Z^{(1)}_{2,3}(G_A)` does **not** descend to a recursion in the sweep values `S_A`: the
  step must be run on the vector `G_A`, which is what the decision procedure already does,
  and no rearrangement of it turns `S_A ↦ S_{A+1}` into a map on `Λ`.

  The witness is the one the level-raising refutation uses,
  `F_0 = Ce_1 + qy_1` (`HJO.Sweep.levelKernelOne`): it lies in `V_1`, `ct(d_-^{(1)}F_0) = 0`
  (`HJO.Sweep.constantCoeff_lowerRun_one_levelKernelOne`), and the composite sends it to
  `qu[e_2^2 + (q+u-1)e_1e_3 + (q^2+qu-q+u^2-u)e_4] ≠ 0`.

  This is the **one-part** companion of `HJO.Sweep.not_exists_factorization_two_three`, which
  refutes the *level-raising* factorization `ℓ ↦ ℓ+1` of the composition induction. The two are
  independent statements about two different operators — the replicated letter of
  `HJO.Mellit.replicatedLetter` at level `0`, and the stage of `HJO.Mellit.stage` at level `1` — and
  neither implies the other.

* `HJO.Sweep.constantCoeff_dminus_one_replicatedTotal_levelKernelOne` — the defect, in closed form.
  Its route is three evaluations of `z_1` on a monomial of `V_1` and nothing else, and the
  intermediate values are unusually small: `z_1(F_0) = quy_1`
  (`HJO.Sweep.zopOneStar_one_levelKernelOne`) and
  `Z^{(1)}_{2,3}(F_0) = quy_1^2Ce_2 - qu^2y_1^3Ce_1 + qu^3y_1^4`
  (`HJO.Sweep.replicatedTotal_two_three_zero_levelKernelOne`).

* `HJO.Sweep.smul_constantCoeff_dminus_one_replicated_eq_smul_lowerRun_two_stageTotal` — **a
  consistency check.** The defect computed here and the defect of the level-raising refutation
  (`HJO.Sweep.constantCoeff_lowerRun_two_stageTotal_levelKernelOne_two_three`) are the *same*
  element of `Λ` up to a scalar: `(q-1)·(this defect) = q·(that defect)`, both being a multiple of
  `e_2^2 + (q+u-1)e_1e_3 + (q^2+qu-q+u^2-u)e_4`. The two are computed by routes that share no
  lemma — this one through `HJO.Sweep.zopOneStar_one_auxVar_pow_mul_C` at the level `1`, that one
  through the train `T_1^{-1}`, `HJO.Sweep.zCommTwo_monomial'` and seven compositions `B_jB_m` at
  the level `2` — so their agreeing is a check on both, and a sign lost on either would break it.

* `HJO.Mellit.theta_completeHomog_apply_one_smul_eq_sum_theta_mul` — the creation side's recursion
  with its inputs named as what they are: `Θ(h_{A-s})(Q_{2s,3s}(1)) = Θ(h_{A-s}U_s)(1)`, because `Θ`
  is an algebra homomorphism and `Q_{2s,3s} = Θ(U_s)`. So the recursion's inputs are the values of
  the vacuum map `f ↦ Θ(f)(1)` at the **products** `h_{A-s}U_s`, and `h_A` is not a polynomial in
  `U_1, …, U_{A-1}` (`HJO.Sym.completeHomog_not_mem_adjoin_axisGen`), so those products are not
  values the one-part clauses mention. **This is a change of vocabulary and not a reduction**: it is
  one rewrite by `map_mul` in each direction, and the iff would go through with no hypotheses. Its
  only purpose is to name the quantifier that remains.

## What is NOT claimed

Exactly the caveat `HJO.Sym.ladderTwoThree_apply_one_not_determined` carries, which this mirrors on
the other side of the clause: what is refuted is reading a value recursion **off the step**. A map
`φ` witnessing the factorization must be defined on all of `Λ`, and `F_0` is not a stage word — so
nothing here says the family `A ↦ S_A` satisfies no recursion for some other reason, and nothing
here refutes `hlhs`. What is settled is that the datum an induction on `A` must carry is the vector
`G_A` on the sweep side and the operator `Θ(h_j)` on the creation side, not the two values the
clause equates.

Nor does anything here bear on `A = 2`, which is **decided**:
`HJO.Mellit.lhsAt_two_three_two_of_axis` proves the clause at `[2]` at every slope homomorphism.

## Genericity

`HJO.Sweep.zopOneStar_one_C_elemSymm_one`, `HJO.Sweep.zopOneStar_one_auxVar_mul_C_one` and
`HJO.Sweep.zopOneStar_one_levelKernelOne`: `q ≠ 1` alone, the scalar `q/(1-q)` of `HJO.Sweep.zop`.
In a field `0⁻¹ = 0`, so at `q = 1` that scalar is `0` and `z_1` is the zero map; the bracket these
lemmas evaluate is divisible by `1 - q` and the division is where the hypothesis is spent.

`HJO.Sweep.replicatedTotal_two_three_zero_levelKernelOne` and everything downstream add `q ≠ 0` and
`u ≠ 0`, which are the `(qu)^{-1}` of `HJO.Sweep.slopeOperator`: at `q = 0` or `u = 0` the letter
`(qu)^{-1}z_1` is the **zero map**, the defect genuinely is `0`, and the factorization is not
refuted there — so these are not removable and the statements would be *false* without them, not
vacuous. They are also what makes the leading coefficient `qu` of the defect nonzero.

`HJO.Mellit.theta_completeHomog_apply_one_smul_eq_sum_theta_mul`: `qu ≠ 0` and `qu ≠ 1`, verbatim
`HJO.Mellit.theta_completeHomog_apply_one_smul_eq_sum_qop`'s, which are the normalising scalar
`v/(v-1)` of `HJO.Sym.axisGen`: at `qu = 1` every `U_k` is `0` (`HJO.Sym.axisGen_eq_zero`) and
`Θ(h_A)` is not determined at all.

At algebraically independent `q, u` every one of these holds, and `(2,3)` is coprime with
`1 < a < b`, the range the `hlhs` binder quantifies over.

## Implementation notes

These are values of `HJO.Mellit.replicatedLetter`, `HJO.Sweep.zop` and `HJO.Sym.Bop` and a negative
fact about a proof route; none of them is a step of the proof of the main theorem, and the `hlhs`
clause itself is the subject of `HJO.Mellit.lhsRewrite_sweepWitness`.

## References

This file concerns `HJO.Mellit.lhsRewrite_sweepWitness`, `HJO.Mellit.stage`,
`HJO.Mellit.replicatedLetter`, `HJO.Sweep.zop`, `HJO.Sweep.slopeOperator`, `HJO.Sym.Bop`,
`HJO.Sweep.dplusStar`, `HJO.Sweep.dminus`, `HJO.Sym.Qop`, `HJO.Sym.IsSlopeHom`, `HJO.Sym.axisGen`,
`HJO.Sym.completeHomog`, `HJO.Sym.elemSymm`.
-/

@[expose] public section

-- Every computation below closes on a polynomial identity in the `e`-monomials and the scalars
-- `C q`, `C u`, and each is normalised by the *same* rewrite set: which members of it fire depends
-- on the monomial, so some are unused in each individual proof. This is the arrangement of
-- `HJO/Shuffle/SweepStageWordTwoThreeTwoValue.lean`, and its linter exemption too.
set_option linter.unusedSimpArgs false

namespace HJO.Sweep

open HJO.Sym HJO.Mellit

variable {L : Type*} [Field L] [Algebra ℚ L] {q u : L}

/-! ### `z_1` on the two monomials of the kernel witness

`HJO.Sweep.levelKernelOne` is `F_0 = Ce_1 + qy_1`, whose two monomials have `y_1`-degrees `0` and
`1`. Both are below the six degrees
`HJO/Shuffle/SweepStageWordTwoThreeTwoValue.lean` tabulates, so the two values are new; as
there, the bracket of `HJO.Sweep.zopOneStar_one_auxVar_pow_mul_C` is divisible by `1 - q` and the
answer carries a bare `q`. -/

/-- **`z_1(Ce_1) = q(1-q)u·y_1`.** The `y_1`-degree-`0` case of
`HJO.Sweep.zopOneStar_one_auxVar_pow_mul_C`: the two branches are `d^*_+(C(B_0e_1))` and
`B_0(d^*_+(Ce_1))` coefficientwise, with `B_0e_1 = qe_1` (`HJO.Sym.bop_zero_elemSymm_one'`) and
`B_01 = 1`, so the `Ce_1` terms cancel and what survives is the displacement's single letter
`(q-1)uy_1` seen once with the factor `q` and once without.

`q ≠ 1`: the `q/(1-q)` of `HJO.Sweep.zop`, cancelled here against the bracket's factor `1 - q`. -/
theorem zopOneStar_one_C_elemSymm_one (hq1 : q ≠ 1) :
    zopOneStar q u 1 (MvPolynomial.C (elemSymm L 1) : Total L)
      = q • (((1 - q) * u) • ((auxVar 1 : Total L) ^ 1 * MvPolynomial.C (1 : Lambda L))) := by
  have h1q : (1 : L) - q ≠ 0 := sub_ne_zero.2 (Ne.symm hq1)
  have b01 : Bop q ((0 : ℕ) : ℤ) (1 : Lambda L) = 1 := by
    rw [bop_natCast_one]; simp [elemSymm_zero]
  have hbr : dplusStar q u 0 (MvPolynomial.C (Bop q ((0 : ℕ) : ℤ) (elemSymm L 1)))
        - bopExt q ((0 : ℕ) : ℤ) (dplusStar q u 0 (MvPolynomial.C (elemSymm L 1) : Total L))
      = (1 - q) • (((1 - q) * u) • ((auxVar 1 : Total L) ^ 1
          * MvPolynomial.C (1 : Lambda L))) := by
    rw [dplusStar_C_elemSymm_one_expand, map_add, bopExt_C, bopExt_smul_auxVar_pow_mul_C,
      bop_zero_elemSymm_one', b01]
    simp only [map_add, map_sub, map_neg, C_smul_total, map_smul, dplusStar_C_mul,
      dplusStar_C_elemSymm_one]
    simp only [starLetter, smul_eq_scal_mul, scal_mul, scal_sub, scal_one, scal_pow,
      MvPolynomial.smul_eq_C_mul, scal, map_add, map_sub, map_neg, map_mul, map_one, map_pow,
      map_ofNat]
    ring
  conv_lhs => rw [show (MvPolynomial.C (elemSymm L 1) : Total L)
    = (auxVar 1 : Total L) ^ 0 * MvPolynomial.C (elemSymm L 1) from by rw [pow_zero, one_mul]]
  rw [zopOneStar_one_auxVar_pow_mul_C, hbr, smul_smul,
    show q / (1 - q) * (1 - q) = q from by field_simp]

/-- **`z_1(y_1) = qu·y_1`.** The `y_1`-degree-`1` case: `d^*_+` fixes the vacuum
(`HJO.Sweep.dplusStar_C_one`), so the second branch is the constant `C(B_11) = -Ce_1`, the first is
`d^*_+(C(-e_1))`, and the difference is the displacement's letter alone.

`q ≠ 1`: the `q/(1-q)` of `HJO.Sweep.zop`, against the bracket's factor `1 - q`. -/
theorem zopOneStar_one_auxVar_mul_C_one (hq1 : q ≠ 1) :
    zopOneStar q u 1 ((auxVar 1 : Total L) ^ 1 * MvPolynomial.C (1 : Lambda L))
      = q • (u • ((auxVar 1 : Total L) ^ 1 * MvPolynomial.C (1 : Lambda L))) := by
  have h1q : (1 : L) - q ≠ 0 := sub_ne_zero.2 (Ne.symm hq1)
  have b11 : Bop q ((1 : ℕ) : ℤ) (1 : Lambda L) = -elemSymm L 1 := by
    rw [bop_natCast_one]; simp
  have hbr : dplusStar q u 0 (MvPolynomial.C (Bop q ((1 : ℕ) : ℤ) (1 : Lambda L)))
        - bopExt q ((1 : ℕ) : ℤ) (dplusStar q u 0 (MvPolynomial.C (1 : Lambda L) : Total L))
      = (1 - q) • (u • ((auxVar 1 : Total L) ^ 1 * MvPolynomial.C (1 : Lambda L))) := by
    rw [dplusStar_C_one, bopExt_C, b11]
    simp only [map_neg, dplusStar_C_elemSymm_one]
    simp only [starLetter, smul_eq_scal_mul, scal_mul, scal_sub, scal_one, scal_pow,
      MvPolynomial.smul_eq_C_mul, scal, map_add, map_sub, map_neg, map_mul, map_one, map_pow,
      map_ofNat]
    ring
  rw [zopOneStar_one_auxVar_pow_mul_C, hbr, smul_smul,
    show q / (1 - q) * (1 - q) = q from by field_simp]

/-- **`z_1(F_0) = qu·y_1` on the kernel witness of `HJO.Sweep.levelKernelOne`.**

The two monomials contribute `q(1-q)u·y_1` and `q·qu·y_1`, whose sum is `qu·y_1`: the `q`-dependence
cancels exactly, and the whole of `z_1` on this vector is one monomial. That collapse is why the
defect below is computable with three `z_1` values rather than the eleven the `A = 2` evaluation
needed.

`q ≠ 1`: the `q/(1-q)` of `HJO.Sweep.zop`, through the two values above. -/
theorem zopOneStar_one_levelKernelOne (hq1 : q ≠ 1) :
    zopOneStar q u 1 (levelKernelOne q : Total L) = (q * u) • (auxVar 1 : Total L) := by
  have hA : (auxVar 1 : Total L) = (auxVar 1 : Total L) ^ 1 * MvPolynomial.C (1 : Lambda L) := by
    rw [pow_one, MvPolynomial.C_1, mul_one]
  rw [levelKernelOne, map_add, map_smul, hA, zopOneStar_one_auxVar_mul_C_one hq1,
    zopOneStar_one_C_elemSymm_one hq1]
  simp only [starLetter, smul_eq_scal_mul, scal_mul, scal_sub, scal_one, scal_pow,
    MvPolynomial.smul_eq_C_mul, scal, map_add, map_sub, map_neg, map_mul, map_one, map_pow,
    map_ofNat]
  ring

/-! ### The replicated letter on the witness, and the defect -/

/-- **`Z^{(1)}_{2,3}(F_0) = quy_1^2Ce_2 - qu^2y_1^3Ce_1 + qu^3y_1^4`.**

`HJO.Sweep.replicatedTotal_two_three_zero_apply` is the letter as `(qu)^{-1}y_1z_1y_1^2z_1`. The
inner `z_1` gives `quy_1` (`HJO.Sweep.zopOneStar_one_levelKernelOne`), so the outer one meets
`quy_1^3`, a single monomial, and `HJO.Sweep.zopOneStar_one_auxVar_cube_mul_C_one` evaluates it; the
`qu` then cancels the `(qu)^{-1}` and the outer `y_1` raises each degree by one.

`q ≠ 0`, `u ≠ 0`: the `(qu)^{-1}` of `HJO.Sweep.slopeOperator`, cancelled here against the `qu`
the inner `z_1` produced — in a field `0⁻¹ = 0`, so at either the letter is the zero map.
`q ≠ 1`: the `q/(1-q)` of `HJO.Sweep.zop` in both `z_1` values. -/
theorem replicatedTotal_two_three_zero_levelKernelOne (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) :
    replicatedTotal q u 2 3 0 (levelKernelOne q)
      = (q * u) • ((auxVar 1 : Total L) ^ 2 * MvPolynomial.C (elemSymm L 2))
        + (-(q * u ^ 2)) • ((auxVar 1 : Total L) ^ 3 * MvPolynomial.C (elemSymm L 1))
        + (q * u ^ 3) • ((auxVar 1 : Total L) ^ 4 * MvPolynomial.C (1 : Lambda L)) := by
  have hqu : q * u ≠ 0 := mul_ne_zero hq0 hu0
  have hcube : (auxVar 1 : Total L) ^ 2 * (auxVar 1 : Total L) = (auxVar 1 : Total L) ^ 3 := by
    ring
  have h3 : (auxVar 1 : Total L) ^ 2 * ((q * u) • (auxVar 1 : Total L))
      = (q * u) • ((auxVar 1 : Total L) ^ 3 * MvPolynomial.C (1 : Lambda L)) := by
    rw [mul_smul_comm, hcube, MvPolynomial.C_1, mul_one]
  rw [replicatedTotal_two_three_zero_apply, zopOneStar_one_levelKernelOne hq1, h3, map_smul,
    zopOneStar_one_auxVar_cube_mul_C_one hq1, mul_smul_comm, smul_smul, inv_mul_cancel₀ hqu,
    one_smul]
  simp only [starLetter, smul_eq_scal_mul, scal_mul, scal_sub, scal_one, scal_pow,
    MvPolynomial.smul_eq_C_mul, scal, map_add, map_sub, map_neg, map_mul, map_one, map_pow,
    map_ofNat]
  ring

/-- **The defect:
`ct(d_-^{(1)}Z^{(1)}_{2,3}(F_0)) = qu[e_2^2 + (q+u-1)e_1e_3 + (q^2+qu-q+u^2-u)e_4]`.**

`HJO.Sweep.dminus_one_auxVar_pow_mul_C` reads `d_-^{(1)}` off each of the three monomials as
`HJO.Sym.Bop` at the `y_1`-degree, so the value is `quB_2(e_2) - qu^2B_3(e_1) + qu^3B_4(1)`, and the
three `B`-values are proved (`HJO.Sym.bop_two_elemSymm_two'`, `HJO.Sym.bop_three_elemSymm_one`,
`HJO.Sym.bop_four_one`). The `e_2^2` coefficient is `qu` undeformed, which is what makes the defect
nonzero at every parameter inside the three exclusions.

`q ≠ 0`, `u ≠ 0`, `q ≠ 1`: exactly
`HJO.Sweep.replicatedTotal_two_three_zero_levelKernelOne`'s, and at each of the three the defect
genuinely is `0`. -/
theorem constantCoeff_dminus_one_replicatedTotal_levelKernelOne (hq0 : q ≠ 0) (hu0 : u ≠ 0)
    (hq1 : q ≠ 1) :
    MvPolynomial.constantCoeff (dminus q 1 (replicatedTotal q u 2 3 0 (levelKernelOne q)))
      = (q * u) • (elemSymm L 2 * elemSymm L 2
          + (q + u - 1) • (elemSymm L 1 * elemSymm L 3)
          + (q ^ 2 + q * u - q + u ^ 2 - u) • elemSymm L 4) := by
  rw [replicatedTotal_two_three_zero_levelKernelOne hq0 hu0 hq1]
  simp only [map_add, map_smul, dminus_one_auxVar_pow_mul_C, constantCoeff_smul,
    MvPolynomial.constantCoeff_C, bop_two_elemSymm_two', bop_three_elemSymm_one, bop_four_one]
  simp only [MvPolynomial.smul_eq_C_mul, map_add, map_sub, map_neg, map_mul, map_one, map_pow,
    map_ofNat]
  ring

/-- **The defect is nonzero.** `e_2^2`, `e_1e_3` and `e_4` are linearly independent
(`HJO.Sym.elemSymm_two_sq_add_smul_ne_zero`, proved by pulling back along the injective substitution
`p_k ↦ e_k`), so the bracket is nonzero at every `q` and `u`, and the prefactor `qu` is nonzero
exactly when `q ≠ 0` and `u ≠ 0`.

So this is not a numeric separation at one point: the defect is nonzero on the whole of the
parameter space minus the three exclusions. -/
theorem constantCoeff_dminus_one_replicatedTotal_levelKernelOne_ne_zero (hq0 : q ≠ 0) (hu0 : u ≠ 0)
    (hq1 : q ≠ 1) :
    MvPolynomial.constantCoeff (dminus q 1 (replicatedTotal q u 2 3 0 (levelKernelOne q)))
      ≠ (0 : Lambda L) := by
  rw [constantCoeff_dminus_one_replicatedTotal_levelKernelOne hq0 hu0 hq1]
  exact smul_ne_zero (mul_ne_zero hq0 hu0) (elemSymm_two_sq_add_smul_ne_zero _ _)

/-! ### The refutation -/

/-- **`ct ∘ d_-^{(1)} ∘ Z^{(1)}_{2,3}` does NOT factor through `ct ∘ d_-^{(1)}` on `V_1`**, at
`(a,b) = (2,3)` — a point inside the range `1 < a < b` that the `hlhs` binder of
`HJO.Mellit.shuffle_of_lhs_and_induction` quantifies over.

The consequence for the one-part family: `HJO.Mellit.stageWordTotal_singleton_succ` makes the sweep
side's recursion `G_{A+1} = Z^{(1)}_{2,3}(G_A)`, and the clause reads only
`S_A = ct(d_-^{(1)}G_A)`. A step from `S_A` to `S_{A+1}` would be such a `φ`. There is none, so an
induction on `A` must carry the **vector** `G_A`, which is what the decision procedure of
`HJO.Mellit.lhsAt_two_three_singleton_iff_bop` does one `A` at a time.

The witness is `F_0 = Ce_1 + qy_1` (`HJO.Sweep.levelKernelOne`), the same vector the level-raising
refutation uses: it lies in `V_1`, `ct(d_-^{(1)}F_0) = 0`
(`HJO.Sweep.constantCoeff_lowerRun_one_levelKernelOne`), and
`HJO.Sweep.constantCoeff_dminus_one_replicatedTotal_levelKernelOne_ne_zero` says the composite does
not kill it — while linearity forces `φ(0) = 0` through `F = 0`.

**What this does not say.** A `φ` must be defined on all of `Λ`, and `F_0` is not a stage word: this
refutes reading a value recursion **off the step**, not the existence of some value recursion for
another reason. That is the same scope as `HJO.Sym.ladderTwoThree_apply_one_not_determined` on the
creation side of the same clause. It is also independent of
`HJO.Sweep.not_exists_factorization_two_three`, which refutes the *level-raising* factorization: the
operators are different — the replicated letter of `HJO.Mellit.replicatedLetter` at level `0` here,
the stage of `HJO.Mellit.stage` at level `1` there — and neither statement implies the other.

`q ≠ 0`, `u ≠ 0` and `q ≠ 1`, and no others: at `q = 0` and `u = 0` the letter `(qu)^{-1}z_1` of
`HJO.Sweep.slopeOperator` is the zero map and at `q = 1` the scalar `q/(1-q)` of `HJO.Sweep.zop`
is `0`, so there the composite kills `F_0` too and this witness refutes nothing — the exclusions are
the inverse-becomes-zero hazard and not an artefact of the answer's shape. -/
theorem not_exists_factorization_replicated_two_three (hq0 : q ≠ 0) (hu0 : u ≠ 0) (hq1 : q ≠ 1) :
    ¬ ∃ φ : Lambda L → Lambda L, ∀ F ∈ piece L 1,
      MvPolynomial.constantCoeff (dminus q 1 (replicatedTotal q u 2 3 0 F))
        = φ (MvPolynomial.constantCoeff (dminus q 1 F)) := by
  rintro ⟨φ, hφ⟩
  have hrun : Mellit.lowerRun q 1 (levelKernelOne q) = dminus q 1 (levelKernelOne q) := by
    rw [Mellit.lowerRun, Mellit.lowerRun, Module.End.mul_apply, Module.End.one_apply]
  have hzero : φ (0 : Lambda L) = 0 := by
    have h := hφ 0 (zero_mem _)
    simp only [map_zero] at h
    exact h.symm
  have hF := hφ (levelKernelOne q) (levelKernelOne_mem_piece q)
  rw [← hrun, constantCoeff_lowerRun_one_levelKernelOne, hzero] at hF
  exact constantCoeff_dminus_one_replicatedTotal_levelKernelOne_ne_zero hq0 hu0 hq1 hF

/-! ### Consistency check: the two refutations' defects are proportional -/

/-- **The two defects are the same element of `Λ` up to a scalar:**

  `(q-1)·ct(d_-^{(1)}Z^{(1)}_{2,3}F_0) = q·ct(d_-^{(1)}d_-^{(2)}G_{2,1}F_0)`.

Both sides are a multiple of `e_2^2 + (q+u-1)e_1e_3 + (q^2+qu-q+u^2-u)e_4` — with prefactor `qu`
here and `u(q-1)` in `HJO.Sweep.constantCoeff_lowerRun_two_stageTotal_levelKernelOne_two_three` —
and the two routes to that bracket share no lemma. This one applies
`HJO.Sweep.zopOneStar_one_auxVar_pow_mul_C` twice at the level `1` and projects with
`HJO.Sweep.dminus_one_auxVar_pow_mul_C`; that one runs the train `T_1^{-1}`, the grading-one defect
`HJO.Sweep.zDefect` and seven compositions `B_jB_m` at the level `2`. So the agreement is a check on
both computations, and a sign or a normalising scalar lost on either would break it.

Genericity: `q ≠ 0`, `u ≠ 0`, `q ≠ 1`, which are both sides' own. -/
theorem smul_constantCoeff_dminus_one_replicated_eq_smul_lowerRun_two_stageTotal (hq0 : q ≠ 0)
    (hu0 : u ≠ 0) (hq1 : q ≠ 1) :
    (q - 1) • MvPolynomial.constantCoeff
        (dminus q 1 (replicatedTotal q u 2 3 0 (levelKernelOne q)))
      = q • MvPolynomial.constantCoeff
          (Mellit.lowerRun q 2 (Mellit.stageTotal q u 2 3 1 1 (levelKernelOne q))) := by
  rw [constantCoeff_dminus_one_replicatedTotal_levelKernelOne hq0 hu0 hq1,
    constantCoeff_lowerRun_two_stageTotal_levelKernelOne_two_three hq0 hu0 hq1, smul_smul,
    smul_smul]
  congr 1
  ring

end HJO.Sweep

namespace HJO.Mellit

open HJO.Sym HJO.Sweep Finset

variable {L : Type*} [Field L] [Algebra ℚ L] {q u : L}

/-! ### The creation side's recursion, with its inputs named -/

/-- **`(1 - v^A)Θ(h_A)(1) = (v-1)v^{A-1}∑_{s=1}^{A}Θ(h_{A-s}U_s)(1)`, `v = qu`** — the recursion of
`HJO.Mellit.theta_completeHomog_apply_one_smul_eq_sum_qop` with the slope operator absorbed back
into `Θ`: `Q_{2s,3s} = Θ(U_s)` by `HJO.Sym.IsSlopeHom` and `Θ` is multiplicative, so
`Θ(h_{A-s})(Q_{2s,3s}(1)) = Θ(h_{A-s}U_s)(1)`.

**This is a change of vocabulary, not a reduction.** It is one rewrite by `map_mul` in each
direction, the iff holds with no hypotheses beyond the two already present, and nothing is
transported. Its only purpose is to name the quantifier an induction on `A` would have to discharge:
the recursion's inputs are the values of the vacuum map `f ↦ Θ(f)(1)` at the **products**
`h_{A-s}U_s`, not at the generators `h_A` the one-part clauses speak about. Since `h_A` is not a
polynomial in `U_1, …, U_{A-1}` (`HJO.Sym.completeHomog_not_mem_adjoin_axisGen`) those products are
genuinely outside the family, and the vacuum map is linear but not multiplicative, so the values
`Θ(h_j)(1)` for `j < A` do not determine them.

Together with `HJO.Sweep.not_exists_factorization_replicated_two_three` this is the shape of the
obstruction to the whole one-part family: the sweep side's recursion is internal to the family but
does not descend to its values, and the creation side's descends to values but not of the family.

Genericity: `qu ≠ 0`, `qu ≠ 1`, the normalising scalar `v/(v-1)` of `HJO.Sym.axisGen`; at `qu = 1`
every `U_k` is `0` and `Θ(h_A)` is not determined. -/
theorem theta_completeHomog_apply_one_smul_eq_sum_theta_mul
    {Θ : Lambda L →ₐ[L] Module.End L (Lambda L)}
    (hΘ : IsSlopeHom 2 3 q u Θ) (hv0 : q * u ≠ 0) (hv1 : q * u ≠ 1) (A : ℕ) :
    (1 - (q * u) ^ A) • Θ (completeHomog L A) 1
      = ((q * u - 1) * (q * u) ^ (A - 1)) •
          ∑ s ∈ range A,
            Θ (completeHomog L (A - (s + 1)) * axisGen (q * u) (s + 1)) 1 := by
  rw [theta_completeHomog_apply_one_smul_eq_sum_qop hΘ hv0 hv1 A]
  refine congrArg _ (Finset.sum_congr rfl fun s _ => ?_)
  rw [map_mul, Module.End.mul_apply, hΘ (s + 1) (Nat.succ_pos s)]

end HJO.Mellit

end
